### ISSUE TITLE
Support for "completion mode"?

### ISSUE THREAD

**Issue by fsouza** [hrsh7th/nvim-cmp#100]
I've been hacking my way around different completion plugins to support my approach for completion, and I realize this may be something others may be interested in, I don't know. Basically, I use completion in manual mode, until I don't lol The idea is that whenever I start completion, I want to enable autocomplete/as you type completion, then disable it again when I exit insert mode. So it's basically a transition from normal mode, to insert mode and then to insert mode with autocomplete enabled (which I'm calling "completion mode" here).

I've recently migrated to nvim-cmp and tried a similar approach to what I did in nvim-compe (set `autocomplete` to `true` when starting completion), but that doesn't seem to work, even after I set autocompl. Before figuring out how to make it work for myself, I wanted to check if this is something you'd be interested in supporting more directly.

My previous approach with nvim-compe: https://github.com/fsouza/dotfiles/blob/a0f215977b4d480d6d2fdcdfaeac092a95db9fcb/nvim/lua/fsouza/lsp/completion.lua#L43-L52

Current one with nvim-cmp: https://github.com/fsouza/dotfiles/blob/13f57c03d4637bd574adda6d62c135c52ac1a3e0/nvim/lua/fsouza/lsp/completion.lua#L50-L60

I did some preliminary investigation and noticed that the "issue" is that the context isn't considered changed [here](https://github.com/hrsh7th/nvim-cmp/blob/405581e7405da53924fd9723e3e42411b66d545d/lua/cmp/core.lua#L134-L146), so I get the following logs if I enable debug mode:

```
>>> TextChanged
ctx: `^Ic`
unchanged
```

Again, feel free to ignore this if you don't feel like this is a feature that makes sense, I can figure something out :D

**Comment by hrsh7th** [comment]
@fsouza I've fixed the issue. I think your expected behavior can realize by the following config.

```lua
autocmd vimrc InsertEnter * call s:on_insert_enter()
function! s:on_insert_enter() abort
lua <<EOF
local cmp = require'cmp'
cmp.setup.buffer {
  completion = {
    autocomplete = false,
  },
  mapping = {
    ['<C-Space>'] = function(fallback)
      cmp.setup.buffer {
        completion = {
          autocomplete = { cmp.TriggerEvent.TextChanged }
        },
        mapping = {
          ['<C-Space>'] = cmp.mapping.complete()
        }
      }
      print(vim.inspect(require('cmp.config').get().completion))
      cmp.complete()
    end
  }
}
EOF
endfunction

```

**Comment by fsouza** [comment]
Thank you very much for the very quick fix!
