### ISSUE TITLE
documentation is deprecated

### ISSUE THREAD

**Issue by anteg** [hrsh7th/nvim-cmp#1000]
Hi

When trying to start nvim it says
`[nvim-cmp] documentation is deprecated 
[nvim-cmp] use window.documentation = cmp.config.window.bordered()`

I have found that I should edit either cmp config file or cmp.config and the closest i have found is **config.lua** in cmp. And the section that is supposed to be edited should look something like 

```
documentation = { 
...
}
```

and it should be edited to
```
 window = {
    documentation = {
        ....
    }
}
```

but the closest thing to this I can find in **config.lua** is

```
if c.documentation ~= nil then
    vim.api.nvim_echo({
      { '[nvim-cmp] ', 'Normal' },
      { 'documentation', 'WarningMsg' },
      { ' is deprecated.\n', 'Normal' },
      { '[nvim-cmp] Please use ', 'Normal' },
      { 'window.documentation = cmp.config.window.bordered()', 'WarningMsg' },
      { ' instead.', 'Normal' },
    }, true, {})
    c.window = c.window or {}
    c.window.documentation = c.documentation
  end
```

But also found the **default.lua** file that has the most similar to the section I should alter but have not been able to do so succesfully

```
 window = {
      completion = {
        border = { '', '', '', '', '', '', '', '' },
        winhighlight = 'Normal:Pmenu,FloatBorder:Pmenu,CursorLine:PmenuSel,Search:None',
      },
      documentation = {
        max_height = math.floor(WIDE_HEIGHT * (WIDE_HEIGHT / vim.o.lines)),
        max_width = math.floor((WIDE_HEIGHT * 2) * (vim.o.columns / (WIDE_HEIGHT * 2 * 16 / 9))),
        border = { '', '', '', ' ', '', '', '', ' ' },
        winhighlight = 'FloatBorder:NormalFloat',
     }

```
     
Could someone please help me with this issue since I am not able to get this right

Thanks

**Comment by wookayin** [comment]
You should show your config and probably there is something wrong with your config. Don't have `documentation = ...` directly under `cmp.setup {}`

**Comment by anteg** [comment]
Thanks for the answer. Sorry for not following the template on my first post. I have now posted a new issue in the right maner.

Best regards
