### ISSUE TITLE
attempt to call field 'unpack' (a nil value)

### ISSUE THREAD

**Issue by paulhersch** [hrsh7th/nvim-cmp#1017]
Hi!
Right now when i use Tab completion and just want to use tab to create big spaces, i get the error:
`E5108: Error executing lua [string ":lua"]:84: attempt to call field 'unpack' (a nil value)`

I dont exactly know where the function is that causes this, but here is my traceback:
```
stack traceback:                                                                                                                         
        [string ":lua"]:84: in function 'has_words_before'                                                                               
        [string ":lua"]:105: in function 'on_keymap'                                                                                     
        /home/paul/.vim/plugged/nvim-cmp/lua/cmp/core.lua:146: in function 'callback'                                                    
        /home/paul/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:118: in function </home/paul/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap
.lua:112>                                                                                                                                
        /home/paul/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:248: in function </home/paul/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap
.lua:247>
```
I used the snippet provided by the wiki:
```lua
...
      ["<Tab>"] = cmp.mapping(function(fallback)
	      if cmp.visible() then
	        cmp.select_next_item()
	      elseif luasnip.expand_or_jumpable() then
	        luasnip.expand_or_jump()
	      elseif has_words_before() then
	        cmp.complete()
	      else
	        fallback()
	      end
      end, { "i", "s" }),
...
```
Any ideas how i can fix this?

**Comment by adastx** [comment]
After a bit of research, this seems to be some Lua deprecation issue related to `unpack()` being changed to `table.unpack()`

This is used in the `local has_words_before = function() ...`

My workaround for now is to add the following to the top of my cmp config:

    if not table.unpack then
        table.unpack = unpack
    end

**Comment by smjonas** [comment]
@adastx did you perhaps mean
```lua
if not unpack then
  unpack = table.unpack
end
```
?

**Comment by adastx** [comment]
No. For me the old `unpack` works and the new `table.unpack` results in the error OP is getting.

**Comment by paulhersch** [comment]
thanks for the help @adastx !
I was confused because i knew about the deprecation thing of `table.unpack`, but wasn't sure why the error would occur as the lua that is used to build neovims lua deps for my distro is versioned at 5.2 (NixOS uses luaPackages.*, which is at version 5.2.4) and should have both functions...
Do you know how one could use a more recent lua version to build neovim? Or is the dependency on 5.1 too big?

(closing issue because the problem itself is solved)

**Comment by adastx** [comment]
> Do you know how one could use a more recent lua version to build neovim? Or is the dependency on 5.1 too big?

I would assume this isn't possible at the moment, so you probably just have to wait for future neovim updates.

**Comment by aktau** [comment]
I don't think there will be, as LuaJIT only supports 5.1 (with some optional 5.2 extensions). Plugins thus write to 5.1. I think 5.2 (and above) introduce some backwards incompatible changes/
