### ISSUE TITLE
feature request: interpolation for snipmate snippets

### ISSUE THREAD

**Issue by voyeg3r** [hrsh7th/nvim-cmp#1020]
snipmate.vim has the following feature:

```
snippet date
 	`system("date +%Y-%m-%d")`
```

This means that when I type "date" the trigger will get the date from the system. Is it possible to have on nvim-cmp?

Here is the documentation for snipmate.vim:
https://github.com/msanders/snipmate.vim/blob/master/doc/snipMate.txt

**Comment by smjonas** [comment]
This is already supported but depends on the snippet engine you are using. E.g. UltiSnips (with cmp-nvim-ultisnips) can handle Vim script code but LuaSnip does not currently. If you don't use UltiSnips, another possibility is to convert the snippets to vsnip format and use vsnip as your snippet engine. For that, have a look at my plugin [snippet-converter.nvim](https://github.com/smjonas/snippet-converter.nvim)😄

**Comment by hrsh7th** [comment]
Yes. It's depending on to the your snippet engine. So nvim-cmp does nothing for this. Sorry.
