### ISSUE TITLE
Segmentation fault when writing "// 1." in c like languages

### ISSUE THREAD

**Issue by nikolightsaber** [hrsh7th/nvim-cmp#1021]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug "hrsh7th/cmp-path"
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "buffer" },
    { name = "path" },
  },
}
EOF

```

### Description

When I go into a c like file and start writing the comment `//1.` i get a segmentation fault

I'm pretty sure it is the dot that is doing it.

I feel it is an issue with cmp-path  in combination with another cmp source like buffer. 

![Screenshot from 2022-06-02 20-59-50](https://user-images.githubusercontent.com/103886134/171713453-b48c2798-11b8-43a5-898e-1672a4badded.png) 

I use the lastest neovim from master 0.8-dev (commit: e6652821bd32e4ff8d62a0b67fc2041a5f41e252)

Do I need to make an issue in the main neovim repo. This seems serious.

### Steps to reproduce

Go into any c like file and start wring `// 1.` and the issue should happen.

With the config above of course.

### Expected behavior

No segmentation fault.

### Actual behavior

Segmentation fault

**Comment by nikolightsaber** [comment]
Hi thanks for the comment ! 

I've updated my neovim this morning and indeed the problem seems fixed for me.
https://github.com/neovim/neovim/pull/18834. seems to have don the job

I'll close the issue since it is fixed for me 

if it is not fixed for you feel free to re-open

**Comment by smjonas** [comment]
Fixed for me as well after upgrading to latest master :+1:
