### ISSUE TITLE
New features: add the source of vim events

### ISSUE THREAD

**Issue by XXiaoA** [hrsh7th/nvim-cmp#1024]
I wrote a simple [plugin](https://github.com/XXiaoA/cmp-events)  to add the source of vim events.
May you add it into the [wiki](https://github.com/hrsh7th/nvim-cmp/wiki/List-of-sources#miscellaneous)? Although it's really a simple plugin.
Or maybe I should create a PR?

**Comment by smjonas** [comment]
Feel free to add it to the list of sources in the Wiki!

**Comment by XXiaoA** [comment]
> Feel free to add it to the list of sources in the Wiki!

Finished it. thanks
