### ISSUE TITLE
Search with wildmenu does not work

### ISSUE THREAD

**Issue by rockyzhang24** [hrsh7th/nvim-cmp#1027]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Just add this piece of code into the minimal config, making cmp support search with wildmenu. 

```vim
lua<<EOD
cmp.setup.cmdline('/', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' },
  },
  view = {
    entries = { name = 'wildmenu', separator = ' · ' }
  },
})
EOF
```

### Description

After typing `/` to search, `<TAB>` works well to cycle through the candidates, however, the searched word after `/` won't be autocompleted. See the demo below please.

https://user-images.githubusercontent.com/11582667/172446222-b8b4ed91-7306-4f8d-9998-cde15302cac5.mov

Thank you.

### Steps to reproduce

1. Open any file using the minimal config
2. Search something
3. Press <Tab> and <S-Tab> to cycle through the candidates

### Expected behavior

The word after `/` should be auto-completed by the candidates.

### Actual behavior

The searched word after `/` won't be autocompleted

### Additional context
System: macOS 12.4
Nvim: build via the latest commit

**Comment by tzachar** [comment]
This is not a bug, but the default mapping you are using.
Try this instead:
```lua
mapping = {                                                                                                              
  ['<C-p>'] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }), { 'i', 'c' }),         
  ['<C-d>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),                                                    
  ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),                                                     
  ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),                                                     
  ['<C-e>'] = cmp.mapping(cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true }), { 'i', 'c' }), 
  ['<CR>'] = cmp.mapping.confirm({                                                                                       
    behavior = cmp.ConfirmBehavior.Replace,                                                                              
    select = false,                                                                                                      
  }),                                                                                                                    
  ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }), { 'i', 'c' }),         
  ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }), { 'i', 'c' }),       
},                                                                                                                       
```

**Comment by rockyzhang24** [comment]
@tzachar Thanks anyway. But you got me wrong. I was not saying the mappings do not work, but they work well and just cannot feed the selected item to the search. I think this should be a bug. The default mapping already maps TAB and S-TAB to select the next item in cmdline, see this please https://github.com/hrsh7th/nvim-cmp/blob/f51dc68e1bb170fc49c2d7e13eb45e5ec83f5ee9/lua/cmp/config/mapping.lua#L47-L68

For both insert and cmdline, the default mappings look perfect for me, so I don't need to remap them. In insert, all default mappings work well. In cmdline, TAB and S-TAB also work well, i.e., they can select the next/prev item as expected, however, the selected item cannot be fed to the search `/`.

**Comment by tzachar** [comment]
cmp.select_next_item() needs to get `behavior = cmp.SelectBehavior.Insert` as a parameter. Its 8s mapped like that in normal mode, but not in dline mode.

**Comment by rockyzhang24** [comment]
Wow, nice! I totally understand. It definitely confused and bothered me a lot. Really appreciate your explanation. I will close this.
