### ISSUE TITLE
Mapping Esc for cmdline doesn't work as expected

### ISSUE THREAD

**Issue by shibotto** [hrsh7th/nvim-cmp#1033]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<Esc>'] = { c = cmp.mapping.close() },
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When mapping `<Esc>` like this, it sends whatever currently is in the cmdline just as if you pressed Enter.

### Steps to reproduce

Start writing something in the cmdline (wither with `:` or `/`) then press `<Esc>`.

### Expected behavior

Close the completion menu if visible, than do nothing else.

### Actual behavior

See description.

### Additional context

Quickly bisecting showed that it started here https://github.com/hrsh7th/nvim-cmp/commit/801a9f98bbae14135be3a04515b9350b145ce25b .

**Comment by scardenasb** [comment]
I have this mappings, <Esc> function abort(), try it instead of close()

![image](https://user-images.githubusercontent.com/84429399/174220804-12c1861e-8f29-4b6d-b036-f55c8dedb2c1.png)

**Comment by hrsh7th** [comment]
Hm... This is caused by vim's strange cmdline mapping behavior.

The following minimal reproduction is shows the same error.

1. `nvim --clean`
2. `:cnoremap foo <Esc>`
3. `:set afoo`

**Comment by hrsh7th** [comment]
I think this issue is hard to fix.
For example, if the user hope to define the mapping such as `cnoremap <C-o> <Esc>` for closing cmdline with `<C-o>`, the mapping will fail via same reason.

**Comment by hrsh7th** [comment]
I guess vim treats the `<Esc>` mapping as as `<C-u><Esc>` in cmdline.
So you can feed it manually.

```
    ['<Esc>'] = {
      c = function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-u><Esc>', true, true, true), 'n', true)
      end
    },
```

**Comment by shibotto** [comment]
OK, it took me a while to sorta figure this out. Reading the [docs](https://neovim.io/doc/user/cmdline.html#c_Esc), it appears that `<Esc>`  executes when in macros or when 'x' is in 'cpoptions'. From your commit message, i believe this is the former scenario.  
Right below however there is `<C-c>`, which is said to "quit command-line without executing", ever. Nothing against `<C-u><Esc>`, but if it doesn't break anything this just feels "more right" 😃

So, I realize my original post is not very clear about what I'm expecting, so I'll rephrase: when I press `<Esc>` in the cmdline, I want it to close the cmp menu if it's visible, retaining exactly what is in the cmdline, including eventual cmp completions (no `.abort()` then). If the cmp menu is not visible, quit the cmdline.

Following your suggestion, this is what I came up with:

```lua
['<Esc>'] = cmp.mapping({
  c = function()
    if cmp.visible() then
      cmp.close()
    else
      vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-c>', true, true, true), 'n', true)
    end
  end
}),
```

<details><summary>Full config example</summary>

```lua
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
"Plug 'hrsh7th/nvim-cmp', { 'commit': '27970d8a1c99cd6ddea2709beda52d8e9336228b' }
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-cmdline'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<Esc>'] = cmp.mapping({
      c = function()
        if cmp.visible() then
          cmp.close()
        else
          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-c>', true, true, true), 'n', true)
        end
      end
    }),
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}

cmp.setup.cmdline(":", {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = "cmdline" },
    { name = "buffer" },
  }
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

</details>

I'm closing the issue since this solution is acceptable to me. If I'm overlooking something that may explode my neovim, please let me know 🙂

**Comment by icholy** [comment]
@hrsh7th would you consider adding a build-in mapping like `cmd.mapping.abortc()` which contains:

``` lua
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-c>', true, true, true), 'n', true)
```
