### ISSUE TITLE
Ignore certain words/patterns

### ISSUE THREAD

**Issue by mway** [hrsh7th/nvim-cmp#1036]
Thanks for the great plugins!

One issue that's been frustrating a lot lately is that there are unwanted completions. For a trivial example, in Go, if I'm writing a function like the following:

```go
func doSomething() error {
  return nil
}
```

after I've typed `return ni`, suggestions begin popping up (I use `keyword_length=2` and `<CR>` to confirm, fyi), but the very last one is `nil`. Instead of `nil` being at the top (which I'd expect because it's the closest match), the first suggestion might be `nilerr`, which is a package that's (probably) a very transitive dependency that I don't use in my project, and so it'll be selected when I hit return (I type fast), and gopls will add an import for it as well, which I then need to undo.

Anyway, I know I can use something like:

```lua
cmp.mapping.confirm({ select = false })
```

so that I'd need to select it explicitly, but what I'd really like is just to ignore `nilerr` (and various others) completely as an option. I considered adding a function handler for the `<CR>` bind, but they'd still show in the completion list, and I'd have to keep typing or navigate through them to get what I actually wanted in the first place.

Is this something that's already possible? If not, would you consider adding support for it?

Happy to provide any other info you'd like!

**Comment by hrsh7th** [comment]
The entry_filter option can be used now.
