### ISSUE TITLE
Complete without snippet expansion

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/nvim-cmp#1038]
I have a question.
Is it possible to confirm completion without snippet expansion by a custom shortcut (using `<C-CR>`, for example)?

I.e. when completing a function:
![изображение](https://user-images.githubusercontent.com/22453358/174055746-58936c39-aa8c-454c-9aa9-b79bc9d0338d.png)
Insert it like this: 
![изображение](https://user-images.githubusercontent.com/22453358/174055781-91c1e22a-8e50-48f9-ba4b-e774fc0980aa.png)
Instead of this:
![изображение](https://user-images.githubusercontent.com/22453358/174055811-7870cd53-2d8d-4acb-af55-74db0e23c59a.png)

Because I trying to pass a function into another function.

**Comment by hrsh7th** [comment]
I thought this feature was feasible with the current feature set, but the perfect solution seems difficult.

Therefore, it is necessary to add a function.
Note that this feature is a bit special.
nvim-cmp has carefully created the "text inserted when selecting an item", but in some cases it is not perfect.

_google translated_

**Comment by hrsh7th** [comment]
What I want to say is that nvim-cmp implements the text state after "expand" as the server intended, but the text state at the time of selection is not always perfect. ..

**Comment by Shatur** [comment]
As a workaround i press `Ctrl+n` - it inserts function name without substituting arguments. But it gets problematic when there is a single completion item or the item I need is preselected (via rust magic completion, for example). In this case I press `Ctrl+n` and then `Ctrl+p`. Not very convenient, but better then nothing.

**Comment by Shatur** [comment]
Maybe I can create a hacky workaround by sending `Ctrl+n` with `Ctrl+p` to insert in my configuration?

**Comment by hrsh7th** [comment]
Yes. `<C-n><C-p>` combo can be usable as workaround. But you have to write some codes.

**Comment by hrsh7th** [comment]
It's may work for you.

```
      ['<C-j>'] = function()
        local active = cmp.get_active_entry()
        if active then
          return
        end
        local next = '<Cmd>lua require("cmp").select_next_item()<CR>'
        local prev = '<Cmd>lua require("cmp").select_prev_item()<CR>'
        local close = '<Cmd>lua require("cmp").close()<CR>'
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(next .. prev .. close, true, true, true), 'n', true)
      end,
```

**Comment by Shatur** [comment]
> Could you help me with this a little bit? 

Thank you!

Can I make this work when an item was selected? It inserts messed text If I comment out the check for `active`.

**Comment by Shatur** [comment]
Example:
![изображение](https://user-images.githubusercontent.com/22453358/174450971-6955d6fc-6824-49dc-bc89-7f7f1a5987bd.png)
![изображение](https://user-images.githubusercontent.com/22453358/174450976-4884b856-1858-43f4-bd57-3e9089d6cdcf.png)

**Comment by hrsh7th** [comment]
Reluctantly, I needed vim.schedule to make it work.
The nvim-cmp mapping process needs to be refactored.
Anyway, I think the following implementation works.

```
      ['<C-j>'] = function()
        local active = cmp.get_active_entry()
        if active then
          return cmp.close()
        end
        local selected = cmp.get_selected_entry()
        if not selected then
          cmp.select_next_item()
        else
          cmp.select_next_item()
          cmp.select_prev_item()
        end
        vim.schedule(function()
          cmp.close()
        end)
      end,
```

**Comment by Shatur** [comment]
Hm... It inserts wrong item for me:

![изображение](https://user-images.githubusercontent.com/22453358/174451116-efd59058-767c-400e-a0c7-0f465e724d69.png)
![изображение](https://user-images.githubusercontent.com/22453358/174451117-1a833284-5021-4be1-a503-ae0ff14adaf3.png)

**Comment by Shatur** [comment]
@hrsh7th sorry for the ping, but I think I know why the solution doesn't work for me. `cmp.get_selected_entry()` for some reason returns `nil` even in this situation:

![изображение](https://user-images.githubusercontent.com/22453358/185759783-a0b85b1e-cc39-4ef0-96ec-1e9db2bbb077.png)

Do you have any idea why it happens?

**Comment by alexveden** [comment]
hrsh7th's solution also didn't work for me. Eventually I foud workaround, by remapping Up/Down keys by cmp.select_next_item() / cmp.select_prev_item() ( similar to C-n and C-p ) and pressing Escape keeps the signature without snippet.

```lua
 opts.mapping['<Down>'] = cmp.mapping(function(fallback)
                if cmp.visible() then
                    cmp.select_next_item()
                else
                    fallback()
                end
            end
            , {"i", "c"})
        opts.mapping['<Up>'] = cmp.mapping(function(fallback)
                if cmp.visible() then
                    cmp.select_prev_item()
                else
                    fallback()
                end
            end
            , {"i", "c"})

```

**Comment by xzbdmw** [comment]
> hrsh7th's solution also didn't work for me. Eventually I foud workaround, by remapping Up/Down keys by cmp.select_next_item() / cmp.select_prev_item() ( similar to C-n and C-p ) and pressing Escape keeps the signature without snippet.
> 
> ```lua
>  opts.mapping['<Down>'] = cmp.mapping(function(fallback)
>                 if cmp.visible() then
>                     cmp.select_next_item()
>                 else
>                     fallback()
>                 end
>             end
>             , {"i", "c"})
>         opts.mapping['<Up>'] = cmp.mapping(function(fallback)
>                 if cmp.visible() then
>                     cmp.select_prev_item()
>                 else
>                     fallback()
>                 end
>             end
>             , {"i", "c"})
> ```

what's the difference of type C-n C-p and esc as mentioned above?

**Comment by xzbdmw** [comment]
I think a workaround in snippet engine can help:
``lua
            snippet = {
                expand = function(args)
                    if not expand then
                        local function remove_bracket_contents(input)
                            local pattern = "^(.*)%b().*$"
                            local result = string.gsub(input, pattern, "%1")
                            return result
                        end
                        args.body = remove_bracket_contents(args.body)
                        expand = true
                    end
                    require("luasnip").lsp_expand(args.body)
                end,
            },
                ["<D-b>"] = cmp.mapping(function()
                    if cmp.visible then
                        expand = false
                        cmp.confirm()
                    end
                end),
```

**Comment by drowning-cat** [comment]
```lua
mapping = cmp.mapping.preset.insert {
  ['<CR>'] = function()
    cmp.select_next_item { behavior = cmp.SelectBehavior.Insert, count = 0 }
    cmp.close()
  end,
}
```

**Comment by drowning-cat** [comment]
```lua
mapping = cmp.mapping.preset.insert {
  ['<CR>'] = function(fallback)
    if cmp.visible() then
      cmp.select_next_item { behavior = cmp.SelectBehavior.Insert, count = 0 }
      cmp.abort()
    else
      fallback()
    end
  end,
}
```

**Comment by Shatur** [comment]
Thanks!
