### ISSUE TITLE
How to enable compeletion virtual text like README.md in nvim-cmp index page

### ISSUE THREAD

**Issue by MRVAX** [hrsh7th/nvim-cmp#1039]
i am wondering how to enable the virtual text in sample of readme.md's videos, i try to search "virtual" in help and wiki and seems it's not in there QAQ

**Comment by Shougo** [comment]
I think it is ghost text feature.

**Comment by MRVAX** [comment]
thank u!

**Comment by hrsh7th** [comment]
You can enable ghost text via this https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L584

:)
