### ISSUE TITLE
Keyboard interrupt

### ISSUE THREAD

**Issue by strash** [hrsh7th/nvim-cmp#1043]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

I got this error but I don't know how to reproduce it. This error just pops up sometimes and it's not the first time.

```lua
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/nvim-cmp/lua/cmp/utils/misc.lua:243: Keyboard interrupt
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/nvim-cmp/lua/cmp/utils/misc.lua:243: in function <...m/site/pack/packer/start/nvim-cmp/lua/cmp/utils/misc.lua:241>
```

### Steps to reproduce

Unknown

### Expected behavior

-

### Actual behavior

It just shows the error.

### Additional context

Here is [my config](https://github.com/strash/.dotfiles/tree/master/nvim/.config/nvim) if it helps.

**Comment by Shougo** [comment]
You have pressed C-c to leave insert mode.
You should not do it.
It breaks plugins.

**Comment by strash** [comment]
@Shougo didn't know about it. Well, looks like I'll have to bear with it

**Comment by Shougo** [comment]
```
						*i_CTRL-C*
CTRL-C		Quit insert mode, go back to Normal mode.  Do not check for
		abbreviations.  Does not trigger the |InsertLeave| autocommand
		event.
```

`C-c`  is emergency feature.  It is not just back to Normal mode.
It is similar with `C-c` interrupt in shell.

**Comment by strash** [comment]
@Shougo thanks for the clarification. Btw, since this is not a cmp problem, do I need to close this issue?

**Comment by Shougo** [comment]
Yes.  It should be closed.

**Comment by marwan38** [comment]
Oh, I came here looking for the same thing. That's good to know! I use it because it's easier then reaching for escape. Are there any alternatives?

**Comment by Shougo** [comment]
You can user other map to escape like this.

`inoremap <C-l> <Esc>`

I don't recommend for you to map `<C-c>` to `<Esc>`.
Because `<C-c>`map is only used in `Insert mode`.
