### ISSUE TITLE
How to disable insertion of text until the completion has been selected

### ISSUE THREAD

**Issue by saisasidhar** [hrsh7th/nvim-cmp#1050]
More of a question really, if the feature does not exist please consider this report as an enhancement request.

I tried looking in the documentation but to no avail. I wanted to disable insertion of text in the current line until the competition has been selected from the list.

**Comment by hrsh7th** [comment]
You can use the following mapping.

```lua
cmp.setup {
  ...
  mapping = {
    ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
  }
  ...
}
```

**Comment by saisasidhar** [comment]
Wonderful, Thank you very much.
