### ISSUE TITLE
Feature Request: Sort order changes when drop down vs drop up

### ISSUE THREAD

**Issue by jrwrigh** [hrsh7th/nvim-cmp#1052]
It'd be nice if there was an option to have the sorting change based on whether the completion menu is going up vs down relative to the cursor. My desired effect would be the matches with the highest score be closest to the cursor. Currently (from what I can tell). It looks like the sorting is fixed to one direction. 

For example, if the drop down is going up relative to the cursor, I get this completion:
![image](https://user-images.githubusercontent.com/20801821/176236701-fd6a20ca-45a7-449e-b298-27c4497301fd.png)

If the drop down is going down relative to the cursor position, I get this completion:
![image](https://user-images.githubusercontent.com/20801821/176236919-2da777a2-c25e-4501-8129-eac7ba6c3874.png)

Note it'd also be nice to have this change work for `cmdline` completions as well (that was the original motivation for making this request before I realized that my undesired behavior happened in the normal editor window as well).

**Comment by Shougo** [comment]
Please see this.

https://github.com/hrsh7th/nvim-cmp/issues/910

**Comment by jrwrigh** [comment]
The [solution in that post](https://github.com/hrsh7th/nvim-cmp/issues/910#issuecomment-1101040797) worked. Thanks!
