### ISSUE TITLE
Enable/disable options

### ISSUE THREAD

**Issue by mcchrish** [hrsh7th/nvim-cmp#106]
```lua
local cmp = require('cmp')
cmp.setup {
  enabled = true -- false if disabled initially
}
```

And the commands to enable/disable/toggle on demand:
```vim
:CmpEnable
:CmpDisable
:CmpToggle
```

**Comment by uga-rosa** [comment]
You can pseudo-turn it off by emptying the source, but is that not enough for your use?

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/131276742-29a54af2-dc8b-495a-8744-357922c48b65.png)

Yes. I will also need this feature so I can disable the plugin for some of filetype.

For compe, I can do this:
```lua
vim.api.nvim_command("autocmd FileType clap_input call compe#setup({ 'enabled': v:false }, 0)")
```

**Comment by hrsh7th** [comment]
This feature is low priority.

```lua
autocmd FileType clap_input lua require'cmp'.setup { autocomplete = false }
```

**Comment by ray-x** [comment]
For some reason, this trick (autocomplete = false) does not work for `cmp`. How to check if `autocomplete` is disabled?

**Comment by hrsh7th** [comment]
@ray-x Sorry. It the below config works? `autocmd FileType clap_input lua require'cmp'.setup.buffer { autocomplete = false }`

**Comment by hrsh7th** [comment]
New version uses `setup.buffer` instead of `setup`

**Comment by ray-x** [comment]
Still not work.
I run a quick test for current buffer (not necessary clap_input)
`lua require'cmp'.setup.buffer { autocomplete = false }` 
But autocomplete was not disabled.

**Comment by hrsh7th** [comment]
Please try it.
```lua
autocmd FileType clap_input lua require'cmp'.setup.buffer {
\   completion = {
\     autocomplete = false
\   }
\ }
```

**Comment by ray-x** [comment]
Yes. This one works.

**Comment by hrsh7th** [comment]
I've implemented `require('cmp').setup.buffer { enabled = false }`

**Comment by Thanatermesis** [comment]
@hrsh7th can you implement a toggle too? I'm adding a mapped key to toggle cmp between enabled and disabled

**Comment by Thanatermesis** [comment]
From another thread I found an example code that I tried to set on my mappings but didn't worked:

```lua
    ["<leader>tm"] = {
      function()
        if vim.b.cmp_enabled
          then require('cmp').setup.buffer { enabled = false }
          else require('cmp').setup.buffer { enabled = true }
        end
      end,

      "Menu suggestions (cmp) toggle",
    },
```

**Comment by bnse** [comment]
@Thanatermesis 
https://gist.github.com/bnse/a3eb5b9941e6af4582c5406b29d76e05

**Comment by Thanatermesis** [comment]
Thank you :)
