### ISSUE TITLE
cmp-buffer throws E5113 during loadup

### ISSUE THREAD

**Issue by mrghosti3** [hrsh7th/nvim-cmp#1063]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Minimal vim config:
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8
 
if &compatible
  set nocompatible
endif
 
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end
 
execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit
```

### Description

Throws the following error during launch (after plugin is installed using packer and reopening neovim instance)
```
Error detected while processing /home/vagrant/.local/share/nvim/site/pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:1: attempt to index a boolean value
stack traceback:
        ...pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:1: in main chunk
```

### Steps to reproduce

1. Open vim (happens in neovim 0.7.2 and 0.6.1).
2. Download/Install the plugins.
3. Relaunch neovim and get the error.

### Expected behavior

-

### Actual behavior

Throws error mentioned in the description.

### Additional context

OS: Ubuntu LTS 22.04 (Pop os 22.04 LTS)

Neovim:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457
```

plugins:
- wbthomason/packer.nvim
- nvim-lua/popup.nvim
- nvim-lua/plenary.nvim
- lunarvim/colorschemes
- hrsh7th/nvim-cmp
- hrsh7th/cmp-buffer

config based on: https://github.com/LunarVim/Neovim-from-scratch/tree/05-completion/lua/user

**Comment by mrghosti3** [comment]
Never mind this, apparently I had a script named exactly as module in a plugin. Sorry for the sillyness

**Comment by Fobo00** [comment]
Hey could you tell me what was the problem because I have the same error and i can't manage to find it

**Comment by mrghosti3** [comment]
Well for me it was namespace collission. My lua config file had the same name as one of the plugins, to which the solution was to move all my scripts under another folder to change the namespace.
