### ISSUE TITLE
Documentation highlights not consistent (and impossible to fix by highlighting all of the cmp highlight groups)

### ISSUE THREAD

**Issue by hrqmonteiro** [hrsh7th/nvim-cmp#1064]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

![Screenshot from 2022-07-03 22-39-50](https://user-images.githubusercontent.com/17055027/177147316-4540aeaa-5d3e-4b93-b8f4-783f3641bdc3.png)

Inconsistent cmp highlighting when opening documentation, and not of the `hi` groups fix it, i tried changing all of them.
As you can see, i have some parts that are with a darker background, and i want to find it and fix it.

I tried changing all of the highlight groups that start with `Cmp`:

![Screenshot from 2022-07-04 08-39-36](https://user-images.githubusercontent.com/17055027/177147393-7173a553-0dbe-42f4-9573-7b3cac8215b0.png)

And yet wasn't able to find the one that highlights it.

### Steps to reproduce

Just open a cmp completion window.

### Expected behavior

To find the highlight group.

### Actual behavior

Changed all of the cmp highlight groups and none of them highlights it. Its coming from somewhere else.

**Comment by reaz1995** [comment]
i tryed to mess with the hi groups, found out only these want to work:
select menu:
:lua vim.api.nvim_set_hl(0,'PMenu',{ bg='#ffffff' })
docs float window (this one is weird, like the inner inhert hi group from floatborder and after change inner stays same as it was, when i use transparency plugin to clean the hi group before it loads  the whole window of docs lose color):
:lua vim.api.nvim_set_hl(0,'FloatBorder',{ bg='#ffffff' })
