### ISSUE TITLE
Ask a question about fuzzy matching

### ISSUE THREAD

**Issue by yyy33** [hrsh7th/nvim-cmp#1076]
### I'm using gopls, why can't I match `fmt.print` in the following cases

![2022-07-16_05-54](https://user-images.githubusercontent.com/51548147/179316509-953a0796-da1e-4371-b813-88cbddae4012.png)
![2022-07-16_05-55](https://user-images.githubusercontent.com/51548147/179316526-c7bdfcea-ff67-46d3-bfc7-2f2efc2e4c8c.png)
![2022-07-16_05-59](https://user-images.githubusercontent.com/51548147/179316897-56ddc542-3fd2-4de2-97ee-ce310df362e5.png)
![2022-07-16_05-59_1](https://user-images.githubusercontent.com/51548147/179316903-ae922326-c7a1-42e1-ad18-b1b15fb9d2fb.png)
![2022-07-16_06-00](https://user-images.githubusercontent.com/51548147/179316906-e965636e-bb8c-4da8-98d0-d81376b90667.png)
![2022-07-16_06-00_1](https://user-images.githubusercontent.com/51548147/179316913-a23aa7cb-e64a-4767-a733-8da184286eba.png)

**Comment by hrsh7th** [comment]
Because gopls doesn't return the `fmt.Println` candidate with input of `fnt`.
