### ISSUE TITLE
Menu BG is pink?

### ISSUE THREAD

**Issue by godalming123** [hrsh7th/nvim-cmp#1077]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Description

When I use my menu it is pink and despite setting:
```vim
" gray
highlight! CmpItemAbbrDeprecated guibg=#000000 gui=strikethrough guifg=#808080
" blue
highlight! CmpItemAbbrMatch guibg=#000000 guifg=#569CD6
highlight! CmpItemAbbrMatchFuzzy guibg=#000000 guifg=#569CD6
" light blue
highlight! CmpItemKindVariable guibg=#000000 guifg=#569CD6
highlight! CmpItemKindInterface guibg=#000000 guifg=#569CD6
highlight! CmpItemKindText guibg=#000000 guifg=#569CD6
" pink
highlight! CmpItemKindFunction guibg=#000000 guifg=#569CD6
highlight! CmpItemKindMethod guibg=#000000 guifg=#569CD6
" front
highlight! CmpItemKindKeyword guibg=#000000 guifg=#569CD6
highlight! CmpItemKindProperty guibg=#000000 guifg=#569CD6
highlight! CmpItemKindUnit guibg=#000000 guifg=#569CD6
```
Is there not a bg color setting?

### Expected behavior
Bg is a senseble color that is easily readable by default

### Actual behavior

Bg is pink

**Comment by ghifarit53** [comment]
nvim-cmp doesn't define any color for the menu but instead links to existing colorscheme group (i.e. `Pmenu`). perhaps your config/colorscheme doesn't have any highlighting defined for `Pmenu`, so it fallbacks to its default colors (that pink background)

**Comment by godalming123** [comment]
thank you Can you document this it would have saved a lot of time
