### ISSUE TITLE
Snippet Engine setup 

### ISSUE THREAD

**Issue by pavanbhat1999** [hrsh7th/nvim-cmp#108]
I setup snippet engine using vim-vsnip. I am getting snippet suggestions but when i select them ,   

error('snippet engine is not configured.') 
above error is shown . 
What is the problem here.I think it is problem with default configuration
`
    snippet = {
      expand = function()
        error('snippet engine is not configured.')
      end,
    },`

**Comment by pavanbhat1999** [comment]
Okay sorry I got the solution. It was a problem with key mappings.

**Comment by acomagu** [comment]
@pavanbhat1999 I encountered same problem now. How did you solve it? My cmp setup:

```lua
cmp.setup {
  preselect = false,
  mapping = {
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<C-x><C-o>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
  },
  sources = {
    { name = 'calc' },
    { name = 'nvim_lsp' },
    { name = 'path' },
  },
}
```

**Comment by acomagu** [comment]
Solved by specifying `snippetSupport = false` for `nvim_lsp.update_capabilities`.

```lua
lua capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities(), {
      \   snippetSupport = false,
      \ })
```

**Comment by pavanbhat1999** [comment]
@acomagu  Can you share your whole config with nvim.cmp.

**Comment by pavanbhat1999** [comment]
@acomagu  chechkout Updated README.md . Now you can setup snippets without any hazzzel. 
My setup of nvim-cmp
`local cmp = require'cmp'
  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
mapping = {
  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
  ['<C-f>'] = cmp.mapping.scroll_docs(4),
  ['<C-Space>'] = cmp.mapping.complete(),
  ['<C-e>'] = cmp.mapping.close(),
  ['<CR>'] = cmp.mapping.confirm({
    behavior = cmp.ConfirmBehavior.Replace,
    select = true,
  })
},
 sources = {
    { name = 'buffer' },
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'vsnip' },
  },
  })
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
`

**Comment by pavanbhat1999** [comment]
@acomagu chechkout Updated README.md . Now you can setup snippets without any hazzzel.
My setup of nvim-cmp

```
local cmp = require'cmp'
  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
mapping = {
  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
  ['<C-f>'] = cmp.mapping.scroll_docs(4),
  ['<C-Space>'] = cmp.mapping.complete(),
  ['<C-e>'] = cmp.mapping.close(),
  ['<CR>'] = cmp.mapping.confirm({
    behavior = cmp.ConfirmBehavior.Replace,
    select = true,
  })
},
 sources = {
    { name = 'buffer' },
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'vsnip' },
  },
  })
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
 
```

**Comment by pavanbhat1999** [comment]
@acomagu chechkout Updated README.md . Now you can setup snippets without any hazzzel.
My setup of nvim-cmp

``` lua
local cmp = require'cmp'
  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
mapping = {
  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
  ['<C-f>'] = cmp.mapping.scroll_docs(4),
  ['<C-Space>'] = cmp.mapping.complete(),
  ['<C-e>'] = cmp.mapping.close(),
  ['<CR>'] = cmp.mapping.confirm({
    behavior = cmp.ConfirmBehavior.Replace,
    select = true,
  })
},
 sources = {
    { name = 'buffer' },
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'vsnip' },
  },
  })
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
 
```

**Comment by acomagu** [comment]
@pavanbhat1999 I misunderstood this issue some. I wanted to setup **without** snippet plugin. I'm sorry.

Now the README seems to be rewritten: Snippets plugin is necessary. But for now, for my environment my configuration works well(without Snippets) I'll leave it untouched.

Whole configuration:

```lua
local cmp = require('cmp')
cmp.setup {
  preselect = false,
  mapping = {
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<C-x><C-o>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
  },
  sources = {
    { name = 'calc' },
    { name = 'nvim_lsp' },
    { name = 'path' },
  },
}

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities(), {
  snippetSupport = false,
})
require'lspconfig'.tsserver.setup{
  capabilities = capabilities;
  filetypes = {"typescript", "typescriptreact", "typescript.tsx"};
}
```
