### ISSUE TITLE
window.{completion,documentation}.border lacks documentation.

### ISSUE THREAD

**Issue by techtycho** [hrsh7th/nvim-cmp#1080]
I've read `cmp.txt`, `utils/window.lua` and `config/window.lua`. The documentation for the `window.{completion,documentation}.border` says that it should be either an array of strings:

```
local border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│", }

cmp.setup({
  window = {
    completion = {
      border = border,
    }
  },
})
```

or one single string, like in `config/window.lua`:

```
border = opts.border or 'rounded',
```

I want to get a window that is **not rounded**, but with borders. And getting random Unicode characters for the borders sounds tedious. I thought that this will have a string for it, like `'rounded'`. But there was _no_ documentation about `string` types. I spent hours reading the source code, especially in `utils/window.lua` and I found this piece of code:

```
  if type(border) == 'string' then
    if border == 'shadow' then
      return {..}
    end
    return {..}
  end
```
(Read [the entire code block](https://github.com/hrsh7th/nvim-cmp/blob/9897465a7663997b7b42372164ffc3635321a2fe/lua/cmp/utils/window.lua#L242))

So there is `shadow` and `rounded`. But neither one is documented. Instead, I found them randomly. And I think there are more options, maybe one for sharp (not rounded) borders. But `window.border` lacks documentation. I just want a list of options for border.

Or if there is no option for non-rounded borders, how can I achieve them?

**Comment by hrsh7th** [comment]
I documented it as `See nvim_open_win`. You should read the `nvim_open_win`'s documentation.

It is intented as `same as nvim's API` so I don't write duplicated document for it.

**Comment by techtycho** [comment]
Thanks! Found it.

- none
- single
- double
- rounded
- solid
- shadow
