### ISSUE TITLE
Failed to select an item from the pop menu

### ISSUE THREAD

**Issue by uchenily** [hrsh7th/nvim-cmp#1083]
It seems that this commit "Remove all default mappings"(https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558) changed select behavior.

```
(venv) [root@archlinux nvim-cmp]# git reset --hard 93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558
HEAD is now at 93cf84f Remove all default mappings
```

![图片](https://user-images.githubusercontent.com/39831719/180265487-35ec3b4e-b689-418a-aa24-bfe0b43dc7d4.png)
In this picture, I want to select "dump", and I pressed "ctrl-n", then the menu changed to origin keyword completion, which is not what I expected.
![图片](https://user-images.githubusercontent.com/39831719/180266368-c13ca2d0-8f87-4c8f-9226-0801a0dcaee0.png)

Then, I checkout to previous commit, everything became ok.

```
(venv) [root@archlinux nvim-cmp]# git reset --hard HEAD^1
HEAD is now at 4f1358e Add deprecation notice
```

![图片](https://user-images.githubusercontent.com/39831719/180266985-60d4b969-5aca-4b82-aee8-b33ddbd08d8f.png)

**Comment by hrsh7th** [comment]
Could you read the announcement?
https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017

**Comment by uchenily** [comment]
Thanks
