### ISSUE TITLE
Menu customization API

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#11]
From #10, #7

**Comment by gegoune** [comment]
Are you using custom window to display completion candidates in cmp or standard vim/nvim one?

**Comment by hrsh7th** [comment]
Haha, Currently nvim-comp uses vim's native completion menu.

But my next task after nvim-comp stabilized is it! I will use a custom completion menu via the floating window. (It realizes custom 
 highlighting.)

**Comment by Jesse-Bakker** [comment]
Sounds pretty cool! Will there then also be an option to just use the regular neovim completion menu?

**Comment by akinsho** [comment]
> Sounds pretty cool! Will there then also be an option to just use the regular neovim completion menu?

Sounds like you'd have to maintain two implementations to do that, one that conforms to the requirements of nvim's completion menu and one to a custom popup. I'm nowhere near the code but seems like it'd be easier to just add configuration options for whatever a person might want to disable/enable rather than implement/maintain both styles

**Comment by Jesse-Bakker** [comment]
> I'm nowhere near the code but seems like it'd be easier to just add configuration options for whatever a person might want to disable/enable rather than implement/maintain both styles

Yeah, that's what I meant

**Comment by windwp** [comment]
```lua

vim.lsp.protocol.CompletionItemKind = {
    '', -- Text          = 1;
    '', -- Method        = 2;
    'ƒ', -- Function      = 3;
    '', -- Constructor   = 4;
    '⌘', -- Field         = 5;
    '', -- Variable      = 6;
    '', -- Class         = 7;
    'ﰮ', -- Interface     = 8;
    '', -- Module        = 9;
    '', -- Property      = 10;
    '', -- Unit          = 11;
    '', -- Value         = 12;
    '了', -- Enum          = 13;
    '', -- Keyword       = 14;
    '﬌', -- Snippet       = 15;
    '', -- Color         = 16;
    '', -- File          = 17;
    '', -- Reference     = 18;
    '', -- Folder        = 19;
    '', -- EnumMember    = 20;
    '', -- Constant      = 21;
    '', -- Struct        = 22;
    '', -- Event         = 23;
    '', -- Operator      = 24;
    '', -- TypeParameter = 25;
}
local cmp = require('cmp')
for index, value in ipairs(vim.lsp.protocol.CompletionItemKind) do
    cmp.lsp.CompletionItemKind[index] = value
end

```
a little snippet to implement lsplkind on nvim-cmp

**Comment by miguelcaravantes** [comment]
> ```lua
> vim.lsp.protocol.CompletionItemKind = {
>     '', -- Text          = 1;
>     '', -- Method        = 2;
>     'ƒ', -- Function      = 3;
>     '', -- Constructor   = 4;
>     '⌘', -- Field         = 5;
>     '', -- Variable      = 6;
>     '', -- Class         = 7;
>     'ﰮ', -- Interface     = 8;
>     '', -- Module        = 9;
>     '', -- Property      = 10;
>     '', -- Unit          = 11;
>     '', -- Value         = 12;
>     '了', -- Enum          = 13;
>     '', -- Keyword       = 14;
>     '﬌', -- Snippet       = 15;
>     '', -- Color         = 16;
>     '', -- File          = 17;
>     '', -- Reference     = 18;
>     '', -- Folder        = 19;
>     '', -- EnumMember    = 20;
>     '', -- Constant      = 21;
>     '', -- Struct        = 22;
>     '', -- Event         = 23;
>     '', -- Operator      = 24;
>     '', -- TypeParameter = 25;
> }
> local cmp = require('cmp')
> for index, value in ipairs(vim.lsp.protocol.CompletionItemKind) do
>     cmp.lsp.CompletionItemKind[index] = value
> end
> ```
> 
> a little snippet to implement lsplkind on nvim-cmp

great i am using it this way to show icon + text
```lua
for index, value in ipairs(vim.lsp.protocol.CompletionItemKind) do
    cmp.lsp.CompletionItemKind[index] = value .. ' ' ..  cmp.lsp.CompletionItemKind[index]
end
```

**Comment by hrsh7th** [comment]
I've added the API for it. see 
https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem
