### ISSUE TITLE
Toggle documentation window

### ISSUE THREAD

**Issue by ziombo** [hrsh7th/nvim-cmp#1101]
Is it possible to set a shortcut to toggle the documentation window? 

In the documentation I found the part about disabling it:
```
How to disable the documentation window?~

  Simply use the following config:
  cmp.setup.filetype({ 'markdown', 'help' }, {
    window = {
      documentation = cmp.config.disable
    }
  })
```

but I would like to be able to display it in certain (not defined) circumstances.

**Comment by hrsh7th** [comment]
dup

**Comment by hrsh7th** [comment]
v
