### ISSUE TITLE
Lag when scrolling in a popup menu with a lot of completion items

### ISSUE THREAD

**Issue by dmitmel** [hrsh7th/nvim-cmp#111]
Basically what the title says. An easy way to reproduce this bug is to type `/usr/bin/` on a Linux/macOS system with the [path](https://github.com/hrsh7th/cmp-path) completion source (or with a fake source, perhaps, which just returns a bunch of results) and scroll with Up/Down arrows. I took a profile and I believe that the cause of this bug is in the `cmp.menu.get_selected_entry` function:

<https://github.com/hrsh7th/nvim-cmp/blob/24406f995ea20abba816c0356ebff1a025c18a72/lua/cmp/menu.lua#L208-L226>

This function is triggered on the `CompleteChanged` autocommand, and the call to `complete_info` has to transmit all completion items to the Lua side every time a different item is selected. Can the completion items be stored in a table on the Lua side? Alternatively, can this call be bypassed if I have `documentation` option disabled (I think the documentation float is the only user of the selected completion item, judging by the `cmp.menu.select` and `cmp.menu.unselect` functions)?

**Comment by hrsh7th** [comment]
@dmitmel I've improved the implementation. Could you test with latest ?

**Comment by dmitmel** [comment]
No, it doesn't, the slow path is still taken... Isn't `v:complete_item` intended for use in `CompleteDone`? By the way, here's a source that can be used to diagnose the problem:

```lua
local source = {}
source.new = function()
  return setmetatable({}, { __index = source })
end
function source:is_available()
  return true
end
function source:get_keyword_pattern(params)
  return '.+'
end
function source:complete(params, callback)
  local items = {}
  for i = 1, 10000 do
    items[i] = { label = string.format('%d', i) }
  end
  callback(items)
end
cmp.register_source('lag_machine', source.new())
```

**Comment by dmitmel** [comment]
I think the following patch should do the job:

```diff
diff --git a/lua/cmp/menu.lua b/lua/cmp/menu.lua
index cd24b11..6c353af 100644
--- a/lua/cmp/menu.lua
+++ b/lua/cmp/menu.lua
@@ -217,9 +217,8 @@ menu.get_selected_entry = function(self)
   if selected == -1 then
     return nil
   end
-  local items = vim.fn.complete_info({ 'items' }).items
 
-  local completed_item = items[math.max(selected, 0) + 1] or {}
+  local completed_item = self.items[math.max(selected, 0) + 1] or {}
   if not completed_item.user_data then
     return nil
   end
@@ -234,8 +233,7 @@ end
 ---Get first entry
 ---@param self cmp.Entry|nil
 menu.get_first_entry = function(self)
-  local info = vim.fn.complete_info({ 'items' })
-  local completed_item = info.items[1] or {}
+  local completed_item = self.items[1] or {}
   if not completed_item.user_data then
     return nil
   end
```

**Comment by hrsh7th** [comment]
I don't think so because when menu scrolling, get_selected_entry always be fallbacked to get_active_entry.

**Comment by dmitmel** [comment]
Don't know, I still observe the issue... Well anyway, what do you think of the patch? I realized that you already have the list of completion items on the Lua side (tested, this fixes the problem for me).

**Comment by hrsh7th** [comment]
I was considering your solution. But it has a side-effect. For example, if the user invoke `<C-x><C-o>`, the popup menu index will specify another item list.

**Comment by hrsh7th** [comment]
_BTW, I've happy the user understand my codes. _

When I encountered it before, it improved this way.

```lua
  require'lspconfig'.gopls.setup {
    flags = { debounce_text_changes = 200 },
    ...
  }
```

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/131242146-48805d5f-8458-48b0-9526-f2c09d06fa5e.mp4

**Comment by hrsh7th** [comment]
@dmitmel Do you still have this problem?

**Comment by dmitmel** [comment]
Yes, and I am working on a workaround for a problem you mentioned, when the user triggers omni-completion or other type of completion with the nvim-cmp menu still open. Also I think I know why you couldn't reproduce my issue. This may sound stupid, but that is because you were using Ctrl-N/Ctrl-P, while I was using Up/Down arrow keys. For some reason they (arrow keys) don't cause `v:completed_item` to be set, which is why the fallback wasn't taken in my case. I created a minimal reproduction vimrc, you can see for yourself with `nvim -u minimal_init.vim`:

```vim
set nocompatible
set runtimepath+=~/.config/nvim/plugged/nvim-cmp
lua <<EOF

local cmp = require('cmp')

do
  local source = {}
  source.new = function()
    return setmetatable({}, { __index = source })
  end
  function source:is_available()
    return true
  end
  function source:get_keyword_pattern(params)
    return '.+'
  end
  function source:complete(params, callback)
    local items = {}
    for i = 1, 10000 do
      items[i] = { label = string.format('%d', i) }
    end
    callback(items)
  end
  cmp.register_source('lag_machine', source.new())
end

cmp.setup({
  sources = {
    { name = 'lag_machine' }
  };
  mapping = {
    ['<C-Space>'] = cmp.mapping.complete();
    ['<CR>'] = cmp.mapping.confirm();
    ['<C-y>'] = cmp.mapping.confirm();
    ['<C-e>'] = cmp.mapping.close();
    ['<Esc>'] = cmp.mapping.close();
  };
})

EOF
```

Press Ctrl-Space to trigger the menu, then try scrolling with Ctrl-N/Ctrl-P, you'll observe no lag, then try with arrow keys and you will surely notice the issue.

> _BTW, I've happy the user understand my codes. _

Your code is really a pleasure to work with!

**Comment by hrsh7th** [comment]
I've confirmed. If we use `<Down>`or `<Up>`. It doesn't fallback to `get_active_entry`.

I will fix it. (maybe)

**Comment by dmitmel** [comment]
My idea was to listen for the `CompleteDone` autocommad and reset the menu when it is fired. I noticed that it is always fired when changing the completion type.

**Comment by hrsh7th** [comment]
@dmitmel I've fixed it by checking `complete_info().mode` is eval or not.

**Comment by dmitmel** [comment]
Hold on, your solution will break if some items were filtered through `dup`. `self.items` may be shorter than `self.entries` due to this loop:

https://github.com/hrsh7th/nvim-cmp/blob/e867bf233e4f91dec180378307317cfd42af4bdb/lua/cmp/menu.lua#L115-L129

**Comment by hrsh7th** [comment]
Indeed. I think we should remove the manual dup filter.

**Comment by dmitmel** [comment]
Yeah, didn't think of this, but this would solve the problem as well (if indexes returned by `complete_info(['selected']).selected` are correct for duplicates). Here's my solution:

```diff
diff --git a/lua/cmp/menu.lua b/lua/cmp/menu.lua
index 1e7e7e5..ca50985 100644
--- a/lua/cmp/menu.lua
+++ b/lua/cmp/menu.lua
@@ -16,6 +16,7 @@ local check = require('cmp.utils.check')
 ---@field public on_select fun(e: cmp.Entry)
 ---@field public items vim.CompletedItem[]
 ---@field public entries cmp.Entry[]
+---@field public deduped_entries cmp.Entry[]
 ---@field public entry_map table<number, cmp.Entry>
 ---@field public selected_entry cmp.Entry|nil
 ---@field public context cmp.Context
@@ -59,6 +60,7 @@ menu.reset = function(self)
   self.offset = nil
   self.items = {}
   self.entries = {}
+  self.deduped_entries = {}
   self.entry_map = {}
   self.context = nil
   self.preselect = 0
@@ -115,11 +117,13 @@ menu.update = check.wrap(function(self, ctx, sources)
   -- create vim items.
   local items = {}
   local abbrs = {}
+  local deduped_entries = {}
   local preselect = 0
   for _, e in ipairs(entries) do
     local item = e:get_vim_item(offset)
     if not abbrs[item.abbr] or item.dup == 1 then
       table.insert(items, item)
+      table.insert(deduped_entries, e)
       abbrs[item.abbr] = true
 
       if preselect == 0 and e.completion_item.preselect and config.get().preselect ~= types.cmp.PreselectMode.None then
@@ -132,6 +136,7 @@ menu.update = check.wrap(function(self, ctx, sources)
   self.offset = offset
   self.items = items
   self.entries = entries
+  self.deduped_entries = entries
   self.entry_map = entry_map
   self.preselect = preselect
   self.context = ctx
@@ -210,7 +215,7 @@ menu.get_selected_entry = function(self)
   if selected == -1 then
     return nil
   end
-  return self.entries[math.max(selected, 0) + 1]
+  return self.deduped_entries[math.max(selected, 0) + 1]
 end
 
 ---Get first entry
@@ -219,7 +224,7 @@ menu.get_first_entry = function(self)
   if not self:is_valid_mode() then
     return nil
   end
-  return self.entries[1]
+  return self.deduped_entries[1]
 end
 
 ---Return the completion menu is visible or not.
```

**Comment by hrsh7th** [comment]
Thank you. @dmitmel I've fixed.

**Comment by dmitmel** [comment]
Great, thanks a lot!

**Comment by hinell** [comment]
It would be nice if items are cached.

**Comment by bew** [comment]
@hinell this is a very old issue, I'd suggest to open a new one with your information, description of the problem, etc ...
