### ISSUE TITLE
luasnip integration code causes random jumps in insert mode

### ISSUE THREAD

**Issue by dialtone** [hrsh7th/nvim-cmp#1114]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
-- Setup Completion
-- See https://github.com/hrsh7th/nvim-cmp#basic-configuration
-- https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#luasnip
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end
local cmp = require'cmp'
local luasnip = require("luasnip")
cmp.setup({
  -- Enable LSP snippets
  snippet = {
    expand = function(args)
      require'luasnip'.lsp_expand(args.body)
    end
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    -- Add tab support
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" }),
  },

  -- Installed sources
  sources = {
    { name = 'luasnip' },
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'path' },
  },
})
```

### Description

[GIF of what happens](https://imgur.com/CESDk5w)

Basic description is that after accepting an autocompletion with the luasnip integration, somehow pressing again `tab` in insert mode results in the caret jumping back to the autocompletion that was accepted.

I've started noticing this behavior only a few days ago, maybe a week ago give or take.

### Steps to reproduce

Enable luasnip with nvim-cmp, simple configuration, with the luasnip integration accepting an auto-complete results in the caret jumping around, without the luasnip integration it doesn't happen.

### Expected behavior

After the completion suggestion is taken, it should remove the marks to jump around with `tab`

### Actual behavior

jumps around.

**Comment by hrsh7th** [comment]
Why do you think this is nvim-cmp's bug? IMO, it should open in luasnip repo.

**Comment by dialtone** [comment]
I had opened it there at first, but figured that the handling on the auto complete place holders is in nvim-cmp and I think that's where the issue is that when you leave insert mode those placeholders are still kept around. Obviously I could be misunderstanding the source of the problem.

**Comment by hrsh7th** [comment]
nvim-cmp just calls the snippet engine on confirmation. After that nvim-cmp don't touch the snippet session.

So I can't support `The snippet session should be deactivated in suitable timing`. Sorry.

**Comment by dialtone** [comment]
alright, I opened the issue in luasnip.

**Comment by dialtone** [comment]
are you positive about this being a luasnip issue though? The gif doesn't actually work via luasnip, it seems to be just the behavior in the `<tab>` key that is bogus, but what is autocompleted in the gif is a `nvim-cmp` suggestion, not snippet.

**Comment by onsails** [comment]
@dialtone have you found a way to fix this? I also encounter this problem each time I work with rust sources

**Comment by onsails** [comment]
found a [solution](https://github.com/L3MON4D3/LuaSnip/issues/258#issuecomment-1011938524)
