### ISSUE TITLE
How to set `keyword_pattern` for specific language?

### ISSUE THREAD

**Issue by przepompownia** [hrsh7th/nvim-cmp#1115]
After setting 
```lua
  confirmation = {
    default_behavior = cmp.ConfirmBehavior.Replace,
  },
```
completing `$this` again inside `$this->foo()` results with `$this>foo()` because `-` belongs to the default keyword pattern. 

I copied the original pattern from `config/default` without the dashes into my configuration:
```lua
  completion = {
    keyword_pattern = [[\%(\d\+\%(\.\d\+\)\?\|\h\w*\)]],
  },
```

It seems to work but I'd like apply it only for PHP buffers (for each completion source). Currently it's a global configuration.

I found that we can define `get_keyword_pattern()` per source but didn't found how to make it language-dependent.

**Comment by hrsh7th** [comment]
```
cmp.setup.filetype({ 'php' }, {
  completion = {
    keyword_pattern = [[...]]
  }
})
```

You can use `cmp.setup.filetype(...)`.

**Comment by przepompownia** [comment]
Thanks for the basic hint. I overlooked it starting from detail.
