### ISSUE TITLE
[Question] Exit insert mode after completion is confirmed

### ISSUE THREAD

**Issue by TheLox95** [hrsh7th/nvim-cmp#1118]
I would like when pressing `enter` to confirm completion and exit the insert mode.
Right now tried the following code but the completion is inserted twice and neovim stays on insert mode
```lua
cmp.setup(
    {
        mapping = cmp.mapping.preset.insert(
            {
                
                ["<CR>"] = function(fallback)
                    if cmp.visible() then
                        cmp.confirm()
                        vim.cmd("stopinsert")
                    else
                        fallback() -- If you use vim-endwise, this fallback will behave the same as vim-endwise.
                    end
                end,
            }
        ),
    }
)
```

**Comment by ExuCounter** [comment]
I have a similar problem.
I want to call cmp.abort() on <Esc> and exit from insertmode, but it doesn't work for me either.

**Comment by hrsh7th** [comment]
the `cmp.confirm` take the callback argument. You should feed `<Esc>` after completion callback.

**Comment by awoodx** [comment]
> I have a similar problem. I want to call cmp.abort() on "<Esc>" and exit from insertmode, but it doesn't work for me either.

It also felt more natural to me that <Esc> would exit insert mode. I ended up with this, feels kind of hacky, but it worked.

`  ['<Esc>'] = function(_)
      cmp.abort()
      vim.defer_fn(function() vim.cmd('stopinsert') end, 0)
  end,
`

**Comment by CanonRouge24** [comment]
> > I have a similar problem. I want to call cmp.abort() on "" and exit from insertmode, but it doesn't work for me either.
> 
> It also felt more natural to me that Escape would exit insert mode. I ended up with this, feels kind of hacky, but it worked.
> 
> ` ['<Esc>'] = function(_) cmp.abort() vim.defer_fn(function() vim.cmd('stopinsert') end, 0) end,`

I noticed that this borks the functionality of [digit]o/O, you'll only ever get one new line created.

```
["<Esc>"] = function (fallback)
  if (cmp.visible()) then
    cmp.abort()
    vim.defer_fn(
      function ()
        vim.cmd("stopinsert")
      end,
      0 -- 0 milliseconds
    )
  else
    fallback()
  end
end,
```

fixes that behavior for me.
