### ISSUE TITLE
Using the autocomplete menu removes the completion when using GDScript LSP Server

### ISSUE THREAD

**Issue by ForAzens** [hrsh7th/nvim-cmp#1119]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif vim.fn["vsnip#available"](1) == 1 then
        feedkey("<Plug>(vsnip-expand-or-jump)", "")
      elseif has_words_before() then
        cmp.complete()
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function()
      if cmp.visible() then
        cmp.select_prev_item()
      elseif vim.fn["vsnip#jumpable"](-1) == 1 then
        feedkey("<Plug>(vsnip-jump-prev)", "")
      end
    end, { "i", "s" }),
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.gdscript.setup {
  capabilities = capabilities,
  }
EOF
```

### Description

If you press `<CR>` without navigating through the autocomplete menu with `<TAB>`, it will autocomplete the first selection without issues:
![Peek 2022-08-06 23-25](https://user-images.githubusercontent.com/29065801/183266582-4df868f5-6a35-4be8-a19b-cce025809978.gif)

The problem occurs when you navigate through the autocomplete menu and press `<CR>` when a item is selected:
![Peek 2022-08-06 23-24](https://user-images.githubusercontent.com/29065801/183266612-31a14cf8-3471-4957-853b-f28294b949d4.gif)

### Steps to reproduce

With the minimal config provided earlier:
1. Download Godot https://godotengine.org/download
2. Clone the repository with godot example projects https://github.com/godotengine/godot-demo-projects
3. Open the project **godot-demo-projects/2d/bullet_shower** in Godot (otherwise the GDScript LSP server will not work).
4. Open the file **godot-demo-projects/2d/bullet_shower/bullets.gd** in neovim with the minimal config provided.
5. Try to autocomplete some constant or variable with and without navigating through the autocomplete menu.

### Expected behavior

It should complete the selected item in the autocomplete menu without any issue.

### Actual behavior

It does not complete the selected item, only works when you press `<CR>` without navigating through the menu.

### Additional context

I have been digging into this problem before creating this issue, and what I have found is that the LSP server only returns a `label` without any `insert_text` in the LSP type `completionItem/resolve`.
Then the neovim lsp client or nvim-cmp creates a CompletionItem where the property `insert_text` is an empty string.

Then I found that the "problem" was in this line: https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/core.lua#L414

  If I replace that line with the next code, it solves the problem but I don't know if it can cause issues with others LSP servers or sources from nvim-cmp.
```lua
local insertText = misc.safe(completion_item.insertText)
if misc.empty(insertText) then
  insertText = nil
end
completion_item.textEdit.newText = insertText or completion_item.word or
    completion_item.label
```

I got through this solution with the LSP Spec: 
```
	/**
	 * The label of this completion item.
	 *
	 * The label property is also by default the text that
	 * is inserted when selecting this completion.
	 *
	 * If label details are provided the label itself should
	 * be an unqualified name of the completion item.
	 */
	label: string;
```
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

My knowledge about the LSP Protocol and Lua is limited so maybe this is not correct.

**Comment by hrsh7th** [comment]
Thank you for detailed investigation.

Hm... In my eyes, it's bug of language server side... but I hope to support this case (if it's rational).

Could you put the godot response?

**Comment by ForAzens** [comment]
Sorry for the long delay,

here is the godot response:
`[DEBUG][2022-11-08 19:20:52] .../lua/vim/lsp.lua:1388	"LSP[gdscript]"	"client.request"	2	"completionItem/resolve"	{  data = {    position = {      character = 1,      line = 12    },    textDocument = {      uri = "file:///home/forazens/Downloads/godot-demo-projects/2d/bullet_shower/bullets.gd"    }  },  kind = 21,  label = "SPEED_MAX"}	<function 1>	8`
`[DEBUG][2022-11-08 19:20:52] .../lua/vim/lsp.lua:1388	"LSP[gdscript]"	"client.request"	2	"workspace/executeCommand"	{  command = "",  title = ""}	<function 1>	8
`

**Comment by Mawdac** [comment]
Thanks for sharing your findings @ForAzens - I was just trying to figure this out too
