### ISSUE TITLE
Specifying completion offset

### ISSUE THREAD

**Issue by ii14** [hrsh7th/nvim-cmp#1127]
In completion sources for nvim-compe I could specify the offset for the completion. Is it not possible in nvim-compe anymore? Is there any workaround? I'm looking at the source code of the omni source and as far as I can tell the offset received from the omnifunc is more or less just ignored.

**Comment by bew** [comment]
What do you mean by 'completion offset'  ?
Like changing what string prefix should be used to compute relevant candidates?

**Comment by ii14** [comment]
Kinda, what you're talking about is an indirect method of specifying at what column the completion should start. The completion sources should be able to specify the column explicitly, like you can with vim's omni completion or nvim-compe. I already know the column, I don't want to come up with some elaborate context-dependent regex that will try to substitute an actual parser. And this is quite clear with the omni source, the offset returned from omnifunc is basically ignored. Instead it just assumes that the pattern is always `\k\+` and can start completion at invalid column.

**Comment by Shougo** [comment]
Hm..  It seems `source.complete()` override is needed for it.
The default implementation uses `keyword_pattern`.

https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/source.lua#L239

**Comment by Shougo** [comment]
> Instead it just assumes that the pattern is always \k\+ and can start completion at invalid column.

Do you want to call omnifunc with every input characters?
You can use `.*` pattern instead of `\k\+`.

And the offset is used.  It is not ignored.

https://github.com/hrsh7th/cmp-omni/blob/main/lua/cmp_omni/init.lua#L16

**Comment by ii14** [comment]
If I understand it correctly it's used only to create the `base` argument for omnifunc and to create `insertText` property (I think this can offset the completion to the right of the keyword, but not to the left). But it's ignored as the value it's actually supposed to represent, which means "the completion should replace the text starting from this column".

> Do you want to call omnifunc with every input characters?

Is that what keyword pattern is only used for? Isn't that what are you supposed to use `trigger_characters` for?

> Hm.. It seems `source.complete()` override is needed for it.

Can I override this? Completion sources are wrapped in it and just `id` is returned:
```lua
cmp.register_source = function(name, s)
  local src = source.new(name, s)
  cmp.core:register_source(src)
  return src.id
end
```

**Comment by Shougo** [comment]
> Is that what keyword pattern is only used for? Isn't that what are you supposed to use trigger_characters for?

`trigger_characters` means if it is input, source completion length is ignored like manual completion.

**Comment by Shougo** [comment]
Hm... I have read the source code.
nvim-cmp has not complete position feature from sources.
It seems trade off with LSP spec compatibility.
If you need the feature, you should use other completion engine.

**Comment by hrsh7th** [comment]
You can specify the `textEdit` it's will be used for completion offset.

**Comment by ii14** [comment]
@hrsh7th Thanks a lot, that works :) It probably should be used in the omni source as well.
