### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by otavioschwanck** [hrsh7th/nvim-cmp#1128]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

.

### Description

Would be awesome to have nvim-cmp enabled in macro.  

To implement this, probabily the logic is:

When something is selected in nvim-cmp (inside macro), edit the macro to insert the text that nvim-cmp instead of recording the tabs, up, down, etc.

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

**Comment by hrsh7th** [comment]
Sorry. I gave up supporting the macro. So it's out of scope. If you can implement it, feel free to create PR or separate repo or fork.
