### ISSUE TITLE
Question: working without snippet engine?

### ISSUE THREAD

**Issue by myxo** [hrsh7th/nvim-cmp#1129]
Hi. 
Is there a way to run this plugin without snippet engine? My problem is: I never want completion snippet expand with arguments and types. I just want function name inserted and continue typing. It's kinda resemble #1038 but there described a more special problem.

It's seems that I may just set `snippet.expand` to function that pass function name, but I don't know how to do it.

**Comment by Shougo** [comment]
Please read this.

https://github.com/hrsh7th/nvim-cmp/issues/947

**Comment by myxo** [comment]
@Shougo I don't believe this is relevant. That issue shows some bug (?) in language server.

I want to know if I can autocomplete only functions or classes names without expanding snippets with arguments and types.

I guess it may be done from snippet side (although I didn't find this feature in luasnip). But it seems kind of redundant to bring snippet engine just to turn it off.

**Comment by Shougo** [comment]
The snippet feature is enabled by Language Server side.
So you need to disable it.
The config depends on Language Server.

**Comment by myxo** [comment]
Oh, ok, I misunderstand what person from the issue wanted.

But is it really no way to just ignore snippet from server and just print function name?

**Comment by Shougo** [comment]
The snippet feature is enabled by Language Server side.
So you need to disable it.
The config depends on Language Server.

This problem is not for both nvim-cmp and snippet engines.

**Comment by Shougo** [comment]
It depends on your Language server.
What do you use the language server?

**Comment by myxo** [comment]
Right now I am using rls, but truly, I want to turn it off for all lsp I am using.

> nvim-cmp cannot ignore them.

"cannot" - mean there is some fundamental problem with that or just nobody cared enough to implement it yet ?

**Comment by Shougo** [comment]
For rls, please see this.

https://github.com/neovim/nvim-lspconfig/issues/276

It is from LSP spec.
If candidates contains snippets, completion engine must support them.
If it is ignored, candidates contains just garbage items.

**Comment by hrsh7th** [comment]
It isn't impossible but we can't support it as perfect behavior.
So I don't want to implement this. it will increase support cost.

**Comment by carloruiz** [comment]
Adding a comment for posterity:

```lua
local capabilities = require('cmp_nvim_lsp').default_capabilities()
-- This line disables snippets. Note that has side-effects like not including parens on autocomplete.
capabilities.textDocument.completion.completionItem.snippetSupport = false

-- gopls client configuration.
require('lspconfig').gopls.setup({
	capabilities = capabilities, 
	on_attach = codeNavigationBindings,
})
```
