### ISSUE TITLE
Setting autocomplete to empty table doesn't disable autocomplete

### ISSUE THREAD

**Issue by ram02z** [hrsh7th/nvim-cmp#113]
From README:
> If you set this to empty or false, nvim-cmp will not perform completion automatically. You can still use manual completion though (like omni-completion via the cmp.mapping.complete function).

Setting `autocomplete` to false still works, but setting it to an empty table, `{}`, stopped working after 24406f995ea20abba816c0356ebff1a025c18a72.

**Comment by hrsh7th** [comment]
Thank you. I've forgotten to change README.md.

The empty table will be merged for now.

**Comment by hrsh7th** [comment]
I've updated the README.md :)
https://github.com/hrsh7th/nvim-cmp/commit/b29356a17649730ef3370e37dd84cbe404c25eeb
