### ISSUE TITLE
include in C will add `<` or `"`

### ISSUE THREAD

**Issue by NEX-S** [hrsh7th/nvim-cmp#1133]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

1

### Description

1

### Steps to reproduce

https://user-images.githubusercontent.com/97107165/185115434-43060269-861b-4164-8360-a455682467b4.mp4

### Expected behavior

#include <stdio.h>

### Actual behavior

#include <stdio.h>>

**Comment by max397574** [comment]
there is a reason why there is a field with minimal reproducible config
it makes things for developers much easier
please try to fill it out @NEX-S

**Comment by Shougo** [comment]
I think some config fixes your problem.  But I have forgot about it...
