### ISSUE TITLE
When using `wildmenu` for cmdline completion, selected entry does not auto-expand or confirm

### ISSUE THREAD

**Issue by dansalvato** [hrsh7th/nvim-cmp#1141]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  view = {
    entries = {name = 'wildmenu'}
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  }, {
    { name = 'buffer' },
  }),
})

cmp.setup.cmdline('/', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' }
  }
})

cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When setting the view to `custom`, selecting completion entries in cmdline mode works as expected—your command expands to the selected entry and is confirmed with `<CR>`.

When setting the view to `wildmenu`, selecting completion entries in cmdline mode does *not* expand your command, and `<CR>` runs your half-typed command instead of the selected entry.

### Steps to reproduce

1. Start a new nvim instance, and create a vertical split (`<C-w>v`).
2. Type `:q` so that the wildmenu completion entries appear.
3. Use `<Tab>` or `<C-n>` to select `qall`. Notice that the cmdline input does not expand.
4. Press `<CR>`. Notice that instead of running `:qall` and exiting nvim, `:q` gets run and one window is closed.
5. In the minimal config, replace `'wildmenu'` with `'custom'`. Repeat the above steps. Notice that the cmdline input does expand, and `:qall` gets run as expected.

### Expected behavior

Using `wildmenu` completion view in cmdline mode should expand and confirm selected entries, the same as `custom` view.

### Actual behavior

Only `custom` view expands and confirms selected entries, while `wildmenu` view does not.

**Comment by hrsh7th** [comment]
Sorry. I can't reproduce (probably, this issue has already gone or your another plugin is the root cause.)

https://user-images.githubusercontent.com/629908/185744088-dd496da0-5604-4e94-94da-dc0d650bbe98.mp4
