### ISSUE TITLE
Complete can only be used in insert mode

### ISSUE THREAD

**Issue by sbbddz** [hrsh7th/nvim-cmp#1142]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local status, packer = pcall(require, 'packer')

vim.cmd [[
  set completeopt=menuone,noinsert,noselect
]]

if (not status) then
  print("[ERROR] Packer is needed for this configuration to work")
  return
end

return require('packer').startup(function()
  --- Packer
  use 'wbthomason/packer.nvim'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/nvim-cmp'
end)

```

### Description

With a fresh install of vim with full lua configuration, I'm getting this error when autocompleting a command in normal mode.

The error can be reproduced with a call to vim.fn.complete(1, {})

There is no other plugins or mappings that could conflict, only the config shown above

### Steps to reproduce

Just copy the config and run nvim -u config.lua, need to have packer installed.

Try autocompleting one command or issuing :lua vim.fn.complete(1, {})

### Expected behavior

Autocomplete commands without errors.

### Actual behavior

Error spam when trying to autocomplete from normal command mode

### Additional context

<img width="889" alt="Screenshot 2022-08-20 at 14 34 44" src="https://user-images.githubusercontent.com/5954310/185746770-967b3ee3-3992-4073-abb5-03b5bfb17e3c.png">
<img width="904" alt="Screenshot 2022-08-20 at 14 34 17" src="https://user-images.githubusercontent.com/5954310/185746773-628bde6f-cbb6-46f4-90fb-116c3c7291fc.png">

Didn't find anything related on issues or faq, if this is documented somewhere or I'm missing something I'm sorry for opening a new issue.

Thanks! Ask for any extra information that could be needed!

**Comment by hrsh7th** [comment]
Sorry for annoying. I've fixed.

**Comment by bagwaa** [comment]
Wow, this was fast, thanks for reporting and the fix 👍

**Comment by wonbinbk** [comment]
Thanks @hrsh7th , this was superb!

**Comment by sbbddz** [comment]
Deeply grateful! That was fast! Thanks!

**Comment by Spo0on** [comment]
I still have same problem with native menu view.
This only occurs when I set view to native:
```
view = {
    entries = "native",
},
```
This is my config:
```
local has_words_before = function()
	local line, col = unpack(vim.api.nvim_win_get_cursor(0))
	return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local luasnip = require("luasnip")

-- Setup nvim-cmp.
local cmp = require("cmp")

local mapping_sets = {
	["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "s", "c" }),
	["<C-b>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "s", "c" }),
	["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "s", "c" }),
	["<CR>"] = cmp.mapping.confirm({ select = true }, { "i", "s", "c" }),
	["<C-e>"] = cmp.mapping({
		i = cmp.mapping.abort(),
		c = cmp.mapping.close(),
	}),
	["<Tab>"] = cmp.mapping(function(fallback)
		if cmp.visible() then
			cmp.select_next_item()
		elseif luasnip.expand_or_jumpable() then
			luasnip.expand_or_jump()
		else
			fallback()
		end
	end, { "i", "s", "c" }),
	["<S-Tab>"] = cmp.mapping(function(fallback)
		if cmp.visible() then
			cmp.select_prev_item()
		elseif luasnip.jumpable(-1) then
			luasnip.jump(-1)
		else
			fallback()
		end
	end, { "i", "s", "c" }),
}

local lspkind = require("lspkind")
cmp.setup({
	snippet = {
		expand = function(args)
			luasnip.lsp_expand(args.body)
		end,
	},
	window = {
		completion = cmp.config.window.bordered({
			border = "rounded",
		}),
		documentation = cmp.config.window.bordered({
			border = "rounded",
		}),
	},
	mapping = cmp.mapping.preset.insert(mapping_sets),
	sources = cmp.config.sources({
		{ name = "cmp_tabnine" },
		{ name = "luasnip" },
		{ name = "nvim_lsp" },
	}, {
		{ name = "buffer" },
		{
			name = "path",
			option = {
				trailing_slash = true,
			},
		},
	}),
	formatting = {
		fields = { "kind", "abbr" },
		format = lspkind.cmp_format({
			mode = "symbol",
			maxwidth = 50,
		}),
	},
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(":", {
	view = {
		entries = "native",
	},
	mapping = mapping_sets,
	sources = cmp.config.sources({
		{
			name = "path",
			option = {
				trailing_slash = true,
			},
		},
		{ name = "cmdline" },
	}),
})

-- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline("/", {
	mapping = mapping_sets,
	sources = cmp.config.sources({
		{
			name = "path",
			option = {
				trailing_slash = true,
			},
		},
		{ name = "buffer" },
	}),
})

```
