### ISSUE TITLE
Extra undo point is created after enter

### ISSUE THREAD

**Issue by rob-3** [hrsh7th/nvim-cmp#1144]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

After using enter to `confirm()` a completion, undoing the insert action with the completion requires `uu` to undo, with one undo seemingly doing nothing.

### Steps to reproduce

1. `nvim -u ~/cmp-repro.vim hello.txt`
2. Enter insert mode with `i`.
3. Type `hello`.
4. Exit insert mode with `<Esc>`.
5. Type `oh`.
6. Accept nvim-cmp's completion with `<CR>`.
7. Exit insert mode with `<Esc>`.
8. Type `u`. Observe that nothing is undone.
9. Type `u` again. Notice that the change is undone.

### Expected behavior

As above, but the insertion (or at least the completion expansion) should be undone on the first `u` leaving either nothing or `h`.

### Actual behavior

Typing `u` twice is necessary to undo the insertion.

**Comment by hrsh7th** [comment]
Thank you. I've added the undojoin.

**Comment by rob-3** [comment]
Wow - that was incredibly fast! It works as expected now. Thanks for getting this fixed and for making `nvim-cmp`!
