### ISSUE TITLE
Confirmation behavior `Replace` does not work 

### ISSUE THREAD

**Issue by przepompownia** [hrsh7th/nvim-cmp#1146]
I have copied from `lua/cmp/config/default.lua` and modified:
```lua
  confirmation = {
    default_behavior = cmp.ConfirmBehavior.Replace,
  },
```
It worked previously (see #1115) but currently it works like for `Insert`. Using `git bisect` I found that it's broken from 49c4050e.

**Comment by abalmos** [comment]
I can confirm that I am seeing the same behavior

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/pull/1148 fixes your problem?

**Comment by przepompownia** [comment]
Yes, it fixes confirmation, thanks. Please respect it in `select_next_item` and `select_prev_item` too.
