### ISSUE TITLE
[Question] How to get syntax highlighting in autocompletion menu..?

### ISSUE THREAD

**Issue by AmitKumarHQ** [hrsh7th/nvim-cmp#1157]
I was setting up nvim with nvim-cmp, but I can't figure out how can I get the nice syntax highlighting in the autocompletion menu.
![image](https://user-images.githubusercontent.com/94821119/187020524-7d6397ff-ba62-4fce-9e2d-0b97242c6dc1.png)

**Comment by Dawn-K** [comment]
Are you talking about highlighting of selected characters? I think this  [document](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu) might help you.
Just set your color according to this document (and maybe adjust your background color appropriately)

**Comment by hrsh7th** [comment]
You should use colorscheme that supports nvim-cmp highlights.
