### ISSUE TITLE
[clangd] selecting method name & pressing CR deletes the partial method name

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [hrsh7th/nvim-cmp#1158]
I have set up nvim-cmp & use it mostly for Python and C++.

In Python, completion works great (I enter a part of the method name, get suggestions, select one, press enter and - voila! the method name is completed)

In C++ (clangd LSP), however, I do exactly the same thing, but instead of completing the method name, pressing "enter" deletes the part of the function name I have already written.

TBH, since it works for Python (pyright), but not for clangd, I am very confused & any help would be much appreciated!

**Comment by lvimuser** [comment]
Possible duplicate of https://github.com/hrsh7th/nvim-cmp/issues/1156 ?

**Comment by tobi-wan-kenobi** [comment]
@lvimuser I thought so as well, but I am not using replace mode. I *will* try the patch, however and see if the situation improves.

I also tried with tag v0.0.1 and had exactly the same issue.

**Comment by tobi-wan-kenobi** [comment]
Added a more comprehensive description with minimal config, steps to reproduce, sample C++ code that demonstrates the issue, in #1161
