### ISSUE TITLE
Keep original text instead of having temporary inserted text

### ISSUE THREAD

**Issue by spywhere** [hrsh7th/nvim-cmp#116]
This ticket is a follow up to #97

When the suggestion is selected/deselected, text is changed back and forth between original text and expanded text.

Take a look in this video. You'll see that when I select/deselect the suggestion, the code kept changing from the original text (`table>tr*4>td*3`) to expanded one (`<table>`).

https://user-images.githubusercontent.com/1087399/131258369-4255cfe4-4a6b-4f0a-8d8a-4471ca884dac.mov

**Comment by hrsh7th** [comment]
This is the most complex thing of implementing an LSP complementary plugin.

First, we need to see how VSCodes works.

https://user-images.githubusercontent.com/629908/131258441-002db650-5911-4d68-9048-d674ef28c2f5.mp4

Yes. VSCode has no temporary inserted text.
And also, it is not defined in the LSP specification.

So some LSP plugins make it in their own way.

**Comment by hrsh7th** [comment]
Haha. coc.nvim is worked as the same. It will choose `#` as temporary inserted text in this case.

**Comment by spywhere** [comment]
> Haha. coc.nvim is worked as the same. It will choose `#` as temporary inserted text in this case.

Interesting finding. I haven't use coc.nvim for quite some time now, so I don't have a chance to notice it. :laughing:

Anyway, feel free to keep or close this ticket. I think it could fall into enhancement category here if that's the behavior usually get implemented.

**Comment by hrsh7th** [comment]
I think we should continue to improve this but I close this for now.
