### ISSUE TITLE
Add scroll off in cmp window

### ISSUE THREAD

**Issue by NEX-S** [hrsh7th/nvim-cmp#1165]
Sometimes when we navigate through the pop-up menu but accidentally miss the result we want in subconscious

Maybe setting the scroll off in the cpm window would be a good idea :D

**Comment by Shougo** [comment]
What do you mean the scroll off?
I think more detailed information is needed.

**Comment by hrsh7th** [comment]
It's valid request. You can create PR. :)

**Comment by Shougo** [comment]
I recommend for you to upload the screenshot before/after for the feature.

**Comment by hrsh7th** [comment]
No. nvim-cmp uses floating window for showing popup-menu. So we already can implement this feature.

**Comment by hrsh7th** [comment]
Added scrolloff option.
