### ISSUE TITLE
Characters from regular expressions are taken as trigger characters 

### ISSUE THREAD

**Issue by danielo515** [hrsh7th/nvim-cmp#1167]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```
Will provide it latter, I promise 

### Description

Given the following snippets:

```lua
  s({ trig = "(%w+)tmap", dscr = "Wrap current table with a map method", regTrig = true }, {
    t "vim.tbl_map(",
    l(l.CAPTURE1, {}),
    i(0),
    t ")",
  }),

```

I don't expect it to appear when I type a literal parenthesis as an expansion option, but it does:

![image](https://user-images.githubusercontent.com/2270425/187646332-f956b022-fa2f-4c2a-a0ac-e0cc7fb22909.png)

### Steps to reproduce

Just trigger the snippets using part of the snippet regex

### Expected behavior

I expect to not get suggestions when typing parts of the capture group 

### Actual behavior

When I type a parenthesis the snippet appears 

### Additional context

Thank you for this awesome extension.
Related issue on LuaSnip repo: L3MON4D3/LuaSnip/issues/563

**Comment by hrsh7th** [comment]
You should open issue on `cmp_luasnip` repo (The `L3MON4D3` was intented this).

**Comment by danielo515** [comment]
@L3MON4D3 suggested that I should open an issue in this repository, so that's why  did because I trust he understands the issue better tahn me

**Comment by L3MON4D3** [comment]
Oh nono, I did mean `cmp_luasnip`, it's where the completion-items for Luasnip-snippets are generated, and where this can be addressed

**Comment by danielo515** [comment]
Oh sorry, how dumb from my side! Thanks for pointing it out
