### ISSUE TITLE
How to setting maxwidth

### ISSUE THREAD

**Issue by enricofadly** [hrsh7th/nvim-cmp#1169]
hello i know nothing about lua and i want to use this menu setup but i dont know how to limit the pop up only 50, 
could anyone tell me how to do it? thanks in advance 

  formatting = {
    fields = { "kind", "abbr" },
    format = function(_, vim_item)
      vim_item.kind = cmp_kinds[vim_item.kind] or ""
      return vim_item
    end,
  },

**Comment by Shougo** [comment]
This?

https://github.com/hrsh7th/nvim-cmp/issues/980

**Comment by enricofadly** [comment]
thanks mate, i closed this
