### ISSUE TITLE
Erorr when using keyword_pattern

### ISSUE THREAD

**Issue by Eternex49** [hrsh7th/nvim-cmp#1170]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'

Plug 'hrsh7th/cmp-omni'
Plug 'lervag/vimtex'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "omni", keyword_pattern = { vim.g["vimtex#re#neocomplete"] } },
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

The cmp-omni source is used to get suggestions provided by vimtex.

Ideally, after typing a `\cite{` statement, the completion menu should appear with a list of possible bibliographical citations (provided, obviously, by vimtex).
Instead to get the completion menu to appear one has to type at least one character after the `\cite{` statement, ie: `\cite{a`.

To make the completion menu appear without having to type at least one character I've added a keyword pattern to the source. I've used the one provided by vimtex for neocomplete ( vimtex doesn't provide one for cmp, but I think it should work the same):
```
let g:vimtex#re#neocomplete =
      \ '\v\\%('
      \ .  '%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|%(\a*cites|Cites)%(\s*\([^)]*\)){0,2}'
      \     . '%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*'
      \     . '%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|bibentry\s*\{[^}]*'
      \ . '|%(text|block)cquote\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|%(for|hy)\w*cquote\*?\{[^}]*}%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|defbibentryset\{[^}]*}\{[^}]*'
      \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
      \ . '|hyperref\s*\[[^]]*'
      \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|%(include%(only)?|input|subfile)\s*\{[^}]*'
      \ . '|([cpdr]?(gls|Gls|GLS)|acr|Acr|ACR)\a*\s*\{[^}]*'
      \ . '|(ac|Ac|AC)\s*\{[^}]*'
      \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|%(usepackage|RequirePackage|PassOptionsToPackage)%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|begin%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|end%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|\a*'
      \ . ')'
```

### Steps to reproduce

1. Put the following files in a folder:
test.bib
```
@article{foo11,
    author={Author A.},
    title={Example article}
}

@book{bar11,
    author={Author B.},
    title={Example book}
}
```
test.tex
```
\documentclass{article}
\bibliographystyle{plain}

\begin{document}

This is a citation:
\cite{

\bibliography{./test.bib}
\end{document}
```
2. Download vimrc.vim
3. `nvim -u vimrc.vim test.tex`
4. Enter insert mode at the end of the `\cite{` line

### Expected behavior

After a `\cite{` statement, the completion menu should appear suggesting the possible bibliographical citations.

### Actual behavior

After positioning at the end of the `\cite{` line the completion menu doesn't appear. Typing a letter results in a bunch of errors.

**Comment by Shougo** [comment]
I think neocompletion pattern does not work.
Please see both.

https://github.com/hrsh7th/nvim-cmp/issues/258
https://github.com/lervag/vimtex/issues/2215

**Comment by hrsh7th** [comment]
Your specified value is wrong.
The keyword_pattern should be `string` but you specified `array`.

You should paste error message if you sent bug report.

I think @Shougo's suggestion is correct. In my knowledge, `vimtex#re#neocomplete` wont work. (but I don't know the reason)
