### ISSUE TITLE
[feature request] Completions on prompt

### ISSUE THREAD

**Issue by pro-anon** [hrsh7th/nvim-cmp#1171]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
````

### Description

Support completions with prompts, `input()`

https://github.com/neovim/neovim/pull/18284

### Steps to reproduce

Completions don't appear in prompts made with `vim.fn.input()`

### Expected behavior

Completions, specially path completions, appear in prompts invoked with `input()`

### Actual behavior

No completions appear

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/938

**Comment by shadyalfred** [comment]
Is installing
ddc.vim, ddc-cmdline, and pum.vim enough to make completions work with nvim-cmp or is this just for your alternative completion framework ddc?
@Shougo

**Comment by Shougo** [comment]
`nvim-cmp` uses original popup menu framework.  So `nvim-cmp` cannot use it.
`nvim-cmp` already implement `ddc-cmdline` feature.
`ddc-input` feature is needed.

**Comment by hrsh7th** [comment]
Sorry. I don't plant this.
