### ISSUE TITLE
Is there any options can remove `~` in snippet completion window?

### ISSUE THREAD

**Issue by NEX-S** [hrsh7th/nvim-cmp#1173]
I'm wondering how to remove `~ `in the completion window like `for ~` to `for`, I think the icon already shows us that this item is a snippet, and it's expandable, so `~` in the completion window feels a bit redundant, does that make sense?

![Screenshot from 2022-09-02 08-28-31](https://user-images.githubusercontent.com/97107165/188130322-b4ce5567-e3a2-4523-a3f7-4b5e8d6a2008.png)

I have found it in entry.lua: 238
```lua
    -- ~ indicator
    local is_snippet = false
    if #(misc.safe(completion_item.additionalTextEdits) or {}) > 0 then
      is_snippet = true
    elseif completion_item.insertTextFormat == types.lsp.InsertTextFormat.Snippet then
      is_snippet = self:get_insert_text() ~= word
    elseif completion_item.kind == types.lsp.CompletionItemKind.Snippet then
      is_snippet = true
    end
    if is_snippet then
      abbr = abbr .. "~" <------------------------ HERE
    end
```

**Comment by hrsh7th** [comment]
The `~` is appended if the `item is snippet` or `item has additionalTextEdit` so it's `expandable` indicator.

I can add the `formatting.expandable_indicator = false` option. PR welcome.
