### ISSUE TITLE
Autocompletion not working for html

### ISSUE THREAD

**Issue by Leo-Zarni01** [hrsh7th/nvim-cmp#1178]
Hello, so I have installed vscode language server according to the guide shown in this page: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#html.

However, it seems that even though the language server is installed and is working, the autocomplete feature seems to be not working. I have followed the instructions on that page and even enabled the snippet (LuaSnippet) but nothing shows up in autocompletion. 

Here are the images below for your reference:
![image](https://user-images.githubusercontent.com/50450659/190210375-2946658f-8aec-4a4d-9f70-e32a88d02d60.png)
![image](https://user-images.githubusercontent.com/50450659/190210444-e570f1e0-8ce9-4208-b5e0-6e08a0b12463.png)
![image](https://user-images.githubusercontent.com/50450659/190210506-c03ccfb6-7f7c-4e29-91a7-2072c03f6e8b.png)
![image](https://user-images.githubusercontent.com/50450659/190210653-7619260f-f89f-41fc-b0fb-0fa1a0023d4b.png)

Looking forward for your help, thank you!

**Comment by hrsh7th** [comment]
I can't help without reproducible steps and I can't reproduce this issue.
