### ISSUE TITLE
Completions are filtered after being returned by a callback. Can this be turned off somehow?

### ISSUE THREAD

**Issue by rwblokzijl** [hrsh7th/nvim-cmp#1179]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

using only cmp-spell
```vim
    Plug 'hrsh7th/nvim-cmp'
    Plug 'f3fora/cmp-spell'
```
```lua
cmp.setup({
  preselect = cmp.PreselectMode.None,

  mapping = cmp.mapping.preset.insert({
    ["<C-n>"] = cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Insert },
    ["<C-p>"] = cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Insert },
  }),

  sources = cmp.config.sources({
    { name = 'spell' },
  }),
})

```

### Description

Using the spell extentsion: all the suggestions from spell should be shown.
![2022-09-17-010254_295x100_scrot](https://user-images.githubusercontent.com/446634/190828753-8cdfa238-9e80-488b-8fd3-b26b73f53ff7.png)

cmp-spell uses vim builtin spelling correction, which should return:

![2022-09-17-010753_209x427_scrot](https://user-images.githubusercontent.com/446634/190828976-3dafc2a4-a299-4401-a7ab-04c41f9c5b72.png)

I also tried adding the entry_filter, but this achieved nothing. I would expect there to be an option that turns this filtering off, but cant find anything that worked.

### Steps to reproduce

- Use the extentions above, and the lua config provided.
- Try to complete a misspelled word.

### Expected behavior

all the suggestions from spellcorrect should be shown

### Actual behavior

Only the suggestions where the characters are a superset of the matched word are shown.

### Additional context

I checked their code, and they return everything correctly in their callback, but nvim-cmp filters it after the fact.

**Comment by hrsh7th** [comment]
This is not a bug and you should open feature-request to the source repo.

**Comment by rwblokzijl** [comment]
@hrsh7th The source returns the whole list properlt. It's nvim-cmp that does some additional filtering that breaks this.

**Comment by bew** [comment]
If I understand correctly, the behavior is because cmp is using fuzzy search, so it filters all entries that do not have all the letters of the word you entered in the buffer.

To try to clarify, it looks like you want a very specific behavior for spell suggestions:
- do not apply cmp's filtering (but you probably want it for other sources)
- and probably also want the spell source to be queried for each char? (not sure whar this would give you performance wise, maybe only update after N millisecond of idling?)

Not sure if this behavior is already possible with cmp though.

**Comment by f3fora** [comment]
> This is not a bug and you should open feature-request on the source repo.

f3fora/cmp-spell#6

> and probably also want the spell source to be queried for each char?

This is what currently happens, and is achieve setting [`isIncomplete = true`]( https://github.com/f3fora/cmp-spell/blob/5602f1a0de7831f8dad5b0c6db45328fbd539971/lua/cmp-spell/init.lua#L25). It is not a performance issue.

> do not apply cmp's filtering (but you probably want it for other sources)

I think in the beginning of `nvim-cmp` this filter wasn't applied and all `vim.fn.spellsuggest` outcomes were displayed. Then fuzzy search was implemented.

**Does a way to disable the fuzzy search for a single source exist?**

**Comment by hrsh7th** [comment]
I think `isIncomplete = true` and `item.filterText` can be used to this.

I'm not aware of any completion engine that behaves like it doesn't filter certain completion types at all.

For the time being, I will try to implement it, but I think there will be no end if I receive all these requests. . .

**Comment by hrsh7th** [comment]
Hm... If we return whole items (it means does not apply any matching process), how to highlight matched text that contained in the completion menu?

**Comment by f3fora** [comment]
> `item.filterText` can be used to this

You are right. Setting  item.filterText as input should do the trick.

> For the time being, I will try to implement it, but I think there will be no end if I receive all these requests. . .

No need to implement anything ;-)

> Hm... If we return whole items (it means does not apply any matching process), how to highlight matched text that contained in the completion menu?

I don't get the problem.
Another problem would be setting a specific `comparator` for sorting a specific source.

**Comment by f3fora** [comment]
I find a way to solve this issue. See f3fora/cmp-spell#6

**Comment by yyy33** [comment]
> Hm... If we return whole items (it means does not apply any matching process), how to highlight matched text that contained in the completion menu?



How about not highlighting these items, but adding a slash under each of these items to indicate that they all match?
