### ISSUE TITLE
Only takes from the buffer

### ISSUE THREAD

**Issue by kul-sudo** [hrsh7th/nvim-cmp#1182]
https://user-images.githubusercontent.com/95244851/191269571-b397ef7d-c44e-48ae-b058-530df2e5e8f2.mp4

Hello, people.
For some reason, my nvim-cmp only does the autocompletion from the buffer of the words I have already used in the file. I do have the LSP as I use the well-known Devaslife config, and everything should work fine.
Do you guys know why it happens?

**Comment by Shougo** [comment]
You should upload the minimal init.vim
