### ISSUE TITLE
cmdheight=0 might cause cmp redraw issue in neovim-nightly

### ISSUE THREAD

**Issue by NEX-S** [hrsh7th/nvim-cmp#1183]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
nvim_cmp.setup.cmdline(':', {
    mapping = nvim_cmp.mapping.preset.cmdline(),
    sources = {
        { name = 'cmdline' },
        { name = 'cmdline_history' },
    },
})
```

### Description

![image](https://user-images.githubusercontent.com/97107165/191465768-3b1309b4-da59-4cce-831f-4b3d54e1d192.png)

![image](https://user-images.githubusercontent.com/97107165/191466609-a1ee6061-714e-4ea6-8ac6-7fdcedb8c6bb.png)

### Steps to reproduce

set cmdheight=0
enter cmd mode and input someting
the completion window will not disappear when done.

### Expected behavior

the completion window disappear when done.

### Actual behavior

the completion window will not disappear when done.

### Additional context

NVIM v0.8.0-dev-1120-ga0e6e767a

**Comment by Shougo** [comment]
It is neovim problem instead of nvim-cmp.
Please test https://github.com/neovim/neovim/pull/20249.
