### ISSUE TITLE
[Question]: Auto Highlight

### ISSUE THREAD

**Issue by chenyekun1** [hrsh7th/nvim-cmp#1191]
How to configure auto highlight first item in popup menu when typing?

![image](https://user-images.githubusercontent.com/24608750/192109625-ad6aabe1-8c5f-4a0d-9381-75fa060d7b53.png)
(the first item is not auto highlight)

**Comment by Shougo** [comment]
You can change completeopt for it.

```vim
set completeopt+=noinsert
```

**Comment by chenyekun1** [comment]
> 

it doesn't work.

**Comment by Shougo** [comment]
Hm...  I will take look later.

**Comment by hrsh7th** [comment]
```lua
require'cmp'.setup {
  completion = {
    completeopt = 'menu,menuone,noinsert'
  }
}
```

it may be work.

**Comment by hrsh7th** [comment]
I can't understand `first item auto highlight` so this solution might not work for you.
I hope to work this solution to this problem.

**Comment by chenyekun1** [comment]
> 

It works very well!
