### ISSUE TITLE
How to write source plugins?

### ISSUE THREAD

**Issue by kflak** [hrsh7th/nvim-cmp#1205]
Hi, and thanks for a life-saving plugin!

I would like to create a source for nvim-lilypond-suite, but I can't find any noob-friendly documentation on how to write such a thing, given a list of dictionary files with the following structure:
```
$LILYDICTPATH/grobs
$LILYDICTPATH/keywords
$LILYDICTPATH/musicFunctions
$LILYDICTPATH/articulations
$LILYDICTPATH/grobProperties
$LILYDICTPATH/paperVariables
$LILYDICTPATH/headerVariables
$LILYDICTPATH/contextProperties
$LILYDICTPATH/clefs
$LILYDICTPATH/repeatTypes
$LILYDICTPATH/languageNames
$LILYDICTPATH/accidentalsStyles
$LILYDICTPATH/scales
$LILYDICTPATH/musicCommands
$LILYDICTPATH/markupCommands
$LILYDICTPATH/contextsCmd
$LILYDICTPATH/dynamics
$LILYDICTPATH/contexts
$LILYDICTPATH/translators
```

These are all, AFAICT files with keywords separated by newlines.

Any help much appreciated!

**Comment by hrsh7th** [comment]
Did you see this help? https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L700

**Comment by kflak** [comment]
Great, exactly what I was looking for! Looking at the example, it seems I should be able to iterate over a bunch of text files using standard lua functions to populate the callback? So that each `{ label = x }` is a candidate for completion?

**Comment by hrsh7th** [comment]
yes. You seem to have got it right.
