### ISSUE TITLE
<CR> confirm mapping autocomplete not working

### ISSUE THREAD

**Issue by robbienohra** [hrsh7th/nvim-cmp#1208]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require "cmp"

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
    end,
  },
  mapping = {
    ["<Left>"] = cmp.mapping(cmp.mapping.select_prev_item(), { "i", "c" }),
    ["<Right>"] = cmp.mapping(cmp.mapping.select_next_item(), { "i", "c" }),
    ["<C-b>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "c" }),
    ["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "c" }),
    ["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
    ["<C-y>"] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
    ["<C-e>"] = cmp.mapping {
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    },
    ["<CR>"] = cmp.mapping.confirm { select = true }, -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  },
  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "vsnip" }, -- For vsnip users.
  }, {
    { name = "buffer" },
  }),
}

cmp.setup.filetype("gitcommit", {
  sources = cmp.config.sources({
    { name = "cmp_git" },
  }, {
    { name = "buffer" },
  }),
})

cmp.setup.cmdline("/", {
  sources = {
    { name = "buffer" },
  },
})

cmp.setup.cmdline(":", {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = "path" },
  }, {
    { name = "cmdline" },
  }),
})
```

### Description

I have this recommended config:

```lua
    ["<CR>"] = cmp.mapping.confirm { select = true }, -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
```

However, in `cpp` when I type `#include` — I see the options to select, but when I do select an option (by hitting enter) the cursor remains in the same position and does not move & auto-insert quotes (to continue entering a package).

<img width="345" alt="image" src="https://user-images.githubusercontent.com/28514482/193470120-46577266-7390-49b6-bc99-22637ec4f9ed.png">

<img width="356" alt="image" src="https://user-images.githubusercontent.com/28514482/193470129-fd7b4d27-ec43-42f9-ba51-449801712c15.png">

### Steps to reproduce

Create a `cpp` file. Type `#include`. Select an option (by hitting enter). Note that the cursor remains in the same position and does not move & auto-insert quotes (to continue entering a package).

### Expected behavior

Cursor should auto-insert quotes when trying to include a `cpp` package when selecting an option (by hitting enter).

### Actual behavior

Cursor remains in the same position and does not move & auto-insert quotes (to continue entering a package) upon selection (when hitting the enter key).

### Additional context

If this is not an `nvim-cmp` issue but rather a `clangd` language server issue then I'd be happy to be pointed in the right direction to better troubleshoot it at that level.

**Comment by robbienohra** [comment]
For what it's worth I'm observing the same issue for other auto-completions for example `namespace`. The cursor lands in front of `namespace` without auto-inserting quotes.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/28514482/193470644-d85ee5b1-1eab-4357-ba62-f1ed2829224f.png">

<img width="230" alt="image" src="https://user-images.githubusercontent.com/28514482/193470674-4b2eca44-2d27-4319-aa1f-aad735de0c11.png">

**Comment by tom-pollak** [comment]
I think its an issue with 0.8, rolling back to 0.7.2 worked for me

**Comment by robbienohra** [comment]
Oh dang 🤔 

Yeah I'm on version `0.8` of `neovim` — likely worth leaving the thread open regardless, but thanks for the clue!

**Comment by hrsh7th** [comment]
What do you use snippet engine?

**Comment by robbienohra** [comment]
Not consciously using a particular one tbh I just have the recommended configs from the doc re. the snippet engine

```
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-cmdline",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-vsnip",
    "hrsh7th/nvim-cmp",
    "hrsh7th/vim-vsnip",
    "hrsh7th/vim-vsnip-integ",
```

```
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
    end,
  },

...

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "vsnip" }, -- For vsnip users.
  }, {
    { name = "buffer" },
  }),

```


so I'm thinking `vsnip`?

**Comment by hrsh7th** [comment]
Ah Sorry. OK. You use vsnip.

What do you use LSP servers? Is the `include "header"~` snippet came from?

**Comment by robbienohra** [comment]
Np! I'm using mason + lsp here's my `lsp` config:

```lua
local util = require "lspconfig.util"
local lspconfig = require "lspconfig"

require("mason").setup {}

require("mason-lspconfig").setup {

  automatic_installation = true,

  ensure_installed = {
    "bash-language-server",
    "clangd",
    "eslint-lsp",
    "json-lsp",
    "lua-language-server",
    "pyright",
    "rust-analyzer",
    "shfmt",
    "sqlls",
    "svelte-language-server",
    "typescript-language-server",
    "vue-language-server",
    "yaml-language-server",
  },
}

-- disable formatting for cases where null-ls is the desired default
-- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities
local function on_attach(client)
  client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentFormattingProvider = false
end

lspconfig.bashls.setup { on_attach = on_attach }
lspconfig.clangd.setup {}
lspconfig.jsonls.setup { on_attach = on_attach }
lspconfig.tsserver.setup { on_attach = on_attach }
lspconfig.volar.setup { on_attach = on_attach }
lspconfig.yamlls.setup { on_attach = on_attach }

local sumneko_opts = require "user.lsp.settings.sumneko_lua"
lspconfig.sumneko_lua.setup(sumneko_opts)


local capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())

util.default_config = vim.tbl_extend("force", util.default_config, {
  autostart = true,
  capabilities = capabilities,
})

require "user.lsp.null-ls"
```

**Comment by robbienohra** [comment]
So it would be `clangd`:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/28514482/193502183-de1e4179-5c89-4488-96ad-266cfccfab39.png">

**Comment by robbienohra** [comment]
@hrsh7th no luck? 😅

**Comment by hrsh7th** [comment]
I can't reproduce on my local clangd. I'll update it and then try again reproducing step.

**Comment by hrsh7th** [comment]
I can't reproduce. Could you try again with the latest nvim-cmp?

**Comment by fidelski** [comment]
I was facing the same issue - but only on one machine! I have a git repo for my neovim configuration and the exact same setup was working on one machine with neovim 0.8.0 and not on the other with exactly the same neovim version. The issue came up after updating the system. For me the problem was the installed version of pynvim that I had installed with pip, after I removed it with pip and installed the version from my package manager completion works again. Might be because I am using ultisnips that is written in Python and therefore not apply to other snippet engines.

Btw. Thank you for this awesome plugin!

**Comment by fidelski** [comment]
Which snippet engine do you use?

**Comment by risico** [comment]
I managed to pin point it down to the `capabilities` option being set in my lsp configs. 

```
local function config(_config)
	return vim.tbl_deep_extend("force", {

                 -- commenting this fixed the issue 
		-- capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities()),


	}, _config or {})
end

require("lspconfig").gopls.setup(config({
	cmd = { "gopls", "serve" },
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
			staticcheck = true,
		},
	},
}))
```

**Comment by fidelski** [comment]
Hm, I guess at that point it is not guaranteed that the lsp server is setup already. You might want to update the capabilities as soon as or even better after it is launched. You can do this that way:
```lua
local function get_forced_lsp_capabilities ()
    local capabilities = vim.lsp.protocol.make_client_capabilities ()
    capabilities.textDocument.completion.completionItem.snippetSupport = true
    capabilities.textDocument.completion.completionItem.resolveSupport = {
        properties = { "documentation", "detail", "additionalTextEdits" },
    }
    return capabilities
end

local function my_lsp_on_attach (client, bufnr)
...
require ('cmp_nvim_lsp').update_capabilities (get_forced_lsp_capabilities ())
end


lspconfig.util.default_config = vim.tbl_deep_extend ('force',
                                                    lspconfig.util.default_config, {
    on_attach = my_lsp_on_attach,
    capabilities = get_forced_lsp_capabilities ()
})
```
That way the capabilities get updated whenever the a buffer gets attached to the language server.

**Comment by robbienohra** [comment]
I tried the above but no cigar 😞 

Here is my current LSP config setup — @risico @fidelski do you see anything suspect re. my `capabilities` call sequence?

**Comment by robbienohra** [comment]
Tried this for example but no cigar:

```lua
local util = require "lspconfig.util"
local lspconfig = require "lspconfig"

require("mason").setup {}

require("mason-lspconfig").setup {

  automatic_installation = true,

  ensure_installed = {
    "bash-language-server",
    "clangd",
    "eslint-lsp",
    "json-lsp",
    "lua-language-server",
    "pyright",
    "rust-analyzer",
    "shfmt",
    "sqlls",
    "svelte-language-server",
    "terraform-ls",
    "typescript-language-server",
    "vue-language-server",
    "yaml-language-server",
    "yamlfmt",
  },
}

-- disable formatting for cases where null-ls is the desired default
-- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities
local function on_attach(client)
  client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentFormattingProvider = false
end

lspconfig.bashls.setup { on_attach = on_attach }
lspconfig.clangd.setup {}
lspconfig.jsonls.setup { on_attach = on_attach }
lspconfig.terraformls.setup { on_attach = on_attach }
lspconfig.tsserver.setup { on_attach = on_attach }
lspconfig.volar.setup { on_attach = on_attach }
lspconfig.yamlls.setup { on_attach = on_attach }

local sumneko_opts = require "user.lsp.settings.sumneko_lua"
lspconfig.sumneko_lua.setup(sumneko_opts)

local function get_forced_lsp_capabilities()
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  capabilities.textDocument.completion.completionItem.resolveSupport = {
    properties = { "documentation", "detail", "additionalTextEdits" },
  }
  return capabilities
end

local function my_lsp_on_attach(client, bufnr)
  require("cmp_nvim_lsp").update_capabilities(get_forced_lsp_capabilities())
end

util.default_config = vim.tbl_extend("force", util.default_config, {
  autostart = true,
  on_attach = my_lsp_on_attach,
  capabilities = get_forced_lsp_capabilities(),
})

require "user.lsp.null-ls"
```

**Comment by robbienohra** [comment]
@hrsh7th there was [this discussion](https://github.com/williamboman/nvim-lsp-installer/discussions/636#discussioncomment-2670359) that I commented on back in May that is likely relevant

**Comment by fidelski** [comment]
Hm, honestly I don't know whether it matters but you call setup on the language servers and _then_ you set the default config. I would try to
1. Setup the default config
2. Then call the setup function of the language servers

So in the `on_attach` callback I would call `require("cmp_nvim_lsp").update_capabilities` - for all servers. So if you write your callback, then setup the default config with that callback and then call setup on the language servers things should be fine. You can always override settings in the setup call but if you are happy with the defaults you can simply call setup with an empty table.

```lua
local function get_forced_lsp_capabilities()
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  capabilities.textDocument.completion.completionItem.resolveSupport = {
    properties = { "documentation", "detail", "additionalTextEdits" },
  }
  return capabilities
end

local function my_lsp_on_attach(client, bufnr)
  require("cmp_nvim_lsp").update_capabilities(get_forced_lsp_capabilities())
end

util.default_config = vim.tbl_extend("force", util.default_config, {
  autostart = true,
  on_attach = my_lsp_on_attach,
  capabilities = get_forced_lsp_capabilities(),
})

lspconfig.bashls.setup {}
lspconfig.clangd.setup {} -- You might want to consider p00f/clangd_extensions.nvim, it gives you special features
lspconfig.jsonls.setup {}
lspconfig.terraformls.setup {}
lspconfig.tsserver.setup {}
lspconfig.volar.setup {}
lspconfig.yamlls.setup {}
```

**Comment by robbienohra** [comment]
It looks like that did the trick, thanks a bunch!

**Comment by hrsh7th** [comment]
Thank you for community help!!!

**Comment by fidelski** [comment]
Thank you for bringing this awesome plugin to the community! :heart:
