### ISSUE TITLE
Inserting comma confirms the preselected list item

### ISSUE THREAD

**Issue by dainiusm07** [hrsh7th/nvim-cmp#121]
Is it possible to somehow disable selection confirmation on , ? 
https://user-images.githubusercontent.com/44223680/131375501-99ff6a97-80f6-49f5-a58d-1faaaff53940.mov

**Comment by hrsh7th** [comment]
Currently, no. I will add the option for it.

**Comment by hrsh7th** [comment]
I've added `confirmation.get_commit_characters` option.

You can do it.

```lua
cmp.setup {
  confirmation = {
    get_commit_characters = function(commit_characters)
      return vim.tbl_filter(function(char)
        return char ~= ','
      end, commit_characters)
    end
  }
}
```
