### ISSUE TITLE
How can I unbind arrow keys

### ISSUE THREAD

**Issue by amarakon** [hrsh7th/nvim-cmp#1210]
This plugin binds arrow keys up and down to next and previous respectively. I only use <kbd>Control</kbd><kbd>N</kbd> and <kbd>Control</kbd><kbd>P</kbd>. I would like to unbind the arrow keys so that I can actually use them to go up and down.

**Comment by hrsh7th** [comment]
You can fully manage key mapping by yourself.
You should read the docs to understand key-mapping configuration.

**Comment by smzm** [comment]
It should probably work.
```lua
 ['<Up>'] = cmp.mapping(function(fallback)
    fallback() -- Allows Up arrow to fall back without interacting with cmp
  end, { 'i', 'c' }),

  ['<Down>'] = cmp.mapping(function(fallback)
    fallback() -- Allows Down arrow to fall back without interacting with cmp
  end, { 'i', 'c' }),
```
