### ISSUE TITLE
CI failed

### ISSUE THREAD

**Issue by yuys13** [hrsh7th/nvim-cmp#1215]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

Recently CI has failed due to two reasons.
One is not running stylua.
The other is `vusted lua` is failing.

### Steps to reproduce

`make integration`

### Expected behavior

CI is a success.

### Actual behavior

https://github.com/hrsh7th/nvim-cmp/actions/runs/3168929547/jobs/5160482542
```
./utils/stylua --config-path stylua.toml --check --glob 'lua/**/*.lua' -- lua
Diff in lua/cmp/entry.lua:
23[9](https://github.com/hrsh7th/nvim-cmp/actions/runs/3168929547/jobs/5160482542#step:8:10) 239  |     local is_expandable = false
240 240  |     local expandable_indicator = config.get().formatting.expandable_indicator
241 241  |     if #(misc.safe(completion_item.additionalTextEdits) or {}) > 0 then
242      |-    is_expandable = true
    242  |+      is_expandable = true
243 243  |     elseif completion_item.insertTextFormat == types.lsp.InsertTextFormat.Snippet then
244      |-    is_expandable = self:get_insert_text() ~= word
    244  |+      is_expandable = self:get_insert_text() ~= word
245 245  |     elseif completion_item.kind == types.lsp.CompletionItemKind.Snippet then
246      |-    is_expandable = true
    246  |+      is_expandable = true
247 247  |     end
248 248  |     if expandable_indicator and is_expandable then
249      |-    abbr = abbr .. '~'
    249  |+      abbr = abbr .. '~'
250 250  |     end
251 251  | 
252 252  |     -- append delta text
Diff in lua/cmp/utils/api.lua:
48  48   | api.get_cursor = function()
49  49   |   if api.is_cmdline_mode() then
50  50   |     return { math.min(vim.o.lines, vim.o.lines - (vim.api.nvim_get_option('cmdheight') - 1)), vim.fn.getcmdpos() - 1 }
51       |-
52  51   |   end
53  52   |   return vim.api.nvim_win_get_cursor(0)
54  53   | end
make: *** [Makefile:[21](https://github.com/hrsh7th/nvim-cmp/actions/runs/3168929547/jobs/5160482542#step:8:22): integration] Error 1
Error: Process completed with exit code 2.
```
If there is no problem with formating
https://github.com/hrsh7th/nvim-cmp/actions/runs/3132729331/jobs/5085371648
```
not ok 24 - entry [ansiblels] 1
# lua/cmp/entry_spec.lua @ 293
# Failure message: lua/cmp/entry_spec.lua:325: Expected objects to be equal.
# Passed in:
# (string) 'blockinfile'
# Expected:
# (string) 'modified'
```

### Additional context

I have looked into what causes vusted to fail.
The commit that caused vusted to fail is [this](https://github.com/hrsh7th/nvim-cmp/commit/dd4173fceedc99706276be5eb4ad6c8e81ecfdf7).
In the source code before the fix, before and after [e:resolve(done)](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/entry_spec.lua#L323) in the test code, `e:get_vim_ item(e:get_offset())` resulted in the following
```
{
  abbr = "blockinfile",
  dup = 1,
  empty = 1,
  equal = 1,
  kind = "Class"
  menu = "",
  word = "blockinfile"
}
```
The test code succeeded before and after the execution of e:resolve(done), because it expects `blockinfile` for the value of word.

After the relevant commit, the cache is now cleared by e:resolve(done), so the subsequent `e:get_vim_item(e:get_offset())` is as follows.
```
{
  abbr = "blockinfile",
  dup = 1,
  empty = 1,
  equal = 1,
  kind = "Class",
  menu = "",
  word = "modified"
}
```
The test code states that the expected value for word is `blockinfile`, but in fact word is `modified`, so the test fails.

I have so far not been able to determine if the test code is incorrect or if there is an error in the modification. Therefore, I am reporting it.
I am willing to continue to investigate this issue.

**Comment by hrsh7th** [comment]
From the viewpoint of maintenance cost, we decided to delete the test case.
I'll think about it when the issue is submitted again.
