### ISSUE TITLE
cmp.mapping creates empty scratch buffers

### ISSUE THREAD

**Issue by bjdm** [hrsh7th/nvim-cmp#1217]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  -- commenting out mapping prevents unlisted buffer in ls!
  --mapping = {
  --  ['<CR>'] = cmp.mapping.confirm({ select = true })
  --},

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

Any call to cmp.setup.mapping creates an empty unlisted scratch buffer without bufhidden = wipe causing the bufferlist to be  polluted with empty scratch buffers

### Steps to reproduce

nvim -u ~/.vimrc.vim
:ls!

### Expected behavior

Calls to mapping do not create an empty scratch buffer

### Actual behavior

Each call to cmp.setup.mapping() creates an empty scratch buffer and leaves it in the bufferlist

### Additional context

Adding `api.nvim_buf_set_option(buf, 'bufhidden', 'wipe') ` prevents scratch buffers being created when added below [this line](https://github.com/hrsh7th/nvim-cmp/blob/e1f31778a8c4100d3195d7d98c3468aa0b004b66/lua/cmp/utils/buffer.lua#L22)

**Comment by tomtomjhj** [comment]
I don't understand why this is considered a bug. cmp creates several unlisted scratch buffer, and the keymap normalization buffer is just one of them. IMO, users are not supposed to care about the unlisted scratch buffers, and that is the exact reason they are unlisted.

The rationale of #991 is that we can just reuse the normalization buffer, instead of creating new ones every time cmp creates a mapping. This prevents cmp from rapidly increasing the buffer numbers, which I think is far more annoying than few unlisted scratch buffers.
