### ISSUE TITLE
omni completion as a source

### ISSUE THREAD

**Issue by nael8r** [hrsh7th/nvim-cmp#122]
With `nvim-compe`, one could add `omni` completion as a source doing the following:

```
  source = {
    omni = {
        filetypes = {'tex'},
    },
    ....
```

This was really nice since we could use `compe` with [vimtex](https://github.com/lervag/vimtex) completion, for example.

Is there any way to have the same feature in `nvim-cmp`?

**Comment by hrsh7th** [comment]
I have no plan.
I hope someone create it.

**Comment by mseri** [comment]
That's a pity, I hope this will get resolved one way or another, vimtex is my only blocker to move to nvim-cmp

**Comment by hrsh7th** [comment]
I've tried to support vimtex but vimtex's regular expression does not expose to the external plugin so I can't realize it.
