### ISSUE TITLE
Issue implementing Copilot

### ISSUE THREAD

**Issue by malisoft** [hrsh7th/nvim-cmp#1221]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: Vim:E433: No tags  tlast                        Variable
stack traceback:                                 tfirst                       Variable
        [C]: in function 'getcompletion'         tablast                      Variable
        ...e/pack/packer/start/cmp-cmdline/lua/c tabclose                     Variable
        ...e/pack/packer/start/cmp-cmdline/lua/c tabfirst                     Variable
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:314: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:287: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:169: in function 'callback'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:219: in function 'autoindent'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:310: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```

### Description

Problem with Copilot, conflict suggesting completation using snippets and copilot at same time

![image](https://user-images.githubusercontent.com/55772887/194777789-67265dac-3dae-42c9-89d1-71acb2c4387b.png)

i fixed making pull request

### Steps to reproduce

install Copilot and use cmp with ultisnips, then in a file try to get suggestions for a variable example: "ts_config", "my_app" or "ls_config" after white _ you will see this error. 

### Expected behavior

validate if can get a suggestion  or not

### Actual behavior

validate if there are not conflicts with others autocomplete code suggestions

**Comment by malisoft** [comment]
i fixed this problem,  making a pull request

**Comment by hrsh7th** [comment]
I think you enabled the copilot source for commandline-mode.
I can't guess your problem because you didn't provide the configuration.
