### ISSUE TITLE
Exception "Attempt to call field 'get_captures_at_pos'" making neovim unusable

### ISSUE THREAD

**Issue by TheStilbruch** [hrsh7th/nvim-cmp#1226]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Same as minimal config provided at https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

### Description

On inserts, commands, or most key presses an exception is thrown. 
`
Error executing vim.schedule lua callback: /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/config/context.lua:38: attempt to call field 'get_captures_at_pos' (a nil value)
stack traceback:
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/config/context.lua:38: in function 'in_treesitter_capture'
        /home/stilbruch/etc/nvim/lua/config/cmp.lua:59: in function 'enabled'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/config.lua:136: in function 'enabled'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/init.lua:298: in function 'callback'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/utils/async.lua:136: in function </tmp/plugged/vim-plug/nvim-cmp/lua/cmp/utils/async.lua:134>

`

### Steps to reproduce

Try inserting into a buffer

### Expected behavior

No exception

### Actual behavior

An exception, making it impossible to use nvim for anything

### Additional context

The error is pretty self explanatory, looks like something is being required that is returning nil. Seems to be an issue in the most recent commit.

**Comment by TheStilbruch** [comment]
[Offending line](https://github.com/hrsh7th/nvim-cmp/blob/0ad2450ff617a3568cc3f5e46f13635ef5185e6c/lua/cmp/config/context.lua#L38)
from [this commic](https://github.com/hrsh7th/nvim-cmp/commit/0ad2450ff617a3568cc3f5e46f13635ef5185e6c)

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/nvim-cmp/commit/99ef854322d0de9269044ee197b6c9ca14911d96
