### ISSUE TITLE
Enable colorscheme make nvim-cmp's auto-selection failed

### ISSUE THREAD

**Issue by tanchihpin0517** [hrsh7th/nvim-cmp#1229]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

init.lua
```lua
require('plugins')
require('autocomplete')

vim.cmd[[colorscheme tokyonight]]
```

autocomplete.lua
```lua
--vim.opt.completeopt = {'menu', 'menuone', 'noselect'}
vim.opt.completeopt = {'menu', 'menuone'}

-- Set up nvim-cmp.
local cmp = require'cmp'

cmp.setup({
  snippet = {
    -- REQUIRED - you must specify a snippet engine
    expand = function(args)
      -- vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
      --require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
      -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
      -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
    end,
  },
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-h>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  }),
  sources = cmp.config.sources(
  {
    { name = 'path' },
  },
  {
    { name = 'buffer' },
  }
  )
})

-- Set configuration for specific filetype.
cmp.setup.filetype('gitcommit', {
  sources = cmp.config.sources({
    { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
  }, {
    { name = 'buffer' },
  })
})

-- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' }
  }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
```

plugin.lua:
```lua
local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

return require('packer').startup({
function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  -- Theme
  use 'folke/tokyonight.nvim'

  -- auto complete
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'ray-x/cmp-treesitter'
  use 'hrsh7th/nvim-cmp'
  use { "L3MON4D3/LuaSnip", tag = "v1.*" }
  use 'saadparwaiz1/cmp_luasnip'

  -- Bootstrap
  if packer_bootstrap then
    require('packer').sync()
  end
end,

config = {
  display = {
    open_fn = require('packer.util').float, -- floating window
  }
}

})
```

### Description

I notice `vim.cmd[[colorscheme tokyonight]]` will make `vim.opt.completeopt = {'menu', 'menuone'}` behavior same as `vim.opt.completeopt = {'menu', 'menuone', 'noselect'}` (always NOT to auto-select the first suggestion)

I'm not sure it's `nvim_cmp`'s or colorscheme's problem. Just report it.

This screenshot shows that the suggestion is not auto-selected:
![](https://user-images.githubusercontent.com/10648553/195256584-5d80623c-e760-4777-a91b-9182940c6d4c.png)

If I comment the line of setting colorscheme like this:
```lua
require('plugins')
require('autocomplete')

--vim.cmd[[colorscheme tokyonight]]
```
The suggestion is auto-selected as expected:
![](https://user-images.githubusercontent.com/10648553/195256866-078c4471-7bb9-40ae-90bd-a4513fc416c5.png)

But I can still use `<c-n>` to select the suggestion manually like this:
![image](https://user-images.githubusercontent.com/10648553/195261934-fcaee307-8c83-43b2-9843-f58aaa5a6a62.png)
So I think the colorscheme supports `nvim_cmp`'s highlight.

### Steps to reproduce

1. Use the configuration above
2. Run `vim main.py`
3. Type the text as what `description` shows

### Expected behavior

The first suggestion should be auto-selected without `<c-n>` like this:
![](https://user-images.githubusercontent.com/10648553/195261934-fcaee307-8c83-43b2-9843-f58aaa5a6a62.png)
Edit: I know the text shouldn't be completed. I would like to focus on the part of auto-selection.

### Actual behavior

No auto-selection:
![](https://user-images.githubusercontent.com/10648553/195256584-5d80623c-e760-4777-a91b-9182940c6d4c.png)

**Comment by hrsh7th** [comment]
Try `cmp.config.completeopt = 'menu,menuone,noinsert'`
