### ISSUE TITLE
[Question] How to disable the filtering of cmp itself

### ISSUE THREAD

**Issue by yyy33** [hrsh7th/nvim-cmp#1233]
I looked at the `cmp-snip` code and found the function `source:complete(params, callback)`, which does the following steps (my guess) when I perform the completion:
1. the `source:complete` function is called, it gets all the fragment entries of the current file type, then it performs the `show_condition` function to filter, returning the filtered entries to nvim-cmp
2. nvim-cmp filters the returned information again according to 'line_to_cursor
3. Display the filtered entries

Now I want to write my own filtering logic in the `show_condition` function, then I don't want step 2 to be executed, how should I do it, thanks

```
function source:complete(params, callback)
    -- vim.api.nvim_err_writeln('11')
	init_options(params)

	local filetypes = require("luasnip.util.util").get_snippet_filetypes()
	local items = {}

	for i = 1, #filetypes do
		local ft = filetypes[i]
		if not snip_cache[ft] then
			-- ft not yet in cache.
			local ft_items = {}
			local ft_table = require("luasnip").get_snippets(ft, {
				type = "snippets"
			})
			if ft_table then
				for j, snip in pairs(ft_table) do
					if not snip.hidden then
						ft_items[#ft_items + 1] = {
							word = snip.trigger,
							label = snip.trigger,
							kind = cmp.lsp.CompletionItemKind.Snippet,
							data = {
								filetype = ft,
								snip_id = snip.id,
								show_condition = snip.show_condition,
							},
						}
					end
				end
			end
			snip_cache[ft] = ft_items
		end
		vim.list_extend(items, snip_cache[ft])
	end

	if params.option.use_show_condition then
		local line_to_cursor = params.context.cursor_before_line
		items = vim.tbl_filter(function(i)
			-- check if show_condition exists in case (somehow) user updated cmp_luasnip but not luasnip
			return not i.data.show_condition or i.data.show_condition(line_to_cursor)
		end, items)
	end

	callback(items)
end
```

**Comment by hrsh7th** [comment]
You should use `filterText`.
Currently, nvim-cmp does not provide the disabling nvim-cmp's filtering process.

**Comment by yyy33** [comment]
> 

I can't find any option for 'filterText' in the help file, can you give me some more hints?

**Comment by yyy33** [comment]
> You should use `filterText`. Currently, nvim-cmp does not provide the disabling nvim-cmp's filtering process.

I can't find any option for `filterText` in the help file, can you give me some more hints?

**Comment by hrsh7th** [comment]
See this thread https://github.com/hrsh7th/nvim-cmp/issues/1179

**Comment by yyy33** [comment]
> See this thread #1179

Thank you, it works fine now!
