### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by notwidow** [hrsh7th/nvim-cmp#1234]
Hi, How to set Tab key for selection of next item in snippet ? and the suggestions that come is annoying the that if i write function and hit enter then it prints the body of snippet. So how to configure it to not select snippet by default and only when i press tab to choose snippet?
THANKS!!!

**Comment by hrsh7th** [comment]
Sorry. I can't understand the problem.

**Comment by notwidow** [comment]
> Sorry. I can't understand the problem.

how to set tab key for selecting next snippet

**Comment by Shougo** [comment]
It should be discussion instead.
