### ISSUE TITLE
Question: buffer source behavior when joining two words

### ISSUE THREAD

**Issue by adrian5** [hrsh7th/nvim-cmp#1242]
Currently I seem to run a lot into the following behavior:

![cmp-buffercomplete-insert](https://user-images.githubusercontent.com/5426924/196008478-cb5884a6-515b-49b3-949c-38d7d3bc673e.gif)

What I'm trying to do there is remove the space after `foo` and insert a linebreak (Enter) to bring `bar` into the next line, i.e. what would happen if cmp wasn't in use. I'm not sure if cmp has always worked like this with the buffer source and my behavior simply changed. If this is normal, then I won't investigate further.

My nvim version is `0.8.0`.

**Comment by gegoune** [comment]
Seem like you have auto selection or confirming by enter turned on. Have a look at docs how to change that behaviour, should be all there.

**Comment by adrian5** [comment]
Thank you @gegoune, that was the culprit! I recently overhauled my config and took the opportunity to check out cmp's current examples (for my selection of plugins). I noticed a change there which I adopted without understanding what it does:

```lua
-- Before
["<Cr>"] = cmp.mapping.confirm()

-- After
["<Cr>"] = cmp.mapping.confirm({ select = true })
```

Reverting to plain `.confirm()` restores the behavior I am used to.
