### ISSUE TITLE
Using autocomplete in macro doesn't store content of completion in macro register

### ISSUE THREAD

**Issue by kdheepak** [hrsh7th/nvim-cmp#125]
https://user-images.githubusercontent.com/1813121/131451590-8b3495fc-3ed0-46aa-afcf-c58465480149.mov

In the gif, I complete `boo<TAB>` to `bootstrap` but only `boo` is stored in the contents of the register.

**Comment by hrsh7th** [comment]
I think nvim-cmp now supports macro.

**Comment by kdheepak** [comment]
Thank you for all your work on this!
