### ISSUE TITLE
With autocomplete=false, cmp menu will still auto appear after aborting if text under cursor matches a suggestion

### ISSUE THREAD

**Issue by schoblaska** [hrsh7th/nvim-cmp#1251]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end
cmp.setup {
  completion = {
    autocomplete = false,
  },

  mapping = {
    -- https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#luasnip
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif has_words_before() then
        cmp.complete({
          reason = cmp.ContextReason.Auto,
        })
      else
        fallback()
      end
    end, { "i", "s" }),

    ["<C-e>"] = cmp.mapping.abort(),
  },

  sources = cmp.config.sources({
    { name = "buffer" },
  }),
}
EOF
```

### Description

With autocomplete set to false, if the cmp menu is manually triggered and then manually closed (eg, via `cmp.mapping.abort()` or `cmp.mapping.close()`), the cmp menu will re-appear while the cursor is within the original completion area.

 

https://user-images.githubusercontent.com/29129/197155715-6953cf9f-9e05-4fa3-b199-c5f55d1fe374.mov

### Steps to reproduce

1. Using the provided config
2. Start typing a word that will have buffer completions
3. Hit `<Tab>` to trigger cmp menu
4. Hit `<C-e>` to abort the menu
5. Continue typing, matching at least one of the suggestions from the cmp menu
6. Cmp menu reappears automatically

### Expected behavior

Completion menu only appears when manually triggered if autocomplete is set to false.

### Actual behavior

Completion menu reappears after being aborted as long as text under cursor continues to match suggestions.

**Comment by par4m** [comment]
Any updates on this ? I'm facing the same issue.

**Comment by s3cy** [comment]
I managed to fix it with `cmp.core:reset()`.

```
local cmp = require("cmp")
local abort = function()
    cmp.abort()
    cmp.core:reset()
end

cmp.setup({
    mapping = {
        ["<C-e>"] = cmp.mapping(abort, { "i", "s" }),
    },
})
```

I have no idea if it is the right way. :-P
