### ISSUE TITLE
[Question] How i can make the autocompletion of the preview video?

### ISSUE THREAD

**Issue by zDylant** [hrsh7th/nvim-cmp#1256]
In the video, when a autocomplete option is selected the text appears in the file with a **gray color**:

https://user-images.githubusercontent.com/629908/139000570-3ac39587-a88b-43c6-b35e-207489719359.mp4

Also, how can i make nvim-cmp automatically **put the closing parenthesis/quote when i put the opening one**?

Sorry if this is a dumb question or if you dont understand, im new in neovim and english is not my native language.

**Comment by TheSquake** [comment]
Hello,

I was wondering this myself and found the answer you should add this to your lua file to get that gray color text (ghost text)

```
cmp.setup {
  ...
  experimental = {
    ghost_text = true
  }
  ...
}
```
