### ISSUE TITLE
How to setup the language server?

### ISSUE THREAD

**Issue by ethan-rod6** [hrsh7th/nvim-cmp#1259]
I'm really new into neo-vim, but not vim. I switched to neo-vim because it's highly customizable. Now I want to add auto completion to that. I find this amazing repo and tried to implement it. But the problem is I can't add a language server in the `init.lua`  file. I installed `Mason` and installed `kotlin-language-server`. Then I added the following. 
```
require'lspconfig'.kotlin_language_server.setup{}

local capabilities = require('cmp_nvim_lsp').default_capabilities()
local lspconfig = require('lspconfig')

local servers = {'kotlin-language-server'}
for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup{
        capabilities = capabilities,
    }
end
```
However I get the following error.
```
[lspconfig] Cannot access configuration for kotlin-language-server. Ensure this server is listed in `s
erver_configurations.md` or added as a custom server. 
```

I wanna know exactly how to setup this.

**Comment by arpangreat** [comment]
Did you installed nvim-lspconfig ? cause it's stores the server configs and the methods to work with lsp servers.

**Comment by ethan-rod6** [comment]
Yup

**Comment by hrsh7th** [comment]
Sorry. I don't know because I don't use kotlin-language-server.

Did you install kotlin-labguage-server?
https://github.com/fwcd/kotlin-language-server

**Comment by ethan-rod6** [comment]
Yes! And I resolved it. It's just a typo. I had to use `_` instead of `-`. However thank you so much for the fast reply.
