### ISSUE TITLE
Incorrect keys being fed during macro

### ISSUE THREAD

**Issue by zdcthomas** [hrsh7th/nvim-cmp#127]
Hi there! First off, thank you for the amazing plugin.
I recently noticed that while playing back a macro that contains and of the keymappings associated with nvim_cmp, the string `<Plug>(cmp-utils-keymap:_)` sent to the buffer as a series of keystrokes in normal mode. I've found that string [here](https://github.com/hrsh7th/nvim-cmp/blob/bc50c49a7fe1a5c51a0943d42b96ac58da0ab3c5/lua/cmp/utils/keymap.lua#L148) and [here](https://github.com/hrsh7th/nvim-cmp/blob/bc50c49a7fe1a5c51a0943d42b96ac58da0ab3c5/lua/cmp/utils/keymap.lua#L154), both inside of the keymap.lua file, and I believe that [this line](https://github.com/hrsh7th/nvim-cmp/blob/bc50c49a7fe1a5c51a0943d42b96ac58da0ab3c5/lua/cmp/utils/keymap.lua#L154) is the ultimate culprit, because it is feeding the keys into the buffer. 
Maybe the mode string is wrong in the `feedkeys` function? I'm not sure.

Just in case it's something do with my specific configuration, here's my `nvim_cmp` config file 
```
local conf = {}

local function check_back_space()
  local col = vim.fn.col('.') - 1
  return col == 0 or vim.fn.getline('.'):sub(col, col):match('%s')
end

local function tab_handler(fallback)
  if vim.fn.pumvisible() == 1 then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
  elseif check_back_space() then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Tab>', true, true, true), 'n')
  elseif vim.fn['vsnip#available']() == 1 then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>(vsnip-expand-or-jump)', true, true, true), '')
  else
    fallback()
  end
end

local function shift_tab_handler(fallback)
  if vim.fn.pumvisible() == 1 then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n')
  elseif check_back_space() then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<S-Tab>', true, true, true), 'n')
  elseif vim.fn['vsnip#jumpable'](-1) == 1 then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>(vsnip-jump-prev)', true, true, true), '')
  else
    fallback()
  end
end

local function mappings()
  local cmp = require('cmp')
  return {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-e>'] = cmp.mapping.close(),
    ['<C-l>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
    ['<Tab>'] = tab_handler,
    ['<S-Tab>'] = shift_tab_handler,
  }
end

local function snippet_func(args)
  vim.fn['vsnip#anonymous'](args.body)
end

local function sources()
  return {
      { name = 'buffer' },
      { name = 'vsnip' },
      { name = 'path' },
      { name = 'tmux'},
      { name = 'calc'},
      { name = 'nvim_lsp',
        opts = {
          all_panes = true
        }
      },
    }
end

function conf.setup()
  local cmp = require('cmp')
  cmp.setup {
    snippet = {
      expand = snippet_func
    },
    mapping = mappings(),
    sources = sources(),
  }
end

return conf
```

Thanks again! and sorry if I'm missing something obvious!

**Comment by hrsh7th** [comment]
@zdcthomas Thank you. This report is insightful. I'm trying to solve it but it a bit difficult.
It will be take a time but I think I have to solve it.

**Comment by hrsh7th** [comment]
Duplicate #125

**Comment by zdcthomas** [comment]
Awesome! Im down to help anyway I can.

Also what I'm seeing is slightly different from #125. Whereas that isn't storing the content of the completion in the macro register, mine is inserting the entire key map string as a normal mode sequence of key presses. I can try to make a video of it tomorrow if that's helpful.

**Comment by hrsh7th** [comment]
I think nvim-cmp now supports macro.

**Comment by zdcthomas** [comment]
Hey, very sorry but I just updated to the most recent release and I'm still seeing the same behavior.

**Comment by zdcthomas** [comment]
Here's a recording of what I'm seeing. https://asciinema.org/a/AUg2OkS1OwG0wy1PgZpsogQXw

**Comment by hrsh7th** [comment]
@zdcthomas Thank you. I've overlooked it.

Could you test with latest nvim-cmp? (I've applied patch for it.

**Comment by zdcthomas** [comment]
absolutely! Let me take a look!

**Comment by zdcthomas** [comment]
It works!! thank you so much!

**Comment by hrsh7th** [comment]
Thank you!
