### ISSUE TITLE
Custom completion source - completion popup not showing up

### ISSUE THREAD

**Issue by OrangeLightning219** [hrsh7th/nvim-cmp#1273]
Hi. I'm trying to write a custom completion source. I managed to get it working when a trigger character is pressed but I would like it to show suggestions all the time and not only after a specific character. Here's the code I'm using:
```lua
local cmp = require('cmp')

local custom_source = {}

local registered = false
custom_source.setup = function()
  if registered then
    return
  end

  registered = true

  local source = {}

  source.new = function()
    return setmetatable({}, {__index = source})
  end

  -- source.get_trigger_characters = function()
  --   return {'.', '>', ':'}
  -- end

  source.get_keyword_pattern = function(self, params)
    -- copied from cmp-buffer
    -- return [[\%(-\?\d\+\%(\.\d\+\)\?\|\h\%(\w\|á\|Á\|é\|É\|í\|Í\|ó\|Ó\|ú\|Ú\)*\%(-\%(\w\|á\|Á\|é\|É\|í\|Í\|ó\|Ó\|ú\|Ú\)*\)*\)]]

    -- copied from cmp-treesitter
    return [[\%(-\?\d\+\%(\.\d\+\)\?\|\h\w*\%([\-]\w*\)*\)]]
  end


  source.complete = function(self, request, callback)

    -- local input = string.sub(request.context.cursor_before_line, 1, request.offset)
    local items = {}

    -- this always displays the same stuff for testing purposes
    local completion_items = {'test1', 'test2', 'test3'}
    for index, item in ipairs(completion_items) do
      table.insert(items, {
        filterText = 'Some text',
        label = item,
      })
    end

    callback({items = items, isIncomplete = false})
  end

  cmp.register_source('custom_source', source.new())

  cmp.setup.filetype({'cpp', 'c', 'h', 'hpp'}, {sources = cmp.config.sources({{name = 'custom_source'}})})
end

custom_source.setup()
```
From what I've seen this is very similar to what other completion sources do (cmp-lsp, cmp-treesitter etc.). What am I missing?

**Comment by Eternex49** [comment]
This is probably connected with a bigger problem affecting cmp's regex handling. I have the same problem and, judging by multiple tests I've done over months, it seems to be quite a stubborn issue.
For some other reason (if related or unrelated I don't know), using magic mode, i.e. '\v', is unexplainably problematic too.

**Comment by hrsh7th** [comment]
The cmp's regex handling is very simple.

```
  return self.cache:ensure({ 'get_offset', keyword_pattern, self.cursor_before_line }, function()
    return pattern.offset(keyword_pattern .. '\\m$', self.cursor_before_line) or self.cursor.col
  end)
```

**Comment by Eternex49** [comment]
@hrsh7th Why are you modifying the user-provided pattern? In two instances:
context.lua at line 77
source.lua at line 177
If the user is expected to provide a custom pattern or, in this case, the author of the source, this could cause problems. It also is, most likely, the reason why the long-discussed issue concerning the custom completion pattern for vimtex existed.

**Comment by hrsh7th** [comment]
Did you check the code? If we don't add `$` to the pattern, it won't work.

Probably, we may need to make more complex changes.

[[\%(]] .. keyword_pattern .. [[\)\m$]]

**Comment by Eternex49** [comment]
As I understand, $ means end-of-line, and \m sets magic mode. Why is it necessary to set it?. Also, nesting the said vimtex pattern: https://github.com/lervag/vimtex/blob/master/autoload/vimtex/re.vim#L35 inside another set of %() is probably what makes it faulty.

**Comment by hrsh7th** [comment]
vim allows nested `\%(\)`.

`echomsg matchstr('foobar', '\%(\%(foo\)\)')`

I've updated.
https://github.com/hrsh7th/nvim-cmp/commit/2743dd989e9b932e1b4813a4927d7b84272a14e2

**Comment by Eternex49** [comment]
Yes, I see, so that shouldn't be a problem.
The problem is that your additions to the pattern assume to be in magic mode \m. The vimtex pattern sets very-magic mode \v. So you should also add a \m before the the ) you add, to make sure that the regex you add will be read in the mode it was written for.
Second thing, even if I manually added the \m, the vimtex pattern still doesn't match (the pattern is not the problem, it works perfectly fine out of cmp).
You also haven't said why you add the end-of-line in the regex and nest keyword_pattern inside the %().
You didn't talk about the second modification made to the pattern: https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/source.lua#L177

**Comment by hrsh7th** [comment]
Please read the code.

A general completion engine checks "whether the string before the cursor matches the pattern".

I don't know of any other way to achieve this than creating a cursor_before_text and matching keyword_pattern + `$`.

**Comment by Eternex49** [comment]
Maybe you could try to explain systematically what you expect the software to do, using a list:
1. does this
2. does that
3. then does that other thing.

**Comment by Eternex49** [comment]
Hey @hrsh7th, can you explain me why do you need to put add the $ and ^ to the user-provided pattern? I don't really think they are necessary.

**Comment by Shougo** [comment]
Hi.  `$` is needed for the pattern.

Beause, if you input "foo bar" text, you want to match `bar` text.

Input text: `foo bar`
Pattern: `\w*`

The pattern matches `foo`.  I think it is not expected.
The pattern must match you have input recently text.

So `$` is needed for the pattern.

Pattern: `\w*$`

It matches `bar` as expected.

`$` means `end of the user input`.

**Comment by hrsh7th** [comment]
Please read my comment...

> A general completion engine checks "whether the string before the cursor matches the pattern".
> I don't know of any other way to achieve this than creating a cursor_before_text and matching keyword_pattern + $.
