### ISSUE TITLE
How to set the border/icon  color

### ISSUE THREAD

**Issue by louisrc3ys** [hrsh7th/nvim-cmp#1284]
![2022-11-08_15-34](https://user-images.githubusercontent.com/71259902/200502563-8b0f9978-d558-488b-b352-734e2d1eaa2e.png)

Because my theme is mainly transparent color, I want to change the border color for him, otherwise it will affect the visual effect

**Comment by hrsh7th** [comment]
See default configuration.

You can change the winhighlight option.

https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/default.lua#L92
