### ISSUE TITLE
Autocompletion menu breaks auto indent correction

### ISSUE THREAD

**Issue by huyiqun** [hrsh7th/nvim-cmp#129]
I mainly encountered this problem in editing .tex files with `vimtex` loaded.

Assume we want to enter the following texts:
```
\begin{itemize}
  \item one
  \item two
\end{itemize}
```
Without autocompletion (no drop down menu), hit enter at the end of line `\item one` to enter a new line and start typing `\item`, the editor will look like (using `|` to indicate the cursor location)
 ```
\begin{itemize}
  \item one
    \item|
\end{itemize}
```
As soon as I hit `space` after the keyword `\item`, `vimtex` autocorrects the indentation to
```
\begin{itemize}
  \item one
  \item |
\end{itemize}
```

With `nvim-cmp` enabled with either `buffer` or `spell` source (only tested these two), when typing the keyword `item`, a drop down menu will pop up since it is a normal word. Despite whether I select an item from the list or abort to finish typing `item` on my own, after hitting `space` after `item`, the new line will no longer auto correct the indentation, so it will remain as:
```
\begin{itemize}
  \item one
    \item |
\end{itemize}
```

**Comment by hrsh7th** [comment]
I've fixed it but it is a experimental solution if other people report an issue for it, I will revert it maybe.
