### ISSUE TITLE
Cmp overwrites highlight groups

### ISSUE THREAD

**Issue by litoj** [hrsh7th/nvim-cmp#1296]
When using a theme that gets loaded before cmp, all highlight groups used by cmp get overwritten to the default. Is there a workaround so I don't have to set the highlight separately in cmp config?
Apparently caused by 8ce0832
using `default=true` according to `:help nvim_set_hl` would protect the currently set highlight to be protected from overwriting. I am not sure, how the issue for which this was done could be solved, but also I don't know, if there is a way to set highlights from a theme when it gets overwritten by cmp.
Possibly there could be an option in settings to force the default highlight.

**Comment by JosefLitos** [comment]
Sorry, didn't realize there are other than default groups. If I can bother, is there a separate group used for border? I would like to to change the border colour but FloatBorder doesn't seem to be used.

**Comment by esn89** [comment]
I am having the same issue.  I want to change the border colour, but FloatBorder doesn't do anything when I change it.
