### ISSUE TITLE
Pyright together with Jedi language server is slow

### ISSUE THREAD

**Issue by HansPinckaers** [hrsh7th/nvim-cmp#131]
Hi there! Nice work on the new version.

I use Pyright for its diagnostic/linter messages and jedi-language-server for auto-complete. I can disable the Pyright autocomplete with the option: `disableLanguageServices`. However, cmp is still slower with autocomplete than when Pyright is not enabled at all. 

It's the same behaviour as this issue:
https://github.com/hrsh7th/nvim-compe/issues/501

In compe using that option is a bit fast than cmp.

I looked in the logs and the resolved capabilities are still `completion = true` for Pyright, maybe that is a problem?

Anything I can help to debug? 

Thanks,
Hans

**Comment by hrsh7th** [comment]
I think so.
Probably, we should add the option to disable specific LSP server manually to cmp-ncim-lsp source.

**Comment by HansPinckaers** [comment]
<img width="641" alt="Screenshot 2021-09-03 at 16 18 41" src="https://user-images.githubusercontent.com/70747/132020479-6877aebf-12d7-4fa0-8acf-429c8499689b.png">

Added this to `source.is_available` in `cmp_nvim_lsp`. Works perfect!

**Comment by hrsh7th** [comment]
@HansPinckaers Thank you very much!! It's very helpful. I think neovim built-in lsp does not support `dynamicRegistration` so it might occur.

I will add the option for nvim-lsp.

**Comment by hrsh7th** [comment]
Oh. I found the solution without any modification.

You can set capabilities manually.

```lua
require'lspconfig'.pyright.setup {
  on_attach = function(client)
   cclient.server_capabilities.completionProvider = false
  end
}
```

**Comment by HansPinckaers** [comment]
Yes that works too! Thanks
