### ISSUE TITLE
Wrong place of autocomplete insertion

### ISSUE THREAD

**Issue by programmador** [hrsh7th/nvim-cmp#1315]
I thought it was related to #1097
But it wasn't. The issue has been fixed so that there's no exception anymore but the insertion is being performed in wrong place.

Here's the suggestion (a variant to be completed is already hovered):
![screenshot_2022-11-20-170633](https://user-images.githubusercontent.com/674995/202909833-fe8a3ce9-2b27-42cc-bb3d-48ccd6165041.png)

And here's how it looks like after pressing `enter`:
![screenshot_2022-11-20-170641](https://user-images.githubusercontent.com/674995/202909860-c83c353c-61ee-4ce4-a3a0-151396636324.png)

The problem is that suggested text is being inserted `before` cursor though it should be inserted `after`. Also the letters already typed are not being replaced/deleted.

P.S. I don't know whether it's related to nvim-cmp or caused by any other component.
I'm using:
* SpaceVim
* Neovim 0.8.0
* Intelephense (PHP)

**Comment by Shougo** [comment]
Well, your nvim-cmp is the latest?
SpaceVim has original repository and the plugins are not latest.

**Comment by programmador** [comment]
Yes, definitely. I've re-checked: deleted the bundled version and downloaded latest master from github.

**Comment by programmador** [comment]
I've got  what's happening! The issue occurs only while aut-importing with nvim-cmp+intelephense!
So a regular autocomplete works nicely.
But when a new import (`use` in PHP) line is to be inserted - that's when a cursor positioning issue occurs.

**Comment by programmador** [comment]
I've checked the same with Dart/Flutter: the issue does not occur even when a new import is to be inserted by LSP.
So either it's PHP-related or it's some kind of tricky multithreading issue.

**Comment by Shougo** [comment]
What is the PHP auto completion?

**Comment by programmador** [comment]
I have SpaceVim on two PC's.
* On one I get both current issue and #1097
* On other I get current issue only
How could it be happening at all?

I've found two folders named nvim-cmp:
* ./.cache/vimfiles/repos/github.com/hrsh7th/nvim-cmp
* ./.SpaceVim/bundle/nvim-cmp
and made clean `git clone` into both of them.
Nothing happens.

Where else could the plugin be cached?

**Comment by hrsh7th** [comment]
Sorry. I don't know but you can check the `runtimepath`.

checkout `:echomsg &runtimepath`

**Comment by programmador** [comment]
I've tried the same inside of a docker image.
Both bugs still do occur: #1315 and #1097

Runtime path contains exactly one mention about nvim-cmp:
```
/home/developer/.cache/vimfiles/repos/github.com/hrsh7th/nvim-cmp
```
And in that directory git tells that I'm on recent `main` which contains latest fixes of #1315.


#1097 is a bit harder to reproduce. So I can't tell You with confidence in what conditions which of them occurs.

For some cases in some files autocomplete works nicely. Other files (or places in that files) fill code in the wrong place #1315.
Editing the same file few lines upper or lower raise #1097:
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp/util.lua:428: start_col out of bounds
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:428: in function 'apply_text_edits'
        ...files/repos/github.com/hrsh7th/nvim-cmp/lua/cmp/core.lua:460: in function <...files/repos/github.com/hrsh7th/nvim-cmp/lua/cmp/core.lua:419>
        ...s/github.com/hrsh7th/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function <...s/github.com/hrsh7th/nvim-cmp/lua/cmp/utils/feedkeys.lua:45>

```

**Comment by hrsh7th** [comment]
Could you provide the reproduxtion steps?

**Comment by programmador** [comment]
Of course. Probably the most convenient would be via a Dockerfile or a docker-compose project. Including a script to create a sample project. I'll try to make it.

**Comment by programmador** [comment]
I've created a docker-compose environment with reproduction steps:
https://bitbucket.org/programmador/spacevim-debug
