### ISSUE TITLE
[Question] Is there any way to complete only the missing part of matched result?

### ISSUE THREAD

**Issue by tanchihpin0517** [hrsh7th/nvim-cmp#1320]
For example, with the [minimal configuration](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim):
```
hello_world
h|world
```
'|' is the position of the cursor. The completion menu shows 'hello_world' is matched. If I select it, the content will become:
```
hello_world
hello_worldworld
```
But I expect:
```
hello_world
hello_world
```
It doesn't make sense for me.
I checked the Wiki and didn't find the suggestion I need.

How could I make nvim-cmp insert only the missing characters on completing?

**Comment by tomtomjhj** [comment]
`cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace })`

**Comment by hrsh7th** [comment]
@tomtomjhj is correct. Thank you.
