### ISSUE TITLE
Postfix snippet not replacing input

### ISSUE THREAD

**Issue by ifyuhj** [hrsh7th/nvim-cmp#1321]
For example:
    `some` is a built-in postfix snippet of rust-analyzer

Expected behavior
```vim
    a.some<cr> -> Some(a)
```
Actual behavior
```vim
    a.some<cr> -> someSome(a)
```

It may be caused by this commit: e820335208a6a46e97202592a3694d8e01b923bc.
It worked well before the commit, but I am unable to solve this problem.

**Comment by pudnax** [comment]
same issue :+1:

**Comment by muchzill4** [comment]
I'm experiencing a similar issue with gopls. Can confirm that commit before https://github.com/hrsh7th/nvim-cmp/commit/e820335208a6a46e97202592a3694d8e01b923bc behaves correctly.

**Comment by hrsh7th** [comment]
Reproduced.
I'll fix this.

**Comment by muchzill4** [comment]
@hrsh7th I'm still experiencing this in golang after checking out the latest version. 🤔

**Comment by hrsh7th** [comment]
If you use packer.nvim, you should do PackerSync and PackerCompile.

**Comment by hrsh7th** [comment]
anyway, I'll check with golang.

**Comment by hrsh7th** [comment]
@muchzill4 If you report a problem, please include steps to reproduce it.

**Comment by hrsh7th** [comment]
It works in my environment.

https://user-images.githubusercontent.com/629908/203839428-bc61090f-90dd-4d7c-a990-373c95e64544.mov

**Comment by muchzill4** [comment]
@hrsh7th thanks for fast turnaround on this and rapid responses. My repro steps:

```
mkdir yolo
go mod init yolo
touch main_test.go
nvim main_test.go
```

```go
package yolo

func TestFo<tab> # -> func TestFoTestFo(t *testing.T)
```

Versions:
```
go version go1.19.2 darwin/arm64
golang.org/x/tools/gopls v0.10.1
NVIM v0.8.1
```

**Comment by muchzill4** [comment]
FWIW, the one you demonstrated in the video (`.print!`) works for me too on the latest `nvim-cmp`.

**Comment by hrsh7th** [comment]
It's gopls bug.

I've  tested with old nvim-cmp (before https://github.com/hrsh7th/nvim-cmp/commit/e820335208a6a46e97202592a3694d8e01b923bc ).
