### ISSUE TITLE
 attempt to index field 'mapping' (a nil value)

### ISSUE THREAD

**Issue by jaden-falls** [hrsh7th/nvim-cmp#1325]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/118032179/203909399-64163d65-524a-4111-9875-a7d8acfe060f.png">

### Description

I was just trying to map nvim-cmp but then when I save and entered vim again, this happened

### Steps to reproduce

<img width="1612" alt="image" src="https://user-images.githubusercontent.com/118032179/203909748-7f7d0be4-e460-4c2d-bf42-239dd3891048.png">

### Expected behavior

I expected it to just have no error, I honestly don't know what this "Expected behavior" box is for

### Actual behavior

I just said it at the top, again this box is unnecessary

**Comment by jaden-falls** [comment]
sorry I accidentally made this a bug, sorry

**Comment by CharlesEkkel** [comment]
@jaden-falls How did you fix this? I'm new to neovim configuration so it's probably something obvious, but I've got the same problem.

**Comment by Aleksanaa** [comment]
same here
