### ISSUE TITLE
Luasnip abandons navigation between nodes when cmp.confirm is called.

### ISSUE THREAD

**Issue by Mechap** [hrsh7th/nvim-cmp#1329]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require 'cmp'
local luasnip = require 'luasnip'

local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

cmp.setup({
    snippet = {
        expand = function(args)
            luasnip.lsp_expand(args.body)
        end,
    },
    mapping = cmp.mapping.preset.insert({
        ['<CR>'] = cmp.mapping.confirm({ select = true }),
        ['<C-Space>'] = cmp.mapping.complete(),

        ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
                luasnip.expand_or_jump()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end, { "i", "s" }),

        ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, { "i", "s" }),

        ['<C-k>'] = cmp.mapping.scroll_docs(-4),
        ['<C-j>'] = cmp.mapping.scroll_docs(4),

        ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
    }),
}
```

### Description

When I confirm a snippet using cmp, luasnip allows me to navigate between node. For example, when calling a function using snippet, I can navigate between the arguments. 
![20221126_15h45m21s_grim](https://user-images.githubusercontent.com/54742369/204094749-03550dd5-891c-491b-a9e2-0b7e34bd1574.png)
However, I still use lsp completions when editing each arguments, and as soon as I hit `<CR>` which confirms the selected item, I can no longer navigate between nodes.

### Steps to reproduce

Call a function as a snippet and edit one of the argument.

### Expected behavior

After editing the so-called argument, I used to be able to hit `<TAB>` to go to the next argument.

### Actual behavior

Not only I can't navigate to the next argument, but my cursor goes to the very beginning of the line.
![20221126_15h51m03s_grim](https://user-images.githubusercontent.com/54742369/204094969-e624fed3-1718-4f4c-9b15-791a4e96e2ea.png)
When I hit `<TAB>` again, it is interpreted as a tabulation.

### Additional context

I suspect that luasnip abandons the snippet as soon as I call cmp.confirm. The issue does only occur when I hit `<CR>` and I do not use other fancy plugins that could have overriden `<CR>`.

**Comment by hrsh7th** [comment]
Ah, Yes., It's cmp's  bug. i'll fix it.
