### ISSUE TITLE
documentation window doesn't close when aborting selection with '<C-c>'

### ISSUE THREAD

**Issue by ibhagwan** [hrsh7th/nvim-cmp#133]
Basically title, sometimes I enter the menu by mistake by entering '<Tab>' more than once, at that point I'd like to cancel the selection and revert to the previous text so I press '<C-c>', the pum menu closes and reverts to my original text but the documentation window doesn't and remains visible.

The documentation window will then close when a new completion menu opens with no documentation.

**Comment by hrsh7th** [comment]
nvim does not fire events by `<C-c>`. So I can't support it.

**Comment by ibhagwan** [comment]
Maybe there is a way to hook another event and check if `pumvisible` and if it’s not close the window?

**Comment by ibhagwan** [comment]
> `<C-c>` doesn'5 occur any events. (also InsertLeave)
> 
> Isn't `inoremap <C-c> <Esc>` work?

That’s not good because for me they do different things, `Esc` should close the pum while not modifying the text (leaving it at last selection), `C-c` closes the pum and reverts to the original text, so if I press `Tab-Tab` by mistake, I can `C-c` to revert the selection.

**Comment by hrsh7th** [comment]
What do you think about `inoremap <C-c><C-e><Esc>` ?

**Comment by ibhagwan** [comment]
> What do you think about `inoremap <C-c><C-e><Esc>` ?

I think it's a great solution :-)

This is my mapping now so I can still maintain the uniqueness of `<C-c>` everywhere else:
```lua
vim.api.nvim_set_keymap('i', '<c-c>', '(pumvisible() ? "\\<c-e>\\<Esc>" : "\\<c-c>")', { noremap = true,  expr = true })
```
