### ISSUE TITLE
Question: what is args.body?

### ISSUE THREAD

**Issue by matteouni** [hrsh7th/nvim-cmp#1331]
In the example
local cmp = require'cmp'

```
  cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      end,
    },
```
what is args? why do we pass args.body field to the functions?

**Comment by matteouni** [comment]
I can't find the "args" structure. What do their fields mean?

**Comment by matteouni** [comment]
I mean: since all snippet engines take as argument args.body, why do you pass a structure with more fileds?

**Comment by hrsh7th** [comment]
Because LSP spec defines `insertTextMode` that has `adjustIndentation` or `asIs`.
`args.insertTextMode` is can be used but I don't know what snippet engine supported `insertTextMode`.

**Comment by hrsh7th** [comment]
_It's also ready for future expansion._
