### ISSUE TITLE
Add sorting results based on most recent/frequently used

### ISSUE THREAD

**Issue by beauwilliams** [hrsh7th/nvim-cmp#134]
I.e, If I am using a completion item a lot, place it at the top. For completion items that I never select, place them at the bottom.

Basically, can we have completion items sorted by frecency?

**Comment by hrsh7th** [comment]
I think it should be implemented but I want to discuss it more deeply.

**Comment by EpsilonKu** [comment]
is it count frequency of word on code?

**Comment by hrsh7th** [comment]
Nothing for now.
It will inplement too on this.

**Comment by JoseConseco** [comment]
IMO,  [frecency](https://en.wikipedia.org/wiki/Frecency) is cool, but  boosting priority of words that are close to currently edited line could be even more helpfull. 
Maybe based of treesitter nodes - we could give biggest priority boost to words in current node,  then slightly smaller weights to words in parent node etc.  Using treesitter could also help to ignore words that are not available in current scope.

**Comment by hrsh7th** [comment]
The recently used sorter is implemented as built-in.
