### ISSUE TITLE
Full gopls function snippet is inserted after the cursor instead of replacing the typed characters.

### ISSUE THREAD

**Issue by phakepraful** [hrsh7th/nvim-cmp#1344]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()
require("mason").setup()
require("mason-lspconfig").setup({
    ensure_installed = { "gopls" }
})
require'lspconfig'.gopls.setup {
  capabilities = capabilities,
}
EOF


```

### Description

When a gopls function suggestion is confirmed, the whole suggestion is inserted after the cursor, instead of replacing the already typed words.

### Steps to reproduce

open a go test file _something_test.go_ and type 
```
package something

import "testing"

func Te
```

and confirm the first suggestion.
![image](https://user-images.githubusercontent.com/78707643/206698487-0f6887d2-174a-4d6c-a704-2430d676a565.png)

### Expected behavior

```
package something

import "testing"

func TestXxx|(t *testing.T){

}
```
![image](https://user-images.githubusercontent.com/78707643/206698316-7f21659c-a889-4aac-bc1f-37af1a5ff66d.png)

### Actual behavior

```
package something

import "testing"

func TeTestXxx|(t *testing.T){

}
```
![image](https://user-images.githubusercontent.com/78707643/206698787-3c173eef-881e-4bd7-8fb0-b97acd9ab2f1.png)

### Additional context

It is working fine for methods and other suggestions.
![image](https://user-images.githubusercontent.com/78707643/206699197-727c070d-a710-43dc-af1b-3cfc694dcad2.png)
![image](https://user-images.githubusercontent.com/78707643/206699242-9b5676e5-eb25-4516-82ca-0480b3eda905.png)

**Comment by marcuscaisey** [comment]
I'm also having the same issue. I bisected and found the bad commit here: e820335208a6a46e97202592a3694d8e01b923bc. I'm not familar with the codebase at all but going to have a little dig and see if I can spot anything obvious.

**Comment by marcuscaisey** [comment]
I think i've narrowed it down to a change in `lua/cmp/entry.lua` based on the issue not being present when I check out the version from the parent commit.
