### ISSUE TITLE
cmp-cmdline automatically triggers commands without hitting <Enter>

### ISSUE THREAD

**Issue by Bekaboo** [hrsh7th/nvim-cmp#1348]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Minimal `init.lua`:

```lua
vim.cmd('packadd packer.nvim')
require('packer').startup({
  function(use)
    use({ 'wbthomason/packer.nvim' })
    use({
      'voldikss/vim-floaterm',
      cmd = { 'FloatermNew', 'FloatermToggle' },
    })
    use({
      'hrsh7th/nvim-cmp',
      config = function()
        local cmp = require('cmp')
        cmp.setup()
        cmp.setup.cmdline(':', {
          enabled = true,
          sources = {
            { name = 'cmdline' },
          }
        })
      end,
    })
    use({
      'hrsh7th/cmp-cmdline',
      requires = 'nvim-cmp',
    })
  end,
})
```

### Description

Floaterm is automatically triggered with cmp-cmdline enabled when user is typing in the command-line.

Disabling `cmp-cmdline` solves this issue.

### Steps to reproduce

1. Replace `init.lua` with the minimal config provided.
2. Run `PackerSync`
3. Enter nvim
4. Type in command-line: `FloatermNew`
5. Hit Space
6. Floaterm automatically opens

### Expected behavior

Floaterm should not be opened before the user hits <Enter>.

### Actual behavior

Floaterm is automatically opened before the user hits <Enter>.

### Additional context

A demo of this bug:

https://user-images.githubusercontent.com/76579810/207524716-1bb6c329-c548-4c18-b63a-b05b722401af.mp4

Disabling `cmp-cmdline` solves this issue.

Demo:

https://user-images.githubusercontent.com/76579810/207527517-f283f499-2def-40b7-a10a-72185acc46f4.mp4

It is also worth mentioning the bug might also be related to recent `packer.nvim` updates that changes the implementation of lazy-loading commands in its compiled file, so I also reported the bug there.

**Comment by Bekaboo** [comment]
Also see the issue under `packer.nvim`: [](https://github.com/wbthomason/packer.nvim/issues/1166)

**Comment by hrsh7th** [comment]
Please create straight forward reproduction step. I can't understand how to reproduce the problem.

**Comment by Bekaboo** [comment]
> Please create straight forward reproduction step. I can't understand how to reproduce the problem.

Hi, thanks for your reply. It is pretty clear how to reproduce this issue. Just use the provided minimal `init.lua` as the config file for nvim, run `PackerSync` first and then run `FloatermNew`, after that, hit space to reproduce the bug.

**Comment by hrsh7th** [comment]
The provided `init.lua` causes the error. the reproduction step does not contains the installation step of packer.nvim.

**Comment by hrsh7th** [comment]
Please create the minimal init.vim that based on https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim
