### ISSUE TITLE
select_prev_item() and select_next_item() loosing focus

### ISSUE THREAD

**Issue by fdelacruz** [hrsh7th/nvim-cmp#1356]
I usually use C-j and C-k to move between items in a completion. That suddenly stopped working..I muss say I haven't been using nvim in weeks. Maybe something changed in the setup. I just don't know what.
Can somebody please look at my [config](https://github.com/fdelacruz/nvim/blob/main/lua/user/cmp.lua)? 

Thanks

**Comment by fdelacruz** [comment]
The following is what happens when I hit C-j to go to the next item in the snippet 
https://user-images.githubusercontent.com/148098/208467516-35859925-ee41-458c-86f1-a1914950644b.mov

**Comment by sooohka** [comment]
And idea how did you fix?
