### ISSUE TITLE
nvim-cmp causes nvim to crash

### ISSUE THREAD

**Issue by doums** [hrsh7th/nvim-cmp#137]
Hi,

I spotted a special case where `nvim-cmp` causes nvim to crash (infinite freeze).
Take this simple snippet saved in a `.lua` file (I don't know if this is relevant though).
```
--[[ place your cursor just after the two closing brackets -> ]] --
```
Enter in insert mode and just press `<cr>`. The crash should occur.

**Comment by hrsh7th** [comment]
I can't reproduce it.

https://user-images.githubusercontent.com/629908/131830278-f26585b6-7c32-41af-aaa2-ecfa281eea37.mp4

**Comment by doums** [comment]
Ok I found it. It was one of my personal plugin, which maps `<CR>` in insert mode. Disabling this mapping simply resolve the issue.

**Comment by hrsh7th** [comment]
@doums Could you provide the trouble mapping?

**Comment by doums** [comment]
Of course yes,
```
    imap <expr> <CR> <SID>AutoBreak()

function s:AutoBreak()
  if pumvisible()
    return "\<CR>"
  endif
  for [open, close] in b:pairs
    if open != close && getline(line("."))[col(".") - 2] == open
      let [line, col] = searchpairpos(s:Escape(open),
            \ '',
            \ s:Escape(close),
            \ 'cnW',
            \ 's:IsString(line("."), col(".")) || s:IsComment(line("."), col("."))',
            \ s:GetLineBoundary('f'))
      if line == line(".") &&
            \ match(getline("."), '^'.s:Escape(open).'\s*'.s:Escape(close), col(".") - 2) > -1
        return "\<CR>\<CR>\<Up>\<C-f>"
      endif
    endif
  endfor
  return "\<CR>"
endfunction
```
In fact you could use it right with the plugin  `doums/coBra`.
