### ISSUE TITLE
Statusline disappears on insert when cmdheight=0

### ISSUE THREAD

**Issue by mehalter** [hrsh7th/nvim-cmp#1382]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--branch=stable",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

vim.opt.cmdheight = 0

require("lazy").setup({
	{ "hrsh7th/nvim-cmp", config = true },
})
```

### Description

I believe something is getting printed to the messages or the command area for some reason when going into insert mode. When `cmdheight=0` this causes the statusline to disappear because it is showing the printed information. I found the commit where the issue comes up and have linked it below.

Thanks for your help with this!

### Steps to reproduce

Have `nvim-cmp` and `vim.opt.cmdheight = 0`, open neovim and go into insert mode

### Expected behavior

Statusline shouldn't be disappearing

### Actual behavior

Statusline disappears

### Additional context

Asciinema recording showing it: https://asciinema.org/a/o380q12yWjfhK1MzFgZssUIk8

Commit that introduces the bug: https://github.com/hrsh7th/nvim-cmp/commit/e55033fce468c9c578b946948807f2ac48a6ee08

**Comment by o-typ** [comment]
This behavior can be caused only by the following settings.
It would be too subtle to be an nvim-cmp problem.

```lua
vim.opt.cmdheight = 0
vim.opt.laststatus = 2

vim.api.nvim_create_autocmd('InsertEnter', {
  callback = function()
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Cmd>call v:lua.call()<CR>', true, false, true), 'n', true)
  end
})

_G.call = function()
end

-- vim:expandtab tabstop=2 shiftwidth=2
```

* I tested with nvim 0.8.2

**Comment by Shougo** [comment]
It is not nvim-cmp problem and cmdheight feature.

**Comment by hrsh7th** [comment]
I can't reproduce now. If you still have the problem, feel free to re-open this.

**Comment by Pocco81** [comment]
I too have this issue. My statusline disappears after entering `insert` mode, and won't reappear until I move. However, unlike @mehalter. I can reproduce it with `nvim-cmp` disabled.

Matter of fact, I just tested `cmdheight=0` with no user config or plugins (using: `nvim -n -i NONE -u NONE`) and surprisingly enough, after entering `insert` the statusline didn't disappear until going back to normal mode; and it stayed like this until going in and out of command line mode. That's a very... odd behavior? 

I'm personally on `NVIM v0.9.0` release build. I don't know why @hrsh7th can't reproduce it. I thought that maybe this was fixed on the latest `nightly` build, but I just tried `NVIM v0.10.0-dev-422+g68e2d7229` and it's still happening!

**Comment by Shougo** [comment]
Hi.  I want to reproduce the behavior.

Please upload the reproduce instruction in more detailed.
I cannot reproduce it on neovim HEAD.

**Comment by Shougo** [comment]
@Pocco81 Your neovim version is too old.  Please test neovim HEAD.
It should be reported in neovim issue instead.

**Comment by KentoOgata** [comment]
@Shougo 

It is reproduce in my environment with Neovim HEAD.
I tested with below conifg.

```vim
const s:packpath = expand('<sfile>:h')
const s:optpackpath = s:packpath .. '/pack/github.com/opt/'
if !isdirectory(s:optpackpath)
  call mkdir(s:optpackpath, 'p')
endif
exec printf('set packpath=%s', s:packpath)

function s:packadd(ghrepo)
  const l:installdir = s:optpackpath .. a:ghrepo
  if !isdirectory(l:installdir)
    call system(printf('git clone https://github.com/%s.git %s', a:ghrepo, l:installdir))
  endif
  exec printf('packadd %s', a:ghrepo)
endfunction

call s:packadd('hrsh7th/nvim-cmp')

lua << EOF
require('cmp').setup {
  enabled = false,
}
EOF

set cmdheight=0
set laststatus=2
```

1. `nvim -u init.vim`
2. Enter to insert mode with `i`
3. Statusline will be disappear.

**Comment by Shougo** [comment]
I get it.  It is redraw problem.  Please report it in neovim issues instead.

And real minimal config is:


```vim
set cmdheight=0
set laststatus=2
```

**Comment by Shougo** [comment]
Reproduced the problem without nvim-cmp.

```vim
set cmdheight=0
set laststatus=2

autocmd InsertEnter * call nvim_feedkeys(nvim_replace_termcodes('<Cmd>call v:lua.call()<CR>', v:true, v:false, v:true), 'n', v:true)

lua << END
_G.call = function()
end
END
```

I will report it in neovim upstream.
