### ISSUE TITLE
Feature Question "cmp has the feature for us to separate source like 'omnifunc'/'completefunc' ?"

### ISSUE THREAD

**Issue by PorcoRosso85** [hrsh7th/nvim-cmp#1385]
Feature Question "cmp has the feature for us to separate source like 'omnifunc'/'completefunc' ?"

As you know, omnifunc and completefunc are vim's basic function.
These are called with [C-x][C-_] on insert mode.
nvim-cmp is amazing for me to use these basic functions.

As I know, nvim-cmp provides us its suggestions with all of sources in bulk.
IMO, it's useful for me if I can call any source as I choose.

For example, on insert mode and when we insert anything,
[C-x][C-v] -- vsnip
[C-x][C-l] -- luasnip
[C-x][C-c] -- copilot
and so on...

If you feel anything, please let me know what you feel.
Thanks.

**Comment by hrsh7th** [comment]
Yes. I think you can use the following feature.

https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L187

**Comment by PorcoRosso85** [comment]
This is what I want, thanks.

By the way, from where do you think the best for newbie to start learning to create new source for nvim-cmp?
Anyone can create new custome source as text / json / csv file?

**Comment by PorcoRosso85** [comment]
> Yes. I think you can use the following feature.
> 
> https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L187

Excuse me.
This way of config will require us to set "source" definition in parallel with "mapping"?
OR
we only have to set "source" under "mapping"?
