### ISSUE TITLE
Is there any documentation for this plugin and how to configure them (there is nothing in the Wiki either)

### ISSUE THREAD

**Issue by tinnick** [hrsh7th/nvim-cmp#1388]
As the title says. I'm curious how people are actually settings this up to their liking without any documentation.
Are people reading the source code and figuring things out?

**Comment by bew** [comment]
There is plenty of documentation, did you try `:h cmp` from inside Neovim?
Alternatively you can read it online in the repo https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt

**Comment by tinnick** [comment]
> There is plenty of documentation, did you try `:h cmp` from inside Neovim? Alternatively you can read it online in the repo https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt

@bew 

Superb!! To be honest, I didn't even think about it because it lacked Wiki and I couldn't find any reference pointing to the help. 
Perhaps fix the README and the Wiki links?

**Comment by hrsh7th** [comment]
1. README.md
- https://github.com/hrsh7th/nvim-cmp
2. vimhelp
- https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt
- `:help cmp`
3. Community Tips (Wiki)
- https://github.com/hrsh7th/nvim-cmp/wiki
4. GitHub Discussion
- https://github.com/hrsh7th/nvim-cmp/discussions
