### ISSUE TITLE
Which snippets engine would you recommend to go with nvim-cmp?

### ISSUE THREAD

**Issue by Pocco81** [hrsh7th/nvim-cmp#139]
Hello @hrsh7th :)

I was just wondering which snippets engine you'd recommend between these two:
+ [L3MON4D3/LuaSnip](https://github.com/L3MON4D3/LuaSnip)
+ [hrsh7th/vim-vsnip](https://github.com/hrsh7th/vim-vsnip)

I've used both but recently I've been experiencing some slowness with LuaSnip, so thought about migrating to vsnip again, yet again vsnip is not written in Lua so I think it'll have some performance issue(?). What do you think? comparing your project with LuaSnip.

**Comment by Pocco81** [comment]
Awesome! thanks I'll stick with LuaSnip (I fixed the issues). Btw off topic but would it be possible to have a "**awesome nvim-cmp**" in the README for all of the sources?

**Comment by hrsh7th** [comment]
What is `awesome nvim-cmp`?

**Comment by Shougo** [comment]
It seems nvim-cmp sources list.
But it is hard to maintain.

**Comment by Pocco81** [comment]
@hrsh7th you know, like [awesome-neovim](https://github.com/rockerBOO/awesome-neovim). Since nvim-cmp is based on sources then it'd be cool to get a list of them :+1:

**Comment by hrsh7th** [comment]
The source list is here https://github.com/topics/nvim-cmp
