### ISSUE TITLE
Custom mapping that is not part of 'cmp.mapping.~' doesn't work when passed to 'cmp.config.setup()'

### ISSUE THREAD

**Issue by tinnick** [hrsh7th/nvim-cmp#1391]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
local ensure_packer = function()
  local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim';

  if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path});
  end

  vim.cmd [[packadd packer.nvim]];
end;

ensure_packer();

local packer = require('packer');

packer.startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim';
  use 'neovim/nvim-lspconfig';
  use 'williamboman/mason.nvim';
  use 'williamboman/mason-lspconfig.nvim';
  use 'hrsh7th/nvim-cmp';
  use 'hrsh7th/cmp-buffer';
  use 'hrsh7th/cmp-path';
  use 'hrsh7th/cmp-cmdline';
  use 'hrsh7th/cmp-nvim-lsp';
  use 'hrsh7th/cmp-nvim-lsp-document-symbol';
  use 'hrsh7th/cmp-nvim-lsp-signature-help';
  use 'hrsh7th/cmp-nvim-lua';
  use 'hrsh7th/vim-vsnip';
end)

local cmp = require('cmp');

cmp.setup({
  snippet = {
    expand = function(args)
       vim.fn['vsnip#anonymous'](args.body);
    end
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'nvim_lsp_signature_help' },
    { name = 'path' },
    { name = 'buffer' },
  },
  mapping = cmp.mapping.preset.insert({
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then cmp.mapping.select_next_item() else fallback() end
    end, { 'i' })
  }),
});
```

### Description

I'm wanting to map <kbd>Tab</kbd> to `cmp.mapping.select_next_item()` when the completion view is visible and a simple tab insert when it is not.

I have nothing else mapped to tab.

### Steps to reproduce

1. source the above config.
2. run `:PackerSync` to install deps.
3. open file with some lines in buffer.
4. type something to get the completion menu showing.
5. press <kbd>Tab</kbd> on the keyboard.

### Expected behavior

Pressing <kbd>Tab</kbd> when completion view is showing should select the next item in view and insert '\t' otherwise.

### Actual behavior

Nothing happens.

**Comment by hrsh7th** [comment]
It's documented.

You should use `cmp.select_next_item` here.

https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L313

**Comment by tinnick** [comment]
Thanks!!
