### ISSUE TITLE
Completion doesn't update cursor to the end of word

### ISSUE THREAD

**Issue by TroySigX** [hrsh7th/nvim-cmp#1398]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

vim.cmd([[set completeopt=menu,menuone,noselect]])

local has_words_before = function()
  unpack = unpack or table.unpack
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end

local cmp = require('cmp')

cmp.setup({
    window = {
      -- completion = cmp.config.window.bordered(),
      -- documentation = cmp.config.window.bordered(),
    },

    mapping = cmp.mapping.preset.insert({
    ['<C-Space>'] = cmp.mapping.complete{ reason = cmp.ContextReason.Auto },
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    ['<Tab>'] = function(fallback)
      if not cmp.select_next_item() then
        if vim.bo.buftype ~= 'prompt' and has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if not cmp.select_prev_item() then
        if vim.bo.buftype ~= 'prompt' and has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end
    end,
    }),

    sources = cmp.config.sources({ { name = 'nvim_lsp' },
    }, {
      { name = 'buffer' },
    }),

    snippet = {
        -- We recommend using *actual* snippet engine.
        -- It's a simple implementation so it might not work in some of the cases.
        expand = function(args)
          unpack = unpack or table.unpack
          local line_num, col = unpack(vim.api.nvim_win_get_cursor(0))
          local line_text = vim.api.nvim_buf_get_lines(0, line_num - 1, line_num, true)[1]
          local indent = string.match(line_text, '^%s*')
          local replace = vim.split(args.body, '\n', true)
          local surround = string.match(line_text, '%S.*') or ''
          local surround_end = surround:sub(col)

          replace[1] = surround:sub(0, col - 1)..replace[1]
          replace[#replace] = replace[#replace]..(#surround_end > 1 and ' ' or '')..surround_end
          if indent ~= '' then
            for i, line in ipairs(replace) do
              replace[i] = indent..line
            end
          end

          vim.api.nvim_buf_set_lines(0, line_num - 1, line_num, true, replace)
        end,
    },
})

### Description

When triggering completion of a class's function (for example, class.function()), cmp doesn't update the cursor to the end of function(), but rather keeps it between the period symbol (. symbol) and function().

### Steps to reproduce

1. write class. (include the full stop symbol)
2. Type f and enter to trigger completion of function()

### Expected behavior

Cursor moves to the end of function(), right after the closing bracket

### Actual behavior

The cursor stays between . and function()

**Comment by hrsh7th** [comment]
you should fix `snippet.expand` implementation.

it's not,a bug.

**Comment by TroySigX** [comment]
Thank you!
