### ISSUE TITLE
Auto confirm after timeout and no input?

### ISSUE THREAD

**Issue by sollymay** [hrsh7th/nvim-cmp#1399]
Hi @hrsh7th, first of all I want thank you for all your work. nvim-cmp is such a great tool and I really use it on a daily basis. Can't imagine not using it.

I want to see how could I implement the following behavior WITHOUT breaking my current tab behavior.

- when cmp opens, start a timer. each time the user types or uses tab, reset timer
- If no input is given after the timer ends, automatically confirm the last selection

This behavior mimics the way that some editors auto confirm tab selections after a short amount of time if there's no input from the user.

I am eager to help achieve this but have no idea on how to do it. these are my current mappings (I think I might need to disable the cmp.mapping.confirm and write a function on the confirm behavior but I don't want to assign it to a key if that makes sense?

Any help to get me started is highly appreciated.

```
  ['<CR>'] = cmp.mapping.confirm({ select = true }),
        ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
                luasnip.expand_or_jump()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end, { "i", "s" }),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, { "i", "s" }),

```

**Comment by hrsh7th** [comment]
Sorry. I don't want to add this in the core.

You can use `require('cmp').event:on('complete_done', function() ... end)` for this.
