### ISSUE TITLE
Documentation window border highlight group

### ISSUE THREAD

**Issue by itscarlosecp** [hrsh7th/nvim-cmp#140]
I was wondering if there is any highlight group available to customize the documentation window borders. I think it's currently inheriting from my Pmenu highlight group, but I want to change only the border's color.

Current border color:
![image](https://user-images.githubusercontent.com/47466248/131914749-6cc02eca-a871-46a9-80eb-ba79bbb807fa.png)

I want to the link the borders' group to match my lsp_signature window borders:
![image](https://user-images.githubusercontent.com/47466248/131914875-90872958-9ef4-42f9-badd-8ebd6ba2fc31.png)

**Comment by hrsh7th** [comment]
You can change it via https://github.com/hrsh7th/nvim-cmp#documentationwinhighlight-type-string
