### ISSUE TITLE
attempt to index field 'preset' (a nil value)

### ISSUE THREAD

**Issue by CoderWeiJ** [hrsh7th/nvim-cmp#1401]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [x] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require 'cmp'
local luasnip = require('luasnip')
local lspkind = require 'lspkind'

cmp.setup({
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
    end,
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-c>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    ['<c-d>'] = cmp.mapping(function(fallback)
      if luasnip.jumpable(1) then
        luasnip.jump(1)
      else
        fallback()
      end
    end, { "i", "s" }),
    ['<c-b>'] = cmp.mapping(function(fallback)
      if luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" })
  }),
sources = cmp.config.sources({
    { name = 'nvim_lsp',
      entry_filter = function(entry)
        return require('cmp.types').lsp.CompletionItemKind[entry:get_kind()] ~= 'Text'
      end
    },
    { name = 'luasnip' }, -- For luasnip users.
  }, {
    { name = 'buffer' },
  }),
  formatting = {
    format = function(entry, vim_item)
      if vim.tbl_contains({ 'path' }, entry.source.name) then
        local icon, hl_group = require('nvim-web-devicons').get_icon(entry:get_completion_item().label)
        if icon then
          vim_item.kind = icon
          vim_item.kind_hl_group = hl_group
          return vim_item
        end
      end
      return lspkind.cmp_format({ with_text = true })(entry, vim_item)
    end
  }
})

cmp.setup.filetype('gitcommit', {
  sources = cmp.config.sources({
    { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
  }, {
    { name = 'buffer' },
  })
})

cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' }
  }
})

cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})

vim.cmd([[
set completeopt=menuone,noinsert,noselect
highlight! default link CmpItemKind CmpItemMenuDefault
]])

```

### Description

I edited a `p-mp.lua` file and introduced it in `init.lua`, and then every time I went into `nvim`, I made an `attempt to index field 'preset'`, I didn't understand these configurations at all, followed someone else's configuration, I just wanted it to work

### Steps to reproduce

```shell
nvim xxx
```

### Expected behavior

normal work

### Actual behavior

have a error

### Additional context

![image](https://user-images.githubusercontent.com/46297020/211991280-f3a002fa-2ef3-4fac-af3f-bcc305c36ecb.png)

**Comment by CoderWeiJ** [comment]
> ### FAQ
> * [x]  I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.
> 
> ### Announcement
> * [x]  I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).
> 
> ### Minimal reproducible full config
> ```lua
> local cmp = require 'cmp'
> local luasnip = require('luasnip')
> local lspkind = require 'lspkind'
> 
> cmp.setup({
>   snippet = {
>     expand = function(args)
>       require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
>     end,
>   },
>   mapping = cmp.mapping.preset.insert({
>     ['<C-Space>'] = cmp.mapping.complete(),
>     ['<C-c>'] = cmp.mapping.abort(),
>     ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
>     ['<c-d>'] = cmp.mapping(function(fallback)
>       if luasnip.jumpable(1) then
>         luasnip.jump(1)
>       else
>         fallback()
>       end
>     end, { "i", "s" }),
>     ['<c-b>'] = cmp.mapping(function(fallback)
>       if luasnip.jumpable(-1) then
>         luasnip.jump(-1)
>       else
>         fallback()
>       end
>     end, { "i", "s" })
>   }),
> sources = cmp.config.sources({
>     { name = 'nvim_lsp',
>       entry_filter = function(entry)
>         return require('cmp.types').lsp.CompletionItemKind[entry:get_kind()] ~= 'Text'
>       end
>     },
>     { name = 'luasnip' }, -- For luasnip users.
>   }, {
>     { name = 'buffer' },
>   }),
>   formatting = {
>     format = function(entry, vim_item)
>       if vim.tbl_contains({ 'path' }, entry.source.name) then
>         local icon, hl_group = require('nvim-web-devicons').get_icon(entry:get_completion_item().label)
>         if icon then
>           vim_item.kind = icon
>           vim_item.kind_hl_group = hl_group
>           return vim_item
>         end
>       end
>       return lspkind.cmp_format({ with_text = true })(entry, vim_item)
>     end
>   }
> })
> 
> cmp.setup.filetype('gitcommit', {
>   sources = cmp.config.sources({
>     { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
>   }, {
>     { name = 'buffer' },
>   })
> })
> 
> cmp.setup.cmdline({ '/', '?' }, {
>   mapping = cmp.mapping.preset.cmdline(),
>   sources = {
>     { name = 'buffer' }
>   }
> })
> 
> cmp.setup.cmdline(':', {
>   mapping = cmp.mapping.preset.cmdline(),
>   sources = cmp.config.sources({
>     { name = 'path' }
>   }, {
>     { name = 'cmdline' }
>   })
> })
> 
> vim.cmd([[
> set completeopt=menuone,noinsert,noselect
> highlight! default link CmpItemKind CmpItemMenuDefault
> ]])
> ```
> 
> ### Description
> I edited a `p-cmp.lua` file and introduced it in `init.lua`, and then every time I went into `nvim`, I made an `attempt to index field 'preset'`, I didn't understand these configurations at all, followed someone else's configuration, I just wanted it to work
> 
> ### Steps to reproduce
> ```shell
> nvim xxx
> ```
> 
> ### Expected behavior
> normal work
> 
> ### Actual behavior
> have a error
> 
> ### Additional context
> ![image](https://user-images.githubusercontent.com/46297020/211991280-f3a002fa-2ef3-4fac-af3f-bcc305c36ecb.png)

**Comment by hrsh7th** [comment]
Could you try `vim.pretty_print(cmp)` ?

I can't understand how to cause this problem.

**Comment by CoderWeiJ** [comment]
我是魏健！已收到您的邮件。辛苦啦！

**Comment by CoderWeiJ** [comment]
> Could you try `vim.pretty_print(cmp)` ?
> 
> I can't understand how to cause this problem.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/46297020/213869001-a5997eab-34df-4153-9f48-9fd3f3460b33.png">

the mapping object has not a "preset" function
