### ISSUE TITLE
<CR> selects item if suggestions list only have a single element

### ISSUE THREAD

**Issue by fgr1986** [hrsh7th/nvim-cmp#1407]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```
...
mapping = cmp.mapping.preset.insert({
...
['<CR>']=cmp.mapping.confirm({select=false}),
...
})
```

### Description

Even setting mapping.confirm.select to false, hitting enter would automatically select the option.

### Steps to reproduce

```
def test_fn(test_arg):
    return
````

![image](https://user-images.githubusercontent.com/10627849/213431534-dc88feac-0bd0-4448-986c-ebe91b2d6073.png)

### Expected behavior

<CR> should simply enter a new line.

### Actual behavior

<CR> selects `test_arg` and completes it.

**Comment by hrsh7th** [comment]
It seems to the same with https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L803

Could you try this solution?
