### ISSUE TITLE
Is it possible to show colours?

### ISSUE THREAD

**Issue by thewinger** [hrsh7th/nvim-cmp#141]
Is there a way to show a colour preview in the completion menu?
Specifically, I'm searching for a way of having colour previews for Tailwindcss colours.

![image](https://user-images.githubusercontent.com/121455/131963603-a1872653-1d7a-4cfd-8fa2-b3ec2a831a15.png)

**Comment by hrsh7th** [comment]
Sorry. It is impossible at the moment.
