### ISSUE TITLE
Cannot scroll documentation with `scroll_docs`

### ISSUE THREAD

**Issue by dk949** [hrsh7th/nvim-cmp#1410]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.ccls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

Can't get the documentation window to scroll (with `scroll_docs`). It does work with a mouse when using `mouse=a`, but I usually have this option off.

### Steps to reproduce

1. With the config above run 
``` shell
printf "#include <vector>\n\nstd::vector<int> a;\n\n" > test.cpp
nvim -u init.vim --noplugin test.cpp
```
2. Make you terminal small (vertically) 
3. In neovim position the cursor over the word `vector` and execute `:lua vim.lsp.buf.hover()`
	* A Documentation window will appear, the terminal should be small enough that the whole docstring doesn't fit
4. Execute `:lua require("cmp").scroll_docs(4)`

### Expected behavior

The documentation window scrolls

### Actual behavior

Nothing happens.

**Comment by hrsh7th** [comment]
`require('cmp').scroll_docs()` only support `cmp's documentation window`.

It won't support nvim-lsp's hover window.

**Comment by cxwx** [comment]
scroll_docs not working 
how to check the problem?
I cannot use `require('cmp').scroll_docs()` when cmp trigger

**Comment by Magicrafter13** [comment]
> It won't support nvim-lsp's hover window.

I've never explicitly enabled this as far as I can tell, how do I remove it? I'd like nvim-cmp's scrollable version (plus, it doesn't really need to be here without nvim-cmp installed anyway, as it isn't related to linting).

![Image](https://github.com/user-attachments/assets/99ab7b1d-edc8-4876-b9fc-f572bcb425e9)

**Comment by roubaobaozi** [comment]
> `require('cmp').scroll_docs()` only support `cmp's documentation window`.
> 
> It won't support nvim-lsp's hover window.

So, since I saw `select_next_item()` works, I looked in the documentation for it, and saw there's a count option. This does work!

```
['<Down>'] = cmp.mapping.select_next_item(),
['<PageDown>'] = cmp.mapping.select_next_item({ count = 4 }),
['<Up>'] = cmp.mapping.select_prev_item(),
['<PageUp>'] = cmp.mapping.select_prev_item({ count = 4 }),
```
