### ISSUE TITLE
Source specific keyword_length

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-cmp#142]
Hi,

is there a chance to add a support for source specific options, like `keyword_length`? I'm using https://github.com/quangnguyen30192/cmp-nvim-tags, but it prints a lot of gibberish when it autocompletes empty string. I want to set a min length on input before it gets triggered.

If not, I'll open an issue to the tags source repo that will provide this option.

**Comment by hrsh7th** [comment]
We should implement this.

**Comment by hrsh7th** [comment]
```lua
{
  name = 'nvim_lsp',
  keyword_pattern = [[\k\+]],
  keyword_length = 3,
  max_item_count = 10,
  opts = {
    ... source specific options ...
  }
}
```

**Comment by kristijanhusak** [comment]
Looks goo

> ```lua
> {
>   name = 'nvim_lsp',
>   keyword_pattern = [[\k\+]],
>   keyword_length = 3,
>   max_item_count = 10,
>   opts = {
>     ... source specific options ...
>   }
> }
> ```

This looks great!

**Comment by hrsh7th** [comment]
Implemented.
