### ISSUE TITLE
Completely unmap <cr> from plugin

### ISSUE THREAD

**Issue by sieuwerts** [hrsh7th/nvim-cmp#143]
Is there a way to completely unmap `<cr>`? I don't want the plugin to do anything (no completion, confirm, etc) other than give me a new line when pressing `<cr>`.

I apologize in advance if the solution to this is already stated somewhere, but I could not find it and I have tried everything I could think of. Thanks!

**Comment by hrsh7th** [comment]
You can specify `mapping = {}`

**Comment by sieuwerts** [comment]
Thank you. I think I found the issue, was related to Packer not compiling and nothing to do with the cmp plugin, sorry for taking up your time. Keep up the great work, really enjoy it. 👍
