### ISSUE TITLE
Unable to complete commands in command line mode 

### ISSUE THREAD

**Issue by 0xAdk** [hrsh7th/nvim-cmp#1437]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require 'cmp'
cmp.setup.cmdline(':', { mapping = cmp.mapping.preset.cmdline() })
EOF
```

the relevant part being pretty much just
```lua
local cmp = require 'cmp'
cmp.setup.cmdline(':', { mapping = cmp.mapping.preset.cmdline() })
```

### Description

When I try to use tab completion in the command line nothing happens

### Steps to reproduce

1. using the mini config
2. open command line `:`
3. write a command to complete, for example `:hel`
4. press tab

### Expected behavior

command is completed to `:help` and a few other commands are shown in a popup

### Actual behavior

tab acts like it's mapped to `<nop>`

### Additional context

might be the same issue as #1436

**Comment by wwweww** [comment]
I also encountered the same problem, please ask you to solve it?

**Comment by 0xAdk** [comment]
git bisect gives 53f49c5145d05a53b997d3f647f97e5ac8e9bd5c as the first bad commit

**Comment by wwweww** [comment]
> git bisect gives [53f49c5](https://github.com/hrsh7th/nvim-cmp/commit/53f49c5145d05a53b997d3f647f97e5ac8e9bd5c) as the first bad commit

Thanks, I've also rolled back my version, waiting for an update from the author.

**Comment by o-typ** [comment]
Could you try follow configuration?

```lua
lua << EOF
local cmp = require 'cmp'
--cmp.setup.cmdline(':', { mapping = cmp.mapping.preset.cmdline() })
cmp.setup.cmdline(':', {
  mapping = {
    ['<Tab>'] = function()
      local cmp = require 'cmp'
      if cmp.visible() then
        cmp.select_next_item()
      else
        vim.fn.feedkeys('<C-z>', 'nt')
      end
    end,
  }
})
EOF
```

**Comment by nataneb32** [comment]
@o-typ It works with this config. :smile:

**Comment by hrsh7th** [comment]
Maybe I didn't understand your needs exactly.

The provided configuration attempts to enable key mappings for the command line for nvim-cmp without specifying a source for the command line.

Simply remove `cmp.setup.cmdline(':', ... )` or install `cmp-cmdline`.

**Comment by hrsh7th** [comment]
If enable `cmp-cmdline` as the following config, it works as expected.

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
  local cmp = require 'cmp'
  cmp.setup.cmdline(':', {
    sources = {
      { name = 'cmdline' },
    },
    mapping = cmp.mapping.preset.cmdline()
  })
EOF
```

**Comment by Nan-Do** [comment]
Installing 'cmp-cmdline' fixed the issue for me. 
Thanks for sharing the configuration

**Comment by 0xAdk** [comment]
> If enable `cmp-cmdline` as the following config, it works as expected.
> 
> ```viml
> if has('vim_starting')
>   set encoding=utf-8
> endif
> scriptencoding utf-8
> 
> if &compatible
>   set nocompatible
> endif
> 
> let s:plug_dir = expand('/tmp/plugged/vim-plug')
> if !filereadable(s:plug_dir .. '/plug.vim')
>   execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
> end
> 
> execute 'set runtimepath+=' . s:plug_dir
> call plug#begin(s:plug_dir)
> Plug 'hrsh7th/nvim-cmp'
> Plug 'hrsh7th/cmp-buffer'
> Plug 'hrsh7th/cmp-nvim-lsp'
> Plug 'hrsh7th/cmp-cmdline'
> Plug 'hrsh7th/vim-vsnip'
> Plug 'neovim/nvim-lspconfig'
> call plug#end()
> PlugInstall | quit
> 
> " Setup global configuration. More on configuration below.
> lua << EOF
>   local cmp = require 'cmp'
>   cmp.setup.cmdline(':', {
>     sources = {
>       { name = 'cmdline' },
>     },
>     mapping = cmp.mapping.preset.cmdline()
>   })
> EOF
> ```

> Maybe I didn't understand your needs exactly.
>
> The provided configuration attempts to enable key mappings for the command line for nvim-cmp without specifying a source for the command line.

The issue was that I was obvious oblivious of my broken configuration since before 53f49c5145d05a53b997d3f647f97e5ac8e9bd5c it didn't do me any harm. 

I had
```lua
cmp.setup.cmdline(':', {
	mapping = cmp.mapping.preset.cmdline(),
	sources = cmp.config.sources(
		{ { name = 'path' } },
		{ { name = 'cmdline' } }
	)
})
```
in my config for a while now, but at some point I removed the path and cmdline sources, and forgot to remove the setup code for them. Since it didn't do anything until  53f49c5145d05a53b997d3f647f97e5ac8e9bd5c I assumed it was a bug.

And the reason mini config doesn't include any sources is because it "worked"  (broke) just like it did in my config.

 Even if it only break already broken configs, maybe this counts as a breaking change?

**Comment by seriiserii825** [comment]
> Maybe I didn't understand your needs exactly.
> 
> The provided configuration attempts to enable key mappings for the command line for nvim-cmp without specifying a source for the command line.
> 
> Simply remove `cmp.setup.cmdline(':', ... )` or install `cmp-cmdline`.

Thanks, installed **use("hrsh7th/cmp-cmdline")** and it works
