### ISSUE TITLE
Insert mode vanilla autocompletion fails if LSP not used

### ISSUE THREAD

**Issue by Labnann** [hrsh7th/nvim-cmp#1438]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
-- Install packer
local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  is_bootstrap = true
  vim.fn.system { 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path }
  vim.cmd [[packadd packer.nvim]]
end


require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'hrsh7th/cmp-nvim-lsp'

  use {'hrsh7th/nvim-cmp',
    requires = { 'hrsh7th/cmp-nvim-lsp', 'L3MON4D3/LuaSnip', 'saadparwaiz1/cmp_luasnip' },
  }

  use 'hrsh7th/vim-vsnip'

  end
)


local cmp = require('cmp')

cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
    end,
  },
 
-- This will cause breakage
  mapping = cmp.mapping.preset.insert({}),


  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' }, -- For vsnip users.
  }, {
    { name = 'buffer' },
  })
})

```

### Description

Expected:
Whether LSP used or not used, using <C-p> or <C-n> should autocomplete any word if the word is already written in that particular file.
Reality:
The word autocomplete only works if the file supports an LSP.

More description:
- Simply removing the line marked in cmp.setup in the given config preserves the vanilla behavior.
- Git bisect leads to [53f49c5](https://github.com/hrsh7th/nvim-cmp/commit/53f49c5145d05a53b997d3f647f97e5ac8e9bd5c). Commits prior to this behaves normally.

### Steps to reproduce

Use the config provided above. Save it as:
`~/.config/nvim/init.lua`

Open neovim.
`$ nvim`
Install all packer plugins with `:PackerInstall`.
Quit neovim `:q`.

Open neovim again.
`$ nvim`

Go to inseret mode `i` and type things like:

```
Hello
How
Hexagon
H
```

Press \<C-p\>

### Expected behavior

![image](https://user-images.githubusercontent.com/55809005/218529518-4747670b-8b0d-4ac9-a3a8-ef071030af2a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/55809005/218529234-8ce7944e-5066-48c9-90ab-4272f78cf504.png)
Nothing occurs.

### Additional context

Might be related to #1437

**Comment by o-typ** [comment]
I think you should install `cmp-buffer` source.

```diff
use {'hrsh7th/nvim-cmp',
-   requires = { 'hrsh7th/cmp-nvim-lsp', 'L3MON4D3/LuaSnip', 'saadparwaiz1/cmp_luasnip' },
+   requires = { 'hrsh7th/cmp-nvim-lsp', 'L3MON4D3/LuaSnip', 'saadparwaiz1/cmp_luasnip', 'hrsh7th/cmp-buffer' },
}
```

**Comment by o-typ** [comment]
If you want to complete a string in a buffer to a candidate, the following settings are sufficient.

```lua
-- Install packer
local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.system { 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path }
  vim.cmd.packadd 'packer.nvim'
end

require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/cmp-buffer'
end)

local cmp = require('cmp')

cmp.setup({
  mapping = cmp.mapping.preset.insert({}),
  sources = cmp.config.sources({
    { name = 'buffer' },
  })
})

-- vim:expandtab tabstop=2 shiftwidth=2
```

**Comment by Labnann** [comment]
Using cm-buffer fixes the issue.

I think it should be on "Breaking changes Announcement" though. Because before 53f49c5, like in cfafe0a vanilla behavior was working fine and cmp-buffer was not necessary.

**Comment by hrsh7th** [comment]
Very sorry. Admittedly this is a change in behavior, but we don't want to make the preset change a breaking change.

I will specify this in the README.md.

In nvim-cmp, we want the user to be responsible for keymapping. Sorry again.

**Comment by hrsh7th** [comment]
I've added it to the README.md.

https://github.com/hrsh7th/nvim-cmp/commit/1b2e843a692a04756afbda16a491514a2be2479d
