### ISSUE TITLE
Mapping occasionally gets corrupted

### ISSUE THREAD

**Issue by dhleong** [hrsh7th/nvim-cmp#1439]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

TK; I still don't have a 100% repro, but primarily I have a mapping for `['<CR>']` that uses a function, something like:

```lua
---@param key_or_config string|{ key:string, cmdwin: string }
local function try_accept_completion(key_or_config)
  local key = key_or_config
  local cmdwin = nil
  if type(key_or_config) == 'table' then
    key = key_or_config.key
    cmdwin = key_or_config.cmdwin
  end

  return cmp.mapping(function(fallback)
    local is_cmp_visible = cmp.visible()
    local entry = is_cmp_visible and cmp.get_active_entry()
    if is_cmp_visible and entry then
      cmp.confirm()

      if key and not entry_has_key(entry, key) then
        vim.api.nvim_feedkeys(key, 'nt', false)
      end
    elseif cmdwin and vim.fn.getcmdwintype() ~= '' then
      local to_feed = vim.api.nvim_replace_termcodes(cmdwin, true, false, true)
      vim.api.nvim_feedkeys(to_feed, 'nt', true)
    else
      fallback()
    end
  end, { 'i', 'c' })
end

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = try_accept_completion { cmdwin = '<CR>' },
  },
  -- ...
}
```

I also have a mapping created in vim before the `setup` call:

```vim
imap <silent> <Enter> <C-R>=dhleong#text#TryCleanWhitespace()<cr><Plug>DiscretionaryEnd
```

### Description

Instead of a newline, when I hit the enter key, the text `<Lua 190: ~/.config/nvim/bundle/nvim-cmp/lua/cmp/utils/keymap.lua:127>` gets inserted. There is nothing in `messages` with more context. 

### Steps to reproduce

As mentioned above, I don't have a reliable repro yet, but it's basically just edit a file and hit enter in insert mode.

### Expected behavior

I expect newline to be inserted

### Actual behavior

The text `<Lua 190: ~/.config/nvim/bundle/nvim-cmp/lua/cmp/utils/keymap.lua:127>` gets inserted.

### Additional context

If I manually re-execute the `imap` and subsequently the `cmp.setup` that seems to fix it. I've tried wrapping my function in `pcall` to catch an error, but to no avail. I've also tried tweaking the function to just directly call `fallback()` and it still reproduces, so my best guess is the fallback function gets corrupted somehow, but I'm not sure how to inspect the state further when this situation arises to figure out what's happening. It's not clear to me what is generating that stack trace line, or where. I'm happy to keep experimenting with some suggestion of where to look!

**Comment by hrsh7th** [comment]
Could you provide the reproducible minimal configuration? I can't reproduce this.

**Comment by dhleong** [comment]
Still working on a repro, but I have a suspicion it's interaction with another plugin that lazily sets up its map. I added some instrumentation to `keymap.listen()`:

```lua
  keymap._fallback_sources[mode .. ':' .. lhs] = existing
```

and when I repro the issue I can print out that value to see:

```lua
{
  buffer = false,
  expr = false,
  lhs = "<CR>",
  noremap = false,
  nowait = false,
  replace_keycodes = false,
  rhs = "<lt>Lua 237: ~/.config/nvim/bundle/nvim-cmp/lua/cmp/utils/keymap.lua:129><Plug>MirrorClose",
  script = false,
  silent = false
}
```

So I can probably fix by disabling that mapping in the plugin, since it seems like cmp tries to recreate maps on every `InsertEnter` if they don't have the expected `desc`.

**Comment by dhleong** [comment]
Ah yeah, one of my plugins was using `maparg('<CR>', 'I')` to extend an existing `<CR>` mapping, and because it just becomes `<Lua ...>` (and it couldn't tell that its mapping was already handled by cmp's fallback) it was appending its `<Plug>` mapping to that string, which cmp then picked up as the new fallback on `InsertEnter`.

So the repro would be:

1. Install the old version of this plugin that ignores `<Lua ...>` mappings
2. Open a supported file type and enter insert mode to consume that mapping into `fallback`
3. Use `:e` or something to trigger `FileType` autocmd; this will produce the above `<lt>Lua` value for `rhs`
4. Enter insert mode again to consume *this* mapping into `fallback`
5. Hit `<cr>`

**Comment by dhleong** [comment]
I've pushed a new version of my plugin that just nops when it encounters a lua mapping, instead of squashing it. Not sure if there's a more general way to handle this sort of thing on cmp's end, so feel free to close.

**Comment by hrsh7th** [comment]
Thank you. I understand :)
