### ISSUE TITLE
cant jump to next tabstop without filling previous one (ultisnips)

### ISSUE THREAD

**Issue by JoseConseco** [hrsh7th/nvim-cmp#144]
I'm not sure if this is correct plugin to post the issue (maybe its more related to cmp-ultisnip)
I can't jump to next tabstop, when I want to skip filling in  current tabstop ($2) value. Editing $2 (we go from 'select' into 'insert' mode) - makes < tab > jump work ok.  Example  snippet:

```vim
snippet integer "IntProperty"
$1: bpy.props.IntProperty(name="test", description='', default=${2: 1})$0
```
In above snippet I get stuck on $2 (cant tab)   if I wont edit its value, however using UltiSnip build-in < c-j > jump  works .  Basically:
- if I wont edit  $2  => we stay in '**select**' mode  =>  < tab > jump  wont work   (only < c-j > works)
- if I edit $2   => we switch from 'select' to '**inset**' mode  => now < tab > forward work

My mappings:

```lua
	mapping = {
		['<C-p>'] = cmp.mapping.select_prev_item(),
		['<C-n>'] = cmp.mapping.select_next_item(),
		['<Tab>'] = cmp.mapping(function(fallback)
			-- print('can jump ='..vim.inspect(vim.fn["UltiSnips#CanJumpForwards"]()))
			if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpForwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<tab>"), "n")
			else
				vim.fn.feedkeys(t("<tab>"), "n")
			end
		end, { "i", "s"}),
		['<C-e>'] = cmp.mapping.close(),
		['<CR>'] = cmp.mapping.confirm({ -- remapped at bottom by autopairs
			behavior = cmp.ConfirmBehavior.Replace,
			select = false,
		}),
		-- ['<C-Space>'] = cmp.mapping.complete(),
		['<C-Space>'] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				if vim.fn.complete_info()["selected"] ~= -1 then
					if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
						return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
					else
						vim.fn.feedkeys(t("<cr>"), "n")
                                        end
				else
					vim.fn.feedkeys(t("<C-e>"), "n")
				end
			elseif check_back_space() then
				vim.fn.feedkeys(t("<cr>"), "n")
			else
				fallback()
			end
		end, { "i", "s", }),
	},

```

For me  'select' mode  jumping seems broken, so I created separate mapping  

`snoremap <tab> "<C-R>=UltiSnips#JumpForwards()<CR>"`

but then using tab on $2 will create   double-quote character for no reason (not sure why). 
Any ideas why :
`if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpForwards()<CR>"))`  
wont jump in  'select' mode ?

**Comment by hrsh7th** [comment]
You can chenc `<C-r>=` as `<Cmd>...<CR>`

```lua
vim.fn.feedkeys(t("<Cmd>UltiSnips#JumpForwards()<CR>"))
```

**Comment by hrsh7th** [comment]
The `<C-r>=...<CR>` way can be used only in `insert-mode`.

**Comment by JoseConseco** [comment]
Thx the <cmd> thing almost worked.   But in he end I had to use:
`vim.fn.feedkeys(t("<esc>:call UltiSnips#JumpForwards()<CR>"))`
Found in UltiSnips:  ~/.local/share/nvim/site/pack/packer/start/ultisnips/autoload/UltiSnips/map_keys.vim 
It still did not work, but in above file I found variable  `UltiSnipsRemoveSelectModeMappings` and bingo - UltiSnip was messing with my mappings. We can disable it in Packer config:

```lua
		use {'SirVer/ultisnips', requires='honza/vim-snippets',
			config=function()  vim.g.UltiSnipsRemoveSelectModeMappings = 0  end,}
```
Now tab  mapping is not removed  when we are in snippet expanded mode  (works both in insert and select mode)
