### ISSUE TITLE
! cmdline completion is broken (regression)

### ISSUE THREAD

**Issue by michelesr** [hrsh7th/nvim-cmp#1441]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
```

### Description

Since 53f49c5145d05a53b997d3f647f97e5ac8e9bd5c was merged, shell command line completion is broken `:!` and similar (e.g. `%!` doesn't complete anymore with the available shell commands. 

### Steps to reproduce

- type `:!`
- press tab

### Expected behavior

command line completion is shown

### Actual behavior

nothing happens

### Additional context

Now that I think about it, the completion menu for commands is probably from neovim rather than the plugin, however it was very nice to have and after this regression it won't show anymore.

**Comment by axieax** [comment]
Weird, my cmdline completion doesn't work, but my shell one does :/

**Comment by entropitor** [comment]
For me, it seems neither commandline nor shell completion is working 😅

**Comment by hrsh7th** [comment]
Please specify cmdline source options like this.

```lua
cmp.setup.cmdline(':', {
  sources = {
    {
      name = 'cmdline',
      option = {
        ignore_cmds = {}
      }
    }
  } 
})
```
