### ISSUE TITLE
Giving more fuzzy letters doesn't keep matching some words

### ISSUE THREAD

**Issue by bew** [hrsh7th/nvim-cmp#1443]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
cmp.setup.global {
  sources = { { name = "buffer" } },
  matching = {
    disallow_partial_fuzzy_matching = false,
  },
}
```

### Description

Trying to reduce the number of suggestions by adding more fuzzy letters doesn't keep matching some words that _logically_ should still match.

### Steps to reproduce

In a file, write `thisdoesnotmatch`

Then try to complete this word by typing `thinm`
(these are the first letters that poped to my mind to write this long word)

### Expected behavior

Get suggestion for the long word `thisdoesnotmatch`

### Actual behavior

`thinm` doesn't match the long word.

Although `thin` does match.

I would expect that giving more letters would still match the word!

### Additional context

I'm on commit: 208d69f233d65526a22c6497ed57d0c80d99fa5f

**Comment by bew** [comment]
Hit again by this bug today, I wanted to match `saved_splitright` using `sasr` but it didn't show up.. :/

No problem if you don't have time to look into it, but do you agree this is a bug?
I can try to make a PR, any idea what might be giving this behavior?

**Comment by nyngwang** [comment]
@bew Did experience this before and was reluctant to report it. Thanks for your help!

**Comment by bew** [comment]
Hello! Thanks for looking into it, it does indeed fix the completion of `saved_splitright` & `error_msg` when using the letters I gave above, but not in all cases with other letters.
:point_right: Also the word in my initial post still does not work for some reason: `thisdoesnotmatch` using `thinm` or `thidn`

Could you please re-open this issue?

Here are more examples of what works, and what doesn't:
With a file with:
```
saved_splitbelow
saved_splitright
```

These letters should match both:
* (✅) `s`, `sa`, `sv`, `sd`, `s_`, `ss`
* (❌) `svd`, `sv_`, `svl`
* (❌) `sves`
* (✅) `sasl`
* (✅) `saspt`
* (✅) `sapli`
* (❌) `sapi`
* (❌) `saplt`
* (✅) `savedslit`

These letters should match only `saved_splitright`:
* (✅) `sg`, `sh`, `sr`
* (❌) `sgt`
* (❌) `stt`
* (❌) `sii`
* (✅) `sasr`
* (❌) `sasii`
* (❌) `saslg`
* (❌) `sapr`

(and I could do the same thing for `saved_splitbelow` but you get the idea)

To double-check my letters I tested every one of these with fzf (which is my 'fuzzy' reference at the moment) with this oneliner `echo "saved_splitbelow\nsaved_splitright" | fzf` and they all matched successfully.

**Comment by hrsh7th** [comment]
It is not intended to have the same behavior as fzf fuzzy matching.
However, general fuzzy match behavior should be achieved.

**Comment by bew** [comment]
Thanks, that definitely solved it for me!
However I don't understand why you added a new option to disable that.
What is the difference between having it enabled or disabled?
(=> What was the rational of the previous behavior?)

**Comment by hrsh7th** [comment]
nvim-cmp does boundary matching first, then fuzzy matching.

Fuzzy matching that is not full-fuzy is like substring matching without boundaries.

**Comment by hrsh7th** [comment]
If this explanation can be reasonably documented, a PR would be greatly appreciated.
_google translated_

**Comment by bew** [comment]
> Fuzzy matching that is not full-fuzy is like substring matching without boundaries.

I'm sorry but I still don't understand :/
Could you maybe give examples of non-fullfuzzy and reason why it matches/doesn't match?

**Comment by bew** [comment]
It looks like that fullfuzzy implementation still isn't enough..
I'm trying to match `forward_word` with `fww` or `foww` or `fwdd` without success :eyes:

**Comment by hrsh7th** [comment]
That is a specification and there are no plans to fix it.
The logic is designed to prioritize boundary matches.
