### ISSUE TITLE
Cannot erase text in search mode. Text gets restored back after I hit backspace or ctrl-w after certain character

### ISSUE THREAD

**Issue by carljohnson93** [hrsh7th/nvim-cmp#1444]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}

cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' }
  }
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

### Description

I spotted this bug about a three weeks ago, but couldn't reproduce it this whole time, it just happened sometimes and I couldn't figure out what's happening. Today I was finally able to catch it again and this time I was able to reproduce it.
So basically the bug is in search I mode after I type some text for which completion popup shows up, then add for example opening paren (maybe other characters too but that's the one I encountered bug with most often), and then try to erase (kill) few characters - they get put back at the search cmdline.

I recorded the screen, here's how it looks:

https://user-images.githubusercontent.com/47556468/219358952-c6e4fb83-f561-49d9-958d-6039ed859c61.mov

### Steps to reproduce

Open new file and insert the following example contents to the file:
```text
transparent
transcendent
```
save the file, exit neovim.
Copy the config I provided above to vimrc.vim
Open neovim: `nvim -nu vimrc.vim file.txt`
type `/`,
then type `tr(`,
then hit Enter, 
hen hit `/` again,
hit Arrow Up, then try hitting backspace multiple times or ctrl-w and you'll see that text gets restored back

### Expected behavior

Expected for text to be erased character by character as usual

### Actual behavior

Text gets "restored" back after hitting backspace/ctrl-w/other key that kills text

**Comment by hrsh7th** [comment]
I think it's fixed in the latest main. Thank you.
