### ISSUE TITLE
Regarding color scheme at the end of the Menu-Appearance in the wiki

### ISSUE THREAD

**Issue by VPavliashvili** [hrsh7th/nvim-cmp#1449]
Hello
In the customization [wiki](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance), at the end of the file there is color scheme lua table but I could not figure out what does that fields mean. Can you specify more clear how am I suppose to use them?
for example if I want exactly same completion popup appearance what should I pass to `winhighlight` field as string value?
thanks in advance

**Comment by hrsh7th** [comment]
See `:help nvim_open_win`.
