### ISSUE TITLE
show function signatures/arguments while inside ()

### ISSUE THREAD

**Issue by WANDEX** [hrsh7th/nvim-cmp#145]
Show function signatures/arguments while inside ()
+dynamically highlight current argument like on screenshot:
![image](https://user-images.githubusercontent.com/15724752/132017773-e0f35bc3-8778-46d6-b312-6c2bae6d04d7.png)
Similar to this plugin [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim)

Currently this plugin cant show it's floating window with cmp in "INSERT COMPL" mode.
But if we exit and go to basic "INSERT" mode, it will show up. (***inside red borders on screenshot***) 

with bind=false -> it shows even in "INSERT COMPL" mode, but it uses virtual text, does not highlight argument and generally looks ugly and not distinct from the other text, because of lack of borders.

#### easy to try - copypaste config:

```lua
use 'ray-x/lsp_signature.nvim'
local sigf_lsp = require('lsp_signature')
local sigf_opts = {
  bind = true,
  doc_lines = 5,
  floating_window = true,
  hint_enable = false,
  handler_opts = {border = "single"},
  extra_trigger_chars = {"(", ","},
}

sigf_lsp.setup(sigf_opts)
---- or like this inside `local on_attach = function(client, bufnr)`
-- sigf_lsp.on_attach(sigf_opts, bufnr)
```

**Comment by hrsh7th** [comment]
First, I have no plan to add it (it is not a `completion` feature of LSP spec).

Sorry. I'm not a native English Speaker. So I might not understand what you mean.

Why lsp_signature.nvim is not enough?

**Comment by WANDEX** [comment]
this plugin does not show it's floating window while we type in "INSERT COMPL" mode.

**Comment by WANDEX** [comment]
Also, while cmp completes function name it can show function documentation, but when we type () of that function -> documentation string disappears, this behavior can be optional, dont you think? It will make cmp much more convenient and superior, if we just add extra configuration option to cmp to "not hide documentation string after ( bracket". Even better - after list of pre-defined characters in config, for example: { "(", "," }

**Comment by hrsh7th** [comment]
Hm... ? In my environment, lsp_signature.nvim works great.

https://user-images.githubusercontent.com/629908/132029725-270d47e6-6409-4f5a-8f57-54ef9ccb94da.mp4

**Comment by WANDEX** [comment]
Can you please give me a link or share your config?

**Comment by hrsh7th** [comment]
My config is super ugly 🤣

My config can switch to use
- LSP: coc/neovim/vim-lsp/vim-lsc/LanguageClient-neovim/my custom LSP client
- Competion: cmp/compe/asyncomplete/deoplete/ddc
- Snippets: LuaSnip/vim-vsnip/Ultisnips

So I don't recommend to look it

**Comment by WANDEX** [comment]
> Also, while cmp completes function name it can show function documentation, but when we type () of that function -> documentation string disappears, this behavior can be optional, dont you think? It will make cmp much more convenient and superior, if we just add extra configuration option to cmp to "not hide documentation string after ( bracket". Even better - after list of pre-defined characters in config, for example: { "(", "," }

But personally, i think this option would be very useful without necessity installing extra plugin, since doc showing actually already built in cmp, just needs extra option to not hide doc string.

**Comment by hrsh7th** [comment]
You can look into it.

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'ray-x/lsp_signature.nvim'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  sources = {
    { name = 'nvim_lsp' }
  }
}

require'lsp_signature'.setup {
  bind = true,
  doc_lines = 5,
  floating_window = true,
  hint_enable = false,
  handler_opts = {border = "single"},
  extra_trigger_chars = {"(", ","},
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.documentationFormat = { 'markdown' }
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.preselectSupport = true
capabilities.textDocument.completion.completionItem.insertReplaceSupport = true
capabilities.textDocument.completion.completionItem.labelDetailsSupport = true
capabilities.textDocument.completion.completionItem.deprecatedSupport = true
capabilities.textDocument.completion.completionItem.commitCharactersSupport = true
capabilities.textDocument.completion.completionItem.tagSupport = { valueSet = { 1 } }
capabilities.textDocument.completion.completionItem.insertTextModeSupport = { valueSet = {} } -- TODO
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

require'lspconfig'.vimls.setup {
  flags = {
    debounce_text_changes = 200,
    allow_incremental_sync = true,
  },
  capabilities = capabilities,
}
EOF
```

**Comment by WANDEX** [comment]
Thank you, i will try to make it work with my cmp configuration later when i can.

**Comment by sQVe** [comment]
I'm having issues here too. Once I input `(` it gives me a `() ~` snippet option and it seems like `lsp_signature` is suppressed. I do not have this issue with `nvim-compe`.

**Comment by hrsh7th** [comment]
I think it is not relate to nvim-cmp...

**Comment by sQVe** [comment]
It very well might not be, which is not what I'm trying to say, but I don't know really how to best find the culprit. I'm getting this when running the `tsserver` LSP. I find the whole `(` snippet to be sort of annoying. 🤷🏼

**Comment by elianiva** [comment]
hmm, I don't think `(` snippet comes from tsserver (just checked)

**Comment by hrsh7th** [comment]
@sQVe @WANDEX Are you using `nvim-autopairs`? it has a feature of adding `(` automatically.

**Comment by sQVe** [comment]
I'm not using it. I have a snippet though that might be problematic. Will need to remove it and see if that makes a difference.

**Comment by WANDEX** [comment]
I found the reason why lsp_signature.nvim plugin was not working paired with cmp in my config.
It was '*luasnip*' source of 'saadparwaiz1/cmp_luasnip', issue was *solved by removing* it from cmp config.
It does not really sounds as a proper solution, but, at least in my case, it worked, and seems like **the problem** with the '*luasnip*' source, **not with the nvim-cmp itself**.
Probably i should try different snippet source and snippet plugin, before closing this issue, to properly locate the source of the problem.
*I will try this later and report the results.*

**Comment by gegoune** [comment]
Might be worth opening issue with saadparwaiz1/cmp_luasnip.

**Comment by WANDEX** [comment]
Tried with 'hrsh7th/vim-vsnip' snippet engine with 'hrsh7th/cmp-vsnip' source, same behavior.
Snippets are working with both snippet engies: vsnip & luasnip, but if add any of their sources to cmp,
window from lsp_signature.nvim plugin will not be shown in "INSERT COMPL" mode, the same as i described in issue at the beginning.
My guess that, problem somehow related to snippet sources or smth related to snippets in general.

**It looks like if i have snippet suggestion after typing the function name, i will not get lsp_signature window,
as it is was blocked by the next immediate "INSERT COMPL" mode suggestion from snippet source.**

### Solution that worked in my case.
For some reason snippets are suggested right after inserting ( character.
Because increasing `completion = { keyword_length = 2, },` from default 1 to 2, actually **solved my problem**.

### My guess that ( character is counted as a keyword character for starting suggesting completion, maybe cmp should ignore some characters like this by default?

What do you think about it?

**Comment by sQVe** [comment]
I found the issue for me. I had a snippet in `vsnip` with the `prefix` of `()`. As soon as I change that I don't get autocompletion for the snippet on `(` and I correctly see the signature help.

**Comment by hrsh7th** [comment]
I think it absolutely doesn't nvim-comp's issue.

And I can't reproduce it even if I have a snippet that having a prefix of `()`.

https://user-images.githubusercontent.com/629908/132608078-eecf60a6-8dd7-4899-ba5e-005a43d02079.mp4

**Comment by hrsh7th** [comment]
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'ray-x/lsp_signature.nvim'
call plug#end()
PlugInstall | quit

imap <expr><C-l> vsnip#available(1)    ? '<Plug>(vsnip-expand)'         : '<C-l>'
smap <expr><C-l> vsnip#available(1)    ? '<Plug>(vsnip-expand)'         : '<C-l>'
imap <expr><Tab> vsnip#available(1)    ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
smap <expr><Tab> vsnip#jumpable(1)     ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr><S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr><S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'


" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' }
  }
}

require'lsp_signature'.setup {
  bind = true,
  doc_lines = 5,
  floating_window = true,
  hint_enable = false,
  handler_opts = {border = "single"},
  extra_trigger_chars = {"(", ","},
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.documentationFormat = { 'markdown' }
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.preselectSupport = true
capabilities.textDocument.completion.completionItem.insertReplaceSupport = true
capabilities.textDocument.completion.completionItem.labelDetailsSupport = true
capabilities.textDocument.completion.completionItem.deprecatedSupport = true
capabilities.textDocument.completion.completionItem.commitCharactersSupport = true
capabilities.textDocument.completion.completionItem.tagSupport = { valueSet = { 1 } }
capabilities.textDocument.completion.completionItem.insertTextModeSupport = { valueSet = {} } -- TODO
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

require'lspconfig'.vimls.setup {
  flags = {
    debounce_text_changes = 200,
    allow_incremental_sync = true,
  },
  capabilities = capabilities,
}
EOF
```

I was using this in the above screencast.
