### ISSUE TITLE
cmdline tabs not working without cmp-cmdline plugin

### ISSUE THREAD

**Issue by axieax** [hrsh7th/nvim-cmp#1454]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}

cmp.setup.cmdline(":", {
  mapping = cmp.mapping.preset.cmdline(),
  view = { entries = "wildmenu" },
  sources = cmp.config.sources({
    { name = "path" },
  }),
})

vim.opt.wildmenu = "full"
vim.opt.wildoptions = "tagfile"
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

### Description

It seems that 53f49c5145d05a53b997d3f647f97e5ac8e9bd5c may have caused tab completion to stop working without the cmp-cmdline plugin (which was working previously). From examining the code, perhaps there is something wrong with the fallback keys not sending `<Tab>` or `<S-Tab>` appropriately.

### Steps to reproduce

1. Enter the beginning of a command with `:Ma`
2. Press `<Tab>` or `<S-Tab>`
3. Nothing happens (not even `<C-i>`)

### Expected behavior

Native popup menu should show up (mine configured with `wildoptions = "tagfile"` and `wildmenu = "full"`

### Actual behavior

Literally nothing.

### Additional context

Fixing this issue will also close #953, which is still open from 9 months ago.

**Comment by hrsh7th** [comment]
You know cmp-cmdline works, so why is this a problem?

**Comment by axieax** [comment]
I can amend the mapping for `<Tab>` to be `vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Tab>", true, false, true), "tn", false)` if cmp is not visible, but am not sure what to do for the `<S-Tab>` case.

**Comment by hrsh7th** [comment]
You can specify your mapping by yourself.

The following config is just `example`.
```lua
local cmp = require('cmp')
cmp.setup.cmdline(':', {
  ...
  mapping = cmp.mapping.preset.cmdline({
    ['<Tab>'] = {
      c = function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        else
          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-z>', true, true, true), 'ni', true)
        end
      end
    }
  })
  ...
})
```

**Comment by axieax** [comment]
Oo this works for `<Tab>` as well. Is there a way to get this working for `<S-Tab>`??
