### ISSUE TITLE
Checking for if vim.fn.setcmdline exists before executing it doesn't work

### ISSUE THREAD

**Issue by joebb97** [hrsh7th/nvim-cmp#1455]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}


-- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline({ '/', '?' }, {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
        { name = 'buffer' }
    }
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}

EOF

```

### Description

https://github.com/hrsh7th/nvim-cmp/blob/d3a2833c118843859c667f64b6169e22bffe13d0/lua/cmp/view/custom_entries_view.lua#L415

This failsafe doesn't work since `vim.fn.<anythinghere>` evaluates to a real function. This causes a crash in neovim versions < v.0.8.0 since `vim.fn.setcmdline` tries to get executed.

I've verified that on both neovim versions v.0.7.2 and v.0.8.3 that `:lua print(vim.fn.notreallyafunction)` prints `function: <some hex number>` and not `nil` like you'd expect it to.

### Steps to reproduce

Open up a file with neovim version < v0.8.0. Execute a search with `/` and attempt to select from the completions. I can't grab the stack trace here because I updated my system to fix it.

### Expected behavior

Searching and selecting autocompletion for search should succeed

### Actual behavior

A stacktrace is printed and nvim-cmp stops working

### Additional context

I think it would be safer to check if this function exists with
`if vim.fn.has('nvim-0.8') then vim.fn.setcmdline(....) end`

**Comment by hrsh7th** [comment]
Thank you for detailed information.
Could you create the PR?

**Comment by joebb97** [comment]
Sure thing!

**Comment by hrsh7th** [comment]
Thank you~!

**Comment by mburz** [comment]
@joebb97 `if(0)` is `true` in Lua. Can you please fix your check?
`if vim.fn.has('nvim-0.8')` evaluates to true even on versions < 0.8

Thanks!

**Comment by joebb97** [comment]
This issue should probably be opened again based on @mburz comment, and can *hopefully* be closed when my PR lands
