### ISSUE TITLE
How to change window border color ?

### ISSUE THREAD

**Issue by leandrocunha** [hrsh7th/nvim-cmp#1457]
There is any possibility to change the border color of the completion window? I would like to change this white for another color for instance. How to do it?

![image](https://user-images.githubusercontent.com/1820920/220719597-19866130-0550-4481-a203-7a4c78ddd9de.png)

**Comment by hrsh7th** [comment]
You can use winhighilight iption.
See https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L610
