### ISSUE TITLE
it un-select the first item sometimes after hitting `<Tab>`

### ISSUE THREAD

**Issue by nyngwang** [hrsh7th/nvim-cmp#1458]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
local G = {
  extend = function (tb1, tb2)
    return vim.tbl_deep_extend('force', {}, tb1, tb2)
  end
}

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight.nvim",
  -- add any other pugins here
  {
    'hrsh7th/nvim-cmp',
    dependencies = {
      'neovim/nvim-lspconfig',
      'hrsh7th/cmp-nvim-lsp',
      'hrsh7th/cmp-buffer',
      'hrsh7th/cmp-path',
      'hrsh7th/cmp-nvim-lua',
      'hrsh7th/cmp-vsnip',
      'hrsh7th/vim-vsnip',
      'onsails/lspkind-nvim',
    },
    config = function ()
      local cmp = require('cmp')
      cmp.setup {
        snippet = {
          expand = function (args)
            vim.fn["vsnip#anonymous"](args.body)
          end
        },
      mapping = cmp.mapping.preset.insert({
        -- <option-shift-P/N>
        ['<C-S-p>'] = cmp.mapping.scroll_docs(-4),
        ['<C-S-n>'] = cmp.mapping.scroll_docs(4),
        ['<C-o>'] = cmp.mapping.complete(), -- O for Open: This will open completion menu.
        ['<C-c>'] = cmp.mapping.close(), -- C for Close: This will close completion menu.
        ['<C-y>'] = cmp.mapping(
          cmp.mapping.confirm {
            behaviour = cmp.ConfirmBehavior.Insert,
            select = true
          }, { 'i', 'c' }
        ),
        -- Tab Completion.
        -- See: https://github.com/hrsh7th/nvim-cmp/discussions/783.
        ['<Tab>'] = cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Select },
        ['<S-Tab>'] = cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Select },
      }),
        sources = {
          { name = 'nvim_lsp' },
          { name = 'path' },
          { name = 'vsnip' },
          { name = 'buffer', keyword_length = 5 },
          { name = 'nvim_lua', ft='lua' },
        },
        sorting = {
          -- WARNING: Copy-paste from https://github.com/tjdevries/config_manager/blob/master/xdg_config/nvim/after/plugin/completion.lua
          comparators = {
            cmp.config.compare.offset,
            cmp.config.compare.exact,
            cmp.config.compare.score,

            -- copied from cmp-under, but I don't think I need the plugin for this.
            -- I might add some more of my own.
            function (entry1, entry2)
              local _, entry1_under = entry1.completion_item.label:find "^_+"
              local _, entry2_under = entry2.completion_item.label:find "^_+"
              entry1_under = entry1_under or 0
              entry2_under = entry2_under or 0
              if entry1_under > entry2_under then
                return false
              elseif entry1_under < entry2_under then
                return true
              end
            end,

            cmp.config.compare.kind,
            cmp.config.compare.sort_text,
            cmp.config.compare.length,
            cmp.config.compare.order,
          }
        },
        formatting = {
          format = function (entry, vim_item)
            -- ref.: https://github.com/rebelot/dotfiles/blob/713819963b009fbe86577748c0ca9ad7f6a8fc5b/nvim/lua/plugins/cmp.lua#L144
            vim_item = require('lspkind').cmp_format({
              mode = 'text_symbol',
              maxwidth = 50
            })(entry, vim_item)

            local alias = {
              nvim_lsp = '[lsp]',
              path = '[dir]',
              vsnip = '[vsnip]',
              buffer = '[buf]',
              nvim_lua = '[lua]',
            }

            if entry.source.name == 'nvim_lsp' then vim_item.menu = entry.source.source.client.name
            else vim_item.menu = alias[entry.source.name] or entry.source.name end

            return vim_item
          end
        },
        experimental = {
          native_menu = false,
          ghost_text = false,
        },
      }
    end
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```

### Description

After pressing `<Tab>` to trigger the `cmp.mapping.select_next_item`, the cursor seems to blink on the first item, like the demo:

https://user-images.githubusercontent.com/24765272/220900121-19cb2ac6-2be9-4439-9a62-bfcd2850bfb2.mov

This is the related part of my config:

```lua
mapping = cmp.mapping.preset.insert({
  -- Tab Completion.
  ['<Tab>'] = cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Select },
  ['<S-Tab>'] = cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Select },
}),
```

### Steps to reproduce

I don't know, it rarely happens but this problem was also confirmed by [others](https://www.reddit.com/r/neovim/comments/119s0dq/comment/j9nzjwy/?utm_source=share&utm_medium=web2x&context=3) on reddit.

### Expected behavior

No blink.

### Actual behavior

blink.

**Comment by seblj** [comment]
I am also noticing this sometimes. See the video below for context. My guess is that this has something to do with me selecting an option and then the completion list is being recreated and some new entries are added. This causes it to deselect my option, and I have to then press `<C-n>` again. Hope this could help a bit.

I have a snippet set for a filetype, and that is loaded immediately. The LSP suggestions are then coming in after the snippet

[Screencast from 24. feb. 2023 kl. 15.04 +0100.webm](https://user-images.githubusercontent.com/5160701/221198305-6f83f335-8aba-44b1-8a7c-d700c8b8e6b5.webm)

**Comment by hrsh7th** [comment]
Thank you for your report.

Basically, the "occasionally reproduced" type of bug is hardest one.

If I can reproduce this on my environment, I'll tackle it...

**Comment by buschco** [comment]
From my experience, @seblj guess seems just like to explain issue. I have some cmp sources that are super quick, and some (like tsserver 🙃 ) that are super slow. I added another video.

https://user-images.githubusercontent.com/14929556/235366693-59ec2d79-f715-4c03-8e51-a0612a865c6a.mov

**Comment by hrsh7th** [comment]
I think this is `SelectBehavior.Select` related problem(maybe).
I'll investigate it.

**Comment by buschco** [comment]
I tried to fix the issue here https://github.com/hrsh7th/nvim-cmp/pull/1547

I am pretty sure this is not a bullet proof solution, but it improves my `nvim-comp` experience a lot.

**Comment by hrsh7th** [comment]
Could you try with `try-to-fix-1458` branch?

The nvim-cmp has `active` flag that turn on if the user selects the item via `SelectBehavior.Insert`.
If the flag was turned on, the nvim-cmp does not accept new completion menu update event.

**Comment by buschco** [comment]
@hrsh7th I noticed with `try-to-fix-1458` that sometimes, there will not come any new items from `tsserver` and sometimes the deselect behavior. In the video you can see both:

https://user-images.githubusercontent.com/14929556/235443195-85a632e2-caf9-498c-bba6-5f9efa1c52f1.mov

**Comment by hrsh7th** [comment]
If the menu is being displayed and the user is not selecting an item, nvim-cmp updates the menu. However, if the user is selecting an item, it skips updating the menu. Are you asking if this behavior is intended?

**Comment by buschco** [comment]
Not quite.
I think, if the user selects an item, it is intended not to update the list.
However it seems the list is still being updated even if the user has selected an item, which is not intended imo.

**Comment by hrsh7th** [comment]
I can't reproduce this.

My setup is the following.

1. Add the super slow completion source.
```lua
local Source = {}
Source.__index = Source

function Source.new()
  return setmetatable({}, Source)
end

function Source:complete(params, callback)
  local word = params.context.cursor_before_line:sub(params.offset)
  vim.defer_fn(function()
    callback({
      isIncomplete = true,
      items = {
        {
          label = word .. 'foo',
        }
      }
    })
  end, 1000)
end

return Source
```

```lua
cmp.setup {
  mapping = {
    ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
    ...
  },
  sources = {
    { name = 'debug' },
    { name = 'nvim_lsp' },
    ...
  }
}
```

2. Invoke completion and select item
3. The `debug` source results does not trigger to update the menu.

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/235445789-afcd3587-6dbb-4f39-a26c-b85ca998c0fb.mov

**Comment by buschco** [comment]
Played around a little bit, and i was not able to reproduce it 👍 

I'll keep an eye on it. Idk how I was able to reproduce it earlier, maybe it was a once in a lifetime reproduction 😄

**Comment by hrsh7th** [comment]
Thank you for your report and information.

Reports from multiple users allowed me to deduce the cause of the issue!

**Comment by buschco** [comment]
thanks for the fix and the plug-in 🙏

**Comment by hrsh7th** [comment]
This issue was closed after 1year ago.
If you have problem, please create new issue and don't re-use old one.
