### ISSUE TITLE
Question: Breaking changes/config from migrating from nvim-compe to nvim-cmp?

### ISSUE THREAD

**Issue by stevenproctor** [hrsh7th/nvim-cmp#146]
Seeing that hrsh7th/nvim-compe is now deprecated (https://github.com/hrsh7th/nvim-compe/issues/517), and this is the replacement, I was wondering if there were any known migration steps to be aware of when moving from hrsh7th/nvim-compe to this project

I think the biggest question I know to ask is would extra sources still be compatible with `nvim-cmp`, or will there be API integration changes that need to happen?

Are there any other things that someone should be aware of when migrating to this plugin?

**Comment by hrsh7th** [comment]
nvim-cmp is a different plugin than nvim-compe.

Therefore, if the user uses nvim-cmp, it needs to be reconfigured.

Most source authors already support nvim-cmp.
https://github.com/topics/nvim-cmp

(google translated)
