### ISSUE TITLE
[Question] How to change the documentation window appearance

### ISSUE THREAD

**Issue by leandrocunha** [hrsh7th/nvim-cmp#1460]
I would like to change the underline color of the documentation title, it's possible?

![image](https://user-images.githubusercontent.com/1820920/221188912-2a956cf1-6ab0-43f3-bc0d-c3f0e1976b4c.png)

**Comment by hrsh7th** [comment]
It's impossible. Sorry.

**Comment by hrsh7th** [comment]
The documentation window appearance is came from nvim core.
