### ISSUE TITLE
Deal with quoted candidates properly

### ISSUE THREAD

**Issue by musjj** [hrsh7th/nvim-cmp#1463]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

<details>
<summary>init.lua</summary>

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```
</details>

### Description

Candidates with quotes isn't completed correctly when using autopair plugins.

### Steps to reproduce

A sample source to test with:

```lua
local source = {}

function source:complete(params, callback)
  callback({
    { label = '"foobar"' },
    { label = '"some_string"' },
  })
end
  
return source
```

### Expected behavior

`call_fn("some_str|")` -> `call_fn("some_string"|)`

### Actual behavior

`call_fn("some_str|")` -> `call_fn("some_string"|")`

**Comment by hrsh7th** [comment]
It should be care on source impl.

**Comment by musjj** [comment]
I'm not sure what you mean.

Things like partial word completion is already handed by the plugin:

`part|_word` -> `partial_word|`

Why should quotes be any different? Actually, for some reason quotes completion _do_ work under certain conditions:

`"som|_string"` -> `"some_string"|`

Which makes me further convinced that this is a bug on nvim-cmp's side. Can you please re-open the issue?

**Comment by hrsh7th** [comment]
I can confirm your PR fixes this problem.
