### ISSUE TITLE
nvim-cmp breaks <Tab> (wildchar) autocompletion in Neovim if following the doc `cmdline setup`

### ISSUE THREAD

**Issue by aktau** [hrsh7th/nvim-cmp#1468]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

At the end of https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim, add (from the README):

```vim
-- `:` cmdline setup.
cmp.setup.cmdline(':', {
 mapping = cmp.mapping.preset.cmdline(),
 sources = cmp.config.sources({
   { name = 'path' }
 }, {
   { name = 'cmdline' }
 })
})
```

### Description

No completion of any kind pops up. Pressing `ctrl-D` still works.

### Steps to reproduce

1. Open nvim (0.9.0+, current HEAD) with the config described above.
2. Type something like `lua vim.ls<Tab>`.

### Expected behavior

I expected it to complete, similar to the default/native functionality.

### Actual behavior

Nothing pops up. No errors. No completion.

**Comment by hrsh7th** [comment]
https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

The vimrc does not install `cmp-cmdline` source.

**Comment by aktau** [comment]
Alright. This may never have worked for me, but recently it started to also break regular command-line completion I guess. I've just removed the setup statement. Thanks!
