### ISSUE TITLE
cmdline freeze on quiting from long line file

### ISSUE THREAD

**Issue by tkkcc** [hrsh7th/nvim-cmp#1469]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
require('packer').init({max_jobs = 5})
require('packer').startup(function()
use 'wbthomason/packer.nvim'
use {
  'hrsh7th/nvim-cmp',
  config = function()
     local cmp = require 'cmp'
     cmp.setup()
  end,
}
end)
```

### Description

cmdline freeze for seconds when I try to quit a long json

### Steps to reproduce

Download this long json, and open it
```sh
wget https://penguin-stats.io/PenguinStats/api/v2/result/matrix -O matrix.json 
nvim matrix.json
```
Type `:q` to quit

### Expected behavior

quit without freeze

### Actual behavior

freeze for seconds

### Additional context

`nvim --clean matrix.json` doesn't have this problem.
nvim v0.8.3

**Comment by mgoral** [comment]
I'm experiencing this issue as well, but for me Neovim freezes right after entering command line (after typing `:`). If I wait long enough, sometimes Neovim crashes (or maybe it's killed by OOM killer).

I'm not sure if it's helpful, but I can break whatever nvim-cmp is doing with Ctrl-C and each time I get the traceback below. After that I can type any command without freezes.

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/nvim-cmp/lua/cmp/config/compare.lua:129: couldn't parse regex: Key
board interrupt
stack traceback:
        [C]: in function 'regex'
        ...te/pack/packer/start/nvim-cmp/lua/cmp/config/compare.lua:129: in function 'callback'
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'ensure'
        ...te/pack/packer/start/nvim-cmp/lua/cmp/config/compare.lua:127: in function 'update'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:302: in function 'callback'
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:138: in function <.../site/pack/packer/start/nvim-cmp/lua/cmp/uti
ls/async.lua:136>
```

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/1433

**Comment by hrsh7th** [comment]
duplicated
