### ISSUE TITLE
I wish I could close the prompt window but I didn't find the option

### ISSUE THREAD

**Issue by yjhtry** [hrsh7th/nvim-cmp#1479]
I hope there is no popover interference in coding, but the other functions of cmp stopped working when I set active=false

**Comment by bushblade** [comment]
If you want to just close the completion popup you can call..

```lua
      require("cmp").mapping.close()
```
I have this mapped to `<C-e>`

**Comment by yjhtry** [comment]
> If you want to just close the completion popup you can call..
> 
> ```lua
>       require("cmp").mapping.close()
> ```
> 
> I have this mapped to `<C-e>`

Thank you very much, But I want to close the popover permanently

**Comment by Shougo** [comment]
You can disable the completion menu by `autocomplete = false`.
For manual completion, you can use `cmp.mapping.complete()`.
