### ISSUE TITLE
characters are overwritten when use <cr> to complete

### ISSUE THREAD

**Issue by ackerr** [hrsh7th/nvim-cmp#1488]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local vim = vim

-- Automatically install lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

-- Plugin
require("lazy").setup({
	{ "rebelot/kanagawa.nvim" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "neovim/nvim-lspconfig" },
	{ "hrsh7th/nvim-cmp" },
	{ "hrsh7th/cmp-nvim-lsp" },
	-- { "windwp/nvim-autopairs" },
	{ "onsails/lspkind-nvim" },
	{ "L3MON4D3/LuaSnip" },
        { "saadparwaiz1/cmp_luasnip", dependencies = "hrsh7th/nvim-cmp" },
})

vim.cmd([[
  silent! colorscheme kanagawa
  highlight VertSplit guibg=NONE
]])

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require("cmp_nvim_lsp").default_capabilities(capabilities)
-- lsp installer

local servers = { "gopls", "rust_analyzer", "lua_ls", "pyright", "vimls", "jsonls", "tsserver" }
require("mason").setup({})
require("mason-lspconfig").setup({
	ensure_installed = servers,
	automatic_installation = true,
})

-- lsp config
local lspconfig = require("lspconfig")

for _, server in ipairs(servers) do
	lspconfig[server].setup({
		capabilities = capabilities,
		-- on_attach = on_attach,
		flags = {
			debounce_text_changes = 150,
		},
	})
end

local cmp = require("cmp")
local lspkind = require("lspkind")
local luasnip = require("luasnip")

require("luasnip.loaders.from_vscode").lazy_load()
cmp.setup({
	formatting = {
		fields = { "kind", "abbr", "menu" },
		format = lspkind.cmp_format({
			with_text = false,
			maxwidth = 50,
			before = function(entry, vim_item)
				vim_item.menu = ({
					nvim_lsp = "[LSP]",
					luasnip = "[Snippet]",
					buffer = "[Buffer]",
					path = "[Path]",
				})[entry.source.name]
				return vim_item
			end,
		}),
	},
	mapping = cmp.mapping.preset.insert({
		["<CR>"] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Insert }),
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-b>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-e>"] = cmp.mapping.close(),
		["<Tab>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_next_item()
			elseif luasnip.expandable() then
				luasnip.expand()
			elseif luasnip.expand_or_jumpable() then
				luasnip.expand_or_jump()
			else
				local copilot_keys = vim.fn["copilot#Accept"]()
				if copilot_keys ~= "" then
					vim.api.nvim_feedkeys(copilot_keys, "i", true)
				else
					fallback()
				end
			end
		end, { "i", "s" }),
		["<S-Tab>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_prev_item()
			else
				fallback()
			end
		end, { "i", "s" }),
	}),
	snippet = {
		expand = function(args)
			require("luasnip").lsp_expand(args.body) -- For `luasnip` users.
		end,
	},
	sources = {
		{ name = "nvim_lsp" },
		{ name = "luasnip" },
		{ name = "buffer" },
		{ name = "path" },
	},
	confirm_opts = {
		behavior = cmp.ConfirmBehavior.Insert,
		select = false,
	},
	window = {
		documentation = {
			border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
		},
	},
	experimental = {
		ghost_text = false,
		native_menu = false,
	},
})
```

### Description

Trying to complete before some characters, the result is that the brackets replace some characters.

Example，I input `fmt.Println("???")`，then i input `fmt.Println` in front of them，when i type <cr>，the brackets overwrite `fmt`
![20230308-194907](https://user-images.githubusercontent.com/35414361/224695700-dbdeb7e5-b5b6-4437-9d09-ffef39820962.gif)

### Steps to reproduce

1. use the config
2. use gopls 
3. input some characters
4. complete something in front of them

### Expected behavior

When i type <cr>， it should be `fmt.Println()fmt.Println()`, not `fmt.Println().Println()`

### Actual behavior

characters are overwritten when use <cr> to complete

**Comment by jivvy** [comment]
The same happens to me with `rust-analyzer` and `rust-tools`

Completing from text works correctly, the text positioned after the completion remains in that case
Completing when the source is 'Module' , 'Function', 'Keyword', etc, suggesting it came from rust lsp, will then replace the text positioned after the completion, which should not happen

**Comment by FinleyGe** [comment]
Similar problem to me. It could be cause by nvim-lsp (or some of them). Because after I close the LSP server by `Lspsaga stop` and  complete  by the content, this problem disappeared.
I am using `volar` as LSP server to code vue SPF btw.

**Comment by hrsh7th** [comment]
It's gopls problem. I think.

See https://github.com/hrsh7th/nvim-cmp/issues/611

**Comment by FinleyGe** [comment]
> Similar problem to me. It could be cause by nvim-lsp (or some of them). Because after I close the LSP server by `Lspsaga stop` and complete by the content, this problem disappeared. I am using `volar` as LSP server to code vue SPF btw.

I am sorry I misread this issue. My problem is not similar with this issue. And maybe it is caused by `volar`. I will issue in volar's repo to get some help.
