### ISSUE TITLE
[feat req] config for ghost text hl

### ISSUE THREAD

**Issue by McAuleyPenney** [hrsh7th/nvim-cmp#149]
Submitted before writing anything. My bad.

So, I realize that ghost text is experimental right now. I personally love the feature and hope that it stays around, but using the Comment highlight makes writing comments a little more difficult. I'd love to be able to choose the highlight from the configuration. I'd try writing it myself but I don't know if, when, or how ghost text will be integrated permanently, e.g. moved out of the experimental table in configuration, so I don't know if I should attempt a change at the moment.

So, my questions are: will ghost text be formally integrated later on? If so, would it make sense to write a configuration option to change it's highlight right now?

**Comment by hrsh7th** [comment]
It's still experimental but we can make it configurable.
I will consider it.

**Comment by hrsh7th** [comment]
I've added the option `experimental.ghost_text.hl_group`
