### ISSUE TITLE
bug: doc not showing for all functions/methods

### ISSUE THREAD

**Issue by primalmotion** [hrsh7th/nvim-cmp#150]
In the list of completion items, highlighting a function or method sometimes shows the doc, sometimes not. I cannot find what causes to not show. This was working perfectly well on CoC and omnifunc shows them all.

Here's an example of what's happening:

https://user-images.githubusercontent.com/208711/132111608-d064cd50-4e85-4f12-92d7-1c335aea5d57.mp4

Let me know if you need more info. This is the last thing that prevents me to switch from CoC :)

**Comment by hrsh7th** [comment]
I will investigate it.

**Comment by hrsh7th** [comment]
@primalmotion I can't reproduce this now. Could you try this with latest cmp?

**Comment by aspeddro** [comment]
i'm having a problem similar to this. All function of `vim` not show documentation (only `function`). I don't know if it's a problem with lsp or plugin.

![image](https://user-images.githubusercontent.com/16160544/132277219-66b8ea40-4db1-45eb-a22d-6f475dd7fd23.png)

LspInfo:
![image](https://user-images.githubusercontent.com/16160544/132277339-014571ab-8070-4d29-8752-ea1229a88d05.png)

```lua
-- my config
local cmp = require'cmp'
cmp.setup{
  completion = {
    completeopt = 'menu,menuone,noinsert',
  },
  snippet = {
    expand = function(args)
      require'luasnip'.lsp_expand(args.body)
    end,
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<Esc>'] = cmp.mapping.close()
  },
  formatting = {
    format = function(entry, vim_item)
      vim_item.kind = require("lspkind").presets.default[vim_item.kind] .. " " .. vim_item.kind
      vim_item.menu = ({
        buffer = "[Buffer]",
        nvim_lsp = "[LSP]",
        luasnip = "[LuaSnip]",
        nvim_lua = "[Lua]",
        latex_symbols = "[Latex]",
      })[entry.source.name]
      return vim_item
    end
  },
  sources = {
    { name = 'luasnip' },
    { name = 'nvim_lua' },
    { name = 'vsnip' },
    { name = 'path' },
    { name = 'latex_symbols' },
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'emoji' }
  }
}
```

**Comment by hrsh7th** [comment]
@aspeddro It is not a LSP completion. It is `nvim_lua`'s item.

**Comment by aspeddro** [comment]
Thank you @hrsh7th. Fixed

**Comment by primalmotion** [comment]
I updated to latest, and it seems to work fine for me now. Thanks!

**Comment by primalmotion** [comment]
sorry. reopening. I missed your PR
