### ISSUE TITLE
misaligned text in floating window

### ISSUE THREAD

**Issue by Diogo-ss** [hrsh7th/nvim-cmp#1504]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require('cmp')

cmp.setup({
    snippet = {
        expand = function(args)
            vim.fn["UltiSnips#Anon"](args.body)
        end,
    },

    sources = {
        {name = 'nvim_lsp', keyword_length = 1},
        { name = 'ultisnips', keyword_length = 1},
    },
})
```

### Description

Text is misaligned in the floating window.

![image](https://user-images.githubusercontent.com/86174715/228998660-173fe880-f454-4797-9296-2227b71b4e11.png)
![image](https://user-images.githubusercontent.com/86174715/228998964-9088257d-76e5-448f-af42-d1380a95c727.png)

### Steps to reproduce

Use Clangd(15.0.6) installed through Mason.
Nvim v0.8.3

### Expected behavior

aligned and flawless text.

### Actual behavior

text is misaligned in floating window suggestions.

**Comment by gegoune** [comment]
Seems like your 'key' icon is double width maybe?

**Comment by hrsh7th** [comment]
I guess it was a clangd side problem.

The nvim-cmp's help describe it. Could you read it?

```
I'm using clangd. The menu items are mis-indented. 

  It's caused by clangd. You can specify `--header-insertion-decorators` for
  clangd's command-line arguments. See #999.
```
