### ISSUE TITLE
[Feature/Question] Select one character from current match

### ISSUE THREAD

**Issue by Bekaboo** [hrsh7th/nvim-cmp#1505]
I wonder if it is possible to make nvim-cmp accepting **one character** from current match, just like what nvim will do with native `popupmenu-completion`:

```
CTRL-L		  Add one character from the current match, may reduce the
		  number of matches.
```

Thanks for your work!

**Comment by hrsh7th** [comment]
Sorry. I can't understand the feature how useful.
