### ISSUE TITLE
Is there a way to trigger suggestion withouting typing anything

### ISSUE THREAD

**Issue by MOB-34** [hrsh7th/nvim-cmp#1507]
i am using the vim plugin in vscode with the following configuration, and i want to achive a behaviour in nvim like i mentioned in the title
```json
{
   "vim.insertModeKeyBindings": [
    {
      "before": ["<C-i>"],
      "commands": ["editor.action.triggerSuggest"]
    }
  ]
}
```

**Comment by Player01osu** [comment]
``` lua
cmp.setup({
	mapping = {
		["<C-i>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
		["<C-e>"] = cmp.mapping({
			i = cmp.mapping.abort(),
			c = cmp.mapping.close(),
		}),
})
```

**Comment by MOB-34** [comment]
> ```lua
> cmp.setup({
> 	mapping = {
> 		["<C-i>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
> 		["<C-e>"] = cmp.mapping({
> 			i = cmp.mapping.abort(),
> 			c = cmp.mapping.close(),
> 		}),
> })
> ```

@Player01osu  it works, thx

**Comment by miron2363** [comment]
Ctrl + i is the same as tab in vim / nvim. So choose another shortcut to don't lose the tab in insert mode people
https://www.reddit.com/r/vim/comments/oywg54/how_to_remap_tab_without_affecting_ctrli/
