### ISSUE TITLE
Question: Sort LSP output

### ISSUE THREAD

**Issue by mikatpt** [hrsh7th/nvim-cmp#151]
Hi there! Thanks for all your hard work on this plugin. I was reading through your `types/lsp.lua` file and I noticed that you have a specific order for LSP output. Is there a way we could change this order? I didn't see a way to do that with the comparators.

When I'm using go, I frequently type <C-SPACE> inside structs to open cmp and look through field names, but cmp renders functions before fields for LSP.

```go
type A struct  {
    X string
}

test := A{
    // type <C-SPACE> for field names
    // expect fields to appear before functions
} 
```

Thank you!

**Comment by hrsh7th** [comment]
See https://github.com/hrsh7th/nvim-cmp#sortingcomparators-type-function
