### ISSUE TITLE
`<Tab>` not working in CSI u mode

### ISSUE THREAD

**Issue by sxyazi** [hrsh7th/nvim-cmp#1510]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

See the description.

### Description

I'm using neovim's CSI u extension, which allows me to treat `<Tab>` and `<C-i>` as two different keys, so I can bind only `<C-i>`, while keeping the default behavior of `<Tab>` in neovim like this:

```lua
vim.keymap.set("i", "<C-i>", "<Esc>5k")
```

Unfortunately, cmp doesn't handle it correctly, and here's a minimal configuration:

```lua
cmp.setup({
  mapping = {
    ["<Tab>"] = cmp.mapping.confirm({ select = true })
  }
})
```

When there is no autocomplete candidate, it maps the behavior of `<Tab>` to `<C-i>`, but it is expected to be `<Tab>`. I tried using it in the following way and it works fine:

```lua
["<Tab>"] = cmp.mapping(function()
  if cmp.visible() then
    cmp.confirm({ select = true })
  else
    vim.api.nvim_feedkeys("\t", "n", false)  -- avoid remap to the behavior of <C-i>
  end
end, { "i", "c" }),
```

But when I need to set `<Tab>`, `<C-i>` at the same time, it breaks again (`<C-i>` is the navigation key in my keyboard layout):

```lua
cmp.setup({
  mapping = {
    ["<Tab>"] = cmp.mapping.confirm({ select = true }),
    ["<C-i>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
  }
})
```

The configuration above will work with only one key, since it identifies `<Tab>` and `<C-i>` as the same key. 

I tried checking the issues but didn't find anything relevant, not sure if I'm missing something there :(

### Steps to reproduce

Set both `<Tab>` and `<C-i>` for cmp, while binding `<C-i>` in neovim.

### Expected behavior

Treat `<Tab>` and `<C-i>` as different keys.

### Actual behavior

Same key over there.

**Comment by hrsh7th** [comment]
I don't know how to debug with CSI.

But I know `<Tab>` and `<C-i>` has same meaning in usual terminal and neovim.

I checked the implementation of nvim-cmp and (maybe) improve it. Could you test with this?

Branch: try-to-fix-csi

**Comment by sxyazi** [comment]
Well done! It works now! 😆

**Comment by hrsh7th** [comment]
I'd merged the branch. Thank you for testing.
