### ISSUE TITLE
[Questing] Is there an explain or document for sorting.comparators ?

### ISSUE THREAD

**Issue by nanozuki** [hrsh7th/nvim-cmp#152]
I want to customize the completion suggestion list. But I can't understand each meaning for `sorting.comparators`.
Is there an explain or document for `sorting.comparators` ?

I tried nvim `:help` but no answer returned.

And there is another question in this situation: Why the preselected item is not always on the top of the suggestion list.

**Comment by hrsh7th** [comment]
It is an,advanced configuration. I have no plan to explain in detail.
If you want customize it, please read the default config.

**Comment by nanozuki** [comment]
> It is an,advanced configuration. I have no plan to explain in detail.
> If you want customize it, please read the default config.

OK, is there a method to let the preselected item always be on the top?
