### ISSUE TITLE
How to disable nvim-cmp or disable all cmp-sources for certain files?

### ISSUE THREAD

**Issue by doronbehar** [hrsh7th/nvim-cmp#1522]
I have a long bash script with an enormous amount of variables that I think make my `nvim-cmp` stuck when I try to edit it. How do I disable it? I'm looking for something like treesitter's feature:

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/README.md?plain=1#L132-L139

**Comment by doronbehar** [comment]
BTW I did encounter the `enable = function() ... end` option to `cmp.setup`, but the problem is that it seems that I either enable completely, or disable completely nvim-cmp... The behavior I'm looking for is per-buffer and per cmp-source: to be able to control which cmp source is enabled for each buffer. I did find out that the problematic cmp source is [cmp-treesitter](https://github.com/ray-x/cmp-treesitter).

**Comment by uga-rosa** [comment]
It can be managed from the source side by defining the `source:is_available()` method.
https://github.com/hrsh7th/nvim-cmp/blob/e28fb7a730b1bd425fdddfdbd3d36bb84bd77611/doc/cmp.txt#L748-L752

In other words, this issue should be put up in cmp-treesitter, not here.

**Comment by hrsh7th** [comment]
You can fully control nvim-cmp configuration based on autocmd as below.

```lua
vim.api.nvim_create_autocmd('FileType', {
  callback = function()
    require('cmp').setup.buffer {
      ...
    }
  end,
})
```

**Comment by doronbehar** [comment]
Thanks for the idea @hrsh7th :) For the sake of others I added a wiki subsection at:

https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disable--enable-cmp-sources-only-on-certain-buffers

**Comment by gitaarik** [comment]
This seems to work for me too, for completely disabling nvim-cmp for a certain filetype:

```lua
require("cmp").setup.filetype("txt", {
  enabled = false,
})
```

**Comment by space11** [comment]
@gitaarik Thanks for sharing, exactly what I was looking for.
