### ISSUE TITLE
Disable Tab and S-Tab

### ISSUE THREAD

**Issue by RobertBrunhage** [hrsh7th/nvim-cmp#1527]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require('cmp')

local cmp_mappings = cmp.mapping.preset.insert({
  ["<C-b>"] = cmp.mapping.scroll_docs(-4),
  ["<C-f>"] = cmp.mapping.scroll_docs(4),
  ["<C-y>"] = cmp.mapping.complete(),
  ["<C-e>"] = cmp.mapping.abort(),
  ["<CR>"] = cmp.mapping.confirm({ select = false }),
});

-- disable completion with tab
-- this helps with copilot setup
-- This doesn't seem to work though
cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil

cmp.setup({
  sources = {
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'luasnip' },
    { name = 'buffer',  keyword_length = 5 },
  },
  mapping = cmp_mappings,
})

```

### Description

I want to disable Tab fully as I am using Copilot which I want to use Tab with. However, even if I try to "unbind" `Tab` it still is mapped when checking `:map`

![image](https://user-images.githubusercontent.com/26344867/233668563-441a8ae1-abe3-4731-954c-1f784387f7a3.png)

### Steps to reproduce

Any setup with cmp

### Expected behavior

Tab should be able to disable

### Actual behavior

Can't disable Tab

### Additional context

Tried https://github.com/hrsh7th/nvim-cmp/issues/880#issuecomment-1094144400 but had no effect either

**Comment by RobertBrunhage** [comment]
Closing, seemed to reset after a couple of tried of just disabling and enabling cmp and copilot. Seemed like something was cached?

**Comment by trigun539** [comment]
@RobertBrunhage how did you disable/enabled cmp and copilot? Still unable to unmap tab.

**Comment by RobertBrunhage** [comment]
@trigun539 I used what I described in the issue and after some restarts it just correctly unmapped it. Not sure if it somehow was cached or similar, but for me this was in the end, enough.

```lua
-- disable completion with tab
-- this helps with copilot setup
-- This doesn't seem to work though
cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil
```

**Comment by hrsh7th** [comment]
The `nil` has specisl,meaning in Lua.

You should ise `vim.NIL`
