### ISSUE TITLE
option to autocomplete your cursor's text on the first item too

### ISSUE THREAD

**Issue by Thanatermesis** [hrsh7th/nvim-cmp#1529]
I have the "autocomplete = false", so menu only opens when I hit "tab"

If you see, when the second item is selected, the text in the cursor is filled up (similar to ghost_text), but this doesn't happens with the first item

In the normal behaviour that's somewhat normal, where the menu always opens with the first item preselected, but only when you scroll to the next option your cursor's text is modified, the issue is that the first item is not really preselected just hilighted, but when you trigger cmp.complete(), the first item should be selected in the same way the next ones are

**Comment by Shougo** [comment]
It seems dup of https://github.com/hrsh7th/nvim-cmp/discussions/1424

**Comment by Thanatermesis** [comment]
@hrsh7th tried but doesn't seems to work, I have recorded a video showing the issue: https://youtu.be/awc4BjLwf9M

**Comment by hrsh7th** [comment]
What do you get the result with `:echomsg &completeopt`?

**Comment by Shougo** [comment]
It seems Vim completeopt menu behavior.

**Comment by Thanatermesis** [comment]
1. menu,preview

2. i  <Tab>       * <Lua 480: ~/.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
                 cmp.utils.keymap.set_map

3. http://sprunge.us/bqzcZB

**Comment by hrsh7th** [comment]
@Thanatermesis Could you try with `:set completeopt=menu,menuone,noselect`?

**Comment by hrsh7th** [comment]
I can't determine the root cause. Sorry.

**Comment by Shougo** [comment]
@Thanatermesis You should create the minimal `init.lua` for it.

**Comment by uga-rosa** [comment]
Is nvim-cmp updated to the latest version?
Also, please provide a stand alone `init.lua` that describes the minimal configuration necessary to reproduce this issue as @Shougo suggests. [This](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim) is a good base to build on.

**Comment by Shougo** [comment]
Please don't use the plugin distribution for it.
It is not easy to reproduce for us.

**Comment by hrsh7th** [comment]
Could you try the following?

```lua
require('cmp').setup {
  completion = {
    completeopt = 'menu,menuone,noselect'
  }
}
```

My nvim-cmp config does not reproduce this problem so I think you should raise issue for the nvchad side.

**Comment by Thanatermesis** [comment]
There's a small screencast of all the process (installing the nvim NvChad framework from zero, and without extra plugins) from scratch, the modifications I did to disable the autopopup, and showing the issue, including a "set" of the parameters you told me, in a strange way even if I set the values you said, it seems like when running nvim they are replaced by "menu,preview" 🤔  

> My nvim-cmp config does not reproduce this problem so I think you should raise issue for the nvchad side.

Maybe @siduck knows why the value of completeopt is replaced


_Note: the bug is on the minute 5:00, already included on the link:_

https://asciinema.org/a/IlDwksvQPFlq3qWY3emVwnMlF?t=4:58

**Comment by siduck** [comment]
> There's a small screencast of all the process (installing the nvim NvChad framework from zero, and without extra plugins) from scratch, the modifications I did to disable the autopopup, and showing the issue, including a "set" of the parameters you told me, in a strange way even if I set the values you said, it seems like when running nvim they are replaced by "menu,preview" thinking
> 
> > My nvim-cmp config does not reproduce this problem so I think you should raise issue for the nvchad side.
> 
> Maybe @siduck knows why the value of completeopt is replaced
> 
> _Note: the bug is on the minute 5:00, already included on the link:_
> 
> https://asciinema.org/a/IlDwksvQPFlq3qWY3emVwnMlF?t=4:58

![image](https://user-images.githubusercontent.com/59060246/235273137-28089365-72a6-4574-9349-203d0d1e189d.png)


just override nvim-cmp opts in your custom plugins

**Comment by Thanatermesis** [comment]
@siduck yes that's what I do but it doesn't seems to take effect, I changed it to "menu,menuone,noselect" but it doesn't gets static (as you can see in the video), on the other hand I set it manually with :set to that value but the bug stills present 🤔

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/235274201-93a11d2e-c682-4670-aadd-b3c34321c54c.mp4

@Thanatermesis 

```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      completion = {
        completeopt = "menu,menuone,noselect",
      },
    },
  },
  ```

**Comment by Thanatermesis** [comment]
@siduck  Mmmh, I don't think so, the issue is that when the menu is set to not automatically popup all the time but with manually triggering it, so by pressing tab, the text is not autocompleted to the first result, only to the next ones

This means, adding "autocomplete = false," on the completion section, and in the TAB mapping, changing the fallback line to "cmp.complete()"

More details on the first post and a demo on the video: https://youtu.be/awc4BjLwf9M

**Comment by Thanatermesis** [comment]
Ok so I think this code made it finally working, so first I need to have the entry to ```completeopt = "menu,menuone,noselect",``` otherwise without "noselect", the first selection will be made _(without filling up my code with it, so what is this issue about)_, 

Then, I need to replace the ```cmp.complete()``` entry (which is triggered with Tab) using this combination instead, which If im not wrong what it does is "create the menu" and "switch to the first item"

```lua
        cmp.complete({ behavior = cmp.SelectBehavior.Select })
        cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
```

This looks very good! the menu only appears when I press Tab, at the same time my text has the added keyword, if I press "space" the keyword is kept (used) on my line, if i want to open a snippet I press "enter"... same behaviour with the menu automatically showing up (which is annoying for me at the moment because [it doesn't lets me to use Copilot as I mentioned here](https://github.com/hrsh7th/nvim-cmp/issues/495#issuecomment-1532565576))

**Comment by srcrip** [comment]
For anyone coming across this from google, you can improve it a little bit more by conditionally running complete based on whether the menu is already open. heres the full example I'm using right now:

```lua
          ["<C-k>"] = cmp.mapping(function(fallback)
            if not cmp.visible() then
              cmp.complete({ behavior = cmp.SelectBehavior.Select })
            end
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert })
          end, { 'i', 's' }),
          ["<C-j>"] = cmp.mapping(function(fallback)
            if not cmp.visible() then
              cmp.complete({ behavior = cmp.SelectBehavior.Select })
            end
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
          end, { 'i', 's' }),
```
