### ISSUE TITLE
Autocomplete confirm ignores existing closing braces

### ISSUE THREAD

**Issue by nguyenvukhang** [hrsh7th/nvim-cmp#1532]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
call plug#begin("./plug")
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'L3MON4D3/LuaSnip'
call plug#end()

lua <<EOF
  local cmp = require'cmp'
  cmp.setup({
    completion = {
      keyword_length = 1
    },
    snippet = {
      expand = function(args)
        require('luasnip').lsp_expand(args.body)
      end,
    },
    mapping = cmp.mapping.preset.insert({
      ['<C-l>'] = cmp.mapping.confirm({ select = true }),
    }),
    sources = cmp.config.sources({{ name = 'nvim_lsp' }, { name = 'luasnip' }})
  })
  require('lspconfig').tsserver.setup({
    capabilities = require('cmp_nvim_lsp').default_capabilities(
      vim.lsp.protocol.make_client_capabilities()
    )
  })
EOF
```

### Description

When autocompleting within `{}` braces and the `}` braces already exists, confirming completion will still add a new brace.

### Steps to reproduce

save the config into `init.vim`, and save the following script locally as `run.sh`

```sh
#!/bin/sh

cleanup() {
  rm -rf nvim plug node_modules package.json yarn.lock index.js
}
trap cleanup EXIT

yarn init -y
yarn add --dev @types/node

mkdir nvim
cp init.vim nvim/init.vim

curl -fLo nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

XDG_CONFIG_HOME=. nvim -c "PlugInstall" -c "qa"

echo "import { readFileSync }" >index.js

XDG_CONFIG_HOME=. nvim index.js -c "norm! fc"
```

Then run it with

```sh
sh run.sh
```

It should open `index.js` and put the cursor on "c" of "readFileSync".

```javascript
import { readFileSyn█ }
```

(Manually) press `sc<CR>` to replace the "c" and trigger the completion menu, and select the first result.

### Expected behavior

```javascript
import { readFileSync } from "fs";
```

### Actual behavior

```javascript
import { readFileSync } from "fs"; }
```

### Additional context

MacOS Ventura 13.2.1
neovim version:
```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Shougo** [comment]
Hm....  It seems hard to fix the problem.

**Comment by uga-rosa** [comment]
![1532](https://user-images.githubusercontent.com/82267684/234056833-56c455a2-2aaf-4c59-919d-828b92d23b07.gif)

I can't reproduce it.

**Comment by uga-rosa** [comment]
Also, the minimum configuration you are putting up cannot be reproduced as well. Perhaps you are not disabling some plugins because you are using a plugin manager that normally uses the pack function such as packer.nvim?

**Comment by nguyenvukhang** [comment]
I'm running the minimum configuration with `XDG_CONFIG_HOME=. nvim index.js`, and I've also put a `print()` in my original daily config to assert that it's not being ran.

I've updated the minimal config above to include the exact sequence of commands I ran to reproduce the issue, from scratch, including setting up the plugin manager (vim-plug).

Also, I tried using lexima.vim but unfortunately the extra brace still appears.

**Comment by uga-rosa** [comment]
I have tried the init.vim and run.sh you prepared, but it still does not reproduce.
If the plugin is still in `~/.local/share/nvim/site/pack/*/start/`, etc., it will load on its own, have you checked (which is why I suspected you were a packer user)?

**Comment by nguyenvukhang** [comment]
Yep, I've cleared out `~/.local/share/nvim/site/pack/*/start/` and also used `$NVIM_APPNAME`, but I'm still getting the same behavior.

(running `:echo &rtp` on my latest debug state does indeed show that the runtimepaths are properly replaced.)

I'll try it again on a docker container and see if I can isolate the situation further.

**Comment by uga-rosa** [comment]
What is tsserver's version?

**Comment by hrsh7th** [comment]
I can't reproduce.
I did press the `<C-y>` to confirm the item in the below screencast.

https://user-images.githubusercontent.com/629908/234166325-4fb1fec0-94e4-4d71-aed4-9decaa478861.mov

**Comment by nguyenvukhang** [comment]
> What is tsserver's version?

I'm currently on 1.2.0

That's surprisingly outdated.

After updating, the bug is fixed.

Thanks for the help @uga-rosa

**Comment by SuggonM** [comment]
Same issue here with snippets containing braces.

https://github.com/user-attachments/assets/eb9390c7-c667-441a-a476-535b48b008ce

In VScode for comparison:

https://github.com/user-attachments/assets/e2956975-edbd-4537-a016-2e2bdf646ccd
