### ISSUE TITLE
Feature - Max number of completions

### ISSUE THREAD

**Issue by patrickaldis** [hrsh7th/nvim-cmp#1535]
It would be great to be able to set the maximum number of completions, as some completion boxes have many entires spanning the entire window. This can feel quite invasive. I might have missed something but I don't believe there is a way to do this currently

**Comment by Shougo** [comment]
You can use this.

https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L555

**Comment by patrickaldis** [comment]
Doesn't this throw away the entries > `max`. What I was thinking was having a height for the completion box, where if there are > `max` entries, these could still be browsed with a scroll bar

**Comment by hrsh7th** [comment]
their comment is correct.
