### ISSUE TITLE
Feature: option to complete word by word; option to complete line by line

### ISSUE THREAD

**Issue by xuyangy** [hrsh7th/nvim-cmp#1536]
For some completion sources such as Tabnine or Copilot, the completion items are usually multiple words or even multiple lines. However, often times, the whole multi-word or multi-line completion item is not exactly what one needs. It will be really convenient to be able to complete word by word and line by line.

**Comment by Shougo** [comment]
I think you should upload the examples.

> It will be really convenient to be able to complete word by word and line by line.

And it should be requested in source level?

**Comment by hrsh7th** [comment]
This plugin based on the LSP spec. I have no plan to do this.

**Comment by xuyangy** [comment]
Thanks @hrsh7th @Shougo for a quick reply. 
When I type `I want a b`, assume the first completion item is `beautiful dog`. If I press Enter, I will accept that as a whole and I will have `I want a beautiful dog`.

What I want is another mapping, say `<C-w>` to accept only the first space separated word, i.e. when I press `<C-w>`, I want to have `I want a beautiful`. Then the popup will be closed and reopened with updated completions. Of course I can continue typing like `I want a beautiful cat`.

@Shougo, I was thinking that the source can be the same as whatever the LSP supply, the preview, document etc will all be the same. It's only when I "confirm", I want to intercept the completion text the LSP supply, split it by `space` or by `newline` and insert the first word or first line into the buffer instead of the whole completion text.

**Comment by Shougo** [comment]
Hm.. I understand.

**Comment by MatejBransky** [comment]
Here is the related discussion where I've added a recording of how it works in the VS Code: https://github.com/hrsh7th/nvim-cmp/discussions/1579
