### ISSUE TITLE
How to disable cmp for particular string?

### ISSUE THREAD

**Issue by prashantt492** [hrsh7th/nvim-cmp#1539]
I am using nvim-cmp for writing tex files. But whenever I use period "." at the end of sentences and then press enter key to move to the next line, the very first snippet from the popup triggers. This gets very annoying to insert blankspace and then move to the next line.
Is there a way to disable it for a particular string?

**Comment by hrsh7th** [comment]
You can use `entry_filter`. 
See `:h entry_filter`.
