### ISSUE TITLE
Auto completion items are not showing as expected

### ISSUE THREAD

**Issue by janghan-park** [hrsh7th/nvim-cmp#154]
https://user-images.githubusercontent.com/87399910/132119771-24929bfd-f76f-4030-b577-68cb5f07a98d.mov

When starting to type, The list of completion items are not showing until I execute cmp.mapping.complete() manually which is  mapped with "C-Space"

I couldn't find this behaviour while working in a react project.
(I am not sure If it has anything to do with that.. just wanted to mention)

**Comment by hrsh7th** [comment]
Please your cmp.setup call.

**Comment by janghan-park** [comment]
```
-- Set completeopt to have a better completion experience
vim.o.completeopt = "menuone,noselect"

-- luasnip setup
local luasnip = require "luasnip"

-- nvim-cmp setup
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      require("luasnip").lsp_expand(args.body)
    end
  },
  mapping = {
    ["<C-p>"] = cmp.mapping.select_prev_item(),
    ["<C-n>"] = cmp.mapping.select_next_item(),
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    ["<C-Space>"] = cmp.mapping.complete(),
    ["<C-e>"] = cmp.mapping.close(),
    ["<CR>"] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true
    },
    ["<TAB>"] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true
    }
  },
  sources = {
    {name = "nvim_lsp"},
    {name = "buffer"},
    {name = "luasnip"}
  },
  formatting = {
    format = function(entry, vim_item)
      -- fancy icons and a name of kind
      vim_item.kind = require("lspkind").presets.default[vim_item.kind] .. " " .. vim_item.kind

      -- set a name for each source
      vim_item.menu =
        ({
        buffer = "[Buffer]",
        nvim_lsp = "[LSP]",
        luasnip = "[LuaSnip]",
        nvim_lua = "[Lua]",
        latex_symbols = "[Latex]"
      })[entry.source.name]
      return vim_item
    end
  }
}

```

Here is my nvim-cmp setup

**Comment by hrsh7th** [comment]
It seems language server problem.
which langiage server are you using?

**Comment by janghan-park** [comment]
Thank you for your very fast answer :)

I am using this language server

[https://github.com/vuejs/vetur/tree/master/server](url) which is mentioned in nvim-lspconfig page

[https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#vuels](url)


https://user-images.githubusercontent.com/87399910/132122181-3373731c-1785-4d28-909d-b68726eddc03.mov

Unfortunately, It works fine with nvim-compe which is kinda previous version of nvim-cmp.

**Comment by hrsh7th** [comment]
Oh... Hm... I will investigate it.

**Comment by hrsh7th** [comment]
@janghan-park Fixed. Thank you. It's insightful issue.

**Comment by janghan-park** [comment]
@hrsh7th Thank YOU for making life easier 👍
