### ISSUE TITLE
Improved documentation on adding custom key mappings

### ISSUE THREAD

**Issue by s1nistr4** [hrsh7th/nvim-cmp#1545]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

There should be better docs on how to write custom keymappings for this. For example, if you want to set it up so you can select items using leader + hjkl keys or something, instead of the arrow keys or default config.

I checked the readme and the help section and neither of them had any solution to this

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

**Comment by hrsh7th** [comment]
Did you read the [docs](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L250)?

I don't want to include huge example settings.

I understand you want `arrow key setting` but I'd received a lot of request about `tab key setting` example.
