### ISSUE TITLE
Completing with a printable character does not insert the character

### ISSUE THREAD

**Issue by CalinLeafshade** [hrsh7th/nvim-cmp#155]
If i type something completable and then use a printable character to commit the completion (like a parenthesis `(`) the parenthesis is not printed.

![image](https://user-images.githubusercontent.com/3149669/132141513-eb211f74-022c-42a6-b1ee-dc7181c05967.png)

Then I press `(`

![image](https://user-images.githubusercontent.com/3149669/132141519-50b1d0e4-57d7-48b7-837a-42ef1095818d.png)

I would expect it to look like:

![image](https://user-images.githubusercontent.com/3149669/132141527-7a90d296-85be-4552-b15c-81c460c4e844.png)

**Comment by hrsh7th** [comment]
I can't reproduce it.

https://user-images.githubusercontent.com/629908/132207489-0c6c5e64-2040-438b-bddf-963883564f40.mp4

**Comment by Shougo** [comment]
@CalinLeafshade I think you should upload the minimal config.

**Comment by hrsh7th** [comment]
I can't reproduce it.

https://user-images.githubusercontent.com/629908/132208475-4dbbcb0d-8165-4433-9678-0b28d54d1306.mp4
