### ISSUE TITLE
Autocomplete does not disappear when cmp panel closes

### ISSUE THREAD

**Issue by TroySigX** [hrsh7th/nvim-cmp#1550]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

``` lua
local cmp = require('cmp')
cmp.setup({
    mapping = cmp.mapping.preset.insert({
    ['<Tab>'] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        else
          fallback()
        end
    end, { 'i', 's' }),
    })
})
```

### Description

When the cursor reaches the end of the suggestion panel, when I press `Tab` again, I would expect the  autocomplete to disappear

### Steps to reproduce

1. Press something
2. Cmp panel shows up for suggestion
3. Navigate all the way down to the end (pressing `Tab`)
4. Press `Tab` again to deselect the last suggestion

### Expected behavior

The autocomplete shown on editor disappear

### Actual behavior

It doesn't. Here's the photo:
Last suggestion selected:
![image](https://user-images.githubusercontent.com/88051085/235781015-4802bb36-9e4a-46c5-aa49-acf9a069db2e.png)

Deselect last suggestion (using `Tab`):
![image](https://user-images.githubusercontent.com/88051085/235781105-220cfbff-0af7-4963-8368-71a530e0aba7.png)

**Comment by hrsh7th** [comment]
Generaly, some of the completion software does not behave as your expectation.

You should manage it via your custom key mappng.

The following codes just are example. I can't provide full example of codes now. (I'm now on the outside of my home. Sorry).

```lua
local cmp = require('cmp')
cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ['<Tab>'] = cmp.mapping(function(fallback)
        if cmp.visible() then
          local entries = cmp.get_entries()
          local bottom_entry = entries[#entries]
          if bottom_entry == cmp.get_selected_entry() then
            cmp close()
          else
            cmp.select_next_item()
          end
        else
          fallback()
        end
      end, { 'i', 's' }),
    })
})
```

**Comment by TroySigX** [comment]
No, what I meant was, if I type `con` in a cpp file, cmp will suggest 2 completions `const` and `constexpr`, when iterating through the suggestion list, cmp will show the autocompletion on the editor as a preview, and when pressing `Tab` after the last entry in cmp is reached, I would expect the autocompletion on the editor would disappear as well (last suggestion is `constexpr`, and this is shown on the editor, pressing `Tab` again, I'd want to have `con`, as I previously typed, back)

**Comment by hrsh7th** [comment]
You can use `cmp.abort()` instead of `cmp.close()`. Please read the docs!

**Comment by TroySigX** [comment]
I switched to `cmp.abort()`, but it still doesn't work

**Comment by hrsh7th** [comment]
It seems I misunderstood the content of your issue.
Fixed a bug that the input characters were not restored when the selection of completion candidates was stopped.

**Comment by TroySigX** [comment]
It works, thank you!
