### ISSUE TITLE
Extra character is added when confirm completion

### ISSUE THREAD

**Issue by luarch** [hrsh7th/nvim-cmp#1552]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
call plug#begin()
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua dofile("./config.lua")
```

```lua
local lspconfig = require('lspconfig')

local capabilities = require('cmp_nvim_lsp').default_capabilities()
lspconfig['clangd'].setup {
    capabilities = capabilities
}
lspconfig['pyright'].setup {
    capabilities = capabilities
}

local cmp = require 'cmp'
cmp.setup({
    snippet = {
        -- REQUIRED - you must specify a snippet engine
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        end,
    },
    window = {
        documentation = cmp.config.window.bordered(),
    },
    mapping = cmp.mapping.preset.insert({
        ['<C-b>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.abort(),
        ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
    sources = cmp.config.sources(
        {
            { name = 'nvim_lsp' },
            { name = 'vsnip' }, -- For vsnip users.
        }
    ),
    confirmation = {
      get_commit_characters = function(commit_characters)
        return {}
      end
    }
})
```

### Description

When using cmp with Clangd, upon confirmation of completion with `<CR>`, an extra character will be added.

In following example I tried to select a method `data()` expect to get `v.data()` but instead get `v.data()d`:
![Recording 2023-05-03 at 20 06 06](https://user-images.githubusercontent.com/2871155/235911365-0e04f725-2fe4-4e92-9b8e-3de6c2c43c6f.gif)

### Steps to reproduce

Try to complete a method name with clangd LSP.

### Expected behavior

Method name get completed with no extra unwanted characters.

### Actual behavior

Method name is completed but followed by an unwanted character.

### Additional context

It seems it has higher probability to be triggered if there are many candidate items in the completion popup.

The extra character seems always to be the first character of the method name being completed.

I also tried with ccls. It suffers the same. But with Pyright no issue.

**Comment by NicolasGB** [comment]
Hi! I'm having the same exact issue, tested in gopls and and rust_analyzer.

This seems to happen when completing without any previous character belonging to the completion. When i start typing it autocompletes fine but when i'm chaining methods after a "." the autocompletion adds the first letter to the end of it. Also happens if i prompt cmp in a blankline and choose a completion.

**Comment by luarch** [comment]
> Can confirm this. Also happens with gopls and possibly others (not yet tested). It only happens when completing **directly after the dot** without typing any more character.
> 
> Probably caused by commit [524cc0b](https://github.com/hrsh7th/nvim-cmp/commit/524cc0ba6146efd938b0e76fe23e7fee6134edef)
> 
> Pinning cmp at commit [5dcbc91](https://github.com/hrsh7th/nvim-cmp/commit/5dcbc91d9a0eed00f66b6cdc406f843c4253020f) can be used as workaround.

Thanks @silvercircle . can confirm the workaround it works for me.

**Comment by uga-rosa** [comment]
Reverted in 9b0bc5f9cdd5904aa94779f05ea61d6b173f3dcd.
