### ISSUE TITLE
Cycle through multiple pyright imports of the same name

### ISSUE THREAD

**Issue by robyoung** [hrsh7th/nvim-cmp#1553]
I am using Pyright with nvim-cmp through lunarvim. It is all working great in almost all situations. However, when using auto-import, when there are multiple possible import locations with the same name nvim-cmp will only show one.

For example; I would like to import the `patch` function from `unittest.mock.patch` while I also have the `ddtrace` package installed, which has `ddtrace.patch`. If I type `patch` and then hit tab the only auto-import option is for the one from `ddtrace`. How can I get access to the other import locations?

<img width="654" alt="Completion selection with only one patch option" src="https://user-images.githubusercontent.com/14287/235955578-9b3b282f-d399-49e8-a68c-590676dfba04.png">

**Comment by hrsh7th** [comment]
nvim-cmp shows duplicated identifier by default.

I can't think it's nvim-cmp's problem.

I guess your problem is language-server or lunarnvim or your configuration's problem.
