### ISSUE TITLE
cmp.matcher.match does not match sometimes even when `input` is a substring of `word`

### ISSUE THREAD

**Issue by d-r-a-b** [hrsh7th/nvim-cmp#1554]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Reproduces in the config hosted in the nvim-cmp repo at current main branch https://github.com/hrsh7th/nvim-cmp/blob/8d2f190506013064775ec328377e196ab343ad61/utils/vimrc.vim

### Description

Run the vim command:

`:= require('cmp.matcher').match('chronic','crd_chronic_h')`
 
shows the message:

```
0
{}
Press ENTER or type command to continue
```

### Steps to reproduce

Described above

### Expected behavior

If I am understanding the purpose of `cmp.matcher.match` correctly, I should get a non-zero score and match details

### Actual behavior

Zero score

### Additional context

Very dependent on the word being matched. For example, just removing one letter allows this to match

`= require('cmp.matcher').match('chronic','crd_chronic_')`

Shows the message

```lua
11.8
{ {
    fuzzy = false,
    index = 1,
    input_match_end = 1,
    input_match_start = 1,
    no_symbol_match = false,
    strict_ratio = 1,
    word_match_end = 1,
    word_match_start = 1
  }, {
    fuzzy = true,
    input_match_end = -1,
    input_match_start = 2,
    strict_ratio = 1,
    word_match_end = 11,
    word_match_start = 6
  } }
Press ENTER or type command to continue
```

~~Even though the above matches, I don't understand how `word_match_start` and `word_match_end` map to the match since `assert(#'chronic' == 7)` and `assert(#{6,7,8,9,10,11} == 6)`. A quick Ctrl-F of https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt doesn't find any "match_start" or "match_end", but if the values are as expected, just let me know and I'll dig through the source to figure it out when I have the time. If that is a different bug, let me know and I can file as a separate issue so that it's easier to close individual issues.~~
> EDIT: I figured it out. `matches` is conceptually a list of of tables, each table representing a contiguous portion of the `word` that matches a contiguous portion of `input`. So the first "match" shows where "c" matches and the second part shows where "hronic" matches

**Comment by d-r-a-b** [comment]
Some potential hints from playing with things inside a buffer.

`input` ch
`word` ch_chronic_h
matches on first and last letter
![image](https://user-images.githubusercontent.com/107967151/236224869-86173e53-cdcb-4a4a-a20b-797b0d1c1780.png)

`input` chr
`word` ch_chronic_h
searchs for "r"" after the last "h"? (obviously fails since word is empty after last "h")
![image](https://user-images.githubusercontent.com/107967151/236225043-9e4242e7-15dd-4ee0-a64c-b7c6e250b8bd.png)

**Comment by d-r-a-b** [comment]
Removing `_` underscore allows match to occur, suggesting this may have something to do with `char.get_next_semantic_index()`

![image](https://user-images.githubusercontent.com/107967151/236227415-cee4388a-a20d-4353-bbd2-0d92147060e7.png)

**Comment by bew** [comment]
Related: #1443 (especially https://github.com/hrsh7th/nvim-cmp/issues/1443#issuecomment-1445410688)

**Comment by hrsh7th** [comment]
The nvim-cmp implementation tries to provide practical completion results and better performance as much as possible.

I'm not sure how to achieve your expectations while balancing performance.

At least, I don't have the plans for this, but I will review PRs if you sent.

**Comment by d-r-a-b** [comment]
> I'm not sure how to achieve your expectations while balancing performance.
> At least, I don't have the plans for this, but I will review PRs if you sent.

Totally fair, the Matcher implementation you have works well for the use-case you are optimizing.

Thank you for making this project available - I am not a coder in any professional way, but *the code base is well-organized ❤️* and can be understood with some study and understanding that many concepts are based on LSP completion. I know it's a hobby project, thank you for also taking the time to maintain it.

Although `cmp.matcher` exposes several functions and variables publicly, the only one that gets consumed by anything else in the code is `cmp.matcher.match`. Instead of tweaking the existing `cmp.matcher`, would you be open to the idea of a PR that allows a new `cmp.matcher.external` module or `cmp.matcher.match` function to be passed?

**Comment by d-r-a-b** [comment]
- [ ] I think I understand what is needed for something like this, but I would also love confirmation/clarification on the following if you have the time:

##### Is my understanding accurate?
>    `cmp.matcher.match(input,word,opts)`  has the following return signature:
>    ```
>    score = number,
>    matches = { submatch1, submatch2, submatch3, . . . }
>    ```
>
> and each `submatch` should be a table of form:
> 
>    ```lua
>    { 
>        -- defines corresponding regions between input and match
>        input_match_end = number, 
>        input_match_start = number,
>        word_match_end = number,
>        word_match_start = number,
>
>       -- whether match is "fuzzy"
>       -- convenience attribute
>       -- consumed externally only for highlight groups?
>       fuzzy = (input_match_start == 0) && (word_match_start == 0),
>    }
>    ```
>
> `score` should be non-zero for a match of `cmp.matcher.match( "", word, {} )` or else trigger characters will break (like `./` for `cmp-path`

#### Are these necessary?
>    Parts of the submatch are accessible externally, but I don't think anything consumes them. Would external Matcher need these?
>    ```lua
>    {
>    -- only used internally by `cmp.matcher`?
>    -- `cmp.matcher.external` can skip implementation?
>    index = 1,
>    no_symbol_match = false,
>    strict_ratio = 1,
>    }
>    ```
> `cmp.matcher` also exposes a number of other functions and variables that only used seem to be used internally, would cmp.matcher.external need to implement these?
>  ```lua
>  
>  -- variables
>  matcher.WORD_BOUNDALY_ORDER_FACTOR = 10
>  matcher.PREFIX_FACTOR = 8
>  matcher.NOT_FUZZY_FACTOR = 6
>  -- functions
>  matcher.debug = function(...)
>  matcher.fuzzy = function(input, word, matches, option)
>  matcher.find_match_region = function(input, input_start_index, input_end_index, word, word_index)
>  ```

Thank you for any clarification on the above points.

**Comment by d-r-a-b** [comment]
**I also understand if you don't want this as a PR since people trying to create custom Matchers may create more headaches then solutions.** Sorry to be 1 of them 😅.

On the plus side, because your `nvim-cmp` is so well nicely modularized, it is possible *right now* to unofficially do this by creating a `cmp.matcher` in a different directory that gets added as higher priority in the `runtimepath`. So this may be an option for people who want a different matching strategy that's a bit less effort than forking the entire codebase.

If you don't want a PR and you can clarify the questions I asked above, this might be a good ticket to mention in other issues that want different Matching behavior -- it's open source and a user can implement their own matcher 😉 in an 🎉unsupported🎉 way.

If the PR solution is no good, anybody going forward with this `runtimepath` method would need to understand that this mechanism is

- [ ] unsupported
- [ ] fragile and will break if nvim-cmp ever refactors `cmp.matcher`
- [ ] 🎉unsupported🎉
