### ISSUE TITLE
Error of  : start_col out of bounds. Extra characters at the end of completions.

### ISSUE THREAD

**Issue by MostHated** [hrsh7th/nvim-cmp#1560]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Unfortunately, I cannot reliably reproduce this. It happens randomly, and I have to close and reopen nvim.

### Description

I am having the same issue as described in issue https://github.com/hrsh7th/nvim-cmp/issues/1097 but that one said to open a new issue.

Sometimes I will start to notice that completions will have extra characters at the end. Today was the first time that I recall seeing an actual error, which can be seen below.

Example:
I start to type something, and at the end of the completion, it should end with `");`  but it ends with `");");`. Yesterday, I noticed that it was doing this, but with a newline as well.

Ex.
Expected this:
```
let whatever = whatever("whatever");
```
Got this:
```
let whatever = whatever("whatever");
);
```
Below are my version numbers, as well as the actual error message that appeared this time, which prompted my searching and coming across the issue mentioned above.

Versions
```
NVIM v0.9.0-dev-554+g6f25623e7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

● nvim-cmp 0.7ms  lsp-zero.nvim
    dir    /home/mosthated/.local/share/nvim/lazy/nvim-cmp
    url    https://github.com/hrsh7th/nvim-cmp
    branch main
    commit 1cad30f
    readme README.md
    help   |nvim-cmp|
```

```
Error  04:58:19 PM msg_show.lua_error E5108: Error executing lua ...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:383: start_col out of bounds
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:383: in function <...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:371>
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function <...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:45>
```

### Steps to reproduce

Unfortunately, it is seemingly pretty random. I am not sure how to forcefully reproduce it. So far, I have only noticed it in Rust, but at the same time, I have only really been writing Rust the last few weeks.

### Expected behavior

No error or extra characters in completions 

### Actual behavior

Error and extra characters in completions

**Comment by hrsh7th** [comment]
I can't fix without repro steps...


Is this problem caused if you type multibyte character?

**Comment by MostHated** [comment]
I understand that. I am trying to contribute what I can by reporting an issue. I don't expect you to be able to fix it with that I have provided alone, but I also didn't want to simply ignore the fact that an error occurred.

I am honestly not 100% sure of what characters are multibyte. I know a good number of non-english characters are, but are typical symbols used in programming multibyte? Ex: `&`, or `!`, etc? 

I will try and pay attention the next time it occurs and will see try and come back with the exact characters I tried to type, and what the completion was.

**Comment by ActionScripted** [comment]
I'm not sure if this helps at all but for me it seems to happen when using Copilot (nvim-cmp, copilot-cmp, copilot.lua) and tab completion. When I use arrow keys things don't seem to break but if I use tab to cycle between options and then hit return I get `Invalid 'start_col': out of range`

But only sometimes. When I save/close the file and reopen and try the same completion oftentimes it works. I saw elsewhere something about async maybe being a cause, maybe that's what is going on.

Again sorry for not being more helpful but here's my lazy.vim config for `nvim-cmp`:

```lua
--[[
-- Auto-complete
--]]
return {
  {
    "hrsh7th/nvim-cmp",
    version = false, -- last release is way too old
    --event = "InsertEnter",
    dependencies = {
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-path",
      --"hrsh7th/cmp-cmdline",
      "saadparwaiz1/cmp_luasnip",
      "L3MON4D3/LuaSnip",
      {
        "zbirenbaum/copilot-cmp",
        dependencies = {
          {
            "zbirenbaum/copilot.lua",
            cmd = "Copilot",
            build = ":Copilot auth",
            opts = {
              suggestion = { enabled = false },
              panel = { enabled = false },
            },
          },
        },
        opts = {},
        config = function(_, opts)
          local copilot_cmp = require("copilot_cmp")
          copilot_cmp.setup(opts)
          -- attach cmp source whenever copilot attaches
          -- fixes lazy-loading issues with the copilot cmp source
          require("lazyvim.util").on_attach(function(client)
            if client.name == "copilot" then
              copilot_cmp._on_insert_enter()
            end
          end)
        end,
      },
    },
    opts = function()
      local cmp = require("cmp")
      return {
        completion = {
          completeopt = "menu,menuone,noinsert",
        },
        snippet = {
          expand = function(args)
            require("luasnip").lsp_expand(args.body)
          end,
        },
        mapping = cmp.mapping.preset.insert({
          ['<Tab>'] = function(fallback)
            if cmp.visible() then cmp.select_next_item() else fallback() end
          end,
          ['<S-Tab>'] = function(fallback)
            if cmp.visible() then cmp.select_prev_item() else fallback() end
          end,
          ["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
          ["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
          ["<C-b>"] = cmp.mapping.scroll_docs(-4),
          ["<C-f>"] = cmp.mapping.scroll_docs(4),
          ["<C-Space>"] = cmp.mapping.complete(),
          ["<C-e>"] = cmp.mapping.abort(),
          -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          ["<CR>"] = cmp.mapping.confirm({ 
            behavior = cmp.ConfirmBehavior.Replace,
            select = false
          }),
          -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          ["<S-CR>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          }),
        }),
        sources = cmp.config.sources({
          { name = "buffer" },
          { name = "copilot" },
          { name = "pylsp" },
          { name = "luasnip" },
          { name = "nvim_lsp" },
          { name = "path" },
          --{ name = "cmdline" },
        }),
        formatting = {
          format = function(_, item)
            local icons = require("lazyvim.config").icons.kinds
            if icons[item.kind] then
              item.kind = icons[item.kind] .. item.kind
            end
            return item
          end,
        },
        experimental = {
          ghost_text = {
            hl_group = "LspCodeLens",
          },
        },
      }
    end,
  },
}
```

It's mostly stolen from LazyVim with a few tweaks to toss it all into a single table because I'm testing stuff for a new setup and that's easier.

**Comment by MostHated** [comment]
I just had this occur, not the error, but the extra characters:

Below is where it occurred:

```rust
#[warn(dead_code)])]
pub enum MatcherKind {
  Include(Gitignore),
  Exclude(Gitignore),
}

```

With the code above, I had typed out this much:

```rust
#[warn(
```

The completion was supposed to be:
```rust
dead_code)]
```
but ended up being:

```rust
dead_code)])]
```

It was actually a copilot completion, similar to above, but I don't use tab for the completion. I use <C-CR> to insert it.

**Comment by arpanetus** [comment]
I'm experiencing the same issue right now.

**Comment by wuminzhe** [comment]
> I just had this occur, not the error, but the extra characters:
> 
> Below is where it occurred:
> 
> ```rust
> #[warn(dead_code)])]  // <-- End Result 
> pub enum MatcherKind {
>   Include(Gitignore),
>   Exclude(Gitignore),
> }
> ```
> 
> With the code above, I had typed out this much:
> 
> ```rust
> #[warn(
> ```
> 
> The completion was supposed to be:
> 
> ```rust
> dead_code)]
> ```
> 
> but ended up being:
> 
> ```rust
> dead_code)])]
> ```
> 
> It was actually a copilot completion, similar to above, but I don't use tab for the completion. I use `<C-CR>` to insert it.
> 
> I am not sure if the initial error is related to this, or this is two separate issues that happened to have occurred at the same time.

same issue

**Comment by sunyiynus** [comment]
Same Issue in my config

**Comment by m-wynn** [comment]
I was encountering this and similar errors.  I eventually went through and disabled all my other config and plugins, and eventually found https://github.com/hashivim/vim-terraform was causing the majority of my issues with terraform code, at least.

I chose to disable it rather than dig into it to find out what exactly was causing the issue.  But it may be worth searching for similar type plugins or settings in your config.

**Comment by kapral18** [comment]
![CleanShot 2023-12-23 at 21 00 01](https://github.com/hrsh7th/nvim-cmp/assets/1625373/cb4a7030-46e5-4c06-8320-f6cbe43fede6)

my lazyvim starter config: https://github.com/kapral18/config.nvim/blob/a75e0eb57f5748823d9143e3f4ce0b8c2c1b7222/lua/plugins/coding.lua

**Comment by minhanghuang** [comment]
![image](https://github.com/hrsh7th/nvim-cmp/assets/37317982/e4866101-4a26-4c00-ae54-48ef66298fd0)

experiencing the same issue right now

**Comment by 8veStory** [comment]
I've had the same issue on MacOS Sonoma using LazyVim.

It only happens for me when I hit `<return>` to confirm a [copilot.lua](https://github.com/zbirenbaum/copilot.lua)/[copilot-cmp](https://github.com/zbirenbaum/copilot-cmp) completion. The aforementioned error occurs about an 'Invalid start_col' and requires a restart for `nvim-cmp` to work again.

**Comment by kapral18** [comment]
I noticed that it happens with copilot as well for example when before hitting the completion you move your cursor in any direction.

**Comment by Rigidity** [comment]
I'm having the same problem. Also using Copilot + CMP:

 ![image](https://github.com/hrsh7th/nvim-cmp/assets/35380458/d27ffc18-ffb5-4810-9fa7-846bf927c8b3)

**Comment by xiopt** [comment]
Same problem here. copilot-cmp on mac Sonoma with lazyvim.

**Comment by 8veStory** [comment]
So far I've only seen comments/images that mention/show macOS; if this is the case, perhaps it's an OS specific issue?

**Comment by MostHated** [comment]
I am on Pop_OS (Ubuntu)

**Comment by akthe-at** [comment]
Same Here, on Windows, Not WSL...Using Nvim 9.5 in Windows Terminal/Git Bash.

**Comment by viktorholk** [comment]
I'm having the same issue

**Comment by NukaCody** [comment]
As a data point as I can't seem to reproduce consistently but:

This seems to occur randomly based on what copilot returns (using copilot.lua and not github/copilot.vim). Something about copilot generation and nvim-cmp don't get along. It's intermediary because there are times I can accept a change and other times the error is thrown. Oddly enough I'm also writing rust as the original author and other's pointed out in this thread.

**Comment by pixelprogrammer** [comment]
> So far I've only seen comments/images that mention/show macOS; if this is the case, perhaps it's an OS specific issue?

Just confirming that this is not an OS specific issue. I am on Fedora and have had this issue both on Gnome and Sway.

I also don't believe this is language specific either and is happening on Typescript, Go and maybe some Rust projects (haven't tested that one in a bit)

I am unable to get a consistent error but it does appear to be happening a lot. Using the LazyVim setup and this happens when I try to autocomplete a Github Copilot suggestion sometimes. Usually the first few times work well but then it starts to error out after that.

**Comment by JosefLitos** [comment]
I have the same issue in markdown with cmp-path not updating when quickly writing something with a slash and then going to new line and pressing tab to increase my indent. It keeps showing the same completion on the new line until I've written something on it and it often shows this error in this sequence of actions. The main issue seems to be the menu not updating when changing to a different line.

**Comment by pixelprogrammer** [comment]
> I noticed that it happens with copilot as well for example when completion menu open and before hitting the completion item you move your cursor in any direction.

I think this is the main issue. I have a tendency to hit return twice to give some space. So the cursor ends up one line below and when I do the copilot autocomplete, it errors. This has been consistent on many different languages and can now confirm it happens in Go, Rust, Typescript, PHP, etc.

**Comment by hrsh7th** [comment]
If the same issue occurs with cmp-path, it may be a core issue.

I don't use copilot, but I've never encountered this problem.

**Comment by Ddystopia** [comment]
Hello, I do use copilot and encounter this error quite often.

**Comment by JosefLitos** [comment]
I just managed to reproduce this behaviour intentionally:
![obrazek](https://github.com/hrsh7th/nvim-cmp/assets/54900518/b3e625d4-3c83-41f9-955f-30c41977ebad)

I use this function that causes this for me:
```lua
local function enter_or_list()
	local line =
		vim.api.nvim_buf_get_lines(0, vim.fn.line '.' - 1, -1, false)[1]:match '^%s*%d*[%d%-—.)]+.?'
	if not line then
		return '\r'
	else
		local start, finish = line:find '[%d%-.)]*%d'
		local main
		if not start or not finish then
			start, finish = line:find '[%-.%)]+.?'
			return '\r' .. line:sub(start, finish)
		else
			main = line:sub(start, finish)
			local suffix = line:sub(finish + 1)
			return table.concat {
				'\r',
				main,
				vim.api.nvim_replace_termcodes('<Esc><C-a>a', true, true, true),
				suffix,
			}
		end
	end
end

vim.keymap.set('i', '<Enter>', enter_or_list, { buffer = true, expr = true })
```
I believe this happens, because this function prints text like the user would, but slightly differently, which causes cmp to keep the menu up, but doesn't update it, because from its point of view the user hasn't made any changes.

1. use `cmp-path`
2. start editing a file, write ` /`, the completion should trigger
3. hide the menu (`<Esc>` or something), but do not leave insert mode
4. `<CR>` (as to go to a new line) - the old completion should pop up
5. using `<Left>`, navigate to the previous line and `<BS>` the `' '`
6. now with `<Right>` navigate back to the next line
7. complete the completion (`<Tab>` or whatever your binding is)

during all of 4.+, the completion menu should stay open showing the same completion, by deleting the space, we change the end of the line to before the original position, but the completion doesn't get updated, so tries to complete to an invalid position

**Comment by modk** [comment]
This might be a multi-faceted problem but for me it mainly occurs when entering insert mode (e.g. by pressing 'O' to insert a line above the current one).  It looks like in such a case completion works on an outdated buffer (i.e. the one before switching to insert mode) causing the column information to be out of sync.  If I switch back to normal mode and re-enter insert mode manually completion works just fine.  For the time being the follow hack that does this automatically works for me:
```
diff --git a/lua/cmp/core.lua b/lua/cmp/core.lua
index b34c360..2267543 100644
--- a/lua/cmp/core.lua
+++ b/lua/cmp/core.lua
@@ -370,6 +370,10 @@ core.confirm = function(self, e, option, callback)
   self.view:close()
 
   feedkeys.call(keymap.indentkeys(), 'n')
+  -- Exit and re-enter insert mode just in case.  This ensures that the buffer
+  -- is not out of date.
+  local keys = vim.api.nvim_replace_termcodes('<C-c>i', false, false, true)
+  vim.api.nvim_feedkeys(keys, 'n', {})
   feedkeys.call('', 'n', function()
     -- Emulate `<C-y>` behavior to save `.` register.
     local ctx = context.new()
@@ -391,7 +395,7 @@ core.confirm = function(self, e, option, callback)
       vim.cmd([[silent! undojoin]])
       -- This logic must be used nvim_buf_set_text.
       -- If not used, the snippet engine's placeholder wil be broken.
-      vim.api.nvim_buf_set_text(0, e.context.cursor.row - 1, e:get_offset() - 1, ctx.cursor.row - 1, ctx.cursor.col - 1, {
+      vim.api.nvim_buf_set_text(0, e.context.cursor.row - 1, e:get_offset() - 1, ctx.cursor.row - 1, ctx.cursor.col, {
         e.context.cursor_before_line:sub(e:get_offset()),
       })
       vim.api.nvim_win_set_cursor(0, { e.context.cursor.row, e.context.cursor.col - 1 })
```
 That's not a proper solution but I don't know enough about nvim's API or nvim-cmp to come up with something proper.

**Comment by norpadon** [comment]
I have the same issue with copilot when using <S-CR> as a binding.

**Comment by tris203** [comment]
As a fairly reproducible example for me, create a file with the following Go code

```go
package main

type Test struct {
	Name string `json:"name,omitempty"`
	Age  int    `json:"age"`
}
```
Go to `Age` field, and delete the backtick, there will be a suggestion to add the `omitempty` to the json definition. 

Cmp will crash, and some wierdness goes on where the code is collapsed into one line

**Comment by tris203** [comment]
PR that fixes this issue above if anyone can test it

**Comment by modk** [comment]
Didn't solve the issue for me:
```
[..].local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:394: Invalid 'start_col': out of range
```

**Comment by tris203** [comment]
> Didn't solve the issue for me:
> 
> ```
> [..].local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:394: Invalid 'start_col': out of range
> ```

But it didn't crash cmp entirely right? So you could continue to complete without closing and re-opening nvim?

In order to track this down, I would need more detail around the completion and the context
Thanks
