### ISSUE TITLE
Cmp reset the selected item when source runs callback

### ISSUE THREAD

**Issue by flametuner** [hrsh7th/nvim-cmp#1561]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

I'm using AstroNvim v3.15.2 with [this configuration](https://github.com/flametuner/astronvim-config).

### Description

When you have any item selected in the cmp (via TAB for example) and there is any update with the sources via `callback`, the current selected item is reset and you need to select it again.

This is specially annoying with sources that make requests to the internet. I'm currently using [copilot.lua](https://github.com/zbirenbaum/copilot.lua) with the plugin [copilot-cmp.lua](https://github.com/zbirenbaum/copilot-cmp) to load the results to cmp.

The problem is that sometimes I just want to use the LSP's suggestion and while I'm selecting, the callback from copilot runs and it resets the selected item making me confused on why I selected a word and got a new line.

This isn't a problem only with copilot but is much more visible with it. If you have a slow LSP and you are selecting any snippet, for example, the same thing can happen.

### Steps to reproduce

Start typing in a buffer with attached LSP and Copilot Cmp.

- Try selecting a suggestion using TAB or CTRL+N before Copilot loads the suggestion.
- When the copilot suggestion is loaded, the current selected item is reset.

### Expected behavior

When the callback from a source is received, the current selected item should remain the same.

### Actual behavior

When a callback from a source is received, the current selected item is reset.

**Comment by hrsh7th** [comment]
I recentry fix this problem.
Could you check with latest main?
