### ISSUE TITLE
Ghost text broken with recent update

### ISSUE THREAD

**Issue by ribru17** [hrsh7th/nvim-cmp#1565]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [x] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),

  experimental = {
    ghost_text = true
  }
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF


```

### Description

When typing and receiving autocomplete suggestions with ghost text enabled, no ghost text is shown and an error is produced on the first line of the buffer saying:
```
cmp:GHOST_TEXT: Error executing lua: ...hare/nvim/lazy/nvim-cmp/lua/cmp/view/ghost_text_view.lua:40: attempt to index local 'c' ...
```
When reverting to 1cad30fcffa282c0a9199c524c821eadc24bf939 this issue is not present.

### Steps to reproduce

Open any file and begin typing any text that will cause nvim-cmp to show autocomplete suggestions

### Expected behavior

Ghost text will appear for whichever suggestion you are currently selecting

### Actual behavior

No ghost text is shown and an error is shown on the first visible line of the buffer

### Additional context

This is a very recent breakage

**Comment by rebelot** [comment]
```lua
                                            *cmp-config.experimental.ghost_text*
experimental.ghost_text 
  `boolean | { hl_group = string }`
  Whether to enable the ghost_text feature.
```

I've set it to `{ hl_group = "NonText" }`. Highlight is properly set, but it seems that this new option format caused a regression.

**Comment by Yanis-F** [comment]
The bug is here:
`c` is the value of the config
https://github.com/hrsh7th/nvim-cmp/blob/935b4069ce73b60ba9075bf05ee6ab50ed3af1a9/lua/cmp/view/ghost_text_view.lua#L21
so it can be either a boolean or a table `{ hl_group = string }` (as the doc says)  
but L40, it is assumed to be a table
https://github.com/hrsh7th/nvim-cmp/blob/935b4069ce73b60ba9075bf05ee6ab50ed3af1a9/lua/cmp/view/ghost_text_view.lua#L40
