### ISSUE TITLE
When a new item is added to the menu, the cursor disapears?

### ISSUE THREAD

**Issue by asyncedd** [hrsh7th/nvim-cmp#1568]
So, let's say I have a slow source. But, I already see the item I want to select.
So, I select it and, the source registers the item and boom, the menu updates and my cursor is no longer there.

Is it possible to make the cursor still in the current position when the menu updates?

Thanks!

**Comment by hrsh7th** [comment]
If user already select the item, nvim-cmp does not refresh the menu.

**Comment by asyncedd** [comment]
I meant, when the user selects an items and, a new item is added (because a slow source) the menu refreshes?

Maybe I'm wrong?
