### ISSUE TITLE
How to remove space auto complete activation

### ISSUE THREAD

**Issue by Caixetadev** [hrsh7th/nvim-cmp#1572]
I have an annoying bug with tailwindcss, when I try to type a new class in className, it gives me an auto suggestion of unrelated things and ends up breaking my auto complete. For example, when I enter insert mode and press space to write the class, it gives me this unrelated suggestion:
![soace](https://github.com/hrsh7th/nvim-cmp/assets/87894998/eda22963-26c5-460a-9108-715efc1f2042)

and when I try to type the class I actually want, it doesn't capture the first character: (ignore buffer and luasnip)
![bug](https://github.com/hrsh7th/nvim-cmp/assets/87894998/c0429a77-5510-4e92-8979-cacae5b28b13)

here if i type j twice it actually give me the suggestion i want
![second](https://github.com/hrsh7th/nvim-cmp/assets/87894998/3ad7a2e9-eb0d-4704-acd3-c77b8d29dbbd)

I believe that if I find a way to remove the space from triggering the auto complete, it will work normally.

**Comment by zaqxsw-dev** [comment]
Show your nvim config. @Caixetadev

**Comment by Caixetadev** [comment]
> Show your nvim config. @Caixetadev

my config [nvim](https://github.com/Caixetadev/nvim)
