### ISSUE TITLE
Documentation window does not have the same appearance as `vim.lsp.buf.hover`

### ISSUE THREAD

**Issue by pedrobarco** [hrsh7th/nvim-cmp#1578]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
-- import lsp-zero plugin safely
local lsp_status, lsp = pcall(require, "lsp-zero")
if not lsp_status then
	return
end

-- import cmp plugin safely
local cmp_status, cmp = pcall(require, "cmp")
if not cmp_status then
	return
end

-- import neodev plugin safely
local neodev_status, neodev = pcall(require, "neodev")
if not neodev_status then
	return
end

neodev.setup()

lsp.preset({
	name = "minimal",
})
lsp.setup()

cmp.setup({
	sources = {
		{ name = "path" },
		{ name = "nvim_lsp" },
		{ name = "nvim_lua" },
		{ name = "luasnip", keyword_length = 2 },
		{ name = "buffer", keyword_length = 3 },
	},
	window = {
		documentation = cmp.config.window.bordered(),
	},
})

```

### Description

I don't know why the documentation window appearance differs from `lspconfig`'s `vim.lsp.buf.hover`. FIY https://github.com/VonHeikemen/lsp-zero.nvim/issues/255

### Steps to reproduce

Use the config provided above and try to autocomplete the following with `fmt.Scanf`.

```go
package main

import "fmt"

func main() {
  fmt.S
}
```

### Expected behavior

The documentation window should look like the one being rendered by `vim.lsp.buf.hover`.

### Actual behavior

 Some colors are off, symbols and even the markdown rendering is not working as expected.

**Comment by hrsh7th** [comment]
The nvim-cmp have window appearance settings.
See `:help cmp-config.view`
