### ISSUE TITLE
Documentation window option border not working

### ISSUE THREAD

**Issue by Kindlewing** [hrsh7th/nvim-cmp#1589]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

I configured both the window completion and documentation to have a custom border that I've defined. The  completion border works great, but the documentation is  still a black box with no border. The style is below, and the cmp configuration (using lazy,nvim) is below that:

Style

```lua
local style = {}

style.border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' }

return style

```
Cmp configuration
```lua
return {
	'hrsh7th/nvim-cmp',
	version = false, -- last release is way too old
	event = 'InsertEnter',
	dependencies = {
		'hrsh7th/cmp-nvim-lsp',
		'hrsh7th/cmp-buffer',
		'hrsh7th/cmp-path',
		'saadparwaiz1/cmp_luasnip',
		'hrsh7th/cmp-calc',
		'hrsh7th/cmp-emoji',
		'f3fora/cmp-spell',
		'kdheepak/cmp-latex-symbols',
		'jmbuhr/cmp-pandoc-references',
	},
	opts = function(_, opts)
		local cmp = require('cmp')
		local lspkind = require('lspkind')
		opts.sources = cmp.config.sources(vim.list_extend(opts.sources, {
			{ name = 'otter' },
			{ name = 'pandoc_references' },
			{ name = 'latex-symbols' },
			{ name = 'nvim_lsp_signature_help' },
			{ name = 'spell' },
			{ name = 'treesitter', keyword_length = 5, max_item_count = 3 },
			{ name = 'calc' },
			{ name = 'emoji' },
		}))
		-- stylua: ignore
		opts.window = {
		    completion = {
		        border = require('config.style').border
		    },
			documentation = {
		        border = require('config.style').border
			}
		}
		opts.formatting = {
			format = lspkind.cmp_format(),
		}
	end,
}

```

### Description

I configured both the window completion and documentation to have a custom border that I've defined. The  completion border works great, but the documentation is  still a black box with no border.

### Steps to reproduce

I've included all the relevant details.

### Expected behavior

I've included all the relevant details.

### Actual behavior

I've included all the relevant details.

**Comment by calvinchoy** [comment]
@Kindlewing , did you find a solution for this bug?
