### ISSUE TITLE
<CR> Inserts a newline when I don't want it to

### ISSUE THREAD

**Issue by jamesnicolas** [hrsh7th/nvim-cmp#1591]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"

local has_words_before = function()
  unpack = unpack or table.unpack
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end
cmp.setup {
mapping = {
    ['<Tab>'] = function(fallback)
      if not cmp.select_next_item() then
        if vim.bo.buftype ~= 'prompt' and has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end
    end,

    ['<S-Tab>'] = function(fallback)
      if not cmp.select_prev_item() then
        if vim.bo.buftype ~= 'prompt' and has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end
    end,
  },

     ["<CR>"] = cmp.mapping({
       i = function(fallback)
         if cmp.visible() and cmp.get_active_entry() then
           cmp.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = false })
         else
           fallback()
         end
       end,
       s = cmp.mapping.confirm({ select = true }),
       c = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true }),
    }),

  -- You should specify your *installed* sources.
  sources = {
    { name = 'buffer' },
    { name = 'nvim_lsp' },
    { name = 'ultisnips' },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

### Description

I was reading the wiki and found "Super-Tab" like mapping, and another header that said "Safely select entries with \<CR\>"

I copied that config into mine, expecting to be able to use <CR> to confirm a selection that I made with tab. It does confirm the selection, but it also adds a newline. I don't want it to add a newline.

### Steps to reproduce

Copy the base minimal config to the ~/cmp-repro.vim
Edit ~/cmp-repro.vim for reproducing the issue
Open nvim -u ~/cmp-repro.vim
Type some text out
```
asdf1
asdf2
asdf3
asdf4
```
Go to a newline, type `a`, and press tab until you select asdf3.
Press <CR> to confirm you want it to autocomplete to asdf3.

### Expected behavior

When I press <CR>, it should just confirm the entry without creating a newline.

### Actual behavior

It confirms the entry, but adds an extra newline that I don't want.

### Additional context

I've also tried setting `cmp.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true })` but it didn't seem to do anything either.

 I came here from coc.nvim and coq.nvim. I was able to get the desired behaviour to work in coq.nvim, but I stopped using coq.nvim because it uses python in the background, and my company laptop makes python really slow to start for some reason.

Here is a video of reproducing it.

https://github.com/hrsh7th/nvim-cmp/assets/2841145/c5e0c082-5b08-4914-910d-2164bcb14d49

**Comment by hrsh7th** [comment]
The `CR` mapping seems to be placed outside the `mapping = { ... }` section.
