### ISSUE TITLE
Tailwindcss completion not working

### ISSUE THREAD

**Issue by leonasdev** [hrsh7th/nvim-cmp#1598]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
require'lspconfig'.tailwindcss.setup {
  capabilities = capabilities,
}
EOF

```

### Description

![image](https://github.com/hrsh7th/nvim-cmp/assets/39915562/ccd1f3a3-3e76-4008-8292-e2b71e586571)

Tailwindcss completion not working after this commit: https://github.com/hrsh7th/nvim-cmp/commit/5547295bd048553ed4cd8f8503aa9782696c6a0e, and then fixed by: https://github.com/hrsh7th/nvim-cmp/commit/9b0bc5f9cdd5904aa94779f05ea61d6b173f3dcd which revert previous commit, and then it broke again by this commit: https://github.com/hrsh7th/nvim-cmp/commit/8b76965ed05016a3596b1d4d685c7b5caf1062a5 which added back the first commit I mentioned

### Steps to reproduce

1. `npm install -g @tailwindcss/language-server`
2. Setup any project that using tailwindcss (e.g. https://github.com/leonasdev/interactive-rating-component)
3. `nvim -u ~/cmp-repro.vim src/components/Thanks.tsx`
4. In any `className` attribute type `bg-` or `text-`
5. No color related completion shows

### Expected behavior

Type `bg-` or `text-` in tailwindcss project should showing correct completions.

### Actual behavior

Type `bg-` or `text-` in tailwindcss project not showing correct completions.

**Comment by hrsh7th** [comment]
fixed in https://github.com/hrsh7th/nvim-cmp/commit/3874e09e80f5fd97ae941442f1dc433317298ae9
