### ISSUE TITLE
when there is a single autocomplete candidate in the list, it doesnt get highlighted when selected

### ISSUE THREAD

**Issue by edg-l** [hrsh7th/nvim-cmp#160]

**Comment by edg-l** [comment]
![image](https://user-images.githubusercontent.com/15859336/132198739-26261f22-fe09-4804-a504-ad29607aab4c.png)
idk if this image helps understand the issue

**Comment by edg-l** [comment]
i think this has been fixed too

**Comment by edg-l** [comment]
it still happens, sorry

**Comment by hrsh7th** [comment]
@edg-l It is not relate to a nvim-cmp...

You can set `set completeopt=menu,menuone,noselect`
