### ISSUE TITLE
When the value of document field is Elixir code block, the autocomplete window will not be highlighted.

### ISSUE THREAD

**Issue by scottming** [hrsh7th/nvim-cmp#1600]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

You do not need to care about this; if you need this, I can provide this latter.

### Description

I am the developer of [lexical](https://github.com/lexical-lsp/lexical) (the next-generation Elixir language server). I found that when implementing `document` field of completion, the display effect in vscode is excellent, but there is no highlighting in cmp. I suspect this is because cmp does not highlight the Document results returned by `textDocument/completion`, only highlights the Document results returned by `completionItem/resolve`. I made this judgment based on comparing the request results of Lua and Lexical.

If my guess is correct, then this is a bug in cmp. According to LSP, we only need to provide` completionItem/resolve` method when calculating document and detail has a high cost. However, I believe providing these two fields for some completions in Elixir does not have a high cost. Therefore, we can directly provide them in `textDocument/completion` results.

### Steps to reproduce

<img width="816" alt="image" src="https://github.com/hrsh7th/nvim-cmp/assets/12830256/e3ca5f77-1dea-4c99-a03a-1519b9b7308b">

```lua
[DEBUG][2023-05-29 10:12:34] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  id = 93,
  jsonrpc = "2.0",
  method = "completionItem/resolve",
  params = {
    data = {
      id = 105,
      uri = "file:///Users/scottming/.config/nvim/lua/Lazy.lua"
    },
    insertText = "cmd",
    insertTextFormat = 2,
    kind = 3,
    label = "cmd(command)",
    sortText = "0021"
  }
}
[DEBUG][2023-05-29 10:12:34] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  id = 93,
  jsonrpc = "2.0",
  result = {
    data = {
      id = 105,
      uri = "file:///Users/scottming/.config/nvim/lua/Lazy.lua"
    },
    detail = "function|table",
    documentation = {
      kind = "markdown",
      value = "```lua\n(global) vim.cmd: function|table\n```\n\n---\n\n Execute Vim script commands.\n\n Note that `vim.cmd` can be indexed with a command name to return a callable function to the\n command.\n\n Example:\n <pre>lua\n   vim.cmd('echo 42')\n   vim.cmd([[\n     augroup My_group\n       autocmd!\n       autocmd FileType c setlocal cindent\n     augroup END\n   ]])\n\n   -- Ex command :echo \"foo\"\n   -- Note string literals need to be double quoted.\n   vim.cmd('echo \"foo\"')\n   vim.cmd { cmd = 'echo', args = { '\"foo\"' } }\n   vim.cmd.echo({ args = { '\"foo\"' } })\n   vim.cmd.echo('\"foo\"')\n\n   -- Ex command :write! myfile.txt\n   vim.cmd('write! myfile.txt')\n   vim.cmd { cmd = 'write', args = { \"myfile.txt\" }, bang = true }\n   vim.cmd.write { args = { \"myfile.txt\" }, bang = true }\n   vim.cmd.write { \"myfile.txt\", bang = true }\n\n   -- Ex command :colorscheme blue\n   vim.cmd('colorscheme blue')\n   vim.cmd.colorscheme('blue')\n </pre>\n\n@*param* `command` — Command(s) to execute.\n\n                            If a string, executes multiple lines of Vim script at once. In this\n                            case, it is an alias to |nvim_exec2()|, where `opts.output` is set\n                            to false. Thus it works identical to |:source|.\n                            If a table, executes a single command. In this case, it is an alias\n                            to |nvim_cmd()| where `opts` is empty.\n luacheck: no unused\n\n---\n\n```lua\nfunction vim.cmd(command: string|table)\n```"
    },
    insertText = "cmd",
    insertTextFormat = 2,
    kind = 3,
    label = "cmd(command)",
    sortText = "0021"
  }
}
```

<img width="419" alt="image 2" src="https://github.com/hrsh7th/nvim-cmp/assets/12830256/76ef4e70-2f1a-42fc-a0cc-0c5153582942">

```
[DEBUG][2023-05-29 10:15:39] .../vim/lsp/rpc.lua:284	"rpc.send"	{
  id = 6,
  jsonrpc = "2.0",
  method = "textDocument/completion",
  params = {
    context = {
      triggerKind = 1
    },
    position = {
      character = 4,
      line = 26
    },
    textDocument = {
      uri = "file:///Users/scottming/Code/dummy/lib/dummy.ex"
    }
  }
}
[DEBUG][2023-05-29 10:15:39] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  id = 6,
  jsonrpc = "2.0",
  result = { {
      detail = "Project.Structs.User",
      documentation = {
        kind = "markdown",
        value = "\n```elixir\nt() :: %User{\n  a: String.t(),\n  b: term() \\\\ false\n}\n```\n"
      },
      insertTextFormat = 2,
      kind = 22,
      label = "User",
      textEdit = {
        newText = "User{$1}",
        range = {
          ["end"] = {
            character = 4,
            line = 26
          },
          start = {
            character = 3,
            line = 26
          }
        }
      }
    }, {
      detail = "URI",
      documentation = {
        kind = "markdown",
        value = "\n```elixir\nt() :: %URI{\n  authority: authority(),\n  fragment: nil | binary(),\n  host: nil | binary(),\n  path: nil | binary(),\n  port: nil | :inet.port_number(),\n  query: nil | binary(),\n  scheme: nil | binary(),\n  userinfo: nil | binary()\n}\n```\n"
      },
      insertTextFormat = 2,
      kind = 22,
      label = "URI",
      textEdit = {
        newText = "URI{$1}",
        range = {
          ["end"] = {
            character = 4,
            line = 26
          },
          start = {
            character = 3,
            line = 26
          }
        }
      }
    } }
}
```

### Expected behavior

<img width="649" alt="image" src="https://github.com/hrsh7th/nvim-cmp/assets/12830256/80610984-247a-4770-ba6f-d115ac312442">

### Actual behavior

<img width="419" alt="image 2" src="https://github.com/hrsh7th/nvim-cmp/assets/12830256/76ef4e70-2f1a-42fc-a0cc-0c5153582942">

**Comment by hrsh7th** [comment]
In my environment, this behavior doesn't seem to depend on whether the item came from 'resolve'.

I can't understand why this detail/documentation doesn't highlighted... I'll investigate it.

**Comment by hrsh7th** [comment]
OK. I understand the problem.

1. the nvim-cmp's documentation window uses `vim's syntax highlight` instead of `treesitter highlight`.
2. In my environment, the normal buffer is highlighted because my environment has treesitter and elixir parser.

The `filetype=elixir` buffer seems to not highlighted via `vim's syntax highlight`.

**Comment by scottming** [comment]
Thank you very much for your prompt response. I am not familiar with the highlighting of vim syntax, but is there a way to use treesitter's highlighting for Elixir code blocks in the documentation window?

**Comment by hrsh7th** [comment]
Sorry I'm not familiar with this area.
Sorry, I'm not an expert in this area.
I believe folke was experimenting with this implementation in noise.nvim.

@folke Can you give me some advice?

**Comment by folke** [comment]
Noice can override the functions used in Neovim to highlight lsp docs.

If you're using lazy.nvim, add this to enable:

```lua
{
  "folke/noice.nvim",
  event = "VeryLazy",
  opts = {
    lsp = {
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
        ["cmp.entry.get_documentation"] = true,
      },
    },
  },
}
```

**Comment by scottming** [comment]
I love these highlighting.

![image](https://github.com/hrsh7th/nvim-cmp/assets/12830256/d9c7ad28-d103-41b7-904c-ca1daea85b66)

Thank you both so much. You created stunning plugins and systems.

**Comment by hrsh7th** [comment]
I'm hoping that the feature would be included into the nvim-kit (and then nvim-cmp).
I'll investigate if I have free time.
