### ISSUE TITLE
pum position wrong when the window is not tall enough for a wrapped line

### ISSUE THREAD

**Issue by tomtomjhj** [hrsh7th/nvim-cmp#1605]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

repro.vim
```vim
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  sources = cmp.config.sources({
    { name = "buffer" },
  }),
}
EOF

```

### Description

The popup menu appears at a wrong position when the cursor is on a wrapped line and the window is not tall enough to show the entire line.

### Steps to reproduce

1. Run nvim with the config
```
nvim -u repro.vim
```

2. Run the following command to setup the windows and text. Note that the height of the window at the bottom is 1. which is not tall enough to display the wrapped line containing the text.
```vim
new
wincmd j
exe "normal! z1\<CR>"
call setline(1, 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet')
startinsert!
```

3. Start editing the text, and check the position of popup menu.

### Expected behavior

The popup should be near the cursor.

### Actual behavior

nvim 0.10 (nightly) and 0.9: The popup appears at the top left of nvim.
![image](https://github.com/hrsh7th/nvim-cmp/assets/19489738/1c5448eb-0421-4967-9ffc-ec1dbb07e819)

nvim 0.7 and 0.8: the popup overlaps the cursor.
![image](https://github.com/hrsh7th/nvim-cmp/assets/19489738/6ed2905e-f70d-483c-9713-a034b601ffcb)

**Comment by hrsh7th** [comment]
what is your pumheight?

`:echomsg &pumheight`.

You should set pumheight value.

**Comment by hrsh7th** [comment]
this is depending on to the `set nowrap` or not... I can't understand this.

**Comment by tomtomjhj** [comment]
`screenpos()` seems to be buggy. `screenpos(0, line('.'), col('.'))` returns `{'col': 0, 'row': 0, 'endcol': 0, 'curscol': 0}`. It should return something like this `{'col': 119, 'row': 38, 'endcol': 119, 'curscol': 119}`.

screenpos may return the dict with all zero, but only when the position is not visible:
> If the specified position is not visible, all values are zero.

I'll file an issue on vim

**Comment by tomtomjhj** [comment]
Fixed by https://github.com/neovim/neovim/commit/49ede0a68f1f8fd46dc9715fb1f332a13d13dbe3
