### ISSUE TITLE
`ignored_filetypes` similar to `nvim-compe`?

### ISSUE THREAD

**Issue by yujinyuz** [hrsh7th/nvim-cmp#161]
I find the per buffer setup inconvenient since I would have to create an `after/ftplugin/<language>.lua` for each.

Is `ignored_filetypes` supported in `nvim-cmp` or would it be supported in the future?

Thanks!

**Comment by hrsh7th** [comment]
nvim-cmp hasno this option.

In nvim-cmp, You should specify sources per each filetype.

**Comment by yujinyuz** [comment]
thanks. i guess i just have to create config for each filetype

**Comment by hrsh7th** [comment]
Yes.
It would be a little easier if neovim provided `vim.api.nvim_set_autocmd`.
