### ISSUE TITLE
Help Mapping

### ISSUE THREAD

**Issue by CantoroMC** [hrsh7th/nvim-cmp#162]
Whenever I try to configure any key in the keymap table and use it; I am prompted with these errors (probably I am doing something wrong)

`E5108: Error executing lua [string "v:lua"]:1: attempt to index field 'utils' (a nil value)

**Comment by hrsh7th** [comment]
please your config

**Comment by CantoroMC** [comment]
https://pastebin.com/ycCghJqL

Now the mappings, when I introduce the simpler suggested in the readme, the errors popups.

**Comment by hrsh7th** [comment]
You should add `local` to the `cmp = require'cmp'`.

`local cmp = require'cmp'`

**Comment by CantoroMC** [comment]
Thanks, sorry for bothering you for such a stupid thing.

**Comment by alexzanderr** [comment]
> Thanks, sorry for bothering you for such a stupid thing.

dont worry, its not stupid, i just encountered this, and i was like: how comes mapping is nil when its not empty.
