### ISSUE TITLE
Feature request: Allow preselect to select the first item

### ISSUE THREAD

**Issue by mortezadadgar** [hrsh7th/nvim-cmp#1621]
cmp.PreselectMode.None leaves completion menu completely unselected what I want is to preselect the first from menu something like cmp.PreselectMode.FirstItem

**Comment by Shougo** [comment]
I don't understand.   Why you don't use `cmp.PreselectMode.FirstItem`?

**Comment by hrsh7th** [comment]
@Shougo nvim-cmp does not have `cmp.PreselectMode.FirstItem`... this is a feature request.

**Comment by Shougo** [comment]
Ah, OK.  I thought it is already implemented...

**Comment by cshuaimin** [comment]
Removing noselect from cmp's completeopt is the correct config to always select first item. see `:h cmp-config.completion.completeopt`
```lua
completion = {
  completeopt = "menu,menuone,noinsert", -- remove default noselect
}
```

**Comment by mortezadadgar** [comment]
@cshuaimin doesn't seem to work for me alongside disabling preselect

**Comment by cshuaimin** [comment]
@mortezadadgar weird, I can confirm that removing noselect works regardless of whether preselect is set to None or Item. I tested on lua_ls, tsserver and rust-analyzer.

**Comment by mortezadadgar** [comment]
@cshuaimin my fault I was changing completeopt option in a wrong way now only the first item is selected but i had to set preselect to None, perhaps lsp severs you mentioned doesn't support preselect.
This issue can be closed now.
