### ISSUE TITLE
cmp.ConfirmBehavior.Insert should not replace text to the right

### ISSUE THREAD

**Issue by marcelbeumer** [hrsh7th/nvim-cmp#1623]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.gopls.setup {
  capabilities = capabilities,
}
EOF
```

Base `cmp-repro`, only replaced css lsp with gopls.

### Description

When completing an item while having text on the right, that text (word boundary it seems) is always replaced, also with `ConfirmBehavior.Insert`. 

### Steps to reproduce

Create `main.go`:

```
package main

import (
	"errors"
	"fmt"
)

func main() {
	err := errors.New("err")
	fmt.Println(err.Error())
}
```

- Put cursor here:

```
fmt.Println(err.Error())`
^-------
````

- press `i`
- type `errors`
- press enter (`<CR>`)
- `fmt` is replaced with `errors`

### Expected behavior

I expected `errors` to be inserted and `fmt` to be still there, like `errorsfmt.`

### Actual behavior

`fmt` is replaced with `errors`.

Also when I configure `cmp-repro` with `    ['<CR>'] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Insert })`, the behavior is still the same.

When I first add a space (so there is a one space on the right side of the cursor in insert mode) it works ok, but it's cumbersome to add that space every time.

### Additional context

If this is a feature, not a bug, how to efficiently go into insert mode and add code without having to add a space first?

**Comment by mgnsk** [comment]
I think this behaviour has existed for a long time. I'm currently using the `cmp.ConfirmBehavior.Insert` mapping which I hoped would solve this (before that I used `cmp.ConfirmBehaviour.Replace`):
```lua
["<CR>"] = cmp.mapping.confirm({
	behavior = cmp.ConfirmBehavior.Insert,
	select = false,
}),
```

**Comment by sentiens-docebo** [comment]
Same problem

**Comment by sentiens** [comment]
The same problem, it looks like "cmp.ConfirmBehavior.Insert" doesn't have any effect.

**Comment by hrsh7th** [comment]
duplicated https://github.com/hrsh7th/nvim-cmp/issues/611
