### ISSUE TITLE
How to show lspkind icon before completion text?

### ISSUE THREAD

**Issue by famiu** [hrsh7th/nvim-cmp#163]
I liked the default behavior of nvim-compe where the lspkind was shown before the actual item itself, now the icon is put after the item which I'm not a fan of. Is there a way to put it before the completion item text like nvim-compe?

On another note, I'd also like to use Neovim's CompletionItemKind instead of a plugin like lspkind for the icons. nvim-compe was able to do that, nvim-cmp can't for some reason.

**Comment by hrsh7th** [comment]
You csn modify the completion item by `formatting.format`.

See `:help complete-item`
