### ISSUE TITLE
C# autocompleted generic method not inserting symbols

### ISSUE THREAD

**Issue by SchnozzleCat** [hrsh7th/nvim-cmp#1634]
Currently when completing a generic C# method autocomplete will not insert the generic symbols to specify the type argument, instead immediately skipping to the method arguments.
This means autocompleting a generic method requires deleting the opening and closing brackets, adding the generic symbols, and then adding the method parameters.
Example:
![image](https://github.com/hrsh7th/nvim-cmp/assets/67333469/85346be1-cdec-4d51-b770-81e45dbb6e19)
Becomes:
![image](https://github.com/hrsh7th/nvim-cmp/assets/67333469/52fde98d-0453-470a-bb78-3045f596cf80)
When it should be:
![image](https://github.com/hrsh7th/nvim-cmp/assets/67333469/1840b40c-b333-4ea9-b164-75eec85f7583)

This would make autocompleting generic methods much faster.

**Comment by hrsh7th** [comment]
It should be implemented in the omnisharp side.

**Comment by hrsh7th** [comment]
If you can confirm the `VSCode is supported this feature`, feel free to re-open this.
