### ISSUE TITLE
Pylyzer doesn't work

### ISSUE THREAD

**Issue by TornaxO7** [hrsh7th/nvim-cmp#1635]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.pylyzer.setup {
  capabilities = capabilities,
}
EOF
```

### Description

I don't get any auto-completion in the python file.

### Steps to reproduce

1. Copy the minimal config above to `/tmp/vimrc`
2. Execute `nvim -u /tmp/vimrc /tmp/test.py`
3. Now start typing `from random import randint`. No autocompletion window pops up.

### Expected behavior

The autocompletion window pops up.

### Actual behavior

The autocompletion window doesn't pop up.

### Additional context

Replacing
```lua
require'lspconfig'.pylyzer.setup {
  capabilities = capabilities,
}
```
with
```lua
require'lspconfig'.pyright.setup {
  capabilities = capabilities,
}
```
works. `pyright` gives me autocompletion.

**Comment by hrsh7th** [comment]
Your repro step does not contain pylyzer install step.

**Comment by TornaxO7** [comment]
I switched to helix :)
