### ISSUE TITLE
Colored popup suggestions

### ISSUE THREAD

**Issue by kilpkonn** [hrsh7th/nvim-cmp#164]
I'd say it would look great if we could colorize suggestions popup. 
For example functions could be in one color and variable in other.

It'd be also great if it wouldn't be limited to one color per line and could be customized further with highlight groups etc.

If it's already doable with highlight groups, I'd appreciate minimal example, as I couldn't get it working.

Otherwise maybe something light this could be used: https://github.com/p00f/nvim-ts-rainbow/blob/aa27d56bc53a82f501cd89cd797969f5e2211c61/lua/rainbow/internal.lua#L61

**Comment by Shougo** [comment]
The builtin completion windows does not support the highlight.
You should request it to the upstream instead.

https://github.com/hrsh7th/nvim-cmp/issues/141

**Comment by Shougo** [comment]
> Otherwise maybe something light this could be used: p00f/nvim-ts-rainbow@aa27d56/lua/rainbow/internal.lua#L61

It is buffer colouring instead of completion window.

**Comment by gegoune** [comment]
Number of requests related to this only show ageing of completion window. Perhaps someone could make a good case with core developers. Maybe it's possible to improve situation keeping compatibility with vim.

**Comment by kilpkonn** [comment]
Thank you for the fast reply! I guess I'll make feature request to nvim then
