### ISSUE TITLE
no parser for 'cmp_menu' language

### ISSUE THREAD

**Issue by aghriss** [hrsh7th/nvim-cmp#1648]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

No config file used.

### Description

I'm setting up Neovim using NvChad. When opening a new python file after enabling syntax highlighting for python, I get the error
```
indent-blankline: /usr/share/nvim/runtime/lua/vim/treesitter
/language.lua:94: no parser for 'cmp_menu' language, see :help treesitter-parsers
```
as soon as I start typing

### Steps to reproduce

- Install neovim on Gentoo
-  Install NvChad without any default settings
-  Enable Python syntax highlighting with nvim-treesitter
- Open new python file

### Expected behavior

No errors

### Actual behavior

Error
```
indent-blankline: /usr/share/nvim/runtime/lua/vim/treesitter
/language.lua:94: no parser for 'cmp_menu' language, see :help treesitter-parsers
```

### Additional context

The error goes away when I comment the line
```
  self.entries_win:buffer_option('filetype', 'cmp_menu')
 ``` 
in `lua/cmp/view/custom_entries_view.lua`

**Comment by Shougo** [comment]
Well, this is really nvim-cmp's issue?

**Comment by SarathLUN** [comment]
Yes, i go similar error.
"no parser for 'cmp_menu' language".

**Comment by gegoune** [comment]
Seems like nvchad is misconfigured, most likely nothing to do with cmp itself.

**Comment by aghriss** [comment]
Error due to indent-blankline.nvim , see https://github.com/lukas-reineke/indent-blankline.nvim/issues/591
