### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by HUAHUAI23** [hrsh7th/nvim-cmp#1649]
When using nvim --headless and connecting with neovide, the highlighting of the cmp plugin is problematic, has anyone encountered this? 
<img width="892" alt="image" src="https://github.com/hrsh7th/nvim-cmp/assets/43649186/337058c9-332c-4718-8001-d871034d105c">

**Comment by williamhCode** [comment]
I am working on a neovim gui and have encountered the same problem. https://github.com/neovim/neovim/issues/28120#issue-2216743114

**Comment by zeertzjq** [comment]
This happens because 'termguicolors' is not set when nvim-cmp calls `synIDattr()`. It can be solved by setting 'termguicolors' before loading nvim-cmp.

**Comment by zeertzjq** [comment]
> This happens because 'termguicolors' is not set when nvim-cmp calls `synIDattr()`. It can be solved by setting 'termguicolors' before loading nvim-cmp.

Oops, I tested this incorrectly. This doesn't work.

**Comment by zeertzjq** [comment]
The following change to nvim-cmp should fix this problem:
```diff
diff --git a/plugin/cmp.lua b/plugin/cmp.lua
index 0e5e691..611b5c9 100644
--- a/plugin/cmp.lua
+++ b/plugin/cmp.lua
@@ -25,7 +25,7 @@ for kind in pairs(types.lsp.CompletionItemKind) do
   end
 end
 
-autocmd.subscribe('ColorScheme', function()
+autocmd.subscribe({ 'ColorScheme', 'UIEnter' }, function()
   highlight.inherit('CmpItemAbbrDefault', 'Pmenu', { bg = 'NONE', default = false })
   highlight.inherit('CmpItemAbbrDeprecatedDefault', 'Comment', { bg = 'NONE', default = false })
   highlight.inherit('CmpItemAbbrMatchDefault', 'Pmenu', { bg = 'NONE', default = false })
```

**Comment by hrsh7th** [comment]
It was difficult to arrive at this on my own...
Thank you very much!
