### ISSUE TITLE
attempt to index local 'c'

### ISSUE THREAD

**Issue by gegoune** [hrsh7th/nvim-cmp#165]
Started getting

```
Error executing vim.schedule lua callback: Vim(lua):E5108: Error executing lua ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:62: attempt to index local 'c' (a boolean value)
Error detected while processing CompleteChanged Autocommands for "*":
E5108: Error executing lua ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:62: attempt to index local 'c' (a boolean value)
```

when typing anything and when completion menu pops up (have automatic completion set up).

Fixable by disabling 

```lua
experimental.ghost_text = true
```

and started appearing after https://github.com/hrsh7th/nvim-cmp/commit/b6b15d5f6e46643462b5e62269e7babdab17331c got merged.

**Comment by gegoune** [comment]
Setting `hl_group` as per #166 fixes the issue.

**Comment by hrsh7th** [comment]
I've fixed it.

**Comment by rohit-kumar-j** [comment]
@hrsh7th, currently the tested commit (origin/main) [`935b406`](https://github.com/hrsh7th/nvim-cmp/commit/935b4069ce73b60ba9075bf05ee6ab50ed3af1a9) errors like this:
```bash
cmp:GHOST_TEXT: Error executing lua: .../nvim-data/lazy/nvim-cmp/lua/cmp/view/ghost_text_view.lua:40: attempt to index local 'c' (a boolean value)
```
Switching back to 'v0.0.1' fixes this.
