### ISSUE TITLE
[Question] Completition window popup following the cursor

### ISSUE THREAD

**Issue by leandrocunha** [hrsh7th/nvim-cmp#1660]
It's possible to make the competition window popup, following the cursor while type?

**Comment by Shougo** [comment]
You should upload the example.

**Comment by lvimuser** [comment]
For reference
https://github.com/lvimuser/nvim-cmp/commit/d9a0678897f7c9f342e288c9d3304a7cd7afe6c1

**Comment by Shougo** [comment]
Can you upload the screenshot?
And why the feature is useful?

**Comment by lvimuser** [comment]
https://github.com/hrsh7th/nvim-cmp/assets/109605931/78f122ff-8c4b-4367-8818-fd4788081d8a

Not sure if useful? It looks a bit nicer, imo.

**Comment by ertucode** [comment]
Why isnt this just added as an option? It is literally -3 lines of code.

**Comment by Shougo** [comment]
You can make the PR for it.

**Comment by mcauley-penney** [comment]
Created a PR which adds this as an option, set to `false` by default. I want this feature.

**Comment by leandrocunha** [comment]
> Created a PR (with @lvimuser as coauthor, thank you for the critical piece of source) which adds this as an option for the custom entries view, set to `false` by default. I want this feature.

thank you guys
