### ISSUE TITLE
How do I setup nvim-cmp?

### ISSUE THREAD

**Issue by notprash** [hrsh7th/nvim-cmp#169]
I just got to know that nvim-compe is deprecated. So how do I setup nvim-cmp. I want to scroll through the completions with tab. When I tried reading the docs, I couldn't understand much. I would be nice if you paste the basic nvim-cmp config for autocomplete.

**Comment by hrsh7th** [comment]
minimsl vimrc is here.
https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim
