### ISSUE TITLE
Feature request: Option to match against item descriptions

### ISSUE THREAD

**Issue by micangl** [hrsh7th/nvim-cmp#1703]
Currently, it's only possible to fuzzy match against the completion keywords, and an option to allow matching against item descriptions doesn't exist (what I'm referring to, with the word description, are the entries in the pink rectangle).
![2023-09-16T00:39:10,317768269+02:00](https://github.com/hrsh7th/nvim-cmp/assets/142919381/381f6c11-aee2-485f-b3d3-da51ab4a3170)
This may be useful, for example, when completing Latex `\cite{` statements.

**Comment by bew** [comment]
Why did you close this ? :thinking:

**Comment by micangl** [comment]
@bew I've discovered that matching is controlled by the `filterText` argument of the CompletionItem, which has to be set directly by the source. If you want, I can reopen the issue.
