### ISSUE TITLE
Icons on completion menu

### ISSUE THREAD

**Issue by arpangreat** [hrsh7th/nvim-cmp#173]
Is there any way to get custom Icons on completion menu ?

**Comment by hrsh7th** [comment]
Please read the README.md
https://github.com/hrsh7th/nvim-cmp#how-to-show-name-of-item-kind-and-source-like-compe

**Comment by arpangreat** [comment]
Thanks :)

**Comment by melkster** [comment]
Looks like the documentation has been removed. Is it `formatting.format` that I have to use now instead?
