### ISSUE TITLE
`open_docs` not working

### ISSUE THREAD

**Issue by Myzel394** [hrsh7th/nvim-cmp#1745]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Copy the example from the text:

```lua
  cmp.setup {
    ...
    mapping = {
      ['<C-g>'] = function()
        if cmp.visible_docs() then
          cmp.close_docs()
        else
          cmp.open_docs()
        end
      end
    }
    ...
  }
```

(`<C-g>` seems to be captured by my terminal, I used `<C-f>` instead)

Doesn't work :/

### Description

No popup shown at all

### Steps to reproduce

1. Write something that has docs
2. Go to normal mode
3. Go to insert mode
4. Enter <C-g> - no popup shown

### Expected behavior

A popup should be shown

### Actual behavior

No popup shown

**Comment by qxb3** [comment]
Are there any updates on this?

**Comment by Old-Farmer** [comment]
Similar problem  for me. <C-g> don't toggle docs when cmp menu is not visible.

**Comment by pavelz** [comment]
i will try to fix this I would really want to have this so I don't have to interweb for docs.

**Comment by igords-goncalves** [comment]
Same problem here, I set up my mappings but it doesn't work!

` ['C-Space'] = cmp.mapping.open_docs(), `

I found this resource in https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt

**Comment by qxb3** [comment]
For now i just use the neovim's lsp built-in function:
```lua
vim.lsp.buf.hover()
```

**Comment by hrsh7th** [comment]
The `cmp.open_docs` is used to `change documentation window visibility`.

I'm worried that this issue misunderstands the `cmp.open_docs` purpose.

https://github.com/hrsh7th/nvim-cmp/assets/629908/efd23db0-57be-49ab-a677-6901f1d18041
