### ISSUE TITLE
Documentation max width sometimes doesn't follow `window.documentation.max_width`

### ISSUE THREAD

**Issue by mbrc12** [hrsh7th/nvim-cmp#1763]
Please see the following screenshot of using `rust_analyzer` with `nvim-cmp`.

![image](https://github.com/hrsh7th/nvim-cmp/assets/4688429/9c4e9269-d206-4da8-bccf-6d77ac8095ab)

The command whose output is shown is `lua =require("cmp.config").get().window`

![image](https://github.com/hrsh7th/nvim-cmp/assets/4688429/dc0cef2e-7a93-4ed3-82a6-648959835aff)

Seems like the `max_width` is indeed set properly, but the docs window is so big.  

Many thanks for your help! Please let me know if this is a duplicate of any other issue or if I'm making a stupid mistake (likely).

Best,
mbrc12

**Comment by Shougo** [comment]
Related issues: https://github.com/hrsh7th/nvim-cmp/issues/1154 https://github.com/hrsh7th/nvim-cmp/issues/1673

**Comment by mbrc12** [comment]
@Shougo these appear to be for the completion menu, and not the documentation window, if I am not mistaken? Thanks for pointing out that it is likely a rust specific issue.

**Comment by Shougo** [comment]
It is about completion menu with documentation window issue.  So I think it is similar.

**Comment by mbrc12** [comment]
Closing, it was a mistake in configuration on my part. Seems to work perfectly.
