### ISSUE TITLE
[Help] how to scroll up in second popup menue

### ISSUE THREAD

**Issue by Pger-Y** [hrsh7th/nvim-cmp#1771]
Sorry to bother,I'm new to neovim and don't know how to scroll down or up in file preview menue or golang doc menue
tried the ctr-d and ctr-j but no response
neovim 0.9.4 and nvim-cmp commit is 11102d3
![image](https://github.com/hrsh7th/nvim-cmp/assets/4125972/e752c3a3-9532-4ae3-aee2-4349a588df91)
![image](https://github.com/hrsh7th/nvim-cmp/assets/4125972/fc0efde7-3d16-458f-b43f-4b1afc17e775)

**Comment by wookayin** [comment]
README:

```
     ['<C-b>'] = cmp.mapping.scroll_docs(-4),
     ['<C-f>'] = cmp.mapping.scroll_docs(4),
```

isn't this what you're looking for? what does your config look like?

**Comment by wookayin** [comment]
Also questions should go to https://github.com/hrsh7th/nvim-cmp/discussions.
