### ISSUE TITLE
How to change the cmp source 

### ISSUE THREAD

**Issue by Sologala** [hrsh7th/nvim-cmp#1789]
I wang to alias Property source type to  Prop. 
Where I should config to achive it. 
![image](https://github.com/hrsh7th/nvim-cmp/assets/46283762/8c7799fc-b384-4759-a92f-2e2a1fcd5631)

Things already tried:
I found the following configuration in other's dotfile. But `source_names` segments not work.
```lua
source_names = {
                    nvim_lsp = "(LSP)",
                    treesitter = "(TS)",
                },
```

**Comment by wahyuwiyoko** [comment]
@Sologala that is called a kind items, not a sources. You can customize the kind items name with text or icon in `formatting` options like these example:

```lua
local kind_items = {
  Text = "Text",
  Method = "Method",
  Function = "Func",
  Constructor = "Constructor",
  Field = "Field",
  Variable = "Var",
  Class = "Class",
  Interface = "Interface",
  Module = "Module",
  Property = "Prop",
  Unit = "Unit",
  Value = "Val",
  Enum = "Enum",
  Keyword = "Keyword",
  Snippet = "Snippet",
  Color = "Color",
  File = "File",
  Reference = "Ref",
  Folder = "Folder",
  EnumMember = "EnumMember",
  Constant = "Const",
  Struct = "Struct",
  Event = "Event",
  Operator = "Operator",
  TypeParameter = "TypeParameter"
}

require("cmp").setup({
  formatting = {
    format = function (entry, vim_item)
      -- Kind items
      vim_item.kind = string.format("%s", kind_items[vim_item.kind])

      -- Source
      vim_item.menu = ({
        nvim_lsp = "[LSP]",
        luasnip = "[LuaSnip]",
        buffer = "[Buffer]"
      })[entry.source.name]

      return vim_item
    end
  }
})
```

Take a look the detail in [Menu Appearance wiki](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#basic-customisations).

And I think what `source_names` option you provide it should be `sources` for the completion item like these example I have completion for LSP, LuaSnip, and buffer:

```lua
sources = {
  { name = "nvim_lsp" },
  { name = "luasnip", option = { show_autosnippets = true } },
  { name = "buffer" }
}
```

For all list of sources name, look in [List of sources wiki](https://github.com/hrsh7th/nvim-cmp/wiki/List-of-sources).

**Comment by Sologala** [comment]
THX, I got it work like i wish by your instrcutions.
