### ISSUE TITLE
Improve documentation for mapping

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#181]
There are a lot of mapping-related issues.
To be honest, I'm tired.

I had received a lot of issues where another plugin overwrites the `<CR>` mapping in nvim-compe.
So I decided to provide an automatic mapping fallback mechanism.

But the users still seem to feel it is difficult.

**Comment by gegoune** [comment]
Sorry to hear you feel that way! Your hard work is very appreciated!

Do you think like `<CR>` implementation is lacking something or is it just a matter of documenting stuff?

**Comment by hrsh7th** [comment]
I think we should add the example mapping to the wiki.

If it is not enough, I have to implement this feature.

**Comment by JoseConseco** [comment]
for people interested in tab config with Ultisnips : tab goes not next suggested item, or jump to next tabstop.  Ctrl+space to accept selected item, or expand snippet:

```lua
local t = function(str)
	return vim.api.nvim_replace_termcodes(str, true, true, true)
end   
``` 
then inside: require('cmp').setup{..}  : 
```lua
	mapping = {
		['<C-p>'] = cmp.mapping.select_prev_item(),
		['<C-n>'] = cmp.mapping.select_next_item(),
		['<S-Tab>'] = cmp.mapping(function(fallback)
			if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpBackwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-p>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<S-tab>"), "n")
			else
				vim.fn.feedkeys(t("<S-tab>"), "n")
			end
		end, { "i", "s"}),
		['<Tab>'] = cmp.mapping(function(fallback)
			if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<esc>:call UltiSnips#JumpForwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-n>"), "n")
			else
				vim.fn.feedkeys(t("<tab>"), "n")
			end
		end, { "i", "s"}),
		['<C-d>'] = cmp.mapping.scroll_docs(-4),
		['<C-f>'] = cmp.mapping.scroll_docs(4),
		['<C-e>'] = cmp.mapping.close(),
		['<CR>'] = cmp.mapping.confirm({ -- remapped at bottom by autopairs
			behavior = cmp.ConfirmBehavior.Replace,
			select = false,
		}),
		['<C-Space>'] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				if vim.fn.complete_info()["selected"] ~= -1 then
					if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
						return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
					else
						vim.fn.feedkeys(t("<cr>"), "n")
                                        end
				else
					vim.fn.feedkeys(t("<C-e>"), "n")
				end

			else
				fallback()
			end
		end, { "i", "s", }),
	},

```
```lua
require("nvim-autopairs.completion.cmp").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true, -- it will auto insert `(` after select function or method item
  auto_select = false -- automatically select the first item
})  
```

I think it would be cool if other people  shared theirs working configs.

**Comment by hrsh7th** [comment]
I'm writing the wiki
https://github.com/hrsh7th/nvim-cmp/wiki/Example-mapping

**Comment by Iron-E** [comment]
When I was creating my own keybindings, the only confusing part was that `cmp.mapping.foo()` returned another function, rather than performed the action I desired. Once I figured this out, I was able to get everything working in short order.

I added my supertab config to the wiki too, as it doesn't require a snippet plugin. It has the API snippet expansion code from #102, but all the bugs fixed (🤞 ).

**Comment by akinsho** [comment]
@vinoff you are missing the third argument to `vim.api.nvim_feedkeys` it should be `true` this is also in the updated README

**Comment by hrsh7th** [comment]
Yes. current wiki page is broken. Sorry TT

**Comment by vinoff** [comment]
Ok, this works for luasnip:

```
local has_words_before = function()
  local cursor = vim.api.nvim_win_get_cursor(0)
  return (vim.api.nvim_buf_get_lines(0, cursor[1] - 1, cursor[1], true)[1] or ''):sub(cursor[2], cursor[2]):match('%s') 
end

local luasnip = require("luasnip")
local cmp = require('cmp')
cmp.setup {

    snippet = {
        expand = function(args)
            require("luasnip").lsp_expand(args.body)
        end,
    },

  mapping = {

    ['<Tab>'] = cmp.mapping(function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '', true)
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { 'i', 's' }),

    ['<S-Tab>'] = cmp.mapping(function()
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(t('<C-p>'), 'n', true)
      elseif luasnip.jumpable(-1) == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '', true)
      end
    end, { 'i', 's' }),

  },

  sources = {
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "path" },
  },

}

```

However, I don't see snippets. This could be an issue with luasnip though. Does luasnip bring its own snippets or do I need to get snippets from somewhere else? (slightly offtopic, sorry)

**Comment by akinsho** [comment]
You need to get your own snippets @vinoff, it doesn't ship with any, try https://github.com/rafamadriz/friendly-snippets

**Comment by hrsh7th** [comment]
I'm udpated the wiki page. Please try it and if you found the improvements, feel free to modify it! 👍🏼

**Comment by vinoff** [comment]
I am having this error sometimes, any idea what it might be?:

```
Error detected while processing TextChangedI Autocommands for "*":
E5108: Error executing lua ...user/.vim/plugged/cmp_luasnip/lua/cmp_luasnip/init.lua:47: attempt to index a boolean value
Press ENTER or type command to continue
```

**Comment by hrsh7th** [comment]
I don't know because I have no your config.

**Comment by hrsh7th** [comment]
You might not install luasnip itself. https://github.com/saadparwaiz1/cmp_luasnip/blob/master/lua/cmp_luasnip/init.lua#L47

**Comment by vinoff** [comment]
It is the one I pasted above:
```

local has_words_before = function()
  local cursor = vim.api.nvim_win_get_cursor(0)
  return (vim.api.nvim_buf_get_lines(0, cursor[1] - 1, cursor[1], true)[1] or ''):sub(cursor[2], cursor[2]):match('%s') 
end

local luasnip = require("luasnip")
local cmp = require('cmp')
cmp.setup {

    snippet = {
        expand = function(args)
            require("luasnip").lsp_expand(args.body)
        end,
    },

  mapping = {

    ['<Tab>'] = cmp.mapping(function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '', true)
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { 'i', 's' }),

    ['<S-Tab>'] = cmp.mapping(function()
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(t('<C-p>'), 'n', true)
      elseif luasnip.jumpable(-1) == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '', true)
      end
    end, { 'i', 's' }),

  },

  sources = {
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "path" },
  },
}

```



> You might not install luasnip itself. https://github.com/saadparwaiz1/cmp_luasnip/blob/master/lua/cmp_luasnip/init.lua#L47

No, I have luasnip installed (and also friendlysnippets). However, I still see no snippets in the dropdown so it is probably an issue with luasnip and not really cmp.. 

This is so confusing to me, hours and hours trying to make this work. If anyone has managed to have snippets + cmp + tab-like-supertab working, please share your dotfiles. I am tired for now, will take a few hours off.

Sorry @hrsh7th, it is not you, it is me.

**Comment by hrsh7th** [comment]
Hm... If you are using packer, you might need to re-run `PackerCompile`, I guess.

**Comment by vinoff** [comment]
Ok, I have managed to fix the error, managed to see the snippets in the dropdown. However, tab does not trigger the snippet. All it does it browse to the next item in the dropdown menu. It does not open/trigger/expand the snippet:

```
local has_words_before = function()
  local cursor = vim.api.nvim_win_get_cursor(0)
  return not vim.api.nvim_get_current_line():sub(1, cursor[2]):match('^%s$')
end

local luasnip = require('luasnip')
local cmp = require('cmp')
cmp.setup {

    snippet = {
        expand = function(args)
            require("luasnip").lsp_expand(args.body)
        end,
    },

  mapping = {

    ['<Tab>'] = cmp.mapping(function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { 'i', 's' }),

    ['<S-Tab>'] = cmp.mapping(function()
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n', true)
      elseif luasnip.jumpable(-1) then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '', true)
      end
    end, { 'i', 's' }),

  },

  sources = {
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "path" },
  },
}
```

Does it work for you? At this point I no longer know if this has to do with nvim-cmp, or luasnip or cmp_luasnip or one of the other 30 plugins I have to use.

**Comment by hrsh7th** [comment]
Your configuration says if the completion-menu is visible, the `<Tab>` only works as `next item`.

```
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
```

If `vim.fn.pumvisible() == 1`, the `<Tab>` always feeds `<C-n>`. It is expected behavior.
You can customize it by yourself.

**Comment by vinoff** [comment]
Oohh. Alright.

I suggest editing the Wiki though, as Supertab would expand.

**Comment by hrsh7th** [comment]
If you get it to work, feel free to modify it! 👍🏼

**Comment by vinoff** [comment]
> If you get it to work, feel free to modify it! 👍🏼

Will do! I had it working in compe, but I don't remember how with all the changes I have made since then.. Should have saved the config =(.

**Comment by Iron-E** [comment]
@vinoff FYI that `has_words_before` implementation has some edge cases which doesn't work, you should grab the one from the README or the Wiki (which is now updated to reflect the README).

**Comment by vinoff** [comment]
Hey @Iron-E, thanks for tagging! 

Ya, my issue is that I want Nvim to behave like Sublime-Text, the editor from which I come. I like using Tab for both completion, expanding snippets and jumping around placeholders in snippets. I might have to give your workaround a try, but over the years I've tried different keymaps but never got used to anything else. Let's see.

In the Wiki, you have

**Comment by Iron-E** [comment]
> Snippets don't expand __with <Tab> in this config. Use <C-Space>.__

They do expand, just not with `<Tab>`. While you have an item selected press `<C-Space>` and it will expand. All you need is the `<C-Space> = function(…` part, the rest can stay your config.

**Comment by adrian5** [comment]
> I'm writing the wiki
> https://github.com/hrsh7th/nvim-cmp/wiki/Example-mapping

I think this a good approach, crowd knowledge about robust configs can accumulate over time. Don't overburden yourself with work, and thanks for creating this plugin!

**Comment by uga-rosa** [comment]
LuaSnip is written in lua, so `<Plug>luasnip-hogehoge` calls a lua function.
https://github.com/L3MON4D3/LuaSnip/blob/master/plugin/luasnip.vim
You don't need `feedkeys()` for jump.

```
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),

    ['<S-Tab>'] = cmp.mapping(function()
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n', true)
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      end
    end, { 'i', 's' })
  },
```

I haven't used the supertab like mapping, so there may be a few mistakes.

**Comment by adrian5** [comment]
Unless I'm missing something, that's indeed another improvement to be added. `luasnip` is already in scope anyway.

**Comment by uga-rosa** [comment]
Since it is based on a wiki, I assumed the following.

```lua
local luasnip = require('luasnip')
```

**Comment by uga-rosa** [comment]
The original mapping worked, but I thought it was wasteful and not beautiful, so I posted it.

**Comment by uga-rosa** [comment]
There is one more thing I am curious about. With this conditional branch, I can't jump in the following situation.

bar (`|`) is cursor position.
A snippet of sumneko-lua, `function ()`
```lua
function |()

end
```

I don't think `has_words_before()` is necessary. You may want to do the following.

```lua
    ['<Tab>'] = cmp.mapping(function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),
```

**Comment by Iron-E** [comment]
That would make sense. `has_words_before` only returns `true` if there is a non-space character before the cursor. In that example, there is a space character before the cursor.

You may want to make an additional `if` branch with `cmp.complete` if you want to re-trigger completion for a word you already dismissed completion on:

```lua
['<Tab>'] = cmp.mapping(function(fallback) 
  if vim.fn.pumvisible() == 1 then 
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true) 
  elseif luasnip.expand_or_jumpable() then
    luasnip.expand_or_jump()
  elseif has_words_before() then
    cmp.complete() 
  else 
    fallback() 
  end 
end, { 'i', 's' }),
```

**Comment by babygau** [comment]
@Iron-E and @uga-rosa, but if you do this, `Telescope` <Tab> is broken, the old implementation would work just fine
https://github.com/hrsh7th/nvim-cmp/issues/181#issuecomment-917361024

**Comment by Iron-E** [comment]
I don't use telescope so I'm inferring what you mean here— are you referring to #174? That seems compatible with this because we are using `fallback`

**Comment by babygau** [comment]
@Iron-E, it's the same issue. As I mentioned before, https://github.com/hrsh7th/nvim-cmp/issues/181#issuecomment-917361024 worked great with `Telescope`. The latest wiki update by @uga-rosa break it.

**Comment by Iron-E** [comment]
Thanks for letting us know. Could you try removing `if` arms to see which one has the issue? i.e. `elseif has_word_before` and `elseif luasnip.expand_or_jumpable`.

@uga-rosa do you think #60 would help? I don't know if disabling autocomplete also reverts `<Tab>` mapping. If so maybe this should go in the FAQ, I saw a few issues about Telescope and nvim-cmp. Mentioning how to disable it up front will probably be helpful.

**Comment by babygau** [comment]
@Iron-E `cmp` is working fine for me, no suggestion pop-up in Telescope prompt

**Comment by uga-rosa** [comment]
I just tried it, and it works fine.
I've updated the wiki a few times, will it still break with the current wiki settings?

**Comment by babygau** [comment]
@uga-rosa this
```lua
elseif has_words_before() then
        cmp.complete()
```
break `Telescope` <Tab>. I can reproduce problem with `find_files`, `live_grep` .... Just type a few characters to product results, then you cannot use Tab anymore

**Comment by uga-rosa** [comment]
Ah, I understand, `cmp.complete()` is called within `TelescopePrompt?`
I think this will fix it.
```lua
elseif has_words_before() and require("cmp.utils.check").ok() then
  cmp.complete()
```

**Comment by uga-rosa** [comment]
However, this may not be recommended.
https://github.com/hrsh7th/nvim-cmp/pull/70#issuecomment-905462159

**Comment by babygau** [comment]
@uga-rosa I just tested and it worked as you mentioned. If this is the case, I think you can just extract that function out, just like we have `has-words-before`, so we don't have to expose `cmp.utils.*`

**Comment by uga-rosa** [comment]
Added buftype detection to `has_words_before`. Check wiki.

**Comment by babygau** [comment]
@uga-rosa that's it! thank you 👍🏻

**Comment by vinoff** [comment]
How do I add an "if" statement, before all the others, that would trigger/expand a snippet, if a snippet is available (using luasnip)? Something like this:

```
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      **if SNIPPET_AVAILABLE then
        extend_snippet**
      elseif vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      elseif has_words_before() and luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),

```

**Comment by adrian5** [comment]
While you're all here: what is the logic behind the `has_words_before()` function?

```lua
-- snip
  elseif luasnip.expand_or_jumpable() then
    luasnip.expand_or_jump()
  elseif has_words_before() then
    cmp.complete()
  else
    fallback()
  end
```

I know how it works, but I don't understand what utility it and `cmp.complete()` serve within the tab function. Thanks!

**Comment by hrsh7th** [comment]
I'm definitely confusing. Your pasted code already checks `luasnip.expand_or_jumpable`...

**Comment by hrsh7th** [comment]
It is just basic `if statement`. So you should change it by yourself if you want to change.

```
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif vim.fn.pumvisible() == 1 then
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n', true)
      else
        fallback()
      end
    end, { 'i', 's' }),
```

**Comment by Iron-E** [comment]
@adrian5 I explained that just above (see https://github.com/hrsh7th/nvim-cmp/issues/181#issuecomment-917480461).

---

@hrsh7th I agree, it's a little confusing. Can anyone confirm whether the code in the wiki already expands snippets (@uga-rosa sorry for double tag)?

**Comment by hrsh7th** [comment]
I think wiki code is correct. This is personsl preference.
We can't put and maintein and organize all of possible mapping variation.

**Comment by Iron-E** [comment]
Understood. Don't use Luasnip so I couldn't be sure if it was a bug or order of operation problem.

Thanks for confirming!

**Comment by uga-rosa** [comment]
I have confirmed that it works as expected before editing wiki.
However, since hrsh7th has implemented `enabled` option, we can separate the `buftype` check.

**Comment by vinoff** [comment]
> @adrian5 I explained that just above (see [#181 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/181#issuecomment-917480461)).
> 
> @hrsh7th I agree, it's confusing. ~Can anyone confirm whether the code in the wiki already expands snippets (@uga-rosa sorry for double tag / @babygau)?~
> 
> Edit: confirmed, see below

It doesn't expand snippets, at least not the one titled "Luasnip".

**Comment by adrian5** [comment]
> @adrian5 I explained that just above (see [#181 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/181#issuecomment-917480461)).

Ah sorry, I must have missed the second paragraph. So the feature (gates and) opens the completion menu again, when one has (1) escaped,  (2) returns to insert mode and (3) presses `Tab` again. I think I never use that sequence, so never noticed. All clear now!

**Comment by vinoff** [comment]
Changing the order of the if's fixes the issue for me, that is:

```
    ["<Tab>"] = cmp.mapping(function(fallback)
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif vim.fn.pumvisible() == 1 then
        feedkey("<C-n>")
```

with everything else remaining the same. Now this is proper super-tab like, just like sublime-text is. It rubs me the wrong way claiming that what is in the wiki is supertab when it is not.

**Comment by hrsh7th** [comment]
But If we check `luasnip.expand_of_jumpable` first, it will cause unexpected expansion via `<Tab>` navigation, I think.

So I don't like to check `luasnip.expand_or_jumpable` first. (I'm not using `<Tab>` navigation. So I don't have strong opinion here).

Feel free to change the wiki.

**Comment by akinsho** [comment]
It's definitely a matter of preference but I don't think changing the order should be default example but maybe included as a comment that someone else might choose to use. I think a lot of the super tab examples in vim are based on https://github.com/ervandew/supertab rather than sublime and I *think* (it's been years since I used it) that tab using that plugin moves through the list rather than immediately expanding snippets.

**Comment by vinoff** [comment]
> But If we check `luasnip.expand_of_jumpable` first, it will cause unexpected expansion via `<Tab>` navigation, I think.

I haven't come across any unexpected things. It works exactly like in Sublime for me. At least in the tests I have done!

> It's definitely a matter of preference but I don't think changing the order should be default example but maybe included as a comment that someone else might choose to use.

Ya, a comment would be great. Or even another entry with "Sublime-Text like tab", with the order changed.

**Comment by itaranto** [comment]
I'm gonna take advantage of this thread and ask a couple of questions...

What's the rationale for recommending the `<C-d>` and `<C-f>` for scrolling **up** and **down** the docs respectively?
This is completely intuitive since `C-d` means "scroll up half-page" in normal mode.
Wouldn't be better recommending `C-u` and `C-d` for scrolling **up** and **down** retrospectively?

Why `C-<Space` for `complete` is even recommended to begin with?
Why `C-<e>` for `close` if `<Esc>` already closes?

I don't wanna sound rude, I'm genuinely curious about this.

**Comment by vinoff** [comment]
Did the new "breaking changes" break Enter to any of you? I have the following config:

```
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local luasnip = require("luasnip")
local cmp = require("cmp")

cmp.setup({

  -- ... Your other configuration ...
    snippet = {
        expand = function(args)
            require("luasnip").lsp_expand(args.body)
        end,
    },

  mapping = {

    -- ... Your other mappings ...

    ["<Tab>"] = cmp.mapping(function(fallback)
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      -- elseif vim.fn.pumvisible() == 1 then
      --   feedkey("<C-n>")
      elseif cmp.visible() then
        cmp.select_next_item()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" }),

    -- ... Your other mappings ...
  },

  sources = {
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "path" },
  },
  -- ... Your other configuration ...
})
```

and I would like to be able to select an entry in the completion-menu by selecting the entry and clicking ENTER (<CR>). Can any of you achieve this? I still want tab to work though lol
