### ISSUE TITLE
Please consider not using global variables

### ISSUE THREAD

**Issue by JosefLitos** [hrsh7th/nvim-cmp#1810]
I've recently noticed many of the plugins I use make unnecessary variables in the global namespace. I see that `cmp` is using it for a [function call](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/feedkeys.lua#L27). I wanted to ask, if it would be possible to replace it with something like `<Cmd>lua require'cmp.utils.feedkeys'.run(%s)<CR>` moving the [global function](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/feedkeys.lua#L45) to the module, where it comes from.

**Comment by hrsh7th** [comment]
PR welcome.

**Comment by JosefLitos** [comment]
I am not sure I fully understand why this issue is closed.

**Comment by Shougo** [comment]
He don't want to add the feature, but you can make the PR for it.

**Comment by JosefLitos** [comment]
I see. I suppose it's just me but it seems weird that I'm linking this issue in my PR as a fix to it, despite this being closed, which would signify this already being 'solved'.
