### ISSUE TITLE
Locality bonus sorting

### ISSUE THREAD

**Issue by JoseConseco** [hrsh7th/nvim-cmp#183]
Hi I wonder why cmp wont show the most obvious suggestion first:
![image](https://user-images.githubusercontent.com/13521338/132594822-74afd7eb-2c7a-406f-863e-2e1146ed9cc2.png)

Is there way to boost weight of buffer words that are closes to currently edited lines?  So that  words from line above get most priority? Then less and less the further we go. 
There is something in docs about sorting but I cant figure out how these parameters are working:

> {
>   compare.offset,
>   compare.exact,
>   compare.score,
>   compare.kind,
>   compare.sort_text,
>   compare.length,
>   compare.order,
> }

And if they would help at all in above case.

**Comment by hrsh7th** [comment]
I think this is important but it is difficult from performance concerns.

**Comment by d0u9** [comment]
I also encounters this problem that **nvim-cmp** not always put the most matched item on the top of the list.

**Comment by hrsh7th** [comment]
I think `nvim-cmp` always puts the best matching item. (In the screenshot above, all `offset_` prefixed items are` the best match``.

nvim-cmp doesn't care about "locality", but it's just "enhancement or new feature", not a problem.

**Comment by d0u9** [comment]
I think it is best to give an option that enables sortation by length.  For example, the `offset` is the most matching one according to the typed word.

**Comment by hrsh7th** [comment]
You can disable LSP's `sort_text` sorting.

```
local cmp = require('cmp')
cmp.setup {
  sorting = {
    comparators = {
      cmp.config.compare.offset,
      cmp.config.compare.exact,
      cmp.config.compare.score,
      cmp.config.compare.kind,
      -- cmp.config.compare.sort_text,
      cmp.config.compare.length,
      cmp.config.compare.order,
    }
  }
}
```

**Comment by JoseConseco** [comment]
@d0u9  length comparator seems not useful. Below example with only length  comparator :

- `at|`    cmp suggest  `at`  - does not save any key presses 
-  `att|`     cmp suggest  `attr` - does not help - I would have to tab 6 times to get to correct suggestion see image below)

![image](https://user-images.githubusercontent.com/13521338/132760883-04bf9b90-d188-4a43-82a3-7abfd79f806a.png)
If we got  'attribute_node' suggested, then it saves me time of typing in of 12 characters   `|ribute_nodes`. 

The most helpful suggestion I managed to get are with following setup
```lua
comparators = {
	compare.score, -- based on :  score = score + ((#sources - (source_index - 1)) * sorting.priority_weight)
	compare.offset,
	--compare.order,
	--compare.sort_text,
	-- compare.exact,
	-- compare.kind,
        -- compare.length,
}  
```

It is correctly suggesting 'attribute_node' right **after second letter** I typed in   - `at|`. 
![image](https://user-images.githubusercontent.com/13521338/132760740-0dd94785-b2cb-4f9c-b0ad-4027934ea306.png)

I'm not sure if I understand the comparators   - but It looks like enabling more  of them, just give you more results - but the quality (probability of result being what I need) is not increasing at all.     It works like:
 -  score results   +  offset results  + sort_text results  etc.

But it  could / should work like:
 -  filter_by_proximity (  filter_by_sort_text( score.results )  )   #  get results based on cmp 'sources', then filter these by similarity/distance to user input,  then maybe filter again by weighting by locality bonus (or frecency).

**Comment by hrsh7th** [comment]
It is different for each person.
The users are free to customize it.

The nvim-cmp is based on the VS Code sorting logic and some of the customization. For example, VSCode does sort by `alphabetical` but nvim-cmp sort by `length`.

**Comment by hrsh7th** [comment]
I'm glad you made the settings you expected. 👍🏼

**Comment by ccshao** [comment]
I think [ddc-around](https://github.com/Shougo/ddc-around) (also available in deoplete) is interesting, which selects the candidates from flanking lines. It might be nice if similar source is made here.

**Comment by Shougo** [comment]
The ranking is implemented in `sorter-rank` instead of `ddc-around`.

**Comment by marcelbeumer** [comment]
Wouldn't, architecturally, locality be responsibility of the LSP server?

**Comment by hrsh7th** [comment]
The best @dmitmel did it.
