### ISSUE TITLE
Doubt regarding capabilities

### ISSUE THREAD

**Issue by BSiddharth** [hrsh7th/nvim-cmp#1847]
Should I do `local capabilities = require('cmp_nvim_lsp').default_capabilities()` or `local capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())`

**Comment by netrolite** [comment]
Probably `local capabilities = require('cmp_nvim_lsp').default_capabilities()` because I've only seen people use that and it seems to work just fine

**Comment by BSiddharth** [comment]
I am using `local capabilities = require('cmp_nvim_lsp').default_capabilities()` for now tho I was confused bcz the two examples in https://github.com/hrsh7th/nvim-cmp/wiki/Language-Server-Specific-Samples#rust-with-rust-toolsnvim  did it in two different ways

**Comment by BSiddharth** [comment]
@hrsh7th This was closed but I am still not sure of the answer.

**Comment by QuantenToast** [comment]
If you actually try using `update_capabilities` you are greeted with a deprecation message pointing to `default_capabilities` as its successor. Does that answer your question?
