### ISSUE TITLE
[Discussion]: Map keys using vim.keymap.set()

### ISSUE THREAD

**Issue by AXVIII3** [hrsh7th/nvim-cmp#1849]
**PREFACE**  
This is going to sound stupid but I have searched the internet to the best of my ability and couldnt find anything about this. I also tried to solve this by browsing the code but to no avail.

**PROBLEM** (more like annoyance)  
All of my plugins are set up using vim.keymap.set and I have some stuff setup which depends on this function. To maintain consistency, I would like to remap nvim-cmp mappings like complete, select_next/prev using vim.keymaps.set..... this works fine until I use keys that insert text characters like \<Tab\> or \<CR\> which take away my ability to edit text... the fallback function doesnt seem to work and errors out `tried to call fallback() a nil value`... I don't "think" I need to setup fallback? as I didnt have to when mapping using `cmp.setup`

**MY ATTEMPT**
```lua
local cmp = require("cmp");
local luasnip = require("luasnip");

-- Mapping Tab to go to next suggestion
map(
	{ "i", "s" },
	"<Tab>",
	cmp.mapping(function(fallback)
		if cmp.visible() then
			if #cmp.get_entries() == 1 then
				cmp.confirm({ select = true
				});
			else
				cmp.select_next_item({ behavior = cmp.SelectBehavior.Select });
			end
		elseif luasnip.expand_or_locally_jumpable() then
			luasnip.expand_or_jump()
		elseif ax.has_words_before() then
			cmp.complete()
			if #cmp.get_entries() == 1 then
				cmp.confirm({ select = true });
			end
		else
			fallback()
		end
	end).i
);

-- Mapping Shift-Tab to go to next suggestion
map(
	{ "i", "s" },
	"<S-Tab>",
	cmp.mapping(function()
		if cmp.visible() then
			cmp.select_prev_item();
		elseif luasnip.locally_jumpable(-1) then
			luasnip.jump(-1)
		end
	end).i
);

-- Mapping enter to accept the completion
map(
	"i",
	"<CR>",
	cmp.mapping(function(fallback)
		if cmp.visible() and cmp.get_active_entry() then
			cmp.confirm({ select = false });
		else
			fallback()
		end
	end).i
);
```

**NOTE**
`nmap` is just `vim.keymap.set`

**Comment by gegoune** [comment]
There are discussions (on GitHub) that are geared towards usage question.

**Comment by AXVIII3** [comment]
Hey @gegoune 
Thanks for the reply. I tried looking into some of the discussions but none seemed to be linked or similar to my problem. 
Do you think this kind of mapping can be achieved though or the `fallback()` call only works for keymaps setup in `cmp;.setup({ mappings = {})`?

**Comment by AXVIII3** [comment]
I am guessing it isn;t then? Any way we can change the keymap descriptions though?

**Comment by hrsh7th** [comment]
You can use `vim.keymap.set`

```lua
vim.keymap.set({ 'i', 's' }, '<C-Space>', function()
  require('cmp').complete()
end)
```

The `cmp.mapping` supports `fallback` function.
If you don't need this, you can use `:help cmp-function`.

**Comment by AXVIII3** [comment]
Hey @hrsh7th 



> You can use `vim.keymap.set`
> 
> ```lua
> vim.keymap.set({ 'i', 's' }, '<C-Space>', function()
>   require('cmp').complete()
> end)
> ```

So I tried this, the keymap works perfectly but in case of tab and enter, the actual text editing capabilities of these keys do not work any more (no \t or new line). This does not seem to happen when setting mapping in the setup function.




> The `cmp.mapping` supports `fallback` function.

Oh.. so it will automatically call it or I need to do something?



> If you don't need this, you can use `:help cmp-function`.

![image](https://github.com/hrsh7th/nvim-cmp/assets/76608488/d55ca1cb-075f-4bc1-b015-d223e37a070d)
That did not seem to work. Though I did find a list of function manually by scrolling through the docs

Thanks for the reply! This is not a biggie as I just use the setup function for mapping now... But it would be great anyways

**Comment by hrsh7th** [comment]
The `cmp.mapping.*` is a helper function that has useful implementation for mapping.
The `cmp.*` is just an API function.

So you should implement suitable mapping behavior by yourself.

```lua
vim.keymap.set({ 'i', 's' }, '<CR>', function()
  local cmp = require('cmp')
  if not cmp.confirm({ select = false }) then
    vim.api.nvim_feedkeys(vim.keycode('<CR>'), 'ni', true) -- fallback
  end
end)
```

**Comment by AXVIII3** [comment]
> The `cmp.mapping.*` is a helper function that has useful implementation for mapping. The `cmp.*` is just an API function.
> 
> So you should implement suitable mapping behavior by yourself.
> 
> ```lua
> vim.keymap.set({ 'i', 's' }, '<CR>', function()
>   local cmp = require('cmp')
>   if not cmp.confirm({ select = false }) then
>     vim.api.nvim_feedkeys(vim.keycode('<CR>'), 'ni', true) -- fallback
>   end
> end)
> ```

Thank you a LOT! That worked wonders... Oof...

Cheers! :)
