### ISSUE TITLE
Bug: recent commit causes <CR> mapping to fail

### ISSUE THREAD

**Issue by camilledejoye** [hrsh7th/nvim-cmp#185]
Hi,

Quick message to let you know and I'll look further:

When typing <CR> it actually add ` <Plug>(cmp-utils-keymap-listen-run:lhs)` into the buffer:
![image](https://user-images.githubusercontent.com/11501572/132656021-ddc7bfa6-a8c6-4592-9527-2a4d54306410.png)

EDIT: introduced in the commit https://github.com/hrsh7th/nvim-cmp/commit/ff55c1bbca7967779e1034368a1bf6afaf25b8ce

**Comment by hrsh7th** [comment]
Hmm ... Thank you for your report. I'm now trying & error about improvements around mapping.

**Comment by hrsh7th** [comment]
Could you provide minimal repro? It's high priority issue.

**Comment by camilledejoye** [comment]
The result for the "existing" variable:
```lua
{
  buffer = 1,
  expr = 0,
  lhs = "<CR>",
  lnum = 662,
  mode = "i",
  noremap = 2,
  nowait = 0,
  rhs = "<CR><SNR>68_AutoPairsReturn",
  script = 1,
  sid = 68,
  silent = 1
}
```

My setup:
```lua
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['UltiSnips#Anon'](args.body)
    end,
  },

  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = false,
    },
  },

  sources = vim.tbl_map(function(source)
    return { name = source }
  end, vim.tbl_keys(sources)),

  formatting = {
    format = function(entry, vim_item)
      -- fancy icons and a name of kind
      vim_item.kind = require('lspkind').presets.default[vim_item.kind] .. ' ' .. vim_item.kind

      -- set a name for each source
      vim_item.menu = sources[entry.source.name]

      -- set the detail as menu
      if 'nvim_lsp' == entry.source.name then
        if 'phpactor' == entry.source.source.client.name then
          vim_item.menu = entry.completion_item.detail .. ' ' .. vim_item.menu
        end
      end

      return vim_item
    end,
  },
}
```

To reproduce I simply press enter ><
Since it's because I already have a plugin defining a mapping on the key it might be hard to provide a reproducer.
This is the auto pairs plugin I'm using: https://github.com/jiangmiao/auto-pairs

**Comment by hrsh7th** [comment]
Yey! Reproduced. I  will fix it as soon as possible.

**Comment by hrsh7th** [comment]
@camilledejoye Thank you!

**Comment by camilledejoye** [comment]
You're welcome, I confirm it's fixed for me ;)
