### ISSUE TITLE
cannot auto import package caused by  "pull/1725"

### ISSUE THREAD

**Issue by 3Xpl0it3r** [hrsh7th/nvim-cmp#1856]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

when i update nvim-cmp plugin, then cmp doesn't work for rust. I sure PR 
 https://github.com/hrsh7th/nvim-cmp/pull/1725" caused this.

### Steps to reproduce

<img width="1011" alt="image" src="https://github.com/hrsh7th/nvim-cmp/assets/62287907/30fe653f-0271-4c32-805b-41d2c85b6020">
When I applied 1725 PR, `use std::collection::HashMap;` doesn't appear; It should be auto added, but it's not

### Expected behavior

as steps describe

### Actual behavior

as steps describe

**Comment by hrsh7th** [comment]
@3Xpl0it3r Cloud you test the #1857?

**Comment by emxxjnm** [comment]
> @3Xpl0it3r Could you test the #1857?

The problem is still present.

**Comment by 3Xpl0it3r** [comment]
@hrsh7th This's great! it tried https://github.com/hrsh7th/nvim-cmp/pull/1857 and it works, thx ;
