### ISSUE TITLE
feature request: multiline ghost text

### ISSUE THREAD

**Issue by xzbdmw** [hrsh7th/nvim-cmp#1862]
In vscode:
<img width="463" alt="image" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/e606a437-37b3-46e2-b277-2ec492fe76dd">
in cmp:
<img width="586" alt="截屏2024-03-24 17 34 20" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/63972ba2-fb59-4048-b556-1e3fa24a7bfa">
Any help to guide me to compelete the feature is appreciated.

**Comment by xzbdmw** [comment]
Hmm, it needs to expand snippets early, but I don't see proper api in luasnippet to return raw text, some hack in luasnippet to make it happen.
![image](https://github.com/hrsh7th/nvim-cmp/assets/97848247/c9fd8166-ed98-4974-a4ad-e5b95dc849d3)

**Comment by xzbdmw** [comment]
And copilot-cmp can benefit of this two, if it is more general other than snippet.
<img width="1087" alt="截屏2024-04-07 04 25 46" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/58441852-9805-4283-af9e-6e9bc7cfa08a">

**Comment by cxwx** [comment]
how about codeium
