### ISSUE TITLE
[Question] Is there any way to highlight the source type to another color?

### ISSUE THREAD

**Issue by barrientosvctor** [hrsh7th/nvim-cmp#1864]
I wanted to change the color of source types in cmp completion menu but I didn't find nothing to do it.

![source](https://github.com/hrsh7th/nvim-cmp/assets/113469901/ebe82799-e104-4a3e-ad96-8399122490df)

Is there any way to highlight this?

**Comment by bew** [comment]
IIRC you can change all of them, but there is currently no option to highlight a specifically source afaik

**Comment by barrientosvctor** [comment]
> IIRC you can change all of them, but there is currently no option to highlight a specifically source afaik

How can I do it?

**Comment by bew** [comment]
The `CmpItemMenu` highlight group should allow you to change highlight of all source names

**Comment by barrientosvctor** [comment]
> The `CmpItemMenu` highlight group should allow you to change highlight of all source names

It works. Thanks!
