### ISSUE TITLE
How to disable cmp completion for a specific programming language?

### ISSUE THREAD

**Issue by BlueDruddigon** [hrsh7th/nvim-cmp#187]
I don't want to use cmp completion for python language because I'm using Kite engine for autocompletion. So I don't want the LSP complete, but if using cmp it will not display the Kite complete menu. I read your repo but cannot found something like this so I create a new issue. Sorry for my bad english.

**Comment by uga-rosa** [comment]
Try the following.
```vim
au FileType python lua require("cmp").setup.buffer({completion={autocomplete=false}})
```

**Comment by hrsh7th** [comment]
@BlueDruddigon 
Please try it https://github.com/hrsh7th/nvim-cmp/wiki/Disable-cmp-by-filetype
