### ISSUE TITLE
feature request: support labeldetail field

### ISSUE THREAD

**Issue by xzbdmw** [hrsh7th/nvim-cmp#1873]
Currently custom_view support three fields, kind, abbr and menu, and menu field is left-align, which is a bit awkward because if I set `capabilities.textdocument.completion.labelDetailsSupport=true`, some lsp(rust-analyzer for example) sends back something like:

```txt
    --  detail: {
    --   description = "pub fn shl(self, rhs: Rhs) -> Self::Output",
    --   detail = " (use std::ops::Shl)"
    -- }

```
and cmp simply concat these strings in menu field, something looks like:
<img width="1899" alt="截屏2024-04-08 02 37 33" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/73e6c796-77dc-49b5-9da1-dec01caa444f">
and if I cut off menu field it looks like:
<img width="576" alt="截屏2024-04-08 02 39 01" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/93e8717d-253e-4211-94ad-573de4792cc9">
The disadvantage of this approach is that the starting position on the leftmost side of all menus must be greater than the longest string in abbr, leaving many remaining useless spaces in between, I would like add a new field called detail to stay closely behind abbr, and leave menu field right unchanged(left algin)

note: vscode indeed have a detail field in completion items, for `detail`, it follows abbr and for description, it sitck to right side.
<img width="464" alt="截屏2024-04-08 02 47 40" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/193f4794-5af2-46b0-b0b3-91dfb4d2f0f1">

**Comment by bew** [comment]
Why did you you close? @xzbdmw

**Comment by xzbdmw** [comment]
Hmm, I just found left-align is more tidy for me.
