### ISSUE TITLE
Endwise support breaks <CR> fallback

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-cmp#188]
Hi,

since commit 8f559af081c40272a5c2f2a69be510ffa240e391 I started getting my DelimitMate plug mapping printed out when opening bracket from completion item. Here's the gif:

![cmp-cr-fallback-bad](https://user-images.githubusercontent.com/1782860/132826136-93e0fd7b-37bc-4ce9-b43a-8cfbf1146dea.gif)

And here it is with commit before (working ok):

![cmp-cr-fallback-good](https://user-images.githubusercontent.com/1782860/132826160-c3b9d939-74da-4225-b6d4-54b7d988254d.gif)

Edit: Here's my config https://github.com/kristijanhusak/neovim-config/blob/master/nvim/lua/partials/completion.lua#L7-L48

**Comment by rafamadriz** [comment]
Didn't you had to add anything to make delimate work ? I had to add some like this:

```lua
    as.map(
        "i",
        "<CR>",
        [[pumvisible() ? "<C-Y>" : "<Plug>delimitMateCR"]],
        { expr = true, noremap = false }
    )
```

It is in the help file for delimate, https://github.com/Raimondi/delimitMate/blob/537a1da0fa5eeb88640425c37e545af933c56e1b/doc/delimitMate.txt#L682

**Comment by kristijanhusak** [comment]
No I didn't add anything. It was properly handled through cmp fallback.

**Comment by rafamadriz** [comment]
> No I didn't add anything. It was properly handled through cmp fallback.

Interesting, maybe I didn't configure it correctly because delimate didn't work for me with the fallback function. At least the mapping above solves your issue while this gets fixed (at least that's what I think since I'm having no problems)

**Comment by uga-rosa** [comment]
If you can create a minimal structure like the following, it will be easier to research.
https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

**Comment by hrsh7th** [comment]
@kristijanhusak I've fixed mapping problem now.

**Comment by kristijanhusak** [comment]
It works now, thanks!
