### ISSUE TITLE
feature-request: allow more control over completion highlight

### ISSUE THREAD

**Issue by xzbdmw** [hrsh7th/nvim-cmp#1887]
Zed:
<img width="616" alt="截屏2024-04-17 02 45 02" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/36abf371-46cb-4b03-98b0-5ddb3559217f">

They achieve these beautiful colors by regex substitute [`completion.details`](https://github.com/zed-industries/zed/blob/52591905fb8b399401082f7854be4a0fa5677627/crates/languages/src/rust.rs#L181) from language server and apply highlight to them.Currently cmp apply different highlight at a fix width, would be great to expose variable-size highlight(the same format as nvim_buf_set_extmark?) interface to users(and full lsp response message).

Edit: they are just concating detail items to fake it into valid treesitter grammer and apply highlight directly using [treesitter query](https://github.com/zed-industries/zed/blob/e25f0dfb0a2f76829a2fdd32b600da57ce3c747d/crates/language/src/language.rs#L1272). The fake process is fairly easy and already can be done by formatting config. I assume cmp only needs an option to apply treesitter highlights or not for completion items.

**Comment by xzbdmw** [comment]
quick demo
<img width="923" alt="截屏2024-04-18 09 19 42" src="https://github.com/hrsh7th/nvim-cmp/assets/97848247/533eca23-8c76-4bba-84d5-085a01867c84">
![image](https://github.com/hrsh7th/nvim-cmp/assets/97848247/80de129b-4765-40e6-a7d7-c2f5658f58b2)

**Comment by Moerliy** [comment]
Would love to see this happen.
