### ISSUE TITLE
Unexpected behavior with cmp.abort() and cmp.close() when autocomplete = false.

### ISSUE THREAD

**Issue by Ph7s1c** [hrsh7th/nvim-cmp#1919]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```lua
local cmp = require('cmp')
local cmp_select = { behavior = cmp.SelectBehavior.Select }

cmp.setup({
    mapping = {
        ['<Tab>'] = cmp.mapping(function(fallback)
            if cmp.visible() or has_words_before() then
                cmp.complete()
        	    cmp.confirm({ select = true })
            else
                fallback()
            end
        end, {"i","s","c",}),
        ['<Up>'] = cmp.mapping.select_prev_item(cmp_select),
        ['<Down>'] = cmp.mapping.select_next_item(cmp_select),
        ['<C-Space>'] = cmp.mapping(function()
            if cmp.visible() then
                cmp.abort()
            else
                cmp.complete()
            end
        end, {"i","s","c",}),
    },
    completion = {
        autocomplete = false,
    },
    sources = cmp.config.sources({
        { name = 'treesitter' },
        { name = 'calc' },
        { name = 'buffer'},
    }, {
        { name = 'path',
          option = {
            trailing_slash = true},
        },
    })
})
```

### Description

https://github.com/hrsh7th/nvim-cmp/assets/59641969/6ec6e92d-7d0a-4eda-bfd0-2f8cbf1b979e

When calling cmp.abort() or cmp.close(), with manual completion enabled, the completion menu re-appears after typing more characters. 

### Steps to reproduce

Replication steps:

Spawn a completion menu with ctrl-space.
Abort the menu with ctrl-space again
(or a different bind which doesn't make any difference).

Type more characters or delete some characters.

The menu pops up again, which shouldn't happen, since completion has been
aborted, and autocomplete=false.

### Expected behavior

After completion window is aborted, the window should only re-appear once I call cmp.complete() again, rather than when I type more characters.

### Actual behavior

Completion window is initially closed, but typing more characters re-opens the window.

### Additional context

I looked into different workarounds like selecting no completion, but couldn't figure anything out. If this is the intended behavior of nvim-cmp, then this could serve as a feature request to add a function that does the opposite of cmp.complete() for auto-complete=false users.

**Comment by kjuq** [comment]
This may be a duplication of #1251?
And as a workaround, `cmp.core:reset()` solves a problem, according to https://github.com/hrsh7th/nvim-cmp/issues/1251#issuecomment-1365229958
