### ISSUE TITLE
Can't use <C-n> and <C-p> in telescope prompt

### ISSUE THREAD

**Issue by spindensity** [hrsh7th/nvim-cmp#192]
# Description

In `telescope` prompt, pressing <kbd>Ctrl</kbd> + <kbd>n</kbd> or <kbd>Ctrl</kbd> + <kbd>p</kbd>do not select the next or the previous item in the result window, a completing menu pops up instead.

# Steps to reproduce

1. The following content is the minimal configuration that could reproduce the bug. Start `neovim` with the configuration and execute `:PackerCompile`.

```lua
local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.fn.system({"git", "clone", "https://github.com/wbthomason/packer.nvim", install_path})
    vim.api.nvim_command [[packadd packer.nvim]]
end

require("packer").startup({
    function(use)
        -- Packer can manage itself
        use {
            "wbthomason/packer.nvim"
        }

        use {
            "nvim-telescope/telescope.nvim",
            requires = "nvim-lua/plenary.nvim",
            config = function()
                require("telescope").setup {}
            end
        }

        use {
            {
                "hrsh7th/nvim-cmp",
                config = function()
                    local cmp = require("cmp")
                    cmp.setup {
                        mapping = {
                            ["<C-p>"] = cmp.mapping.select_prev_item(),
                            ["<C-n>"] = cmp.mapping.select_next_item()
                        },
                        sources = {
                            { name = 'buffer' }
                        }
                    }
                end
            },
            {
                "hrsh7th/cmp-buffer"
            }
        }
    end
})
```
2. Restart `neovim`, execute `:Telescope help_tags`, press <kbd>Ctrl</kbd> + <kbd>n</kbd> or<kbd>Ctrl</kbd> + <kbd>p</kbd>.

# Expected behavior

The next or previous item in the result window should be selected.

# Actual behavior

A completing menu pops up.
![Snipaste_2021-09-13_00-09-27](https://user-images.githubusercontent.com/33576822/132994849-4a9b36de-0806-4587-8fac-136d2841fefb.png)

# Additonal information

Commenting the following keymap defined code in the configuration could be a temporary workaround, but I thank the `nvim-cmp` should not override the keymap defined by `telescope` in its prompt.

```lua
mapping = {
    ["<C-p>"] = cmp.mapping.select_prev_item(),
    ["<C-n>"] = cmp.mapping.select_next_item()
},
```

I've try to disable `nvim-cmp` in `telescope` prompt via the following code, but it does not work.
```lua
vim.cmd [[
augroup disable_nvim_cmp_group
autocmd!
autocmd FileType TelescopePrompt lua require('cmp').setup.buffer { completion = { autocomplete = false } }
augroup END
]]
```

**Comment by hrsh7th** [comment]
Please try it
https://github.com/hrsh7th/nvim-cmp/wiki/Disable-cmp-by-filetype

**Comment by spindensity** [comment]
> Please try it
> https://github.com/hrsh7th/nvim-cmp/wiki/Disable-cmp-by-filetype

It's not work, the following code does not forbid the keymap.

```lua
autocmd FileType TelescopePrompt lua require("cmp").setup.buffer({ enabled = false })
```

I've checked the`filetype` of the `telescope` prompt is `TelescopePrompt` by `:echo &ft`

**Comment by hrsh7th** [comment]
Are you usinh latest nvim-cmp? It's weird.

**Comment by spindensity** [comment]
> Are you usinh latest nvim-cmp? It's weird.

Yes.
![Snipaste_2021-09-13_00-40-05](https://user-images.githubusercontent.com/33576822/132995716-716e93c1-8717-46f8-83eb-30783e36626f.png)

Versions:

Telescope: git commit ID `978366ba46e2306b60ef64bd9e51a6c758fe48f0`
nvim-cmp: git commit ID `1cec1ecb31879ba4cf719d1d22cae628d8108f1c`

All of them are the latest commits.

**Comment by spindensity** [comment]
I can not reproduce it after 9c460395a04e2ea7a1f4f8b82572efc67faf18ff, the problem might have been fixed, thanks.
