### ISSUE TITLE
documentation sticks after cancelling completion

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-cmp#193]
![image](https://user-images.githubusercontent.com/29136904/133001753-9e47a523-3084-4acd-8291-741f63aa96ad.png)

**Comment by hrsh7th** [comment]
@ChristianChiarulli I can't reproduce it. Please your config.

**Comment by ChristianChiarulli** [comment]
It may be an issue or conflict with something else, I'll try a couple things out on my end. The config is somewhat complicated but this is how we're setting it up:

https://github.com/LunarVim/LunarVim/blob/rolling/lua/core/cmp.lua

**Comment by hrsh7th** [comment]
Hm... It seems to have a `<C-e>` mapping correctly.


https://user-images.githubusercontent.com/629908/133025874-1e303cf2-39f9-4c6a-b08c-a6dbc19554ea.mp4

**Comment by hrsh7th** [comment]
I've updated the related implementation. Could you try that?
https://github.com/hrsh7th/nvim-cmp/commit/af73e87fd853d61e3ebca6f21f42a8d171124845

**Comment by ChristianChiarulli** [comment]
sure, I'll give it a shot

**Comment by ChristianChiarulli** [comment]
seems to have fixed it thanks!
