### ISSUE TITLE
Disabling preselect doesn't seem to work

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-cmp#194]
I am adding the following to cmp.setup:

`preselect = 'none',` 

one thing to note tho is that the arrow keys work without preselect so maybe there is something to be learned from that.

**Comment by hrsh7th** [comment]
Please check the README.md https://github.com/hrsh7th/nvim-cmp#preselect-type-cmppreselectmode

**Comment by ChristianChiarulli** [comment]
doesn't that just map to "none" tho?

**Comment by hrsh7th** [comment]
You should set `cmp.PreselectMode.None` :)
