### ISSUE TITLE
vim.tbl_add_reverse_lookup is deprecated

### ISSUE THREAD

**Issue by jackfranklin** [hrsh7th/nvim-cmp#1947]
On the latest Neovim nightly release:

```
- WARNING vim.tbl_add_reverse_lookup is deprecated. Feature will be removed in Nvim 0.12
  - ADVICE:
    - stack traceback:
        /home/jack/.local/share/nvim/lazy/nvim-cmp/lua/cmp/types/lsp.lua:205
        [C]:-1
        /home/jack/.local/share/nvim/lazy/nvim-cmp/lua/cmp/types/init.lua:4
        [C]:-1
        /home/jack/.local/share/nvim/lazy/nvim-cmp/plugin/cmp.lua:11
        [C]:-1
        vim/_editor.lua:0
        /home/jack/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:485
```

I am happy to try to figure this out, but reporting in case anyone else beats me to it.

**Comment by xuwei152** [comment]
I have solved it in an ugly way by asking GPT to write a code to replace it
![Clip_2024-05-31_11-36-52](https://github.com/hrsh7th/nvim-cmp/assets/51861161/8954e765-b57d-4769-8db8-406ac1229b2b)

I am looking forward to a more elegant way.

**Comment by Shougo** [comment]
@jackfranklin @xuwei152 

Please update nvim-cmp to the latest version.  Because the function is not used anymore.

**Comment by hrsh7th** [comment]
Thank you. @Shougo

**Comment by jackfranklin** [comment]
Apologies for the noise, I thought I was up to date but clearly not. Thanks so much!
