### ISSUE TITLE
Hover documentation border will not work

### ISSUE THREAD

**Issue by lawsonguilbeau** [hrsh7th/nvim-cmp#1958]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

return {
  "hrsh7th/nvim-cmp",
  event = "InsertEnter",
  dependencies = {
    "hrsh7th/cmp-buffer", -- source for text in buffer
    "hrsh7th/cmp-path", -- source for file system paths
    {
      "L3MON4D3/LuaSnip",
      -- follow latest release.
      version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
      -- install jsregexp (optional!).
      build = "make install_jsregexp",
    },
    "saadparwaiz1/cmp_luasnip", -- for autocompletion
    "rafamadriz/friendly-snippets", -- useful snippets
    "onsails/lspkind.nvim", -- vs-code like pictograms
  },
  config = function()
    local cmp = require("cmp")

    local luasnip = require("luasnip")

    local lspkind = require("lspkind")

    -- loads vscode style snippets from installed plugins (e.g. friendly-snippets)
    require("luasnip.loaders.from_vscode").lazy_load()

    cmp.setup({
      completion = {
        completeopt = "menu,menuone,preview,noselect",
      },
      snippet = { -- configure how nvim-cmp interacts with snippet engine
        expand = function(args)
          luasnip.lsp_expand(args.body)
        end,
      },
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      mapping = cmp.mapping.preset.insert({
        ["<C-k>"] = cmp.mapping.select_prev_item(), -- previous suggestion
        ["<C-j>"] = cmp.mapping.select_next_item(), -- next suggestion
        ["<C-b>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete(), -- show completion suggestions
        ["<C-e>"] = cmp.mapping.abort(), -- close completion window
        ["<CR>"] = cmp.mapping.confirm({ select = false }),
      }),
      -- sources for autocompletion
      sources = cmp.config.sources({
        { name = "nvim_lsp" },
        { name = "luasnip" }, -- snippets
        { name = "buffer" }, -- text within current buffer
        { name = "path" }, -- file system paths
      }),

      -- configure lspkind for vs-code like pictograms in completion menu
      formatting = {
        format = lspkind.cmp_format({
          maxwidth = 50,
          ellipsis_char = "...",
        }),
      },
    })
  end,
}

### Description

The hover documentation window border will not show.

### Steps to reproduce

1. Wrote the config file for nvim-cmp
2. Loaded the plugin with Lazy.nvim
3. Everything worked as expected, except for the hover documentation widow border

### Expected behavior

Hover documentation window border should show. 

### Actual behavior

The border for the hover documentation window will not show.

**Comment by iamhrigved** [comment]
If you use [noice.nvim](https://github.com/folke/noice.nvim), you have to do something like this

```lua
require("noice").setup({
    lsp = {
        documentation = {
	    view = "hover",
	    opts = { -- lsp_docs settings
	    lang = "markdown",
	    replace = true,
	    render = "plain",
	    format = { "{message}" },
	    position = { row = 2, col = 2 },
	    size = {
		max_width = 0.8 * vim.api.nvim_win_get_width(0),
		max_height = 15,
	    },
	    border = {
		style = "rounded",
	    },
	    win_options = {
		concealcursor = "n",
		conceallevel = 3,
		winhighlight = {
		    Normal = "CmpPmenu",
		    FloatBorder = "DiagnosticSignInfo",
		},
	    },
	},
    },
})
```

**Comment by lawsonguilbeau** [comment]
Thank you for the help. I add the code that you suggested to my noice.lua file after adding a config function. I did encounter one issue that I quickly resolved though. When I first tried to open a hover doc after adding the suggested code above, I was given an error { Invalid 'width': Number is not integral }. To fix this I simply removed the { max_width = 0.8 * vim.api.nvim_win_get_width(0), } line from the code, and everything works as expected. Thank you again for the help @iamhrigved.

**Comment by iamhrigved** [comment]
@lawsonguilbeau

You're welcome.

But I have some suggestions,

When you multiply `0.8` to the number of columns of the current buffer, it is possible that the number you get is not an `Integer`. Its probably a coincidence that my terminal window by default has a width, which indeed returns an integer when multiplied be `0.8`.

To prevent that from happening, you can do something like this,

```lua
size = {
    max_width = math.floor(0.8 * vim.api.nvim_win_get_width(0)),
    max_height = 15,
},
```
I highly recommend this setting, because some docs take a lot of space, so it is a good idea to limit their width.

**Comment by lawsonguilbeau** [comment]
I have applied the changes that you suggested, and everything works as expected. I am so grateful for your help in this matter.
