### ISSUE TITLE
How to disable background transport

### ISSUE THREAD

**Issue by longway1024** [hrsh7th/nvim-cmp#1968]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

lazyvim config

### Description

NA

### Steps to reproduce

NA background transport，It is hard to see

### Expected behavior

NA

### Actual behavior

NA

**Comment by Shougo** [comment]
I think the screenshot upload is better.

**Comment by longway1024** [comment]
![244c9c6797084430963572730a9a22ef](https://github.com/hrsh7th/nvim-cmp/assets/131593055/e9ce66fc-5eb5-4caf-9354-141d0af85bb8)

**Comment by longway1024** [comment]
![image](https://github.com/hrsh7th/nvim-cmp/assets/131593055/1e00e5cb-4bba-4c02-bc7d-3c89e7a6469d)

**Comment by longway1024** [comment]
It looks like this，we can see background code

**Comment by Shougo** [comment]
I think `winblend` options is set.  Please check.

**Comment by longway1024** [comment]
yes，winblend set 10.
