### ISSUE TITLE
Navigation through code completion does not work anymore

### ISSUE THREAD

**Issue by Pismice** [hrsh7th/nvim-cmp#1990]
![image](https://github.com/user-attachments/assets/7e70360e-d4f4-4514-9932-2cedbd17438d)
Hello I have been using nvim-cmp for a long time and I acciendtly updated all my packages with Lazy today, and I can not navigate through code completions anymore. I am big neovim and lua noob and I could not figure out how to resolve this issue. This is quite problematic since neovim in my main editor for working :(
It might be something very stupid but I have no clue.
If you have just a glimplse of an idea I would be glad to hear it :)

**Comment by Hexdigest123** [comment]
After I updated my config, I ran into the same issue. Currently, my config is "unusable" due to this error. If anyone finds a hotfix, I would definitely appreciate it.

**Comment by shelldandy** [comment]
Same here, we probably need to downgrade nvim-cmp

**Comment by Pismice** [comment]
how can i downgrade it ?

**Comment by Hexdigest123** [comment]
> Same here, we probably need to downgrade nvim-cmp

yes probably it only affects the dev branch

> how can i downgrade it ?

in case of lazyvim you could choose a different branch

**Comment by bew** [comment]
Make sure to check recently opened issues before creating new ones 😬
In this case: #1988

**Comment by Pismice** [comment]
> > Same here, we probably need to downgrade nvim-cmp
> 
> yes probably it only affects the dev branch
> 
> > how can i downgrade it ?
> 
> in case of lazyvim you could choose a different branch

Isnt it pulling "main" by default and not "dev" ?

**Comment by polirritmico** [comment]
> how can i downgrade it using Lazy?

Use `commit = "<hash>",` in the nvim-cmp spec.

**Comment by Hexdigest123** [comment]
> > > Same here, we probably need to downgrade nvim-cmp
> > 
> > 
> > yes probably it only affects the dev branch
> > > how can i downgrade it ?
> > 
> > 
> > in case of lazyvim you could choose a different branch
> 
> Isnt it pulling "main" by default and not "dev" ?

yes you are right it does

**Comment by shelldandy** [comment]
You can hotfix this by tweaking your `lazy-lock.json` to

```json
 "nvim-cmp": { "branch": "main", "commit": "7e348da6e5085ac447144a2ef4b637220ba27209" },
```

Then open nvim and hit `:Lazy restore`

**Comment by Pismice** [comment]
Yep all good thank you guys :)

**Comment by BotDeIA** [comment]
i applied the changes manually from pr #1989 on my pc until the problem is fixed, and it worked again auto complete
