### ISSUE TITLE
cmp.select_next_item() gets error "attempt to perform arithmetic on local 'cursor'

### ISSUE THREAD

**Issue by TecAbel** [hrsh7th/nvim-cmp#1992]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<C-n>"] = cmp.mapping(function ()
          cmp.complete()
        end, { "i", "s" }),
        ["<Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_next_item({ select = true })
            -- You could replace the expand_or_jumpable() calls with expand_or_locally_jumpable()
            -- this way you will only jump inside the snippet region
          elseif luasnip.expand_or_locally_jumpable() then
            luasnip.expand_or_jump()
          elseif has_words_before() then
            cmp.complete()
          else
            fallback()
          end
        end, { "i", "s" }),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          elseif luasnip.jumpable(-1) then
            luasnip.jump(-1)
          else
            fallback()
          end
        end, { "i", "s" }),
      })

```

### Description

I use the supertab approach like the LazyVim docs says, but it does not works. I'm getting the Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value).
This error stills reproducing if removing the supertab config.
<img width="2048" alt="Screenshot 2024-07-15 at 5 41 15 p m" src="https://github.com/user-attachments/assets/9b17fea4-90ca-4f30-8a9b-50bb0b5f718b">

### Steps to reproduce

Write anything and try to autocomplete with Tab or <C-n>

### Expected behavior

navigate into the options provided

### Actual behavior

getting the error 
<img width="2048" alt="Screenshot 2024-07-15 at 5 41 15 p m" src="https://github.com/user-attachments/assets/8858b139-b122-49da-9f66-2cd313e45f52">

**Comment by bew** [comment]
Please search open issues with the error msg for example.
Existing issue about this: #1988

**Comment by TecAbel** [comment]
Thank you @bew 

In case anyone get this behaviour too, this helps

the comment of @shelldandy https://github.com/hrsh7th/nvim-cmp/issues/1990#issuecomment-2229282421 helps

change this line on your lazy-lock.json

```json
{
 "nvim-cmp": { "branch": "main", "commit": "7e348da6e5085ac447144a2ef4b637220ba27209" },
}
```

then run 
```bash
:Lazy restore
```

**Comment by Shougo** [comment]
Please test this.

https://github.com/hrsh7th/nvim-cmp/pull/1993

**Comment by sjclayton** [comment]
#1993 solves the issue.

**Comment by Shougo** [comment]
It should be closed.
