### ISSUE TITLE
Improperly sized windows

### ISSUE THREAD

**Issue by rafaeljacov** [hrsh7th/nvim-cmp#1999]
# How to fix this?
- I sometimes get this funny too narrow sized context window in cmp while the completion window takes unnecessary large space.
- Is there a way to adjust them accordingly? (for example setting max width for the completion window).

![image](https://github.com/user-attachments/assets/9e989a7a-4e5d-4c20-b2c2-46758de62721)

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/980
