### ISSUE TITLE
Will this deprecate nvim-compe?

### ISSUE THREAD

**Issue by kuator** [hrsh7th/nvim-cmp#2]
Hi, thank you for creating amazing plugins! I have a question: will nvim-cmp deprecate https://github.com/hrsh7th/nvim-compe?

**Comment by figsoda** [comment]
if not, what are the differences between the 2 plugins

**Comment by hrsh7th** [comment]
Yes. I will deprecate nvim-compe. But it will take a time yet.

**Comment by Shatur** [comment]
> Yes. I will deprecate nvim-compe. But it will take a time yet.

What the purpose of rewrite?

**Comment by hrsh7th** [comment]
The purpose is that try to solve nvim-compe's some design mistakes.

1. nvim-compe does not treat LSP's CompletionItem type as first class things.
This makes it harder to implement some of the features like `replacing text`, `commit characters`, `customizing menu`.

2. nvim-compe supports the way of configuration by Vim script.
This makes it harder to implement configuration by Lua functions.

3. nvim-compe is a bit difficult to configure.
nvim-compe provides `compe#confirm`, `compe#complete` etc.
But I was received many issues with it... (tpope/vim-endwise etc...)

**Comment by kuator** [comment]
> The purpose is that try to solve nvim-compe's some design mistakes.
> 
>     1. nvim-compe does not treat LSP's CompletionItem type as first class things.
>        This makes it harder to implement some of the features like `replacing text`, `commit characters`, `customizing menu`.
> 
>     2. nvim-compe supports the way of configuration by Vim script.
>        This makes it harder to implement configuration by Lua functions.
> 
>     3. nvim-compe is a bit difficult to configure.
>        nvim-compe provides `compe#confirm`, `compe#complete` etc.
>        But I was received many issues with it... (tpope/vim-endwise etc...)

Thank you for the comprehensive answer!

**Comment by gegoune** [comment]
@hrsh7th issue worth pinning for the time being I think.

**Comment by lucax88x** [comment]
@hrsh7th Can you ping there when you think it's production ready to substitute nvim-compe?

**Comment by hrsh7th** [comment]
OK. I will update nvim-compe's README.md if the time has come.
