### ISSUE TITLE
lspkind-nvim compatibility

### ISSUE THREAD

**Issue by timbedard** [hrsh7th/nvim-cmp#20]
nvim-compe was compatible with [lspkind-nvim](https://github.com/onsails/lspkind-nvim). Do the changes in nvim-cmp prohibit this compatibility, or is it something we can add?

**Comment by gegoune** [comment]
There is a way, like

```lua
for index, value in ipairs(vim.lsp.protocol.CompletionItemKind) do
    cmp.lsp.CompletionItemKind[index] = value
end
```
(search other issues for original author, I think it was @windwp) But it definitely would be nicer if `vim.lsp.protocol.CompletionItemKind` was used if set.

**Comment by hrsh7th** [comment]
I will add the API to customize menu's. I think this customization should be realized on user-land.

**Comment by timbedard** [comment]
> I will add the API to customize menu's. I think this customization should be realized on user-land.

I agree. Thanks!

**Comment by hrsh7th** [comment]
I've added the API for it.
https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem

**Comment by timbedard** [comment]
Sweet. Thanks!

**Comment by gegoune** [comment]
How would relevant function look without lspkind-nvim? Tried

```lua
formatting = {                                                                                        
  format = function(_, vim_item)                                                                      
    vim_item.kind = vim.lsp.protocol.CompletionItemKind[vim_item.kind]                                
    return vim_item                                                                                   
  end,                                                                                                
},                                                                                                    
```
but it does not display anything except for completion candidate itself.
<img width="221" alt="Screenshot 2021-08-16 at 11 31 16" src="https://user-images.githubusercontent.com/69750637/129542498-75822381-dca0-4fe5-8347-3342f0edb7ee.png">

**Comment by hrsh7th** [comment]
vim_item.kind can be `Function`/`Snippet`/`Folder` etc.
You should check `vim.lsp.protocol.CompletionItemKind` keys.

And I think it doesn't problem.  Is it a problem for you?

**Comment by gegoune** [comment]
Ah, ok, so it won't work since `vim.lsp.protocol.CompletionItemKind` is

```lua
vim.lsp.protocol.CompletionItemKind = {
  'ﮜ [text]', -- Text = 1;
  ' [method]', -- Method = 2;
  'ƒ [function]', -- Function = 3;
…
}
```
