### ISSUE TITLE
preselection not working in command mode

### ISSUE THREAD

**Issue by Rekwass** [hrsh7th/nvim-cmp#2005]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

set ignorecase " Set the ignorecase option

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-cmdline' " This plugin is required to display the issue
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  -- Change the completion, so that the first item is selected and highlighted.
  completion = {
    completeopt = 'menu,menuone,noinsert'
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}

-- Setup the cmdline with the bare minimum
cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
	{ name = 'cmdline' }
    }),
})

EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When writing in command mode in neovim with `ignorecase` everything works fine, but when pressing enter, even if the first item is selected, it will not be replaced with the proper case and the command will fail (if not cased properly).

### Steps to reproduce

- Use the minimal config provided
- Open neovim
- Hop in command mode (with `:` in this case)
- Try to write the `CmpStatus` command but without case ("cmpstatus")
- Press enter
- See that it says "Not an editor command cmpstatus"
![cmp-cmdline-preselection](https://github.com/user-attachments/assets/97aeb960-519e-4bd8-9964-3dfdb36d8efa)

### Expected behavior

I am expecting the first item that is highlighted to be inserted as I press enter.
![cmp-expected](https://github.com/user-attachments/assets/3a126a9c-d708-40e9-8e12-d72bb5519e09)
(In the GIF, I hit `<Tab>` twice to unselect then select it again.

### Actual behavior

The command shows properly but does not insert as expected when pressing enter.
![cmp-cmdline-preselection](https://github.com/user-attachments/assets/97aeb960-519e-4bd8-9964-3dfdb36d8efa)

### Additional context

Same behaviour for every command characters (:, /, ?, ...). This is related to the `COMMAND` mode.
Works as expected in insert mode.
![cmp-insert-mode](https://github.com/user-attachments/assets/25d8d74f-334f-4620-838e-049532e53716)
Also, setting the `cmp.ConfirmBehavior` to `Replace` did not resolved the issue.

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/mapping.lua#L74

`cmp.mapping.preset.cmdline()` does not define `<CR>`.
So your mappings does not work as expected.

**Comment by Shougo** [comment]
```lua
-- Setup the cmdline with the bare minimum
cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline({
      ['<CR>'] = { c = cmp.mapping.confirm({ select = true })}
    }),
    sources = cmp.config.sources({
      { name = 'cmdline' }
    }),
})
```

It works for me.

**Comment by Rekwass** [comment]
> https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/mapping.lua#L74
> 
> `cmp.mapping.preset.cmdline()` does not define `<CR>`. So your mappings does not work as expected.

I probably mixed up the configuration of the `insert` mode and `command` for some reason.

Thank you
