### ISSUE TITLE
Autocomplete characters getting stuck in terminal window

### ISSUE THREAD

**Issue by bragjo** [hrsh7th/nvim-cmp#201]
I'm having some issues with characters being rendered/stuck in my terminal window even after closing the suggestion list.

See attachments.
![unknown2](https://user-images.githubusercontent.com/17138968/133428902-b4bf21a7-79ae-487b-8611-d8a990ceb443.png)
![unknown](https://user-images.githubusercontent.com/17138968/133428905-4ab29df2-cdfd-425e-98a3-9e6506674b0b.png)

I tried to disable the colorscheme and tried another terminal aswell (currently using Windows terminal but same happens for me in Alacritty).

**Comment by Shougo** [comment]
Same with https://github.com/hrsh7th/nvim-cmp/issues/48 ...

**Comment by hrsh7th** [comment]
@bragjo I've turned off the option of `format.deprecated`.

**Comment by bragjo** [comment]
> @bragjo I've turned off the option of `format.deprecated`.

I can confirm that by adding format.deprecated = false in my cmp config file, this problem is eliminated. Thanks alot!
