### ISSUE TITLE
Disable this plugin for floating windows

### ISSUE THREAD

**Issue by uwla** [hrsh7th/nvim-cmp#2012]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Description

Look at the following demo, it does not let me rename the variable back from "MyVar" to "M" due to the completion prevents me when I hit enter:

![NVIM-CMP](https://github.com/user-attachments/assets/1afd0b86-3894-4ca7-9101-32b2431cc65f)

When using <https://github.com/filipdutescu/renamer.nvim> to rename variables with LSP, this plugins shows a floating input box to rename the variable, but often `nvim-cmp` shows a completion menu and it either (1) crashes the rename plugin (2) does not crashes the renamer plugin but it creates a very poor user experience by annoying pop-up suggestions.

### Steps to reproduce

1. Install and set up `renamer.nvim` and `nvim-cmp`
2. Rename a variable and type something that will trigger a `nvim-cmp` suggestion (such as another word in the current buffer)
3. `nvim-cmp` will show suggestions and upon hit `ENTER` in the middle of the variable name it simply crashes everything

### Expected behavior

Option to disable `nvim-cmp` in floating windows? I cannot remember a scenario where completion is needed in a floating window because floating windows usually are used for refactoring and floating inputs

### Actual behavior

It shows the completion menu, but in this context it should not attempt to provide completion.

**Comment by Shougo** [comment]
You can see this.

https://github.com/hrsh7th/nvim-cmp/issues/60#issuecomment-905632958
