### ISSUE TITLE
Not following set source order

### ISSUE THREAD

**Issue by sQVe** [hrsh7th/nvim-cmp#202]
👋

I run `nvim_lsp` and `vsnip` and noted that the `vsnip` completion gets an higher order than `nvim_lsp` sometimes. There seems to some kind of race condition then the lsp engine or something is providing info slowly.

I basically run something like this:
```
        sources = {
            {name = 'nvim_lsp'}, {name = 'path'}, {name = 'vsnip'}
        }
```

Above should give me:
![image](https://user-images.githubusercontent.com/2284724/133435703-d31b34a7-512b-4682-9884-59e0ac6b6c3c.png)

which is sometimes does but sometimes gives:
![image](https://user-images.githubusercontent.com/2284724/133435793-6d070ce6-620e-4a20-bafb-452bd52b5153.png)

(the LSP suggestions is listed but after ALL snippets)

**Comment by hrsh7th** [comment]
Please reproduce steps and tour snippets.

**Comment by sQVe** [comment]
Setting the `priority` manually solves this issue for me.

**Comment by hrsh7th** [comment]
But I think your config should be working as expected.
Hm... I hope to know how to reproduce this isuee.

**Comment by sQVe** [comment]
I'll see if I can create a minimal config that reproduces it.

**Comment by sQVe** [comment]
It's kind of annoying to put together a minimal config for this due to *LSP* etc. Is it enough will my full setup? You can see it here: https://github.com/sQVe/dotfiles/tree/master/config/nvim

**Comment by hrsh7th** [comment]
Thank you. It's enough. I will check it

**Comment by hrsh7th** [comment]
I think now `cmp-vsnip` solves this issue... (maybe)
