### ISSUE TITLE
Option to show the completion window above the cursor

### ISSUE THREAD

**Issue by khanhicetea** [hrsh7th/nvim-cmp#2024]
Hi, thanks for the plugins

I read the docs but can't find settings to show the "completion" window above the cursor, because in my context, the hide the "documentation" window (see screenshot below).

Or is there a top-padding of documentation window setting ( the "col_offset" looks work only for vertial )

![image](https://github.com/user-attachments/assets/d0d0f90c-178e-427f-b172-8fb5f296c56b)

Btw, thanks!

**Comment by Shougo** [comment]
Please see this.

https://github.com/hrsh7th/nvim-cmp/pull/1701

**Comment by khanhicetea** [comment]
Thanks, removing "nvim_lsp_signature_help" source works for me (look like I don't need it, the "documentation" window is enough for me). Reading your PR, I think it suite for Copilot things.

I understand the author have a good reason to not add lot features :) He has busy life behind ^^ 

I close this issue because duplication, thank you @Shougo
