### ISSUE TITLE
Incompatibility with "whonore/Coqtail"

### ISSUE THREAD

**Issue by swy7ch** [hrsh7th/nvim-cmp#204]
# Preamble

Sorry if this isn't the right place for posting it. I wondered if I should create an issue here or on the [whonore/Coqtail](https://github.com/whonore/Coqtail) project, but since the plugin doesn't seem to mess with the current buffer's content and `nvim-cmp` is, well, *supposed* to do so, I'm reporting here. I can always report on the other project if need be. 

Also, please note that the combo `Coqtail` x `nvim-compe` (the former project from u/hrsh7tm) worked flawlessly.

# Problem

Using `hrsh7th/nvim-cmp` along with [whonore/Coqtail](https://github.com/whonore/Coqtail) introduces unwanted, unremovable characters:

![image](https://user-images.githubusercontent.com/24797611/133518506-f205b0cb-8405-4182-9d7c-576dd9bc5a38.png)

(sorry for the coloration, this is part of `whonore/Coqtail` and I want the config to be minimal).

It *seems* to be related to keywords ending a block of work (such as a proof block), since it seems to concern only keywords such as `Qed`, `Admitted`or `Abort` :

![image](https://user-images.githubusercontent.com/24797611/133520224-0ed51b71-113f-46ce-b144-ed2f9f326a45.png)

As you can see, no issue with starting keywords such as `Proof` or `Lemma`.

Those characters are interpreted by the Coq interpretor and therefore, make the file almost unusable since they are unremovable via backspace or delete. I did find a "hack", that is typing the desired word twice : since the character `^F` only appears once, we can then go back to normal mode and delete it via `x` or `d`.

## Expected behaviour

No insertion of character by the completion engine.

## Steps to reproduce

Here is the basic neovim config file that I used:

    require'cmp'.setup { }

    return require('packer').startup(function()
      -- Packer can manage itself
      use 'wbthomason/packer.nvim'
      use "hrsh7th/nvim-cmp"
      use "whonore/Coqtail"
    end)

* Install both `nvim-cmp` and `whonore/Coqtail` plugins
*  Open a coq file using `$ nvim -u basic_init.lua foo.v`
*  Enter INSERT mode, and type ```Qed.```

# Setup

* `NVIM v0.6.0-dev+276-g685cf3981`, latest version as of writing
* all plugins (`packer`, `nvim-cmp` and `Coqtail`) are up to date

# Additional infos

Currently empty, I'll edit this part if need be.

**Comment by hrsh7th** [comment]
This issue caused by `feedkeys('<C-f'>` without `set indentkeys-=!^F`.
I've fixed it.

**Comment by swy7ch** [comment]
Dang that was fast. Thanks ! :)
