### ISSUE TITLE
cmp.mapping.complete() Doesn't Load the Completion Menu

### ISSUE THREAD

**Issue by thomastthai** [hrsh7th/nvim-cmp#2046]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
-- Bug testing for nvim-cmp
-- https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  completion = { autocomplete = false },
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ["<C-S-Tab>"] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

Attached is my `~/cmp-repro.vim` config file. Auto-completion works great. However, manual completion isn't working, or could be my understanding of how it should work. By manual completion, I mean:

Various keybinding mappings have been tried to no avail after checking for potential keybinding mapping conflicts. Google and Issues have been searched.

### Steps to reproduce

1. Setting `completion = { autocomplete = false },`
2. Setting the mapping to `["<C-S-Tab>"] = cmp.mapping.complete(),`
3. Restarting: `nvim -u ~/cmp-repro.vim`
4. `:e ~/cmp-repro.css`
5. Put the cursor after `h1 {`
6. Press `Control-Shift-Tab` 
7. No completion menu appears.

~/cmp-repro.css:

```css
/* Styles for the body element */
body {
  font-family: Georgia, "Times New Roman", Times, serif;
  color: purple;
  background-color: #d8da3d;
  padding-left: 11em;
}
h1 {
```

### Expected behavior

The completion menu to appear after manual completion keybinding is pressed as seen in in the image below when auto-completion is on:

<img width="720" alt="Screenshot 2024-09-24 at 2 34 11 PM" src="https://github.com/user-attachments/assets/af428304-3f8c-41ae-b570-163831dabfae">

### Actual behavior

The completion menu didn't appear after keybinding is pressed.

### Additional context

```bash
❯ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724232689
```

**Comment by bew** [comment]
Are you sure your terminal is is configured to pass the keys ctrl-shift-tab to neovim? (e.g. With kitty keyboard protocol)

To check if it's the keybind that is just not sent to neovim, try to use a different key like `<C-t>`or `<Tab>` for that action and see if it works.
