### ISSUE TITLE
Code hints / suggestions from demo video

### ISSUE THREAD

**Issue by qgates** [hrsh7th/nvim-cmp#2047]
Watching your demo.mp4 video for nvim-cmp, as you type line completion suggestions are made (in gray). Is this a feature of nvim-cmp or a side effect of copilot / codeium, if so what's the config option to enable it?

Thanks for this extension, it's a real time saver 🙂

**Comment by Shougo** [comment]
It is `ghost_text` feature.

https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L763

**Comment by qgates** [comment]
Brilliant thanks! 🙂
