### ISSUE TITLE
Not suggesting snippet?

### ISSUE THREAD

**Issue by phuongthuan** [hrsh7th/nvim-cmp#206]
I'm using nvim-cmp + vsnip
here is my configuration:

In `cmp.lua`

```
cmp.setup {
  completion = {
    completeopt = "menu,menuone,noinsert",
  },
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
    ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
    ['<Tab>'] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
      elseif vim.fn['vsnip#available']() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>(vsnip-expand-or-jump)', true, true, true), '')
      else
        fallback()
      end
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' }
    { name = 'vsnip' },
  },
}
```
and update capabilities
```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
```

I created javascript snippet like this in `javascipt.json` file:
```
{
  "useState": {
    "prefix": ["useS"],
    "body": [
      "const [$1, $2] = useState($3);$0"
    ]
  },
}
```

in `test.js` file, and This is what I got.
![image](https://user-images.githubusercontent.com/20045189/133553385-ca8e15f7-4be7-4312-867d-9d7b2779383c.png)

What is wrong here? or am I missing something?

**Comment by hrsh7th** [comment]
You should set `g:vsnip_filetypes`.
See https://github.com/hrsh7th/vim-vsnip#2-setting

**Comment by phuongthuan** [comment]
> You should set `g:vsnip_filetypes`.
> See https://github.com/hrsh7th/vim-vsnip#2-setting

Oh i missing, i also created this `vsnip.lua` file:
```
local g = vim.g
local map = require('utils').map
local cmd = vim.cmd

g.vsnip_filetypes = {
  javascriptreact = { 'javascript' },
  typescriptreact = { 'typescript' },
}

map('n', '<leader>V', ':VsnipOpen<CR>')

cmd [[
  imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
  smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
  imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
  smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
]]

```

**Comment by hrsh7th** [comment]
Could you check filetype? `:echomsg &filetype`

**Comment by hrsh7th** [comment]
And Could the snippet  be expanded with manually?

**Comment by phuongthuan** [comment]
> Could you check filetype? `:echomsg &filetype`

the result is `javascript`



> And Could the snippet be expanded with manually?

What do you mean? I can't get it

**Comment by phuongthuan** [comment]
You mean i have to put all of these lines of code in my setting?: https://github.com/hrsh7th/vim-vsnip#2-setting

**Comment by hrsh7th** [comment]
Can you open the tour snippet file by `:VsnipOpen`?

**Comment by phuongthuan** [comment]
Yep, I can open it. Even when I type `useS` then tab, it shows the snippet that I wrote. but the cmp not suggest

**Comment by hrsh7th** [comment]
Did you install `htsh7th/cmp-vsnip` source?

**Comment by phuongthuan** [comment]
Hi everyone, i solved my problems. Because I did not install the source for `vsnip`.
So please don't forgot to install this one https://github.com/hrsh7th/cmp-vsnip
Thanks for the help.
