### ISSUE TITLE
uuid suggestion 🤷‍♂️

### ISSUE THREAD

**Issue by jbrodriguez** [hrsh7th/nvim-cmp#2062]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
local cmp = require("cmp")
-- local highlight = require("nvim-highlight-colors")

return {
  -- modify borders
  {
    "hrsh7th/nvim-cmp",
    opts = {
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      -- formatting = {
      --   format = highlight.format,
      -- },
    },
  },
}
```
this is my config with lazyvim

### Description

i get a suggestion of uuid which is nowhere near the code logic

### Steps to reproduce

check screenshot
![Screenshot 2024-10-14 at 14 20 23](https://github.com/user-attachments/assets/529e042d-9859-4417-b594-7696c995bd89)

### Expected behavior

no uuid suggestion

### Actual behavior

suggest a random uuid

**Comment by Shougo** [comment]
It is not bug.
It seems just dynamic uuid suggestion is returned.

**Comment by iguanacucumber** [comment]
This suggestion does not come from an LSP, it comes from [friendly-snippets](https://github.com/rafamadriz/friendly-snippets)

**Comment by iguanacucumber** [comment]
to disable them i guess you could make an entry filter

**Comment by jbrodriguez** [comment]
i just disabled the entire friendly-snippets (using lazyvim), wasn't using any of them after all, thanks !
