### ISSUE TITLE
`<Plug>(cmp-autoindent)` being insert into the buffer randomly

### ISSUE THREAD

**Issue by IndianBoy42** [hrsh7th/nvim-cmp#207]
Well its not really random, it happens when autoindent should trigger. it only started happening after updating today. A quick look through the codebase and I think its because of this line:

https://github.com/hrsh7th/nvim-cmp/blob/c2e7736260ffc6e4f863038d06a97e03767d92c6/lua/cmp/core.lua#L235

And this commit

https://github.com/hrsh7th/nvim-cmp/commit/c2e7736260ffc6e4f863038d06a97e03767d92c6

If i am not wrong, `feedkeys(..., 'n', ...)` is equivalent to noremap, ie it doesn't consider any keymaps (even <Plug> maps maybe?). So probably thats why the text is inserted verbatim rather than the command being being run. You probably want `'m'`

**Comment by hrsh7th** [comment]
I've fixed it. Thank you.
