### ISSUE TITLE
additional configuration

### ISSUE THREAD

**Issue by bkyerv** [hrsh7th/nvim-cmp#208]
does it require any additional setup such as inserting 'onAttach property' into setup table when setting up the lsp (e.g. tsserver)? I installed nvim-cmp but skipped snippets and the buffer plugin but it didn't work. are those necessary dependencies?

**Comment by hrsh7th** [comment]
Please your  config

**Comment by dmitmel** [comment]
@bkyerv

> does it require any additional setup such as inserting 'onAttach property' into setup table when setting up the lsp (e.g. tsserver)?

No, the source automatically connects to any buffers to which at least one LS client is attached. No changes to server configurations are necessary.

> I installed nvim-cmp but skipped snippets and the buffer plugin but it didn't work. are those necessary dependencies?

Have you installed cmp-nvim-lsp? But anyway, it would be easier if you post your config.
