### ISSUE TITLE
Can't add Command key(D-/) bindings in MacOS

### ISSUE THREAD

**Issue by OnlyWick** [hrsh7th/nvim-cmp#2080]
That's strange because the mapping was working before. I don't know why it suddenly stopped working.
```lua
cmp.setup({
  mapping = {
    -- open / close
    ["<D-/>"] = cmp.mapping({
      i = function()
        if cmp.visible() then
          cmp.abort()
        else
          cmp.complete()
        end
      end,
      c = function()
        if cmp.visible() then
          cmp.close()
        else
          cmp.complete()
        end
      end,
    }),
  },
})
```

**Comment by Shougo** [comment]
Related issue?

https://github.com/hrsh7th/nvim-cmp/issues/2071

https://github.com/hrsh7th/nvim-cmp/pull/2073

Please test the latest version.

**Comment by OnlyWick** [comment]
Already updated. It suddenly stopped working!!

**Comment by OnlyWick** [comment]
It was working fine before, but now it's not working. I have a habit of updating plugins regularly. Could it be that some plugins have caused this mapping to fail? I used `:checkhealth which-key` but couldn't detect any conflicts related to `D-/`.
