### ISSUE TITLE
"..." instead of completion

### ISSUE THREAD

**Issue by sineptic** [hrsh7th/nvim-cmp#2086]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

init.lua
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "

local function confirm_completion(fallback)
    if require("cmp").visible() then
        require("cmp").confirm({ select = true, behavior = require("cmp").ConfirmBehavior.Insert })
    else
        fallback()
    end
end
local function select_next_item(fallback)
    if require("cmp").visible() then
        require("cmp").select_next_item()
    else
        fallback()
    end
end
local function select_prev_item(fallback)
    local cmp = require("cmp")
    if cmp.visible() then
        cmp.select_prev_item()
    else
        fallback()
    end
end

require("lazy").setup({
    {
        "hrsh7th/nvim-cmp",
        event = "InsertEnter",
        dependencies = {
            "hrsh7th/cmp-nvim-lsp",
        },
        opts = {
            sources = {
                {
                    name = "nvim_lsp",
                    entry_filter = function(entry)
                        return require("cmp.types").lsp.CompletionItemKind[entry:get_kind()] ~= "Text"
                    end,
                },
            },
            mapping = {
                ["<CR>"] = function(fallback)
                    confirm_completion(fallback)
                end,

                ["<Tab>"] = function(fallback)
                    select_next_item(fallback)
                end,
                ["<S-Tab>"] = function(fallback)
                    select_prev_item(fallback)
                end,
            },
        },
    },
    {
        "mrcjkb/rustaceanvim",
        lazy = false,
        setup = true,
    },
})

```

### Description

with rust:

https://github.com/user-attachments/assets/69bc4ed6-88d4-413c-bf54-cc3609a135ef

with python for example(or other):

https://github.com/user-attachments/assets/bb579e43-dfab-463e-b504-81aa885b94cc

### Steps to reproduce

1. copy init.lua that I provided
2. run 
```
nvim -u init.lua main.rs
```
3. wait while rust-analyzed loads(~5 secs)
4. type 
``` rust
fn main() {
    pri // or smth other
}
```
5. select not first completion

### Expected behavior

work as first completion(only brackets, cursor inside, no `...`)

### Actual behavior

`...` inside brackets second brackets after and cursor in them

### Additional context

In my config specified rustaceanvim version = "^4" from start.
This issue happens only few month, not from start 100%.
Issue occurs even on version "^3".
So I think issue in your plugin, not rustaceanvim.

**Comment by hafeoz** [comment]
I had encountered the same issue. After lots of trails and errors I've nailed down to `snippetSupport` LSP capability. Setting
```lua
vim.g.rustaceanvim = {
    server = {
        capabilities = {
            textDocument = {
                completion = {
                    completionItem = {
                        snippetSupport = true
                    }
                }
            }
        }
    }
}
```
solves the issue for me.

A few Google searches lead me to [https://github.com/rust-lang/rust/blob/78bb5ee79e0261e8e47476b631da02acc1cb03ef/src/tools/rust-analyzer/crates/ide-completion/src/render/function.rs#L278](https://github.com/rust-lang/rust/blob/78bb5ee79e0261e8e47476b631da02acc1cb03ef/src/tools/rust-analyzer/crates/ide-completion/src/render/function.rs#L278) where the `…` seems to came from. I'm not familiar with LSP enough to determine whether it's `rust-analyzer`'s problem, `nvim-cmp`'s problem or it's purely a config error though.

**Comment by sineptic** [comment]
Thank you, it works, but now snippets, that may be interpreted like lsp completion

For example `something.ok<CR>` -> `Ok(something)`

**Comment by hafeoz** [comment]
OK after some git bisection I've found hrsh7th/cmp-nvim-lsp@44b16d11215dce86f253ce0c30949813c0a90765 to be the culprit. Overriding these properties one by one reveals `textEdit` to be the offending one.

A quick search then reveals hrsh7th/cmp-nvim-lsp#72 (which has a confusing and unrelated name for those unfamiliar with LSP internals like me...), and using codes from [hrsh7th/cmp-nvim-lsp/72#issuecomment-2425963432](https://github.com/hrsh7th/cmp-nvim-lsp/issues/72#issuecomment-2425963432) solves the issue while allowing snippet completion.

We probably should close this issue as dupe and track the progress on hrsh7th/cmp-nvim-lsp#72?

**Comment by sineptic** [comment]
Issue related to another repo.
