### ISSUE TITLE
highlight first selection

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-cmp#209]
hey @hrsh7th, amazing work this is long way from nvim-comp, well done.

I just start migrating to cmp and I have this issue where the first item is selected when I press enter, but is not highlighted.

<img width="287" alt="Screen Shot 2021-09-16 at 5 36 47 PM" src="https://user-images.githubusercontent.com/65782666/133631902-16610f1b-17b6-47cb-9cee-41de80fca8e8.png">

**Comment by hrsh7th** [comment]
In nvim-cmp, the confirmation/selection is fully customizable.

**Hope to select first candidates automatically when pressing `<CR>`**
You can specify `cmp.mapping.confirm({ select = true })`

**Hope to select first candidates automatically always**
You can specify `cmp.setup { confirmation = { completeopt = 'menu,menuone,noinsert' } }`

**Comment by tami5** [comment]
> I still remember the first issue you submitted on nvim-compe.

❤️ long time (first? 😆) user for your astonishing creation.

> cmp.mapping.confirm({ select = true })
> cmp.setup { confirmation = { completeopt = 'menu,menuone,noinsert' } }

I tried them both and additionally, I added select to completeopt but still it doesn't highlight the selection.

Here's a gif 
![2021-09-16 20 03 00](https://user-images.githubusercontent.com/65782666/133654766-5265e13e-e880-4393-95b6-84a919d52c08.gif)

You see in the gif confirm first item works without issue, but it doesn't highlight it. When I press c-n it get highlighted.

**Comment by hrsh7th** [comment]
You should specify `completeopt = 'menu,menuone,noinsert'`

**Comment by tami5** [comment]
This just weird, still no effect, I'm a bit worried that my issue is miss understood.

Basically, I'm used to having the first item highlighted all time, so that I know when I press enter it will select the highlighted item.

my update config

```lua

M.config = function()
  local cmp = require 'cmp'
  local this = require'user.pack.cmp'
  local c = {
    preselect = true,
    sources = {},
    formatting = { format = this.format },
    confirmation = { completeopt = 'menu,menuone,noinsert' },
  }

  c.mapping = {
    ['<C-k>'] = cmp.mapping.select_prev_item(),
    ['<C-j>'] = cmp.mapping.select_next_item(),
    ['<C-u>'] = cmp.mapping.scroll_docs(-4),
    ['<C-d>'] = cmp.mapping.scroll_docs(4),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = this.confirm,
    ["<Tab>"] = this.tab(),
    ["<S-Tab>"] = this.stab(),
  }

  c.sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
    { name = "buffer" }, -- very annoying sometimes
    { name = "path" },
    { name = "path" },
    { name = "calc" },
    { name = "emoji" } -- load for writing only
  }

  c.documentation = {
    border = "rounded",
    winhighlight = "NormalFloat:CompeDocumentation,FloatBorder:CompeDocumentationBorder",
    max_width = 50,
    min_width = 50,
    max_height = math.floor(vim.o.lines * 0.4),
    min_height = 3,
  }

  c.snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end
  }

  cmp.setup(c)
  user.pack.cmp.autocmds(cmp)
end

```

What I'm experiencing (CR always select which is what I want)
![Screen Shot 2021-09-17 at 11 16 24 AM](https://user-images.githubusercontent.com/65782666/133749097-8d9ccf16-3914-40ef-acdd-03505253b343.png)


What I expect
![Screen Shot 2021-09-17 at 11 16 59 AM](https://user-images.githubusercontent.com/65782666/133749188-6a4b9f68-e26a-431e-9731-d20d84d91104.png)

**Comment by hrsh7th** [comment]
Sorry. I was wrong. You should set the following.

```
cmp.setup {
  completion = {
    completeopt = 'menu,menuone,noinsert'
  }
}
```

**Comment by tami5** [comment]
Nice it worked. Thanks so much @hrsh7th ❤️ . I'll keep experimenting some more and hopefully I get up to speed with cmp soon

**Comment by yueyingjuesha** [comment]
@hrsh7th Your solution seems doesn't work with status line completion. It indeed displaying the first item auto-selected, but when you press  <CR>, the input you actually type in is executed, not completed entry

**Comment by cwqt** [comment]
I'm still experiencing this issue even with the suggested addition of `completeopt = "menuone,noinsert,noselect"` using 913eb8599816b0b71fe959693080917d8063b26a neovim v0.7.0, config at: https://gitlab.com/cxss/dotfiles/-/tree/main/nvim

https://user-images.githubusercontent.com/61694629/189383842-caedb5bc-04c7-4a1f-a0eb-327cb7b89ccb.mov

**Comment by tuanbass** [comment]
> @hrsh7th Your solution seems doesn't work with status line completion. It indeed displays the first item auto-selected, but when you press CR , the input you actually type in is executed, not completed entry

Did you have solution for this? I also experienced the same problem, and not  found yet a solution for this.

**Comment by hrsh7th** [comment]
I'm surprised no one has created a new issue and doesn't include steps to reproduce it.

In nvim-cmp, mapping is user-configured.
My guess is that the following settings seem to work. (I'm probably not understanding the correct requirements.)

```lua
['<CR>'] = cmp.mapping(cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Insert }), { 'i', 'c' })
```
