### ISSUE TITLE
how to turn off this?

### ISSUE THREAD

**Issue by xrhahelry** [hrsh7th/nvim-cmp#2090]
![image](https://github.com/user-attachments/assets/05a6fa05-a913-4459-affb-658c073e8420)

I don't want that function description to pop up automatically if i want to look at it i will explicitly do "K" on the function name

**Comment by Dan7h3x** [comment]
Do you have noice.nvim installed?

check throug 'lsp_signature' of that plugin or smthg like that

**Comment by xrhahelry** [comment]
> Do you have noice.nvim installed?
> 
> check throug 'lsp_signature' of that plugin or smthg like that

Thank you it really was because of noice 

```
require("noice").setup({
	lsp = {
		signature = {
			auto_open = {
				trigger = false,
			},
		},
	},
})
```
this solved the issue
