### ISSUE TITLE
Dot for R language

### ISSUE THREAD

**Issue by shaman-yellow** [hrsh7th/nvim-cmp#2095]
In R, "." is not considered a symbol for calling a member function like in other languages. I want cmp to consider "." as a normal character instead of a breaking character when I input it in R. Is this possible?

**Comment by hrsh7th** [comment]
1. You can change the `keyword_pattern` for R language.

```lua
cmp.setup.filetype('R', {
  completion = {
    keyword_pattern = '...'
  }
})
```

2. If `R` language server returns `trigger_characters` as `.`, you can remove it.

```lua
cmp.setup.filetype('R', {
  completion = {
    get_trigger_characters = function(chars)
      return vim.iter(chars):filter(function(char)
        return char ~= '.'
      end):totable()
    end
  }
})
```

**Comment by shaman-yellow** [comment]
I setup as following:
```lua
cmp.setup.filetype('R', {
  completion = {
    keyword_pattern = '...',
    get_trigger_characters = function(chars)
      return vim.iter(chars):filter(function(char)
        return char ~= '.'
      end):totable()
    end
  }
})
```

But in R，

```R
var.postfix
var.
```

When I type `var.`, cmp can not trigger completion. When type `var.post`, no candidates of `var.postfix`.

**Comment by shaman-yellow** [comment]
The following work fine.

```lua
cmp.setup.filetype({'r', 'rmd'}, {
  sources = {
    name = 'buffer',
    option = { keyword_pattern = "\\k\\+" },
  }
})
```
