### ISSUE TITLE
Inconsistent behavior with rust-analyzer

### ISSUE THREAD

**Issue by DrakulaD3a** [hrsh7th/nvim-cmp#2106]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'

require"mason".setup()
require"mason-lspconfig".setup({
  ensure_installed = { "rust_analyzer" },
})
require"mason-lspconfig".setup_handlers({
  function(server)
    require"lspconfig"[server].setup({
      capabilities = require"cmp_nvim_lsp".default_capabilities(capabilities),
    })
  end,
})
```

### Description

When using nvim-cmp with rust-analyzer, showed completions are different from the completions, that actually get inserted. This happens only with rust-analyzer, no other lsp that I used.

### Steps to reproduce

Just use the completion with the provided config

### Expected behavior

Normal completion

### Actual behavior

Completion of seemingly unrelated items

### Additional context

With my config:

https://github.com/user-attachments/assets/1b2bb7fa-dacd-451f-a3c1-6ff888891a0f

With minimal config:

https://github.com/user-attachments/assets/29e15051-20fe-420b-bfd3-beca462fe052

**Comment by hejops** [comment]
I've noticed this as well. Another way to trigger this odd behaviour is to type something like `'x'.` and select `to_owned()`. This completes `partial_cmp` on my system.

In comparison, Python (Pyright) and Go (gopls) are unaffected.

**Comment by hejops** [comment]
FWIW, updating `rust-analyzer` to `2024-12-02` resolved my issue.

**Comment by kyoryo** [comment]
I still got this issue even after updating rust-analyzer to mentioned version above.
![image](https://github.com/user-attachments/assets/8a8c00d2-e00d-43a9-ac5f-617abb5167de)

**Comment by hejops** [comment]
I did not, unfortunately.

**Comment by kyoryo** [comment]
It's the analyzer problem, not cmp I think. https://github.com/rust-lang/rust-analyzer/issues/18547

**Comment by hrsh7th** [comment]
IMO, this bug is solved by IMO, current `cmp-nvim-lsp` has no this problem by https://github.com/hrsh7th/cmp-nvim-lsp/pull/77 .

Could you update `cmp-nvim-lsp`?

**Comment by hrsh7th** [comment]
Oh, sorry. I guess I misunderstood. It looks like we need to fix rust-analyzer, so please wait.
