### ISSUE TITLE
It looks like there are suggestions shown in the popup that "shadow" other suggestions

### ISSUE THREAD

**Issue by svanharmelen** [hrsh7th/nvim-cmp#2109]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'mrcjkb/rustaceanvim'  "<-- this is the only thing I added to the provided minimal config
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

It somehow looks like there are suggestions shown in the popup that "shadow" other suggestions.

Please have a look at the screen-capture below and notice that as I'm moving down through the suggestions, the first 3 items seem consistent and remain the same when I move to the next item. But after that, when I move to the next item the previous item suddenly changes!

In addition please notice that when I reach the last item (`size_of_val(...)`) and then press `<CR>` to select the suggestion, it actually inserts what seems to be a snippet instead of the `size_of_val(..)` method I thought I was selecting:

![Kapture 2024-12-07 at 17 07 22](https://github.com/user-attachments/assets/9b3baa68-8db6-4743-bd96-0eb2d6d714e6)

So it looks like the list of suggestions is not actually showing the items in the list, as when I try to select an item it actually selects the item that was hidden "underneath" the item that was shown.

### Steps to reproduce

- Use the provided minimal config
- Create a new Rust project
- Open `src/main.rs` and type `So` or anything else that will give you a list of suggestions
- Traverse through the list and watch magic happen ;)

### Expected behavior

I expect that the items in the list stay consistent and that when I select an item it actually selects the item that I can see.

### Actual behavior

Please see the screen-capture... Some items change when moving over them and selecting an item may insert a different item.

**Comment by kyoryo** [comment]
same issue as #2106

**Comment by svanharmelen** [comment]
I managed to "solve" this by doing `brew uninstall rust-analyzer` and then `rustup component add rust-analyzer` This gave me an older version which didn't give me any issues. So its clearly an issue with `rust-analyzer` and not with `nvim-cmp`.
