### ISSUE TITLE
Latex: Inserting `{` instead of `(` when completing functions

### ISSUE THREAD

**Issue by Joakker** [hrsh7th/nvim-cmp#211]
Is there a way to do this? It's rather annoying having to replace `()` manually every time a function is inserted.

**Comment by hrsh7th** [comment]
I don't familiar with latex so I can't understand what you mean.

**Comment by rhcher** [comment]
Are you using nvim-autopairs plugin?

**Comment by hrsh7th** [comment]
And I think nvim-cmp does not provides `{` and `(` so I think it is not related to nvim-cmp.

**Comment by xeluxee** [comment]
I don't think this is related to nvim-cmp
See this https://github.com/LunarVim/LunarVim/issues/1257

**Comment by Joakker** [comment]
Oh ok, ok. Sorry 😅

**Comment by xeluxee** [comment]
See https://github.com/windwp/nvim-autopairs#mapping-cr, expand `nvim-cmp` section and copy the setup function.

I think you can close this issue now
