### ISSUE TITLE
cmp with emmet-ls not working properly?

### ISSUE THREAD

**Issue by bragjo** [hrsh7th/nvim-cmp#212]
Hi,

When using cmp in conjunction with emmet-ls I'm struggling to get it to work properly.

For example when typing div.container it should pop up as an LSP suggestion like this:

![image](https://user-images.githubusercontent.com/17138968/133649085-5f1eb8d0-993a-4b84-8bac-48eb262d0095.png)

This only works when typing div.container> see:

![image](https://user-images.githubusercontent.com/17138968/133649539-292b1dc5-901f-4d9d-a14c-3dcd7ea6b308.png)

 and then removing the ">" via backspace. I assume this is a cmp issue? Others on discord have reported that they are facing the same issue. Especially with html.

This is the result by just typing div.container (without the > and then deleting it):

![image](https://user-images.githubusercontent.com/17138968/133649371-7484e14e-967c-40db-9130-8f46532401f6.png)

No suggestion as u see.

Please help.

**Comment by hrsh7th** [comment]
Other language server works fine so it's servres problem.
