### ISSUE TITLE
Getting error will any sources loading from packer.vim

### ISSUE THREAD

**Issue by boydkelly** [hrsh7th/nvim-cmp#216]
Hi,  Just attempting to try this out but getting this error starting nvim:

Error detected while processing /var/home/bkelly/.local/share/nvim/site/pack/packer/start/cmp-nvim-ultisnips/after/plugin/cmp_nvim_ultisnips.lua:
E5113: Error while calling lua chunk: ...t/cmp-nvim-ultisnips/after/plugin/cmp_nvim_ultisnips.lua:1: attempt to call field 'register_source' (a nil
 value)

I'm getting this with any sources in my packer.lua config below,  I am using the nightly on Fedora 35.  Since this is comming from packer loading the source... Is there something I am missing in the config?   Thanks for any insight.

` root  toolbox  ~  #  nvim --version
NVIM v0.6.0-dev+274-g6188926e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
`

`  use {
    "hrsh7th/nvim-cmp",
    requires = {
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-nvim-lsp",
      "quangnguyen30192/cmp-nvim-ultisnips"
  }`

**Comment by hrsh7th** [comment]
I don't familiar woth packer butcI think each source requires nvim-cmp.

**Comment by dmitmel** [comment]
The `requires` key specifies dependency or library plugins needed for the plugin to work, so in your config you are saying that for nvim-cmp to work, cmp-buffer, cmp-nvim-lsp and so on must be installed and loaded, while in fact it is the reverse - nvim-cmp needs to be loaded first and is a dependency of all of your sources. I stopped using packer, but if my memory serves me right, this should work:

```lua
use { "hrsh7th/nvim-cmp" }
use { "hrsh7th/cmp-buffer", requires = { "hrsh7th/nvim-cmp" } }
use { "hrsh7th/cmp-nvim-lsp", requires = { "hrsh7th/nvim-cmp" } }
use { "quangnguyen30192/cmp-nvim-ultisnips", requires = { "hrsh7th/nvim-cmp" } }
```

**Comment by boydkelly** [comment]
Strange...   I tried with this (with and without requires:

`  use { "hrsh7th/nvim-cmp" }
use { "hrsh7th/cmp-buffer" }
  use { "hrsh7th/cmp-nvim-lsp", requires = { "hrsh7th/nvim-cmp" } }
  use { "quangnguyen30192/cmp-nvim-ultisnips", requires = { "hrsh7th/nvim-cmp" } }`

But I get this on startup (no error for cmp-nvim-lsp but errors for cmp-buffer and utlisnips!
`
E5113: Error while calling lua chunk: /var/home/bkelly/.config/nvim/lua/nvim-cmp.lua:18: attempt to index field 'mapping' (a nil value)
Error detected while processing /var/home/bkelly/.local/share/nvim/site/pack/packer/start/cmp-nvim-ultisnips/after/plugin/cmp_nvim_ultisnips.lua:
E5113: Error while calling lua chunk: ...t/cmp-nvim-ultisnips/after/plugin/cmp_nvim_ultisnips.lua:1: attempt to call field 'register_source' (a nil
 value)
Error detected while processing /var/home/bkelly/.local/share/nvim/site/pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/cmp-buffer/after/plugin/cmp_buffer.lua:1: attempt to call field 'register_source' (a nil
 value)
`
Not sure if that is all related but 
And line 17/18 of that  file is (right from the sample setup...)

`      mapping = {
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),`

**Comment by hrsh7th** [comment]
@boydkelly Are you using lazy feature?

**Comment by captainko** [comment]
@boydkelly, try these instead.

```lua
  use {
    "hrsh7th/nvim-cmp",
    event = "InsertEnter", -- for lazyload
    requires = {
      { "hrsh7th/cmp-nvim-lsp", after = "nvim-cmp" },
      { "f3fora/cmp-spell", after = "nvim-cmp" },
      { "hrsh7th/cmp-path", after = "nvim-cmp" },
      { "hrsh7th/cmp-buffer", after = "nvim-cmp" },
      { "hrsh7th/cmp-calc", after = "nvim-cmp" },
      { "quangnguyen30192/cmp-nvim-ultisnips", after = "nvim-cmp" },
    },
    config = config "cmp",
  }

```

**Comment by boydkelly** [comment]
Wasn't using lazy load, but I did get it sorted out.   Not sure what the issue was but its working now.   Sorry for the noise...  And thanks for the suggestions.
