### ISSUE TITLE
Conflict with vim-vsnip: snippet placeholders containing a trigger character of a source will try to trigger the completion menu in Select mode, but only if there is another source with an asynchronous `execute` method

### ISSUE THREAD

**Issue by dmitmel** [hrsh7th/nvim-cmp#217]
I discovered this bug while using the cmp-nvim-lua together with cmp-nvim-lsp, vim-vsnip and sumneko's Lua language server. You see, the server has an option `Lua.completion.callSnippet` that makes completion return snippets for function calls which generally look like this:

```
gsub(${1:s: string}, ${2:pattern: string}, ${3:repl: string|table|function}, ${4:n: number})
```

Which works great with nvim-cmp and vim-vsnip, however, if I try to complete a function such as `print` (and this is important because not every function causes the bug), I get the following error:

```
Error executing vim.schedule lua callback: Vim:E785: complete() can only be used in Insert mode
```

<details>
<summary>Error with the stack trace</summary>

```
Error executing vim.schedule lua callback: /home/dmitmel/dotfiles/nvim/lua/dotfiles/global_utils.lua:7: Vim:E785: complete() can only be used in Insert mode
stack traceback:
        [C]: in function 'complete'
        ...e/dmitmel/.config/nvim/plugged/nvim-cmp/lua/cmp/menu.lua:169: in function 'show'
        ...e/dmitmel/.config/nvim/plugged/nvim-cmp/lua/cmp/menu.lua:139: in function 'update'
        ...e/dmitmel/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:285: in function 'fn'
        ...el/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:35: in function 'cb'
        vim.lua:277: in function <vim.lua:277>
        [C]: in function 'xpcall'
        /home/dmitmel/dotfiles/nvim/lua/dotfiles/global_utils.lua:7: in function </home/dmitmel/dotfiles/nvim/lua/dotfiles/global_utils.lua:6>
```

The code snippet I used for debugging:

```lua
local old_schedule = vim.schedule
function vim.schedule(callback)
  return old_schedule(function(...)
    assert(xpcall(callback, debug.traceback, ...))
  end)
end
```

</details>

Upon closer inspection I found that, obviously, the error originates from nvim-cmp, and began investigating. By disabling my installed plugins I found that I get the error only when I have cmp-nvim-lua and cmp-nvim-lsp enabled together. I came up with the following minimal vimrc:

<details>

```vim
call plug#begin(stdpath('config').'/plugged')
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-nvim-lua'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set completeopt=menu,menuone,noselect

lua <<EOF
  local cmp = require('cmp')

  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<CR>'] = cmp.mapping.confirm(),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'nvim_lua' },
    }
  })

  require('lspconfig').sumneko_lua.setup({
    cpabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
    cmd = {
      -- ...
    },
    settings = {
      Lua = {
        completion = {
          callSnippet = 'Replace',
        },
      },
    },
  })
EOF
```

</details>

I tried dumping the completion items that the Lua Language Server returns and quickly discovered that the distinction is that the items which cause the error have a `command` attached to them. The Server returns a `command` for every function completion which executes `editor.action.triggerParameterHints`. Now, because I realize that reproduction involves using 5 unrelated pieces of software, I wrote an even more minimal reproduction vimrc by observing what code paths get taken in the LSP source:

```vim
call plug#begin(stdpath('config').'/plugged')
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/vim-vsnip'
call plug#end()

set completeopt=menu,menuone,noselect

lua <<EOF

local cmp = require('cmp')

cmp.register_source('fake_nvim_lsp', {
  complete = function(self, params, callback)
    callback({
      items = {
        {
          detail = 'function',
          insertText = 'print(${1:...})',
          insertTextFormat = cmp.lsp.InsertTextFormat.Snippet,
          kind = cmp.lsp.CompletionItemKind.Snippet,
          label = 'print(...)',
          sortText = '0002',
        },
      },
    })
  end,
  execute = function(self, item, callback)
    vim.schedule(callback)
  end,
})

cmp.register_source('fake_nvim_lua', {
  get_trigger_characters = function()
    return { '.' }
  end,
  complete = function(self, request, callback)
    callback({
      items = {
        {
          detail = 'boolean',
          kind = cmp.lsp.CompletionItemKind.Value,
          label = 'hi',
        },
      },
    })
  end,
})

cmp.setup({
  snippet = {
    expand = function(args)
      vim.call('vsnip#anonymous', args.body)
    end,
  },
  mapping = {
    ['<C-Space>'] = cmp.mapping.complete();
    ['<CR>'] = cmp.mapping.confirm();
    ['<C-y>'] = cmp.mapping.confirm();
    ['<C-e>'] = cmp.mapping.close();
    ['<Esc>'] = cmp.mapping.close();
  },
  sources = {
    { name = 'fake_nvim_lsp' },
    { name = 'fake_nvim_lua' },
  }
})

EOF
```

To reproduce you must run `nvim -u minimal_init.vim test.lua`, open the completion menu and autocomplete the `print` function.

And so I found the exact set of circumstances which cause an exception to be thrown from `vim.fn.complete`:

1. There must be a source which has an asynchronous `execute` method. cmp-nvim-lsp does this to execute completion item commands. If you replace the `execute` in the `fake_nvim_lsp` source above with
   ```lua
   execute = function(self, item, callback)
     callback()
   end
   ```
   The whole setup will work just fine.
2. There must be another source which always returns some results AND has a list of trigger characters. cmp-nvim-lua qualifies both criteria, which is why I was having troubles with it.
3. You also must have vim-vsnip installed. Tried with LuaSnip - no error (not sure about the other snippet plugins, haven't tried).
4. Finally, the first source must return a snippet completion item which has a placeholder with one of the trigger characters of the second source. Remember how I said that it would happen with `print` and not other functions? That is because for `print` the Language Server returns the following snippet:
   ```
   print(${1:...})
   ```
   ...so this would only result in an error only with vararg functions. To verify that this trigger characters are responsible you can try changing the trigger_characters list of the fake_nvim_lua source to, say, `!`, and the snippet returned by `fake_nvim_lsp` to `print(${1:!!!})`.

It is also important that a trigger character must be before the cursor, so `print(${1:a.})` and `print(${1:.})` will expand successfully, but `print(${1:.a})` will fail. My assumption is that nvim-cmp thinks that a character has been typed, while in reality it was vim-vsnip responsible for inserting that text.

I am also not sure where to report this. The bug doesn't happen with LuaSnip, but also most of the code responsible is related to nvim-cmp.

**Comment by hrsh7th** [comment]
It's perfect issue report. I respect you.

Probably, we should wrap callback with `vim.schedule`.

**Comment by dmitmel** [comment]
> Probably, we should wrap callback with `vim.schedule`.

Why? Was this causing other problems?

**Comment by hrsh7th** [comment]
nvim-cmp will call `cmp.complete ()` again after confirmation. (It's useful if you are using a css language server etc).

However, when the confirmation is finished, vim may be in select-mode, so we should check it.

**Comment by dmitmel** [comment]
Works perfectly now, thank you!
