### ISSUE TITLE
Can't complete some items from cmp-emoji

### ISSUE THREAD

**Issue by spindensity** [hrsh7th/nvim-cmp#218]
# Description

Some items from [hrsh7th/cmp-emoji](https://github.com/hrsh7th/cmp-emoji) source could not be completed by inputting the characters of the completing text.

# Steps to reproduce

1. Use [hrsh7th/cmp-emoji](https://github.com/hrsh7th/cmp-emoji) source, press <kbd>:</kbd>, the completing menu pops up, now try to complete the `👍` emoji:
![Snipaste_2021-09-18_00-21-41](https://user-images.githubusercontent.com/33576822/133822166-be25aa0b-5290-41d1-826d-38a56a1b3ba5.png)
2. Input the character <kbd>+</kbd> since the text of `👍` in the completing menu is `:+1:`;
3. The completing menu disappears.

# Expected behavior

We could complete the item as usual.

# Actual behavior

The completing menu disappears,, the only way to complete the item is  scrolling and selecting it.

**Comment by dmitmel** [comment]
The fix is simple enough:

```diff
diff --git a/lua/cmp_emoji/init.lua b/lua/cmp_emoji/init.lua
index b35a6d0..aff2499 100644
--- a/lua/cmp_emoji/init.lua
+++ b/lua/cmp_emoji/init.lua
@@ -11,7 +11,7 @@ source.get_trigger_characters = function()
 end
 
 source.get_keyword_pattern = function()
-  return [[\%(\s\|^\)\zs:\w*:\?]]
+  return [[\%(\s\|^\)\zs:[0-9A-Za-z_+\-]*:\?]]
 end
 
 source.complete = function(self, request, callback)
@@ -28,4 +28,3 @@ source.complete = function(self, request, callback)
 end
 
 return source
-
```

**Comment by hrsh7th** [comment]
@dmitmel Thank you. It's correct solution.
I've fixed it.

**Comment by spindensity** [comment]
Thanks for the quick fix!
