### ISSUE TITLE
/path/lua/cmp/entry.lua:53: attempt to index field 'completion_item' (a userdata value)

### ISSUE THREAD

**Issue by duydang2311** [hrsh7th/nvim-cmp#219]
First of all, thank you for this great plugin.
I have an nvim-cmp setup for css, svelte, ts, omnisharp but svelte is the one that has this kind of issue.
In detail, the issue only happens when I write HTML code in svelte, but not for CSS and TS code as you can see below.
![image](https://user-images.githubusercontent.com/34796192/133882344-67f0072f-5cef-4a14-b06e-90d37a7465a2.png)
![image](https://user-images.githubusercontent.com/34796192/133882426-d88adea7-ff3a-4896-a623-42d77412ac31.png)

Having tried `nvim-completion` but still geting the same issue, very likely a problem of the svelte language server. I might be stupid to make an issue here but I hope you can investigate into this or tell me to make an issue somewhere else.

**Comment by hrsh7th** [comment]
Thank you. It's interesting. I willll investigate it. Is it caused only by svelte?

**Comment by hrsh7th** [comment]
@duydang2311 I don't familiar with svelte. How to reproduce it? (I installed svelte-language-server now)

**Comment by duydang2311** [comment]
Thanks for the fast reply!
I can say that, only Svelte is causing the issue for me, at least for now.
Here's the reproduction steps:
1. Setup a svelte-ts project and run `node scripts/setupTypeScript.js` in order to make svelte support typescript.
```js
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
node scripts/setupTypeScript.js
npm install
```
or you can always have a look at original Svelte's tutorial [here](https://svelte.dev/blog/the-easiest-way-to-get-started).

2. Setup svelte lsp with the following configuration:
```lua
require'lspconfig'.setup {
	cmd = { "svelteserver.cmd", "--stdio" }, -- remove ".cmd" if you're not on Windows
	flags = {
		debounce_text_changes = 150,
	}
}
```

3. Open your `App.svelte` and type some HTML tags.

Hopefully you can reproduce this.

**Comment by hrsh7th** [comment]
Hm... Sorry. I can't reproduce it.
Could you add `print(vim.inspect(response))` in `source.lua:L312` ?

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/133894767-dc3865a0-a2c1-476e-826a-0c6d318d5484.mp4

**Comment by duydang2311** [comment]
Here is a part of the messages when I add the `print`.
Input: `<`
Output:
```
...
    }, {
      documentation = {
        kind = "markdown",
        value = "The template element is used to declare fragments of HTML that can be cloned and inserted in the document by script.\n\n[MDN Reference](https://developer.mozilla.org/docs/Web/HTML/Element/template)"
      },
      insertTextFormat = 1,
      kind = 10,
      label = 'template (lang="pug")',
      textEdit = {
        newText = 'template lang="pug"',
        range = {
          end = {
            character = 1,
            line = 0
          },
          start = {
            character = 1,
            line = 0
          }
        }
      }
    }, vim.NIL }
}
Error executing vim.schedule lua callback: C:\Users\duyda\.vim\plugged\nvim-cmp\lua\cmp\entry.lua:53: attempt to index field 'completion_item' (a userdata value)
Error executing vim.schedule lua callback: C:\Users\duyda\.vim\plugged\nvim-cmp\lua\cmp\entry.lua:53: attempt to index field 'completion_item' (a userdata value)
```

I didn't provide my `nvim-cmp` configuration for you because mine is pretty much as same as the one in README but in case it might be useful:
```lua
require'cmp'.setup {
	preselect = cmp.PreselectMode.Item,
	completion = {
		completeopt = 'menuone,noselect,preview'
	},
	snippet = {
		expand = function(args)
			vim.fn['vsnip#anonymous'](args.body)
		end,
	},
	mapping = {
		['<C-p>'] = cmp.mapping.select_prev_item(),
		['<C-n>'] = cmp.mapping.select_next_item(),
		['<C-Space>'] = cmp.mapping.complete(),
		['<C-e>'] = cmp.mapping.close(),
		['<C-y>'] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Replace,
			select = true,
		})
	},
	sources = {
		{ name = 'nvim_lsp' }
	},
	formatting = {
		format = function(entry, vim_item)
			vim_item.kind = require('lspkind').presets.default[vim_item.kind] .. ' ' .. vim_item.kind
			vim_item.menu = ({
				nvim_lsp = '[LSP]',
				path = '[Path]',
			})[entry.source.name]
			return vim_item
		end,
	},
}
```

**Comment by hrsh7th** [comment]
Wow. The LSP server returns `{ completion_item, completion_item, nil }`...

OK. I will filter out it.
