### ISSUE TITLE
mapping <cr> to cmp.mapping.confirm doesn't correctly fallback

### ISSUE THREAD

**Issue by figsoda** [hrsh7th/nvim-cmp#220]
Pretty sure https://github.com/hrsh7th/nvim-cmp/commit/1cec1ecb31879ba4cf719d1d22cae628d8108f1c broke it for me
[my config](https://github.com/figsoda/dotfiles/blob/0ff2e9de4cc7aabe78475127becefed2c970bda1/lib/nvim/init.lua#L92-L116):
```lua
cmp.setup({
  confirmation = { default_behavior = cmp.ConfirmBehavior.Replace },
  formatting = {
    format = function(_, item)
      item.kind = lspkind.presets.default[item.kind]
      return item
    end,
  },
  mapping = {
    ["<cr>"] = cmp.mapping.confirm(),
    ["<m-cr>"] = cmp.mapping.confirm({ select = true }),
  },
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  sources = {
    { name = "buffer" },
    { name = "crates" },
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "path" },
  },
})
```
My other `<cr>` mapping is set [here](https://github.com/figsoda/dotfiles/blob/0ff2e9de4cc7aabe78475127becefed2c970bda1/lib/nvim/autopairs.lua#L108-L110) which automatically indents when pressing `<cr>` inside a pair, but it stops working when `["<cr>"] = cmp.mapping.confirm(),` is set

**Comment by hrsh7th** [comment]
In my environment, The fallback works perfectly.

https://user-images.githubusercontent.com/629908/133894676-3ef3c2b5-92b1-40a6-9720-76b06fae79dd.mp4

**Comment by figsoda** [comment]
i tried a minimal config
```vim
inoremap <cr> a<cr>
lua <<END
require("cmp").setup {
  mapping = { ["<cr>"] = require("cmp").mapping.confirm() },
  sources = { { name = "buffer" } },
}
END
```
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
```

**Comment by hrsh7th** [comment]
Hm... I've understood the `<cr>` should be `<CR>` for the problem...

I will investigate if we can improve it.

**Comment by figsoda** [comment]
fixes the issue for me, thank you, that was really quick

**Comment by McAuleyPenney** [comment]
After updating, tab completion is broken. I am trying to find out why right now
