### ISSUE TITLE
mapping keycodes with lowercase characters (e.g. `<Tab>`) is broken

### ISSUE THREAD

**Issue by goolord** [hrsh7th/nvim-cmp#221]
as of commit https://github.com/hrsh7th/nvim-cmp/commit/7c8876330df6e11cf91ca42ab6e52f37d81cc003 mapping
```lua
mapping = {
  ...
  ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })
  ...
}
```
no longer works

**Comment by saadparwaiz1** [comment]
it's this [line](https://github.com/hrsh7th/nvim-cmp/blob/7c8876330df6e11cf91ca42ab6e52f37d81cc003/lua/cmp/utils/keymap.lua#L124) specfically that broke the Tab mapping

**Comment by entropitor** [comment]
@saadparwaiz1 Thanks, easy fix in your config, capitalize the TAB:

```lua
mapping = {
  ...
  ['<TAB>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })
  ...
}
```

**Comment by huyiqun** [comment]
Confirm `<C-j>` and `<C-k>` also broken with

```
mapping = {
  ...
  ['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })
  ['<C-k>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' })
  ...
}
```

**Comment by lourenci** [comment]
`<C-Space>` is also broken. =/

**Comment by goolord** [comment]
presumably the hotfix of using all caps in the keycode will work for all of these as well

**Comment by hrsh7th** [comment]
Sorry. I was adding the bug. I've fixed it.
