### ISSUE TITLE
Can we have `experimental.ghost_text=true` and `completiong.auto_complete=false` together?

### ISSUE THREAD

**Issue by IndianBoy42** [hrsh7th/nvim-cmp#223]
Basically I want to have the ghost_text completion without the PUM by default. and then bind `<c-space>` to get the pum when I need it

**Comment by hrsh7th** [comment]
I have no plan to add it. Sorry.

**Comment by hrsh7th** [comment]
The ddc.vim has an option for your expects.

**Comment by Shougo** [comment]
Yes.  If you want to test the feature, please read ddc.vim documentation.

**Comment by IndianBoy42** [comment]
I don't really want to switch completion plugins just for this, If I can get a PR for this would you consider it?
