### ISSUE TITLE
Cursor moves to the beginning of word.

### ISSUE THREAD

**Issue by CantoroMC** [hrsh7th/nvim-cmp#227]
When i complete certain word, such as end in lua or \item in latex, the cursor is moved to the beginning of the word.
This won't happen if i remove nvim-cmp and use builtin completion, anyway, I'm not 100% sure that this is not due interaction with other setting, but I'm pretty confident.
Anyone experience the same issue?
How to avoid it?

**Comment by hrsh7th** [comment]
Please minimsl repro steps.

**Comment by CantoroMC** [comment]
I have discovered what is the cause of this behaviour, i have `set startofline`, probably nvim-cmp internally call one of the command/keycode listed in `:h startofline`.
Removing it fix the issue and also I have vim-endwise, now its behaviour is much better.

You probably would like to take a look at this or maybe inform other users.
Thanks
