### ISSUE TITLE
<C-space> adds a space in insert mode

### ISSUE THREAD

**Issue by marwan38** [hrsh7th/nvim-cmp#230]
Hi,

Not sure if this belongs here, but, I didn't know where else to ask. I've consulted the neovim documentation but can't find anything on it.

`cmp.mapping.complete()` is set to `<C-space>` in the `cmp.setup{}` mapping. The issue is that `<C-space>` adds a space in insert mode, so I always have to delete the char to get back to what I was doing. Is there a way around this? Is this something in my config that might cause this?

Thank you

**Comment by hrsh7th** [comment]
Please minimal repro syeps. I can't reproduce it.

**Comment by marwan38** [comment]
This only happens with alacritty, using windows powershell does not reproduce this issue.

Alacritty:
```
showkey -a
              32 0040 0x20
```

Powershell:
```
showkey -a
^@        0 0000 0x00
```

Must be the terminal not sending through ctrl properly. Closing issue.

**Comment by hrsh7th** [comment]
Oh. I didn't know it. Thank you! (I can't fix it maybe. Sorry!)

**Comment by marwan38** [comment]
@hrsh7th Not you at all, thank you for being so supportive, regardless. I have found the solution if anyone stumbles upon this looking for a fix.

Using alacritty on WSL2, and this is the fix:
```
key_bindings:
- { key: Space, mods: Control, chars: "\x00" }
```
