### ISSUE TITLE
Sometimes HLS (haskell language server) completion suggestions do not appear.

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-cmp#232]
As shown in this video, when I type `vi`, no suggestions appear, but when I type `vid`, suggestions appear, and when I type `vo`, suggestions appear even for the second letter.

![cmp](https://user-images.githubusercontent.com/82267684/134209352-bf943c94-8993-4899-80e6-f162ab7808e7.gif)

**Comment by hrsh7th** [comment]
Hm... I can't reproduce it.

https://user-images.githubusercontent.com/629908/134215955-b4e1ddda-21a9-4de9-8d63-862684b3da7b.mp4

**Comment by hrsh7th** [comment]
Ah. I have to type `vi` instead of `vo`

**Comment by hrsh7th** [comment]
I found the cause.
The haskell-language-server returns a lot of completion response to `vi`. (this response does not contains the `void` candidates).

**Comment by hrsh7th** [comment]
Probably, it has a side-effect but I could improve it in my local environment.
I will push it.
