### ISSUE TITLE
Cursor moves one letter left when I type else and end

### ISSUE THREAD

**Issue by NiYanhhhhh** [hrsh7th/nvim-cmp#233]
Screenshot:
![Peek 2021-09-22 01-36](https://user-images.githubusercontent.com/55988662/134220156-69122eae-e196-4c79-ae1c-aebaa1f9b151.gif)
When I typed word which will backspace the indent, the cursor will move a letter left... Strange.

**Comment by hrsh7th** [comment]
Sorry. I had tested with `set virtualtext=all`.

**Comment by NiYanhhhhh** [comment]
Thanks, all goes well!

**Comment by arathunku** [comment]
I just wanted to say, thank you @hrsh7th for fixing it and over all this package. I also had this problem.
