### ISSUE TITLE
Configurable throttle

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-cmp#234]
Hi,

I noticed that throttle time configuration is hardcoded in the core.
Is there any reason why that's not exposed through configuration? I would like to play with it and see if bigger values would work for me.

**Comment by hrsh7th** [comment]
I didn't expose the throttle time anymore. the reason is that I can't think it is convenient.
If you met the perf improvements by modifying it, I can expose it.

(I think it is better to have as few configurable settings as possible.

**Comment by kristijanhusak** [comment]
I'm not sure if it will help for perf improvements. I'll give it a try by changing it directly and let you know if it helped or not. Thanks.

**Comment by kristijanhusak** [comment]
I gave it a try for couple of hours with different throttle (bigger one), but didn't notice any perf improvements. We can close this. Thanks.
