### ISSUE TITLE
Autoloading

### ISSUE THREAD

**Issue by SevereOverfl0w** [hrsh7th/nvim-cmp#238]
For authors of completion engines, it would be useful to support detection of when cmp is loaded.  This allows for plugins which may not be used alongside cmp always to not have to do a slow conditional load of cmp.  Alternatively, you could automatically load sources by name using a special path.

Ncm2 solves this by problem by using an autocommand: https://github.com/ncm2/ncm2/blob/master/doc/ncm2.txt#L505-L512

**Comment by hrsh7th** [comment]
OK.  I will add it. Thanks!

**Comment by hrsh7th** [comment]
I've added the `cmp#ready` autocmd.
