### ISSUE TITLE
i_CTRL-N does not work

### ISSUE THREAD

**Issue by lourenci** [hrsh7th/nvim-cmp#239]
`:help i_CTRL-N` is not working when some completions appear, I've to either exit the insert mode and enter again or press `ctrl-e` twice.

To simulate:
* Force the completions with `cmp.mapping.complete`.
* Close the menu with `cmp.mapping.close`.
* Try to use `i_CTRL-N`.

**Comment by uga-rosa** [comment]
Isn't it just that there is no match in keyword completion?

**Comment by lourenci** [comment]
Isn’t. If I `close` twice, I’m able to get the i_CTRL-n completion options.  You can try in a buffer with some text on it…

**Comment by lourenci** [comment]
It worked like a charm. Tks.
