### ISSUE TITLE
vsnip does not work with lsp

### ISSUE THREAD

**Issue by lourenci** [hrsh7th/nvim-cmp#24]
How can I get vsnip to work with nvim-cmp-lsp?

plugins:
```lua
  use {
    'hrsh7th/nvim-cmp',
    after = 'nvim-lspconfig',
    config = function() require'config/nvim-compe' end,
  }
  use {
    'hrsh7th/cmp-nvim-lsp',
    after = 'nvim-cmp',
    config = function() require('cmp_nvim_lsp').setup {} end,
  }
  use {
    'hrsh7th/vim-vsnip',
    after = 'nvim-cmp',
  }
  use {
    'hrsh7th/vim-vsnip-integ',
    after = 'vim-vsnip',
  }
```

config:
```lua
local cmp = require'cmp'

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-d>'] = cmp.mapping.scroll(-4),
    ['<C-f>'] = cmp.mapping.scroll(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<C-y>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    })
  },
  sources = {
    { name = 'nvim_lsp' }
  },
}
```

`~/.vsnip/global.json`:
```json
{
  "diso": {
    "prefix": "diso",
    "body": ["${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}"],
    "description": "ISO date time stamp"
  }
}
```

results in a json file:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/2339362/129482456-7d5b04f2-a6f4-4186-aa6a-2ee53417451e.png">

**Comment by hrsh7th** [comment]
You should add  { name = 'vsnip' } to sources.

**Comment by hrsh7th** [comment]
BTW, Your reporting is much clear. Thanks!

**Comment by lourenci** [comment]
So don’t I need to set up `vsnip-integr` plugin? I thought I could ignore vsnip source since the snippets are coming from the lsp source…

**Comment by hrsh7th** [comment]
You don't need to set up `vim-vsnip-integ`. If you want to show vsnip candidates to completion-menu, You just add `sources = { { name = 'nvim_lsp' }, { name = 'vsnip' } }` both.

**Comment by lourenci** [comment]
Do you mind to trying explain to me the purpose of `vsnip-integr`? I think I could ignore vsnip source altogether with it. 

Thank you very much. It is working configuring it as a source…

**Comment by hrsh7th** [comment]
The `vim-vsnip-integ` supports `vim-lsp`, `vim-lsc`, `neovim builtin lsp omnifunc` etc.

The `nvim-cmp` has a customizable snippet configuration point, so it is not needed.

**Comment by marcushwz** [comment]
Hi @hrsh7th, sorry for disturbing you. 

I am migrating over from `nvim-compe` and having the same problem where `nvim-cmp` does not show snippets from `vsnip + friendly-snippets`. I have already added `vsnip` to the sources but it still does not work.

Appreciate if you can point me to debug further, thank you. 

This is the config
```lua
local cmp = require 'cmp'
cmp.setup {
  snippet = {
    expand = function(args)
        vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-d>'] = cmp.mapping.scroll(-4),
    ['<C-f>'] = cmp.mapping.scroll(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
    ['<Tab>'] = cmp.mapping.mode({ 'i', 's' }, function(_, fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
      else
        fallback()
      end
    end),
    ['<S-Tab>'] = cmp.mapping.mode({ 'i', 's' }, function(_, fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n')
      else
        fallback()
      end
    end),
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  },
}
```

**Comment by hrsh7th** [comment]
@marcushwz Did you install `cmp-vsnip` source via your plugin manager?

**Comment by marcushwz** [comment]
@hrsh7th, Didn't know about that. Just did that and it works now, thank you so much, and have a great day!

**Comment by learning2bdeveloper** [comment]
hey guys, i have problem that i can't use my custom snippet from ~/.vsnip/. please help me guys!
