### ISSUE TITLE
ultisnips not working with the latest neovim nightly

### ISSUE THREAD

**Issue by Trid-collab** [hrsh7th/nvim-cmp#241]
I have noticed that the Ultisnips options have stopped working with latest neovim nightly release. Have checked that it works with the rolled back stable release. 

Is there something we need to do to fix in the new release

**Comment by hrsh7th** [comment]
nvim-cmp has no ultisnips related codes.

**Comment by Trid-collab** [comment]
I was using the cmp-nvim-ultisnips to for ultisnips sources. it seems to have stopped providinq ultisnip sources during autocomplete in the latest neovim nightly. It was working in the previous releases and is also working in the stable 0.5 release

**Comment by hrsh7th** [comment]
If your all sources stop working, it is nvim-cmp's problem, I think.
But you say `'cmp-nvim-ultisnips' not working with latest neovim`.

**Comment by Trid-collab** [comment]
I mean I not sure if its the issue with cmp-nvim-ultisnips but since the ultisnips options are not showing up in the auto complete I am presuming its due to cmp-nvim-ultisnips or something in cmp which has broken due to the latest changes in the neovim nightly. I am no expert on this

**Comment by Shougo** [comment]
I think is should be reported in `cmp-nvim-ultisnips` issues.
But UltiSnips neovim support is best effort.
It may not be fixed.

**Comment by rebelot** [comment]
I had the same issue, fixed it with the following. I discovered it with `:echo &rtp`, I don't know enough to understand the problem, but from ultinsnips documentation it looks for directories named `UltiSnips` in `runtimepath`. However my start plugins are not present in rtp. Idk if it's an issue and where it comes from

```
  use {'honza/vim-snippets', rtp = '.'}
  use {'SirVer/ultisnips'}
```

**Comment by Trid-collab** [comment]
Putting the following as suggested - helped to get back the ultisnip options 
use {'honza/vim-snippets', rtp = '.'}
use {'SirVer/ultisnips'}

But I also noticed that the I am not able to circulate the snippet placeholders using tabs like it was working before. Its not even working in the neovim stable release. When I am typing in the snippet placeholder the autocompletes are popping up while I am typing. On completion I am not able to use the tabs to move to the next placeholder.

This working earlier before -few days back

**Comment by hrsh7th** [comment]
I think placeholder issue relates your mapping configuration.

**Comment by Trid-collab** [comment]
This is my mapping setup. I am sorry I am no expert on this. Just tried to follow some leads which I picked up while going through the configs of others and it worked for me till recently

	mapping = {
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-d>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-Space>"] = cmp.mapping.complete(),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Insert,
			select = true,
		}),
		["<Tab>"] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 or vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
					return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>"))
				end

				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<tab>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
		["<S-Tab>"] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-p>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
	},

**Comment by hrsh7th** [comment]
Your configuration says

1. If popup menu is visible, check `UltiSnips#CanExpandSnippet` or `UltiSnips#CanJumpForwards`
2. If it returns `false`, should navigate the next popup menu item.

So I think the problem caused by `UltiSnips#CanExpandSnippet` or `UltiSnips#CanJumpForwards`, right?

**Comment by hrsh7th** [comment]
@Trid-collab Do you still have a problem?
