### ISSUE TITLE
[Feature] show client name for nvim_lsp

### ISSUE THREAD

**Issue by rebelot** [hrsh7th/nvim-cmp#243]
Would it be possible to show the lsp client name for lsp completions? I tried somethin like this but it didn't work:

```lua
  formatting = {
    format = function(entry, vim_item)
       if entry.source.name == 'nvim_lsp' then
         vim_item.menu = entry.source.client.name
       else
         vim_item.menu = entry.source.name
      end
      return vim_item
      end
  },
```

Thanks

**Comment by hrsh7th** [comment]
@rebelot `entry.source.source.client.name` should work. But it is out of the scope of nvim-cmp. So I can't promise to keep the signature.
