### ISSUE TITLE
Weird symbols in scss files

### ISSUE THREAD

**Issue by ziombo** [hrsh7th/nvim-cmp#246]
While using nvim-cmp in .scss files, I get some weird suggestion that stay in window (they persist when changing buffers) after closing the completion menu.

Here's an example:
![image](https://user-images.githubusercontent.com/15613606/134661647-20cbe087-e8b7-4f6c-8dcc-10e714fd98bc.png)

after closing completion menu the values that were shown "outside" of the area of the menu stay visible (until I put changes in the file that reach these lines):
![image](https://user-images.githubusercontent.com/15613606/134661732-186954b0-8c61-48c0-aefd-e22c638f56f5.png)

Additionaly, even though these two options have these weird strikethrough lines, they will paste properly into the buffer once selected. The common thing about these issue inducing options is that they are marked as nonstandard in their definition: 
![image](https://user-images.githubusercontent.com/15613606/134662381-5c9f5241-ebd4-430d-b3fe-2f9c97f50d29.png)
So maybe that's causing them to be written into completion menu in a weird way?

**Comment by rhcher** [comment]
same as #48 ,however you can wait this PR that solved this issue merger

**Comment by hrsh7th** [comment]
@ziombo You can set `formatting.deprecated = false`
