### ISSUE TITLE
Support displaying signature after selecting completion

### ISSUE THREAD

**Issue by ericvw** [hrsh7th/nvim-cmp#247]
Coming from `vim` and [YouCompleteMe](https://github.com/ycm-core/YouCompleteM), a feature I didn't realize I depended upon was [YCM's signature help](https://github.com/ycm-core/YouCompleteMe#signature-help) ([associated PR for it with GUI examples](https://github.com/ycm-core/ycmd/pull/1255)).  The signature would pop up after accepting a completion so that you can easily reference the signature while typing.

Below is what I am talking about:
<img width="377" alt="vim-ycm" src="https://user-images.githubusercontent.com/1284017/134727947-25be2d67-ee54-424c-bcdd-3bb5795449e1.png">

After typing `foo(`, the signature help would float above what I was typing to reference it.  After the closing paren (i.e., `)`) the signature would disappear.

Does `nvim-cmp` already support this?  If not, is it a feature that fits well with the project?  Thanks!

**Comment by ericvw** [comment]
A colleague pointed me at https://github.com/ray-x/lsp_signature.nvim.  If this feature is not in scope for `nvim-cmp`, I can use another plugin for this functionality.

**Comment by rafamadriz** [comment]
The author of this plugin has mentioned multiple times that this feature is not within the scope of the project because is not in the LSP spec, hence he has no plans of supporting this. As you mentioned, there is lsp_signature.nvim and it's a fine solution.

**Comment by ericvw** [comment]
@rafamadriz, thanks!  I completely forgot to check existing closed issues.  I found https://github.com/hrsh7th/nvim-cmp/issues/235#issuecomment-924942666.  I'll close this and apologies for the noise.
