### ISSUE TITLE
gopls and preselection

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-cmp#248]
Hey there,

I'm setting up gopls server and I notice weird behavior with pre-select. I'm used to have first item selected at all time but gopls seems to break that for some reason. Any ideas
![completion_menu](https://user-images.githubusercontent.com/65782666/134742675-81b60c1b-cd94-40cf-ade0-c6f4b5b96f68.gif)

**Comment by hrsh7th** [comment]
You can disable by `cmp.setup { preselect = cmp.PreselectMode.None }`
