### ISSUE TITLE
'<C-Space>' mapping doesn't work

### ISSUE THREAD

**Issue by gusfrehse** [hrsh7th/nvim-cmp#249]
When I change to ``'<C-g>'`` it works, so I guess it's related to how the string ``'<Space>'`` is handled? I tried to dig the source and saw that  ``'<Space>'`` is handled differently. Maybe ``'<C-Space>'`` needs too?

[Here's the line](https://github.com/hrsh7th/nvim-cmp/blob/fdd38098938ec41d235162feac67b20c20762325/lua/cmp/utils/keymap.lua#L13), it is just a guess though.

This is my config:
```lua
-- nvim-cmp config
local cmp = require('cmp')
cmp.setup({
    snippet = false,
    mapping = {
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),
        ['<C-u>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.close(),
        ['<CR>'] = cmp.mapping.confirm({ select = false }),
    },
    sources = {
        { name  = 'nvim_lsp' },
    },
    completion = {
        autocomplete = false,
    },
})
```

**Comment by hrsh7th** [comment]
No. The line you pointed is to be used only the character conversion for LSP to vim mapping.

**Comment by hrsh7th** [comment]
I can't reproduce with your config.
I guess your language server isn't working. You must check `:LspInfo`.

**Comment by gusfrehse** [comment]
I guess it's a problem with my terminal, tried with one GUI and it worked. Seems like terminals treat ``C-Space`` differently.
Sorry for the unrelated issue.

I have a question though, are snippets required for ``cmp.mapping.confirm()``? I've put ``snippets = false`` but when selecting a match from the list and pressing ``<CR>`` I get

```E5108: Error executing lua ...im-data\site\pack\packer\start\nvim-cmp\lua\cmp\core.lua:381: attempt to index field 'snippet' (a boolean value)```

Is this expected as I don't have a snippet engine installed? (Maybe I should make another issue about this?)
