### ISSUE TITLE
Completions not properly inserted

### ISSUE THREAD

**Issue by WhyNotHugo** [hrsh7th/nvim-cmp#250]
When I pick an option from the completions menu, it's not inserted.

I originally though this was an issue with the completions emoji, and [reported it as an issue for that plugin](https://github.com/hrsh7th/cmp-emoji/issues/1):

https://user-images.githubusercontent.com/730811/134767422-14e17315-9ebf-4dc9-ae63-9b81ecaae737.mp4

However, this also happens with other completion sources, like LSPs, for example here, if I pick an entry, it's not inserted:

https://user-images.githubusercontent.com/730811/134767438-244f8bdc-5646-4e56-83e7-5029125bf57c.mp4

This is my config:

```lua

vim.opt.completeopt = { "menu", "menuone", "noselect" }
local cmp = require("cmp");

cmp.setup({
  sources = {
    { name = "buffer" },
    { name = "emoji" },
    { name = "nvim_lsp", priority = 100 }, -- Keep LSP results on top.
    { name = "path" },
    { name = "spell" },
    { name = "treesitter" },
    { name = 'nvim_lua' },
  },
  formatting = {
    format = function(entry, vim_item)

      -- set a name for each source
      vim_item.menu = ({
        buffer = "[Buffer]",
        emoji = "[Emoji]",
        nvim_lsp = "[LSP]",
        path = "[Path]",
        spell = "[Spell]",
        treesitter = "[Treesitter]",
        nvim_lua = "[Neovim]",
      })[entry.source.name]
      return vim_item
    end,
  },
})
```

This worked properly out-of-the-box with `compe`:

```lua
vim.o.completeopt = "menuone,noselect"

require("compe").setup({
  enabled = true,
  autocomplete = true,
  debug = false,
  min_length = 1,
  preselect = "disable",

  source = {
    path = true,
    buffer = true,
    calc = true,
    vsnip = true,
    nvim_lsp = true,
    nvim_lua = true,
    spell = true,
    tags = true,
    snippets_nvim = true,
    treesitter = true,
    emoji = true,
  },
})
```

I'm not sure if I'm missing some setting or something extra, of if I'm just hitting a bug.

**Comment by uga-rosa** [comment]
Please map.
https://github.com/hrsh7th/nvim-cmp/tree/custom-menu#mapping-type-tablestring-funfallback-function

**Comment by WhyNotHugo** [comment]
`cmp.SelectBehavior` doesn't exist on the `master` branch.

I tried the examples in the README in master (plus some variations of it), but can't get a working setup. Do you have a snippet of what a config that works with the master branch?

I also tried `["<Tab>"] = cmp.mapping.select_next_item(),` but that doesn't work either. The entry is selected in the menu, but is not inserted.

**Comment by hrsh7th** [comment]
You should map `<CR>` to confirm.

**Comment by WhyNotHugo** [comment]
I've experimented a bit with that and I think I understand what you're suggesting: <kbd>Tab</kbd> would be used to pick an option from the menu, and then one needs to press <kbd>CR</kbd> to "commit the operation".

I'd like to avoid this extra step of "commiting". It adds a bit too much cognitive burden -- if I've picked an option I want it inserted and don't want to have to thing about confirming as an extra step.

With `compe` merely _selecting_ an option was enough and I didn't need to commit as a separate action (and that was actually the behaviour out-of-the-box). Is that not possible with `cmp`?

**Comment by hrsh7th** [comment]
Yes. At least, cmp-emoji does not work as so.
It isn't impossible but I think it's personal preference.

**Comment by WhyNotHugo** [comment]
Agreed, it's a matter of preference.

Would you consider allowing this sort of usage, or should I just stick with `nvim-compe`? The extra confirmation step is too confusing for me to try and adapt to it :sweat:

**Comment by hrsh7th** [comment]
implemented.

**Comment by hrsh7th** [comment]
You should set `{ name = 'emoji', opts = { insert = true } } `
