### ISSUE TITLE
Extend completion with user dictionary

### ISSUE THREAD

**Issue by eronde** [hrsh7th/nvim-cmp#251]
First of all, thanks for your time to create this great plugin.

In neovim you can complete item from user dictionaries with the key-binding \<C-X\>\<C-K\>, see example below.
![userdict](https://user-images.githubusercontent.com/1305254/134782900-d4608b18-8556-4de2-b18e-783ba27c47b7.png)

I was wondering if nvim-cmp provides an option to attach the output of \<C-X\>\<C-K\>  into the completion of nvim-cmp.

**Comment by uga-rosa** [comment]
https://github.com/uga-rosa/cmp-user_dictionary
Please try it.
I've just created it, so there will probably be some bugs, but please open an issue over there.

**Comment by hrsh7th** [comment]
@uga-rosa Thank you for quickly impl!

**Comment by eronde** [comment]
@uga-rosa Thanks for your time :pray:
