### ISSUE TITLE
How to setup auto trigger without typing any keybinding

### ISSUE THREAD

**Issue by siansiansu** [hrsh7th/nvim-cmp#252]
Hi,
I would like to ask that how to setup auto trigger without typing any keybinding.

Just like the demo in the [deoplete.nvim](https://github.com/Shougo/deoplete.nvim)

https://github.com/archseer/elixir.nvim/blob/master/autocomplete.gif

**Comment by hrsh7th** [comment]
Please more detailed explanation of what you want.

I guess you want to completion via `InsertEnter`.

You can use `require('cmp').setup { completion = { autocomplete = { cmp.TriggerEvent.InsertEnter, cmp.TriggerEvent.TextChanged } }`

**Comment by siansiansu** [comment]
It's fixed. Thanks!
