### ISSUE TITLE
Create vimdocs

### ISSUE THREAD

**Issue by p0da** [hrsh7th/nvim-cmp#253]
Seeing as the README already is several hundred lines long and will likely only increase in the future it may be wise to consolidate all documentation in the wiki, removing it from the README. Additionally elaborating on what each configuration option does would be nice to see as the current descriptions are somewhat terse. I am more than willing to help if you need any.

**Comment by gegoune** [comment]
I would suggest not doing it but instead cleaning up README to only contain short overview of what that plugin is, how to install it and such things and put all documentation into vimdoc. It can then be very easily accessed from neovim for the exact version user has installed, so no need to check if configuration still applies to installed version, etc.

**Comment by Shougo** [comment]
I think the README documentation should be moved to Vim documentation help file.

**Comment by p0da** [comment]
Of course that may be done as well. I don't see why they have to be mutually exclusive.

**Comment by hrsh7th** [comment]
It's not perfect yet, but most of it is vimdoc.
