### ISSUE TITLE
Difference between nvim-cmp and nvim-compe 

### ISSUE THREAD

**Issue by krisfans** [hrsh7th/nvim-cmp#255]
I wonder what is the  difference between nvim-cmp and nvim-compe ? Should I switch from compe to cmp ?Thanks

**Comment by hrsh7th** [comment]
nvim-cmp is improved version of nvim-compe.

1. Support replacement completion
2. Support trimming insertion text via text after cursor
3. Customizable via Lua function
4. Support ghost text
5. Fancy appearance (WIP)

Other minor improvements are done in nvim-cmp.

Both plugins are for completion so those have no big difference.
