### ISSUE TITLE
Opening paren trigger autocompletion confirmation

### ISSUE THREAD

**Issue by harrysolovay** [hrsh7th/nvim-cmp#256]
When autocomplete items are visible and selected (but not explicitly confirmed––in my case via a carriage return), an opening paren triggers the completion. I'd like to disable this behavior.

For instance, in the video below, I type `window.at`, followed by an opening paren. This triggers the autocompletion item as `window.atob` (sourced from `nvim_lsp`). However, I'd like for this only to happen if I explicitly trigger it with a carriage return.

https://user-images.githubusercontent.com/4893548/134897504-b52be499-f113-4de7-90ac-5a493db6bc31.mov

For reference, here is my `cmp` config:

```lua
local cmp = require("cmp")

cmp.setup({
    completion = {
        completeopt = "menu,menuone,noinsert",
    },
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end,
    },
    mapping = {
        ["<S-Tab>"] = cmp.mapping.select_prev_item(),
        ["<Tab>"] = cmp.mapping.select_next_item(),
        ["<C-d>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete(),
        ["<C-e>"] = cmp.mapping.close(),
        ["<CR>"] = cmp.mapping.confirm({
            select = true,
        }),
    },
    sources = {
        { name = "nvim_lsp" },
        { name = "path" },
        { name = "crates" },
        { name = "nvim_lua" },
        { name = "buffer" },
        { name = "vsnip" },
    },
})
```

And here is my `autopairs` config:

```lua
require("nvim-autopairs.completion.cmp").setup({
    map_cr = true,
    map_complete = true,
    auto_select = false,
})
```

(I've tried setting all of the above to false)

Apologies if this is addressed elsewhere. I spent quite a while sifting through previous issues. Any help would be greatly appreciated. Thank you!

**Comment by hrsh7th** [comment]
It's feature of LSP spec.
You can disable it by the following configuration.
https://github.com/hrsh7th/nvim-cmp#confirmationget_commit_characters-type-funcommit_characters-string-string

```lua

cmp.setup {
  confirmation = {
    get_commit_characters = function() return {} end
  }
}
```

**Comment by harrysolovay** [comment]
Worked like a charm, thank you!
