### ISSUE TITLE
Completion items from wrong context

### ISSUE THREAD

**Issue by harrysolovay** [hrsh7th/nvim-cmp#257]
When prompting for completions, the incorrect context is shown / drawn from the LS––it show globals.

In the following example, I'm attempting to autocomplete the fields of an object being passed to a function in TypeScript. The LS is aware of the correct type information (inferred from its placement within the function call). Even when I type characters matching an inferred name, the correct completion list does not get displayed. Yet it is clear from the nested completions (such as `tag`, `force`, `watchFile`) that the LS has the correct type info. How can I have`cmp` show the correct type info at the top level?

https://user-images.githubusercontent.com/4893548/134983337-bcc795f4-58a0-4b2d-a412-19a07de924a9.mov

I also noticed that some of the type info is missing from the docs that get displayed. For instance, the `excludeFiles` field should have a type of `string[]` (not `any`).

<img width="822" alt="Screen Shot 2021-09-27 at 4 53 15 PM" src="https://user-images.githubusercontent.com/4893548/134984001-902a1303-1c46-423e-b77e-3244d0229aa1.png">

However, if I attempt to place an `any` value for one of these fields, I correctly get a type error.

<img width="817" alt="Screen Shot 2021-09-27 at 4 56 53 PM" src="https://user-images.githubusercontent.com/4893548/134984119-ade11bc8-2320-41b2-afa5-708d579d814f.png">

Any ideas on how to get this behaving would be greatly appreciated. Thank you!

For reference, here is my `cmp` config:

```lua
local cmp = require("cmp")

cmp.setup({
    confirmation = {
        get_commit_characters = function()
            return {}
        end,
    },
    completion = {
        completeopt = "menu,menuone,noinsert",
    },
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end,
    },
    mapping = {
        ["<S-Tab>"] = cmp.mapping.select_prev_item(),
        ["<Tab>"] = cmp.mapping.select_next_item(),
        ["<C-d>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete(),
        ["<C-e>"] = cmp.mapping.close(),
        ["<CR>"] = cmp.mapping.confirm({
            select = true,
        }),
    },
    sources = {
        { name = "nvim_lsp" },
        { name = "path" },
        { name = "crates" },
        { name = "nvim_lua" },
        { name = "buffer" },
        { name = "vsnip" },
    },
})
```

And here is my `autopairs` config:

```lua
require("nvim-autopairs.completion.cmp").setup({
    map_cr = true,
    map_complete = true,
    auto_select = false,
})
```

Thanks again!

**Comment by hrsh7th** [comment]
It's language server issue. Sorry...

**Comment by harrysolovay** [comment]
I'm sad to hear. Thank you anyways!
