### ISSUE TITLE
Attempt to index field 'snippet'

### ISSUE THREAD

**Issue by Iliyapunko** [hrsh7th/nvim-cmp#260]
![image](https://user-images.githubusercontent.com/53742299/135120638-65bbe80d-4a18-4286-aed9-b8396bc361c0.png)

When i have completion and press 'C-n', after that press '(', i get error.

**Comment by Iliyapunko** [comment]
My config
`local cmp = require 'cmp'

local sources = {
  nvim_lsp   = '[LSP]',
  buffer     = '[BUF]',
  path       = '[PATH]',
  treesitter = '[TS]',
  spell      = '[SP]'
}

cmp.setup {
  snippet = false,
  formatting = {
    format = function(entry, vim_item)
      local icon = require 'plugins.icons'.icons[vim_item.kind]

      vim_item.kind = string.format('%s %s', icon, vim_item.kind)
      vim_item.menu = sources[entry.source.name]

      return vim_item
    end,
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    -- ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    -- ['<CR>'] = cmp.mapping.confirm { select = false },
  },
  sources = {
    {
      name = 'nvim_lsp',
    },
    {
      name = 'buffer',
      opts = {
        get_bufnrs = function()
          return vim.api.nvim_list_bufs()
        end
      }
    },
    { name = "path" },
    { name = "spell" },
    { name = "treesitter" },
  },
}
`

**Comment by hrsh7th** [comment]
Oh. `snippet.expand` isn't documented yet. Sorry.
But `snippet.expand = false` is wrong setting. You must set up `snippet.expand` config.

**Comment by Iliyapunko** [comment]
Thank's. It was super fast :)
