### ISSUE TITLE
Ways to turn on/off

### ISSUE THREAD

**Issue by osamuaoki** [hrsh7th/nvim-cmp#261]
#### Background:
Although, this kind of **smart** tools are generally useful and is better to be enabled all the time, in some odd occasion, we want to turn off a short period by calling a lua call via some key binding.

There may be already enough code to do this or not, I don't know.   It was not easy one for me to figure out.

#### Requested content
I am asking additional help message in README.md (with optional feature addition if needed) to describe how to turn on and off.  I don't have proposed text for nvim-cmp but what I proposed for nvim-autopairs may give some idea of the desirable content.

  https://github.com/windwp/nvim-autopairs/pull/141/commits/1afc05a2ed84394e050f16ee58b8c11cc5df5c64

Here, nvim-autopairs has 3 key APIs to enable this.

- read status
- enable
- disable

Making complicated condition to turn off can become non-trivial.  This approach offers a simple alternative way to avoid problematic situations.

#### An example of a problematic situation addressed by this proposed documentation improvement (FYI):

Suppose you are writing C code for an embedded USB device scanning keyboard switches, this nvim-cmp is very useful to get all the variable names etc.

But when you start writing a MACRO table describing how each key responds to input for each state of the device, we need to make such tables for many device states.  Copy (yy->p) and overwrite (R) is one way.  But Instead of using overwrite mode, use of many **CTRL-Y** with occasional typing in the insert mode accommodates careful line-by-line updates.

Currently, every time some cmp's snippet engine finds opportunity, it stops **CTRL-Y** with a POPUP window.  Then I need to close the POPUP. This is quite annoying and I just want to turn off for that part of editing.

For this kind of needs, editing configuration file of nvim-cmp and restarting nvim is not desirable path.

**Comment by hrsh7th** [comment]
I think you already have two options.

#### You can disable auto-completion
```lua
local cmp = require('cmp')
cmp.setup {
  completion = {
    autocomplete = false,
  },
  mapping = {
    ['<C-Space>'] = cmp.mapping.complete()
  }
}
```

#### You can switch enabled/disabled by configuration.

nvim-cmp has a `enabled` option that accepts `function`.

```lua
local cmp = require('cmp')
cmp.setup {
  enabled = function()
    return vim.g.your_cmp_disable_enable_toggle
  end
}
```
Then you can enable/disable nvim-cmp by `:let g:your_cmp_disable_enable_toggle = v:true or v:false`

Enjoy.

**Comment by osamuaoki** [comment]
Thanks.

Considering the default on was a function, I ended up doing the following.
With which-key, its quite easy to remember and type.
```
-- toggle_completion() -- <leader>tc -- toggle completion
vim.g.cmp_toggle_flag = true -- initialize
local normal_buftype = function()
  return vim.api.nvim_buf_get_option(0, 'buftype') ~= 'prompt'
end
M.toggle_completion = function()
  local ok, cmp = pcall(require, "cmp")
  if ok then
    local next_cmp_toggle_flag = not vim.g.cmp_toggle_flag
    if next_cmp_toggle_flag then
      print("completion on")
    else
      print("completion off")
    end
    cmp.setup {
      enabled = function()
        vim.g.cmp_toggle_flag = next_cmp_toggle_flag
        if next_cmp_toggle_flag then
          return normal_buftype
        else
          return next_cmp_toggle_flag
        end
      end
    }
  else
    print("completion not available")
  end
end
```
This is a part of my PR https://github.com/NTBBloodbath/doom-nvim/pull/132 for doom-nvim project.

**Comment by benbrastmckie** [comment]
> Considering the default on was a function, I ended up doing the following.
> With which-key, its quite easy to remember and type.

This looks like just what I am looking for, however I'm struggling to get the toggle_completion to work. At least cutting and pasting what you provided above into my nvim-cmp config file as is gave me a bunch of errors. My config is in Lua but I'm far from confident working in it. Any pointers would be much appreciated!

**Comment by osamuaoki** [comment]
FYI: AstroNvim now has this feature with `<leader>uc`.  (I created original PR for this and merged and updated)

**Comment by benbrastmckie** [comment]
Thanks! I poked around a bit and see that there is lots of fodder for inspiration in AstroNvim. In my case I think all I need is something very simple like:
```
function toggle_cmp()
  if vim.b.cmp_enabled = true
    then require('cmp').setup.buffer { enabled = false }
  else require('cmp').setup.buffer { enabled = true }
end
```
This didn't work since I don't really know what I'm doing, but hope that I'm on the right track. Any pointers would be much appreciated!

**Comment by friedelino** [comment]
Hey @benbrastmckie! Even though this issue is closed now... I stumbled upon this thread because i also was searching for a simple way to map a function toggling nvim-cmp on/off to a key. Here is the solution which works fine for me now:

``` lua
-- initialize global var to false -> nvim-cmp turned off per default
vim.g.cmptoggle = false

local cmp = require('cmp')
cmp.setup {
  enabled = function()
    return vim.g.cmptoggle
  end
}
vim.keymap.set("n", "<leader>ua", "<cmd>lua vim.g.cmptoggle = not vim.g.cmptoggle<CR>", { desc = "toggle nvim-cmp" })
```

**Comment by benbrastmckie** [comment]
Hey thanks for this! Works great :)

**Comment by FernandoBasso** [comment]
Maybe this could be useful to others, but we can set the keybinding to print a message of cmp being enabled or disabled:

```lua
local cmp = require'cmp'

--
-- nvim cmp turned off by default.
--
vim.g.cmp_toggle = false

local cmp = require('cmp')

vim.keymap.set(
  'n',
  '<Leader><Leader>c',
  function ()
    vim.g.cmp_toggle = not vim.g.cmp_toggle
    local status

    if vim.g.cmp_toggle then
      status = 'ENABLED'
    else
      status = 'DISABLED'
    end

    print('nvim-cmp', status)
  end,
  { desc = 'toggle nvim-cmp' }
)

cmp.setup({
  enabled = function()
    return vim.g.cmp_toggle
  end,

  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },

 -- Rest of the setup...
}

**Comment by gitaarik** [comment]
I'm doing it in this way:

```lua
local function toggle_autocomplete()
  local cmp = require('cmp')
  local current_setting = cmp.get_config().completion.autocomplete
  if current_setting and #current_setting > 0 then
    cmp.setup({ completion = { autocomplete = false } })
    print('Autocomplete disabled')
  else
    cmp.setup({ completion = { autocomplete = { cmp.TriggerEvent.TextChanged } } })
    print('Autocomplete enabled')
  end
end

vim.api.nvim_create_user_command('NvimCmpToggle', toggle_autocomplete, {})

-- Set a keymap like this for example:
-- vim.api.nvim_set_keymap('n', '<Leader>a', ':NvimCmpToggle<CR>', { noremap = true, silent = true })
```

I also created a plugin repo for it for easy installation: https://github.com/gitaarik/nvim-cmp-toggle

**Comment by osamuaoki** [comment]
FYI: I have moved to LazyVim .  Here is my updated set up.

Here, I address which-key binding, completion state notification, starting state setting.

My `~/.config/nvim/lua/config/keymaps.lua` containing:

```
-- For warn/info/float-term dialogue
local Util = require("lazyvim.util")

-- Toggle Input Suggestion with <TAB>
-- * https://github.com/hrsh7th/nvim-cmp/issues/429
-- * https://github.com/hrsh7th/nvim-cmp/issues/261
map("n", "<leader>u<tab>", function()
  -- vim.g.input_suggestion == nil is treated as true
  vim.g.input_suggestion = vim.g.input_suggestion == false
  if vim.g.input_suggestion then
    Util.warn("Enabled Input Suggestion", { title = "Input Suggestion (global)" })
  else
    Util.info("Disabled Input Suggestion", { title = "Input Suggestion (global)" })
  end
  require("cmp").setup({
    enabled = function()
      if vim.api.nvim_buf_get_option(0, "buftype") == "prompt" then
        return false
      else
        return vim.g.input_suggestion
      end
    end,
  })
end, { desc = "Toggle Input Suggestion †" })
```

I control starting mode with `~/.config/nvim/lua/config/options.lua`  containing:
```
-- Input Sugesstion (toggle with "<leader>u<tab>")
--   * false: Disable
--   * true:  Enable
vim.g.input_suggestion = false
-- vim.g.input_suggestion = true
```

**Comment by emilBeBri** [comment]
> I'm doing it in this way:
> 
> ```lua
> local function toggle_autocomplete()
>   local cmp = require('cmp')
>   local current_setting = cmp.get_config().completion.autocomplete
>   if current_setting and #current_setting > 0 then
>     cmp.setup({ completion = { autocomplete = false } })
>     print('Autocomplete disabled')
>   else
>     cmp.setup({ completion = { autocomplete = { cmp.TriggerEvent.TextChanged } } })
>     print('Autocomplete enabled')
>   end
> end
> 
> vim.api.nvim_create_user_command('NvimCmpToggle', toggle_autocomplete, {})
> 
> -- Set a keymap like this for example:
> -- vim.api.nvim_set_keymap('n', '<Leader>a', ':NvimCmpToggle<CR>', { noremap = true, silent = true })
> ```
> 
> I also created a plugin repo for it for easy installation: https://github.com/gitaarik/nvim-cmp-toggle

This is great thanks!! Works like a charm.

Although I better figure out *why* nv-cmp is so slow on even an ~ 4.000 line bash file, LSP is disabled. Just using the standard configs from the github repo. Hmm.  But this at least makes it possible for me to work in "large" files like this on the fly. thanks.

**Comment by Shougo** [comment]
You can create minimal config and upload the sample file.

**Comment by Bacbia3696** [comment]
Code snip for who want to toggle per buffer

```lua
function()
  if vim.fn.exists("b:cmp") == 0 or vim.api.nvim_buf_get_var(0, "cmp") then
    vim.api.nvim_buf_set_var(0, "cmp", false)
    require("cmp").setup.buffer({ enabled = false })
    vim.notify("Disabled auto cmpletion")
  else
    vim.api.nvim_buf_set_var(0, "cmp", true)
    require("cmp").setup.buffer({ enabled = true })
    vim.notify("Enabled auto cmpletion")
  end
end,
```

**Comment by carloseduribeiro** [comment]
> I'm doing it in this way:
> 
> ```lua
> local function toggle_autocomplete()
>   local cmp = require('cmp')
>   local current_setting = cmp.get_config().completion.autocomplete
>   if current_setting and #current_setting > 0 then
>     cmp.setup({ completion = { autocomplete = false } })
>     vim.notify('Autocomplete disabled')
>   else
>     cmp.setup({ completion = { autocomplete = { cmp.TriggerEvent.TextChanged } } })
>     vim.notify('Autocomplete enabled')
>   end
> end
> 
> vim.api.nvim_create_user_command('NvimCmpToggle', toggle_autocomplete, {})
> 
> -- Set a keymap like this for example:
> -- vim.api.nvim_set_keymap('n', '<Leader>a', ':NvimCmpToggle<CR>', { noremap = true, silent = true })
> ```
> 
> I also created a plugin repo for it for easy installation: https://github.com/gitaarik/nvim-cmp-toggle

This is great!  
I've just configured your plugin in my `nvim-cmp` dependencies config like bellow and it worked well for me.

```lua
return {
    'hrsh7th/nvim-cmp',
    dependencies = {
        -- ...
        -- It allow us to enable and disabel auto completion
        {
            'gitaarik/nvim-cmp-toggle',
            config = function()
                vim.api.nvim_set_keymap('n', '<Leader>ac', ':NvimCmpToggle<CR>', { noremap = true, silent = true })
            end,
        },
        -- ...
    },
}
```
}

 Thanks!
