### ISSUE TITLE
Wrong cursor position in some cases

### ISSUE THREAD

**Issue by rhcher** [hrsh7th/nvim-cmp#262]
## Explain the issue
The cursor position is wrong when I input `end` in Lua file second time.

### Steps to reproduce
 1. run `nvim -u vimrc.vim test.lua`
 2. We can input like this
![image](https://user-images.githubusercontent.com/50723480/135255607-c7ea8934-9c00-41be-8296-328c40197c17.png)
The first function is written just to have the words we need in the buffer

 3. Then we input `end`, we can see vim works well.
![image](https://user-images.githubusercontent.com/50723480/135255849-e352da37-10cb-4bf1-9435-c8773ee47158.png)

 4. Then we go back normal mode and input `cc` and `end`, it will be like this
![image](https://user-images.githubusercontent.com/50723480/135256059-b2e7c7ae-fc29-4719-8ac7-bcbe989c206d.png)
We can see that the cursor position is wrong.

## Minimal working example
test.lua
```lua
function test(x, y)
        return x + y
end

function foo(parameters)
        return parameters
```

## Minimal vimrc file
vimrc.vim
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ["<CR>"] = cmp.mapping.confirm({ select = true, }),
  },

  sources = {
    { name = "buffer" },
  },
}
EOF
```

## Additonal information
nvim version: NVIM v0.6.0-dev+364-gec4731d982
I can provide any other information if needed

**Comment by hrsh7th** [comment]
@rhcher I can't reproduce this with minimal config.

https://user-images.githubusercontent.com/629908/135258634-89bf1dd4-0908-4c62-8dc7-080c6b86fb0a.mp4

**Comment by rhcher** [comment]
Yes, the first input is always right, we need to input it once and then clear it and input it again.

**Comment by spindensity** [comment]
> Yes, the first input is always right, we need to input it once and then clear it and input it again. In fact, I found that the only way to reproduce this phenomenon is to modify it on the same line, e.g. `cc`. If we type `dd` and then go back to this line and retype it, the phenomenon is normal.

I have the same problem and I can reproduce it exactly.

**Comment by hrsh7th** [comment]
Reproduced. Yes. cc will cause this.
