### ISSUE TITLE
Question: Does this make any sense and is somehow correct?

### ISSUE THREAD

**Issue by CantoroMC** [hrsh7th/nvim-cmp#263]
This is intended to load omnicompletion in nvim-cmp with those filetype that use syntaxcomplete#complete.
Is this correct and does it seems useful?
https://pastebin.com/rPxxsC2U

Thanks in advance.

**Comment by hrsh7th** [comment]
@CantoroMC You can use https://github.com/hrsh7th/cmp-omni

```lua
autocmd FileType css,scss lua require('cmp').setup.buffer {
\   sources = {
\     { name = 'omni' }
\  }
\ }

```
