### ISSUE TITLE
Error for autocompletion after upgrading to 0.5.1

### ISSUE THREAD

**Issue by yujinyuz** [hrsh7th/nvim-cmp#264]
I'm having this error

```
Error executing vim.schedule lua callback: .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:318: bad argument #1 to 'ipairs' (table expected, got string)
```

I tried printing the `response` and it seems to be returning `textDocument/completion` instead of a table

**Comment by hrsh7th** [comment]
Hm... cmp-nvim-lsp source supports nvim-lsp's signature change.
https://github.com/hrsh7th/cmp-nvim-lsp/commit/cdf83a55339007f3fbb811933efecb2fd84b99c6

Could you debug this line?
https://github.com/hrsh7th/cmp-nvim-lsp/commit/cdf83a55339007f3fbb811933efecb2fd84b99c6#diff-9a079dbefdd9876e3888197f7179902ace6edc34ad289f0027956fdcabf277c7R95

I want to know `arg1, arg2, arg3, arg4` values.

**Comment by yujinyuz** [comment]
Here's what I got

```
"arg1"
"arg2" "textDocument/completion"
"arg3" {
  client_id = 2,
  method = "textDocument/completion"
}
"arg4"
```
I think arg1 and arg4 is empty

**Comment by hrsh7th** [comment]
I've fixed maybe.
https://github.com/hrsh7th/cmp-nvim-lsp

**Comment by yujinyuz** [comment]
I don't see the errors but I'm not getting autocomplete suggestions

**Comment by hrsh7th** [comment]
@yujinyuz Hm...
```
  _, request_id = self.client.request(method, params, function(...)
    local args = { ... }
    print(vim.inspect(args))
    if self.request_ids[method] ~= request_id then
      return
    end
    if method == args[2] then
      callback(args[1], args[3]) -- old signature
    else
      callback(args[1], args[2]) -- new signature
    end
  end)
  self.request_ids[method] = request_id
```

What do you get the results?

**Comment by yujinyuz** [comment]
```
{
  [2] = "textDocument/completion",
  [3] = {
    client_id = 2,
    method = "textDocument/completion"
  }
}
```

**Comment by hrsh7th** [comment]
Hm... Where are our LSP results? 🤣

**Comment by hrsh7th** [comment]
I think we can't fix it in plugin-side.

**Comment by yujinyuz** [comment]
Oh. I thought you only needed the output of `print`..

Do you need the screenshot?

**Comment by hrsh7th** [comment]
No. No.
```
{
  [2] = "textDocument/completion",
  [3] = {
    client_id = 2,
    method = "textDocument/completion"
  }
}
```

I think the response doesn't contain LSP results...

**Comment by yujinyuz** [comment]
it's okay. i can just switch back to 0.5.0

**Comment by hrsh7th** [comment]
Let's closing this for now.
