### ISSUE TITLE
Option to debounce autocompletion ?

### ISSUE THREAD

**Issue by andersevenrud** [hrsh7th/nvim-cmp#266]
I have a fairly large TypeScript project that I'm currently working on using a relatively slow laptop, and when I have autocompletion enabled I get a lot of general slowdown while editing.

Is there a way to configure cmp so that I can debounce the completion trigger to like X00ms? Would be nice if it would kick in after I have stopped (or slowed down) typing rather than immediately on key press.

---

Also, just a side note on this. When I'm editing massive files in this project I sometimes get this error:

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: cannot resume dead coroutine
```

To reproduce it, I just have to do the following:

* Press a letter to start completion
* The popup opens with suggestions (this is important, it has to be visible)
* Type very fast (spam keys, or just hold down a single key). For each letter inserted everything becomes slower and slower
* Stop typing after a few seconds, and error appears after the UI has finished catching up

**Comment by hrsh7th** [comment]
First, consider using existing feature instead of adding new feature.

For example, Isn't `completion.keyword_length` enough?

And this project doen't use plenary.nvim.

**Comment by hrsh7th** [comment]
And If you have a `vim.lsp.set_log_level(...)`. It should be removed for performance.

**Comment by andersevenrud** [comment]
> For example, Isn't completion.keyword_length enough?

I've tried this and it doesn't really have much effect, sadly.

> And this project doen't use plenary.nvim.

My bad! This must be a side effect because of how things slow down when I have autocomplete enabled :blush: 

> And If you have a vim.lsp.set_log_level(...). It should be removed for performance.

Double checked, and it's not turned on.

---

But it's fine. I just wondered if maybe there was some existing feature or code I maybe could hook into to adjust this behavior as I could not see any mention of timers in the docu. Since there isn't I'll just close this and live with it. I was just using this very old slow computer because I have issues with my workstation and it was a little bit annoying at times. I'll just do manual completion keybinding for now.

Thanks for the quick reply and for your awesome work!

**Comment by mjlbach** [comment]
@andersevenrud do you want to test https://github.com/neovim/neovim/pull/15854/files

**Comment by andersevenrud** [comment]
@mjlbach Just fired up your branch, and with a side-by-side comparison I sadly don't really notice any difference.

Since the slowdown depends on the size of my current file (doesn't matter if buffer source is enabled or not) and typing speed it's a bit hard to actually quantify this just by feel alone. I'll have to see if I can't figure out a way to get some actual numbers on this.

**Comment by mjlbach** [comment]
Hm interesting, thanks for testing! Maybe the built in client isn't bottlenecking in your particular situation

**Comment by andersevenrud** [comment]
>  Just to clarify you did set VIMRUNTIME correctly right?

Indeed!

> built in client isn't bottlenecking

This seems to be the case. I just think it's because of the anemic system I'm on in combination with TypeScript LSP :man_shrugging:
