### ISSUE TITLE
selecting suggestion using <Tab> fails

### ISSUE THREAD

**Issue by elspecal** [hrsh7th/nvim-cmp#267]
Updated the mapping part of my nvim-cmp setup according to the posted breaking changes. Now when I want to select a completion suggestion it gitves me the following error:
`E5108: Error executing lua /home/miki/.config/nvim/lua/plugins/nvim-cmp.lua:13: attempt to call field 'visible' (a nil value)`

And this is all my nvim-cmp config:
```lua
local cmp = require 'cmp'

cmp.setup {
  snippet = {
    expand = function(args) require 'luasnip'.lsp_expand(args.body) end
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true
    },
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
	cmp.select_next_item()
      else
	fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
	cmp.select_prev_item()
      else
	fallback()
      end
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
    { name = 'buffer' }
  }
}
```
It did work for some time tho. Not sure what happened. Can you help me solve it, please?

**Comment by rhcher** [comment]
The PR related this break change hasn't  been mergerd yet.

**Comment by elspecal** [comment]
Oh I see now. Thats misleading then
