### ISSUE TITLE
Error: "snippet engine is not configured"

### ISSUE THREAD

**Issue by itaranto** [hrsh7th/nvim-cmp#268]
Hello,

I don't use a snippet engine, every time the `confirm` mapping is called, `nvim-cmp` fails with error:

```
E5108: Error executing lua ...site/pack/paqs/start/nvim-cmp/lua/cmp/config/default.lua:26: snippet engine is not configured.
```

And after this `nvim-cmp` stops working.

This is my current configuration:

```lua
-- Set completeopt to have a better completion experience
vim.opt.completeopt = 'menuone,noselect'

-- nvim-cmp setup
local cmp = require('cmp')
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(4),
    ['<C-u>'] = cmp.mapping.scroll_docs(-4),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'calc' },
    { name = 'path' },
    { name = 'spell' },
  },
  formatting = {
      format = function(entry, vim_item)
        vim_item.menu = ({
          nvim_lsp = '[LSP]',
          buffer = '[Buffer]',
          calc = '[Calc]',
          path = '[Path]',
          spell = '[Spell]',
        })[entry.source.name]
        return vim_item
      end,
  },
}
```

Is this expected behavior?
Why someone should be forced to use a snippet engine?

**Comment by hrsh7th** [comment]
You can manage the snippet by yourself.

https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#no-snippet-plugin

> Why someone should be forced to use a snippet engine?
That is just my decision.

**Comment by itaranto** [comment]
> You can manage the snippet by yourself.
> 
> https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#no-snippet-plugin
> 
> > Why someone should be forced to use a snippet engine?
> 
> That is just my decision.

Is there some *simple* configuration to disable snippets?

I believe a completion plugin should not force users to use a snippet engine.

**Comment by hrsh7th** [comment]
I think disabling the snippet feature will make a lot of issues (and I have to support it).
In fact, your LSP server returns snippet items.

You can use other completion engines like ddc.vim etc.
