### ISSUE TITLE
Problem in the autocomplete

### ISSUE THREAD

**Issue by Johan-Palacios** [hrsh7th/nvim-cmp#271]
System and nvim info:
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
WSL Ubuntu 20.04

Description of the problem

Recently I passed to cmp, but I have problems with the autocomplete, In C# language I have a problem with LSP autocomplete, you can see the video to watch the problem:

https://user-images.githubusercontent.com/77251405/135775472-73b4e9a4-0bdf-4420-bd1b-06d5d924de24.mp4

If the problem is that cmp does not detect well some LSP parameters and that causes that when it wanted to access the property of the “archivo”, cmp did not show them, for that reason it had to enter normal mode and then return to insert mode to show me the autocomplete, could you tell me some solution or if you can include a solution to this little inconvenience.

**Comment by etrnal70** [comment]
Looks very similar to #265 with rust-analyzer. Can you try the old nvim-compe to see if it works normal ?

**Comment by Johan-Palacios** [comment]
Ok, I try in NVIM-COMPE, but I have the same Issue

https://user-images.githubusercontent.com/77251405/135783354-690dd24f-3e78-4e35-a694-f3107bc0226f.mp4

In fact it is more difficult to work in NVIM-COMPE

**Comment by Johan-Palacios** [comment]
> Looks very similar to #265 with rust-analyzer. Can you try the old nvim-compe to see if it works normal ?

Yes I saw that, I think that is in a specific programming languages

**Comment by hrsh7th** [comment]
Please minimal repro steps. (I don't know your server and your file content)
