### ISSUE TITLE
Changing sources with `setup.buffer` does not work in some cases

### ISSUE THREAD

**Issue by spindensity** [hrsh7th/nvim-cmp#272]
# Description

Changing sources with `setup.buffer` does not work in some cases.

# Steps to Reproduce

1. Install the following plugins:
    - [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim);
    - [nvim-cmp](https://github.com/hrsh7th/nvim-cmp);
    - [cmp-buffer](https://github.com/hrsh7th/cmp-buffer);
    - [cmp-path](https://github.com/hrsh7th/cmp-path).

2. Prepare the directory(`~/repro_bug`) and the file(`~/repro_bug/README.md`) to reproduce the bug:

```bash
mkdir ~/repro_bug
cd ~/repro_bug
touch README.md
```

3. Start `neovim` with the following minimal configuration:

```lua
require("telescope").setup({})
local cmp = require("cmp")
cmp.setup({
    sources = {
        { name = "buffer" },
    },
})

vim.cmd([[
augroup nvim_cmp_settings_group
autocmd!
autocmd FileType TelescopePrompt lua require('cmp').setup.buffer { enabled = false }
autocmd FileType markdown lua require('cmp').setup.buffer { sources = { { name = 'path' } } }
augroup END
]])
```

4. In `neovim`, change the current working directory to `~/repro_bug`

```vim
:cd ~/repro_bug
```

5. Use `telescope.nvim` to open the file `~/repro_bug/README.md`, execute `:Telescope find_files`, select `README.md`, and press <kbd>Enter</kbd>
6. Check the sources with `:CmpStatus`.

# Expected behavior

The output of `:CmpStatus` should be:

```log
# ready source names:

- path

# unused source names:

- buffer
```

# Actual behavior

The output of `:CmpStatus`:

```log
# ready source names:

- buffer

# unused source names:

- path
```

# Additional information

If we delete `autocmd FileType TelescopePrompt lua require('cmp').setup.buffer { enabled = false }`, then everything is OK.

**Comment by hrsh7th** [comment]
I'm trying to reproduce it.

I think `autocmd FileType markdown` does not fire with the following config.

```
    augroup nvim_cmp_settings_group
      autocmd!
      autocmd FileType markdown echomsg 'markdown'
      autocmd FileType TelescopePrompt echomsg 'TelescopePrompt'
    augroup END
```

I can't support it. Because `cmp.setup.buffer` didn't called in this situation.

**Comment by hrsh7th** [comment]
I meant it doesn't echo `markdown` if I open the `README.md` by telescope.nvim.

**Comment by spindensity** [comment]
It's very strange, see the following configuration:

```lua
-- settings.lua
local M = {}
function M.test()
    vim.cmd("setlocal spell")
    require("cmp").setup.buffer({ sources = { { name = "buffer" }, { name = "spell" }, { name = "emoji" } } })
end

vim.cmd[[
  augroup nvim_cmp_settings_group
      autocmd!
      autocmd FileType markdown require("settings").test()
      autocmd FileType TelescopePrompt echomsg 'TelescopePrompt'
    augroup END
]]

return M
```

The first statement in the function `test` has been executed, but the second statement `require("cmp").setup.buffer({ sources = { { name = "buffer" }, { name = "spell" }, { name = "emoji" } } })` has no effect.

You can open a markdown file and input a misspelled word to validate it.
