### ISSUE TITLE
Support clangd's completion score extension

### ISSUE THREAD

**Issue by tom-anders** [hrsh7th/nvim-cmp#277]
See https://clangd.llvm.org/extensions#code-completion-scores

Is this something that could be added to nvim-cmp?

**Comment by dmitmel** [comment]
```lua
local cmp = require('cmp')
cmp.setup({
  -- ...

  sorting = {
    comparators = {
      function(entry1, entry2)
        local score1 = entry1.completion_item.score
        local score2 = entry2.completion_item.score
        if score1 and score2 then
          local diff = score1 - score2
          if diff < 0 then
            return true
          elseif diff > 0 then
            return false
          end
        end
      end,

      -- The built-in comparators:
      cmp.config.compare.offset,
      cmp.config.compare.exact,
      cmp.config.compare.score,
      cmp.config.compare.kind,
      cmp.config.compare.sort_text,
      cmp.config.compare.length,
      cmp.config.compare.order,
    };
  };

  -- ...
})
```

**Comment by hrsh7th** [comment]
Thank you! You can add it in the Wiki :)

**Comment by tom-anders** [comment]
Just or of curiosity, from the clangd docu:

> Clients that fuzzy client-side filtering should multiply score by their fuzzy-match score and sort by the result.
> Clients with non-fuzzy client-side filtering only should sort by score.
> Clients that don’t support client-side filtering should ignore this and use sortText, which incorporates score and fuzzy-matching.

Which one of these statements applies to cmp? Judging from the code snippet posted by @dmitmel it's the second one...?

**Comment by hrsh7th** [comment]
1. nvim-cmp supports fuzzy matching
2. The above example of comparetor uses only clangd's score only (does not multiply with client matching score)

**Comment by dmitmel** [comment]
I dunno, I didn't try it. As far as I understand, true being returned from a comparator means that the element A must come before B.
