### ISSUE TITLE
feature request: source from other lines of code similar to the one started

### ISSUE THREAD

**Issue by themarcel** [hrsh7th/nvim-cmp#283]
What I mean is that from a key combination, not by default, `cmp` will read the current buffer for similar lines to the one your are at. If it finds one that matches with your line, it gives you the rest.

```rust
async fn get_user() -> Result<User> {
    let url = format!("https://api.github.com/user");
    let user = make_json_request(&url).await?.json::<User>().await?;

    Ok(user)
}

async fn get_user_data( username: string ) -> Result<User> {
    let url = format!("https://api.github.com/{}", user);
    let user_data = make_json//_request(&url).await?.json::<User>().await?; <-- suggestion of cmp
```

I have a video example of where they use something similar at minute 45:00:
 https://www.youtube.com/watch?v=tAVxxdFFYMU

**Comment by Shougo** [comment]
It means complete with other buffer?

**Comment by marcelarie** [comment]
> Your description is hard to understand. Please describe it more clearly with example codes like other issues.

Yes it was a awful explanation, I just edited.

 

> It means complete with other buffer?

Well I was thinking only from the current buffer.

**Comment by Shougo** [comment]
OK.  I get it.  It seems line completion.
C-x C-l 
It is correct?

**Comment by marcelarie** [comment]
> OK. I get it. It seems line completion. C-x C-l It is correct?

That is what I was searching for :) Thanks!

**Comment by marcelarie** [comment]
I didn't know about `cmp.register_source`, thanks! I need to read more the documentation 😄
