### ISSUE TITLE
Cursor flickers when selecting next or previous item in custom menu

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#289]
This is a really minor issue, but I thought I would create an issue and see if there is anything that could be done with this. 

When selecting the next and previous item in the custom menu, the cursor flickers a bit. See the video below:

https://user-images.githubusercontent.com/5160701/136559314-ac47d32f-d9be-4d81-a69e-d6259e3f02cd.mov

This does not happen with the builtin one. See video below for comparison:

https://user-images.githubusercontent.com/5160701/136559414-e1b7047b-6062-4ad3-a3fc-3c006952e9ff.mov

Like I said, this is not a big problem, but it was something I noticed that bothered me a little bit. If you feel like this will be too hard to fix, or just doesn't bother, feel free to close the issue! 

Awesome work with the custom menu btw!

**Comment by hrsh7th** [comment]
@seblj I will try to fix it.

@captainko You can use native menu or other completion engine :)

**Comment by bluz71** [comment]
I am getting this as well.

I sporadically tested the development branch a couple times during the past few weeks, and I don’t recall seeing this issue (though I could be mistaken). Maybe a recent regression?

I am back to native menu, hopefully not for long.

**Comment by Shougo** [comment]
I think the implementation is changed to support repeat `.` feature.

**Comment by hrsh7th** [comment]
I think it should be solved by `set lazyredraw`.

I will investigate the workaround. But I think it can't fix perfectly.

**Comment by hrsh7th** [comment]
Is it fixed now...?

**Comment by kwkarlwang** [comment]
> Is it fixed now...?

After trying today's update, I no longer experience any flickering, thanks!

**Comment by bluz71** [comment]
> Is it fixed now...?

**Yes.**

No more flickery/jumpy cursor. Much much nicer.

Superb.

**Comment by seblj** [comment]
Yes, sorry for late response, but it also is fixed for me! Thank you!

**Comment by hrsh7th** [comment]
Hi, All of users.
If `set lazyredraw` will be the required option (for avoiding flicker), do feel it annoying?

**Comment by bluz71** [comment]
Yes, it causes problems.

Years ago I tested lazyredraw and concluded it had side effects, such as X delete backwards having weird rendering effects (from memory).

lazyredraw is not the default, probably for good reason.

My 2cents.

**Comment by hrsh7th** [comment]
Maybe I've supported undos/macros/dot-repeat with avoiding flicker. I've removed the breaking change announcement.
If anyone has another issue, feel free to create new issues.

**Comment by bluz71** [comment]
Thank you @hrsh7th , the cursor flicker is now fixed in commit [7a36a31](https://github.com/hrsh7th/nvim-cmp/commit/7a36a31331a75edae760d0bf49f200972cc38f56).

Excellent work and genuine thanks..
