### ISSUE TITLE
[BUG] cycling completion item creates multiple empty buffers

### ISSUE THREAD

**Issue by elianiva** [hrsh7th/nvim-cmp#3]
everytime the completion item is being cycled using `<C-n>` or `<C-p>`, an empty buffer gets created but never closed (though some of them *do* get closed). I don't think it's supposed to do that?

Here's the minimal config used in the screencast: https://paste.sh/P0YU62dw#2DgBpe53f9BnJv5z08Se4SII

https://user-images.githubusercontent.com/51877647/128645905-af021285-a337-43af-9dde-89fee79f9cd0.mp4

**Comment by hrsh7th** [comment]
Thank you. It was a bug. I've fixed it.
