### ISSUE TITLE
Depreciated items are no longer crossed out / broken graphics in the documentation

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/nvim-cmp#302]
The new menu does look and feel better but there seems to be some big problems.

Using neovim 0.5.1 appimage and latest nvim-cmp with the new menus and the deno language server:

`deno.buffer` is depreciated and used to have a cross through it, also 'ected' has appeared from nowhere:
![Screenshot from 2021-10-09 09-40-09](https://user-images.githubusercontent.com/12832280/136651256-050d67e5-ac5a-4b04-8e1d-f6a59b424349.png)

documentation window has gone very wrong:
![Screenshot from 2021-10-09 09-40-26](https://user-images.githubusercontent.com/12832280/136651251-1ebd55fc-d481-4463-ba55-28c74dd0b040.png)

Some kind of terrible bug is plaguing this:
![Screenshot from 2021-10-09 09-40-18](https://user-images.githubusercontent.com/12832280/136651254-4f03aeb4-5ef1-407c-b91f-a43f91f84e03.png)

There are very similar problems on the latest `0.6 master` branch too:

![Screenshot from 2021-10-09 09-51-24](https://user-images.githubusercontent.com/12832280/136651524-3f9c971a-5f13-4184-9084-de0d8aa46aea.png)

**Comment by David-Else** [comment]
I found the answer, I have the following lines added to stop the virtual text and instead show the diagnostics on putting the cursor on the error... I think it is much better:

```lua
-- Turn off virtual text
vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
  virtual_text = false,
})

-- Show diagnostics on cursor over and stop window being focusable
vim.cmd [[autocmd CursorHold,CursorHoldI * lua vim.lsp.diagnostic.show_line_diagnostics({focusable=false})]]
```
Now it shows the error right on top of and in the documentation window, you can see the error in red on the last image I attached above. It seems the message is white in version `0.5.1`.

**Comment by hrsh7th** [comment]
OK. I get the reason too.
I think you don't need the `CursorHoldI` (Because in insert-mode, some other plugins will show the another floating window so It easy to conflict with `show_line_diagnostics`.

**Comment by David-Else** [comment]
Thanks, that fixes it :)
