### ISSUE TITLE
Error executing vim.schedule lua callback: ...cker/start/nvim-cmp/lua/view/custom_entries_view.lua:119: Invalid buffer id: 3

### ISSUE THREAD

**Issue by lostl1ght** [hrsh7th/nvim-cmp#306]
Completion stopped working after update `ada9dde`.

I get error `Error executing vim.schedule lua callback: ...cker/start/nvim-cmp/lua/view/custom_entries_view.lua:119: Invalid buffer id: 3`

My completion setup:
```lua
-- Completion settings
vim.o.completeopt = 'menu,menuone,noselect'
local luasnip = require 'luasnip'
local cmp = require 'cmp'
cmp.setup {
    snippet = {
        expand = function(args)
            luasnip.lsp_expand(args.body)
        end,
    },
    mapping = {
        ['<C-p>'] = cmp.mapping.select_prev_item(),
        ['<C-n>'] = cmp.mapping.select_next_item(),
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.close(),
        ['<CR>'] = cmp.mapping.confirm {
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
        },
        ['<Tab>'] = function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
                vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
            else
                fallback()
            end
        end,
        ['<S-Tab>'] = function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '')
            else
                fallback()
            end
        end,
    },
    sources = {
        { name = 'buffer' },
        { name = 'nvim_lsp' },
        { name = 'luasnip' },
        { name = 'vim-dadbod-completion' },
    },
}
```

**Comment by sQVe** [comment]
Already an issue open: https://github.com/hrsh7th/nvim-cmp/issues/293.

**Comment by sQVe** [comment]
Already an issue open: https://github.com/hrsh7th/nvim-cmp/issues/293.

**Comment by lostl1ght** [comment]
> Already an issue open: #293.

I believe this is a different issue. They a having an error produced by `cmp-buffer` while I'm having an error by `nvim-cmp'.

**Comment by Shatur** [comment]
> How to reproduce it? I can't reproduce...

Try the following configuration, I can reproduce it with with any keystroke in INSERT mode.

```lua
local cmp = require('cmp')
cmp.setup({
  sources = {
    { name = 'buffer' },
  },
})
```

**Comment by hrsh7th** [comment]
No, it has not been reproduced. If it is a minimal reproduction condition, it cannot be overlooked.

**Comment by hrsh7th** [comment]
@vxio Thank you. I will try with this external plugin.

**Comment by Shatur** [comment]
> @Shatur I noticed this bug also happens for me, but only after I switch sessions using https://github.com/Shatur/neovim-session-manager (awesome plugin btw)

Wow, yes! The issue happens with my plugin.
I think that the problem may be related to the fact that buffers are deleted when switching a session:
https://github.com/Shatur/neovim-session-manager/blob/2e984a17b00224cb3b34d801cd8ad371f194a76d/lua/session_manager/utils.lua#L46-L54
