### ISSUE TITLE
Autocomplete not working with code in Rust Docs

### ISSUE THREAD

**Issue by kawaki-san** [hrsh7th/nvim-cmp#31]
Awesome work on the plugin, works almost perfectly for me,
Just one problem though, I don't get autocomplete in Rust docs, works outside of it though.

I'm using the default capabilities provided [here](https://github.com/hrsh7th/cmp-nvim-lsp#setup)

Something else I need to check?

**Comment by hrsh7th** [comment]
@kawaki-san Thank you for your words.

Sorry. I don't familiar with Rust. So I can't understand Rust Docs mean correctly.

**Comment by kawaki-san** [comment]
Okay so if you have a look [here](https://docs.rs/tokio/1.10.0/tokio/#examples)
That code isn't in a regular rust program, it's placed inside what is called doc comments but its rendered in HTML like actual code. They look like this:
```rs
///
/// # Example
/// ```
/// # fn main() {
///        // auto complete doesn't work here
///        code.with.auto.complete();
/// # }
///
fn main(){
    //auto complete works here
}
 ```
My auto complete doesn't work in the /// blocks.
I'm thinking maybe it's a config issue with LSP?

**Comment by hrsh7th** [comment]
@kawaki-san I tried it with the coc (It is best LSP client in my knowledge.) but it's the same behavior.

I think the rust-analyzer doesn't support it. If you want to support it, you should open issue in rust-analyzer repo, I think.

**Comment by kawaki-san** [comment]
Thanks buddy. Keep up the good work! I'll close this.
