### ISSUE TITLE
Highlighting problem with the floating window menu

### ISSUE THREAD

**Issue by spindensity** [hrsh7th/nvim-cmp#317]
# Description

There is a highlighting problem with the floating window menu:

![Snipaste_2021-10-10_13-57-25](https://user-images.githubusercontent.com/33576822/136684385-5742bbfe-4442-4fc7-bd35-16a9024cc845.png)

# Steps to reproduce:

1.  Install the following plugins:
    - [nvim-cmp](https://github.com/hrsh7th/nvim-cmp);
    - [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp);
    - [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

2. Create minimal `neovim` configuration file:

```lua
local lspconfig = require("lspconfig")

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require("cmp_nvim_lsp").update_capabilities(capabilities)

lspconfig.clangd.setup({
    capabilities = capabilities,
})

local cmp = require("cmp")
cmp.setup({
    sources = {
        { name = "nvim_lsp" }
    }
})
```

3. Prepare the environment to reproduce the bug:
    1. Make sure [cmake](https://cmake.org/) and [clangd](https://clangd.llvm.org/) are in your `PATH`;
    2. Create the sample project:
```bash
mkdir test

cd test

cat <<EOF > test.cpp
#include <vector>

int main() {
    std::vector<int> v;
    return 0;
}
EOF

cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.12)
project(test VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)

add_executable(test test.cpp)
EOF

cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=1 .
```

4. Open `test.cpp` with `neovim` with the above minimal configuration file, do what the above picture shows.

# Expected behavior

No highlighting problems.

# Actual behavior

![Snipaste_2021-10-10_13-57-25](https://user-images.githubusercontent.com/33576822/136684385-5742bbfe-4442-4fc7-bd35-16a9024cc845.png)

**Comment by hrsh7th** [comment]
Duplicate #294
