### ISSUE TITLE
BUG: Completion menu breaks with floats

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-cmp#320]
Hey everyone
After switching to the new float menu (btw, crazy good) I started to notice completion menu going all over the place when I use it in popup/float window

<img width="1312" alt="Screen Shot 2021-10-10 at 4 44 48 PM" src="https://user-images.githubusercontent.com/65782666/136698398-59515d60-6d5a-4010-935b-f3ec5fb503c2.png">

**Comment by tami5** [comment]
here's another example. 

<img width="1312" alt="Screen Shot 2021-10-10 at 5 32 11 PM" src="https://user-images.githubusercontent.com/65782666/136700170-b74c6a2a-116f-4ebd-9a02-d6911c001932.png">

> You have an issue that custom menu will place to the wrong place if the cursor on another floating window, right?

Basically, the positioning is wrong when using cmp inside a floating window

**Comment by hrsh7th** [comment]
I've fixed.

**Comment by tami5** [comment]
No longer an issue, well done
