### ISSUE TITLE
Feature: Item Kind Highlight groups

### ISSUE THREAD

**Issue by danielnehrig** [hrsh7th/nvim-cmp#327]
It would be cool if we could specify/overwrite for each Item Kind our own Highlights
So for instance item kind Function is 'Blue' and snippet is 'orange'

**Comment by hrsh7th** [comment]
How to realize it? If you have an idea, feel free to post it.
(CmpKindFunction, CmpKindInterface ...)?

**Comment by danielnehrig** [comment]
Correct kind of like this:
`CmpKind .. kind_name`

on the setup function we could introduce a table:
```
kind = {
  Function = "#3d3d3d",
  Snippet = "...",
  ...
}
```
The table is used to compose highlights

**Comment by danielnehrig** [comment]
thanks!

**Comment by Dan7h3x** [comment]
> It would be cool if we could specify/overwrite for each Item Kind our own Highlights So for instance item kind Function is 'Blue' and snippet is 'orange'

I do it by creating custom highlight groups
https://github.com/Dan7h3x/NvimPy
