### ISSUE TITLE
Is there a plan to add vim-lsp as a source?

### ISSUE THREAD

**Issue by jbarik** [hrsh7th/nvim-cmp#329]
I guess vim-lsp is not a priority for you to add as a source, still I would like to know if you plan to add it anytime soon. 

I use ccls with vim-lsp. I tried switching to nvim-lspconfig, but for some reason my cpu usage shoots through the roof when I use the built-in lsp feature. Was forced to switch back to vim-lsp.

I would love to see nvim-cmp support vim-lsp.

Thank you.

**Comment by mjlbach** [comment]
> I use ccls with vim-lsp. I tried switching to nvim-lspconfig, but for some reason my cpu usage shoots through the roof when I use the built-in lsp feature. Was forced to switch back to vim-lsp.

Which version of neovim are you on? This should not be the case (sorry to hijack the issue).

**Comment by mjlbach** [comment]
Ah, you're free to override the root detection ordering in your setup call to whatever logic would detect the appropriate root for your codebase.

**Comment by mjlbach** [comment]
No, there's always a minimal amount of logs by default (start stop client and errors)

**Comment by hrsh7th** [comment]
@dmitmel is implemented this. Thank you!
