### ISSUE TITLE
disable theme/coloring in menu condidats

### ISSUE THREAD

**Issue by ccshao** [hrsh7th/nvim-cmp#331]
How to disable the coloring of candidates? I mean the matched characters are highlighted, and other characters are grey. Quite fancy, but to me the color is distractive. Thanks!

![Screenshot_2021-10-11_11-40-30](https://user-images.githubusercontent.com/4980631/136769036-1047f547-8d13-4b02-89b0-c0bd059ec0a2.png)

**Comment by app** [comment]
> You can use
> 
> ```
> highlight! link CmpItemAbbr Pmenu
> highlight! link CmpItemKind Pmenu
> highlight! link CmpItemMenu Pmenu
> ```

Why not make this the default?
I had to do the same for my Solarized color scheme after searching a lot.
