### ISSUE TITLE
Duplicate entries shown when using svelte language server

### ISSUE THREAD

**Issue by charbelnicolas** [hrsh7th/nvim-cmp#334]
When having the svelte language server enabled, the completion menu will always show duplicates entries.

Here is a small video showing the issue:

https://user-images.githubusercontent.com/14960414/136828537-ddcc92cb-c689-4be5-8222-16c28a044233.mp4

This only happens with svelte files as far as I know.

Here is a file for you to try it on:

[sveltefile.zip](https://github.com/hrsh7th/nvim-cmp/files/7324237/sveltefile.zip)

**Comment by hrsh7th** [comment]
I didn't know how to setup svelte environment.
Please reproduction steps.

**Comment by hrsh7th** [comment]
And You should check `LspInfo`.

**Comment by charbelnicolas** [comment]
CmpStatus:

# ready source names                                                                                                                                                                                             
- nvim_lsp:svelte                                                                                                                                                                                                
- buffer                                                                                                                                                                                                         
- path

**Comment by charbelnicolas** [comment]
Yep, thank you.
