### ISSUE TITLE
whenever I type in a tex file I get an error

### ISSUE THREAD

**Issue by momofor** [hrsh7th/nvim-cmp#336]
Every time I type in tex files I get this error: 
`Error detected while processing CursorHold Autocommands for "*":                                                  
method textDocument/codeAction is not supported by any of the servers registered for the current buffer`

I'm using texlab langserver and this is the output of CmpStatus:
    `   # ready source names                                                                                              
        - path                                                                                                            
        - nvim_lsp:texlab                                                                                                 
        - luasnip                                                                                                         
        - buffer  `
this is the output of LspInfo:
` 
       Language client log: /home/momofor/.cache/nvim/lsp.log
       Detected filetype:   tex
       
       1 client(s) attached to this buffer: 
       
       Client: texlab (id: 2, pid: 5238, bufnr: [1, 1, 1, 1, 1])
 	      filetypes:       tex, bib
 	      autostart:       true
 	      root directory:  /home/momofor/.other/programs/noice
 	      cmd:             texlab
       
       1 active client(s) not attached to this buffer: 
       
       Client: texlab (id: 1, pid: 5198, bufnr: [])
 	      filetypes:       tex, bib
 	      autostart:       true
 	      root directory:  /home/momofor/.other/programs/noice
 	      cmd:             texlab
       
       Configured servers list: texlab
    `

and my configuration is: 

    local cmp = require 'cmp'
    
    local cmp_kinds = {
        Class = ' ',
        Color = ' ',
        Constant = 'ﲀ ',
        Constructor = ' ',
        Enum = '練',
        EnumMember = ' ',
        Event = ' ',
        Field = ' ',
        File = '',
        Folder = ' ',
        Function = ' ',
        Interface = 'ﰮ ',
        Keyword = ' ',
        Method = ' ',
        Module = ' ',
        Operator = '',
        Property = ' ',
        Reference = ' ',
        Snippet = ' ',
        Struct = ' ',
        Text = ' ',
        TypeParameter = ' ',
        Unit = '塞',
        Value = ' ',
        Variable = ' '
    }
    local luasnip = require "luasnip"
    require('luasnip.loaders.from_vscode').lazy_load()
    vim.opt.completeopt = 'menuone,noselect'
    cmp.setup({
        formatting = {
            format = function(entry, vim_item)
                vim_item.kind = string.format('%s %s', cmp_kinds[vim_item.kind],
                                              vim_item.kind)
                vim_item.menu = ({
                    nvim_lsp = '[LSP]',
                    luasnip = '[Snp]',
                    buffer = '[Buf]',
                    nvim_lua = '[Lua]',
                    path = '[Pth]',
                    calc = '[Clc]',
                    emoji = '[Emj]'
                })[entry.source.name]
    
                return vim_item
            end
        },
        snippet = {
            expand = function(args)
			    require('luasnip').lsp_expand(args.body)
		    end
        },
        mapping = {
            ['<C-n>'] = cmp.mapping.select_next_item({
                behavior = cmp.SelectBehavior.Insert
            }),
            ['<C-p>'] = cmp.mapping.select_prev_item({
                behavior = cmp.SelectBehavior.Insert
            }),
            --[[ ['<Tab>'] = cmp.mapping.select_next_item({
                behavior = cmp.SelectBehavior.Select
            }),
            ['<S-tab>'] = cmp.mapping.select_prev_item({
                behavior = cmp.SelectBehavior.Select
            }), ]]
            ['<Tab>'] = function(fallback)
                if cmp.visible() then
                    cmp.select_next_item()
                elseif luasnip.expand_or_jumpable() then
                    luasnip.expand_or_jump()
                else
                    fallback()
                end
            end,
            ['<S-Tab>'] = function(fallback)
                if cmp.visible() then
                    cmp.select_prev_item()
                elseif luasnip.jumpable(-1) then
                    luasnip.jump(-1)
                else
                    fallback()
                end
            end,
            ['<C-d>'] = cmp.mapping.scroll_docs(-4),
            ['<C-f>'] = cmp.mapping.scroll_docs(4),
            ['<C-Space>'] = cmp.mapping.complete(),
            ['<C-e>'] = cmp.mapping.close(),
            ['<CR>'] = cmp.mapping.confirm({
                behavior = cmp.ConfirmBehavior.Replace,
                select = true
            })
        },
        sources = {
            {name = 'nvim_lsp'},{name = 'luasnip'} ,{name = 'buffer'},
            {name = 'path'}
        }
    })
Any help is appreciated, thanks in advance.

**Comment by momofor** [comment]
Sorry about that I don't what's the minimal reproducible configuration to get this error but this lang server works fine with nvim-compe

**Comment by stoicAlchemist** [comment]
For anyone that faces this issue in the future, this is not a nvim-cmp issue, it might be related to the `glepnir/lspsaga.nvim` plugin.

**Comment by momofor** [comment]
It actually is related to the glepnir/lspsaga.nvim plugin as it didn't  support the latest version of neovim but now it's forked and under developement again so it works.
