### ISSUE TITLE
How to change highlight for selected item

### ISSUE THREAD

**Issue by mhanberg** [hrsh7th/nvim-cmp#339]
Hi!

Switching over from nvim-compe finally, and and figuring out the highlights for my theme.

I'm not really sure how to style the currently selected item in the menu, is there a way to do this?

This is what I currently see, the selected item is `from_native/3~` (the fourth entry).
<img width="378" alt="image" src="https://user-images.githubusercontent.com/5523984/136964818-afb92271-c761-496b-8388-50c15fbec6fa.png">

Thanks!

**Comment by hrsh7th** [comment]
Ah....!!! Sorry! I say the wrong.

It's `PmenuSel` by default.
