### ISSUE TITLE
Completion auto adds paretheses.

### ISSUE THREAD

**Issue by talbergs** [hrsh7th/nvim-cmp#342]
When the method is completed and does not accept parameters, parentheses are auto inserted.
Is there any way to configure this behaviour?

Effectively - I would then be able to configure this to never auto insert such parentheses.

**Comment by ecosse3** [comment]
I had the same problem today but now I cannot reproduce it. Right now after selecting some items from cmp menu it duplicates the text which I have written. Maybe it's related. I use tsserver. Demo below:

![Peek 2021-10-13 01-03](https://user-images.githubusercontent.com/17691791/137040429-9f19fae0-b353-47f6-8376-3469d84dbb24.gif)
