### ISSUE TITLE
Floating window scrollbar highlight is incorrect the when it first opens

### ISSUE THREAD

**Issue by akinsho** [hrsh7th/nvim-cmp#345]
When the floating menu first opens the scroll bar appears to have a thumb but the track is invisible, I'm not sure what highlight group is used to style it but it appears not to be exposed or to change since after completing a few characters the track then becomes visible.

![cmp-scroll-bug](https://user-images.githubusercontent.com/22454918/137103344-97932ed4-da48-40e1-bf07-97718224909c.gif)

**Comment by EdwarKenedy** [comment]
hi @akinsho i had the same issue, try changing the highlight background from ```EndOfBuffer``` to none

**Comment by akinsho** [comment]
@EdwarKenedy thanks but I haven't actually set the highlights for that window explicitly
