### ISSUE TITLE
After expanding menu selection it duplicates suggested text

### ISSUE THREAD

**Issue by ecosse3** [hrsh7th/nvim-cmp#351]
Hi, after the last updates I have a problem with cmp. After I try to expand some LSP/Snippet/TabNine suggestion it duplicates it instead of replacing it. I use mostly UltiSnips.

Demo:

![137040429-9f19fae0-b353-47f6-8376-3469d84dbb24](https://user-images.githubusercontent.com/17691791/137195444-1987dba0-8852-4648-a4c2-b8ef9dc6d7af.gif)

My cmp config:
```
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
      vim.fn["UltiSnips#Anon"](args.body)
    end
  },

  -- You must set mapping if you want.
  mapping = {
    ['<C-b>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
    ['<Tab>'] = function(fallback)
      if vim.fn.complete_info()["selected"] == -1 and vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
        press("<C-R>=UltiSnips#ExpandSnippet()<CR>")
      elseif vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
        press("<ESC>:call UltiSnips#JumpForwards()<CR>")
      elseif cmp.visible() then
        cmp.select_next_item()
      elseif has_any_words_before() then
        press("<Tab>")
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
  },
},
```

I use typescript-language-server mostly. I have nvim-autopairs installed but I'm not sure if it can be related.

It breaks like that also with Tabnine suggestions:

![Peek 2021-10-13 20-49](https://user-images.githubusercontent.com/17691791/137195539-13577750-f84c-4764-a23e-ac194513656d.gif)

Setting `behavior = cmp.ConfirmBehavior.Replace` in `<CR>` mapping didn't change anything.

Please let me know if I can provide you with some more debug info. Thanks!

**Comment by tinytub** [comment]
meet same issue

**Comment by ecosse3** [comment]
Thank you! I thought it was required to make UltiSnips work. It works now correctly.
