### ISSUE TITLE
Char before inserted completion is deleted, if line is indented by tabs

### ISSUE THREAD

**Issue by crater2150** [hrsh7th/nvim-cmp#352]
When completing from the `nvim-lsp` source (using Scala Metals language server), one char before the inserted completion is deleted, e.g. the dot before a method or a parenthesis in front of the completed word.
After long config bisecting, I found that this curiously only happens, if the line is indented by tabs, not if it is indented by spaces.

Here is a recording of the behaviour (showing the difference between space and tab indents):
https://asciinema.org/a/RvlyJNxrJ9R8oQU1XT4kvfNmk

The full configuration used (https://gist.github.com/crater2150/256d81bf766144e4158176e632bb8ac8, mostly from Readme + Metals config):
```
call plug#begin(expand('<sfile>:p:h') . '/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/nvim-cmp'
Plug 'nvim-lua/plenary.nvim'
Plug 'scalameta/nvim-metals'

Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'

call plug#end()

set completeopt=menu,menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'vsnip' },
      { name = 'buffer' },
    }
  })

  -- Setup lsp.
  metals_config = require("metals").bare_config
  metals_config.init_options.statusBarProvider = "on"
  metals_config.settings = { showImplicitArguments = true }
  metals_config.on_attach = on_attach
  metals_config.capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
EOF
augroup lsp
	au!
	au FileType scala,sbt lua require("metals").initialize_or_attach({})
augroup end
```
I'm not sure if this is specific to the metals language server, as I don't use any others currently. I may be able to try out something else tomorrow evening.
The small Scala example used in the recording can be found at https://github.com/crater2150/nvim-cmp-bug-demo

**Comment by hrsh7th** [comment]
I don't met this problem with `gopls`.

The golang is always uses the `Tab` for indentation.

**Comment by elianiva** [comment]
I found this issue on both tsserver and gopls. Though I doesn't seem to be consistent? Most of the time it happens when I type some characters and then confirm the first suggestion. I've attached a screencast to better explain it.

https://user-images.githubusercontent.com/51877647/139686298-4b83f9d8-a667-47ae-a02d-54a597b6a2d2.mp4

[Minimal init.lua](https://paste.sh/NvknKQut#4VYiWY4-Dn_MtWxTy23HQZmM)

**Comment by hrsh7th** [comment]
@elianiva Thank you for your information. It's very helpful and I could reproduce.

In the first place, I feel that the native menu of nvim-cmp is not working properly.

I will fix it...

**Comment by hrsh7th** [comment]
I'm sorry. The native menu just didn't work because the main branch was buggy a while ago.

I will re-test it.

**Comment by hrsh7th** [comment]
Oh... after updating gopls, I'd reproduce it too.

**Comment by hrsh7th** [comment]
@elianiva Thank you. I've fixed it by https://github.com/hrsh7th/nvim-cmp/commit/a881adb1d7da9946f3ba204c9426f78a7dc4af42

Hm... but I think the original issue report does not relate to this fix...

**Comment by dolenam317** [comment]
> I don't met this problem with `gopls`.
> 
> The golang is always uses the `Tab` for indentation.

I am having this same issue with gopls as well.

**Comment by hrsh7th** [comment]
@dolenam317 Could you provide the reproduction steps and minimal configuration?

**Comment by lumbo7332** [comment]
I think mine might be a related issue. Typing in insert mode constantly prints `Pattern not found`, but only if `native_menu` is enabled. I can get it to reproduce with `sumneko_lua, `pyright`, and `rust_analyzer`.

**Comment by Shougo** [comment]
> @dolenam317 Could you provide the reproduction steps and minimal configuration?

Please see this.
You need to upload the minimal configuration and the reproduction steps.

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/352#issue-1025728784

I think the config can be more reduced.

**Comment by crater2150** [comment]
It looks like the problem has gone away with the update to neovim 0.7
