### ISSUE TITLE
Error when naming Rust function paramater

### ISSUE THREAD

**Issue by heygarrett** [hrsh7th/nvim-cmp#354]
My ignorance of Rust (and Neovim, to be honest) might make it difficult to explain this issue, but I can reproduce it consistently with a minimal.lua:

<details><summary>Click to expand minimal.lua</summary>

```lua 
vim.api.nvim_command('autocmd BufWritePost packer.lua source <afile> | PackerCompile')

local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	vim.fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
	vim.api.nvim_command('packadd packer.nvim')
end

require('packer').startup {
	function(use)
		use 'wbthomason/packer.nvim'
		use 'neovim/nvim-lspconfig'
		use {'hrsh7th/nvim-cmp', requires = {
			'hrsh7th/cmp-nvim-lsp',
			{'saadparwaiz1/cmp_luasnip', requires = {
				'L3MON4D3/LuaSnip'}}}}

	end
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
require('lspconfig').rust_analyzer.setup {
	capabilities = capabilities
}

vim.opt.showmode = false
local cmp = require('cmp')
cmp.setup {
	snippet = {
		expand = function(args)
			require('luasnip').lsp_expand(args.body)
		end
	},
	mapping = {
		['<CR>'] = cmp.mapping.confirm {
			behavior = cmp.ConfirmBehavior.Replace,
			select = true,
		},
	},
	sources = {
		{name = 'luasnip'},
		{name = 'nvim_lsp'},
	},
	formatting = {
		format = function(entry, vim_item)
			vim_item.menu = ({
				luasnip = '[luasnip]',
				nvim_lsp = '[LSP]',
			})[entry.source.name]
			return vim_item
		end,
	},
	experimental = {native_menu = true},
}
```

</details>

## Steps to reproduce

1. Type `fn` in a blank Rust file  
2. Select `fn~` from the completion menu
3. Name the function (eg, test)
4. Exit insert mode
5. Enter insert mode between the parentheses  
6. Type `num`

## Expected behavior

No error.

## Actual behavior

> Error executing vim.schedule lua callback: ...cker/start/nvim-cmp/lua/cmp/view/native_entries_view.lua:44: attempt to call method 'preselect' (a number value)

## Additional info

> ❯ nvim --version
> NVIM v0.6.0-dev+nightly-985-g6b9cb665f
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by garrett@Harmon.local
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-6b9cb66/share/nvim"

**Comment by lourenci** [comment]
This is happening here as well with Golang. Just type something and You'll get the same exact error.
