### ISSUE TITLE
Completion gets selected automatically after timeout

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-cmp#355]
Hi,

Looks like a strange behavior has been happening for me on python files (could not recreate on any other file types).
Check the following screencast:
![Peek 2021-10-14 11-44](https://user-images.githubusercontent.com/4946827/137284280-bd58d49d-53cb-427f-b316-dad217e8e92d.gif)

After typing in `var`, I get suggested two options: `var_a` and `var_b`. When  scrolling to either of them, the list of suggestions gets trimmed as if I selected the item (when in fact I did not press any key).

This happens most consistently when I have `nvim_lsp` enable.

Any ideas?

**Comment by shaksiper** [comment]
I confirm this is an issue after recent update.

**Comment by hrsh7th** [comment]
I can't reproduce it. Please detailed instruction for reproduction.

**Comment by tzachar** [comment]
Here is the minimal config to reproduce (not so minimal, as I need to set up an LSP): [init.lua.zip](https://github.com/hrsh7th/nvim-cmp/files/7357131/init.lua.zip)

The problem can be reproduced when editing the following file:
```py
import numpy as np

var_a = [1, 2, 3]
var_b = [2, 3, 4]

var_
```

When opening the file while the curser is right after the last `var_` and you trigger a completion, if you quickly navigate to the first suggestions, all other suggestions will disappear after a short timeout. I think this has something to do with LSP adding suggestions after cmp-buffer in an async manner, as the issue will not pop up if the menu gets populated with LSP entries when it frst opens up.

Attaching the behaviour I get:
![Peek 2021-10-16 10-36](https://user-images.githubusercontent.com/4946827/137578498-32007e5f-03bb-4384-b59b-fcd70444e03f.gif)
This hapens when I only enter Insert mode, and navigate to the first suggestion entry.

**Comment by marcelarie** [comment]
![cmp](https://user-images.githubusercontent.com/62728887/137585940-feb04e35-5486-4014-9097-fa55d7caa8d6.gif)

**Comment by hrsh7th** [comment]
Oh. This issue also reproduce with rust-analyzer? It's helpful.

**Comment by marcelarie** [comment]
> I can't find the `python` server on [https://github.com/williamboman/nvim-lsp-installer/tree/main/lua/nvim-lsp-installer/servers](https://github.com/williamboman/nvim-lsp-installer/tree/main/lua/nvim-lsp-installer/servers?rgh-link-date=2021-10-16T12%3A24%3A40Z)
> 
> And I can't reproduce with rust-analyzer...
> 
> Could you provide the minimal rust content for reproducing? @marcelarie

Yes of course. You just need to create a new cargo project and put this on the `main.rs`:
```rust
pub trait Summary {
    fn summarize(&self) -> String;
}

pub struct NewsArticle {
    pub headline: String,
    pub location: String,
    pub author:   String,
    pub content:  String,
}

impl Summary for NewsArticle {
    fn summarize(&self) -> String {
        format!("{}, by {} ({})", self.headline, self.author, self.location)
    }
}

impl NewsArticle {
    pub fn new(
        headline: String,
        location: String,
        author: String,
        content: String,
    ) -> NewsArticle {
        NewsArticle {
            headline,
            location,
            author,
            content,
        }
    }
}

fn main() {
    let a = NewsArticle::new(
        String::from("New Rust program!"),
        String::from("Spain"),
        String::from("Me"),
        String::from("zoxide, git delta, "),
    );

    println!("{}", a.summarize());
    println!("{}", a.author);
}
```

**Comment by hrsh7th** [comment]
Hm... I believe this behavior is just `preselect` feature.

Could you reproduce with `preselect = cmp.PreselectMode.None`?
@marcelarie

**Comment by tzachar** [comment]
I have preselct set to None.

**Comment by marcelarie** [comment]
> Hm... I believe this behavior is just `preselect` feature.
> 
> Could you reproduce with `preselect = cmp.PreselectMode.None`? @marcelarie

Fantastic! Do you still need this?
