### ISSUE TITLE
<c-c> shortcuts are broken in insert mode when using nvim-cmp

### ISSUE THREAD

**Issue by Glavnokoman** [hrsh7th/nvim-cmp#359]
`imap <c-c>` does not show anything apart from the shortcuts I defined (they are all two-phase, like <c-c><c-c>). Yet when I hit <c-c> in insert mode I'm dropped to the normal mode. If  I remove the nvim-cmp plugin folder everything works as expected. I did not explicitly defined anything with <c-c> in `cmp.setup({mapping})` so that is quite unexpected.

**Comment by hrsh7th** [comment]
I'd remove the `<C-c>` mapping by default.
