### ISSUE TITLE
0x0 when use `complete` 

### ISSUE THREAD

**Issue by lourenci** [hrsh7th/nvim-cmp#36]
I don't know why, but every time I try to force the completion (`<c-space>`), it inserts `0x0`. Do you know what I'm doing wrong?

My mappings:
```lua
local cmp = require'cmp'

cmp.setup {
  snippet = {
    expand = function(args)
      -- You must install `vim-vsnip` if you set up as same as the following.
      vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<C-y>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    })
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' }
  },
}
```

**Comment by hrsh7th** [comment]
Sorry gor lately reply.
How to solve this problem?

**Comment by lourenci** [comment]
It wasn’t a problem with the plugin itself. I don’t know why, but it seems 0x0 is being sent through tmux when I start it in `tmux -CC` mode. Outside that environment, the plugin works like a charm, even in tmux (without -CC mode).

Thank you and sorry for the inconvenience.

**Comment by hrsh7th** [comment]
Thank you for detailed explain. Good to hear!
