### ISSUE TITLE
nvim-cmp impedes neovim from showing the correct file title in the taskbar (when file is modified +)

### ISSUE THREAD

**Issue by charbelnicolas** [hrsh7th/nvim-cmp#366]
When having nvim-cmp installed as a plugin, if you have `vim.opt.title = true` in the neovim configuration, nvim-cmp will mess up the title for modified files and it will only show as [NO NAME] instead of the actual name of the file.

Using `nvim --clean` and then doing `:set title` works correctly with modified files.

Here is a small video of the issue when using cmp:

https://user-images.githubusercontent.com/14960414/137601768-a9b4cfa0-18e0-4adb-b686-defec4826cee.mp4

**Comment by hrsh7th** [comment]
yes. it's duplicated.
