### ISSUE TITLE
How to disable documentation-window?

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-cmp#37]
Hi. Is it possible to disable the documentation-window from being displayed all the time? I like to open it manually when I need it. With compe I could do so by setting `documentation = false;`
I tried `documentation = { },` in cmp but it didn't work. Thank you.

**Comment by hrsh7th** [comment]
I think `documentation = false` would work.

**Comment by astier** [comment]
Haha don't know why I didn't try it myself. Thanks.
