### ISSUE TITLE
cmp appends selected item to the nvim registers

### ISSUE THREAD

**Issue by EdwarKenedy** [hrsh7th/nvim-cmp#370]
Hi, i noticied that since commit ([0f28030aef5b7b15708aaed8ed90b94d206aa712](https://github.com/hrsh7th/nvim-cmp/commit/0f28030aef5b7b15708aaed8ed90b94d206aa712)) cmp appends entries to registers on every ```cmp.mapping.confirm()```  ```cmp.mapping.select_next_item()``` ``` cmp.mapping.select_prev_item()```

Minimal cmp config
```
local cmp = require("cmp")

cmp.setup({
  mapping = {
    ["<C-n>"] = cmp.mapping.select_next_item(),
    ["<C-p>"] = cmp.mapping.select_prev_item(),
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    ["<C-Space>"] = cmp.mapping.complete(),
    ["<C-e>"] = cmp.mapping.close(),
    ["<CR>"] = cmp.mapping.confirm({ select = true }),
  },
  sources = {
    { name = "buffer" },
  },
})
```

Steps to reproduce
1. create a test.txt file
2. write test and press enter
3. yank  test
4. check registers with ```reg``` command
5. type te and complete with cmp
6. check registers with ```reg``` command

**Comment by dmitmel** [comment]
I can confirm that I have the same problem. Here's an alternative reproduction:

1. Enter `hello world` in some buffer.
2. Do `ciw` on `hello`, start typing `wor` and complete the rest of `world`.
3. I expect the yank register to have `hello` because it was just deleted, but pasting shows that it contains `hello<80>kb<80>kb<80>kbworld` instead.

**Comment by dmitmel** [comment]
> `can't reproduce`

Very weird. For me, even the following vimrc is enough:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'hrsh7th/nvim-cmp' 
Plug 'hrsh7th/cmp-buffer' 
call plug#end()

lua <<EOF
local cmp = require("cmp")
cmp.setup({
  mapping = {
    ['<CR>'] = cmp.mapping.confirm(),
  },
  sources = {
    { name = "buffer" },
  },
})
EOF
```

Delete any word with the `c` key and complete something in its place, then try pasting.

**Comment by dmitmel** [comment]
> Please `echomsg &clipboard` option results.

`''` (with `echo string(&clipboard)`)

**Comment by dmitmel** [comment]
Nice. Thanks.
