### ISSUE TITLE
dates not matching

### ISSUE THREAD

**Issue by pwntester** [hrsh7th/nvim-cmp#374]
Hi,

Im using the nvim-LSP source with the ['zk'](https://github.com/mickael-menu/zk) LSP server which sends completion candidates such as the following upon entering `[[` (wikilink delimiter):

```
{
  additionalTextEdits = { {
      newText = "",
      range = {
        end = {
          character = 2,
          line = 33
        },
        start = {
          character = 0,
          line = 33
        }
      }
    } },
  data = "/Users/pwntester/Library/Mobile Documents/iCloud~md~obsidian/Documents/Pwntester/resources/meeting notes/2021-09-29 1800 - Team meeting.md",
  filterText = "📅 Week summary: resources/meeting notes/2021-09-29 1800 - Team meeting.md",
  kind = 18,
  label = "2021-09-29 1800 - Team meeting",
  textEdit = {
    newText = "[[2021-09-29 1800 - Team meeting]]",
    range = {
      end = {
        character = 4,
        line = 33
      },
      start = {
        character = 2,
        line = 33
      }
    }
  }
}
```

However when I enter `[[2021` I get no completions at all. I also dont get any completions with `[[team meeting` but I guess its because of the space. However entering `[[teammeeting` returns the expected results. Is there any issues with digits or dashes which may prevent the completion entries to match when entering `[[2021`?

Thanks!

**Comment by Feel-ix-343** [comment]
Did you ever get this to work with spaces in the lsp completions? I am working on [this](https://github.com/Feel-ix-343/obsidian-markdown-ls) and having the same issue
