### ISSUE TITLE
vsnip-expand doesn't work with emmet_ls.

### ISSUE THREAD

**Issue by singlexyz** [hrsh7th/nvim-cmp#379]
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#emmet_ls

<img width="218" alt="图片" src="https://user-images.githubusercontent.com/4456413/137974705-4b4f650c-a177-4676-8ac5-a6dfad2ba29d.png">

The snippet is showing, But `<Plug>(vsnip-expand-or-jump)` doesn't work.

And  `['<cr>'] = cmp.mapping.confirm({ select = true })` works.

**Comment by hrsh7th** [comment]
Because it isn't `vsnip's snippet`. It's LSP snippet.
