### ISSUE TITLE
Don't understand LSP config in example vimrc

### ISSUE THREAD

**Issue by BatmanAoD** [hrsh7th/nvim-cmp#382]
This feels like a dumb question, but what is `%YOUR_LSP_SERVER%` supposed to be in the example config file in the README? I'm not familiar with Lua syntax, and I don't know much about LSP. Is this supposed to be the name of a specific language server, and if so, do you need a separate `require...setup` call for every different language you want to use?

**Comment by dmitmel** [comment]
> Should I expect the example `capabilities` setting work for everything in that list? If so, would it make sense to just loop over a bunch of strings and use the `['server']` syntax to set them all up the same way?

Well, it is an option, but honestly I don't get why no tutorials tell you to do it like this:

```lua
local lspconfig = require('lspconfig')

local capabilities = vim.lsp.protocol.make_client_capabilities()
require('cmp_nvim_lsp').update_capabilities(capabilities)
lspconfig.util.default_config.capabilities = capabilities

lspconfig.rust_analyzer.setup {
  -- ...
}

lspconfig.tsserver.setup {
  -- ...
}

-- ...
```

**Comment by hrsh7th** [comment]
Yes. I think so, too. Can be improved.
I always welcome PR.

**Comment by aryklein** [comment]
This is how I did it:
```lua
-- Setup lspconfig.
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
local lspconfig = require('lspconfig')
local servers = { 'gopls', 'pyright' } --- in my example I'm using gopls and pyright servers

for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
        capabilities = capabilities
    }
end
```
