### ISSUE TITLE
I want to let nvim just using ultisnips in latex file while other file type sare using luaSnip, how to make it?

### ISSUE THREAD

**Issue by flaviusbuffon** [hrsh7th/nvim-cmp#387]

**Comment by hrsh7th** [comment]
```
lua EOF>>
cmp.setup {
  snippet = {
    expand = function()
      ... lua snip configuration
    end
  },
  sources = {
    { name = 'luasnip' }
  }
}
EOF

autocmd FileType tex lua require('cmp').setup.buffer {
\   snippet = {
\     expand = function() ... ultisnipet setup ... end,
\   },
\   sources = {
\     { name = 'ultisnips' }
\ }
\ }
```

I provided the functionality. You can realize what you want by that's. Enjoy.

**Comment by flaviusbuffon** [comment]
i am a truely noob,can you give me a more completely config example

thank!




发自我的华为手机


-------- 原始邮件 --------
发件人： hrsh7th ***@***.***>
日期： 2021年10月22日周五 半夜12:38
收件人： hrsh7th/nvim-cmp ***@***.***>
抄送： Flavius Buffon ***@***.***>, Author ***@***.***>
主 题： Re: [hrsh7th/nvim-cmp] I want to let nvim just using ultisnips in latex file while other file type sare using luaSnip, how to make it? (Issue #387)

You can setup the global configuration by cmp.setup { ... } and you can setup the buffer specific configuration by cmp.setup.buffer.

So you can use luasnip globally and can use ultisnips for the specific filetype or buffer.

**Comment by hrsh7th** [comment]
If you need to use ultisnips, I recommend to use ultisnips for everything.
