### ISSUE TITLE
customize completion menu with native CompletionItemKind instead of lspkind-nvim

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-cmp#39]
With nvim-compe I could customize the completion-menu-icons by simply defining the lsp-native CompletionItemKind:

```lua
require('vim.lsp.protocol').CompletionItemKind = {
    '', -- Text
    '', -- Method
    '', -- Function
    '', -- Constructor
    '', -- Field
    '', -- Variable
    '', -- Class
    'ﰮ', -- Interface
    '', -- Module
    '', -- Property
    '', -- Unit
    '', -- Value
    '了', -- Enum
    '', -- Keyword
    '﬌', -- Snippet
    '', -- Color
    '', -- File
    '', -- Reference
    '', -- Folder
    '', -- EnumMember
    '', -- Constant
    '', -- Struct
    '', -- Event
    'ﬦ', -- Operator
    '', -- TypeParameter
}
```

nvim-cmp doesn't recognize it and your README suggests to use lspkind-nvim which itself uses CompletionItemKind in the background. Is it possible to define completion-menu by myself with CompletionItemKind without lspkind-nvim?

**Comment by astier** [comment]
Also calling it completion-kind would be probably more correct than completion-menu.

**Comment by astier** [comment]
I think it would be better if nvim-cmp would simply check for `require('vim.lsp.protocol').CompletionItemKind` internally by itself. This is the official way to customize it and the only thing lspkind-nvim does is to set `require('vim.lsp.protocol').CompletionItemKind` anyway. Making lspkind-nvim a dependency is really not necessary.

**Comment by wimstefan** [comment]
Putting
```lua
for index, value in ipairs(vim.lsp.protocol.CompletionItemKind) do
  cmp.lsp.CompletionItemKind[index] = value
end
```
into my [nvim-cmp configuration](https://github.com/wimstefan/dotfiles/blob/master/config/nvim/init.lua#L879-L881) does the job nicely for me ...

**Comment by astier** [comment]
Thanks. I think this should be the default. The use user should set it manually.

**Comment by hrsh7th** [comment]
No... I think the changing defined value to customize is bad idea.

You should return your favorite kind icon via `formatting.format` instead of modify cmp.lsp.CompletionItemKind

**Comment by wimstefan** [comment]
> No... I think the changing defined value to customize is bad idea.
> 
> You should return your favorite kind icon via `formatting.format` instead of modify cmp.lsp.CompletionItemKind

Hmm I'm afraid I don't understand ...
I could not find any help to `formatting.format`. Could you elaborate a bit more please?

**Comment by ikalnytskyi** [comment]
@wimstefan There's an example here: https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem

**Comment by wimstefan** [comment]
> @wimstefan There's an example here: https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem

Thanks a lot @ikalnytskyi  🙏
Unfortunately my skills are too lousy that I could get that working :/

**Comment by ikalnytskyi** [comment]
@wimstefan You can take a peek at my configuration:

https://github.com/ikalnytskyi/dotfiles/blob/76e8528b9239a045075130f7c3c6437b19f6870f/nvim/.config/nvim/init.lua#L52-L78
https://github.com/ikalnytskyi/dotfiles/blob/76e8528b9239a045075130f7c3c6437b19f6870f/nvim/.config/nvim/init.lua#L254-L259

**Comment by astier** [comment]
@ikalnytskyi this might work but I have two objections with this solution.

1. Isn't `vim.lsp.protocol.CompletionItemKind` already builtin into neovim-lsp or do I get it wrong? If so than why shouldn't it be used by default by nvim-cmp instead of creating a custom solution for it. nvim-compe recognizes `vim.lsp.protocol.CompletionItemKind` without any complicated interventions.
2. I find your solution too complicated to be honest and not intuitive at all. It should be as easy as setting a few variables. Just as it worked with `vim.lsp.protocol.CompletionItemKind` in nvim-compe.

**Comment by hrsh7th** [comment]
I say again. the changing `vim.lsp.protocol.CompletionItemKind` is bad idea.

If some plugin checks `vim.lsp.protocol.CompletionItemKind[item.kind] == 'Snippet'`, this will break with this customization.

**Comment by MurdeRMelodY** [comment]
Here's an example with `codicons.nvim`:

`
  local codicons = require "codicons"
  local codiconsCIK = require("codicons.extensions.completion_item_kind").symbols
  ...
  formatting = {
    format = function(_, vim_item)
      vim_item.kind = codicons.get(codiconsCIK[vim_item.kind].icon)
      return vim_item
    end,
  },

`

**Comment by gegoune** [comment]
@hrsh7th I did not realise implications setting `vim.lsp.protocol.CompletionItemKind` up has. I was then interested to see what lspkind does and it seems like it also modifies it https://github.com/onsails/lspkind-nvim/blob/9cc326504e566f467407bae2669a98963c5404d2/lua/lspkind/init.lua#L100.

Perhaps it should be removed from README if it is such a bad idea and replaced with some safer way?

**Comment by astier** [comment]
To be honest I still don't really understand why it's a bad thing to set CompletionItemKind. Maybe I just don't get what it purpose is if not defining completion-kind-icons but I trust @hrsh7th if he says so. I always assumed it to be correct because lspkind-nvim sets it internally and nvim-cmp recommends lspkind. Also nvim-compe seems to use CompletionItemKind for the icons. @hrsh7th you can close this issue if you want.

**Comment by hrsh7th** [comment]
At least, In nvim-cmp, I prefer all menu customixation realises by `formatting.format`. It's explicit way and super flexisible.
For example, you can change icon per source.

**Comment by hrsh7th** [comment]
Anyway, Thank you for raising a question. It was a good point to me.

**Comment by astier** [comment]
Just wanted to share my final solution without using any plugins:

```lua
formatting = {
  format = function(entry, vim_item)
    vim_item.menu = ({
      nvim_lsp = '',
      buffer   = '',
    })[entry.source.name]
    vim_item.kind = ({
      Text          = '',
      Method        = '',
      Function      = '',
      Constructor   = '',
      Field         = '',
      Variable      = '',
      Class         = '',
      Interface     = 'ﰮ',
      Module        = '',
      Property      = '',
      Unit          = '',
      Value         = '',
      Enum          = '',
      Keyword       = '',
      Snippet       = '﬌',
      Color         = '',
      File          = '',
      Reference     = '',
      Folder        = '',
      EnumMember    = '',
      Constant      = '',
      Struct        = '',
      Event         = '',
      Operator      = 'ﬦ',
      TypeParameter = '',
    })[vim_item.kind]
    return vim_item
  end
},
```
