### ISSUE TITLE
buffer.setup removes global sources

### ISSUE THREAD

**Issue by SebastienWae** [hrsh7th/nvim-cmp#390]
By reading the doc for `sources (type: table<cmp.SourceConfig>)` my understanding is that `require('cmp').setup.buffer` only <ins>adds</ins> extra sources to the current buffer. Yet with my current config it removes all of my global sources too.

![screenshot](https://user-images.githubusercontent.com/55792872/138422017-d53e1158-05ec-4626-911b-fbfd59208826.png)

```lua
-- example config to reproduce with packer.nvim
packer.use {
  'hrsh7th/nvim-cmp',
  requires = {
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-nvim-lua'
  },
  config = function ()
    local cmp = require('cmp')
    cmp.setup({
      sources = {
        { name = 'nvim_lsp' },
        { name = 'buffer'},
      }
    })
    vim.api.nvim_command("autocmd FileType lua lua require'cmp'.setup.buffer{sources = {{ name = 'nvim_lua' }, { name = 'buffer' }}}")
  end
}

```

**Comment by julianobarbosa** [comment]
Essa
