### ISSUE TITLE
can't Disable cmp in specific filetype 

### ISSUE THREAD

**Issue by jczhang02** [hrsh7th/nvim-cmp#396]
```
au FileType TelescopePrompt lua require('cmp').setup.buffer { enabled = false }
```
sorry for annoying , but after your lastest commit, this command is not work anymore!

Hope can solve it.

**Comment by flaviusbuffon** [comment]
now, i have solved the problem "can't Disable cmp in specific filetype'. 
But actually, i still can't make ultisnips work in tex file.
config like this:
```
![image](https://user-images.githubusercontent.com/44057232/138538067-6185d435-7379-4408-bb52-f8fa162e776a.png)

add plugin like this
![image](https://user-images.githubusercontent.com/44057232/138538071-5544e7a8-a56a-4b6b-8d20-b5d88d3fcaea.png)

**Comment by flaviusbuffon** [comment]
> Ah, I think I just figured out what's going. I was putting that autocmd in `cmp` augroup. It works as expected when I use some other name. Apologies about the noise!

So how u solve your problem

**Comment by flaviusbuffon** [comment]
> By adding my auto command in auto group with name other than 'cmp'. Used 'cmp_custom' instead.

can  u give me a config example ?

**Comment by gegoune** [comment]
Example from readme should work:

```viml
" Setup buffer configuration (nvim-lua source only enables in Lua filetype).
autocmd FileType lua lua require'cmp'.setup.buffer {
\   sources = {
\     { name = 'nvim_lua' },
\     { name = 'buffer' },
\   },
\ }
```

You can wrap it with `augroup`, like:
```viml
augroup cms_custom
autocmd!
" Setup buffer configuration (nvim-lua source only enables in Lua filetype).
autocmd FileType lua lua require'cmp'.setup.buffer {
\   sources = {
\     { name = 'nvim_lua' },
\     { name = 'buffer' },
\   },
\ }
augroup END
```

Does that help?
