### ISSUE TITLE
When the cmp completion menu is open pressing enter adds a new line which cannot be removed 

### ISSUE THREAD

**Issue by aditya-K2** [hrsh7th/nvim-cmp#399]
## While Using Native Menu: 

https://user-images.githubusercontent.com/51816057/138512787-6d8c21a4-1541-4bd8-a5bc-e6274a3731f1.mp4

## While Using CMP Menu:

https://user-images.githubusercontent.com/51816057/138512878-5f663885-b8c8-48cd-be65-a683427c4c6e.mp4

**Comment by hrsh7th** [comment]
duplicated #328
