### ISSUE TITLE
How to chang the source-name like which is displayed in the completion-window?

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-cmp#40]
In nvim-compe I could change the source-name/icon which of is shown in the completion-window.

```lua
require'compe'.setup {
    source = {
        buffer = { menu = '' };
        nvim_lsp = { menu = '' };
    }
}
```
Is there a way to do this with nvim-cmp?

**Comment by stvhuang** [comment]
I think you can take a look at [`formatting.format`](https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem).

**Comment by astier** [comment]
It seems to me it is used to set the CompletionItemKind and not the source-text/icon.

**Comment by hrsh7th** [comment]
The `formatting.format` can,be ised to customize,menu appearance.

You can returns vim's complete-items.

See `:help complete-items`

**Comment by hrsh7th** [comment]
The following configuration can be used.

```
    formatting = {
      format = function(entry, vim_item)
        vim_item.menu = ({
          nvim_lsp = '[L]',
          buffer   = '[B]',
        })[entry.source.name]
        return vim_item
      end
    }
```

**Comment by astier** [comment]
Thank you.
