### ISSUE TITLE
Autocompletion window overrides cmp's one

### ISSUE THREAD

**Issue by callb4ck** [hrsh7th/nvim-cmp#408]
My config:

```lua
  local saga = require "lspsaga"
  local cmp = require "cmp"

  local LSPs = language_server_list.nvimlsp
  local nvim_lsp = require "lspconfig"
  --local coq = require("coq")
  local let = require("vim_interfaces/vars").let

  saga.init_lsp_saga()

  cmp.setup({
      snippet = {
        expand = function(args)
          vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        end
      },

      mapping = {
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<Tab>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ['<C-j>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
        ['<C-k>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.close(),
        ['<CR>'] = cmp.mapping.confirm({ select = true }),
      },

      sources = {
        {name = "nvim_lsp"},
        {name = "vsnip"},
      }
    })


  let.g("completion_matching_strategy_list", {"exact", "substring", "fuzzy"})

  local capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())

  for _, lsp in ipairs(LSPs) do
    nvim_lsp[lsp].setup {
      flags = {
        debounce_text_changes = 150,
      },
      capabilities = capabilities
    }
  end
```
![bug_report](https://user-images.githubusercontent.com/43857998/138606840-2d56efec-1adf-42a2-8c28-20ca0fecbcd3.gif)

**Comment by rbozan** [comment]
so if I understand, you can't run coc and nvim-cmp at the same time? I want to transition slowly to nvim-cmp but some things I still need coc for.

**Comment by dmitmel** [comment]
No.

Although, at some point I wanted to write a sources for nvim-cmp which would pull completion results from coc and use cmp for displaying them. I didn't proceed because a) I imagine this would require very hacky workarounds; b) I didn't need this myself; but I might if somebody gives me pointers on how to do it.

> I want to transition slowly to nvim-cmp but some things I still need coc for.

Which? Maybe I can suggest alternatives for your use-cases.

**Comment by rbozan** [comment]
Well.. Thanks for wanting to suggest alternatives, I guess I can actually replace coc entirely on my own, but it's just a bit too much hassle for now as I need to download the LSPs somehow from either the package manager (which doesn't have everything) or some other vim plugin that downloads it for me. I haven't found out what's the best way to do all of that, which is the reason why I haven't fully moved yet.
