### ISSUE TITLE
Completions replace improper words

### ISSUE THREAD

**Issue by ikalnytskyi** [hrsh7th/nvim-cmp#41]
## Description

In some cases when I complete one of the completions, it replaces the text that follows.

## Expected behavior

The text that follows (i.e. after the cursor caret) remains untouched.

## Actual behavior

The text that follows (i.e. after the cursor caret) is removed.

## Example

Checkout on the video below how `do_something` completion replaced `A`, while my intention was to simply wrap `A` (i.e. pass it to `do_something`).

[![asciicast](https://asciinema.org/a/9BMhcud9l07LvwX1xdNLxr6NF.svg)](https://asciinema.org/a/9BMhcud9l07LvwX1xdNLxr6NF)

```python
def do_something(value):
    return value

A = "A"

if "foo" == A:
    pass
```

## Config

```lua
         cmp.setup({
            completion = {
               completeopt = vim.o.completeopt,
            },

            snippet = {
               expand = function(args)
                  vim.fn["vsnip#anonymous"](args.body)
               end
            },

            mapping = {
               ["<C-p>"] = cmp.mapping.prev_item(),
               ["<C-n>"] = cmp.mapping.next_item(),
               ["<C-d>"] = cmp.mapping.scroll(-4),
               ["<C-f>"] = cmp.mapping.scroll(4),
               ["<C-Space>"] = cmp.mapping.complete(),
               ["<C-e>"] = cmp.mapping.close(),
               ["<CR>"] = cmp.mapping.confirm({
                  behavior = cmp.ConfirmBehavior.Replace,
                  select = true,
               })
            },

            formatting = {
               format = function(entry, vim_item)
                  vim_item.kind = string.format("%s %s", LSP_KIND_SIGNS[vim_item.kind], vim_item.kind)
                  return vim_item
               end
            },

            sources = {
               { name = "nvim_lsp" },
               { name = "buffer" },
               { name = "path" },
            },
         })
```

## Language servers

Tried the following:

* `pyright 1.1.162`
* `pylsp v1.2.1`

**Comment by hrsh7th** [comment]
You can use ConfirmBehavior.Insert instead of Replace.

**Comment by ikalnytskyi** [comment]
Thank you, it seems working more like `nvim-compe`. What tokens does it use to decide what to replace?

**Comment by hrsh7th** [comment]
Sorry. I might not understand what your meaning.

> What tokens does it use to decide what to replace?

The each sources can have `keyword-pattern` and nvim-cmp will detects replacing range with it.

**Comment by ikalnytskyi** [comment]
@hrsh7th 
> The each sources can have keyword-pattern and nvim-cmp will detects replacing range with it.

Is that pattern comes from an LSP server? Or it can be configured per source?

Also, I'm curious, why have you decided to use `ConfirmBehavior.Replace` behavior by default? I tried my experiment on VS code, and it seems it works like `ConfirmBehavior.Insert`.

**Comment by hrsh7th** [comment]
There is no reason. It's may be better to change default value as you said.

The keyword pattern will be chosen as the following step.

1. Source specific
If source specified keyword pattern, the user can't customize it.

2. Configuration
You can change by `cmp.setup`.

3. Default

see config/default.lua

**Comment by ikalnytskyi** [comment]
Thanks for explanation!
