### ISSUE TITLE
`:sleep` in `InsertEnter` may break cmp's `InsertEnter`

### ISSUE THREAD

**Issue by tomtomjhj** [hrsh7th/nvim-cmp#421]
## Problem
I use a plugin that registers an `InsertEnter` autocmd that polls a channel in `:sleep` loop.
When that plugin is active, cmp's `InsertEnter` autocmd is not processed correctly.
As a result, cmp's mappings are not initialized.

## Minimal reproducer
`mini.vim`
```vim
set runtimepath^=~/.vim/plugged/nvim-cmp
lua << EOF
local cmp = require'cmp'
cmp.setup {
  mapping = {
    ['<CR>'] = function(_)
        print('123')
    end
  },
}
EOF
```

Run:
```
nvim -u mini.vim -c 'au InsertEnter * sleep'
```

Type:
```
i<CR><ESC>:mess<CR>
```

* **Expected outcome**:
  Typing `<CR>` should not insert a newline and instead print `123` to `:mess`.
* **Actual**:
  Typing `<CR>` inserts a newline and does not print `123` to `:mess`,
  indicating that the provided mapping is not active.

## Analysis
At this line,
https://github.com/hrsh7th/nvim-cmp/blob/881ca573dbbf39ebef6b15d3e3b484484aec53b3/lua/cmp/init.lua#L266
add the following line:
```diff
@@ -263,6 +263,7 @@ cmp.setup = setmetatable({
 autocmd.subscribe('InsertEnter', function()
   -- Avoid unexpected mode detection (mode() function will returns `normal mode` on the InsertEnter event.)
   vim.schedule(function()
+    print('InsertEnter', vim.inspect(vim.api.nvim_get_mode()))
     if config.enabled() then
       cmp.core:prepare()
       cmp.core:on_change('InsertEnter')
```

Then, run the same command as described above.

**Expected:**
```
InsertEnter {
  blocking = false,
  mode = "i"
}
123
InsertEnter {
  blocking = false,
  mode = "c"
}
```

**Actual:**
```
InsertEnter {
  blocking = false,
  mode = "n"
}
InsertEnter {
  blocking = false,
  mode = "c"
}
```

The first `InsertEnter` is triggered by `i`, and the second one is probably triggered by `:`.
Note that the mode of the first event of the actual output is `"n"`, not `"i"`.
This make `config.enabled()` return `false`, and as a result `cmp.core:prepare()` does not run.

On the other hand, other `InsertEnter` autocmds don't seem to trigger this issue.
For example,
```
au InsertEnter * for i in range(0,1000000) | endfor
```

My conclusion is that there is a subtle bug in the interaction of `sleep`, `vim.schedule`, and `vim.api.nvim_get_mode()`.

**Comment by tomtomjhj** [comment]
```vim
lua << EOF
function log(num, start)
    print(num,
          vim.fn.reltimestr(vim.fn.reltime(start)),
          vim.api.nvim_get_mode().mode)
end
EOF
au InsertEnter * lua start = vim.fn.reltime()
au InsertEnter * lua vim.schedule(function() log(1, start) end)
au InsertEnter * exe 'lua print("sleep")' | sleep | lua log(2, start)
au InsertEnter * lua vim.schedule(function() log(3, start) end)
```
Output:
```
sleep
1   0.000050 n
2   1.001121 n
3   1.001208 i
```

So it seems that the scheduled callback can be invoked while `:sleep` is running, at which point the mode is `n`.

BTW please don't be bothered with this issue too much if there are other important issues.  I'll try to think of a workaround.

**Comment by hrsh7th** [comment]
@tomtomjhj I've tried to reproduce this in my local environment (latest neovim) but it can't reproduced.

I was using the following config.

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()

lua <<EOF
  local cmp = require'cmp'

  cmp.setup({
    mapping = {
      ['<CR>'] = function(_)
          print('123')
      end
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
    }, {
      { name = 'buffer' },
    })
  })
EOF

autocmd InsertEnter * sleep
```

Probably, latest neovim or keymap.lua refactor solves this problem....

**Comment by tomtomjhj** [comment]
Unfortunately, I can still reproduce the issue. This issue only happens when the sleep autocmd is registered after cmp's. Cmp's autocmds are defined in `plugin/`, which are sourced after sourcing init.vim. So, the last line should be
```vim
autocmd VimEnter * autocmd InsertEnter * sleep
```

**Comment by hrsh7th** [comment]
My patch is wrong. Sorry. It was reverted now.

**Comment by hrsh7th** [comment]
Fixed the issue by https://github.com/hrsh7th/nvim-cmp/commit/a0053885ba2d50a62660731519aa5b6fef0859c6
