### ISSUE TITLE
Question/feature request: Auto-import with pyright LSP

### ISSUE THREAD

**Issue by AckslD** [hrsh7th/nvim-cmp#426]
I recently started trying out using auto-completion and `nvim-cmp` is very cool so far. One thing that motivated me to use an auto-completion plugin is to have auto-import.

I tried to look around for how to have auto-import working with the pyright LSP but couldn't find anything. If I missed it somewhere feel free to point me where I can read how to do it :)
What I have atm is a setup with `nvim-cmp-lsp` following the readme and that works for normal LSP completion but don't understand if auto-import needs additional setup or special triggering?

I found this issue from `compe`:
https://github.com/hrsh7th/nvim-compe/issues/509

Thanks in advance!

(Since this is more of a question and not an issue, would it maybe make sense to enable the discussion-tab for this repo?)

**Comment by urmzd** [comment]
@AckslD similar issue with my current set up (my dotfiles can be found [here](https://github.com/urmzd/dotfiles)). Would you be able to state the `nvim` version you're using? Additionally, would you be able to provide a snippet of your dotfiles where you configure `cmp` and `pyright`?

**Comment by petertriho** [comment]
```
if server.name == "pyright" then
            opts.settings = {python = {pythonPath = "/usr/bin/python3.9"}}
        end
```

Remove this. Use virtualenv + source it before opening nvim

**Comment by urmzd** [comment]
@petertriho the above works. However, it would be nice if you didn't need a virtual env anytime you wanted to code in `python`. Is this a upstream issue? Potentially with `pyright's` module resolution? Or does it have to with `cmp` specifically?

**Comment by petertriho** [comment]
It should work without a virtualenv as well, it just won't be able to completion dependencies not installed. It's not really an issue, but is related to pyright

**Comment by urmzd** [comment]
@petertriho That's strange considering there were no dependencies installed in the virtual environment. I find it odd that module resolution only works in `venv`. Can you source some of the information you have? I'd like to take a look and see if there's an underlying issue somewhere :)

**Comment by petertriho** [comment]
100% not cmp, it has nothing to do with your python setup. Sorry, I don't have any sources, this just purely anecdotal (from my own setup). Can you execute python from the command line? I'm guessing it's only working in the venv because of this. In that case, I'm not sure why `pythonPath = "/usr/bin/python3.9"` wasn't working

**Comment by urmzd** [comment]
I was able to fix the issue by removing all `python` related `symlinks`. It seems to be a `site-package` resolution error. Hope this helps someone else aswell.

**Comment by smacz42** [comment]
So, per the test above, I can start typing `typing_exten...`, and get a popup called `typing_extensions~ Module`. This puts in the correct import and everything.

However, I was testing this out with `datetime`. So I started typing `date...`, and all I got was `DynamicClassAttribute~ Variable`? 

Here it gets even weirder. If I put `import da...`, it will autofill many different modules, including an option for `datetime`. And then on subsequent lines it will then recognize and autofill `datetime` statements.

Let me know if I should take this somewhere else, but the import here seems to be recognized by pyright but only displayed after importing, which kinda defeats my conception of auto-import.

**Comment by feslima** [comment]
Hey @smacz42 I have the same exact behavior here. Have you found any solution for this?

**Comment by iverberk** [comment]
I'm also experiencing this behavior. Any idea why there are no immediate auto-completion/import suggestions when typing 'datetime' (whereas with typing_ext it will find the module). Might very well be a misconfiguration of the LSP or PyRight but I'm hoping someone has a pointer to a solution or working config.

**Comment by gotgenes** [comment]
I believe this issue in pyright explains what we're experiencing: https://github.com/microsoft/pyright/issues/967

Specifically:
>The current behavior was copied from the TypeScript language server which limits its auto-imports to only those symbols and modules that have been imported somewhere else in the program.

Why does this work with `typing_extensions`? My hypothesis is that pyright automatically loads this as part of its own functionality. In contrast, a module like `datetime` will not automatically be loaded into pyright's symbol space, unless some file within the workspace explicitly does `import datetime` or `from datetime import ...`.

So, this behavior is not a bug in nvim-cmp, and it is also not something you can change with configuration today. The first time an import is needed in your project, you will need to manually import it.
