### ISSUE TITLE
Toggle completion menu

### ISSUE THREAD

**Issue by axieax** [hrsh7th/nvim-cmp#429]
**Describe the bug**
Hi I'm trying to create a mapping for toggling the cmp menu in insert mode. Here is what the code looks like. 

![image](https://user-images.githubusercontent.com/62098008/139291264-d9e46b97-5cb9-4dc9-b463-32bcb65f9ec6.png)

I've found that cmp.mapping.close() and cmp.mapping.complete() aren't working, even though debugging shows that cmp.visible() is working as intended though (code goes to the correct conditional branch).

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
cmp.setup({
      ["<C-k>"] = function(fallback)
        if cmp.visible() then
          cmp.mapping.close()
        else
          cmp.mapping.complete()
        end
      end,
})
```
https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/cmp.lua#L83-L103

**To Reproduce**

1. Use my mapping
2. In insert mode, press `<C-k>` -> menu doesn't open
3. With cmp menu open, press `<C-k>` -> menu doesn't close

**Expected behavior**

If cmp menu is open, pressing `<C-k>` will close it. If cmp menu is closed, pressing `<C-k>` will open it (like `<C-Space>`)

**Additional context**

**Comment by ElPiloto** [comment]
Sorry for resurrecting this, but its the most relevant place and already has all the context.  Is there a way to have the toggle also disable/re-enable nvim-cmp?  As it stands, the toggle will hide nvim-chhhhhhhhhhhhhmp but as you continue to type it will promptly pop back up.  It's not clear to me how to use the "disable" instructions from the README (`lua require('cmp').setup.buffer { enabled = false }`)  in this case.

**Comment by KasonBraley** [comment]
> Sorry for resurrecting this, but its the most relevant place and already has all the context. Is there a way to have the toggle also disable/re-enable nvim-cmp? As it stands, the toggle will hide nvim-cmp but as you continue to type it will promptly pop back up. It's not clear to me how to use the "disable" instructions from the README (`lua require('cmp').setup.buffer { enabled = false }`) in this case.

I was able to accomplish this with the following:

```
local M = {}

-- toggle cmp completion
vim.g.cmp_toggle_flag = false -- initialize
local normal_buftype = function()
  return vim.api.nvim_buf_get_option(0, "buftype") ~= "prompt"
end
M.toggle_completion = function()
  local ok, cmp = pcall(require, "cmp")
  if ok then
    local next_cmp_toggle_flag = not vim.g.cmp_toggle_flag
    if next_cmp_toggle_flag then
      print("completion on")
    else
      print("completion off")
    end
    cmp.setup({
      enabled = function()
        vim.g.cmp_toggle_flag = next_cmp_toggle_flag
        if next_cmp_toggle_flag then
          return normal_buftype
        else
          return next_cmp_toggle_flag
        end
      end,
    })
  else
    print("completion not available")
  end
end

return M


-- in cmp setup
["<C-k>"] = cmp.mapping({
      i = function()
        if cmp.visible() then
          cmp.abort()
          require("plugins.others").toggle_completion()
        else
          cmp.complete()
          require("plugins.others").toggle_completion()
        end
      end,
      c = function()
        if cmp.visible() then
          cmp.close()
        else
          cmp.complete()
        end
      end,
    })


-- separate keybinding to manually toggle completion
map("n", "<Leader>tc", ":lua require('plugins.others').toggle_completion()<CR>", opt)
```

Once `<C-k>` is pressed once, it disables the completion window **and** disables nvim-cmp completion entirely. Until either `<C-k>` is pressed again when trying to open the completion window, or when the separate keybinding is used.

Inspiration from https://github.com/hrsh7th/nvim-cmp/issues/429#issuecomment-954121524 and https://github.com/hrsh7th/nvim-cmp/issues/261#issuecomment-930003962
