### ISSUE TITLE
'set completeopt=menuone,noinsert' not respected

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-cmp#43]
Currently it has to be set with nvim-cmp internally:

```lua
completion = {
  completeopt = 'menuone,noinsert',
},
```

Since `completeopt` is an option which is already built into vim why not just check for it instead of reinventing it a second time in nvim-cmp?

**Comment by hrsh7th** [comment]
What if the user wants to use `completeopt = menu, menuone, noselect` for auto-complete and` completeopt = menu, menuone, longuest` for omni-completion?

(google translated)

**Comment by hrsh7th** [comment]
And I received issues with this (so I documented it as a warning).

https://github.com/hrsh7th/nvim-compe/issues/502
https://github.com/hrsh7th/nvim-compe/issues/61
https://github.com/hrsh7th/nvim-compe/issues/222

**Comment by MurdeRMelodY** [comment]
You could do something like this if you want to use builtin completeopt with cmps':

```lua
  completion = {
    completeopt = table.concat(vim.opt.completeopt:get(), ","),
  }
```
