### ISSUE TITLE
Most recent commits break Tab mapping

### ISSUE THREAD

**Issue by jdrouhard** [hrsh7th/nvim-cmp#431]
The last two commits have seemingly broken my Tab mapping. That being-- c01de2b does not exhibit the problem, but 52d9411 and 6696c6a both do. Reverting just 52d9411 doesn't seem to solve it, it actually requires reverting both or resetting to the working commit to be fixed.

What I'm seeing now is that pressing tab when the new-style menu is shown with completion items simply inserts a tab character and does not select the next item in the list.

**Minimal config**

<details>
<summary>Click to expand the minimal config</summary>

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { 'i',  's' }),
  },
  sources = {
    { name = "buffer" },
  },
}
EOF
```
</details>

**To Reproduce**

1. Open a buffer
2. Go to insert mode and type some characters until the completion window with items appear
3. Press tab

**Comment by hrsh7th** [comment]
@jdrouhard Could you test with latest nvim-cmp? I've added the normalizing keymapping.

**Comment by jdrouhard** [comment]
That seems to have fixed it. Thanks for the quick turnaround!

**Comment by Saecki** [comment]
I'm still having that issue even on the latest [commit](https://github.com/hrsh7th/nvim-cmp/commit/1774ff0f842146521c63707245d3de5db2bb3732). Was there a regression or should I open another issue?

**Comment by jdrouhard** [comment]
@Saecki Yes, I think there was a regression. I'd open a new ticket as I'm seeing the same behavior now as well.
