### ISSUE TITLE
[feature request] source table should have filetype and exclude kewords

### ISSUE THREAD

**Issue by rebelot** [hrsh7th/nvim-cmp#433]
It would be great to be able to do:
```lua
...
 sources = {
        { name = 'nvim_lsp' },
        { name = 'path' },
        { name = 'buffer', exclude = {'python', 'cpp', 'tex'}},
        { name = 'dictionary', filetype = {'pandoc', 'markdown', 'tex'}}
}
...
```
I think this would make it a lot easier to control sources for specific filetypes instead of using `autocommand` and `require'cmp'.setup.buffer`

**Comment by sethidden** [comment]
> { name = 'dictionary', filetype = {'pandoc', 'markdown', 'tex'}}

In the special case of the dictionary, there's https://github.com/uga-rosa/cmp-dictionary#use-different-dictionaries-for-each-filetype

Wondering if you can just set the dictionary to "nothing" to disable it

**Comment by hrsh7th** [comment]
`autocmd FileType markdown,pandoc,tex lua require('cmp').setup.buffer { sources = { { name = 'dictionary' } } }` should work, I think.
