### ISSUE TITLE
[Feature Request] Auto-import on Completion respecting the prefixed in tsconfig.json

### ISSUE THREAD

**Issue by nyngwang** [hrsh7th/nvim-cmp#434]
Yes, don't panic, I did read your words on reading/following the template or so. This is not a bug report, but a feature request. It just takes a little time to read since I will provide some images:

1. I'm using your plugin to __Auto-Import on completion__. It seems great but when I remove-then-auto-import-back to enjoy this feature...

    <img src="https://user-images.githubusercontent.com/24765272/139412741-4e0c7cdb-2505-40c0-bb06-a19ac2a338a1.png" width="500">

    <img src="https://user-images.githubusercontent.com/24765272/139414091-edca2b6b-eb28-43f6-89de-abb2a75475ac.png" width="500">

2. So yep you got the point. The completion system doesn't respect the `tsconfig.json`:

    <img src="https://user-images.githubusercontent.com/24765272/139413053-55fbd78a-0767-4e1e-96e6-d247f82e9022.png" width="500">

I think auto-import __should be accurate__ to be useful. So many you might consider adding this feature.

Sincerely,
Ning.
2021/10/29

**Comment by dmitmel** [comment]
I believe we have resolved this in #646.

**Comment by nyngwang** [comment]
@hrsh7th: may I ask you that is it possible to auto-import-on-completion this kind of line: `import Another from ./Another`, where `./Another` is a component under the same directory?

**Comment by hrsh7th** [comment]
At least, this feature request is out of scope of nvim-cmp.
It must be solved on typescript-language-server or vtsls.

**Comment by ubugnu** [comment]
here is what I used:
```lua
lspconfig.tsserver.setup {
  init_options = {
    preferences = {
      importModuleSpecifierPreference = "non-relative",
    },
  },
}
```
