### ISSUE TITLE
Can't trigger lsp completion automatically with sumneko/lua-language-server

### ISSUE THREAD

**Issue by rhcher** [hrsh7th/nvim-cmp#44]
### Issue Description
Hi, I noticed that nvim-cmp has behavor like this:
![image](https://user-images.githubusercontent.com/50723480/130350601-7f947dec-41b1-4d63-90c1-731bd71aed9b.png)
when I input "key" in cursor, only Text completion pop-up and if I enter \<C-space> to invoke cmp-complete that will pop-up complete entries like this:
![image](https://user-images.githubusercontent.com/50723480/130350722-5f2e5c42-1444-4bb5-add8-d6fff1bfbac7.png)
If I delete "key" and input again that behavior sometimes normal and sometimes abnormal.
### Person config
[My personal nvim config about cmp](https://github.com/rhcher/nvim/blob/c0c68d4c74e24b26ab14a57833843eec3db42817/lua/modules/completion/config.lua#L8-L59).
### Reproduce code:
``` lua
Days = {
  "Sunday",
  "Monday",
  "TuesDay",
  "WednesDay",
  "ThursDay",
  "FriDay",
  "SaturDay",
}

for key, value in pairs(Days) do
  print(value .. " " .. key)
end
```

**Comment by hrsh7th** [comment]
What is the your using language server?

**Comment by rhcher** [comment]
https://github.com/sumneko/lua-language-server

**Comment by hrsh7th** [comment]
I tjink it relates to LSP server's behaivor. I will look into it.

**Comment by rhcher** [comment]
Hi, as you say, it not a cmp issue and it relate to language server. I'm looking for the real reason. Sorry for my carelessness.

**Comment by hrsh7th** [comment]
I think it was fixed now.
