### ISSUE TITLE
`E492: Not an editor command: ],0>},0|,0},0],0)` when editing OCaml files

### ISSUE THREAD

**Issue by jubnzv** [hrsh7th/nvim-cmp#442]
**Describe the bug**
`nvim-cmp` crashes with `E492: Not an editor command: ],0>},0|,0},0],0)` when editing an arbitrary OCaml file. It seems, that there are some incompatibilities with the default ocaml.vim runtime file, because `nvim-cmp` works perfectly on other file types.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**
```vim
set nocompatible

call plug#begin('~/.local/share/nvim/plugged')
Plug 'hrsh7th/nvim-cmp'
call plug#end()

set completeopt=menu,menuone,noselect

lua <<EOF
  require'cmp'.setup({})
EOF
```

**To Reproduce**
1. Open or create the OCaml file using the minimal config: `nvim -u init.vim test.ml`
2. Start writing some reserved OCaml keyword. For example, type `let`.
3. See error in the messages area. Autocompletion won't work after the crash:

![image](https://user-images.githubusercontent.com/12023585/139541045-74c39e7a-6e29-4bac-a563-4e6125369412.png)

**Expected behavior**
No crash.

**Additional context**
`neovim` version: `v0.5.1`. `nvim-cmp` commit hash: 6696c6a0.

**Comment by dmitmel** [comment]
Probably related to `indentkeys` (also no crash for me, for some reason).

**Comment by jubnzv** [comment]
Hi @dmitmel, thanks for the quick reply.

>  no crash for me, for some reason

By "crash" I mean, that autocompletion doesn't work after this error.

> Probably related to indentkeys

Yes, that's right. The [runtime/indent/ocaml.vim](https://github.com/neovim/neovim/blob/master/runtime/indent/ocaml.vim) file contains [the following line](https://github.com/neovim/neovim/blob/97ae0ab4d8e4cdc5be2dab43e328f0a9d248b30a/runtime/indent/ocaml.vim?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L23):
```vim
setlocal indentkeys+=0=and,0=class,0=constraint,0=done,0=else,0=end,0=exception,0=external,0=if,0=in,0=include,0=inherit,0=initializer,0=let,0=method,0=open,0=then,0=type,0=val,0=with,0;;,0>\],0\|\],0>},0\|,0},0\],0)
```

After commenting it in `/usr/share/nvim/runtime/indent/ocaml.vim` everything works.

Could this be fixed in `nvim-cmp`?

**Comment by hrsh7th** [comment]
nvim-cmp doesn't modify the indentkey at the moment.

https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/core.lua#L217

**Comment by jubnzv** [comment]
@hrsh7th Ah, yes, I see. Everything works after update.

Thank you very much for this project, and sorry for that noise.

**Comment by undu** [comment]
> Ah, yes, I see. Everything works after update.

Could you explain what did you update to fix the issue? I'm encountering it as well.

**Comment by jubnzv** [comment]
@undu I just updated `nvim-cmp` using my plugin manager. This issue has been fixed in the current version.

**Comment by undu** [comment]
I had to remove the `indentkeys` in installed `vim-ocaml` and `vim-polyglot` as well
