### ISSUE TITLE
[regression] ^F introduced in insert mode

### ISSUE THREAD

**Issue by swy7ch** [hrsh7th/nvim-cmp#443]
# Preamble

This issue follows another one I opened about a month and half ago, when I had the exact same issue : #204. Just like that time, I only encounter this with [whonore/Coqtail](https://github.com/whonore/Coqtail) plugin...

The fix worked fine, until today when I updated my plugins. I suppose it has to do with this issue : #423 

# Problem

Using hrsh7th/nvim-cmp along with whonore/Coqtail introduces unwanted, unremovable characters:

![image](https://user-images.githubusercontent.com/24797611/139553904-a593cb03-1743-49fb-ad25-c600283ad9d5.png)

(sorry for the coloration, this is part of whonore/Coqtail and I want the config to be minimal).

It seems to be related to keywords ending a block of work (such as a proof block), since it seems to concern only keywords such as Qed, Admitted or Abort :

![image](https://user-images.githubusercontent.com/24797611/133520224-0ed51b71-113f-46ce-b144-ed2f9f326a45.png)

As you can see, no issue with starting keywords such as Proof or Lemma.

Those characters are interpreted by the Coq interpretor and therefore, make the file almost unusable since they are unremovable via backspace or delete. I did find a "hack", that is typing the desired word twice : since the character ^F only appears once, we can then go back to normal mode and delete it via x or d.

# Expected behaviour

No insertion of character by the completion engine.
Steps to reproduce

Here is the basic neovim config file that I used (note that the minimal .vmirc does not fix te behavior):

    require'cmp'.setup { }

    return require('packer').startup(function()
      -- Packer can manage itself
      use 'wbthomason/packer.nvim'
      use "hrsh7th/nvim-cmp"
      use "whonore/Coqtail"
    end)

* Install both nvim-cmp and whonore/Coqtail plugins
* Open a coq file using $ nvim -u basic_init.lua foo.v
* Enter INSERT mode, and type Qed.

Setup

* NVIM v0.6.0-dev+526-geb6a1039c, latest version as of writing
* all plugins (packer, nvim-cmp and Coqtail) are up to date

# Additional infos

Currently empty, I'll edit this part if need be.

**Comment by tomtomjhj** [comment]
Can you try `setlocal indentkeys+=!^F` in `after/indent/coq.vim` like this? https://github.com/tomtomjhj/init.vim/blob/06b1804991b255c72843646789e465820f9cc2e4/after/indent/coq.vim#L4

This means "adjust the indentation when `<C-f>` is pressed in insert mode", which is quite useful and will probably resolve the issue you're experiencing. I use Coqtail, but I haven't run into this problem.

Not related to this issue, but FYI, Coqtail is affected by https://github.com/hrsh7th/nvim-cmp/issues/421.

**Comment by swy7ch** [comment]
Dang. Not only did this fix the issue, it also enabled auto-completion back! Thanks :D

Doesn't explain the regression tho (sorry, I don't have the time right now to investigate further)

**Comment by Julian** [comment]
The fix here re-regresses on the issue from #423 unfortunately.
