### ISSUE TITLE
keyword_length variant?

### ISSUE THREAD

**Issue by fastbodin** [hrsh7th/nvim-cmp#444]
Hi there. I love the plugin in. Thank you for all your work on it.

I wanted to ask if there was a way to set a minimum word length for given completion sources? Note that this is different from keyword_length. For instance, suppose I only want to receive completion suggestions on words of length >= 5 and (within my buffer) I have used the following words:

alph
al
alp
alphaalpha
alphabeta
alphagamma

It would be great if there was an alternate to keyword_length such that if I typed the letter 'a,' I would be given word suggestions on all words that are >= 5 letters in length. In this example typing the letter 'a' would yield the words

alphaalpha
alphabeta
alphagamma

but not the words

alph
al
alp

I hope my question is clear!

**Comment by hrsh7th** [comment]
I've added the `keyword_length` option to `cmp-buffer`.
https://github.com/hrsh7th/cmp-buffer

```lua
cmp.setup {
  sources = {
    { name = 'buffer', opts = { keyword_length = 5 } },
  }
}
```

**Comment by fastbodin** [comment]
Thanks so much! This is fantastic!
