### ISSUE TITLE
Question regarding changes to text before `callback` is called

### ISSUE THREAD

**Issue by PatOConnor43** [hrsh7th/nvim-cmp#445]
**Describe the bug**
Hi :wave: I was trying to build a plugin that would autocomplete packages within a programming language's dependency spec file (Dart's pubspec.yaml file to be specific). As the user types I would _like_ to be able to queue a request to the search API and then populate items back to `cmp`. I wanted to do this asynchronously and also be able only query the API after the user has paused typing. The problem is that it seems like `cpm` expects the custom source to always call the `callback` before new calls to the defined `complete` function gets called again.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"

local source = {}
source.new = function()
    local self = setmetatable({}, { __index = source })
    return self
end

source.is_available = function()
    return true
end

function source.get_debug_name()
    return 'test'
end

function source.resolve(self, completion_item, callback)
    callback(completion_item)
end

function source.execute(self, completion_item, callback)
    callback(completion_item)
end

function source.get_trigger_characters(self, config)
    return {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '_'}
end

function source.complete(self, params, callback)
    
    local cur_line = params.context.cursor_line
    local items = {}

    -- Look for the first word in the line
    name = cur_line:match('([%w_]+)(.*)')
    -- I'm using vim.defer_fn here as a placeholder for my async code that uses a timer.
    vim.defer_fn(function()
      print(name)
      table.insert(items, {label = name})
      callback(items)
      end, 2000)
end


cmp.register_source('test', source.new())

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "test" },
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF


```

**To Reproduce**

- User types `r` on a new line
- My source parses the line and finds the new text
- My source starts a timer that will run a curl request to the API after a duration (2 seconds)
- The user types `edux` rapidly after the `r` (complete word is "redux")
- My source has no way to know that new text was added since it hasn't called the callback with items yet

Right now, it seems like my source doesn't get a call to `complete` related to the `edux` text unless I call the `callback`. 

**Expected behavior**
- User types `r` on a new line
- My source parses the line and finds the new text
- My source starts a timer that will run a curl request to the API after a duration (2 seconds)
- The user types `edux` rapidly after the `r` (complete word is "redux")
- My source stops the timer
- My source creates a new timer that will run the curl request after 2 seconds
- The timer finishes, I make the request, I parse the response into items, I call the callback with the items

I would like to be able to receive a call to `complete` for my trigger characters even if I have a pending call to `complete` or some other way to be notified that new text was added so I can update the call I need to make. This would allow me to call the previous `callback` with `nil` so I can re-create my timer. 

**Additional context**
I really appreciate all the hard work you've put into this and totally understand if this functionality isn't something you want to support. I just wanted to try to build something cool, but maybe this functionality is better to keep out of `cmp`. Thanks for your consideration.

**Comment by hrsh7th** [comment]
It should be supported.

**Comment by PatOConnor43** [comment]
Do you have any initial thoughts on how this would be implemented? I'd be happy to put a pull request together. I'm a little concerned that this part of my comment might be a breaking change:
> I would like to be able to receive a call to complete for my trigger characters even if I have a pending call to complete... 

So maybe it would be better to come up with a new way to notify sources? I'll do some more reading in the `nvim-cmp` code and see if I can think of anything. Thanks!

**Comment by PatOConnor43** [comment]
The change in this PR seems to give me the behavior that I want but it's possible other sources are not expecting multiple calls to complete. You also probably left `SourceStatus.FETCHING` out of that call on purpose. I just wanted to demonstrate the behavior I was looking for.
https://github.com/hrsh7th/nvim-cmp/pull/450/commits/c889921db990cdafb2a78371af245a975c9741a0

**Comment by hrsh7th** [comment]
I've pushed the improvements of `isIncomplete=true` handling.

You can specify `callback({ isIncomplete = true, items = ... })`.

nvim-cmp will check cursor moved after getting callback so your plugin get called again with latest current line state.

**Comment by PatOConnor43** [comment]
I pulled latest `main` and this does seem to work. Should my completion source ever pass `{isIncomplete = true}` with my items or is this change completely internal to `nvim-cmp`?

Thanks for the help :tada: I think this issue can be closed.

**Comment by hrsh7th** [comment]
@PatOConnor43 nvim-cmp will accept `{ isIncomplete = true }`. But you shoud add `items = {}` because LSP spec defines as so.
