### ISSUE TITLE
After renaming a file by `r` using `nvim-tree.lua`, the completion menu still shows the old file name.

### ISSUE THREAD

**Issue by nyngwang** [hrsh7th/nvim-cmp#448]
**Describe the bug**
After renaming a file by `r` using `nvim-tree.lua`, the completion menu shows the old file name.

As shown in the following GIF:

![Kapture 2021-10-31 at 20 23 12](https://user-images.githubusercontent.com/24765272/139583136-028a1b15-62bd-4701-abf2-918154e50553.gif)

**To Reproduce**

1. Open any python project
2. Run `:NvimTree` and rename any module with `r` provided by the nvim-tree.lua.
3. Trigger the completion menu

**Expected behavior**

The completion menu should show the new file name.

NVIM v0.6.0-dev+533-g653d96329
Build type: Release
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui

**Comment by nyngwang** [comment]
I also post it on reddit and try to resolved it with a temporary solution: https://www.reddit.com/r/neovim/comments/qjoo8v/after_renaming_a_file_the_completion_menu_still/?utm_source=share&utm_medium=web2x&context=3

**Comment by hrsh7th** [comment]
It isn't nvim-cmp's problem.

I think this is neovim's lsp problem. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#resourceChanges

LSP has a feature that is used to detect file resource renamed but I think nvim's lsp does not support it.

**Comment by nyngwang** [comment]
Thanks for the information. My current solution is to add an abbreviation `:R` for `:LspRestart`, and this is much simpler and bug-free from my self-answer in the link.
