### ISSUE TITLE
<C-e> mapping undoes action rather than abort

### ISSUE THREAD

**Issue by RaZ0rr-Two** [hrsh7th/nvim-cmp#449]
**Describe the bug**

After entering completion window once, `<C-e>` acts in a weird way, more like undo command.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim

```
vimrc used [here](https://gist.github.com/RaZ0rr-Two/618899655941b21643cc1069b675a5ad)

**To Reproduce**

When I type something completion window pops up. When I press `<C-e>` without entering popup window, it closes. When I press `<C-n>` it auto-inserts an entry and `<c-e>` removes it. All good.

Now start typing again. Completion window pop ups, `<c-e>` undoes what I typed even I never visited the completion menu with `<c-p>` or `<c-n>`. 

1) Move to a new line, type something, completion menu comes up then  press `<C-e>`, what is typed is removed.

2)Move to new line. Go to insert mode and press `<C-e>`, things typed in previous line appears, i.e, things typed in  step (1).
                                                           or
2)Move to new line. Type something, competion window appear, `<c-e>`, whats typed is replaced with things from step (1) above.

**This only happens after you enter completion window atleast once with `<c-n>`

**Expected behavior**

Closes completion window all the time. Not undo what is written if it is not picked from an entry in completion window

**Additional context**

**Comment by shibotto** [comment]
I *think* I have the same problem, but I'm not sure I understand properly what's written above. In short:

1) Write something which triggers the pop-up completion
2) Select a results; what you previously typed gets cached
3) Close the pop-up (.close(), .abort(), .confirm(), anything works)
4) In a new line trigger the pop-up completion again, but **don't select anything**
5) Call .abort() and what was previously cached in step 2) gets inserted here

This could be solved by clearing the cached string after the pop-up is closed.

If I got this wrong and it is a different bug, I'll open a separate issue.

**Comment by RaZ0rr-Two** [comment]
> 2)Move to new line. Type something, competion window appear, , whats type is replaced with things from step (1) above.

It is same bug, see point above.
