### ISSUE TITLE
Please clarify buffer source configuration

### ISSUE THREAD

**Issue by amenonsen** [hrsh7th/nvim-cmp#45]
The README mentions:

```
" Setup buffer configuration
autocmd FileType markdown lua require'cmp'.setup.buffer {
\   sources = {
\     { name = 'buffer' },
\   },
\ }
```

I guess this means something like "use the buffer source only for Markdown files", but it's not clear. Is that what the code is meant to do? And if we want to do this per-filetype configuration, should we leave out `{ name = 'buffer' }` from the `sources` in the main call to `setup`?

**Comment by hrsh7th** [comment]
Thank you.
Your opinion is correct. I will improve document.

I will update docs as using `cmp-nvim-lua` source o Lua filetype.

**Comment by hrsh7th** [comment]
@amenonsen I've update the document to a more meaningful example.
