### ISSUE TITLE
Unexpandable UltiSnips snippets are still shown as options during auto-complete

### ISSUE THREAD

**Issue by ColinKennedy** [hrsh7th/nvim-cmp#451]
Auto-completion is showing UltiSnips snippets that cannot be expanded.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

`minimal.vim`

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'SirVer/ultisnips'
Plug 'quangnguyen30192/cmp-nvim-ultisnips'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
	  vim.fn["UltiSnips#Anon"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
	{ name = 'ultisnips' }, -- For ultisnips users.
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF


```

**To Reproduce**

1. Run this
```bash
nvim -u minimal.vim test.py
```

2. Call `:UltiSnipsEdit` and define an UltiSnips snippet for Python, like this example
```
snippet rt "Return True" b
return True
endsnippet
```
3. Type `foo bar rt`

**Expected behavior**
Because the `rt` snippet is set to `b`, the snippet can only expand if it is the beginning of a line (excluding whitespace).

In this case, because "foo bar" precedes "rt", UltiSnips won't expand the snippet even if we ask it to. So the snippet should not be visible as a completion option at all.

**Actual Behavior**
The `rt` snippet is displayed as an auto-complete option, regardless of whether it's expandable or not. In other words, the `b` option and existing text in the user's current line in the file has no effect on the completion list result.

**Comment by Shougo** [comment]
It is cmp-ultisnips issue instead of nvim-cmp.

**Comment by ColinKennedy** [comment]
Ah okay, you're talking about https://github.com/quangnguyen30192/cmp-nvim-ultisnips, right? I will create a new issue over there, instead. Thank you!
