### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by muniter** [hrsh7th/nvim-cmp#453]
**Describe the bug**
nvim-cmp fails completing "árbol" from "arbol", this suggestions are provided by the spell source, using `spelllang=es` nvim provides "árbol" as the first completion item but cmp is filtering it.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'f3fora/cmp-spell'

call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<CR>'] = cmp.mapping.complete()
  },

  sources = {
    { name = "spell" },
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

set spell
set spelllang=es

```

**To Reproduce**

1. `nvim -u vimrc.vim`
2. enter in insert mode `un arbol`

**Expected behavior**

First completion candidate should be fixing the spelling error, changing `arbol` -> `árbol` you can see this behavior using spelling suggestions `<C-x>s` in the case of cmp it doesn't even show `árbol` it's being filtered.

**Additional context**

I tried making sure it was not an issue with keyword pattern, sets it to `\K\+` which matches `[arbol, árbol]` no problem.

Using print to debug a bit nvim-cmp, I manage to see that cmp is bailing out on `árbol` as completion because it doesn't find any matches. Right here

https://github.com/hrsh7th/nvim-cmp/blob/b10bb327f3909a215d65bc30b10cef3aaed5459b/lua/cmp/matcher.lua#L109

**Comment by hrsh7th** [comment]
@muniter nvim-cmp's default keyword-pattern does not accept any multibyte chars because it sometimes problematic.

You can use `\k\+` as keyword pattern via the following config.

```lua
cmp.setup {
  completion = {
    keyword_pattern = [[\k\+]]
  }
}
```

**Comment by muniter** [comment]
@hrsh7th thanks for the reply, but I've tried that and still have the same issue, also tried setting it to the spell source with the same result. Seems like cmp is filtering things it shouldn't another example "comunicacion -> comunicación" but you don't see that entry on cmp.

**Comment by muniter** [comment]
@dmitmel there's `:help /\%C`to skip composing characters and `:help /\Z`

**Comment by hrsh7th** [comment]
ah. I understand your problem.

Sorry. nvim-cmp will filter items by checking each bytes.

I have no idea to support it...

**Comment by hrsh7th** [comment]
The matching algorithm is [here](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/matcher.lua#L77).

Probably, it should be realized by source implementation.

**Comment by muniter** [comment]
@hrsh7th That's fine, just wanted  to put it out there. Perhaps is something that can be handled at the source level, I really don't know the internals of cmp. But if I remember correctly compe used to handle this, I'll take a look and let you know. Is fine if not supported 👍🏽

**Comment by hrsh7th** [comment]
Yes. The dource can specify `filterText` so you can convert `á` as `a`.

**Comment by dmitmel** [comment]
If I am not mistaken, to convert for the general case like this you need to perform [NFD normalization](https://unicode.org/reports/tr15/) and then remove all combining characters. [Here](https://stackoverflow.com/q/517923/12005228) is how you do it in Python, but with a 3rd-party library. This needs to be done because there are actually multiple ways of encoding `á`: either as a single 2-byte character (btw Vim's `\%C` can't do anything about this exact method of encoding), or as an ASCII `a` with a combining character, and also there is some third way. NFD normalization rewrites the input string to use only one of those methods (`a` with a combining character), after which you can easily remove the unnecessary accents and so on (they have character class `Mn`).

Although, I guess that if you are just going to do that for Spanish, you can make a function which uses `vim.fn.strchars` and `vim.fn.strgetchar` (or something like that) to decode a UTF-8 string into characters and make a table which maps characters with accents which Spanish uses to English letters. I can't give a ready snippet because I haven't worked with multibyte strings with Vimscript functions much, sorry.

Also, if this discussion was about some legal things I would say "I am not a lawyer", but it is about Unicode, so I will say "I am not a Unicode expert" :slightly_smiling_face:

**Comment by muniter** [comment]
Thanks for the answers @dmitmel @hrsh7th I've managed to solve my usecase by just adding "filterText" with a littile `filterText = v:gsub([[á]], [[a]])` on the spell source, thankfully there's not many variations in spanish which is what I need `áÁéÉíÍóÓúÚ`  😄 If cmp wasn't so awesome there wouldn't be `filterText`

**Comment by muniter** [comment]
Just posting in case someone finds this. Did the following to cmp-spell

```patch
diff --git a/lua/cmp-spell/init.lua b/lua/cmp-spell/init.lua
index 28325e2..1fbdda0 100644
--- a/lua/cmp-spell/init.lua
+++ b/lua/cmp-spell/init.lua
@@ -12,10 +12,35 @@ function source:get_keyword_pattern()
     return [[\K\+]]
 end
 
+local reg = vim.regex("[áÁéÉíÍóÓúÚ]")
+local replacements = {
+  ["á"] = "a",
+  ["Á"] = "A",
+  ["é"] = "e",
+  ["É"] = "E",
+  ["í"] = "i",
+  ["Í"] = "I",
+  ["ó"] = "o",
+  ["Ó"] = "O",
+  ["ú"] = "u",
+  ["Ú"] = "U",
+}
+function source:accents_filtertext(label)
+  if reg:match_str(label) then
+    for acc,unacc in pairs(replacements) do
+      local repl, n = label:gsub(acc, unacc)
+      if n > 0 then  -- Bail after the first substitution
+        return repl
+      end
+    end
+  end
+  return nil
+end
+
 local function candidates(entries)
     local items = {}
     for k, v in ipairs(entries) do
-        items[k] = { label = v }
+        items[k] = { label = v, filterText = source:accents_filtertext(v) }
     end
     return items
 end

```

Spanish only has one accent per word so bailing out in the first substitution makes things faster.

**Comment by dmitmel** [comment]
Hmmm I think you can do it without patching the source code of the original plugin:

```lua
local cmp_spell = require('cmp-spell')

local reg = vim.regex("[áÁéÉíÍóÓúÚ]")
local replacements = {
  ["á"] = "a",
  ["Á"] = "A",
  ["é"] = "e",
  ["É"] = "E",
  ["í"] = "i",
  ["Í"] = "I",
  ["ó"] = "o",
  ["Ó"] = "O",
  ["ú"] = "u",
  ["Ú"] = "U",
}
function source:accents_filtertext(label)
  if reg:match_str(label) then
    for acc,unacc in pairs(replacements) do
      local repl, n = label:gsub(acc, unacc)
      if n > 0 then  -- Bail after the first substitution
        return repl
      end
    end
  end
  return nil
end

local orig_complete = cmp_spell.complete
function cmp_spell:complete(request, callback, ...)
  return orig_complete(request, function(result, ...)
    for _, item in ipairs(result.items) do
      item.filterText = cmp_spell:accents_filtertext(item.label)
    end
    return callback(result, ...)
  end, ...)
end
```

**Comment by hrsh7th** [comment]
`{ name = 'buffer', preprocess = function(response) return response end }` might be useful?

**Comment by muniter** [comment]
@hrsh7th That could be really useful, but at the same time It would be better for the sources to implement it, since adding the preprocess after calling `source:complete` means iterating over all the entries once more.

**Comment by SergioQuijanoRey** [comment]
Having the same issue. It would be awesome to have that implemented by default or, at least, have some handy flag in the lua config to give that behavior without me having to implement it.

 Awesome plugin btw :D

**Comment by tkkcc** [comment]
Same issue after migration from compe. In compe, set 
```lua
require'compe'.setup {default_pattern = [[\k\+]]}
```
works. In cmp, I tried 
```lua
cmp.setup({
  sources = cmp.config.sources({{name = 'buffer', keyword_pattern = [[\k\+]]}}),
  completion = {keyword_pattern = [[\k\+]]},
})
```
But nothing changes.

**Comment by hrsh7th** [comment]
```
sources = cmp.config.sources({{name = 'buffer', option = { keyword_pattern = [[\k\+]]}}}),
```

**Comment by tkkcc** [comment]
Still not work。Buffer contains `本地通知`. I type `本` then `<Tab>`.
```lua
  use {
    'hrsh7th/nvim-cmp',
    requires = {
      'hrsh7th/cmp-path', 'hrsh7th/cmp-cmdline', 'hrsh7th/cmp-nvim-lsp',
      'andersevenrud/cmp-tmux', 'dcampos/cmp-snippy', 'dcampos/nvim-snippy',
    },
    config = function()
      vim.o.completeopt = "menu,menuone,noselect"
      local snippy = require("snippy")
      local cmp = require 'cmp'
      local has_words_before = function()
        local line, col = unpack(vim.api.nvim_win_get_cursor(0))
        return col ~= 0 and
                 vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col,
                                                                            col)
                   :match("%s") == nil
      end
      cmp.setup({
        snippet = {
          expand = function(args)
            require'snippy'.expand_snippet(args.body) -- For `snippy` users.
          end,
        },
        mapping = {
          ['<c-l>'] = cmp.mapping(function(fallback)
            if snippy.can_expand_or_advance() then
              snippy.expand_or_advance()
            else
              fallback()
            end
          end, {"i", "s"}),
          ['<c-h>'] = cmp.mapping(function(fallback)
            if snippy.snippy.can_jump(-1) then
              snippy.previous()
            else
              fallback()
            end
          end, {"i", "s"}),
          ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
              cmp.select_next_item()
            elseif snippy.can_expand_or_advance() then
              snippy.expand_or_advance()
            elseif has_words_before() then
              cmp.complete()
            else
              fallback()
            end
          end, {"i", "s"}),

          ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
              cmp.select_prev_item()
            elseif snippy.can_jump(-1) then
              snippy.previous()
            else
              fallback()
            end
          end, {"i", "s"}),
          ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), {'i', 'c'}),
          ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), {'i', 'c'}),
          ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), {'i', 'c'}),
          ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
          ['<C-e>'] = cmp.mapping({
            i = cmp.mapping.abort(),
            c = cmp.mapping.close(),
          }),
          -- Accept currently selected item. If none selected, `select` first item.
          -- Set `select` to `false` to only confirm explicitly selected items.
          ['<CR>'] = cmp.mapping.confirm({select = false}),
        },
        sources = cmp.config.sources({
          {name = 'snippy'}, {name = 'nvim_lsp'},
          {name = 'buffer', option = { keyword_pattern = [[\k\+]]}}, {name = 'path'},
          {name = 'tmux'},
        }),
        completion = {keyword_pattern = [[\k\+]]},
      })

      -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
      cmp.setup.cmdline('/', {sources = {{name = 'buffer'}}})

      -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
      cmp.setup.cmdline(':', {
        sources = cmp.config.sources({{name = 'path'}}, {{name = 'cmdline'}}),
      })

    end,
  }
```

**Comment by SergioQuijanoRey** [comment]
Thank you very much for the fix :smile:

**Comment by gerazov** [comment]
> ```
> sources = cmp.config.sources({{name = 'buffer', option = { keyword_pattern = [[\k\+]]}}}),
> ```

Please add this as a default setting for all us Unicode users :sweat_smile: otherwise `nvim-cmp` doesn't work with Cyrillic.

**Comment by Andrew15-5** [comment]
> Please add this as a default setting for all us Unicode users 😅 otherwise `nvim-cmp` doesn't work with Cyrillic.

Thank you! I was looking for this. Now I can peacefully write in both languages (with autocompletion) with nvim-cmp (I transitioned from coc.nvim).

**Comment by Andrew15-5** [comment]
Since I'm new to nvim-cmp, can someone tell me how to enable both LSP autocompletion and plain text autocompletion? Because when I add

```lua
  sources = {
    {
      name = "buffer",
      option = {
        keyword_pattern = [[\k\+]],
      },
    },
  },
```

To my nvim-cmp setup config I can now reuse words that are already present in the file, but on the other hand I now can't use autocompletion from an LSP server. The practical reason to use both (if it even needs a reason) is Typst, where you can both write code and text in the same file.

**Comment by Andrew15-5** [comment]
I was able to fix my issue with:

```lua
  sources = {
    { name = "nvim_lsp" },
    {
      name = "buffer",
      option = {
        keyword_pattern = [[\k\+]],
      },
    },
  },
```

**Comment by cofeek-codes** [comment]
i have this as my cmp config
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    dependencies = { "hrsh7th/cmp-emoji" },
    opts = function(_, opts)
      table.insert(opts.sources, { name = "emoji" })
      table.insert(opts.sources, { name = "orgmode" })
      table.insert(opts.sources, { name = "buffer", option = { keyword_pattern = [[\k\+]] } })
      opts.window = {
        documentation = {
          border = "rounded",
          winhighlight = "Normal:MyHighlight",
          winblend = 0,
        },
      }
    end,
  },
}

```
but i still can't autocomplete cyrillic text
