### ISSUE TITLE
documentation.winhighlight

### ISSUE THREAD

**Issue by arpangreat** [hrsh7th/nvim-cmp#455]
Loving The Plugin so much , and Thanks to ❤️

But is there any verbose documentation on how to use `documentation.winhighlight` ??

It would be really helpfull. 😀

**Comment by dmitmel** [comment]
Please see <https://neovim.io/doc/user/options.html#'winhighlight'>

**Comment by arpangreat** [comment]
> Please see https://neovim.io/doc/user/options.html#'winhighlight'

But how to define it for cmp ?? any examples ??

**Comment by dmitmel** [comment]
```lua
require('cmp').setup({
  documentation = {
    winhighlight = 'SomeHlGroup1:OverrideForHlGroup1,SomeHlGroup2:OverrideForHlGroup2',
  },
})
```

**Comment by hrsh7th** [comment]
Thank you @dmitmel

@arpangreat @dmitmel is correct. Please use it.

**Comment by arpangreat** [comment]
Thanks @dmitmel so much ❤️

And specially @hrsh7th for making such great plugin ❤️

**Comment by arpangreat** [comment]
Well @hrsh7th if I configure like this

```lua
 documentation = {
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    winhighlight = { "Normal:#51A266, NormalNC:#0C0C0C" },
  },
```

It throws an error as:
`Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:53: Option 'winhighlight' requires a string value`

**Comment by hrsh7th** [comment]
> Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:53: Option 'winhighlight' requires a string value

```
 documentation = {
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    winhighlight = "Normal:#51A266,NormalNC:#0C0C0C",
  },
```

You should specify comma separated string.

**Comment by arpangreat** [comment]
> > Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:53: Option 'winhighlight' requires a string value
> 
> ```
>  documentation = {
>     border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
>     winhighlight = "Normal:#51A266,NormalNC:#0C0C0C",
>   },
> ```
> 
> You should specify comma separated string.

And It still giving another error as:

`W18: Invalid character in group name`
`Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:94: E474: Invalid argument`

**Comment by hrsh7th** [comment]
See `:h winhighlight`. You should specify `hi-buildin:hi` not color code.

**Comment by arpangreat** [comment]
> See `:h winhighlight`. You should specify `hi-buildin:hi` not color code.

Thanks ❤️

**Comment by oblitum** [comment]
By using `winhighlight` you have this issue (notice weird highlight of parentheses in the docs float):

![img-2021-11-27-120553](https://user-images.githubusercontent.com/1269815/143686853-f3726182-f39e-462a-b259-687230077363.png)
![img-2021-11-27-115917](https://user-images.githubusercontent.com/1269815/143686858-5d69d974-0e7e-42cb-82ac-ccbbafcdc221.png)

Can't open issue now as I'm short in time for filling issue template, but the above screenshots were taken with a very minimal setup (as I don't use nvim-cmp and just wanted to verify everyone relying on `winhighlight` was indeed hit by this).

For more information:

- https://github.com/neoclide/coc.nvim/pull/3487
- https://github.com/neoclide/coc.nvim/issues/1251
- https://github.com/neovim/neovim/issues/16419
