### ISSUE TITLE
Crash when running vim-plug's PlugUpdate

### ISSUE THREAD

**Issue by smackesey** [hrsh7th/nvim-cmp#457]
**Describe the bug**

When I run `PlugUpdate` (from vim-plug), after the update finishes `nvim-cmp` enters an endless error cycle. This message keeps repeating:

```
Error executing vim.schedule lua callback: ... y/.cache/nvimplugin/cmp-buffer/lua/cmp_buffer/buffer.lua:46: Invalid buffer id: 951
```

I have to force-quit neovim to break the loop.

**Comment by hrsh7th** [comment]
Duplicate https://github.com/hrsh7th/cmp-buffer/issues/14
