### ISSUE TITLE
Plans on making it faster than coq.nvim?

### ISSUE THREAD

**Issue by ahmedkhalf** [hrsh7th/nvim-cmp#46]
Hello, I was just wondering if they were perhaps planning to make this plugin faster than nvim-compe and coq.nvim. Like recently, for example, Telescope pushed a feature for asynchronous matching which greatly improved the speed.

Also, I see that there is source creation, any plans on making sort creation too?

**Comment by hrsh7th** [comment]
First, Do you feel thw nvim-cmp slow now?

I think I had optimize nvim-cmp as much as possible.

If nvim ships `mpack` module as builtin, I will try to use it to improve performance.

**Comment by Shougo** [comment]
What is the optimization?
It is very interesting.

**Comment by hrsh7th** [comment]
nvim-cmp will cache the filtered items in every key steoke ( of cource, invalidaye it if need)

**Comment by hrsh7th** [comment]
See https://github.com/neovim/neovim/issues/15452

**Comment by hrsh7th** [comment]
@ahmedkhalf I will improve the documentation. Currently, this is not stable status and under development so documentation priority is a bit low than feature implementation.

If your question solved, please close this issue.

**Comment by ahmedkhalf** [comment]
Thanks

**Comment by captainko** [comment]
[neovim#15566](https://github.com/neovim/neovim/pull/15566)

**Comment by hrsh7th** [comment]
Yes. I will investigate and try and error with it.

**Comment by mortezadadgar** [comment]
@hrsh7th now that 0.6 is released would you tell us about progress you have made in using builtin `mpack` module, btw cmp is really fast and response but who doesn't want a faster completion engine right?

**Comment by hrsh7th** [comment]
I sometimes investigate when I have a free hand.
e.g. https://github.com/hrsh7th/nvim-lua-rpc-example-with-headless

I can't think of a good solution for now.
