### ISSUE TITLE
Attempt to index local `response` (a nil value)

### ISSUE THREAD

**Issue by sudkumar** [hrsh7th/nvim-cmp#461]
**Describe the bug**

This is happening after the latest commit.  I think it is happening because of this line: 
https://github.com/hrsh7th/nvim-cmp/commit/7bc2738e14f280bb368a04b28e09e9bd028e8dd6

```diff
    self.complete_dedup(vim.schedule_wrap(misc.once(function(response)
+     self.incomplete = response.isIncomplete or false

      if #((response or {}).items or response or {}) > 0 then
        debug.log(self:get_debug_name(), 'retrieve', #(response.items or response))
```

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

Simply install the latest update using [Packer](https://github.com/wbthomason/packer.nvim) and it should throw an error when pressing tab after a new line.

**Expected behavior**

Should now throw error if there are no suggestions available. 

**Additional context**

This might be what we can do to handle the `nil` response value. I am not much familiar with lua so this might not be a valid suggestion.

```diff
    self.complete_dedup(vim.schedule_wrap(misc.once(function(response)
-     self.incomplete = response.isIncomplete or false
+     self.incomplete = (response or {}).isIncomplete or false

      if #((response or {}).items or response or {}) > 0 then
        debug.log(self:get_debug_name(), 'retrieve', #(response.items or response))
```

**Comment by hrsh7th** [comment]
Sorry. I've fixed.

**Comment by sudkumar** [comment]
Tested. Working. Thank you for the quick fix. 🙏
