### ISSUE TITLE
Enable key mappings in select mode

### ISSUE THREAD

**Issue by dragove** [hrsh7th/nvim-cmp#464]
Thanks for your awesome plugin.

I'm currently using this plugin with the configuration from [lspconfig](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion) and I encountered a problem with snippet completion.

Some snippets have placeholders, when the completion plugin jumps to the placeholder, neovim will get into `SELECT` mode. Then I can overwrite the placeholder. In some cases, I want to just jump to another snippet node leaving the placeholder unchanged. I found all key mappings don't work in select mode. I wonder if there is a way to enable key mappings in select mode.

**Comment by hrsh7th** [comment]
@dragove You can specify modes for mapping.

```lua
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
  }
```

or 

```lua
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping({
      i = cmp.mapping.select_next_item(),
      s = cmp.mapping.select_next_item(),
    }),
  }
```

**Comment by dragove** [comment]
It works, thanks. For the ones who come for solution, can consider below config:
```lua
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { 'i', 's' })
  }
}
```
