### ISSUE TITLE
Searching for "end" still brings up search history window

### ISSUE THREAD

**Issue by desheffer** [hrsh7th/nvim-cmp#466]
**Describe the bug**

A regression in the most recent commit (2a58b8f) has caused bug #420 to reappear. Using a fresh Neovim install and trying to search for the word "end" (e.g. by typing `/end`) interrupts the search and causes the search history window to appear. I was also able to trigger the bug by searching for keywords like "do" or "fi" in a bash script.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

This minimal config provided here is copied from the previous bug report:

```vim
set rtp+=~/.config/nvim/plugged/nvim-cmp
lua <<EOF
require('cmp')
EOF
```

**To Reproduce**

The steps to reproduce are _nearly_ identical to the previous bug. However, now the bug seems to only appear **after you've been in insert mode**. The full steps to reproduce are:

1. `nvim -u minimal_init.vim minimal_init.vim`
2. **Enter and then leave insert mode** (i.e. type `i` followed by `<Esc>`)
3. Type `/end` (don't press `<CR>`)
4. The search history window pops up

**Expected behavior**

Searching for the word "end" or any variation of it should work like any other search query.

**Additional context**

As mentioned above, it seems this bug was reintroduced in the most recent commit (2a58b8f). The bug does not seem to be present in the previous commit (c67ed9d).

Digging further, the `vim.v.insertmode == 'i'` check that was added [here](https://github.com/hrsh7th/nvim-cmp/blob/2a58b8f926ccacf9fbaa7131ea8c5fae4ff1f797/lua/cmp/utils/api.lua#L20) caught my eye. I did a quick test and noticed that `:lua print(vim.v.insertmode)` outputs `"i"` even after I've left insert mode. It seems to indicate that I've _been_ in insert mode, but not necessarily that I am _in_ insert mode.

Thank you for your hard work building these great plugins!

**Comment by dmitmel** [comment]
It seems that `v:insertmode` is valid only during execution of InsertEnter and InsertLeave commands.

```
                                        *v:insertmode* *insertmode-variable*
v:insertmode    Used for the |InsertEnter| and |InsertChange| autocommand
                events.  Values:
                        i       Insert mode
                        r       Replace mode
                        v       Virtual Replace mode
```

**Comment by hrsh7th** [comment]
Fixed. It's `api.is_insert_mode` bug.

**Comment by hrsh7th** [comment]
BTW, I don't know the elegant solution for avoiding the invalid mode detection on InsertEnter. If someone has a solution, please teach me.
