### ISSUE TITLE
Feature Request: source.complete: allow reusing callback

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-cmp#467]
Hi

First, apologies for not using your issue template. This is not an issue, but a feature request...

Is it possible to return completion items in batches?  For example, lets say my source takes a long time to generates all completion items, and I would it so that the user will not have to wait until all of the results have been computed. If I have some results available, can I return them using `callback(items=..., inComplete=True)`, and, in the near future, reuse the same callback with the rest of the items: `callback(items=more_items, inComplete=True)`? 

I tried doing the above, but it does not seem to work.

**Comment by hrsh7th** [comment]
I can understand this request and it easy.
But I'm afraid to implement it because it is not the same behavior as VSCode and LSP do.

**Comment by tzachar** [comment]
If its easy to support then other sources can just ignore it.
Its really hampering my efforts..
I argue that it makes more sense lioe i am suggesting. IIRC coq.nvim also
operates like this.

**Comment by hrsh7th** [comment]
implemented.

NOTE: nvim-cmp is now allowing the invoking callback multiple times if it is a recent one.

**Comment by tzachar** [comment]
Thank.

The behaviour now is almost what I talked about. The only problem is that `cmp` will now _replace_ all the previous items with new items on every callback call.

Should I resubmit all previous items every time?

**Comment by hrsh7th** [comment]
I can understand it but I can't implement. Sorry.


> Should I resubmit all previous items every time?

Yes. I'm sorry, please do so.
