### ISSUE TITLE
cmdline inserts ^Gu before string

### ISSUE THREAD

**Issue by gegoune** [hrsh7th/nvim-cmp#468]
When `<CR>` is pressed `^Gu` will be added to cmd line.

```lua
local cmp = require 'cmp'

cmp.setup {
    mapping = {
        ['<CR>'] = cmp.mapping {
          i = cmp.mapping.confirm {
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          },
          c = cmp.mapping.confirm { select = false },
        },
  }
}

cmp.setup.cmdline(':', {
  completion = {
    completeopt = 'menu,menuone,noselect',
  },
  sources = cmp.config.sources({
    { name = 'path' },
  }, {
    { name = 'cmdline' },
  }),
})
```

**To Reproduce**

1. Open Neovim with those two things: `CR` and `cmdline` configured as above (I did not manage to make any other things influence that issue.)
2. Open any file.
3. In normal mode type: `:w`
4. Completion menu will show up, `wq` will be top most result.
5. Press `CR` to simply execute inserted command (`w`, with above configuration no completion is highlighted/selected and should not be inserted, but what I have typed in should be executed straight away).
6. Observe how cmdline changes to: `:^Guwq`

**Expected behavior**

`:w` should be executed and no completion replacement should take place.

**Additional context**

I have noticed that yesterday, right after 2a58b8f was created. It works fine on c67ed9d.

I hope description is clear enough, apologies if it isn't.

**Comment by tzachar** [comment]
Also had this problem.
For now, I changed my conf as below, which solved the issue:

```lua
cmp.setup {
    mapping = {
        ['<CR>'] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = false,
          }),
        },
  }
}
```

**Comment by hrsh7th** [comment]
Fixed. It's `api.is_insert_mode` bug.

**Comment by gegoune** [comment]
Fixed indeed. Thank you so much @hrsh7th. ❤️

**Comment by gegoune** [comment]
@hrsh7th small update though, I have just noticed that confirming with CR no longer works, is it something you expected or should I open new issue for that?

**Comment by hrsh7th** [comment]
@gegoune I pushed the wrong commit. I think it's already fixed now.

**Comment by gegoune** [comment]
Sorry to be spamming you, I think issue only applies to `require('cmp').setup.buffer` which now loses mappings defined by `require('cmp').setup {}`.

**Comment by gegoune** [comment]
Yes, works again, apologies for spam!
