### ISSUE TITLE
Completing from an already-present word duplicates existing text

### ISSUE THREAD

**Issue by drewolson** [hrsh7th/nvim-cmp#469]
The bug is a bit hard to describe, so I've included a gif demonstrating the problem. In a nutshell:

* If I enter insert mode, begin typing and word and then trigger autocompletion, all works as expected
* If several characters of a word are _already_ present, I enter insert mode at the _end_ of the existing characters, and _then_ trigger autocompletion, the already-present characters are duplicated.

![completion](https://user-images.githubusercontent.com/3536/140102725-a1a59a33-84a1-4ab2-8ca4-2014f9d16e60.gif)

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

https://github.com/drewolson/vim_dotfiles/blob/master/init.vim

**To Reproduce**

1. Disable auto-completion (this happens on manual completion trigger for me).
2. Enter insert mode, type the first two characters of a word you want to auto-complete
3. Leave insert mode.
4. Enter insert mode at the _end_ of the already-typed characters.
5. Trigger completion, and see the first two characters of the word duplicated.

**Expected behavior**

The first two characters of the word should not be duplicated.

**Additional context**

**Comment by hrsh7th** [comment]
First, this is not a *minimal* config.

Could you provide the log with modifying `lua/cmp/utils/debug.lua`'s debug variable as true?

**Comment by drewolson** [comment]
The only information I see is the following when I trigger completion:

```
nvim_lsp:hls^Irequest^I3^I{                                                                                                                                                        
  triggerKind = 1                                                                                                                                                                  
}
```

**Comment by hrsh7th** [comment]
Don't you get any output if you confirm item?

**Comment by drewolson** [comment]
No output on item confirmation. And the character duplication happens when the item is selected, before it is confirmed.

**Comment by hrsh7th** [comment]
if you don't get the output on item confirmation, it's very weird so you should create minimal configuration.

**Comment by ayamir** [comment]
I have encountered similar problem:

https://user-images.githubusercontent.com/61657399/140294953-59f4beb4-29a7-4c73-8bb9-cf50d4e5feab.mp4

**Comment by drewolson** [comment]
I've made a minimal config using only the buffer source and this bug still persists. Here's the config:

```
set nocompatible
syntax on

call plug#begin('~/.config/nvim/plugged')

Plug 'hrsh7th/cmp-buffer', {'commit': '2d85e76c725a389b72067f86fc3c65f3868b9a59'}
Plug 'hrsh7th/nvim-cmp', {'commit': '753f5b7c92da0302efffc5ce6780dffe0602bdf3'}
Plug 'hrsh7th/vim-vsnip', {'commit': '9ac8044206d32bea4dba34e77b6a3b7b87f65df6'}

call plug#end()

lua <<EOF
local cmp = require 'cmp'

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
    end,
  },
  sources = {
    { name = 'buffer' },
  },
}
EOF
```

And here's another gif of the error happening.

![error](https://user-images.githubusercontent.com/3536/141699929-c1139343-96d5-4b14-aa4d-fa09fe208d5a.gif)

**Comment by charlesbthomas** [comment]
I think this might have been re-introduced. Anyone else still observing this behavior?

**Comment by i007c** [comment]
> 've made a minimal config using only the buffer source and this

yes i have a similar issue

**Comment by i007c** [comment]
https://user-images.githubusercontent.com/64564512/221393149-c60c2d8c-802c-41bb-b750-8e1311f1dfdc.mp4

**Comment by swaroopanand10** [comment]
> 

I also suddenly encountered same error, did you find a method to fix it?

**Comment by swaroopanand10** [comment]
> I think this might have been re-introduced. Anyone else still observing this behavior?
I also suddenly encountered same error, did you find a method to fix it?

**Comment by swaroopanand10** [comment]
> I think this might have been re-introduced. Anyone else still observing this behavior?

yes how did you fix it?

**Comment by ViniciusJO** [comment]
> I think this might have been re-introduced. Anyone else still observing this behavior?

Im having the same problem. Have anyone find the solution? #

**Comment by aaronmcadam** [comment]
I see this problem every day. I've tried changing to `Insert` completion mode, and it didn't help.

**Comment by radkle** [comment]
I got the similar issue when using snippet completion.

**Comment by ditzlike** [comment]
I have the same problem

**Comment by Shougo** [comment]
You should create the new issue with minimal config.

**Comment by mmkumr** [comment]
![image](https://github.com/hrsh7th/nvim-cmp/assets/17456593/47af2759-1501-4e47-b792-33d4e88d55ce)
I am also face the same problem.

**Comment by Shougo** [comment]
It seems dup of https://github.com/hrsh7th/nvim-cmp/issues/1870.

**Comment by mmkumr** [comment]
> It seems dup of #1870.

I have reported this issue again because this issue was marked as closed.

**Comment by neymarsabin** [comment]
I am facing the same issue, the texts get duplicated on selection/completion.

**Comment by mmkumr** [comment]
This problem only occures while using snippet completion. I think we should reopen the issue.

**Comment by mmkumr** [comment]
I was facing this problem because I have mention two snippets engine inside expand parameter of snippet section. For reference this is the part of config:
`snippet = {
                -- REQUIRED - you must specify a snippet engine
                expand = function(args)
                    vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
                    --require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
                    vim.fn["UltiSnips#Anon"](args.body)  -- For `ultisnips` users.
                end,
            },`
