### ISSUE TITLE
Freezes when used in conjunction with a high key-repeat rate.

### ISSUE THREAD

**Issue by Bruflot** [hrsh7th/nvim-cmp#473]
**Describe the bug**
`nvim-cmp` seems to halt/freeze completely when cycling through completion items if you use a high key-repeat rate. My repeat rate is set to 100 -- that is to say for every second I hold down a key, the key will be repeated 100 times. If the completion menu is visible and I hold down `<C-n>`, `nvim-cmp` will halt completely and not do anything until a few seconds after I release the keys. 

Does not seem to be related to any specific sources.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**
The mininal config referenced above can be used as-is to reproduce the problem.

**To Reproduce**
1. Adjust your key-repeat rate to 100. If you're using X11, this can be done with `xset r rate 250 100`.
2. Open a file with a lot of symbols, and then open up the completion menu. Make sure there's at least a good amount of completion items shown (ideally 100+).
3. Hold down `<C-n>` and notice that everything halts.

(The default repeat rate for X11 is 50 for reference)

**Expected behavior**
For `nvim-cmp` to cycle through the completion items quickly without stalling or freezing.

**Additional context**
This may be related to the sheer amount of completion items shown. It does not happen when there are only a handful of completion items to choose from, but always happens when there's a large amount (100+).

**Comment by hrsh7th** [comment]
reproduced. But it's too difficult to fix. I'll investigate but it might not be fixed...
