### ISSUE TITLE
Move item kind to the left of the completion menu

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-cmp#476]
Not sure if this is possible or has been asked before but I would like to know if it is possible to move the item kind to the left of the completion item.

![image](https://user-images.githubusercontent.com/29136904/140405557-ee4fd3f4-34ad-4d1a-bbc3-24a311263759.png)

**Comment by gegoune** [comment]
It's documented [here](https://github.com/hrsh7th/nvim-cmp#formattingfields-type-cmpitemfield).

**Comment by lukamanitta** [comment]
It seems like this documentation has been moved, I can't manage to find it. Any clues?

**Comment by gegoune** [comment]
It's in docs under `cmp-config.formatting.fields` tag.
