### ISSUE TITLE
Question: how to transform s mode to insert mode without lossing word/phrase inder cursor?

### ISSUE THREAD

**Issue by ayoubelmhamdi** [hrsh7th/nvim-cmp#478]
when I use [TAB] for competition, the `cmp` is starting to select `char/word/phrase` in s mode, if I press in `i` or `a` to append or insert new `chars`, all chars under select will be removed
- so how to keep all things and `append/insert` new `chars`

**Comment by Shougo** [comment]
Well..  It is hard to understand.

The example with screenshot is useful.

**Comment by hrsh7th** [comment]
@ayoubelmhamdi nvim-cmp does not have the select-mode related feature.
It seems to invoke your snippet plugin by pressing `<Tab>`. (also this is not the nvim-cmp's feature. it's from your configuration)

**Comment by ayoubelmhamdi** [comment]
yes, now I use `luasnip`
