### ISSUE TITLE
cmdline float offset wrong with wrapped lines

### ISSUE THREAD

**Issue by Iron-E** [hrsh7th/nvim-cmp#479]
**Describe the bug**

With line-wrapping settings enabled, if a line is wrapped it will cause the cmdline to hover in the wrong position:

![cap](https://user-images.githubusercontent.com/36409591/140436105-1e8bc237-f83d-4cde-b1e3-1a36a83e2338.png)

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

It works with the minimal config provided at the above link.

**To Reproduce**

1. Open a file
2. Wrap some lines:
    ```
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ```
3. Try to complete on the commandline, e.g. `:e ~/…`
4. The bar is now above the actual commandline.

**Expected behavior**

The bar will show right above the command-line, as shown here:

![cap](https://user-images.githubusercontent.com/36409591/140436324-3d8e7dcc-3adf-442c-85de-e882801685cd.png)

**Additional context**

I think this has to do with the `nvim_win_get_cursor` implementation. It doesn't matter which row you are on in the screen, because you are _technically_ on the same logical line it will report the same number no matter where you go. Functions like `winline` and `screenrow` report this number correctly across "virtual" rows.

I tried to investigate to find where the cmdline is drawn, but I couldn't find it. It will probably be a matter of swapping one of these functions out though.

I made sure to switch over to `main`, since I have a PR going.

**Comment by hrsh7th** [comment]
@Iron-E What neovim version are you using?

**Comment by Iron-E** [comment]
I am using 0.6/master

**Comment by hrsh7th** [comment]
Hm... I'm using nvim0.6 too. But I can't reproduce with wrapped lines.

In cmdline mode, nvim-cmp uses `lua/cmp/utils/api.lua`'s `get_cursor` method.

**Comment by Iron-E** [comment]
Yeah, I'm gonna report upstream. I think in this case using the new float menus might actually fix the bug whereas the native display (`nvim --clean`) is broken.

Thanks for confirming!
