### ISSUE TITLE
The candidate display is wrong.

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-cmp#48]
The source is nvim_lsp (sumneko_lua).

![image](https://user-images.githubusercontent.com/82267684/130561289-3f5e8147-cdab-4864-8a94-5179ca7d76c1.png)

![image](https://user-images.githubusercontent.com/82267684/130561315-f38440ed-9dc5-4326-a5d7-adf11568e831.png)

If I return to normal mode with esc from the first picture, the display will remain like this.

![image](https://user-images.githubusercontent.com/82267684/130561500-097bc7f8-0722-4d0b-bd62-97bc9be15f16.png)

I am using lspkind, but this is not relevant.

**Comment by hrsh7th** [comment]
It seems to cause by deprecated strike through.
I think it's related to your using fonts. I will disable it by default.

The correct case is here.
<img width="686" alt="スクリーンショット 2021-08-24 14 41 06" src="https://user-images.githubusercontent.com/629908/130562176-0c85d9f5-99f4-4150-829c-bf29f6d9c39e.png">

The `table.move` method is not available in LuaJIT so sumneko_lua mark as deprecated it.

**Comment by uga-rosa** [comment]
I see. Thank you for the response!

**Comment by siduck76** [comment]
@hrsh7th how did you get the [LSP] text in the completion menu? I added lspkind to formatting but I just get the icons :disappointed: 

![image](https://user-images.githubusercontent.com/59060246/130569046-4a8144ef-bfa6-4812-b80c-b574228b8971.png)

**Comment by hrsh7th** [comment]
I have below code in my `formatting.format` function.

```lua
        vim_item.menu = ({
          nvim_lsp = '[LSP]',
          buffer = '[Buf]',
        })[entry.source.name]
```

**Comment by siduck76** [comment]
> I have below code in my `formatting.format` function.
> 
> ```lua
>         vim_item.menu = ({
>           nvim_lsp = '[LSP]',
>           buffer = '[Buf]',
>         })[entry.source.name]
> ```

cool that works , Btw how do I add the completion item type too? cmp by default adds the type text  to the item like "Function" "variable" etc but after adding lspkind it doesnt show that ; 

![image](https://user-images.githubusercontent.com/59060246/130571912-683a1d29-a6cd-4b8e-9ee4-92269871c5c4.png)

compe : 

![image](https://user-images.githubusercontent.com/59060246/130571971-507027b6-17cd-44a0-a6ed-2d96c9fd55c7.png)

**Comment by hrsh7th** [comment]
Try this.
```
        vim_item.kind = lspkind.presets.default[vim_item.kind] .. ' ' .. vim_item.kind
```

**Comment by siduck76** [comment]
thanks that worked.

**Comment by uga-rosa** [comment]
Solved. Thx!!

**Comment by LimbicSys** [comment]
![图片](https://user-images.githubusercontent.com/30319215/133379802-80043205-259b-42ab-9b7f-40241e1ca6f4.png)
I have the same problem with @rhcher. But the strikethrough can be shown properly in neovim when use Windows Terminal.
