### ISSUE TITLE
Inside vimscript's lua block, insert tab / backspace before `}` would return to its original position

### ISSUE THREAD

**Issue by jackysee** [hrsh7th/nvim-cmp#480]
When I'm inside a vimscript, with a lua block like:
```
lua << EOF
local someObj = {
    prop1 = 1,
    prop2 = 2
    }
EOF
```
In insert mode, when I place the cursor before `}` and try tab / backspace, it will always return the cursor and character to its original position. 

![cmp-insert](https://user-images.githubusercontent.com/30516/140466917-af628609-8cd5-42c4-989f-0fa79d1a3262.gif)

If I comment the `require"cmp"` code, the insert works fine.

**Minimal config**
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
call plug#end()

PlugInstall | quit


lua << EOF
local cmp = require'cmp'
local someObj = {
    prop1 = 1,
    prop2 = 2
    }
EOF


```

**To Reproduce**

1.  save above to `test.vim`
2. `nvim -u test.vim test.vim`
3. Try in insert mode, tab / backspace at the last `}` within the lua block

**Expected behavior**

It should allow to insert / delete by tab / backspace.
If I comment out the `require"cmp"` line, the insert works fine.
And it seems only happen in indentation where the `}` is in its own line.

**Additional context**
```
NVIM v0.6.0-dev+553-g7899c4099
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by jackysee** [comment]
I found that if I `set ft=lua`, I can insert tab or backspace.
Maybe a filetype thing?

**Comment by hrsh7th** [comment]
Maybe no. It seems the bug of nvim-cmp to me.
