### ISSUE TITLE
nvim-cmp inserts ^F into a buffer when indentkeys contains =foo

### ISSUE THREAD

**Issue by Julian** [hrsh7th/nvim-cmp#481]
**Describe the bug**

The fix for #443 unfortunately re-regresses on #423, so nvim-cmp again inserts ^F into buffers in the `indentkeys+==foo` scenario.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

(Same as #423)

**To Reproduce**

Same as #423

**Expected behavior**

Same as #423

**Comment by Julian** [comment]
@hrsh7th this behavior is still present :(

**Comment by hrsh7th** [comment]
I've re-fixed it and added the test...... :(

**Comment by hrsh7th** [comment]
It's regression with fixing other issue...

**Comment by Julian** [comment]
Ah! Well indeed now it's gone again, thank you!
