### ISSUE TITLE
[Qusetion] is there anything like max_item_length?

### ISSUE THREAD

**Issue by foodornt** [hrsh7th/nvim-cmp#483]
So I'm editing a css file, and when trying to autocomplete, this shows up:

![image](https://user-images.githubusercontent.com/40924367/140602776-765b5fc2-1631-4e0f-beaa-10894fe389a1.png)

How can I set a maximum width to this menu? so only the first n chars appear and the rest are replaced with a (...)

**Comment by ner0-m** [comment]
Checkout [lspkinds cmp-format](https://github.com/onsails/lspkind-nvim#option-2-nvim-cmp)

**Comment by hrsh7th** [comment]
You can modify the vim's xomplwted item via https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem

Also, You csn use lspkind-nvim.

**Comment by nyngwang** [comment]
> You can modify the vim's xomplwted item via https://github.com/hrsh7th/nvim-cmp#formattingformat-type-funentry-cmpentry-vim_item-vimcompleteditem-vimcompleteditem

@hrsh7th  The link is wrong.
