### ISSUE TITLE
cmdline completion affecting incsearch highlights

### ISSUE THREAD

**Issue by axieax** [hrsh7th/nvim-cmp#485]
**Describe the bug**
Incsearch highlights flicker when cmdline buffer completion is enabled. It seems that when no completion item is selected, the highlights will be quickly turned off, causing the "flickering" effect when typing.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
vim.o.incsearch = true
vim.o.completeopt = "menu,menuone,noselect"
cmp.setup.cmdline("/", {
  sources = {
    { name = "buffer" },
  },
})
```
[See more](https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/cmp.lua)

**To Reproduce**

1. Try searching the buffer with my settings
2. Highlights will go crazy

https://user-images.githubusercontent.com/62098008/140614408-69942d2b-df51-4f04-9423-6fde44e54b2e.mp4

**Expected behavior**

Highlights will persist even if no completion item is selected - using whatever is being typed.

**Additional context**

**Comment by hrsh7th** [comment]
I think it can't be fixed because wilder.nvim has a same problem. (I think wilder.nvim is more detailed with cmdline completion, so I think it would be difficult if wilder.nvim couldn't.
