### ISSUE TITLE
Some keys in insert mode doesn't work after loadview command

### ISSUE THREAD

**Issue by BerkinAKKAYA** [hrsh7th/nvim-cmp#487]
**Describe the bug**

After i call the ':loadview' command (manually or with `vim.api.nvim_command('au BufWinEnter * loadview')`), enter key and arrow keys stops working. It gives the error;

```
E5108: Error executing lua .../nvim-cmp/lua/cmp/utils/keymap.lua:261: attempt to index local 'definition' (a nil value)
```

---
My setup;

```lua
-- init.lua

local servers = { 'pyright', 'rust_analyzer', 'tsserver', 'cssls', 'vuels' }
for _, lsp in ipairs(servers) do
	require('lspconfig')[lsp].setup {
		capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
	}
end

cmp.setup({
	snippet = {
		expand = function(args)
			require('luasnip').lsp_expand(args.body)
		end,
	},
	mapping = {
		['<C-u>'] = cmp.mapping.scroll_docs(-4),
		['<C-d>'] = cmp.mapping.scroll_docs(4),
		['<C-Space>'] = cmp.mapping.complete(),
		['<C-e>'] = cmp.mapping.close(),
		['<CR>'] = cmp.mapping.confirm({ select = true }),
	},
	sources = {
		{ name = 'nvim_lsp' },
		{ name = 'luasnip' },
		{ name = 'buffer' },
	}
})

...
```

I installed nvim-cmp via paq.
My init.lua is [here](https://github.com/BerkinAKKAYA/dotfiles/blob/main/config/nvim/init.lua)

---

**To Reproduce**

1. Call `:loadview`
2. Press Enter or Arrow Keys.

---

I tried commenting out all the mappings and disabling luasnip but i couldn't find the reason. I tried adding a `if definition == nil then return` statement to keymap.lua, it hided the error but keys still doesn't work.

**Comment by hrsh7th** [comment]
Please update plugin...

**Comment by BerkinAKKAYA** [comment]
Updating the plugin then cleaning the `.local/share/nvim/view` folder fixed it, thanks.
