### ISSUE TITLE
Snippet completion triggered without prefix

### ISSUE THREAD

**Issue by marcushwz** [hrsh7th/nvim-cmp#49]
Working on migration from `nvim-compe` to here, and I have this issue, where snippet completions got triggered even when I haven't type anything yet.

## Actual Behavior
- Snippet completions got triggered without any prefix
- Example in typescript
![image](https://user-images.githubusercontent.com/40255418/130613824-34d99e64-bf41-48cd-bf6f-8e0b84fa5735.png)

- Example in ruby
![image](https://user-images.githubusercontent.com/40255418/130613904-b8d14f15-4b1b-4a34-9468-fe2c7ef59253.png)

## Expected Behavior
- I am expecting that snippets completion should only be triggered if I type in the prefix.

## Config

```lua
local cmp = require 'cmp'
cmp.setup {
  completion = {
    completeopt = 'menu,menuone,noinsert'
  },
  snippet = {
    expand = function(args)
        vim.fn['vsnip#anonymous'](args.body)
    end
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-d>'] = cmp.mapping.scroll(-4),
    ['<C-f>'] = cmp.mapping.scroll(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
    ['<Tab>'] = cmp.mapping.mode({ 'i', 's' }, function(_, fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
      else
        fallback()
      end
    end),
    ['<S-Tab>'] = cmp.mapping.mode({ 'i', 's' }, function(_, fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n')
      else
        fallback()
      end
    end),
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  },
}
```

**Comment by hrsh7th** [comment]
It's weird... I can't reproduce.

Anyway, you can set `completion.autocomplete = { cmp.TriggerEvent.TextChanged }` to avoid this.

**Comment by marcushwz** [comment]
Thanks for the reply. I have added that but the same thing still happens.

```lua
  completion = {
    autocomplete = { cmp.TriggerEvent.TextChanged },
    completeopt = 'menu,menuone,noinsert'
  },
```

**Comment by marcushwz** [comment]
I tried debugging them a bit, and it seems like if the `prefix` contain any `spaces` then it will get triggered. Once i remove the spaces then it will not get triggered.

```json
  "if else": {
    "prefix": "if else",
    "body": ["if ${1:test}", "\t$0", "else", "\t", "end"]
  },
  "if elsif": {
    "prefix": "if elsif",
    "body": ["if ${1:test}", "\t$0", "elsif ", "\t", "end"]
  },

```

**Comment by hrsh7th** [comment]
OK. It seems a cmp-vsnip problem.

**Comment by marcushwz** [comment]
I will close this issue then, do you want me to create one on `cmp-vsnip`?

For my use case now, I will just rename the prefix and delete those that I am not using.

Thanks again! Enjoying the new one so far, great work! :)

**Comment by hrsh7th** [comment]
Hm... I'm investigating it now. It's a bit difficult 🤣

**Comment by hrsh7th** [comment]
I've forgotten pushing local changes on cmp-vsnip 🤭

**Comment by abzcoding** [comment]
i have a similar issue with `luasnip` as well, so I'm not sure the root cause is `cmp-vsnip` or not
![image](https://user-images.githubusercontent.com/10992695/130672364-834c8299-1381-4985-a05d-aa52306243ec.png)
and even if I do the following, 
![image](https://user-images.githubusercontent.com/10992695/130672498-c2d1da34-a167-44f6-b260-4625bf6f1477.png)

I'll get the same issue just after doing sth like ` permissions = `

[my configurations](https://github.com/abzcoding/nvim/commit/658731a651d1e51236bce39d421b1dd8675e02b6) for reference

**Comment by hrsh7th** [comment]
@abzcoding No. because `cmp-vsnip` issue is solved by `cmp-vsnip`'s commit.
You should open issue to `cmp-luasnip` repo.

**Comment by abzcoding** [comment]
> cmp-luasnip

thank you, just added a PR and tested it locally https://github.com/saadparwaiz1/cmp_luasnip/pull/3
