### ISSUE TITLE
cmdline completion not work for some plugins

### ISSUE THREAD

**Issue by aspeddro** [hrsh7th/nvim-cmp#490]
**Describe the bug**

Using `cmp.setup.cmdline` some commands completion not work.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'aspeddro/tex.nvim'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
require'tex'.setup()
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}

cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```
With `cmdline.setup`:

![image](https://user-images.githubusercontent.com/16160544/140668672-321ebe49-6029-4947-9c88-eb5f853cffc5.png)

Without `cmdline.setup`:

![image](https://user-images.githubusercontent.com/16160544/140668967-c8b7841a-677e-480c-85cb-50b475dede97.png)

**To Reproduce**

1. Open nvim
2. `:TexSwitchEngine` press `space` and `tab`

**Expected behavior**

Completion work same behavior of native menu

**Additional context**

Plugin tested: https://github.com/aspeddro/tex.nvim

**Comment by hrsh7th** [comment]
Fixed by cmp-cmdline source side. Thank you.
