### ISSUE TITLE
html, cssls server not working 

### ISSUE THREAD

**Issue by woong-s** [hrsh7th/nvim-cmp#491]
**Describe the bug**

[ WARN ] 2021-11-08T11:02:58+0900 ] ...nvim/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]   "The language ser
       │ ver html triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is
       │  harmless"

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

**Additional context**

can you fix bug? 

**i can't use html, cssls of cmp**, but  work tsserver, gopls

**Comment by hrsh7th** [comment]
I can't reproduce. It works fine.

I can't debug without information.
