### ISSUE TITLE
Add IntelliJ-like completion to docs

### ISSUE THREAD

**Issue by danymat** [hrsh7th/nvim-cmp#492]
Hello,

Thanks for doing such a great plugin, that helps me a lot!
In the process of changing my cmp keybinds, I wanted to mimic the IntelliJ-like completion, which is:

- If no completion is selected, insert the first one in the list.
- If a completion is selected, insert this one.

I did implement this like this:

```lua
["<Tab>"] = cmp.mapping(function(fallback)
	-- This little snippet will confirm with tab, and if no entry is selected, will confirm the first item
	if cmp.visible() then
		local entry = cmp.get_selected_entry()
		if not entry then
			cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
		end
		cmp.confirm()
	else
		fallback()
	end
end, {
	"i",
	"s",
	"c",
}),
```

And I think we could make it work into the README or the cmp docs, because:
1. It helps users switching from alternative IDE's to mimic their workflow
2. It provides the user examples on how to create their own mappings

**Comment by hrsh7th** [comment]
You can edit the wiki page https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings

Thank you!
