### ISSUE TITLE
Move cursor outside brackets when the calling function needs no signatures.

### ISSUE THREAD

**Issue by thuan1412** [hrsh7th/nvim-cmp#497]
When I call a function, no matter what signatures it needs, the cursor is always placed inside the brackets.
I think it would be useful when we automatically move the cursor outside the brackets when the calling function needs no signatures.

**Comment by hrsh7th** [comment]
nvim-cmp does not decide the cursor position by `itself`.

nvim-cmp will follow the instruction from the completion `source` like cmp-nvim-lsp (of source, the instruction came from the `LSP server` so I can't control the behavior for this)
