### ISSUE TITLE
Disable in buftype prompt

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#5]
nvim-cmp is enabled even if buftype is prompt. For example when searching in telescope. It would be great if it would be turned off in buftype prompt like with nvim-compe.

Awesome work btw!

**Comment by hrsh7th** [comment]
Thank you for your report. I've fixed it by 22ec3ad442462294b464e4418126ffdecd0cafe0

**Comment by carlitux** [comment]
getting this when selecting a telescope item in insert mode and add 0 at the end of the prompt

```E5108: Error executing lua ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:77: attempt to call a table value``` 

Maybe related with this https://github.com/hrsh7th/nvim-cmp/issues/30

I have to go to normal mode in prompt and hit enter to open the file
