### ISSUE TITLE
Deno LS Markdown TypeScript code blocks have no syntax highlighting

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/nvim-cmp#500]
**Describe the bug**

The Deno LS shows Markdown that should be syntax highlighted for TypeScript, but it is not. This was previously assumed to be a bug in Deno, but this bug has since been fixed and is now in either nvim-cmp or Neovim itself.

Please see https://github.com/denoland/deno/issues/12620#issuecomment-957679790 and the entire thread to see the problem in context.

There was a similar issue in the past which may shed some light on this https://github.com/hrsh7th/nvim-compe/issues/373

It is not just the SignatureHelp, but all markdown code blocks returned by Deno:

![Screenshot from 2021-11-09 10-44-22](https://user-images.githubusercontent.com/12832280/140910412-f6ea3052-c43f-4934-9caf-c8b59fd613f4.png)

**To Reproduce**
1. Use the Deno language server https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols
3. Start typing `Deno.test` (or any function that has code blocks)

I have tested on Neovim 0.5.1 and the latest master, same result

I am using no special nvim-cmp setup, just copy pasted from the example README.

**Additional context**

Deno has the fix mentioned in https://github.com/denoland/deno/issues/12620#issuecomment-957679790 released later today in version `1.16.0`, but you can use that version now by typing `deno upgrade --canary`. The fix seems to make no difference in Neovim.

**Comment by hrsh7th** [comment]
nvim-cmp uses neovim's built-in markdown highlighter.
See https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/view/docs_view.lua#L50

**Comment by hrsh7th** [comment]
The upstream issue was closed and it seems solved.
