### ISSUE TITLE
Possible to config custom get_trigger_characters for each source?

### ISSUE THREAD

**Issue by sandangel** [hrsh7th/nvim-cmp#501]
I have the `fuzzy_path` source which has trigger characters as `.`, `/`, `~`. I only want it is triggered on `/`, I tried to config with `completion = { get_trigger_characters: ... }`, but that is for all completion sources and will be overwritten by each source. Is there a way to do it for each complete source?

**Comment by hrsh7th** [comment]
Yes. Currently, nvim-cmp does not suppor this.

PR welcome :)

**Comment by sandangel** [comment]
I think I found a workaround. I overwrite the function before calling cmp.setup 

```lua
local cmp_path = require 'cmp_path'

cmp_path.get_trigger_characters = function()
  return { '/' }
end
```

😅

**Comment by hrsh7th** [comment]
I've added the `cmp.setup { sources = { { name = " ... ", trigger_characters = { '.' } } } }`

**Comment by sandangel** [comment]
awesome. thanks very much.
