### ISSUE TITLE
Feature/doc request: <expr> mappings in programmatic API

### ISSUE THREAD

**Issue by smackesey** [hrsh7th/nvim-cmp#502]
I am adopting `nvim-cmp` gradually. In some projects I still use coc or omni completion. I would like to have completion mappings that work across all my projects, regardless of whether the underlying provider is cmp, coc, or omni.

To my knowledge, there is no way to programmatically manipulate the builtin popup menu. This means you have to use `<expr>` mappings. For example, here is how I define a "start completion or go to next item" command:

```vim
inoremap <expr> <Plug>(completion-next) <SID>completion_next()

function! s:completion_next()
  let prov = util#get_completion_engine()
  if prov ==# 'coc'
    if pumvisible()
      return "\<C-n>"
    else
      return coc#refresh()
    end
  elseif prov ==# 'omni'
    if pumvisible()
      return "\<C-n>"
    else
      return "\<C-x>\<C-o>"
    endif
  elseif prov ==# 'cmp'
    " WHAT CAN I PUT HERE?
  else
    echo printf('No behavior defined for completion provider %s', prov)
  endif
endfunction
```

As you can see in the above block, I am not sure what to put for cmp-- I need to return appropriate strings that will trigger `cmp.select_next_item` and `cmp.confirm`. But AFAICT, cmp's programmatic API doesn't support this.

If cmp *does* support programmatic `<expr>` mappings, consider this a request to make this clearer in the docs. If not, then this is a feature request to add this functionality.

**Comment by hrsh7th** [comment]
I didn't think the user exists who want to use expr map with nvim-cmp.

Hm...
I think you might able to use `<Cmd>lua require('cmp').complete()<CR>`.

**Comment by smackesey** [comment]
It works! Didn't realize you could do this, thanks.
