### ISSUE TITLE
ghost text for arguments

### ISSUE THREAD

**Issue by linde12** [hrsh7th/nvim-cmp#503]
Hi! This is more of a question than a bug, so im not sure this is the right place, but in the repo video you get ghost text for the arguments and i'm trying to achieve the same thing but with tsserver, however i can't get it to work. I get ghost text for function names and such, but not the arguments. Is this supported?

Thanks for your work!

**Comment by hrsh7th** [comment]
The ghost text content is determined by the LSP server (or custom source).

For example, gopls will show the function arguments as ghost text. So it is depending on the your server. I can't support it in nvim-cmp. Sorry.

<img width="1413" alt="スクリーンショット 2021-11-10 3 59 52" src="https://user-images.githubusercontent.com/629908/140987423-128824fe-87a2-494a-88c1-8223e74e7137.png">

**Comment by burgessa23** [comment]
According to https://github.com/neovim/nvim-lspconfig/issues/1259 tsserver supports snippet completion now. Is there something that needs to be set in `capabilities` to get it working?
