### ISSUE TITLE
Mappings are broken after update

### ISSUE THREAD

**Issue by frei-0xff** [hrsh7th/nvim-cmp#505]
I have Tab key mapped to `cmp.select_next_item()`.
After plugin update, Tab key no longer works in insert mode when floating window is not visible.

**Minimal config**

```vim
call plug#begin(stdpath('data').'/plugged')
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { 'i', 's', }),
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF
```

**To Reproduce**

1. Open new blank file
2. Go to insert mode by pressing `<i>`
3. Press `<Tab>`

**Expected behavior**

`<Tab>` character should be inserted.

**Observed behavior**

Text `<Plug>(cmp.utils.keymap.recursive:      )`  is inserted.

**Comment by CadeMichael** [comment]
I just installed so I can't say if it is due to an update but I am not having the correct response from mappings either. When I type enter in insert mode, no matter the context I get the following error and then a 0 where I wanted to insert a new line.

```
E5108: Error executing lua ...e/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua
:188: Vim:E117: Unknown function: compe#confirm
```

**Comment by infraorder** [comment]
Bump ^

**Comment by hrsh7th** [comment]
I can't reproduce.

https://user-images.githubusercontent.com/629908/141089872-530edc75-794d-4de0-8de7-7885b8b1d592.mp4

**Comment by infraorder** [comment]
What neovim version?
I can reproduce with 0.5.1

**Comment by hrsh7th** [comment]
I'm using the below.

```
NVIM v0.6.0-dev+565-g8cbe100fc
Build type: Release
LuaJIT 2.1.0-beta3```

**Comment by infraorder** [comment]
Weird
so mine is the following:
`NVIM v0.6.0-dev+569-g2ecf0a4c6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3`

currently using an appimage for neovim

**Comment by hrsh7th** [comment]
> I can reproduce with 0.5.1

@infraorder How to reproduce this? Can you reproduce with the same as the screencast?

**Comment by infraorder** [comment]
I use [nvchad](https://github.com/NvChad/NvChad/)

maybe try using this instead of your config?
would be the easiest

will see where the snippet is for the actual issue within that

**Comment by infraorder** [comment]
> > I can reproduce with 0.5.1
> 
> @infraorder How to reproduce this? Can you reproduce with the same as the screencast?

Sure will do a screencast

**Comment by infraorder** [comment]
Not sure this helps but

```lua
keymap.recursive = function(bufnr, mode, lhs, rhs)
  rhs = keymap.normalize(rhs)

  local recursive_lhs = ('<Plug>(cmp.utils.keymap.recursive:%s)'):format(lhs)
  local recursive_rhs = string.gsub(rhs, '^' .. vim.pesc(keymap.normalize(lhs)), recursive_lhs)
  if not keymap.equals(recursive_rhs, rhs) then
    keymap.set_map(bufnr, mode, recursive_lhs, lhs, {
      expr = false,
      noremap = true,
      silent = true,
    })
  end
  return recursive_rhs
end

---Set keymapping
keymap.set_map = setmetatable({
  callbacks = {}
}, {
  __call = function(self, bufnr, mode, lhs, rhs, opts)
    if type(rhs) == 'function' then
      local id = misc.id('cmp.utils.keymap.set_map')
      self.callbacks[id] = rhs
      if opts.expr then
        rhs = ('v:lua.cmp.utils.keymap.set_map(%s)'):format(id)
      else
        rhs = ('<Cmd>call v:lua.cmp.utils.keymap.set_map(%s)<CR>'):format(id)
      end
    end

    if bufnr == -1 then
      vim.api.nvim_set_keymap(mode, lhs, rhs, opts)
    else
      vim.api.nvim_buf_set_keymap(bufnr, mode, lhs, rhs, opts)
    end
  end
})
```
this snippet here seems to be the cause `vim.api.nvim_set_keymap(mode, lhs, rhs, opts)`

also uploaded a screencast


https://user-images.githubusercontent.com/39032044/141101809-c1d46fdf-ec86-4eb6-9abe-922929a548eb.mp4

**Comment by hrsh7th** [comment]
What is the output of `:imap` after `nvim test` and once enter to the insert-mode?

**Comment by infraorder** [comment]
i  "           *@v:lua.MPairs.autopairs_map(2,'"')
i  '           *@v:lua.MPairs.autopairs_map(2,"'")
i  (           *@v:lua.MPairs.autopairs_map(2,"(")
i  )           *@v:lua.MPairs.autopairs_map(2, ')')
i  [           *@v:lua.MPairs.autopairs_map(2,"[")
i  ]           *@v:lua.MPairs.autopairs_map(2, ']')
i  `           *@v:lua.MPairs.autopairs_map(2,"`")
i  {           *@v:lua.MPairs.autopairs_map(2,"{")
i  }           *@v:lua.MPairs.autopairs_map(2, '}')
i  <Plug>(cmp.utils.keymap.recursive:<Tab>) * <Tab>
i  <C-Space>   * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600969)<CR>
i  <Plug>(cmp.utils.keymap.evacuate:<CR>) * v:lua.MPairs.completion_confirm()
i  <Plug>(cmp.utils.keymap.evacuate:<Tab>) & v:lua.cmp.utils.keymap.set_map(18600965)
i  <S-Tab>     * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600963)<CR>
i  <Up>        * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600959)<CR>
i  <Down>      * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600957)<CR>
!  <Plug>luasnip-delete-check * <Cmd>lua require'luasnip'.unlink_current_if_deleted()<CR>
i  <Plug>luasnip-jump-prev * <Cmd>lua require'luasnip'.jump(-1)<CR>
i  <Plug>luasnip-jump-next * <Cmd>lua require'luasnip'.jump(1)<CR>
i  <Plug>luasnip-prev-choice * <Cmd>lua require'luasnip'.change_choice(-1)<CR>
i  <Plug>luasnip-next-choice * <Cmd>lua require'luasnip'.change_choice(1)<CR>
i  <Plug>luasnip-expand-snippet * <Cmd>lua require'luasnip'.expand()<CR>
i  <Plug>luasnip-expand-or-jump * <Cmd>lua require'luasnip'.expand_or_jump()<CR>
i  <Plug>(matchup-c_g%) * <C-\><C-O>:call matchup#motion#insert_mode()<CR>
i  <Plug>(vsnip-jump-prev) * <Esc>:<C-U>call <SNR>32_jump(-1)<CR>
i  <Plug>(vsnip-jump-next) * <Esc>:<C-U>call <SNR>32_jump(1)<CR>
i  <Plug>(vsnip-expand) * <Esc>:<C-U>call <SNR>32_expand()<CR>
i  <Plug>(vsnip-expand-or-jump) * <Esc>:<C-U>call <SNR>32_expand_or_jump()<CR>
i  <C-A>       * <Esc>^i
i  <C-D>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600968)<CR>
i  <C-E>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600961)<CR>
i  <C-F>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600962)<CR>
i  <C-G>%        <Plug>(matchup-c_g%)
i  <C-H>       * <Left>
i  <Tab>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600966)<CR>
i  <NL>        * <Down>
i  <C-K>       * <Up>
i  <C-L>       * <Right>
i  <CR>        * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600967)<CR>
i  <C-N>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600970)<CR>
i  <C-P>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600960)<CR>
i  <C-U>       * <C-G>u<C-U>
i  <C-W>       * <C-G>u<C-W>
i  <C-Y>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(18600964)<CR>
i  <C-]>       & copilot#Dismiss() . "\<C-]>"
i  <C-]>       & copilot#Dismiss() . "\<C-]>"

**Comment by frei-0xff** [comment]
@hrsh7th Sorry, as it turned out my config wasn't minimal.
A had also copilot.vim plugin loaded, and the bug appears only with it.
So, the right minimal config is:
```vim
call plug#begin(stdpath('data').'/plugged')
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'neovim/nvim-lspconfig'
Plug 'github/copilot.vim'
call plug#end()

lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { 'i', 's', }),
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF
```

**Comment by infraorder** [comment]
@frei-0xff I also have github/copilot.vim in my nvim.

Confirmed working w/o it!

**Comment by hrsh7th** [comment]
copilot.vim has a automatically `<Tab>` mapping and fallbacking mechanism.
So you should add variable like the below.

```
  let g:copilot_no_tab_map = v:true
  let g:copilot_assume_mapped = v:true
```

**Comment by frei-0xff** [comment]
>   let g:copilot_no_tab_map = v:true
>   let g:copilot_assume_mapped = v:true

Thank you, it helps.

**Comment by lilibyte** [comment]
Same issue: `<Plug>(cmp.utils.keymap.recursive: )` is inserted after hitting Enter. This is happening only in Markdown files since I updated to v0.6.0 today and stopped happening when I uninstall [gabrielelana/vim-markdown](https://github.com/gabrielelana/vim-markdown). Noting for prosperity sake.

**Comment by robbyki** [comment]
getting the same issue this morning in any file as long is I have `["<CR>"].=.cmp.mapping.confirm({.select.=.true.})` in the very minimal config I have then I get the `<Plug>(cmp.u.k.recursive:` printouts with `CR` press. not sure what's happening. Trying to strip down my configs more and more to see if I can track down a conflict but still no luck. Was working fine yesterday.

**Comment by Leandros** [comment]
For me, the culprit seems to be:

```
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```
