### ISSUE TITLE
Completion menu not closing after going to command mode

### ISSUE THREAD

**Issue by jeanlucthumm** [hrsh7th/nvim-cmp#506]
**Describe the bug**
Completion menu should close once user goes into command mode

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

Identical to the provided vimrc.

**To Reproduce**

1. Start typing until completion menu comes up
2. Do not select anything
3. Hit `<C-C>` to go to command mode
4. Completion menu is stuck. Stays in same place even when you scroll page

**Expected behavior**
Completion menu should disappear immediately when pressing `<C-C>`

**Additional context**
I couldn't tell if this was intended behavior, but I didn't find a config option relating to this.

**Comment by Shougo** [comment]
You should not use `<C-c>` to go to command mode.
It breaks plugins behavior.

**Comment by hrsh7th** [comment]
@jeanlucthumm What the nvim version are you using? It will work if you using 0.6.x

**Comment by jeanlucthumm** [comment]
Upgrading seems to have worked, but note that I originally had 0.6.x as well:
```
> nvim --version
NVIM v0.6.0-dev+210-g6751d6254
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
Updated version:
```
> nvim --version
NVIM v0.6.0-dev+569-g2ecf0a4c6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
