### ISSUE TITLE
Issue with Lsp Snippet jump to next placeholder (clojure-lsp)

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-cmp#507]
**Describe the bug**

Using Clojure-lsp, jumping to the next placeholder does not. When confirming a snippet, the first placeholder is highlighted okay but then tab just post 2 spaces.

The server returns 

```json
"(defn%s ${1:name} [$2]\n  $0)"
```
but after is selected and modified nothing works

**Minimal config**

https://gist.github.com/tami5/5da1dae368202898f8d408bef6ad60b3

**To Reproduce**

1. select a snippet item
2. overwrite first placeholder
3. tab

**Expected behavior**

recognize snippet placeholder

**Comment by jethrosun** [comment]
I think you want to follow [this](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings) to set it up according to what snippet engine you are using

**Comment by tami5** [comment]
@jethrosun I believe I have set up this in the minimal config + this issue seems to happen in clojure-lsp only

**Comment by hrsh7th** [comment]
I think this issue can be fixed https://github.com/hrsh7th/nvim-cmp/issues/513.

**Comment by kkharji** [comment]
> I think this issue can be fixed https://github.com/hrsh7th/nvim-cmp/issues/513.

Thanks @hrsh7th I will test it out in a bit

**Comment by tami5** [comment]
> I think this issue can be fixed #513.

Thanks @hrsh7th, I will test it out in a bit

**Comment by tami5** [comment]
Nice no longer an issue. @hrsh7th  you are the best
