### ISSUE TITLE
Unable to override default <c-y> mapping

### ISSUE THREAD

**Issue by cbochs** [hrsh7th/nvim-cmp#508]
**Describe the bug**

Was attempting to override the default confirm behaviour with the same keymapping (`<c-y>`) and it didn't look to be working. Went ahead and commented out the default mapping for `<c-y>` (see: [default.lua#L112](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/default.lua#L112)) and it resolved the issue. I think this has something to do with the misc#merge?

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
local cmp = require('cmp')
cmp.setup({
  mapping = { ['<c-y>'] = cmp.mapping.confirm({ select = true })
})
```

**To Reproduce**

1. Override the `<c-y>` mapping during cmp setup

**Expected behaviour**

Expect to see the `select = true` behaviour, but the default `select = false` behaviour is observed

**Additional context**

**Comment by hrsh7th** [comment]
It's critical bug. Thank you!

**Comment by hrsh7th** [comment]
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/vim-vsnip'
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require('cmp')
cmp.setup {
  snippet = {
    expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<c-y>'] = cmp.mapping.confirm({ select = true }),
  },
  sources = {
    { name = 'buffer'},
  },
}
EOF
```

It's worked as expected.

**Comment by hrsh7th** [comment]
#533
