### ISSUE TITLE
Issues with Treesitter

### ISSUE THREAD

**Issue by tobiwild** [hrsh7th/nvim-cmp#510]
**Describe the bug**

Since I switched from coc.nvim to this plugin I experienced severe issues with Treesitter which are also described here: https://github.com/nvim-treesitter/nvim-treesitter/issues/651
(mainly when using Treesitter for PHP)

I could completely solve the issue by using Neovim's method to apply text edits:

```
function! cmp#apply_text_edits(bufnr, text_edits) abort
    call luaeval('vim.lsp.util.apply_text_edits(_A[1], _A[2])', [a:text_edits, a:bufnr])
endfunction
```

I know this should probably be fixed in Neovim/Treesitter, I just wanted to post this issue FYI.

Tested with NVIM v0.6.0-dev+03b805aee

**Comment by hrsh7th** [comment]
Hm... I don't know how to detect the neovim version that contains the https://github.com/neovim/neovim/pull/15561 or not...

**Comment by mjlbach** [comment]
0.6 will be out in a few weeks so I would just check for has 0.6

**Comment by hrsh7th** [comment]
@mjlbach Thank you! If 0.6.0 released, I'll change the implementation.

**Comment by hrsh7th** [comment]
Fixed. Thank you.
