### ISSUE TITLE
Tab at start of line behave differently than in middle of line

### ISSUE THREAD

**Issue by kuon** [hrsh7th/nvim-cmp#512]
I have this simple configuration:

```lua
local nvim_lsp = require'lspconfig'

-- Enable rust_analyzer
nvim_lsp.rust_analyzer.setup({
  on_attach=on_attach,
  settings = {
        ["rust-analyzer"] = {
            assist = {
                importGranularity = "module",
                importPrefix = "by_self",
            },
            cargo = {
                loadOutDirsFromCheck = true
            },
            procMacro = {
                enable = false
            },
        }
    }
})

nvim_lsp.elixirls.setup{
  cmd = { "/usr/lib/elixir-ls/language_server.sh" };
}



-- nvim-cmp setup
local cmp = require 'cmp'

cmp.setup {
  snippet = {
    expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'buffer', opts = {
      get_bufnrs = function()
        return vim.api.nvim_list_bufs()
      end
    }},
    { name = 'path' },
  },
}

```

In a rust file, if I am at a start of a line, and type `c` the menu open and propose `case` to me, but `case` is already selected, so I have to hit tab, then shift tab to get back. If I am not at the start of the line, for example if I type `self.c` I will get the proper completion with fields starting with `c` but they are not selected, I have to hit tab to select one.

I do not know if this is a bug or a normal behavior, but what I'd like if is the proposed entry is selected but not completed, the first hit on tab should complete and not go to the next item.

**Comment by hrsh7th** [comment]
I can't understand but rust-analyzer has a `preselect` feature. If it causes the problem, you can disable it by `cmp.setup { preselect = cmp.PreselectMode.None }`

**Comment by kuon** [comment]
> I can't understand but rust-analyzer has a `preselect` feature. If it causes the problem, you can disable it by `cmp.setup { preselect = cmp.PreselectMode.None }`

Yes, that seems to be it.

Basically, when I type "re" it would preselect "return" in the menu, but then to complete "re" into "return" I have to select the next item `cmp.mapping.select_next_item()` and then back to "return" with `cmp.mapping.select_prev_item()`.

The behavior I want is if typing "re" preselect "return", doing `cmp.mapping.select_next_item()` should "reselect" "return" and apply the completion. But the solution you proposed work, disabling preselect fixes my issue.

**Comment by hrsh7th** [comment]
I'm sorry. I may not understand exactly what you mean.

Is this issue still be closed or I should re-open this?
