### ISSUE TITLE
Extmarks are extended to the entire line after completion

### ISSUE THREAD

**Issue by dcampos** [hrsh7th/nvim-cmp#513]
**Describe the bug**

After commit 60710622896df79e97048173eabe9752c3bbf7c4, `cmp.confirm()`, if called from within an `extmark`, changes the current extmark to include the whole line. This breaks plugins that rely on extmarks, like some snippet managers.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

<details>
<summary>Minimal config</summary>

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "buffer" },
  },
}
EOF

function! s:simulate() abort
    call setline(1, ['# ipsum', 'Lorem ipsum dolor sit amet'])
    let l:ns = nvim_create_namespace('simulation')
    call nvim_buf_set_extmark(0, l:ns, 1, 6, { 'end_line': 1, 'end_col': 11, 'hl_group': 'Search', 'right_gravity': v:false , 'end_right_gravity': v:true })
endfunction

command! Simulate call s:simulate()
```
</details>

**To Reproduce**

1. Run `:Simulate`
2. Go to line 2, visually select "ipsum" and press `<C-g>` to enter select mode.
3. Type i, use `<down>` to select 'ipsum' from cmp's menu and confirm the completion.

**Expected behavior**

The extmark (highlighted with the `Search` hl_group) should only include the word "ipsum". After commit 60710622896df79e97048173eabe9752c3bbf7c4, it is extended to the entire line.

**Additional context**

I believe it has something to do with calling `nvim_set_current_line()`, which changes the whole line, so that neovim is no longer able to track changes to the extmarks.

**Comment by hrsh7th** [comment]
I think this issue fixed. Could you re-test this?

**Comment by dcampos** [comment]
The issue is fixed for me too. Thanks a lot!
