### ISSUE TITLE
Cursor in wrong position after inserting `Tabnine` completion items

### ISSUE THREAD

**Issue by mystilleef** [hrsh7th/nvim-cmp#516]
**Describe the bug**

The cursor does not move to the end of some completion item after it is inserted into the buffer. The bug is reproducible with completion items that have closing brackets `)` or parenthesis `}`. This happens mostly with `Tabnine` sources. I attached a video below showing the issue.

Sometimes the cursor will momentarily move to the end of the insertion after completion, but will jump back to its previous position before insertion.

According to this [`cmp-tabnine issue`,](https://github.com/tzachar/cmp-tabnine/issues/15#issue-1051353946) this bug was introduced around 8c08bdf7a4e0f218b233765913ff0669358f4a6e. Reverting to that commit fixes this issue for me.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
let s:plug_path = s:plug_dir . '/plug.vim'
if !filereadable(s:plug_path)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'tzachar/cmp-tabnine', { 'do': './install.sh' }
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  experimental = { native_menu = false, ghost_text = true },
  completion = { completeopt = "menu,menuone,noinsert" },
  confirmation = { default_behavior = cmp.ConfirmBehavior.Replace },
  snippet = {
    expand = function(args)
    vim.fn["vsnip#anonymous"](args.body)
  end,
  },

mapping = {
  ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

sources = {
  { name = "tabnine" },
  { name = "nvim_lsp" },
  { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

**To Reproduce**

This video shows how I reproduce the issue.

https://user-images.githubusercontent.com/273399/141614968-42d527df-ea99-4755-9252-8ed6bd803056.mp4

**Expected behavior**

I expect the cursor to jump to the end of a completion insertion.

**Additional context**

More context is available where I originally reported the issue as a `cmp-tabnine` bug [here](https://github.com/tzachar/cmp-tabnine/issues/15#issue-1051353946).

**Comment by hrsh7th** [comment]
Perhaps cmp-tabnine is returning the invalid items.

Basically, the "completed state" and the "returned item" must be synchronized to the same buffer state.

cmp-tabnine saves the "latest  callback" as a variable at https://github.com/tzachar/cmp-tabnine/blob/main/lua/cmp_tabnine/source.lua#L158 and call it later asynchronously.

If there are consecutive completion requests, it is possible to call the callback with the result of the previous request to tabnine.

_google translated_

**Comment by tzachar** [comment]
@hrsh7th 

It is not a problem with the async behavior of cmp-tabnine.
I successfully bisected the issue to e1f880b7e0ae3cae251fb6c7901bc856fe546e0b which is the first commit where the issue appears.

**Comment by hrsh7th** [comment]
@tzachar Thank you bisected. Could you test with this?

Hm... I should write tests for core.confirm but it uses `feedkeys` so hard to create tests...

**Comment by tzachar** [comment]
mmmm, not working:
`
E5108: Error executing lua ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:420: Expected 2 arguments
stack traceback:                                                                                                                         [C]: in function 'nvim_win_set_cursor'                                                                                           ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:420: in function <...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:377>                                                                                                                    .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:44: in function 'next'                                               ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:374: in function <...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:344>                                                                                                                    .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:44: in function 'next'                                               ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:340: in function <...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:321>                                                                                                                    .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:44: in function <.../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:42>                                                                                                                      ...te/pack/packer/start/nvim-cmp/lua/cmp/utils/feedkeys.lua:51: in function <...te/pack/packer/start/nvim-cmp/lua/cmp/utils/feedkeys.lua:49>                                                                                                   
`

**Comment by tzachar** [comment]
10x :)

This solves the issue
