### ISSUE TITLE
Pasting ('set paste' a.k.a. bracketed paste a.k.a. Ctrl+Shift+V in most terminals) can cause autoindentation

### ISSUE THREAD

**Issue by dmitmel** [hrsh7th/nvim-cmp#518]
**Describe the bug**

See the title

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp' 
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup({})
EOF

set expandtab shiftwidth=4 tabstop=4 softtabstop=4 shiftround
```

**To Reproduce**

1. Create and open a file `test.vim`:
   ```vim
   lua <<EOF
   lspconfig.clangd.setup({

   })
   EOF
   ```
2. Go to the empty line (`3gg`)
3. Copy the following text from the browser by double-clicking to select the entire line (it has 4 spaces at the start):
   ```
       flags = { debounce_text_changes = 150, }
   ```
   UPDATE: Actually, it doesn't matter how it is copied, as long as the whitespace at the beginning is present and reading `@+` (the `+` register) doesn't show a `\n` at the end. In other words, executing this will do just as well:
   ```vim
   call setreg('+', '    flags = { debounce_text_changes = 150, }', 'c')
   ```
4. Paste this text into the buffer with your terminal's paste keybinding (I have tested with xfce4-terminal and kitty, both use Ctrl+Shift+V).

**Expected behavior**

The file should contain:

```vim
lua <<EOF
lspconfig.clangd.setup({
    flags = { debounce_text_changes = 150, }
})
EOF
```

But instead it does:

```vim
lua <<EOF
lspconfig.clangd.setup({
flags = { debounce_text_changes = 150, }
})
EOF
```

**Additional context**

This bug depends on a lot of specific conditions, for example, it doesn't occur in other filetypes such as `lua`, so it is most likely dependent on the indent plugin or ftplugin for `vim`. Embedded Lua block seems to have nothing to do with it, pasting into an empty Vimscript file gives the same result. The impact is also very minimal, I can just add the missing indentation myself. Please consider it very low-priority.

**Comment by hrsh7th** [comment]
Thank you very much.
Recently, I've begun to wonder if it would be harmful to nvim-cmp is invoke auto-indent on its own.

**Comment by hrsh7th** [comment]
Fixed.
