### ISSUE TITLE
`\pi<CR>` returns `πþX` instead of `π`

### ISSUE THREAD

**Issue by kdheepak** [hrsh7th/nvim-cmp#52]
Typing `\pi<CR>` returns `πþX` when it should return `π`. This does not happen with other symbols I tested.

![](https://user-images.githubusercontent.com/1813121/130647832-d94294c4-7b2c-49a5-a4d1-6ec5f3da73c1.gif)

This is with the [`latex_symbols`](https://github.com/kdheepak/cmp-latex-symbols/) source. @hrsh7th I tried to debug this but I wasn't able to figure out what is going on. I'm hoping maybe you might have some insight. You can close this if you think it's definitely not related to `nvim-cmp`. 

Here's the same issue on the other repository: https://github.com/kdheepak/cmp-latex-symbols/issues/2

**Comment by hrsh7th** [comment]
Thank you. This issue is very insightful. I've fixed.

**Comment by kdheepak** [comment]
Wow! Thanks for the quick fix! Works great! And thank you for all your work on this! I think using the LSP completion spec for the autocomplete is a good idea :) It should be very flexible.
