### ISSUE TITLE
<TAB> Does Not Work in Bindings

### ISSUE THREAD

**Issue by p0da** [hrsh7th/nvim-cmp#521]
**Describe the bug**
While using the phrase `<TAB>` works as expected in vim bindings cmp seems to only accept `<Tab>` in its mapping definitions.
Simply put:

```['<Tab>'] = cmp.mapping.confirm()``` 
works as expected while 
```['<TAB>'] = cmp.mapping.confirm()``` 
does not.

**Expected Behavior**
`<TAB>` works.

**Comment by vitaly** [comment]
it's worse than that ;). it works **sometimes**. just spent 2 hours hunting configuration problem where tabs would mostly work, but sometimes they wouldn't. I used `<tab>` and not '<TAB>` but I don't think matters. traced it down to `config.set_global` priducing both `<Tab>`, and `<tab>` keys, but then only one of them would get eventually get into `prepare`

**Comment by p0da** [comment]
@vitaly Looks like github's markdown rendering mangled your message, but that is indeed interesting.

**Comment by hrsh7th** [comment]
I often get reports of this issue, but I can't reproduce it at all.
In my environment, `<C-y>` vs `<c-y>`, `<Tab>` vs `<tab>` vs `<TAB>` are all working fine.

**Comment by hrsh7th** [comment]
Sorry. I can't do anything for this unless someone provides the minimum reproducible configuration.

**Comment by mvllow** [comment]
Without looking at the code, it sounds like a race condition. Perhaps the normalising of `<Tab>` to `<tab>` etc. is done after some other logic. This would explain how the issue is so unpredictable. Personally, using `<tab>` does _not_ work half the time while `<Tab>` consistently works every time.

**Comment by asmodeus812** [comment]
@hrsh7th I am also Facing the same issue, if i do press tab as soon as i see the menu load the options i get weird behaviour. Sometimes the cursor jumps back to the prev word, sometimes somewhere else in the file, if i wait a bit it does then work fine. 

```lua
            ["<Tab>"] = cmp.mapping(function(fallback)
                local status_ok, luasnip = pcall(require, "luasnip")
                if status_ok and luasnip.expand_or_jumpable() then
                    luasnip.expand_or_jump()
                elseif cmp.visible() then
                    cmp.confirm({
                        behavior = cmp.ConfirmBehavior.Replace,
                        select = true
                    })
                else
                    fallback()
                end
            end, { "i", "c", "s" }),
````
