### ISSUE TITLE
`E518: Unknown option: ,0=::` when using with haskell-vim

### ISSUE THREAD

**Issue by cyberfined** [hrsh7th/nvim-cmp#522]
After typing where keyword, neovim throws an error `E518: Unknown option: ,0=::`. After that indentation, syntax highlighting and completion stop working.

Minimal config
```vim
set nocompatible

call plug#begin()
Plug 'hrsh7th/nvim-cmp'
Plug 'neovimhaskell/haskell-vim'
call plug#end()

lua <<EOF
  require'cmp'.setup({})
EOF
```
[![asciicast](https://asciinema.org/a/W9UfFSq9S3xw62iPmryzu1K4M.svg)](https://asciinema.org/a/W9UfFSq9S3xw62iPmryzu1K4M)

haskell-vim defines following indentkeys
```vim
setlocal indentkeys=!^F,o,O,0{,0},0(,0),0[,0],0,,0=where,0=let,0=deriving,0=in\ ,0=::\ ,0=\-\>\ ,0=\=\>\ ,0=\|\ ,=\=\
```

**Comment by afnanenayet** [comment]
I'm getting this even without `haskell-vim` installed

**Comment by hrsh7th** [comment]
Fixed.
