### ISSUE TITLE
[Feature Request] Alternative Cmdline Source Specification Syntax 

### ISSUE THREAD

**Issue by p0da** [hrsh7th/nvim-cmp#523]
Would it be possible to specify the cmdline sources in the same fashion as the mappings are definied. For example the current syntax for a mapping is:
```
mapping={
   [$KEY_TO_MAP]=$ACTION
}
```
similarly the cmdline mappings could be something like:
```
cmdline={
   [$PREFIX]=$SOURCE_TABLE
}
```
Currently everything but the cmdline sources are specified within the table passed to cmp.setup() so this change should allow for that trend to continue.

**Comment by hrsh7th** [comment]
You can use
```
cmp.setup {
  mapping = {
    ['<CR>'] = {
      i = cmp.mapping.confirm({ select = true }),
      c = cmp.mapping.confirm({ select = false }),
    },
    ['<C-n>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 'c' }),
  }
}
```

**Comment by p0da** [comment]
Certainly, I was saying that it would be more intuitive if the cmdline source mappings were changed from this (what they currently are):
```
cmp.setup.cmdline('/', {
    sources = {
      { name = 'buffer' }
    }
  })
```
to this:
```
cmdline={
   ['/']= {
      { name = 'buffer' }
    }
}
```

**Comment by Shougo** [comment]
Hmm..
Above config is shorter but hard to understand.
The source definition is not obvious.

**Comment by hrsh7th** [comment]
In fact, the command line source doesn't inherit from the global source, so I can understand what you want.
But this is a significant change and ** I don't think it's worth it **.
