### ISSUE TITLE
Improve `entry:get_offset` with TextEdit.range

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#524]
Currently, nvim-cmp determines the offset per each entry.
If the entry has a `TextEdit`, nvim-cmp will chose `TextEdit.range.start` as the offset position.

But I think it should be improved like this.

Current line: `import { G| }`
KeywordPattern: `\k\+`
TextEdit: start=`[0, 0]`, end=`[0, 12]`, text=`import { GetServerSideProps } from 'next';`

**Comment by tzachar** [comment]
What is the improvement? What should be the new offset?

**Comment by hrsh7th** [comment]
OLD
```
import { G| }
^
TextEdit.range.start & offset
```

NEW
```
import { G| }
^        ^
|        keyword offset & offset
TextEdit.range.start & offset
```

I'm calling it the `shrinking TextEdit range`.

Some LSP server returns the `fat TextEdit range`.
For example, the above situation does not need to specify the `import {` as the replacement range and we can detect it is not needed.

**Comment by tzachar** [comment]
Is it worth saving some text replacement operations by adding more complexity?
I think you should leave that to the language server. `cmp` is already a very complex plugin (yet AMAZING:)

**Comment by hrsh7th** [comment]
The offset handling is the core value of nvim-cmp for me.

This is the most complicated part of implementing an LSP-related completion engine in vim.
As far as I know, only coc.nvim and nvim-cmp do this properly. I think we should improve usability and strictness.
_google translated_

**Comment by hrsh7th** [comment]
The `entry:get_offset` will be used to determine the completion menu position.

We should choose the entry offset as nearby the keyword offset as much as possible for usability.

**Comment by tzachar** [comment]
If several different entries will have different values returned from `entry:get_offset` would the menu bounce around as you cycle between those entries?

**Comment by hrsh7th** [comment]
No. The menu woudn't bounce. The offset will be leftmost value.
