### ISSUE TITLE
`keyword_length` when reason is manual

### ISSUE THREAD

**Issue by lukas-reineke** [hrsh7th/nvim-cmp#528]
Currently, the code does not check `keyword_length` when completion is triggered manually.
https://github.com/hrsh7th/nvim-cmp/blob/4d800fbcab86e545b65306b0c4c0fde03f2a62b8/lua/cmp/source.lua#L249-L252

I think it should still check.
When I have different `keyword_length` per source, even when I trigger completion manually, I still expect only sources to show that have a lower `keyword_length` than the current word length.

I can make a PR to change it, but I wanted to check first if you agree

**Comment by hrsh7th** [comment]
The keyword_length dosen't affected on manual completion is toooo common behaiviour.


So I can't accept the PR.

But I can accept the PR to allow to specify the `cmp.ContextRrason` in `cmp.complete({ reason = cmp.ConyextReason.Auto })`

**Comment by lukas-reineke** [comment]
That makes sense
I'll make a PR tomorrow
