### ISSUE TITLE
`completeopt` seems to be completely ignored when calling cmp.mapping.complete() with autocomplete disabled

### ISSUE THREAD

**Issue by and3rson** [hrsh7th/nvim-cmp#530]
It seems like `completeopt` settings is completely ignored. I've tried setting `noselect`, `longest`, `menu` etc - the menu still behaves like `menu,menuone,noinsert`.

I've highlighted the lines I've changed with `-- !!!`.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    -- !!!
    ['<Tab>'] = cmp.mapping.complete(),
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },

  -- !!!
  completion = {
    autocomplete = false,
  }
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

-- !!!
require'lspconfig'.gopls.setup {
  capabilities = capabilities,
}
EOF
```

**To Reproduce**

1. Open any `.go` source
2. Type something
3. Hit tab

**Expected behavior**

Completeopt should be respected.

**Comment by gegoune** [comment]
https://github.com/hrsh7th/nvim-cmp#completioncompleteopt-type-string try changing this, see if that helps your case.

**Comment by and3rson** [comment]
@gegoune I've tried various values but they seem to be completely ignored.

**Comment by hrsh7th** [comment]
To be honest, I don't plan to support it. Sorry.

If you want to use `longuest`, you can choose the followings ways.

1. Use other completion engine
2. Use nvim-cmp's native menu (it might be removed in the future but it's available for the time being)

**Comment by Shougo** [comment]
Oh, `longest` option support is hard for auto completion plugin...
