### ISSUE TITLE
`cmp.mapping.complete` does not take context into account

### ISSUE THREAD

**Issue by JRasmusBm** [hrsh7th/nvim-cmp#531]
**Describe the bug**

My assumption was that using `cmp.mapping.complete()` should take the context into account, i.e. when I run the mapping after `cmp.` in this repository it should complete its fields. Instead it behaves as if I were at the beginning of the line. Is there a way to configure this?

![complete](https://user-images.githubusercontent.com/17277051/142068273-a39bc712-467e-46bf-9367-a9ad410f22c4.gif)

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

Did my best, the language server part seems irrelevant, I've reproduced this for multiple servers.

https://github.com/JRasmusBm/reproductions/blob/nvim-cmp-complete/vimrc.vim

(Diff against template here: https://github.com/JRasmusBm/reproductions/commit/4fea1b7922f31cf580203e3aef66f422f09226f4)

**To Reproduce**

1. In this `lua/cmp/init.lua` (of this repository)
2. type cmp.
3. Wait for completion
4. Use cmp.mapping.complete (mapped to <C-Space> in the config above)
5. Wait for completion

**Expected behavior**

The completion in 3. and in 5. should be the same

**Additional context**

None

**Comment by JRasmusBm** [comment]
Nowhere in this form could I add that I am incredibly grateful for all the work you put in for the community! Thank you for amazing plugins! :purple_heart:

**Comment by Shougo** [comment]
Please read this.
https://github.com/hrsh7th/nvim-cmp/issues/528

**Comment by JRasmusBm** [comment]
Thank you! :smile:

Setting

```lua
      ["<C-Space>"] = cmp.mapping(cmp.mapping.complete({
        reason = cmp.ContextReason.Auto,
      }), {"i", "c"}),
```

Worked as a charm! :smile:
