### ISSUE TITLE
expansion does not work correctly when using the cssls

### ISSUE THREAD

**Issue by imSafdarAwan** [hrsh7th/nvim-cmp#532]
in ###HTML

https://user-images.githubusercontent.com/87114084/142166044-a2e8cb62-b55c-4fd4-aeee-2ef16fea6665.mp4

in ### c

https://user-images.githubusercontent.com/87114084/142166519-8f85f3c1-5c77-4297-8738-4e2f8a194219.mp4

**Comment by Shougo** [comment]
Oh, you have ignored the issue template.

**Comment by imSafdarAwan** [comment]
and also

> Oh, you have ignored the issue template.

sorry but the issue i have is only with these two things other things work perfectly so i don't think this is the issue with my config

**Comment by gegoune** [comment]
„I don't think this is the issue with my config” — is exactly what minimal config is for.

**Comment by imSafdarAwan** [comment]
> „I don't think this is the issue with my config” — is exactly what minimal config is for.

Other languages works fine .py. css .js .rs. go nothing is heaving any problem only html path and c is giving error

**Comment by imSafdarAwan** [comment]
> „I don't think this is the issue with my config” — is exactly what minimal config is for.

i think i found the issue 
the issue is with confirm ```		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Replace,
			select = true,
		}),
```

**Comment by imSafdarAwan** [comment]
i found another bug in css if you type something like 
```bo``` and then select first suggestion the bo remains in the place and the first suggestion you selected gets inserted it does not replaces it but if you do the same thing and sect suggestion other that the first one every things works fine i will make a video and show you

**Comment by imSafdarAwan** [comment]
https://user-images.githubusercontent.com/87114084/142187574-a84977a9-c4d9-42bc-b0c7-9e84262c5533.mp4

**Comment by hrsh7th** [comment]
@imSafdarAwan I can't get the result of `bo` -> `background-origin: padding-box;` with cssls.

So I think your language server is different than the server I'm using.

https://user-images.githubusercontent.com/629908/142195727-5b3c0f5e-93aa-4208-9a60-26e36ca335c2.mp4

**Comment by imSafdarAwan** [comment]
> @imSafdarAwan I can't get the result of `bo` -> `background-origin: padding-box;` with cssls.
> 
> So I think your language server is different than the server I'm using.
> 
> https://user-images.githubusercontent.com/629908/142195727-5b3c0f5e-93aa-4208-9a60-26e36ca335c2.mp4
> 
> This screencast explains the `padding-box` does not appear after confirmation.
> 

are you using any lsp installer

**Comment by hrsh7th** [comment]
I'm using the `npm i -g vscode-langservers-extracted`

**Comment by imSafdarAwan** [comment]
> @imSafdarAwan I can't get the result of `bo` -> `background-origin: padding-box;` with cssls.
> 
> So I think your language server is different than the server I'm using.
> 
>  Kapture.2021-11-17.at.20.51.18.mp4 
> This screencast explains the `padding-box` does not appear after confirmation.

FOUND the cause of the error

i accidently added the html hint in the null_ls so in html that was the cause and 
in the css i added the stylint_lsp and the emmet_ls and they were messing with the server so in css that was the problem

**Comment by hrsh7th** [comment]
I don't want to add the all servers problem to the README.md.

I hope the issue reporter create the `minimal reproducible configuration` before sending the issue. (it's already noted in the issue template)
