### ISSUE TITLE
spurious ^F inserted

### ISSUE THREAD

**Issue by symphorien** [hrsh7th/nvim-cmp#534]
**Describe the bug**

when typing `do` in a buffer of type sh, `^F` is inserted.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

exactly the content of utils/vimrc.vim

**To Reproduce**

on current main: 17d57f96cc2356158aa7a6ffa3dd700e83c9c9a1

1. ensure there is no file called configure.sh
2. neovim -u utils/vimrc.vim configure.sh
3. type `ido`

**Expected behavior**

`do` is inserted

**Actual behavior**

`do^F` is inserted

![repro](https://user-images.githubusercontent.com/12595971/142208555-8d4c2ff5-cb36-43eb-9621-e40c5c49fdd3.gif)

**Additional context**

NixOS 21.05, linux x86_64
```
$  neovim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compilé par nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "
/nix/store/054c7y9b3j8g6r9hiv1a7fk0ccl3b19w-neovim-unwrapped-0.5.1/share/nvim
"

Run :checkhealth for more info
```

**Comment by hrsh7th** [comment]
Please update nvim-cmp. The nvim-cmp does not feed `<C-f>` now.
