### ISSUE TITLE
Svelte with vsnip

### ISSUE THREAD

**Issue by shlomocarmeter** [hrsh7th/nvim-cmp#536]
Hey,
while working on svelte files trying to get a javascript snippet,  autocomplete menu didn't list it. (Other svelte snippets show fine).
If I do :set ft=javascript the snippet will show.

How to enable javascript snippets for svelte files?
Thanks.

**Comment by hrsh7th** [comment]
https://github.com/hrsh7th/vim-vsnip#2-setting

You can use `g:vsnip_filetypes`.


BTW, Be careful to submit the issue in the right place.

**Comment by shlomocarmeter** [comment]
Oh didn't pay close attention, sorry.
Thanks for the quick response!
