### ISSUE TITLE
Locality sofrting is affecting cmp.cmdline

### ISSUE THREAD

**Issue by JoseConseco** [hrsh7th/nvim-cmp#539]
**Describe the bug**   
New locality comparator affects  cmp.cmdline sorting, and from my test it can't be disabled for  cmp.cmdline 
I tried to provide separate comparators config to cmp.setup.cmdline() : 
```lua
cmp.setup.cmdline(':', {
  sources = cmp.config.sources( {
    { name = 'cmdline_history' }, --will populate cmp table with  command line history
    { name = 'cmdline' },
    { name = 'buffer' },
}),

comparators = {
   compare.recently_used,
   compare.score, 
   compare.offset,
   compare.order,
}   

})  
```
Without : 
`function(...) return cmp_buffer:compare_locality(...) end, `

But  it wont work. Only disabling locality comparator in main 'cmp.setup' works -  but then it is obviously disabled everywhere. 

**To Reproduce**
1. enable new `function(...) return cmp_buffer:compare_locality(...) end, `

**Expected behavior**
IF locality sorting could be **disabled** for cmdline :
![image](https://user-images.githubusercontent.com/13521338/142252020-09d125a1-54ad-4c62-998a-5792588a38f4.png)

**Actual behavior**
we get suggestions from words in current buffer in cmd line -  cant be disabled 
![image](https://user-images.githubusercontent.com/13521338/142251854-a605f426-b467-48bf-b6e1-e2309b882f48.png)

**Comment by dmitmel** [comment]
```lua
cmp.setup.cmdline(':', {
  -- ...
  sorting = {
    comparators = {
      function(...)
        if vim.api.nvim_get_mode().mode:sub(1, 1) ~= 'c' then
          return cmp_buffer:compare_locality(...)
        end
      end,
      -- ...
    }
  },
  -- ...
})
```

**Comment by hrsh7th** [comment]
Please check your configuration before send the issue.

The key should be `sorting.comparators` not a `comparators`.

**Comment by JoseConseco** [comment]
Thx. It works ok now.  What is the best place to ask questions without submitting new issue?  Closing

**Comment by dmitmel** [comment]
> Thx. It works ok now. What is the best place to ask questions without submitting new issue? Closing

@hrsh7th Can you enable the Discussions tab for this repository?

**Comment by hrsh7th** [comment]
I don't know how to use it effectively, but I enabled it for the time being.
