### ISSUE TITLE
Using tab to indent with check_backspace hangs neovim

### ISSUE THREAD

**Issue by kdheepak** [hrsh7th/nvim-cmp#55]
If I use the following setup, and I use `<Shift-I><Tab>` on any line with text, neovim hangs:

```lua

function T(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

cmp.setup({

  snippet = {
    expand = function(args)
      return require("luasnip").lsp_expand(args.body)
    end,
  },

  completion = {
    completeopt = "menu,menuone,noinsert",
  },

  mapping = {
    ["<C-p>"] = cmp.mapping.select_prev_item(),
    ["<C-n>"] = cmp.mapping.select_next_item(),
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    ["<C-Space>"] = cmp.mapping.complete(),
    ["<C-e>"] = cmp.mapping.close(),
    ["<ESC>"] = cmp.mapping.close(),
    ["<CR>"] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    }),
    ["<Tab>"] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(T("<C-n>"), "n")
      elseif check_backspace() then
        return vim.fn.feedkeys(T("<Tab>"))
      elseif luasnip.expand_or_jumpable() then
        vim.fn.feedkeys(T("<Plug>luasnip-expand-or-jump"), "")
      else
        fallback()
      end
    end,
    ["<S-Tab>"] = function(_, fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(T("<C-p>"), "n")
      elseif luasnip.jumpable(-1) then
        vim.fn.feedkeys(T("<Plug>luasnip-jump-prev"), "")
      else
        fallback()
      end
    end,
  },
  sources = {
    { name = "buffer" },
  },
})
```

If I comment the following lines, then it does not hang:

```lua
      elseif check_backspace() then
        return vim.fn.feedkeys(T("<Tab>"))
```

However, I'm no longer able to use `<Tab>` to indent in insert mode.

**Comment by hrsh7th** [comment]
It is not a nvim-cmp's issue.

You should learn vim's key-mapping.

Your configured is triggered by `<Tab>` but you send `<Tab>` with remapping construction.

You should modify the `return vim.fn.feedkeys(T("<Tab>"))` with `return vim.fn.feedkeys(T("<Tab>"), 'n')`

**Comment by kdheepak** [comment]
Thanks for the quick reply! That solves the hanging issue! 

But it doesn't solve the indent problem. 


https://user-images.githubusercontent.com/1813121/130675995-d352a70f-2463-4300-a6ea-d6c083ed1708.mov



Related to this PR: #38

**Comment by hrsh7th** [comment]
Hm... I don't use `<Tab>` mapping.
I will look,into,it tomorrow

**Comment by kdheepak** [comment]
Thanks! I appreciate it.

**Comment by kdheepak** [comment]
This worked in the past btw. When the configuration used a function callback with args that were `core` and `fallback`. I’ll update this comment with the exact config I used that used to work.

**Comment by uga-rosa** [comment]
Will this work?
https://github.com/hrsh7th/nvim-cmp/issues/21#issuecomment-905365843

**Comment by hrsh7th** [comment]
@kdheepak See the @uga-rosa 's suggestion.

**Comment by kdheepak** [comment]
This doesn't work for me but I guess the original issue is resolved, and we can close this issue. I'll comment on the other issue about the tab key issues that I'm having.
