### ISSUE TITLE
Specific characters gets doubled in macro

### ISSUE THREAD

**Issue by Ruthenz** [hrsh7th/nvim-cmp#551]
**Describe the bug**
When using macro recording I noticed that the 3 characters are always inserted twice instead of once.
Those characters seems to be : "("  ","  "." (open bracket, comma ,dot) 
Those characters also seem to be the ones to stop autocomplete in insert mode.

I also noticed this when using :imap
i  (           * <Cmd>call v:lua.cmp.utils.keymap.set_map(1825135301)<CR>
i  ,           * <Cmd>call v:lua.cmp.utils.keymap.set_map(1825135300)<CR>
i  .           * <Cmd>call v:lua.cmp.utils.keymap.set_map(1825135299)<CR>

which to be honest I don't really know what it does 😅  (I'm a newbie in lua and vim)

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```
call plug#begin('~/.config/nvim/autoload/plugged')

    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-buffer'
    Plug 'hrsh7th/nvim-cmp'

    " Snippets for autocomplete
    Plug 'hrsh7th/cmp-vsnip'
    Plug 'hrsh7th/vim-vsnip'
    Plug 'hrsh7th/vim-vsnip-integ'

call plug#end()

 local cmp = require'cmp'
 
 cmp.setup({
   snippet = {
     expand = function(args)
       vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
       -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
       -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
       -- require'snippy'.expand_snippet(args.body) -- For `snippy` users.
     end,
   },
   mapping = {
     ['<C-d>'] = cmp.mapping.scroll_docs(4),
     ['<C-u>'] = cmp.mapping.scroll_docs(-4),
     ['<Tab>'] = function(fallback)
       if cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert }) then
         cmp.scroll_docs(-10000)
       else
         fallback()
       end
     end,
     ['<S-Tab>'] = function(fallback) 
       if cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert }) then
         cmp.scroll_docs(-10000)
       else
         fallback()
       end
     end,
     ['<C-n>'] = cmp.mapping.complete(),
     ['<C-c>'] = cmp.mapping.close(),
     ['<CR>'] = cmp.mapping.confirm({ select = true }),
   },
   sources = cmp.config.sources({
     { name = 'nvim_lsp' },
     { name = 'vsnip' }, -- For vsnip users.
     -- { name = 'luasnip' }, -- For luasnip users.
     -- { name = 'ultisnips' }, -- For ultisnips users.
     -- { name = 'snippy' }, -- For snippy users.
   }, {
     { name = 'buffer' },
   })
 })

  -- Setup lspconfig.
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

```

If anything else is needed please let me know! 

**To Reproduce**

1. Start a macro (qa for example)
2. Enter insert mode and type those 3 characters
3. Stop recording macro
4. Repeat macro - those characters would all appear double?

**Expected behavior**
Those characters shouldn't be doubled.

**Additional context**
I'm sorry if this some how is only on my machine 🙈

**Comment by hrsh7th** [comment]
Hm... I think we can't support macro correctly...

For example, if press <CR> in macro recording, it will add to the macro register literally.
But sometimes, the <CR> wouldn't insert into the buffer but will expand the currently selected item.

We can't distinct the <CR> is expanding the item or adding new line in executing the macro.

This issue will be discussed in #564 .
