### ISSUE TITLE
Completion items middle of suffix

### ISSUE THREAD

**Issue by danymat** [hrsh7th/nvim-cmp#554]
**Describe the bug**

Hello, this is basically the same bug as described and resolved on nvim-compe here: https://github.com/hrsh7th/nvim-compe/issues/375.

Tell me if you need some details on how to reproduce the bug, but I'm not sure it is necessary because it already has been understood in previous nvim-compe repo.

**Comment by hrsh7th** [comment]
I understand but I want to know your problematic CompletionItem.

Currently, nvim-cmp uses `filterText` if it was provided.

**Comment by danymat** [comment]
![Capture d’écran 2021-11-19 à 09 26 48](https://user-images.githubusercontent.com/5306901/142590249-79c78438-02e7-4f3f-8578-29a3ae5bc97e.png)

It's a text like this, and if I press space when typing text (e.g the second one would be `about ...`) it breaks

**Comment by hrsh7th** [comment]
Yes. It's expected behavior. the `space` isn't contained the keyword pattern. nvim-compe has a bug related to this.
You should type `aboutart` instead of `about art`.

**Comment by danymat** [comment]
Oh okay lol (it was quite convenient), I'm closing the issue now, thanks !
