### ISSUE TITLE
Material Icon Preview [feature]

### ISSUE THREAD

**Issue by Donk3ys** [hrsh7th/nvim-cmp#555]
When viewing the docs / completion for a material icon we get the text output for the icon as seen below.

![Screenshot from 2021-11-19 10-15-42](https://user-images.githubusercontent.com/47178744/142593839-dd794f3c-d2f2-4984-b3f5-11a9fe55b8eb.png)

Is there anyway to include the Icon preview such as Android Studio?

![Screenshot from 2021-11-19 10-47-13](https://user-images.githubusercontent.com/47178744/142594075-6f327e6f-de75-45f7-b66d-cb9afa110a97.png)

**Comment by hrsh7th** [comment]
This is out of the scope of the nvim-cmp.

We use the [lspkind-nvim](https://github.com/onsails/lspkind-nvim) for displaying the icons.
