### ISSUE TITLE
Change sources programmatically

### ISSUE THREAD

**Issue by kamalarieff** [hrsh7th/nvim-cmp#556]
Is there a way to change sources programmatically? What I want to achieve is that when I press `C-k`, I want to see only snippets in the completion menu. But other times, I want to see all of my sources in the completion menu.

What I am asking is is there a function that do something like this:
```
["<C-k>"] = cmp.mapping({
    i = function()
        -- I'm setting up different sources here
        cmp.config.sources({
            { name = "vsnip" },
        })
        cmp.complete()
        -- I'm resetting back to default sources 
        cmp.config.sources({
            { name = "buffer" },
            { name = "vsnip" },
            { name = "nvim_lsp" },
        })
    end,
}),
```

**Comment by hrsh7th** [comment]
Duplicated https://github.com/hrsh7th/nvim-cmp/issues/349
