### ISSUE TITLE
<CR> Inserts first completion suggestion no matter what

### ISSUE THREAD

**Issue by zbirenbaum** [hrsh7th/nvim-cmp#557]
I have tried numerous combinations of  "menu","menuone","noselect", "noinsert" for completeopt, and have preselect=cmp.PreselectMode.None in my setup, but no matter what I cannot seem to get pressing enter to actually make a new line if the completion menu is open. I can tell it is still preselecting, because ghost_text (which I have tried turning on and off, along with native_menu) displays the first result. How on earth do I fix this?

**Comment by zbirenbaum** [comment]
nevermind, I'm dumb, select=true was in my confirm mapping. Posting solution to any other people who didn't check the readme carefully enough.

**Comment by kaihowl** [comment]
@zbirenbaum Thank you for writing this down! I had the same issue and you saved me some time debugging and finding the root cause. :)
