### ISSUE TITLE
New lines are removed when executing macro

### ISSUE THREAD

**Issue by tobiwild** [hrsh7th/nvim-cmp#558]
**Describe the bug**

When mapping `<CR>` to `cmp.confirm()` and recording a macro with `<CR>`'s in it the new lines are not available when executing the macro.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
```

**To Reproduce**

- Start a macro in some register
- Switch to insert mode and type
```
Test

Test
```
- Stop recording
- Execute macro
- Result: `TestTest`

This mapping works:

```
vim.keymap.inoremap {
  '<CR>',
  function()
    if vim.fn.reg_executing() ~= '' then
      return '<CR>'
    end
    if not require('cmp').confirm() then
      return '<CR>'
    end
  end,
  expr = true,
}
```

**Comment by hrsh7th** [comment]
Hm... I can't reproduce this.

**Comment by Ruthenz** [comment]
Actually this also happens to me...

https://user-images.githubusercontent.com/8102419/142859069-6a41b446-e770-4fd8-adc0-edeef040d237.mov

**Comment by hrsh7th** [comment]
Reproduced... Hm...

**Comment by hrsh7th** [comment]
Duplicate #551
