### ISSUE TITLE
Core isn't exposed for the new mapping API

### ISSUE THREAD

**Issue by ram02z** [hrsh7th/nvim-cmp#56]
Hey, I am having trouble converting my cmp config to the new mapping API.

Before the new mapping API, I was able to do the following.

```lua
...
  ["<C-Space>"] = cmp.mapping.mode({ "i" }, function(core, fallback)
    local types = require("cmp.types")
    if fn.pumvisible() == 1 then
      core.reset()
    else
      core.complete(core.get_context({ reason = types.cmp.ContextReason.Manual }))
    end
  end),
...
```

Now fallback is the first argument, so I assumed core would be the second, but I guess its not exposed no longer, because the following code fails.

```lua
...
  ["<C-Space>"] = function(fallback, core)
    local types = require("cmp.types")
    if fn.pumvisible() == 1 then
      core.reset()
    else
      core.complete(core.get_context({ reason = types.cmp.ContextReason.Manual }))
    end
  end,
...
```

**Comment by hrsh7th** [comment]
@ram02z 
You can use `require'cmp'.complete()` `require'cmp.close()` instead.

**Comment by hrsh7th** [comment]
See https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/mapping.lua
