### ISSUE TITLE
Docs-popup issue with SelectBehavior.Select

### ISSUE THREAD

**Issue by jandamm** [hrsh7th/nvim-cmp#560]
**Describe the bug**
When using `cmp.select_next_item { behavior = cmp.SelectBehavior.Select }` the initial docs popup isn't visible.
To show the popup for the first entry the second entry has to be selected and then back to first entry.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require 'cmp'

cmp.setup {
	snippet = {
		expand = function(args)
			vim.fn["vsnip#anonymous"](args.body)
		end,
	},
	completion = { autocomplete = false },
	mapping = {
		['<Tab>'] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_next_item { behavior = cmp.SelectBehavior.Select }
			else
				cmp.complete()
			end
		end, { 'i', 's' }),
	},
	sources = cmp.config.sources {
		{ name = 'nvim_lsp' },
	},
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

**To Reproduce**

1. insert `vim.api.`
2. press `<TAB>` (popup opens)
3. press `<TAB>` again (first entry is selected but no popup)
4. press `<TAB>` again (second entry is selected with popup)
5. press `<Up>`  (first entry is selected with popup)

**Expected behavior**

The popup should show on step `3.`

**Additional context**

When using `cmp.select_next_item()` instead of `cmp.select_next_item { behavior = cmp.SelectBehavior.Select }` it does work as expected.

**Comment by hrsh7th** [comment]
I can't reproduce with your minimal config...

https://user-images.githubusercontent.com/629908/142829684-b72e5e66-160c-4763-9a4a-683d3b4c0cfd.mp4

.

**Comment by jandamm** [comment]
Sorry, it seems this has been a hiccup or an issue with timing.
I had this issue consistently but now it seems to be resolved without changing anything.

Maybe the sumneko lsp was a bit slow.
