### ISSUE TITLE
Question: Is this behavior intended?

### ISSUE THREAD

**Issue by captainko** [hrsh7th/nvim-cmp#562]
First, I'm sorry for ignoring the bug report template.
Before this commit 1c7f73aa4ad2ca1d25ea57ba5ab4e43df85d3479 I could get the completion menu after hitting the trigger character `.`
![image](https://user-images.githubusercontent.com/32269291/142835774-99c5f0cb-073f-470a-aec5-13eba9fd004f.png)

The current behavior:
![image](https://user-images.githubusercontent.com/32269291/142835982-26f35bd0-1cee-43a4-98eb-2b22a6572e0c.png)

**Comment by hrsh7th** [comment]
I can't reproduce.

**Comment by hrsh7th** [comment]
Did you get the correct behaivior now?
