### ISSUE TITLE
Mappings table is case sensitive

### ISSUE THREAD

**Issue by lukas-reineke** [hrsh7th/nvim-cmp#570]
**Describe the bug**
The config table is getting merged with `misc.merge`, which is case-sensitive.
Two keys with different cases are kept as different entries. If you map for example `<c-n>`, both `<c-n>` and the default `<C-n>` are in the `mapping` table.
![Screen Capture_select-area_20211123204857](https://user-images.githubusercontent.com/12900252/143019044-c9351a6c-dfdc-42a7-a3da-b95f1bb56000.png)

But `core.on_keymap` compares the keymaps with `keymap.equals`, which uses `vim.api.nvim_replace_termcodes`. In this case `<c-n>` and `<C-n>` are the same.
So the plugin matches the first entry it finds in the `mapping` table, which is random.

So on every start of Neovim, either the user-defined function or the default is mapped.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
require "cmp".setup {
	mapping = {
		["<c-n>"] = function() print("hello") end,
	}
}
```

**To Reproduce**

1. restart Neovim a couple of times
2. about half of the time the default mapping for `<C-n>` is mapped, the other half `print("hello")` is mapped

**Expected behavior**
The mappings table should not be case-sensitive.
`misc.merge` should probably merge that one using `vim.api.nvim_replace_termcodes`

**Comment by lukas-reineke** [comment]
might be related to #475 :thinking:

**Comment by hrsh7th** [comment]
It's weird.

I already normalized the key sequence. see https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config.lua#L97

**Comment by hrsh7th** [comment]
This problem couldn't be reproduced in my environment and was a headache. It would be great if the cause was known.

_google translated_

**Comment by lukas-reineke** [comment]
I think the problem is here https://github.com/hrsh7th/nvim-cmp/blob/9b5d64d90654618461abeddbb1e07b440d362744/lua/cmp/config.lua#L26
this one is not normalized

**Comment by hrsh7th** [comment]
Ahhhhh, indeed! Why did I overlook this? Thank you very much.
