### ISSUE TITLE
[Question] Scrolling through completion dialogs

### ISSUE THREAD

**Issue by WilliamBehrens** [hrsh7th/nvim-cmp#572]
this is my current config
![scrn-10](https://user-images.githubusercontent.com/35979547/143133148-667eca0c-089b-46fa-9559-793efc49e038.png)

I'd love if I'd be able to set it up so that I can still limit the number of options shown at once but allow me to scroll through options similar to how intelij or vscode handle auto complete.

**Comment by hrsh7th** [comment]
I can't understand. Please clarify.

**Comment by Shougo** [comment]
I think you want to scroll completion window.  It is already implemented.

**Comment by smjonas** [comment]
Maybe `:set pumheight` is what you mean?

**Comment by WilliamBehrens** [comment]
@Shougo yes that is exactly what I mean

**Comment by Shougo** [comment]
It seems cmp.mapping.scroll_docs(number)

**Comment by WilliamBehrens** [comment]
@Shougo where would I put that? in cmp.setup?

**Comment by smjonas** [comment]
@WilliamBehrens please check out the `mapping` part in the example configuration at the top of the readme. There is also a separate section about mappings.

**Comment by WilliamBehrens** [comment]
```lua
        -- ['<A-k>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
        -- ['<A-j>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ['<A-k>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), {'i', 'c'}),
        ['<A-j>'] = cmp.mapping(cmp.mapping.scroll_docs(4), {'i', 'c'}),
 
```
I don't understand, so I swapped the command I'm using and it still doesn't work?

**Comment by smjonas** [comment]
Ok so I am sorry if I misunderstood you. Scroll completion docs simply scrolls the text in the window to the right of the actual items cmp shows (like the documentation for a function when using LSP).

Are you sure this is what you want to achieve?

**Comment by WilliamBehrens** [comment]
no it's not, I'll try and explain better

in both jetbrains visual studio, and, vscode their auto complete shows a limited number of items at a time but allows you to scroll through them to see more options while still displaying a limited amount, I'm wanting to replicate this feature with nvim cmp

**Comment by Shougo** [comment]
Hm... the documentation can be scroll, but completion window cannot be scrolled.

@hrsh7th Why the feature is not implemented?

**Comment by Shougo** [comment]
Ah, OK.
