### ISSUE TITLE
Empty lines added in Insert Mode can't be undone if an autocomplete option was not confirmed

### ISSUE THREAD

**Issue by andrewsng** [hrsh7th/nvim-cmp#577]
**Describe the bug**

In insert mode, I type something so the autocomplete menu pops up, but I do not confirm any autocomplete option.
Still in insert mode, I add a bunch of empty lines after what I just typed, and then exit insert mode. I undo everything, but the
empty lines persist and a line gets duplicated. Here, Neovim lets you quit without warning of unsaved changes. When opening
the file back up, the empty and duplicated lines are gone.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

Given config but with lspconfig and some other plugins removed:

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  sources = {
    { name = "buffer" },
  },
}
EOF
```

**To Reproduce**

1. Open the config file above in Neovim
2. Enter insert mode, then type "s". Some autocomplete options should show up
3. Don't confirm any autocomplete option (just continue typing some gibberish)
3. Still in insert mode, hit Enter many times to add empty lines after what you just typed
4. Exit insert mode
5. Undo until "Already at oldest change"
6. The text you typed should be gone, but the empty lines should remain and a line should be duplicated
7. Quit without writing, and Neovim should not warn you of unwritten changes.

**Expected behavior**

The empty lines should all be undone along with the text.
Expected behavior can be seen when reproducing the steps on the final line of the file, or just typing something where
autocomplete options never show up.

**Additional context**

Here's a video:

https://user-images.githubusercontent.com/54720199/143537108-cdfe0102-66b7-4ffe-ae24-a36de7cbdb22.mp4

**Comment by hrsh7th** [comment]
Duplicate #328
