### ISSUE TITLE
autocomplete for "/dev/stdin" will lock the entire neovim program.

### ISSUE THREAD

**Issue by xubury** [hrsh7th/nvim-cmp#578]
**Describe the bug**
If you select and confirm on `/dev/stdin` in the popup menu, the entire neovim program will be stuck.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-path'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "path" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

**To Reproduce**

1. Type `"/dev/"` and trigger the popup menu
2. Select and press enter on `/dev/stdin` or `/dev/stderr/` etc

**Expected behavior**
The program runs freely and the remaining path gets completed.

**Additional context**
OS: Arch Linux on Windows 10 x86_64
Kernel: 5.4.72-microsoft-standard-WSL2
NVIM v0.5.1

**Comment by hrsh7th** [comment]
I can't reproduce...

https://user-images.githubusercontent.com/629908/143562668-640f18fc-f42c-42e7-bfc3-01fb0bddac19.mp4

**Comment by smjonas** [comment]
I can confirm the issue :+1: It will cause Neovim to hang and you cannot type anymore
(right before the selected text is inserted by cmp).

**Comment by xubury** [comment]
> ```viml
> if has('vim_starting')
>   set encoding=utf-8
> endif
> scriptencoding utf-8
> 
> if &compatible
>   set nocompatible
> endif
> 
> let s:plug_dir = expand('/tmp/plugged/vim-plug')
> if !filereadable(s:plug_dir .. '/plug.vim')
>   execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
> end
> 
> execute 'set runtimepath+=' . s:plug_dir
> call plug#begin(s:plug_dir)
> Plug 'hrsh7th/nvim-cmp'
> Plug 'hrsh7th/cmp-buffer'
> Plug 'hrsh7th/cmp-nvim-lsp'
> Plug 'hrsh7th/vim-vsnip'
> Plug 'neovim/nvim-lspconfig'
> Plug 'hrsh7th/cmp-path'
> call plug#end()
> PlugInstall | quit
> 
> " Setup global configuration. More on configuration below.
> lua << EOF
> local cmp = require "cmp"
> cmp.setup {
>   snippet = {
>     expand = function(args)
>       vim.fn["vsnip#anonymous"](args.body)
>     end,
>   },
> 
>   mapping = {
>     ['<CR>'] = cmp.mapping.confirm({ select = true })
>   },
> 
>   sources = {
>     { name = "nvim_lsp" },
>     { name = "buffer" },
>     { name = "path" },
>   },
> }
> EOF
> 
> lua << EOF
> local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
> 
> require'lspconfig'.cssls.setup {
>   capabilities = capabilities,
> }
> EOF
> ```
I just repduce it on a pure linux system,  it happens when you navigate to the item using arrow key.

**Comment by hrsh7th** [comment]
Could anyone reproduce this with Mac OS X?

Is it required Linux to reproduce?

**Comment by dmitmel** [comment]
I know what's the issue, the Lua code in the previewer opens `/dev/stdin` with libuv, for Nvim it is the stream through which the editor is attached to the TTY, and it is open already (otherwise Vim wouldn't be able to handle the input). I'd fix this by disallowing previews for files from either directories `/dev`, `/proc`, `/sys` and so on, or filesystems `devtmpfs`, `proc`, `sysfs` and so on.

**Comment by hrsh7th** [comment]
Thank you for nfo.
So we should check the fs_stat in cmp-path?

**Comment by dmitmel** [comment]
Oh right right, I forgot that this issue was opened on the main repo. The problem is in cmp-path indeed.
