### ISSUE TITLE
VsCode icons in completion

### ISSUE THREAD

**Issue by pynvimdev** [hrsh7th/nvim-cmp#579]
In neovim i have followed your idea and got the completion icons before the lsp source. But to get a true vscode like completion, different colors in the icons would be needed. Can pls you advise me on how to do so.

**Comment by pynvimdev** [comment]
BTW thanks for your non-stop work on nvim-cmp

**Comment by gegoune** [comment]
That's not currently possible I think.

**Comment by hrsh7th** [comment]
Duplicate https://github.com/hrsh7th/nvim-cmp/issues/327

**Comment by pynvimdev** [comment]
Thanks a lot man you are really quick

**Comment by windwp** [comment]
@gegoune you can try my PR
![nvim_cmp](https://user-images.githubusercontent.com/7578110/143575372-00ec1538-499c-483e-8fe6-1477986fa778.gif)

**Comment by ziulev** [comment]
@windwp 
![image](https://user-images.githubusercontent.com/14956407/143579330-4bb20923-083b-4724-a46b-126c42403b5b.png)
How did you align the icons by left side?

**Comment by ziulev** [comment]
Never mind, found the answer `fields = { 'kind', 'abbr', 'menu' },`
