### ISSUE TITLE
Manually trigger completion menu

### ISSUE THREAD

**Issue by andersevenrud** [hrsh7th/nvim-cmp#58]
I usually prefer manually doing <kbd>C</kbd>-<kbd>Space</kbd> to bring up completion which could be achieved in nvim-compe by setting `autocomplete = false`.

Is there such an option in this plugin ? I can't seem to find it by looking at the docs and the code.

**Comment by hrsh7th** [comment]
I think you can use this.
https://github.com/hrsh7th/nvim-cmp#completionautocomplete-type-cmptriggerevent

**Comment by andersevenrud** [comment]
Oh :man_facepalming: I'm not sure how I missed that... sorry for wasting your time!

**Comment by andersevenrud** [comment]
Just leaving this here if anyone else comes across this.

```lua
{
  completion = {
      autocomplete = { nil }
  }
}
```
