### ISSUE TITLE
Cannot quit vim gracefully after delete all buffers with `:%bd`

### ISSUE THREAD

**Issue by dakennguyen** [hrsh7th/nvim-cmp#582]
**Describe the bug**
The bug is related to `cmp.setup.cmdline(':',...)`
Delete all buffers with `:%bd` and then `:q` create this warning
![image](https://user-images.githubusercontent.com/18320285/143614817-476b70e0-d508-4c6d-b29c-cdb9c06a258e.png)
I have to quit vim with `:q!` instead

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}

cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' },
    { name = 'cmdline' }
  })
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').updat_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

**To Reproduce**
1. Setup this
```lua
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' },
    { name = 'cmdline' }
  })
})
```
2. Open some files
3. Delete all buffers with `:%bd`
4. Quit vim with `:q`

**Expected behavior**
Vim should quit without any warning

**Additional context**

**Comment by dmitmel** [comment]
I think the command causes deletion of the buffer that the float window completion menu uses, and this somehow breaks some code which runs on exit. Not sure.

**Comment by dmitmel** [comment]
Question: is having `cmp.setup.cmdline` required for this bug to occur?

**Comment by dakennguyen** [comment]
> Question: is having `cmp.setup.cmdline` required for this bug to occur?

yes, but only for the `:` syntax, not `/`
