### ISSUE TITLE
Issue while making completion source

### ISSUE THREAD

**Issue by Iamafnan** [hrsh7th/nvim-cmp#585]
Hey, I am trying to make completion source for nvim-cmp like emmet but whenever I test the template which was given in the readme, my plugin doesn't show completion and when I do `CmpStatus` my source shows unknown

Here's the repository of my plugin 
https://github.com/Iamafnan/cmp-emmet

**Comment by hrsh7th** [comment]
I think you don't load `lua/cmp-emmet/init.lua`.

```
:lua rewuire('cmp-emmet')
:CmpStatus
```

**Comment by hrsh7th** [comment]
You can see this https://github.com/hrsh7th/cmp-calc as example repo.

**Comment by Iamafnan** [comment]
Thanks it worked
