### ISSUE TITLE
[question] Documentation window border

### ISSUE THREAD

**Issue by marko-cerovac** [hrsh7th/nvim-cmp#588]
Hi, is there any particular reason why the documentation window border highlight is linked to the floating window group [here](https://github.com/hrsh7th/nvim-cmp/blob/092fb66b6ddb4b12b9b542d105d7af40e4fbd9f2/lua/cmp/config/default.lua#L32).

I noticed that both **NormalFloat** and **FloatBorder** are linked to **NormalFloat**. This makes the default border color link to the text in the window, which can look bad in certain colorschemes, so I was wondering was this intentional or by accident.

**Comment by hrsh7th** [comment]
@marko-cerovac The default border was used as `padding` so I specified the `FloatBorder` as `NormalFloat`. It's intentional.
