### ISSUE TITLE
FR: independent loading of sources

### ISSUE THREAD

**Issue by marcelarie** [hrsh7th/nvim-cmp#595]
I work with Perl at work and the LS it's slow as hell. 
So when I want to trigger for example a snippet, nvim-cmp waits for all the sources to be ready to show the suggestions. That makes it impossible to use any snippet. It will be cool if cmp could return the local/smaller sources first. 

example:
![slow](https://user-images.githubusercontent.com/62728887/144227669-9a6b6071-a49d-43fe-b697-5297581e9663.gif)

And BTW thanks for all the hard work 💪🏽

**Comment by hrsh7th** [comment]
It seems to be regression to me. I will improve it.

**Comment by marcelarie** [comment]
Now it works perfectly, thank you!
