### ISSUE TITLE
Add custom placement for Kind items

### ISSUE THREAD

**Issue by danymat** [hrsh7th/nvim-cmp#596]
Hello, from seeing this post: https://www.reddit.com/r/neovim/comments/r5kwg7/rounded_corners_for_popup_menus/

I really liked the fact that the icons are showed before the text.
I didn't see an option to customize placement of the kind items (something like `start`, `end`), and by default it goes after the `abbr`.

<img width="234" alt="Capture d’écran 2021-12-01 à 14 06 33" src="https://user-images.githubusercontent.com/5306901/144239678-61204137-f3d8-4f62-83c3-08468f86d336.png">

Can you pinpoint me where I can add support to this ? (if you agree of course)

**Comment by gegoune** [comment]
https://github.com/hrsh7th/nvim-cmp#formattingfields-type-cmpitemfield

**Comment by danymat** [comment]
Yes sorry, just saw this few moments before this comment, thank you !
