### ISSUE TITLE
Preview completion in formatting.format

### ISSUE THREAD

**Issue by danymat** [hrsh7th/nvim-cmp#597]
Hello, following #596, I had the idea of: instead having something like `fun()~` in snippet `abbr`, provide the same experience as `ghost_text`, but inside the popup (maybe wrapping with `...`) like:

<img width="546" alt="Capture d’écran 2021-12-01 à 14 42 42" src="https://user-images.githubusercontent.com/5306901/144244932-10c22b5f-32b6-4b9e-ade3-ca6164cca199.png">
 
Do you think this is a good idea ?

For info, this is what I have when `ghost_text` enabled:
<img width="296" alt="Capture d’écran 2021-12-01 à 14 43 18" src="https://user-images.githubusercontent.com/5306901/144245055-26e0c7f4-024b-49f8-9ae6-0bf8629f10a7.png">

**Comment by hrsh7th** [comment]
I can't support it in nvim-cmp. nvim-cmp has the feature but it's depending on the LanguageServer related.

**Comment by hrsh7th** [comment]
```lua
formatting = {
  format = function(entry, vim_item)
    vim_item.menu = entry.completion_item.detail
    return vim_item
  end
}
```

If this doesn't help, I can't support sorry.

**Comment by danymat** [comment]
What about this ?

```
		format = function(entry, vim_item)
            local word = entry:get_insert_text()
            word = vim.lsp.util.parse_snippet(word)
            vim_item.abbr = word
            return vim_item
		end,
```
<img width="391" alt="Capture d’écran 2021-12-01 à 14 55 32" src="https://user-images.githubusercontent.com/5306901/144246878-b7a6f57c-ba4f-416f-9bd2-92a63187e900.png">

**Comment by hrsh7th** [comment]
I can't suppor this customization but it looks good :)
