### ISSUE TITLE
Deletes characters when confirming result

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#610]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+665-g4e352ecc4

### nvim-cmp config

```VIM
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'windwp/nvim-autopairs'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua require('nvim-autopairs').setup()

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}

" Set the cmd to your sumneko_lua language server
require'lspconfig'.sumneko_lua.setup {
  cmd = { 'lua-language-server' }
}
EOF
```

### Description

When confirming the result it deletes some characters produces by nvim-autopairs. I believe this issue is because it doesn't play nice with the autopair-plugin.

https://user-images.githubusercontent.com/5160701/144722205-21d2cca8-92ab-4e56-9876-8e2830c74eb1.mov

### Steps to reproduce

Do the minimal config and start typing require like in the video. Choose one option when inside the quotes, and then finish typing the remaining quote characters. You will see that the menu is still open, so when invoking the confirm with <c-y> it deletes the characters. Since I have confirm mapped to enter in my config, this is pretty annoying.

### Expected behavior

The expected behaviour would be that the quote and closing parenthesis are not deleted.

### Actual behavior

The quote and closing parenthesis are deleted like in the video.

### Additional context

This probably has something to do with the autopairs plugin as the menu is still open when the quote and closing parenthesis are typed.

**Comment by hrsh7th** [comment]
I think it can be fixed.

**Comment by hrsh7th** [comment]
Umm... It's difficult to fix than my thoughts.

**Comment by seblj** [comment]
How is it to close the menu when the quote is pressed? Or will this not be a good solution? Because that should also fix the problem

**Comment by hrsh7th** [comment]
nvim-cmp does not update the menu when the user is selecting any items.
This is important because nvim-cmp is asynchronous completion engine.

`Handle by pressing the quotes` is not a common solution.

I think it's possible to fix it, but it's complicated and difficult.

**Comment by seblj** [comment]
Okay I understand!

**Comment by hrsh7th** [comment]
May be fixed.

**Comment by seblj** [comment]
Yes it seems to fix my problem! Thanks a lot!

**Comment by hrsh7th** [comment]
I'm afraid another side effect 😓

**Comment by seblj** [comment]
Hmm, if it breaks something else, we could revert and see if there is another way to fix it?

**Comment by hrsh7th** [comment]
Yes. If this fix breaks something, I will revert this. Sorry.

**Comment by seblj** [comment]
No problem! Thanks for an awesome plugin😄
