### ISSUE TITLE
The first word after autocomplete gets deleted in C#.

### ISSUE THREAD

**Issue by lifer0se** [hrsh7th/nvim-cmp#611]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0

### nvim-cmp config

```lua
local cmp = require"cmp"

vim.cmd[["let g:vsnip_filetypes.cs = ['c#']"]]
vim.cmd([[imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>']])
vim.cmd([[smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>']])
vim.cmd([[imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>']])
vim.cmd([[smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>']])
vim.cmd([[imap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>']])
vim.cmd([[smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>']])


cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  preselect = cmp.PreselectMode.None,

  mapping = {
    ['<C-Space>'] = cmp.mapping.complete({ select = true }),
    ['<C-e>'] = cmp.mapping.close(),
    ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
    ['<CR>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Insert, select = true }),
    },

  formatting = {
    format = require("lspkind").cmp_format({
      with_text = true,
      menu = ({
        buffer = "",
        nvim_lsp = "曆",
        vsnip = "",
        nvim_lua = "",
      })
    }),
  },

  documentation = {
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  },

  experimental = {
    ghost_text = true,
  },

  sources = cmp.config.sources{
    { name = 'vsnip' },
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'path' },
    { name = 'buffer'},
  }
})
-- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline('/', {
  sources = {
    { name = 'buffer' }
  }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
```

### Description

This has been bugging me for a while and I can't find a way to fix it.

When I use cmp to autocomplete a word, if there's no space between the autocompleted word and the next one and I enter any character, cmp will delete that word. This only happens when the completion comes from the LSP. Completions from buffer text do not replace the word after the autocompleted one.

### Steps to reproduce

1. Open any .cs file and attach to omnisharp lsp.
2. Enter insert mode at the beginning of any word.
3. Start typing and select any autocomplete sourced from the LSP.
4. After the selection is automatically inserted, add any character.

### Expected behavior

Words should not be deleted.

### Actual behavior

The word next to the inserted selection gets deleted.

### Additional context

Not sure this makes much sense, so here's a screencap:

https://user-images.githubusercontent.com/16085280/144723153-385293c6-44ee-4abe-9e34-2be202ff4e33.mp4

**Comment by xuxinx** [comment]
has same issue in Golang

**Comment by hrsh7th** [comment]
@xuxinx Please golang reproduce step. I don't want to install all of language servers... (I don't write csharp).

**Comment by xuxinx** [comment]
# system info
```
    System Software Overview:
      System Version: macOS 12.0.1 (21A559)
      Kernel Version: Darwin 21.1.0
      ...
      
    Hardware Overview:
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Chip: Apple M1 Pro
      ...
```
# Neovim info
installed via Homebrew
```
NVIM v0.7.0-dev+667-g419e0d117
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
```
# minimal.lua
``` lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

require'packer'.startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'neovim/nvim-lspconfig'
    use {
        'hrsh7th/nvim-cmp',
        requires = {
            { 'hrsh7th/cmp-nvim-lsp' },
            { 'hrsh7th/cmp-vsnip' },
            { 'hrsh7th/vim-vsnip' },
        },
        config = function ()
            require'cmp'.setup({
                snippet = {
                    expand = function(args)
                        vim.fn["vsnip#anonymous"](args.body)
                    end
                },
                sources = require'cmp'.config.sources{
                    { name = 'nvim_lsp' },
                    { name = 'vsnip' },
                },
            })
        end
    }
    if packer_bootstrap then
        require('packer').sync()
    end
end)

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

require'lspconfig'.gopls.setup{
    capabilities = capabilities,
}
```

# Steps to reproduce
1. init packs  
`nvim -nu minimal.lua minimal.lua`
```
:PackerClean
:PackerInstall
:PackerCompile
```
2. create example golang file with go module inited   
`nvim -nu minimal.lua main.go`
``` go
package main

import "fmt"

func main() {
	xx.xx
}
```
3.  Enter insert mode at the beginning of `xx.xx`. Then type `fmt.s` and select any autocomplete and complete it
# Expected behavior
Words should not be deleted.
# Actual behavior
the first `xx` disappeared.  

https://user-images.githubusercontent.com/12792855/144745277-83e209b5-e4dd-46db-8ec9-73263a468797.mov

**Comment by hrsh7th** [comment]
@xuxinx This rather indicates that nvim-cmp is working properly.

https://user-images.githubusercontent.com/629908/144746573-be2d72a9-e315-461b-86d8-3fb0e8f8c3fb.mp4

**Comment by lifer0se** [comment]
> @xuxinx This rather indicates that nvim-cmp is working properly.
> 
So why would 'xx' get deleted? Would that be an lsp issue?
Also, how can I get that log to check the output for a C# file?

I can also write down all the steps to create a new C# project so you can give it a try and see what's up.It'd require downloading dotnet and the omnisharp server from lsp-installer. Let me know if you're up for it :)

**Comment by hrsh7th** [comment]
Please the setup instruction :)

**Comment by xuxinx** [comment]
> This rather indicates that nvim-cmp is working properly.

hmm... why it is properly?

Anyway, let's look at a more realistic example:  
```go
package main

import (
	"net/http"
)

func main() {
	http.ListenAndServe(":8080", nil)
}
```
If I want to wrap `http.ListenAndServe(":8080", nil)` with `log.Fatal`, my normal behavior is to move the cursor to the beginning of `http.xxx`, then enter the insert mode and input `log.Fatal`. At this time I will most likely use the cmp function, but unexpectedly, after the completion, the word `http` gets deleted.

**Comment by lifer0se** [comment]
Steps to create a new c# project.
1. Install dotnet. (sudo pacman -S dotnet for arch linux)
2. `mkdir csharp_test && cd csharp_test`
3. `dotnet new mstest`
4. `touch minimal.lua`

minimal.lua:
```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

require'packer'.startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'neovim/nvim-lspconfig'
    use 'williamboman/nvim-lsp-installer'
    use {
        'hrsh7th/nvim-cmp',
        requires = {
            { 'hrsh7th/cmp-nvim-lsp' },
            { 'hrsh7th/cmp-vsnip' },
            { 'hrsh7th/vim-vsnip' },
        },
        config = function ()
            require'cmp'.setup({
                snippet = {
                    expand = function(args)
                        vim.fn["vsnip#anonymous"](args.body)
                    end
                },
                sources = require'cmp'.config.sources{
                    { name = 'nvim_lsp' },
                    { name = 'vsnip' },
                },
            })
        end
    }
    if packer_bootstrap then
        require('packer').sync()
    end
end)

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
  local opts = {
    capabilities = capabilities
  }
  server:setup(opts)
end)
```

5. `nvim -nu minimal.lua minimal.lua`
6. `:PackerClean`
7. `:PackerInstall`
8. `:PackerCompile`
9. `:LspInstall omnisharp`
10. `nvim -nu minimal.lua UnitTest1.cs`
11. Inside `public void TestMethod1()` write: `xx.xx;`
12. Place the cursor on top of the 1st 'x', go into insert mode and type 'Sys'
13. Autocomplete `System` and press '.'

https://user-images.githubusercontent.com/16085280/144747853-235e1e54-76d5-42e1-a03f-b0c08c654fce.mp4

**Comment by lifer0se** [comment]
@xuxinx Exactly the same behavior for C#. I made a post on reddit about this as well. A kind soul replied with a workaround:

```lua
    ['('] = function(fallback)
      cmp.mapping.confirm()
      fallback()
    end,
    ['.'] = function(fallback)
      cmp.mapping.confirm()
      fallback()
    end,
```
This fixes the issue for the characters '(' and '.' which are the main two I use after autocompleting something. I'll keep adding characters as I need them. It's a bit hacky and dirty but it works.

**Comment by xuxinx** [comment]
Not work for me. It seems that our two issues are not the same issue. Yours occurred after pressing `.`, and mine occurred immediately after completion.

**Comment by lifer0se** [comment]
@xuxinx oh that's weird it looked very similar in the screen cap you posted. 

Anyway let's see what @hrsh7th comes up with.

**Comment by hrsh7th** [comment]
> hmm... why it is properly?

Because nvim-cmp just apply the text as instructed by the language server.

Please look at the screencast. The gopls returns `should replace 3characters`.

**Comment by hrsh7th** [comment]
Hm... the `(` and `.` problem seems `commit character` handling related problem.

I'm using mac os so I can't install dotnet with your instruction... @lifer0se

**Comment by hrsh7th** [comment]
Hm... I'd search the omnisharp issues but I can't find the similar problem...

**Comment by hrsh7th** [comment]
I think the `commitCharacter` problem is caused from nvim-cmp.
The `word deletion` problem is caused by language server, I guess.

**Comment by lifer0se** [comment]
Give `brew cask install dotnet-sdk ` a try, see if you can get the test a try.

**Comment by hrsh7th** [comment]
I was able to reproduce it using omnisharp. But again, this seems to be due to omnisharp itself pointing to it, as well as gopls.
_google translated_

**Comment by hrsh7th** [comment]
Uploading Kapture 2021-12-06 at 00.38.40.mp4…

**Comment by lifer0se** [comment]
@hrsh7th so it's an issue with the lsp then? It returns those two extra characters to cmp?

**Comment by hrsh7th** [comment]
The `textEdit` was returned from the LSP server. So if it's a `actual problem`, we should report it to language server's repo.

**Comment by lifer0se** [comment]
Okok will open an issue there. I'm leaving this open, I'll comment here if I get a solution to this.

Thanks for the help :)

**Comment by danielo515** [comment]
Does this happen for other things that are not words? For example quotes and parens (`"`, `)`).
It happens to me and I don't know if it is the same issue or can be reported as a different one

**Comment by Baehn** [comment]
Hello,

I have the same problem with rust-analyzer: words (not "." or "(") following a method completion are deleted. However, this problem does not occur on vscode which also uses rust-analyzer as a lsp. 

Maybe someone can provide me some useful tips on how to debug this issue?

**Comment by mj-hd** [comment]
For golang, I think this is the same problem as https://github.com/hrsh7th/nvim-cmp/issues/706, and  https://github.com/golang/go/issues/40871.

**Comment by emmanueltouzery** [comment]
I'm having the same issue here with the rust LSP now. I understand that the LSP is asking nvim-cmp to overwrite the text, but maybe there could be a cmp option to ignore the request and never delete any text? for instance I'm currently experimenting with this hack in cmp-nvim-lsp, it currently seems to work:

```diff
 ---Resolve LSP CompletionItem.
 ---@param completion_item lsp.CompletionItem
 ---@param callback function
 source.resolve = function(self, completion_item, callback)
+  completion_item.textEdit.range['end'] = completion_item.textEdit.range.start
+
  -- client is stopped.
  if self.client.is_stopped() then
```

I'm not claiming that code is worth shipping, but given that this issue occured at least with the golang, rust and C# LSPs, maybe there could be a setting (disabled by default) in nvim-cmp to allow the user to override the LSP requests?

**Comment by fortime** [comment]
I might have found the cause of the issue with rust-analyzer. If a completionItem/resolve request is required for a completion, the issue occurs. For example, this happens when a completion includes an additional import.

Here is the debug log:
```
[DEBUG][2025-08-07 14:11:21] .../vim/lsp/rpc.lua:277    "rpc.send"  { id = 80, jsonrpc = "2.0", method = "completionItem/resolve", params = { data = { for_ref = false, hash = "mZcA5aycXcQPA+CYMpAuL3IXwI4=", imports = { { full_import_path = "std::collections::VecDeque" } }, position = { position = { character = 23, line = 1 }, textDocument = { uri = "file:///tmp/rustlsp/src/main.rs" } }, version = 24 }, detail = "VecDeque<{unknown}, {unknown}>", documentation = { kind = "markdown", value = 'A double-ended queue implemented with a growable ring buffer.\n\nThe "default" usage of this type as a queue is to use [`push_back`] to add to\nthe queue, and [`pop_front`] to remove from the queue. [`extend`] and [`append`]\npush onto the back in this manner, and iterating over `VecDeque` goes front\nto back.\n\nA `VecDeque` with a known list of items can be initialized from an array:\n\n```rust\nuse std::collections::VecDeque;\n\nlet deq = VecDeque::from([-1, 0, 1]);\n```\n\nSince `VecDeque` is a ring buffer, its elements are not necessarily contiguous\nin memory. If you want to access the elements as a single slice, such as for\nefficient sorting, you can use [`make_contiguous`]. It rotates the `VecDeque`\nso that its elements do not wrap, and returns a mutable slice to the\nnow-contiguous element sequence.\n\n[`push_back`]: VecDeque::push_back\n[`pop_front`]: VecDeque::pop_front\n[`extend`]: VecDeque::extend\n[`append`]: VecDeque::append\n[`make_contiguous`]: VecDeque::make_contiguous' }, filterText = "VecDeque", kind = 22, label = "VecDeque(use std::collections::VecDeque)", sortText = "7ffffffb", textEdit = { newText = "VecDeque", range = { ["end"] = { character = 23, line = 1 }, start = { character = 20, line = 1 } } } } }
[DEBUG][2025-08-07 14:11:21] .../vim/lsp/rpc.lua:391    "rpc.receive"   { id = 80, jsonrpc = "2.0", result = { additionalTextEdits = { { newText = "use std::collections::VecDeque;\n\n", range = { ["end"] = { character = 0, line = 0 }, start = { character = 0, line = 0 } } } }, data = { for_ref = false, hash = "mZcA5aycXcQPA+CYMpAuL3IXwI4=", imports = { { full_import_path = "std::collections::VecDeque" } }, position = { position = { character = 23, line = 1 }, textDocument = { uri = "file:///tmp/rustlsp/src/main.rs" } }, version = 41 }, detail = "VecDeque<{unknown}, {unknown}>", documentation = { kind = "markdown", value = 'A double-ended queue implemented with a growable ring buffer.\n\nThe "default" usage of this type as a queue is to use [`push_back`] to add to\nthe queue, and [`pop_front`] to remove from the queue. [`extend`] and [`append`]\npush onto the back in this manner, and iterating over `VecDeque` goes front\nto back.\n\nA `VecDeque` with a known list of items can be initialized from an array:\n\n```rust\nuse std::collections::VecDeque;\n\nlet deq = VecDeque::from([-1, 0, 1]);\n```\n\nSince `VecDeque` is a ring buffer, its elements are not necessarily contiguous\nin memory. If you want to access the elements as a single slice, such as for\nefficient sorting, you can use [`make_contiguous`]. It rotates the `VecDeque`\nso that its elements do not wrap, and returns a mutable slice to the\nnow-contiguous element sequence.\n\n[`push_back`]: VecDeque::push_back\n[`pop_front`]: VecDeque::pop_front\n[`extend`]: VecDeque::extend\n[`append`]: VecDeque::append\n[`make_contiguous`]: VecDeque::make_contiguous' }, filterText = "VecDeque", kind = 22, label = "VecDeque(use std::collections::VecDeque)", preselect = true, sortText = "7ffffffb", textEdit = { newText = "VecDeque", range = { ["end"] = { character = 28, line = 1 }, start = { character = 20, line = 1 } } } } }
```
The `end` of the `textEdit` is changed from 23 to 28.

It looks like a upstream issue.

**Comment by ranger-ross** [comment]
I am also having the same issue with rust-analyzer. I tried the work around above and it did not work for me. (though there is a high chance of user error. I not a very advanced nvim user...)

Having the ability work around this in same way would be great.
