### ISSUE TITLE
Can't Install nvim-cmp

### ISSUE THREAD

**Issue by super-eye** [hrsh7th/nvim-cmp#612]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.5.1

### nvim-cmp config

lua require 'init'

call plug#begin('~/.local/share/nvim/plugged')
Plug 'hrshth/cmp-nvim-lsp'
Plug 'hrshth/cmp-buffer'
Plug 'hrshth/nvim-cmp'
Plug 'hrshth/cmp-nvim-lua'
Plug 'hrshth/cmp-path'
Plug 'hrshth/cmp-calc'
call plug#end()

### Description

Hi, 

I did a Packersync inside my plugins.lua file to uninstall an autopair plugin. Packer asked me to delete all or all the hrsh7th/* plugins I had in the plugins file. Didn't understood why but I accepted.  I tried installing them again and received the message "Failed to install hrshth/nvim-cmp". Finally I tried  installing them with vim-plug and this message was sent "fatal: could not read Username for 'https://github.com': terminal prompts disabled", these are not the only plugins with this issue. Some install fine and some give this message. I beleive it is a github configuration issue, not a bug (just thought this while writing), so any help would be appreciated. 
![1638673902_dic05_00:11:42](https://user-images.githubusercontent.com/61566133/144731966-73509233-ecbe-484c-9778-da00b87e0f14.png)

### Steps to reproduce

Execute the following commands:

PlugInstall (inside init.vim)
or
PackerSync inside (plugins.lua file)

### Expected behavior

Plugins installed

### Actual behavior

Can't install plugins

**Comment by super-eye** [comment]
I just did used the command: git config --global url."git@github.com:".insteadOf "https://github.com/".
And vim-plug now says:
![1638674624_dic05_00:23:44](https://user-images.githubusercontent.com/61566133/144732183-66db5e33-7523-4398-9297-511080e77931.png)

**Comment by super-eye** [comment]
Hi, just installed it.
I changed ''hrshth" for "hrsh7th".
Finally :).
Did I changed the file, or did the repository changed?

**Comment by Shougo** [comment]
It seems just typo.
`hrsh7th` name is not changed.

**Comment by hrsh7th** [comment]
I didn't change repo name...

**Comment by super-eye** [comment]
Hi, thanks both for replying. I must had changed the repo and didn't noticed at all. The vim-plug message made it look for me more serious than that. :)

**Comment by mdnihal5** [comment]
> Hi, just installed it. I changed ''hrshth" for "hrsh7th". Finally :). Did I changed the file, or did the repository changed?

hey can you help me to install iam getting same error
![Uploading Screenshot from 2024-09-20 06-48-35.png…]()
