### ISSUE TITLE
Calling complete() does nothing in select mode

### ISSUE THREAD

**Issue by Melkster** [hrsh7th/nvim-cmp#617]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+660-gd3585e0ec

### nvim-cmp config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin('~/.config/nvim/packages/')
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require('cmp')

cmp.setup({
  mapping = {
    ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 's' }),
  },

  sources = cmp.config.sources({
    { name = 'buffer' },
  }),
})
EOF
```

### Description

Calling `complete()` does not work in select mode. In insert mode it brings up the completion menu, but in select mode it does nothing.

### Steps to reproduce

1. Open any file with text
2. Press `gh` to enter select mode
3. Press `<C-space>` to trigger `complete()`
4. Nothing happens

### Expected behavior

`complete()` should bring up the completion just like how it works in insert mode

### Actual behavior

Nothing happens in select mode

**Comment by hrsh7th** [comment]
I can't define should it works and I don't want to add it. Sorry.

**Comment by Shougo** [comment]
I don't know why the feature is needed.

**Comment by Melkster** [comment]
@hrsh7th 
> I can't define should it works and I don't want to add it. Sorry.

I'm not entirely sure what you mean, could you elaborate please? :)

@Shougo
> I don't know why the feature is needed.

The reason I think this feature is useful is because when using a snippet and jumping to a placeholder it puts you in select mode. I often want to replace the placeholder with an item from nvim-cmp's completion menu by pressing `<C-space>` which calls `complete()`. However, this is currently not possible.

**Comment by petobens** [comment]
Hi! I think I have a similar use case. As you can see in the GIF if I enter a placeholder directly in insert mode then the completion is triggered but if I first get into select mode and then move into insert mode there is no completion.. Are there any pointers to fix this? Or is it a feature?

![visual_selection](https://github.com/hrsh7th/nvim-cmp/assets/2583971/3405a32c-1cbd-4c0b-900e-f19a92aa95fa)

**Comment by xzbdmw** [comment]
> Hi! I think I have a similar use case. As you can see in the GIF if I enter a placeholder directly in insert mode then the completion is triggered but if I first get into select mode and then move into insert mode there is no completion.. Are there any pointers to fix this? Or is it a feature?
> 
> ![visual_selection](https://private-user-images.githubusercontent.com/2583971/266450830-3405a32c-1cbd-4c0b-900e-f19a92aa95fa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzczNjYsIm5iZiI6MTcwOTA3NzA2NiwicGF0aCI6Ii8yNTgzOTcxLzI2NjQ1MDgzMC0zNDA1YTMyYy0xY2JkLTRjMGItOTAwZS1mMTlhOTJhYTk1ZmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjMzNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2NmUwNTQ1OWU0MTQxZmViMWI0M2Y0NWVmNzkxZTE5N2RiNDE4MzBmYzNhNzcwZTMwMGY2NzU5ZDVmNGM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L59P8eaH7rolCtJJ_5b-i6yUDjmH1wctkXuI9_ZPkho) [ ![visual_selection](https://private-user-images.githubusercontent.com/2583971/266450830-3405a32c-1cbd-4c0b-900e-f19a92aa95fa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzczNjYsIm5iZiI6MTcwOTA3NzA2NiwicGF0aCI6Ii8yNTgzOTcxLzI2NjQ1MDgzMC0zNDA1YTMyYy0xY2JkLTRjMGItOTAwZS1mMTlhOTJhYTk1ZmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjMzNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2NmUwNTQ1OWU0MTQxZmViMWI0M2Y0NWVmNzkxZTE5N2RiNDE4MzBmYzNhNzcwZTMwMGY2NzU5ZDVmNGM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L59P8eaH7rolCtJJ_5b-i6yUDjmH1wctkXuI9_ZPkho) ](https://private-user-images.githubusercontent.com/2583971/266450830-3405a32c-1cbd-4c0b-900e-f19a92aa95fa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzczNjYsIm5iZiI6MTcwOTA3NzA2NiwicGF0aCI6Ii8yNTgzOTcxLzI2NjQ1MDgzMC0zNDA1YTMyYy0xY2JkLTRjMGItOTAwZS1mMTlhOTJhYTk1ZmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjMzNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2NmUwNTQ1OWU0MTQxZmViMWI0M2Y0NWVmNzkxZTE5N2RiNDE4MzBmYzNhNzcwZTMwMGY2NzU5ZDVmNGM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L59P8eaH7rolCtJJ_5b-i6yUDjmH1wctkXuI9_ZPkho) [ ](https://private-user-images.githubusercontent.com/2583971/266450830-3405a32c-1cbd-4c0b-900e-f19a92aa95fa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzczNjYsIm5iZiI6MTcwOTA3NzA2NiwicGF0aCI6Ii8yNTgzOTcxLzI2NjQ1MDgzMC0zNDA1YTMyYy0xY2JkLTRjMGItOTAwZS1mMTlhOTJhYTk1ZmEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMjMzNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2NmUwNTQ1OWU0MTQxZmViMWI0M2Y0NWVmNzkxZTE5N2RiNDE4MzBmYzNhNzcwZTMwMGY2NzU5ZDVmNGM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L59P8eaH7rolCtJJ_5b-i6yUDjmH1wctkXuI9_ZPkho)

Have you found a solution？

**Comment by petobens** [comment]
Unfortunately not yet.

**Comment by Shougo** [comment]
> Hi! I think I have a similar use case. As you can see in the GIF if I enter a placeholder directly in insert mode then the completion is triggered but if I first get into select mode and then move into insert mode there is no completion.. Are there any pointers to fix this? Or is it a feature?

Hm...  You should check what is the keyword pattern.
If you add the space before cursor, completion menu may be displayed.

**Comment by xzbdmw** [comment]
> > Hi! I think I have a similar use case. As you can see in the GIF if I enter a placeholder directly in insert mode then the completion is triggered but if I first get into select mode and then move into insert mode there is no completion.. Are there any pointers to fix this? Or is it a feature?
> 
> Hm... You should check what is the keyword pattern. If you add the space before cursor, completion menu may be displayed.

Hello how to make the first D that switch selection mode into insert mode brings up completion menu? Thanks!

https://github.com/hrsh7th/nvim-cmp/assets/97848247/41f8629d-9aa0-49dd-a6c7-0f526298eb63

**Comment by Shougo** [comment]
It seems the completion is not triggered.  It seems completion event problem.

**Comment by xzbdmw** [comment]
> It seems the completion is not triggered. It seems completion event problem.
> 
> I think `autocmd ModeChanged *:i` works for it.

Thanks! It works
```lua
vim.api.nvim_create_autocmd("ModeChanged", {
    callback = function()
        local old_mode = vim.v.event.old_mode
        local new_mode = vim.v.event.new_mode
        if old_mode == "s" and new_mode == "i" then
            require("cmp").complete()
        end
    end,
})
```

**Comment by petobens** [comment]
Hi @xzbdmw and @Shougo. The workaround didn't work for me since the sequence of mode change events looks as:
```
{
  new_mode = "v",
  old_mode = "n"
}
{
  new_mode = "s",
  old_mode = "v"
}
{
  new_mode = "n",
  old_mode = "s"
}
{
  new_mode = "i",
  old_mode = "n"
}
```
so basically i get `v->s->n->i` instead of simply `s->i`.. any pointers? Thanks in advance

**Comment by Shougo** [comment]
Hm.  So you can check `ModeChanged n:i`.

https://github.com/hrsh7th/nvim-cmp/issues/617#issuecomment-1972459849

It checks mode `s`.
