### ISSUE TITLE
Pressing tab in a typescript file after ${ inserts }

### ISSUE THREAD

**Issue by smjonas** [hrsh7th/nvim-cmp#618]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v.0.6.0

### nvim-cmp config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
}
EOF
```

### Description

This was initially reported on the cmp-nvim-ultisnips repo [here](https://github.com/quangnguyen30192/cmp-nvim-ultisnips/issues/44). We confirmed it's not an UltiSnips issue and the issue also occurs when using cmp without any sources or custom mappings.

### Steps to reproduce

1. :e test.ts
2. Type ${
3. Hit <kbd>Tab</kbd>

### Expected behavior

The default mapping for `<Tab>` is executed (e.g. a tab character is inserted).

### Actual behavior

} is inserted after the opening bracket. Pressing <kbd>Tab</kbd> multiple times inserts further } characters, like this:
```
${|}}}}}...
```
(| is the cursor position)

### Additional context

This seems to occur only in typescript files. Enabling / disabling the tsserver LSP server has no effect on this bug. Setting a different snippet engine in the cmp config also doesn't effect it.

**Comment by hrsh7th** [comment]
Of course, can't reproduce.

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/144999198-5e6efb63-c848-4ddc-bd2b-1e7f17b725c1.mp4

**Comment by smjonas** [comment]
No worries! I noticed there were several issues that you could not reproduce. Maybe these issues only occur on Linux and not on MacOS (I read somewhere that you are using MacOS).

**Comment by hrsh7th** [comment]
I believe it isn't nvim-cmp's problem. I think it caused by `vim-snippets` maybe.

**Comment by hrsh7th** [comment]
I'm guessing you're using packer.nvim. Packages installed with packer.nvim will be loaded even if you remove the description in packer.nvim. Do you understand this?

_google translated_

**Comment by smjonas** [comment]
Yes I am using packer. I will manually delete the other packages in my packer directory and check it again. I thought starting nvim with `-nu` would not load other packages.

**Comment by smjonas** [comment]
Closing as I could not reproduce it anymore after deleting my other packages from the packer directory, then starting nvim with the minimal config.
