### ISSUE TITLE
Cmp does not call always the server

### ISSUE THREAD

**Issue by pedro757** [hrsh7th/nvim-cmp#619]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.7.0-dev+677-g523f03b50

### nvim-cmp config

```lua
cmp.setup{
  snippet = {
    expand = function(args)
      require'luasnip'.lsp_expand(args.body)
    end
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
  },
}
```

### Description

My [emmet language server](https://github.com/pedro757/emmet) is not called always **e.g.**

![image](https://user-images.githubusercontent.com/30637426/144945513-823d4dc4-55ea-4e3c-8b86-bccfbe5dbe8d.png)

But if I keep typing the server won't be called anytime

![image](https://user-images.githubusercontent.com/30637426/144945623-0ac7a11b-d785-4d4b-9c3e-67007da7b48e.png)

If I call the `cmp.complete()` function by my own, it works

![image](https://user-images.githubusercontent.com/30637426/144945724-8c57d4bf-40d1-4bfc-ac97-9c86eea1f10b.png)

### Steps to reproduce

You can try installing my [emmet server](https://github.com/pedro757/emmet) and using the snippets in a `html` file

### Expected behavior

The plugin should call the server every time I type a new character

![image](https://user-images.githubusercontent.com/30637426/144946613-8f117e74-7c7d-445c-873c-f42eff558458.png)
![image](https://user-images.githubusercontent.com/30637426/144946633-c8d16214-05f5-451b-9086-e00316311017.png)
![image](https://user-images.githubusercontent.com/30637426/144946646-e88296c6-b869-4566-8fd4-6f77320bedd0.png)

**Comment by pedro757** [comment]
I've been debugging that's why I say my server is not called after the first character

![image](https://user-images.githubusercontent.com/30637426/144949330-9e1c3dfb-70f9-473f-acce-dbef3b2d0d81.png)
![image](https://user-images.githubusercontent.com/30637426/144949357-b9f6add8-4379-4b1f-afc1-1974a9bf64c5.png)
![image](https://user-images.githubusercontent.com/30637426/144949376-b60103e6-ceec-4b52-b87c-c218c7926b0b.png)

**Comment by hrsh7th** [comment]
It's server's problem.
