### ISSUE TITLE
Question: Why doesn't nvim-cmp show me the documentation as shown in the video

### ISSUE THREAD

**Issue by raiyuza** [hrsh7th/nvim-cmp#625]
Hi, I am having trouble replicating the exact results as shown in the intro video of this repo.

When i try to vim.cmd it shows me the following
```
vim.cmd                                                                                                                                                                                     
    cmd Function    function #< Here is where i expected the documentation to show up, but it doesn't      
```
Example with vim.api

``` 
vim.api.nvim_buf_get_offset   
    nvim_buf_get_offset          Function            
```

Without this functionality. COC or (Yuck) YouCompleteMe is a better replacement then this plugin. 

Surely it's something i am doing wrong, or is it a configuration fault?

It always says function where i normally see in the video's about nvim-lsp + nvim-cmp where the documentation for that function is shown. 

I have been struggling with this for a couple hours now, might as well try asking here. Sorry for taking your time with probably a easy stupid answer.

Thanks in advance ~Raiy

**Comment by hrsh7th** [comment]
First, You can use coc.nvim or YouCompleteMe...

I think it's impossible because nvim-cmp just shows the language server response.

<img width="707" alt="スクリーンショット 2021-12-08 22 03 16" src="https://user-images.githubusercontent.com/629908/145213065-9a659ab1-fd86-4b1f-bd00-21fc4104d821.png">
