### ISSUE TITLE
Documentation request: Clarifying where the `cmp` plugin fits in the fast evolving ecosystem

### ISSUE THREAD

**Issue by EdmundsEcho** [hrsh7th/nvim-cmp#626]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

:version NVIM v0.7.0-dev+653-g7229afcd6 Build type: Release LuaJIT 2.1.0-beta3 Compiled by edmund@Edmunds-MacBook-Pro.local

### nvim-cmp config

NA

### Description

Updating plugins involves
1. adding new plugins
2. integrating the use of the new with the old
3. identifying which plugins no-longer "work-together"
4. removing plugins that are "now" redundant given the new additions

It's none-trivial and something that is done in a major way only once a year.  This means, important details that we once knew, that we did our best to document, get lost and provide a source of confusion while applying "what I once knew" with how things have evolved.

### Steps to reproduce

NA

### Expected behavior

Documentation that not only describes the feature set, but also explicitly, at minimum, "hints" at what plugins it aims to replace.  This needs to be articulated with care because we all appreciate the efforts that have gone into the competing and prior efforts.  For instance, the wording might go something like "in the event you decide to use this plugin, here is a list of popular plugins that serve the same purpose".  Or, create a table that just shows the key features alongside other plugins that do the same.  This way, it's just a fact-base (and potential norm for presenting a new plugin).

e.g.,  
* for the built-in lsp-client:  a substitute for `coc`, ...
* for the `cmp` is a replacement to `nvim-completion`, `nvim-cmpe`, and ...

### Actual behavior

There are articles and documentation that refer to `cmp` without describing which plugins I can consider removing from my configuration.  It would be great to have a section that describes how to "trim-away" at the list of plugins required to get the functionality `cmp` provides.  e.g., I still have `Plug 'Shougo/context_filetype.vim`. 

Some configurations include mapping the `omnifunc` capability to the built-in `lsp` feature.  `deoplete` and others did not work with `omnifunc`; we were told to avoid using `omnifunc`.  I kept that in mind when I moved to `coc`; in other words, I made an inference to fill the information void.  I suspect that with the built-in lsp, using `omnifunc` may work.  The void remains as it did with `coc` but also, has me wonder if I can't just use the built-in keybindings that come with `omnifunc` instead of what is included in the `cmp` recommended config. I'm basing this on vague recollections of a prior deep-dive with `deoplete`.

This is relevant here because there is clearly overlapping features, if not completely "one-in the same".  
   

### Additional context

It takes a lot of time to make these changes.  To the degree the docs can help me consider which plugins to now deprecate, that would be truly helpful.

I would be willing to set-up a live online meeting with anyone that is familiar with the plugins that have provided the `cmp` functionality over the years.  I would convert the verbal articulation of the answers to the docs.  I suggest a live conference because it may be easier to relay the information in a less formal medium including enabling fast iteration by way of a follow-up question in the moment.

If interested, perhaps vote with a thumbs up +/- comments.  I would then post a time and link to meet.

\- E

**Comment by uga-rosa** [comment]
`cmd`? typo of `cmp`?
At any rate, I don't think the author can hold a meeting in English...

**Comment by EdmundsEcho** [comment]
@uga-rosa Thank you for catching the typo.  I updated the post.

re English-speaking: the participants could be anyone with a good familiarity with the plugins.

**Comment by Shougo** [comment]
If the documentation is needed to update, you can do it.
It is open source project.

**Comment by hashue** [comment]
Why not  write on Wiki ?

**Comment by hrsh7th** [comment]
Thank you for your interest in this plugin.
Basically, I enjoy developing this plugin, but I'm not trying to make it "easy to use by anyone".
For me, it's a higher priority to provide a lot of ways that users who understand this plugin can customize it.

Of course, wiki maintenance is welcome.

_google translated_
