### ISSUE TITLE
Function parameter prompt

### ISSUE THREAD

**Issue by h1zzz** [hrsh7th/nvim-cmp#629]
Hi, What should I do to make a prompt appear when the cursor is in parentheses?

Use coc.nvim
<img width="538" alt="CleanShot 2021-12-09-18-34-03@2x" src="https://user-images.githubusercontent.com/24761228/145380931-2eb0e707-7729-4f3d-8ee6-37a7f1aba4c2.png">
Use nvim-cmp
<img width="309" alt="CleanShot 2021-12-09-18-34-18@2x" src="https://user-images.githubusercontent.com/24761228/145380946-bcced1ab-6cc5-473f-999b-deb0437e93e8.png">

**Comment by gegoune** [comment]
This is not supported and out of scope for this plugin which was stated by @hrsh7th numerous times. Closest you can get is to use one of those:
* https://github.com/hrsh7th/cmp-nvim-lsp-signature-help
* https://github.com/ray-x/lsp_signature.nvim

**Comment by h1zzz** [comment]
> This is not supported and out of scope for this plugin which was stated by @hrsh7th numerous times. Closest you can get is to use one of those:
> 
> * https://github.com/hrsh7th/cmp-nvim-lsp-signature-help
> * https://github.com/ray-x/lsp_signature.nvim

ok, thanks

**Comment by h1zzz** [comment]
l
