### ISSUE TITLE
`cmp.close` does not go back to the originally typed text compared to `compe#close`

### ISSUE THREAD

**Issue by dhruvmanila** [hrsh7th/nvim-cmp#63]
In `nvim-compe`, `compe#close` would close the completion menu and go back to the originally typed text:

[![asciicast](https://asciinema.org/a/a7XtChPhe4VUfM0DUvLTfvqFO.svg)](https://asciinema.org/a/a7XtChPhe4VUfM0DUvLTfvqFO)

But, in `nvim-cmp` it _only_ closes the completion menu:

[![asciicast](https://asciinema.org/a/8ZIcJOo0Hx7seKckZV4Yza5ur.svg)](https://asciinema.org/a/8ZIcJOo0Hx7seKckZV4Yza5ur)

**Comment by dhruvmanila** [comment]
This is the workaround I'm using for now which is taken from `compe#close`:
```lua
vim.api.nvim_feedkeys(escape '<C-e><C-r>=luaeval(\'require("cmp.core").reset() or ""\')<CR>', "n", true)
```

**Comment by hrsh7th** [comment]
I will add the `cmp.mapping.abort` new mapping function.

**Comment by hrsh7th** [comment]
done https://github.com/hrsh7th/nvim-cmp/commit/79601cb3dbadedbace38ca742b99735a7941e262
