### ISSUE TITLE
Language specific setup

### ISSUE THREAD

**Issue by Melkster** [hrsh7th/nvim-cmp#630]
I want to use `cmp_tabnine` as a source in only specific filetypes, along with my regular nvim-cmp setup. This is my current solution.

```lua
require('cmp').setup({
  ...
})

cmd [[autocmd FileType markdown,text,tex,gitcommit
\ lua require('cmp').setup.buffer {
\   sources = {{ name = 'cmp_tabnine' }},
\ }
]]
```

What I noticed however is that this overrides my original setup in those filetypes, and so I would have to duplicate it and add the whole config again inside the `autocmd`. Is there a nicer way to add language specific configurations?

**Comment by hrsh7th** [comment]
```lua
local vimrc = {}

vimrc.utils = {}
vimrc.utils.concat = function(tbl1, tbl2)
  local tbl3 = {}
  for _, item in ipairs(tbl1) do
    table.insert(tbl3, item)
  end
  for _, item in ipairs(tbl2) do
    table.insert(tbl3, item)
  end
  return tbl3
end

vimrc.cmp = {}
vimrc.cmp.sources = {
  { name = 'nvim_lsp' },
  ...
}

local cmp = require('cmp')
cmp.setup {
  sources = vimrc.cmp.sources
}

vim.cmd([[
  autocmd FileType markdown,text,tex,gitcommit lua require('cmp').setup.buffer {
  \   sources = vimrc.utils.concat(vimrc.cmp.sources, { name = 'cmp_tabnine' }),
  \ }
]])
```

just write Lua.

**Comment by Melkster** [comment]
Ok thank you for your answer. So there's no plan for adding a `filetypes` field to the tables provided to `sources`? For example:

```lua
cmp.setup({
  ...
  sources = cmp.config.sources({
    ...
    {
      name = 'cmp_tabnine',
      filetypes = { 'markdown', 'text', 'tex', 'gitcommit' }
    }
  })
})
```

**Comment by hrsh7th** [comment]
Yes. I don't want to add it. sorry.
It seems that there are users with many different opinions :)

https://github.com/hrsh7th/nvim-compe/issues/174

**Comment by Melkster** [comment]
Ok, I see :)
