### ISSUE TITLE
Feature:  optional auto completion

### ISSUE THREAD

**Issue by Iamafnan** [hrsh7th/nvim-cmp#635]
Can we have vscode auto completion settings like this for nvim-cmp? 
```json
"editor.quickSuggestions" : [
   "other": true,
   "comments" : false,
   "strings" : false
]
```

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-compe/issues/120#issuecomment-772108521

Well, it needs source code parse.

**Comment by hrsh7th** [comment]
Related https://github.com/hrsh7th/nvim-cmp/issues/632
