### ISSUE TITLE
`cmp.mapping.confirm()` not working in nvim 0.7.0

### ISSUE THREAD

**Issue by bandithedoge** [hrsh7th/nvim-cmp#638]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev

### nvim-cmp config

```lua
local cmp = require "cmp"
cmp.setup {
    snippet = {
        expand = function(args)
            require("luasnip").lsp_expand(args.body)
        end,
    },
    mapping = {
        ["<C-Space>"] = cmp.mapping.complete(),
        ["<C-CR>"] = cmp.mapping.confirm { select = true },
        ["<C-j>"] = cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Select },
        ["<C-k>"] = cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Select },
        ["<C-h>"] = cmp.mapping.scroll_docs(-4),
        ["<C-l>"] = cmp.mapping.scroll_docs(4),
    },
    sources = {
        { name = "nvim_lsp" },
    },
}
```

### Description

Any `cmp.mapping.confirm()` binding does not work on Neovim 0.7.0. I've tested iTerm2 and Kitty on both macOS and Linux.

### Steps to reproduce

Map any key to `cmp.mapping.confirm()` in `cmp.setup`

### Expected behavior

The selected menu entry gets inserted

### Actual behavior

Menu closes and the keybinding is ignored.

**Comment by hrsh7th** [comment]
I think CUI vim does not support  `<C-CR>`

**Comment by bandithedoge** [comment]
It most certainly does. I've used it in older versions of nvim.

**Comment by hrsh7th** [comment]
Did you test with `<CR>`? I don't change key mapping related inplementation. If you think nvim-cmp is reason of this provlem, please bisect the commit.
