### ISSUE TITLE
cmp-tabnine suggestions stopped appearing

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-cmp#64]
Hi.

For some reason, `cmp-tabnine` suggestions stopped appearing, even though the source does call the callback supplied to `complete` (although asynchronously, *after* `complete` was invoked).

Any idea?

**Comment by hrsh7th** [comment]
I'm getting completion with removing this line.
https://github.com/tzachar/cmp-tabnine/blob/main/lua/cmp_tabnine/source.lua#L166

**Comment by tzachar** [comment]
Ok 10x.

This is pretty much copied over from compe_tabnine...

**Comment by tzachar** [comment]
Ok, it does work better now.
