### ISSUE TITLE
Compeltion is not correct when I type endif.

### ISSUE THREAD

**Issue by lu5je0** [hrsh7th/nvim-cmp#640]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0

### nvim-cmp config

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

set autoindent
set sw=4
set completeopt=menu,menuone,noselect

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

### Description

Compeltion is not correct when I type endif.

https://user-images.githubusercontent.com/17700877/145723451-95a8c27c-2a43-44d9-b6c8-332332b81c16.mp4

### Steps to reproduce

type en and choice endif then type <c-y>.

### Expected behavior

Compeltion text is endif.

### Actual behavior

Compeltion text is endiendif.

**Comment by hrsh7th** [comment]
It's easy to simply disable autoindent, but it seems difficult to run autoindent properly after accepting completions.

_google translated_

**Comment by lu5je0** [comment]
Thank you, it works.

**Comment by lu5je0** [comment]
There is a hacky way to indent properly for anyone who has same issue, https://github.com/lu5je0/.dotfiles/blob/182b19d118891ffee524d3dba614e3c506b1246b/vim/lua/core/cmp.lua#L11
