### ISSUE TITLE
[Question] How to customize the width of custome floating window

### ISSUE THREAD

**Issue by wkcosmology** [hrsh7th/nvim-cmp#643]
How to set the maximum width of the completion window when `experimental.native_menu` is set to `false`?

**Comment by hrsh7th** [comment]
The nvim-cmp provides `formatting.format` option. You can customize menu appearance with this.

I recommend to use `https://github.com/onsails/lspkind-nvim`.

**Comment by wkcosmology** [comment]
Problem solved! Thanks!
