### ISSUE TITLE
not work with vim-visual-multi

### ISSUE THREAD

**Issue by tkkcc** [hrsh7th/nvim-cmp#644]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.6.0

### Minimal reproducible config

```lua
require('packer').startup(function()
  use { 'wbthomason/packer.nvim' }
  use {
    'mg979/vim-visual-multi',
    config = function()
      vim.g.VM_maps = {
        ["Add Cursor Down"] = '<c-j>',
        ["Add Cursor Up"] = '<c-k>',
      }
    end,
  }
  use {
    'hrsh7th/nvim-cmp',
    requires = {
      'hrsh7th/cmp-buffer',
      'dcampos/nvim-snippy',
    },
    config = function()
      vim.o.completeopt = "menu,menuone,noselect"
      local snippy = require("snippy")
      local cmp = require 'cmp'
      local has_words_before = function()
        local line, col = unpack(vim.api.nvim_win_get_cursor(0))
        return col ~= 0 and
                 vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col,
                                                                            col)
                   :match("%s") == nil
      end
      cmp.setup({
        snippet = {
          expand = function(args)
            require'snippy'.expand_snippet(args.body) -- For `snippy` users.
          end,
        },
        mapping = {
          ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
              cmp.select_next_item()
            elseif snippy.can_expand_or_advance() then
              snippy.expand_or_advance()
            elseif has_words_before() then
              cmp.complete()
            else
              fallback()
            end
          end, {"i", "s"}),
        },
        sources = cmp.config.sources({{name = 'buffer'}}),
      })
    end,
  }
end)
```

### Description

After enter multi cursor mode of vim-visual-multi, Tab completion can not go down in completion list.
This issue also appears after expanding snippets with multi occurrence, for example `print('$1',$1)`.

### Steps to reproduce

![Peek 2021-12-13 22-04](https://user-images.githubusercontent.com/17373509/145827100-22ec8c18-303c-440f-838e-147a6421b943.gif)

### Expected behavior

cmp works with "multi cursor"

### Actual behavior

cmp can not work with "multi cursor"

**Comment by hrsh7th** [comment]
I don't familiar with vim-visual-multi.
Please reproducible key sequence.

**Comment by hrsh7th** [comment]
I can't reproduce with the key sequence that displayed in your screencast.

**Comment by cj** [comment]
@tkkcc I am having the same issue, did you ever find a fix?

**Comment by tkkcc** [comment]
@cj nope. i just type more. (；′⌒`)

**Comment by sokinpui** [comment]
in 2023, I have the same problem, I find it like suddenly happen, I used to be don't have such problem
