### ISSUE TITLE
Q: I  don't want to complete function arguments. How do I disable it?

### ISSUE THREAD

**Issue by cathaysia** [hrsh7th/nvim-cmp#645]
As you see:

![图片](https://user-images.githubusercontent.com/42114817/145848125-757e2a38-e3c2-44f0-a744-d09139b36ef0.png)

When complete a function, it will complete function arguments too. How do I disable this?

**Comment by dmitmel** [comment]
This depends on which language server you are using. This is C++, right? Also I assume you are using nvim-lspconfig and ccls. Here's how you can prevent ccls from returning snippets with argument placeholders when completing function calls:

```lua
lspconfig['ccls'].setup({
  -- ...
  init_options = {
    -- ...
    completion = {
      placeholder = false,
    },
  },
})
```

Read more here: https://github.com/MaskRay/ccls/wiki/Customization#clientsnippetsupport

**Comment by hrsh7th** [comment]
@dmitmel is correct. Thank you.

**Comment by cathaysia** [comment]
Thank you very much
