### ISSUE TITLE
Tsserver now provides snippet completion, does this unblock arg ghost-test in completions?

### ISSUE THREAD

**Issue by burgessa23** [hrsh7th/nvim-cmp#646]
According to neovim/nvim-lspconfig#1259 tsserver supports snippet completion now. Does this mean that ghost-text for args can now work?  Is there something that needs to be set in capabilities to get it working?

Apologies if I'm misunderstanding the issue.

Previously closed issue for reference:

The ghost text content is determined by the LSP server (or custom source).

For example, gopls will show the function arguments as ghost text. So it is depending on the your server. I can't support it in nvim-cmp. Sorry.

<img width="1413" alt="スクリーンショット 2021-11-10 3 59 52" src="https://user-images.githubusercontent.com/629908/140987423-128824fe-87a2-494a-88c1-8223e74e7137.png">

_Originally posted by @hrsh7th in https://github.com/hrsh7th/nvim-cmp/issues/503#issuecomment-964444450_

**Comment by dmitmel** [comment]
Looking at the linked pull request to the TS repository (https://github.com/microsoft/TypeScript/pull/43149), I'm inclined to believe that there has been a misunderstanding here. TSServer currently implements snippet completions only for autoimports, and not for filling out function call parameters. Here's the closest I could find to a "tracking issue" for support of snippets in TSServer: https://github.com/microsoft/TypeScript/issues/25207, and it says that "method completions are currently implemented by VSCode manually" (a look into the built-in VSCode extension for Typescript confirms that: [1](https://github.com/microsoft/vscode/blob/1.63.0/extensions/typescript-language-features/src/languageFeatures/completions.ts#L89), [2](https://github.com/microsoft/vscode/blob/1.63.0/extensions/typescript-language-features/src/languageFeatures/completions.ts#L224-L237), [3](https://github.com/microsoft/vscode/blob/1.63.0/extensions/typescript-language-features/src/utils/snippetForFunctionCall.ts)). So yeah, typescript-language-server does, in fact, support snippets in completion, just not the kind of snippets you were hoping for.

**Comment by gegoune** [comment]
@dmitmel Please ignore my ignorance, JS is a complicated ecosystem. I have seen this [release](https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.8.0) a while ago and tried to set it up with no success. I am referring to second item on the list:

> feat: add support for snippet completions for methods/functions (#303)

**Comment by dmitmel** [comment]
Oh, I think I have found the issue. The PR you mentioned, https://github.com/typescript-language-server/typescript-language-server/pull/303, does implement this functionality, and typescript-language-server does return snippets for function calls if you set the setting `completions.completeFunctionCalls`, but it does so in the `completionItem/resolve` method, and not with the initial batch of completions requested in `textDocument/completion`. cc @hrsh7th: nvim-cmp should respond to updates of `insertText` in `completionItem/resolve`.

**Comment by burgessa23** [comment]
Thanks @dmitmel

**Comment by hrsh7th** [comment]
Hm... The LSP spec seems to define the resolvable properties in capabilities.

OK. I'll add it.
