### ISSUE TITLE
Feature: configure sources for auto and manual completions

### ISSUE THREAD

**Issue by sQVe** [hrsh7th/nvim-cmp#648]
Hey 👋,

I've mapped `cmp.complete({ reason = cmp.ContextReason.Auto })` on <kbd>Ctrl+Space</kbd> to open the completion menu, without overruling the settings set via `sources`.

This makes it behave great when I'm completing some word but I'm missing being able to get information from only `nvim_lsp` when triggering complete on emptty lines.

I'd love being able to change `sources` and their settings specifically for manual and auto completions.

**Comment by hrsh7th** [comment]
I can't understand sorry...

Isn't it enough? https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L190

**Comment by sQVe** [comment]
I want to use `cmp.ContextReason.Auto` together with all the `sources` I've configured in `setup`. It doesn't work when trying to trigger completion on a empty line though.

I've tried:

```lua
{
  reason = cmp.ContextReason.Auto,
  sources = config.sources({
    {
      name = 'nvim_lsp',
      keyword_length = 0,
      priority = 80,
    },
  }),
}
```

**Comment by hrsh7th** [comment]
Do you try the `cmp.ContextReason.Manual`?

**Comment by sQVe** [comment]
Yes, but the problem then is that it removes the set `priority`.

**Comment by sQVe** [comment]
So if you give `complete` this:

```lua
{
  reason = cmp.ContextReason.Manual,
  sources = config.sources({
    {
      name = 'nvim_lsp',
      keyword_length = 0,
      priority = 80,
    },
    {
      name = 'buffer',
      keyword_length = 4,
      option = {
        get_bufnrs = get_all_buffers,
        keyword_pattern = anyWord,
      },
      priority = 20,
    },
  }),
}
```
It will not respect the set `keyword_length` or `priority`, mixing both **lsp** and **buffer** info wildly.

**Comment by hrsh7th** [comment]
Hm... OK. Maybe I understand your issue.

**Comment by sQVe** [comment]
This is the result. I would expect *lsp* to have a much higher priority.

![image](https://user-images.githubusercontent.com/2284724/146006456-b3affc29-ec80-4d7d-82cc-da1c128c18dd.png)

**Comment by sQVe** [comment]
@hrsh7th As always - thank you for your fast response and effort ❤️ 🙏🏼 

The solution ☝🏼 now does what I want it to do! 🎉
