### ISSUE TITLE
Completion window wrongly pops up on the same row as the cursor line

### ISSUE THREAD

**Issue by imcaizheng** [hrsh7th/nvim-cmp#651]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+704-gac2d140a3

### Minimal reproducible config

Save the script as ~/.config/nvim/lua/simple_popup_window.lua
``` lua
local api = vim.api

local function create_temp_buf()
  local buf = api.nvim_create_buf(false, true) -- create new emtpy buffer
  api.nvim_buf_set_option(buf, 'filetype', 'vim')
  return buf
end

local function create_popup_win(buf)
  -- get dimensions
  local width = api.nvim_get_option("columns")
  local height = api.nvim_get_option("lines")

  -- calculate our floating window size
  local win_height = math.ceil(height * 0.5 - 4)
  local win_width = math.ceil(width * 0.5)

  -- and its starting position
  local row = math.ceil((height - win_height) / 2 - 1)
  local col = math.ceil((width - win_width) / 2)

  -- set some options
  local opts = {
    style = "minimal",
    relative = "editor",
    width = win_width,
    height = win_height,
    row = row,
    col = col,
    border = 'single',
  }

  -- and finally create it with buffer attached
  win = api.nvim_open_win(buf, true, opts)

  api.nvim_win_set_option(win, 'cursorline', true)
  api.nvim_win_set_option(win, 'winhighlight', 'Normal:None')
end

local buf, win

local function open_window()
  buf = create_temp_buf()
  win = create_popup_win(buf)
end

return {
  open_window = open_window,
}
```

### Description

![https://i.imgur.com/mvP7N0q.gif](https://i.imgur.com/mvP7N0q.gif)

### Steps to reproduce

Execute `lua require'simple_popup_window'.open_window()` in command mode.

### Expected behavior

The completion window shows up below the cursor just like it normally is.

### Actual behavior

The completion window occupied the cursor line.

### Additional context

Able to reproduce with "Minimal reproducible config".

**Comment by hrsh7th** [comment]
Related https://github.com/neovim/neovim/issues/16132

**Comment by dmitmel** [comment]
It's possible to work around this by checking `nvim_win_get_config(0).border` and adding 1 to the coordinates returned by `screenpos()` if the border exists

**Comment by hrsh7th** [comment]
Then if neovim fixes this bug, we should remove that patch.

**Comment by hrsh7th** [comment]
The neovim has fixed the bug.
https://github.com/neovim/neovim/pull/16134#issuecomment-995714746

Thank you for @zeertzjq !
