### ISSUE TITLE
Omni Completion (offset?) issues

### ISSUE THREAD

**Issue by zacmar** [hrsh7th/nvim-cmp#652]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+717-gf37c5f180a

### Minimal reproducible config
`init.vim`
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-omni'
Plug 'hrsh7th/vim-vsnip'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "omni" },
  },
}
EOF
```
### Description

Using the `omni` source doesn't work as intended.
Consider
```python
import numpy
n|
```
where `|` denotes the cursor. This results in 
![2021-12-17-113249_119x61_scrot](https://user-images.githubusercontent.com/32982619/146531259-764490a4-6cb3-4026-babb-b90d28fd4401.png)
Pressing `<C-n>` results in
```python
import numpy
umpy.
```
![2021-12-17-113429_135x62_scrot](https://user-images.githubusercontent.com/32982619/146531491-250cf54a-8a2e-4e85-989d-a4d963bd8739.png)

### Steps to reproduce

cat > minimal.py << EOF
import numpy
EOF
nvim -u init.vim minimal.py
on\<C-n>

### Expected behavior

```python
import numpy
numpy
```

### Actual behavior

```python
import numpy
umpy.
```

### Additional context

I came across this issue when adding the `omni` source for vimtex. There has been some discussion about offset issues [here](https://github.com/lervag/vimtex/issues/2215) and [here](https://github.com/hrsh7th/cmp-omni/issues/1), which might be somehow related. 

On a side-note, I have noticed that sometimes `(neo)vim`s built-in omni completion for python outperforms the `nvim-lsp` source. For instance, when completing function calls, it inserts the `(` without me having to type this. Is this in `nvim-cmp`s control, or does this depend entirely on the completion the language server provides?

**Comment by hrsh7th** [comment]
@zacmar Hm... I can't get `numpy` results from omni source. How to get it?

**Comment by jhossbach** [comment]
Here is a working minimal vimrc:
`minimal.vim:`
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-omni'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm(),
    ['<Tab>'] = cmp.mapping(function(callback)
	    if cmp.visible() then
		    cmp.select_next_item()
	    else
		callback()
	    end
	end)
  },

  sources = {
    { name = "omni" },
  },
}
EOF
```
 - Start writing a .py file with `nvim -u minimal.vim test.py`.
 - Make sure that `:echo &omnifunc` returns `python3complete#Complete` which is located in `/usr/share/nvim/runtime/autoload/python3complete.vim`
 - try `import numpy<Cr>n` as shown above, if that doesn't work try `import math<Cr>m` if numpy is not installed

**Comment by jhossbach** [comment]
Here is a small Dockerfile to reproduce this issue:
```dockerfile
FROM archlinux

RUN pacman -Syu --noconfirm git python neovim python-neovim

WORKDIR /src/cmp_bug2

COPY ./minimal.vim ./

```

**Comment by jhossbach** [comment]
FYI @hrsh7th: Check out the [Deepl Translator](https://www.deepl.com/translator) for Japanese->English translation, in my experience this provides better translations than the Google translator :)

**Comment by hrsh7th** [comment]
I can reproduce with `math|<C-n>`.

**Comment by jhossbach** [comment]
This fixes the truncation at the beginning, but still adds a dot(.) at the end. Is that intentional?

**Comment by hrsh7th** [comment]
It's specified by python's omnicomplete. I can't fix this sorry.

**Comment by jhossbach** [comment]
I see, thanks for the answer!
