### ISSUE TITLE
`Pattern not found` is constantly printed in insert mode if `native_menu` and `noshowmode` are enabled

### ISSUE THREAD

**Issue by lumbo7332** [hrsh7th/nvim-cmp#653]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.0

### Minimal reproducible config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

set noshowmode

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
  experimental = {
    native_menu = true,
  },
}

EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

### Description

If the experimental nvim-cmp `native_menu` and the Vim `noshowmode` options are enabled, the message `Pattern not found` is printed to the command line with every keystroke in insert mode.

### Steps to reproduce

1. Use minimal configuration file.
2. Set:
```
experimental = {
  native_menu = true,
}
```
3. Set:
```
set noshowmode
```
4. Run `nvim -u <minimal-config>`
5. Enter insert mode
6. Begin typing

### Expected behavior

Nothing is printed to the command line when typing in insert mode.

### Actual behavior

`Pattern not found` is printed to the command line with every keystroke in insert mode

**Comment by Shougo** [comment]
set shortmess+=c

**Comment by dmitmel** [comment]
I think this is a sign of a different problem. I use nvim-cmp with airline, and when the (native) completion menu is open, airline shows the current mode as `INSERT COMPL`. This is how it is supposed to work, but with nvim-cmp the `COMPL` label is added from so much as entering the Insert mode, and appears even if no results are available (so no completion menu is shown). I think this is because nvim-cmp calls `vim.fn.complete()` way too frequently.

**Comment by hrsh7th** [comment]
I think this should be fixed and will be fixed.
Please tell me the reason for using native_menu for reference.

I'm thinking of removing it in the future, so I'd like to know if there is a problem with custom_menu.

_google translated_

**Comment by dmitmel** [comment]
The undo bug, #328

**Comment by lumbo7332** [comment]
> I'm thinking of removing it in the future, so I'd like to know if there is a problem with custom_menu.

Oh. I guess I just prefer using the native UI components so everything can be uniform.

**Comment by lumbo7332** [comment]
That fixes it, thanks!
