### ISSUE TITLE
How do I configure to work with Ultisnips?

### ISSUE THREAD

**Issue by quangnguyen30192** [hrsh7th/nvim-cmp#66]

**Comment by hrsh7th** [comment]
At least, snippet configuration is works with the following config.

```lua
require'cmp'.setup {
  snippet = {
    expand = function(args)
      vim.fn['UltiSnips#Anon'](args.body)
    end
  },
}
```

**Comment by quangnguyen30192** [comment]
Thanks, how do I add Ultisnips into sources? I did not found from https://github.com/topics/nvim-cmp

**Comment by hrsh7th** [comment]
I think currently no.
I hope someone will create cmp-ultisnips source.

**Comment by quangnguyen30192** [comment]
Yes, it's me. Just created the source for ultisnips: https://github.com/quangnguyen30192/cmp-nvim-ultisnips

Added nvim-cmp topic.

**Comment by hrsh7th** [comment]
Wow! Thank you!
