### ISSUE TITLE
ConfirmBehavior.Insert replacing

### ISSUE THREAD

**Issue by adlrwbr** [hrsh7th/nvim-cmp#664]
### Discussed in https://github.com/hrsh7th/nvim-cmp/discussions/628

<div type='discussions-op-text'>

<sup>Originally posted by **smackesey** December  8, 2021</sup>
I see that `cmp.confirm` takes a behavior argument of `cmp.ConfirmBehavior.Insert` or `cmp.ConfirmBehavior.Replace`. What exactly differentiates these behaviors? It's not documented in either `nvim-cmp.txt` or the `README`.

I thought `Replace` would replace the entire word under the cursor, like this:

```
# NOTE: cursor location indicated by "|"

bo|at  # invoke completion: { boat, bore, bong }
bo|re  # I would expect this if I select "bore" for completion with `Replace`
bore|at  # Instead I get this, which is what I would expect for `Insert`
```

</div>

**Comment by adlrwbr** [comment]
I'm attempting to emulate JetBrains' default behavior, but the following mappings are not producing the expected results detailed in #628.
```
mapping = {
  ['<CR>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Insert, select = true }),
  ['<Tab>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true })
}
```

**Comment by hrsh7th** [comment]
### cmp.ConfirmBehavior.Insert

```
aiueo
aiu|<C-n><CR>eo
```
↓↓↓
```
aiueo
aiueo|eo
```

### cmp.ConfirmBehavior.Replace

```
aiueo
aiu|<C-n><CR>eo
```
↓↓↓
```
aiueo
aiueo|
```

**Comment by adlrwbr** [comment]
It does seem to be working. I was mistaken. Thanks.
