### ISSUE TITLE
Buffer management should be built-in

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#665]
I don't satisfy current behavior.

**Comment by hrsh7th** [comment]
The cmp-buffer implementation is quiet smart and efficient now. (Thank you @dmitmel)

I think we should buffer management as built-in feature and we should enable `locality_bonus` by default.

**Comment by dmitmel** [comment]
@hrsh7th Do you wish to move the `buffer.lua` module into the core of nvim-cmp?

**Comment by hrsh7th** [comment]
In nvim-cmp.

```lua
require('cmp').setup {
  completion = {
    keyword_pattern = ... -- It will be used by the `cmp.buffers`.
  }
}
require('cmp').buffers.get(0).get_distance(word, lnum)
require('cmp').buffers.get(0).get_words(from, to)
require('cmp').buffers.add(bufnr)
require('cmp').buffers.del(bufnr)
require('cmp').config.compare.locality
```

And we should refactor `cmp-buffer` to use the `require('cmp').buffers`.

Benefits
- locality bonus sort can be built-in

Pitfalls
- The buffers will be a singleton so we can't do the hack `require('cmp').register_source('buffer2', require('cmp_buffer.source').new())

we should consider the handling of keyword pattern wisely.

**Comment by hrsh7th** [comment]
I hope to make the buffer indexing be a real parallel implementation. I think it's difficult but if we can it, it's very performant.

**Comment by dmitmel** [comment]
> In nvim-cmp.

If so, can you please open a PR with the changes? I might have some comments about the integration.
