### ISSUE TITLE
Disable completion when in a comment

### ISSUE THREAD

**Issue by mbpowers** [hrsh7th/nvim-cmp#667]
I don't know if it's just me, but this would be a useful feature IMO.

**Comment by Shougo** [comment]
It is useful feature, but comment parsing is very difficult.

**Comment by mbpowers** [comment]
Since the syntax highlighting knows when you are in a comment, is there any way that this could  piggyback off that?

**Comment by Shougo** [comment]
The default syntax highlight knows it, but if treesitter is enabled it is hard.

**Comment by dmitmel** [comment]
```lua
cmp.setup({
  enabled = function()
    local lnum, col = vim.fn.line('.'), math.min(vim.fn.col('.'), #vim.fn.getline('.'))
    for _, syn_id in ipairs(vim.fn.synstack(lnum, col)) do
      syn_id = vim.fn.synIDtrans(syn_id) -- Resolve :highlight links
      if vim.fn.synIDattr(syn_id, 'name') == 'Comment' then
        return false
      end
    end
    return true
  end,
```

**Comment by Shougo** [comment]
Yes, it only works for non treesitter syntax

**Comment by max397574** [comment]
I'm working on a function for this
I'll open a pr soon
