### ISSUE TITLE
View labelDetails from cmp-omni with formatting

### ISSUE THREAD

**Issue by Xystel** [hrsh7th/nvim-cmp#668]
Hello, 

first I wanna say thank you for the awesome plugin you made.

# My Enviroment

- edited the formatting according to [Menu Appearence](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance), so I see the LSP Kind and Source Names
- using neovim for coding and writing in LaTeX. For coding I use LSP and for LaTeX I use [vimtex](https://github.com/lervag/vimtex)

# My Problem

I want to see the labelDetails from [cmp-omni](https://github.com/hrsh7th/cmp-omni), discussed in this [Issue](https://github.com/hrsh7th/cmp-omni/issues/1) and implemented in [this commit](https://github.com/hrsh7th/cmp-omni/commit/580d07d32242d542e365d2732eddd2dbb7374aff) to show in my formatted cmp menu. But I dont't know how. 

If I remove the formatting table completely the menu shows the labelDetails, but then I don't have the formatting (obviously).

# Possible Solutions

1. Because this Issue is only affected for `.tex` files, I could reset the formatting in `after/ftplugin/tex.vim`. I tried this with `formatting = {}` and `formatting = nil`, neither of them worked. But overwriting the sources this way worked, so I think I missed something.
2. The other, and prefered solution, would be to edit my formatting. It should show the source name + labelDetails. In the case of my config, it should look like this for latex: `command kind [Omni] labelDetails`. Is this possible?

# My config

cmp.lua
```lua
vim.opt.completeopt = "menuone,noselect"

-- luasnip setup
local luasnip = require 'luasnip'

-- friendly-snippets setup
require("luasnip/loaders/from_vscode").load()

-- nvim-cmp setup
local cmp = require 'cmp'
cmp.setup {
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  mapping = {
    [...]
  },
  -- Reference: https://github.com/hrsh7th/nvim-cmp#how-to-show-name-of-item-kind-and-source-like-compe
  formatting = {
		-- deprecated = true,
		format = function(entry, vim_item)
			-- load lspkind icons
       vim_item.kind = string.format(
          "%s %s",
          require("plugins.config.lspkind").icons[vim_item.kind],
          vim_item.kind
       )

			-- set a name for each source
			vim_item.menu = ({
				nvim_lsp = "[LSP]",
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
				omni = "[Omni]",
			})[entry.source.name]

			return vim_item
		end,
	},
  sources = {
    { name = 'nvim_lsp' },
    { name = 'omni' },
    { name = 'luasnip' },
    { name = 'buffer' },
  },
}
```

after/ftplugin/tex.vim
```vim
lua <<EOF
local cmp = require('cmp')
cmp.setup.buffer {
	enabled = true,
	-- I thought I could reset the formatting with this
	formatting = {},
	sources = cmp.config.sources {
			{ name = 'omni' },
			{ name = 'luasnip' },
			{ name = 'buffer' },
		}
	}
EOF
```

**Comment by hrsh7th** [comment]
The labelDetails will be added to the vim_item.menu.
Your code seems to remove it.

You can check the vum_item via `print(vim.inspect(vim_item))`

**Comment by Xystel** [comment]
Thanks for your quick answer. 

As you said, I overwrite vim_item.menu, which is a desired behavior for most sources, but not with omni. So I adjusted the config. Now my `after/ftplugin/tex.vim` contains this (inside a lua block):

```lua
local cmp = require('cmp')
cmp.setup.buffer {
    	formatting = {
		fields = { 'abbr', 'kind', 'menu' },
		format = function(entry, vim_item)
			if entry.source.name == "omni" then
				return vim_item
			else
				vim_item.menu = ({
					luasnip = "[LuaSnip]",
					buffer = "[Buffer]",
				})[entry.source.name]
			end
			return vim_item
		end,
	},
	sources = cmp.config.sources({
				{ name = 'omni' },
				{ name = 'luasnip' },
				{ name = 'buffer' },
		})
	}
```

This shows the labelDetails for suggestions from omni and for e. g. LuaSnip the custom text, `[LuaSnip]` in my case.

![2021-12-25_20-09](https://user-images.githubusercontent.com/76221461/147391944-f24963cc-7dfb-4d00-b03b-71f3eaf7014a.png)

**Comment by hrsh7th** [comment]
The `formatting.format` is just `function`. You can do everything by yourself.

**Comment by hrsh7th** [comment]
Did you try `print(vim.inspect(vim_item))`?

**Comment by Xystel** [comment]
I experimented with `print(vim.inspect(vim_item))`, but I didn't knew what to do exactly with it. I tried this in my `after/ftplugin/tex.vim`:

```lua
cmp.setup.buffer {
  formatting = {
		format = function(entry, vim_item)
			vim_item.menu = ({
        			omni = print(vim.inspect(vim_item)),
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
			})[entry.source.name]
			return vim_item
		end,
	},
  sources = {
	{ name = 'omni' },
	{ name = 'luasnip' },
	{ name = 'buffer' },
  },
}
```

But It results in an empty string. 

![image](https://user-images.githubusercontent.com/76221461/147404354-44cb763c-ae57-47ea-915f-a196cb27fa51.png)

I also tried something like this:

```lua
format = function(entry, vim_item)
	local menu_text = print(vim.inspect(vim_item.menu))
	vim_item.menu = ({
        	omni = menu_text,
[...]
```

But that does not work either. So I came up with that if-else solution.

**Comment by hrsh7th** [comment]
? why do you use return value of `print(vim.inspect(vim_item.menu))` ?

I say again, the `formatting.format` is just a `Lua function`. You can do what you expect by yourself.

**Comment by Xystel** [comment]
At this point I should admit that I'm currently a beginner with lua and the neovim API.

> ? why do you use return value of `print(vim.inspect(vim_item.menu))` ?

Because you recommended it to me. But I wasn't sure what to do with that exactly, so I tried some things.

> I say again, the `formatting.format` is just a `Lua function`. You can do what you expect by yourself.

Yes I realized that. Thats why I came up with the if-else solution, described in [this comment](https://github.com/hrsh7th/nvim-cmp/issues/668#issuecomment-1001063436). That works for me.

If there is a better solution, I don't see it. If you want you can provide me an example. But you don't need to, because it works and does what I want.

**Comment by hrsh7th** [comment]
Try this.

```
			vim_item.menu = ({
        			omni = print(vim.inspect(vim_item)),
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
			})[entry.source.name] .. vim_item.menu
			return vim_item
```

**Comment by Xystel** [comment]
Does not work, I get following message from Neovim:

```
{                                                                                                                                                                                                                   
  abbr = "begin",                                                                                                                                                                                                   
  dup = 1,                                                                                                                                                                                                          
  kind = "Text",                                                                                                                                                                                                    
  menu = "[cmd: default] ",                                                                                                                                                                                         
  word = "begin"                                                                                                                                                                                                    
}                                                                                                                                                                                                                   
Error executing vim.schedule lua callback: [string ":lua"]:10: attempt to concatenate a nil value                                                                                                                   
stack traceback:                                                                                                                                                                                                    
        [string ":lua"]:10: in function 'format'                                                                                                                                                                    
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:285: in function 'callback'                                                                                                                     
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:36: in function 'get_vim_item'                                                                                                                  
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:205: in function 'get_view'                                                                                                                     
        ...cker/start/nvim-cmp/lua/cmp/view/custom_entries_view.lua:121: in function 'open'                                                                                                                         
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/view.lua:107: in function 'open'                                                                                                                         
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:284: in function 'cb'                                                                                                                           
        vim.lua:285: in function <vim.lua:285> 
```

It seems that `vim_item` is a nil value inside the `formatting.format` function.

**Comment by dmitmel** [comment]
```lua
format = function(entry, vim_item)
  vim_item.menu = ({
    omni = vim.inspect(vim_item),
    luasnip = "[LuaSnip]",
    buffer = "[Buffer]",
  })[entry.source.name]
  return vim_item
end,
```

**Comment by hrsh7th** [comment]
```
			vim_item.menu = (({
        			omni = '[omni]',
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
			})[entry.source.name] or '') .. vim_item.menu
			return vim_item
```
Sorry. it had a bug. Please debug on your side.

**Comment by Xystel** [comment]
Thanks for your help! I now came up with two solutions.

# Concatenate entry.source.name and vim_item.menu

It still crashed with your suggestion, because vim_item.menu is a nil value for all other sources (luasnip and buffer), so I added a function to convert this. The `after/ftplugin/tex.lua` looks now:

```lua
str_check = function(str)
  if str == nil then
    return ""
  else 
    return " -> " .. str
  end
end,

local cmp = require('cmp')
cmp.setup.buffer {
  formatting = {
		fields = { 'abbr', 'kind', 'menu' },

		format = function(entry, vim_item)
			vim_item.menu = ({
        			omni = "[Omni]",
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
				})[entry.source.name] .. str_check(vim_item.menu)
			return vim_item
		end,
	},
-- [...]
}
```

Result:

![image](https://user-images.githubusercontent.com/76221461/147410083-4964a2ea-cbfc-4176-a547-2a1cfab195b3.png)

# Replace vim_item.menu with labelDetails

In this solution I use the `vim_item` as suggested from @dmitmel. But with this solution the labelDetails where between quotes, so I added a `gsub` to remove them.

```lua
formatting = {
		fields = { 'abbr', 'kind', 'menu' },
		format = function(entry, vim_item)
			vim_item.menu = ({
        			omni = (vim.inspect(vim_item.menu):gsub('%"', "")),
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
				})[entry.source.name]
			return vim_item
		end,
	},
```

Result:

![image](https://user-images.githubusercontent.com/76221461/147410307-9da4fb3a-9837-44c6-92aa-d60293115bf9.png)
