### ISSUE TITLE
[Question] Using TAB to expand % in cmdline

### ISSUE THREAD

**Issue by rbozan** [hrsh7th/nvim-cmp#675]
Without the following:
```lua
  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })
```

I can do this:
```
:!cp %<TAB>
```

which expands % to the current file I am seeing. This somehow does not seem to work properly with this plugin. Am I missing something? Is this a bug?

**Comment by Shougo** [comment]
I think `<Tab>` key is mapped by `nvim-cmp` command line completion.

**Comment by hrsh7th** [comment]
Yes. It's bug but it's very difficult to fix.

You can disable nvim-cmp's default mapping via `cmp.config.disable` value like this.

```lua
  cmp.setup.cmdline(':', {
    mapping = {
      ['<Tab>'] = cmp.config.disable,
    },
    sources = cmp.config.sources({
      { name = 'path' },
    }, {
      { name = 'cmdline' },
    })
  })

```
