### ISSUE TITLE
CommandLine Appears to be ignoring Mapping

### ISSUE THREAD

**Issue by miversen33** [hrsh7th/nvim-cmp#678]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev+581-g8f984dc1f

### Minimal reproducible config

```vimscript
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require('cmp')

cmp.setup({
  snippet = {
    -- REQUIRED - you must specify a snippet engine
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<Up>'] = cmp.mapping.select_prev_item(),
    ['<Down>'] = cmp.mapping.select_next_item(),
    ['<Enter>'] = cmp.mapping.confirm({ select=true })
  },
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'cmdline' }
  }),
})

EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When setting the `<Up>` and `<Down>` keys to `cmp.mapping.select_prev_item()` or `cmp.mapping_select_next_item()`, the `Up` and `Down` keys are ignored (pressing them when in command mode exits the completion window instead of moving to the next/previous item in the completion window).

Note; Using _any_ key fails here (I have tried with '<C-o>` and `<C-l>` as well, thinking the arrow keys may have some issue being mapped to). Additionally, the key mappings _do_ work when in the buffer while in `insert` mode.

### Steps to reproduce

Open nvim using the minimal config
```shell
$ nvim -u minimalconfig.lua
```
Press `:` to enter command mode
Begin entering any command and wait for completion window to appear
Press the `Up` or `Down` arrow key (or whatever you map to `select_prev_item` and `select_next_item`)

### Expected behavior

Pressing the keys mapped to `select_prev_item` or `select_next_item` should perform that action when in command mode. 

### Actual behavior

Pressing the keys associated to `select_prev_item` or `select_next_item` closes the completion window

### Additional context

From poking this a bit, I am guessing the `cmp.setup.cmdline` section has hardcoded mappings and thus just ignores the mappings set in `setup` (this can be seen in that `<S-Tab>` and `<Tab>` still work for `select_prev_item` and `select_next_item` regardless of the mapping you have set.

Also, possible related to [Issue 462](https://github.com/hrsh7th/nvim-cmp/issues/642)

**Comment by hrsh7th** [comment]
```
  mapping = {
    ['<Up>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 'c' }),
    ['<Down>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 'c' }),
    ['<Enter>'] = cmp.mapping(cmp.mapping.confirm({ select=true }), { 'i', 'c' })
  },
```

**Comment by miversen33** [comment]
That does it. 
When looking at the documentation, I see [And you can specify the mapping modes.](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L239), however there are certainly examples where the "mode" is not specified. Thus I assumed if I didn't specify the mode, it would apply across _all_ modes. 

It appears that assumption was incorrect, though it might be worth clarifying that in the documentation.

Regardless though, specifying the modes _does_ correct it!

Thanks!
