### ISSUE TITLE
Disable auto-import

### ISSUE THREAD

**Issue by mareksubocz** [hrsh7th/nvim-cmp#682]
Hi, is it possible to disable auto import suggestions? Also, if there is an option to do that, where can I get that information without asking here? I often find myself exploring codebases by looking at the available completions and seeing what's there, auto-import features gives me a lot of unnecessary clutter. Thank you in advance :)

**Comment by dmitmel** [comment]
This depends on the Language Server you are using, nvim-cmp is not responsible for auto imports on completion. Generally, you should look at the documentation of a particular LS to see if autoimporting can be disabled.

**Comment by mareksubocz** [comment]
I see, thank you :)
