### ISSUE TITLE
sumneko_lua module name suggestions remove qoutes or insert extra characters on confirm

### ISSUE THREAD

**Issue by dripware** [hrsh7th/nvim-cmp#683]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.6.0

### Minimal reproducible config

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF

require'lspconfig'.sumneko_lua.setup{}

local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

### Description

using sumneko_lua language server when choosing a suggestion for module names from autocompletion menu weird things happen. like an extra character gets inserted at the end or quote signs get removed. which is very weird because in my config i have shadow_text enabled and shadow text is shown correctly

https://user-images.githubusercontent.com/90397425/147663092-70d2ed78-d879-4e5f-9780-dd97c9c1b839.mp4

### Steps to reproduce

open a lua file
insert require'
choose an item from the auto completion menu

### Expected behavior

module name be inserted correctly without extra characters or quotes getting removed

### Actual behavior

moudle name is not correctly inserted

**Comment by hrsh7th** [comment]
It seems to be a bug because VSCode doesn't have this problem.

I'll push the fix, but if that fix breaks the behavior of other servers, I might revert.
