### ISSUE TITLE
How to disable the appearance of buffer text?

### ISSUE THREAD

**Issue by RomeuG** [hrsh7th/nvim-cmp#684]
Hi!

I did try to see if there was a similar issue that was already open/resolved. I also read the documentation. So I apologize if I did misread something.

While I am editing my `init.lua` file, for some reason, I am getting completions of the kind `Text`:

![image](https://user-images.githubusercontent.com/2325589/147681304-bb27d45a-e18e-4ffe-98de-06ea65ba3b9f.png)

I do not have `cmp-buffer` installed (I think that is supposed to be the purpose of `cmp-buffer`, which I do not want).

Thanks!

**Comment by gegoune** [comment]
You might want to look at sumneko's lua-language-server (I assumed that's what you are using above) to try stop it from returning those completion results. cmp here just displays what LSP returns (I believe).

**Comment by RomeuG** [comment]
Yes, indeed it is. I thought `cmp` could actually filter this, since sumneko's lua-language-server does not clarify how to deal with it.

**Comment by dmitmel** [comment]
When you configure lua-language-server, set the option `Lua.completion.workspaceWord` to `false`.

**Comment by hrsh7th** [comment]
It seems to solved. Thank you.

**Comment by RomeuG** [comment]
Perfect, thanks!
