### ISSUE TITLE
How can I hide (or ignore specific) hints?

### ISSUE THREAD

**Issue by layer7n** [hrsh7th/nvim-cmp#685]
I'm using the Pyright server, and there are instances where my editor shows hints like this:

![image](https://user-images.githubusercontent.com/43588940/147683638-5f01de5c-0692-46cb-814c-c80c50ad23be.png)

These hints go away while editing, but they are extremely distracting in visual mode, especially when they are irrelevant in certain scenarios.

**How can I hide all and/or close specific hints?**

**Comment by gegoune** [comment]
Those have nothing to do with nvim-cmp. Did you mean to post it in lspconfig issues tracker (which isn't the right place to ask that question either)? You can hide them by correctly setting diagnostics via `vim.diagnostic.config()`. `:h vim.diagnostic.config` (`virtual_text.severity`).

**Comment by layer7n** [comment]
> 

Sorry, been a long morning. Any way I can delete this?

**Comment by tetomi** [comment]
I believe putting the code below into your `init.vim` file will solve your problem.
Especially the `virtual_text = false` part is what you're looking for.
    
    vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        underline = true,
        virtual_text = false,
        signs = true,
        update_in_insert = false,
      }
    )

**Comment by layer7n** [comment]
> I believe putting the code below into your `init.vim` file will solve your problem. Especially the `virtual_text = false` part is what you're looking for.
> 
> ```
> vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
>   vim.lsp.diagnostic.on_publish_diagnostics, {
>     underline = true,
>     virtual_text = false,
>     signs = true,
>     update_in_insert = false,
>   }
> )
> ```

Thanks for getting back to me @tetomi . Unfortunately, putting that block in my `init.vim` is giving me errors for some reason:

![7aQm8TdN7g](https://user-images.githubusercontent.com/43588940/147734970-c530d5ca-a68e-4691-821a-a422df877b53.png)

I've been trying to figure it out but I can't disable them.

**Comment by hrsh7th** [comment]
It seems to be solved.
