### ISSUE TITLE
How to move to the next parameter?

### ISSUE THREAD

**Issue by huanglei104** [hrsh7th/nvim-cmp#689]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0

### Minimal reproducible config

 41 local cmp = require('cmp')
 42 cmp.setup({
 43     snippet = {
 44         expand = function(args)
 45             vim.fn["vsnip#anonymous"](args.body)
 46         end,
 47     },
 48     mapping = {
 49       ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
 50       ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
 51       ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
 52       ['<C-y>'] = cmp.config.disable,
 53       ['<C-e>'] = cmp.mapping({
 54         i = cmp.mapping.abort(),
 55         c = cmp.mapping.close(),
 56       }),
 57       ['<CR>'] = cmp.mapping.confirm({ select = true }),
 58     },
 59     sources = cmp.config.sources({
 60       { name = 'nvim_lsp' },
 61       { name = 'vsnip' },
 62       { name = 'buffer' },
 63       { name = 'path' },
 64     })
 65 })
 66 

### Description

when i hit enter,  completion such as 'foo(int a, int b, int c)' ,and 'int a' is selected,
how to select 'int b' ? 

### Steps to reproduce

no

### Expected behavior

no

### Actual behavior

no

**Comment by dmitmel** [comment]
Please take a look at this wiki page: https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#super-tab-like-mapping.

(Also, your screenshot hasn't been uploaded)

**Comment by huanglei104** [comment]
> Please take a look at this wiki page: https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#super-tab-like-mapping.
> 
> (Also, your screenshot hasn't been uploaded)

Solved my problem, thank you very much！
