### ISSUE TITLE
Unable to update from packer

### ISSUE THREAD

**Issue by nachiketkanore** [hrsh7th/nvim-cmp#691]
Unable to update nvim-cmp package from packer.nvim using :PackerSync command
![Screenshot from 2021-12-30 22-32-29](https://user-images.githubusercontent.com/44920607/147772863-51d155cb-54b4-45ab-8bb8-eac7a156e0be.png)

nvim-cmp crashes in between while selecting option from dropdown
![Screenshot from 2021-12-30 22-33-08](https://user-images.githubusercontent.com/44920607/147772928-3ab24078-d2a0-4ef9-b016-8c316a8b1c21.png)

**Comment by hrsh7th** [comment]
Please re-update

**Comment by nachiketkanore** [comment]
Sorry, what do you mean re-update? I tried :PackerUpdate and same issue persists.

**Comment by hrsh7th** [comment]
Please try PackerUpdate & PackerCompile.

**Comment by williamboman** [comment]
I'm running into the same issue. Was there a force push to the `main` branch perhaps? @nachiketkanore I'm not sure if Packer has some builtin command to fix diverging histories, but what you can do is navigate to the installation directory and run a `git reset --hard @{u}`.

**Comment by nachiketkanore** [comment]
PackerUpdate & PackerCompile worked for me. Atleast the "Failed to update" error is gone. Thanks

**Comment by hrsh7th** [comment]
Yes. I somtimes use the force push.... hm...
