### ISSUE TITLE
Bug with cmdline and <C-y>

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#692]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+725-g439336079

### Minimal reproducible config

```VIM
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/vim-vsnip'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "buffer" },
    { name = "path" },
  },
}


-- cmp.setup.cmdline(':', {
--     completion = {
--         autocomplete = false,
--     },
--     sources = cmp.config.sources({
--         { name = 'path' },
--     }, {
--         { name = 'cmdline' },
--     }),
-- })
EOF
```

### Description

First of all, I am not entirely sure if this is a bug with cmdline or cmp itself. It's related to cmdline, but since the main logic for the most part is in cmp, I figured I open the issue here. If it's cmdline issue, then I can move it.

I have a problem with trying to complete the suggestions with cmdline. They are not working like I would expect them to work after using the built-in menu ever since trying cmdline out.

In this video, you can see when I have cmdline configured. That is the minimal config I pasted above, only with the commented lines not commented out. I commented them out to also show you how it work with the built-in one.

cmdline:

https://user-images.githubusercontent.com/5160701/147834723-c7d393c7-9f31-4f6d-9fb4-9ec9fe92ca51.mov

built-in
https://user-images.githubusercontent.com/5160701/147834765-212339c7-149b-4cab-831c-f173d43c7b88.mov

Here you can see that I start typing and tab to complete. Then I want to confirm the option so I can either tab to get the next options up.

With cmdline, it doesn't complete like normal, and it is really annoying when I am not sure of the entire path and need to press tab to get some options up. If I type the entire word it also won't always dissapear since the trailing `/` is a part of the completion.

### Steps to reproduce

Use the minimal config, and try to tab to complete, and then press <C-y> to confirm.

### Expected behavior

I would want the menu to go away when I press <C-y>, so that I can then tab to get the next options up to cycle through.

### Actual behavior

It actually inserts the characters for <C-y>

**Comment by hrsh7th** [comment]
Sorry. I can't understand the expected behavior...

**Comment by seblj** [comment]
Sorry I wasnt't clear enough... I will try to explain better.

The following video is showing when I use the built-in menu. Here you can see my keypresses as well. Notice when I press `^Y` which is `<C-y>`. Then the menu disappears and that keypress is like a `confirm`. I can then start pressing tab again to see items inside `/lib`.

https://user-images.githubusercontent.com/5160701/147849346-84331e05-c150-4e34-b38b-f3272086cc2c.mov


The following here is with cmdline enabled.

https://user-images.githubusercontent.com/5160701/147849406-386b5b54-5827-4a61-9295-cd3053869655.mov

Here you can see that it literally inserts `^Y` instead of closing the menu and inserting the item so I can press tab again. 

So the intended behaviour that I would like from cmdline is to behave in the same way as the built-in menu when pressing `<C-y>`.

**Comment by seblj** [comment]
So I found a workaround for the problem. By using the newly merged api for calling a lua function with keymaps I was able to do this and get the correct behaviour. So I will close this issue as I can live with this workaround

```lua
vim.api.nvim_set_keymap('c', '<C-y>', '', {
    callback = function()
        cmp.confirm({ select = false })
    end,
})
```
