### ISSUE TITLE
Duplicate redraw calls in cmdline cause flicker

### ISSUE THREAD

**Issue by yioneko** [hrsh7th/nvim-cmp#703]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+793-g991e872d8

### Minimal reproducible config

```vim
set packpath=

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  formatting = {
    fields = { "kind", "abbr", "menu" },
  }
}
cmp.setup.cmdline('/', {
  sources = {{ name = 'buffer' }},
})
EOF

hi CmpItemAbbrMatch ctermfg=green
hi CmpItemAbbrFuzzyMatch ctermfg=blue
EOF
```

### Description

https://github.com/hrsh7th/nvim-cmp/blob/1b94aacada96d2a33fef2ecf87748b27a2f50630/lua/cmp/view/custom_entries_view.lua#L222-L226
https://github.com/hrsh7th/nvim-cmp/blob/1b94aacada96d2a33fef2ecf87748b27a2f50630/lua/cmp/utils/window.lua#L177-L181

While typing in cmdline, the two duplicate redraw calls will cause flicker of completion window.

Flicker:
![flicker](https://user-images.githubusercontent.com/65551246/147924157-0a9d13ca-cfe9-455d-a2be-3696f607e38a.gif)

No flicker (remove one of the redraw call in src):
![noflicker](https://user-images.githubusercontent.com/65551246/147924203-1fccf490-2c9e-4172-960a-3542c6e4648c.gif)

This might seem subtle in the minimal reproduce sample, but the flicker is much more apparent if the rendering costs more time (in my dialy use).

### Steps to reproduce

Enable cmdline completion and type in cmdline.

### Expected behavior

There should be no flicker of completion window.

### Actual behavior

The flicker happens on keystroke at times.

**Comment by hrsh7th** [comment]
I'll fix this. thank you!

**Comment by megalithic** [comment]
interestingly enough; I'm getting this issue again, with the cmdline plugin. same behaviour, for instance, my `Packer*` commands are doubled up. is this a regression perhaps @hrsh7th?
