### ISSUE TITLE
Weird replace behaviour with gopls

### ISSUE THREAD

**Issue by itaranto** [hrsh7th/nvim-cmp#706]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Minimal reproducible config

```lua
-- Set completeopt to have a better completion experience
vim.opt.completeopt = 'menuone,noselect'

-- nvim-cmp setup
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end

local luasnip = require 'luasnip'
local cmp = require('cmp')

cmp.setup {
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(4),
    ['<C-u>'] = cmp.mapping.scroll_docs(-4),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { 'i', 's' }),
  },
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'luasnip' },
    {
      name = 'buffer',
      option = {
        get_bufnrs = function()
          local bufs = {}
          for _, win in ipairs(vim.api.nvim_list_wins()) do
            bufs[vim.api.nvim_win_get_buf(win)] = true
          end
          return vim.tbl_keys(bufs)
        end
      },
    },
    { name = 'calc' },
    { name = 'path' },
    { name = 'spell' },
  },
  formatting = {
      format = function(entry, vim_item)
        vim_item.menu = ({
          nvim_lsp = '[LSP]',
          buffer = '[Buffer]',
          calc = '[Calc]',
          path = '[Path]',
          spell = '[Spell]',
        })[entry.source.name]
        return vim_item
      end,
  },
}
```

### Description

After executing "Confirm" inside a Go `struct` the field gets replaced:

https://user-images.githubusercontent.com/11463919/148285825-c0e51c36-2cc5-48a4-a409-96d65ea87164.mp4

The same when calling a function:

https://user-images.githubusercontent.com/11463919/148286288-fc3a19af-96d2-43c2-98b9-f055b6f7178e.mp4

### Steps to reproduce

See description.

### Expected behavior

See description.

### Actual behavior

See description.

**Comment by hrsh7th** [comment]
First of all, The gopls replaces the text by itself.

But I think this issue caused by your configuration.

```
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
```
↓↓↓
```
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    },
```

**Comment by itaranto** [comment]
> behavior = cmp.ConfirmBehavior.Insert,

Setting to `cmp.ConfirmBehavior.Insert` doesn't change anything, I should have explained that in the description, sorry.

But, please don't close this issue.

**Comment by hrsh7th** [comment]
The `word replacement` was specified by the gopls itself. If you think this is still issue, you should report it to gopls

https://user-images.githubusercontent.com/629908/148399355-01b67d6c-abe7-4c91-9a4c-41d88dc61563.mp4

.

**Comment by itaranto** [comment]
> The `word replacement` was specified by the gopls itself. If you think this is still issue, you should report it to gopls

Makes sense, so it's a `gopls` issue then...
