### ISSUE TITLE
Possibility of automatically confirming on CompleteDone or some User autocmd?

### ISSUE THREAD

**Issue by fsouza** [hrsh7th/nvim-cmp#708]
One thing I miss when using nvim-cmp is stuff like auto-imports that just happen without me pressing any key combination. I tried implementing something on my side using CompleteDone, at first I thought that CompleteDone would work because nvim-cmp sets user_data on completion items, but later I found that nvim-cmp doesn't set user_data heh

I know that commit characters could potentially be used for this, but curious if there are any other alternatives to automatically confirm whenever an item is selected? Thanks!

**Comment by hrsh7th** [comment]
Hm... I can add the event like `require('cmp').event:on('close', function(evt) ... end`

**Comment by hrsh7th** [comment]
I've added the `complete_done` autocmd.

But achieving what you expect still be difficult even if this feature is added.

I think you should invoke `vim.lsp.util.apply_text_edits` by yourself manually.
