### ISSUE TITLE
Automatically select first or last result when manually opening completion menu

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#709]
This isn't really a bug, but more of a question/feature request. 

One thing I really miss is the possibility to automatically select the first or last option when the menu opens. 

For example: in cmdline, if I have `autocomplete = false`, and press `<Tab>`, it opens the menu. I would also like it to automatically move to the first entry. (Or last if I press `<S-Tab>`. This way I don't have to press `<Tab>` twice, where the first is to open the menu and the next is to select the first item.

I tried to mess around with overriding the mappings myself to select the next entry after calling `cmp.complete`, but couldn't get it to work. So sorry if there already is an easy way to do this.

The way I think could be good to solve this could be to pass an option to `cmp.complete` to say if it should automatically move to the first or last item when it opens up. For example something like:
`cmp.complete({ select = 'first' })` and `cmp.complete({ select = 'last' }). And if nothing is passed, then just open it like default.

Hope this is something that is possible to do! Thanks!

**Comment by seblj** [comment]
So I was able to find a workaround, but I really hope there is a better solution, or if there isn't already, then I hope it can be added!

This is my workaround for now which seems to work okay, but I don't really like how I have to defer with a timeout of a "magic" value to wait until the completion menu is opened.

```lua
local term = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

cmp.setup({
    mapping = {
        ['<Tab>'] = cmp.mapping({
            c = function(fallback)
                if #cmp.core:get_sources() > 0 and not cmp.get_config().experimental.native_menu then
                    if cmp.visible() then
                        cmp.select_next_item()
                    else
                        cmp.complete()
                        vim.defer_fn(function()
                            feedkeys.call(term('<C-n>'), 'i')
                        end, 50)
                    end
                else
                    fallback()
                end
            end,
        }),
    }
})
```

**Comment by hrsh7th** [comment]
I don't know the completion engine that achieve this feature...

**Comment by seblj** [comment]
I understand... it's probably difficult because of the scheduling and async stuff when opening the completion menu?
