### ISSUE TITLE
Help with vsnip compe migration.

### ISSUE THREAD

**Issue by bushblade** [hrsh7th/nvim-cmp#71]
Hi, I'm just migrating from compe where I was using ultisnips but am now trying vsnip which is mostly working fine.

I am however have a couple of problems I can't figure out.
One is how to use `<Tab>` to trigger expand or jump correctly?
I do have...
```lua
    ["<Tab>"] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<C-n>", true, true, true), "n")
      elseif vim.fn["vsnip#available"]() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>(vsnip-expand-or-jump)", true, true, true), "")
      else
        fallback()
      end
```
Which doesn't work for me.
Also how do you enable snippets in other file types, like enable html snippets in javascript/javascriptreact?
I tried
```lua
vim.g.vsnip_filetypes = {}
vim.g.vsnip_filetypes.javascriptreact = "javascript"
vim.g.vsnip_filetypes.typescriptreact = "typescript"
vim.g.vsnip_filetypes.html = "javascriptreact"
```
but get an error
![Screenshot_2021-08-25_14-59-03](https://user-images.githubusercontent.com/21976188/130804481-61e707a3-4819-4d44-bac9-0f5957a3042f.png)

**Comment by mortezadadgar** [comment]
about your first issue https://github.com/hrsh7th/nvim-cmp#how-to-setup-supertab-like-mapping

**Comment by bushblade** [comment]
@mortezadadgar Thanks for the reply.
Isn't that much the same as what I do have but for luasnip?

**Comment by hrsh7th** [comment]
You can use `vim.fn['vsnip#available'] == 1` and `vim.fn['vsnip#jumpable'](-1) == 1` for vim-vsnip.

It documented in vim-vsnip repo.

**Comment by hrsh7th** [comment]
Please refer to https://github.com/hrsh7th/nvim-cmp#how-to-setup-supertab-like-mapping to set it.

**Comment by bushblade** [comment]
Thanks.
So I'm trying with this..
```lua
    ["<tab>"] = cmp.mapping(
      function(fallback)
        if vim.fn.pumvisible() == 1 then
          vim.fn.feedkeys(t("<C-n>"), "n") -- this works
        elseif vim.fn["vsnip#jumpable"](-1) == 1 then
          print "jumpable"
          vim.fn.feedkeys(t("<Plug>vsnip-expand-or-jump"), "") -- this doesn't work
        elseif check_back_space() then
          vim.fn.feedkeys(t("<tab>"), "n")
        else
          print "fallback" -- this always runs
          fallback()
        end
      end,
      {
        "i",
        "s"
      }
    ),
```
And trying to figure it out added some prints but the else condition seems to run every time after a snippet has completed.

**Comment by bushblade** [comment]
Ok I've just gone with luasnip instead and that works seamlessly for me, so I'll close here.
Thanks for all the help and sorry if I'm a bit of a noob in configuring in lua.
