### ISSUE TITLE
[Question] how to enable triggering completion only after trigger character

### ISSUE THREAD

**Issue by alex-popov-tech** [hrsh7th/nvim-cmp#711]
Problem description:
I'm writing in typescript, and in `global` context there are a lot of stuff ( so if i will start typing `con` in empty file, there will be tens of suggestions ).
<img width="798" alt="CleanShot 2022-01-07 at 19 25 14@2x" src="https://user-images.githubusercontent.com/21224705/148582531-8c42a2d9-d72c-435e-b0e9-848c8001f433.png">
And I don't want these, i want to have suggestions ONLY after some trigger charecter, f.e. `.`(dot), i.e. for `consol` - no suggestions, for `console.` - some suggestions.
I checked out [this issue](https://github.com/hrsh7th/nvim-cmp/issues/501) and found option `sources[n].trigger_characters`, and tried to use it like this:
```
        sources = {
            {name = 'nvim_lsp', max_item_count = 10, trigger_characters={'.', ":"}},
            {name = 'buffer', max_item_count = 10},
            {name = 'path', priority = 1}
        },
```

which did not help for my case, but produced interesting results:
![CleanShot 2022-01-07 at 19 38 42](https://user-images.githubusercontent.com/21224705/148584184-5fc986ee-dd1e-4aca-b4a0-3c4aec3adc3f.gif)
as you see, dot (`.`) produces correct results (`dir`, `log`, etc) i.e. respecting context, but colon (`:`) produces different results, which are from `global` context, not `console`....

For me it seems that there is a bug, but I'm also not sure i understand how to approach my problem in first place :)

**Comment by hrsh7th** [comment]
First, You shoud remove trigger_characters option because of the typescript-language-server doesn't support `:` as trigger character.

Then you can set `keyword_length` as `math.huge` for disabling keyword completion.

**Comment by alex-popov-tech** [comment]
@hrsh7th thank you for answer!

Unfortunately it is not working the way i wanted :(

Currently, after typing `console.` i see completions list, but when i will type first letter of a method like `console.l` completion menu disappears until it hits `keyword_length` value...

And I wanted to remove only `global` scoped completions, and leave `context-based` completions just as they were...
I.e I want different behaviour of completion depending on current context, like
```{name = 'nvim_lsp', keyword_length = 5 }``` for case when typing `console`, and ```{name = 'nvim_lsp' }``` when typing  `console.l...`

Is it possible?

**Comment by hrsh7th** [comment]
I think global scope etc should be achieve by the LSP side.

I think nvim-cmp doesn't support ot. sorry.

**Comment by alex-popov-tech** [comment]
OK, no problem, thank you for explaining :)
And thank you for `nvim-cmp`, its an awesome plugin!
