### ISSUE TITLE
autocompletion isn't work at starting insert

### ISSUE THREAD

**Issue by octaltree** [hrsh7th/nvim-cmp#716]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+863-g8f27c4a041

### Minimal reproducible config

```lua
vim.cmd('set rtp+=~/.local/share/dein/repos/github.com/hrsh7th/nvim-cmp')
vim.cmd('set rtp+=~/.local/share/dein/repos/github.com/hrsh7th/cmp-buffer')

local cmp = require('cmp')
cmp.setup({
    sources = {{name = 'buffer'}},
    completion = {
        autocomplete = {
            require('cmp.types').cmp.TriggerEvent.InsertEnter,
            require('cmp.types').cmp.TriggerEvent.TextChanged
        }
    }
})

cmp.register_source('buffer', require('cmp_buffer'))
vim.cmd('set completeopt+=menu,menuone,noselect')
```

### Description

Sometimes the menu does not appear when I do InsertEnter. It might be skipped because there is no change from the last menu.

### Steps to reproduce

1. Open with `nvim -u mini.lua foo.txt`
2. Type "foo fo". the completion menu has "foo"
3. Escape from insert mode
4. Type 'a' to insert
5. The menu will not be shown

### Expected behavior

I want the completion menu to appear when InsertEnter.

### Actual behavior

It seems like the display is skipped when cursor_before_line is the same.

### Additional context

"`i`foo fo`<ESC>i<ESC>$a`" will show the menu.
"`i`foo fo`<ESC>i<ESC>$a<ESC>a`" will not show the menu at the last a.

**Comment by hrsh7th** [comment]
Thank you. I've fixed it.
