### ISSUE TITLE
Loosing selection in buffer while getting autocomplete in command mode

### ISSUE THREAD

**Issue by tarunsharma20** [hrsh7th/nvim-cmp#725]
Command based on selection not working, as selection getting loose as soon as autocomplete getting trigger.
For example:

### My buffer
```
c
a
c
d
b

```
I want to select 5 lines from my buffer and apply 'sort' command. After selection when i type `:` i am getting `:'<,'>` as expected. However after that when i press `s` i am getting all options(commands) available by my selection is not there anymore.

**Comment by tarunsharma20** [comment]
Is it fixed or not issue?

**Comment by hrsh7th** [comment]
It seems closed accidentaly. Sorry.

**Comment by hrsh7th** [comment]
I think it supported now by cmp-cmdline source side.
