### ISSUE TITLE
Source priority/limit

### ISSUE THREAD

**Issue by lucax88x** [hrsh7th/nvim-cmp#73]
avid user of nvim-compe here.

One feature that was really never implemented in the nvim-compe was a possibility to give a limit / priority on the sources.

classic example: in a typescript file, I want to autocomplete snippets and LSP.

I type 'us'.

from Snippets I should have 3/4 snippets with us.
but from LSP I may have 150 possible types.

In the end, I cannot pick my snippet, because usually they have very few keystrokes and the completion gets completely polluted by the LSP.

So, I have some possible ideas

- possibility to cycle between sources (default LSP, c-N => next source, etc)
- possibility to prioritize sources (I would prioritize snippets)
- possibility to add a limitation to each source (this could lead to problem, expecially for short names)
- maybe configure the fuzzy search show the shorter stuff first

**Comment by hrsh7th** [comment]
First, the source priority is already implemented.

You can change the order of `cmp.setup { sources =  { ... change this values order ... } } `.
And you can change the `sorting.priority_weight`.

However, the limit of each source is not implemented.
I will create separated issue for the limit per source.

**Comment by horseinthesky** [comment]
@hrsh7th Thank you for the successor.

Could you pls shed some light on why you moved the `priority` logic from
```
  source = {
    path = { kind = "" },
    buffer = { kind = "" },
    calc = { kind = "" },
    nvim_lsp = { kind = "" },
    nvim_lua = { kind = "" },
    spell = {
      kind = "",
      priority = 45,
    },
    ultisnips = { kind = "" },
    tabnine = {
      kind = "",
      priority = 50,
      ignore_pattern = "[(|,]",
    },
    emoji = { kind = "ﲃ", filetypes = { "markdown" } },
  },
```
in `compe`

To this
```
When sorting completion items before displaying them, boost each item's score based on the originating source. Each source gets a base priority of #sources - (source_index - 1), and we then multiply this by priority_weight:

score = score + ((#sources - (source_index - 1)) * sorting.priority_weight)
```
and
```
" Setup buffer configuration (nvim-lua source only enables in Lua filetype).
autocmd FileType lua lua require'cmp'.setup.buffer {
\   sources = {
\     { name = 'nvim_lua' },
\     { name = 'buffer' },
\   },
\ }
```
in `cmp`.

Here is my config
https://gist.github.com/horseinthesky/26d813d2974b27b5d142bb8a412d2ba3

It works great but it definitely much less readable now. Setting up everything about the source in the `sources` block was so easy to use and understand.

**Comment by hrsh7th** [comment]
Implemented.

**Comment by marcelarie** [comment]
> Implemented.

How does this work? :)

**Comment by lucax88x** [comment]
@marcelarie https://github.com/hrsh7th/nvim-cmp#sourcesnumbermax_item_count-type-number

**Comment by marcelarie** [comment]
> @marcelarie https://github.com/hrsh7th/nvim-cmp#sourcesnumbermax_item_count-type-number

Thanks!

**Comment by jrwrigh** [comment]
Documentation now found at `:help cmp-config.sources[n].max_item_count` (though `:help` says it can't find it, that is the tag for it in the documentation. You can always just do `:help cmp-config.sources` and search from there)

**Comment by shellheim** [comment]
I am having some problems related to priority right now. While writing css I get the snippets that form as I go and are not usable but the suggestions by the lsp are great.So, in order to use the suggestions I have to arrow down a lot which very inconvenient. The priority syntax doesn't work for me to prioritize nvim_lsp over luasnip. I have tried to fix numerous times now but nothing seems to work.

##My Suggestions 
![lsp](https://user-images.githubusercontent.com/116480892/229358442-6ee8e877-2534-45a2-85b1-c0bf41b37923.png)

**Comment by Shougo** [comment]
The feature is for each sources.
But your issue is from one source.
Another feature is needed for it.

**Comment by shellheim** [comment]
I turned off every source except nvim_lsp and the problem still occurs. Probably a problem with the css lsp. I don't know what to do at this point.

**Comment by DiegoAraujoJS** [comment]
> I turned off every source except nvim_lsp and the problem still occurs. Probably a problem with the css lsp. I don't know what to do at this point.

The thing is that cmp lets you prioritize a source over another. But as the snippet comes from (say) a language server, cmp shows all suggestions for all language servers attached to buffer and has no ordering criteria for these.
I am looking for a solution on this but cmp's sources ordering doesn't seem to point in the right direction. Maybe someone that really knows cmp could give a hint.

**Comment by shellheim** [comment]
Do you mean cmp has no ranking system as an ordering criteria??

**Comment by DiegoAraujoJS** [comment]
Yeah, but that ranking system ranks sources, and its agnostic on how it lists the results of a given source. That's why it just lists LSP results before, say snippets. But it does not make any ordering among the LSP results.

**Comment by ryan-talus** [comment]
@DiegoAraujoJS Does this mean if I have two LSP clients attached, and they're specified as two different sources in my config, the `priority` value has no impact because they are both LSPs? 

So that would be why this feels like it has no impact?

```lua
  sources = {
    { name = 'nvim_lsp', priority = -10000000000 },
    { name = 'copilot',  priority = 10000000000 },
  },
```

**Comment by m-pilia** [comment]
> (The goal is to make my LSP suggestions always appear above my Copilot suggestions)

To achieve that, I use a custom comparator based purely on source config priority:
```lua
-- Entries with higher source priority will be ranked higher
local function priority_comparator(entry1, entry2)
    -- Note that this is not efficient, as each call to `get_source_config` performs a search
    -- through the source configs in linear time
    local diff = entry1.source:get_source_config().priority - entry2.source:get_source_config().priority
    if diff > 0 then
        return true
    elseif diff < 0 then
        return false
    end
    return nil
end
```

That can be added to the config like this
```lua
        cmp.setup({
            sorting = {
                comparators = {
                    priority_comparator,
                    cmp.config.compare.offset,
                    cmp.config.compare.exact,
                    cmp.config.compare.score,
                    // ...
                },
            },
            -- ...
        })
```

By putting it first in the `comparators` table, entries from sources with higher priority will always show up above entries from sources of lower priority (in case of same priority the other comparators will be chained to break the tie as usual).
