### ISSUE TITLE
How to turn off Enter to confirm

### ISSUE THREAD

**Issue by MuseHorizon** [hrsh7th/nvim-cmp#737]
Hi,

How do you turn off enter to accept / confirm?
The similar VSCode setting would be:     "editor.acceptSuggestionOnEnter": "off"

Thanks!

**Comment by mathjiajia** [comment]
Does below work?

` ['<CR>'] = cmp.config.disabled `

**Comment by hrsh7th** [comment]
@mathjiajia is right.

**Comment by MuseHorizon** [comment]
Thanks for the quick response, I ended up just doing:

`['<CR>'] = cmp.mapping.confirm({ select = false })`
