### ISSUE TITLE
Discussion: Remove all default mapping

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-cmp#739]
I think we should remove default mapping.

I know the `cmp.config.disable` can be used but it's implicit. (The user can't see which keys are default or not.)

**Comment by hrsh7th** [comment]
If there is no dissenting opinion after a while, I will implement it as a destructive change.

**Comment by RayZ0rr** [comment]
I agree. Could you also mention in README about wiki page for `<tab>` completion? I think many users would want that and might miss it.

**Comment by hrsh7th** [comment]
It's done via https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558

**Comment by wookayin** [comment]
I would have disagreed with this proposal (see #895) but I wasn't aware of this discussion until it got merged today. I can't catch a rationale behind this change:
>  "The user can't see which keys are default or not."

This seems the only reason? But, why would this be a problem? I agree it is implicit, but IMHO it's a matter of documentation (if we maintain the default behavior "minimal" and sensible enough). Which keymaps specifically has caused a trouble?

**Comment by ambroisie** [comment]
@wookayin I personally think that a plug-in imposing default mappings is annoying as an end-user, whether that is to have a self-documenting configuration or easy to change the defaults.

I think that the balance landing somewhere between "document the recommended defaults" and "have a way to opt-in to the defaults" is a better experience for me.
