### ISSUE TITLE
Smarter completion in the middle of the word

### ISSUE THREAD

**Issue by Logarithmus** [hrsh7th/nvim-cmp#741]
Hello. Huge thanks for your wonderful project. But quite often I encounter the same problem: when completion is triggered in the middle of the word or a function name & I select a suggestion which ends with already present part of the word, neovim just duplicates this part instead of using it only once. Sorry for my awkward explanation, hope you'll understand what I'm talking about after watching a short video:

https://user-images.githubusercontent.com/29541480/149624855-0d971ad5-9f8f-4c63-b438-0ed1ff1aa367.mp4

**Comment by rhcher** [comment]
Do you check cmp.ConfirmBehavior.Replace?

**Comment by Logarithmus** [comment]
@rhcher thanks for your suggestion, now it kinda works like expected, but only for plain text buffer completion. If completion source is LSP, then for some reason it inserts instead of replacing.

https://user-images.githubusercontent.com/29541480/149628130-9130fe04-e02e-487b-9228-f3491c075ffa.mp4

**Comment by hrsh7th** [comment]
It's a bug. I've fixed.

**Comment by Logarithmus** [comment]
@hrsh7th wow, that's blazing fast! I'll check it out
