### ISSUE TITLE
Shift-Tab Remap

### ISSUE THREAD

**Issue by axieax** [hrsh7th/nvim-cmp#743]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

My config:
```lua
cmp.setup({
  mapping = {
    ["<Tab>"] = cmp_map(function(fallback)
      print("right")
      if cmp.visible() then
        cmp.select_next_item()
      else
        -- local copilot_keys = vim.fn["copilot#Accept"]()
        -- if copilot_keys ~= "" then
        --   vim.api.nvim_feedkeys(copilot_keys, "i", true)
        -- else
        --   fallback()
        -- end
        fallback()
      end
    end),
    ["<S-Tab>"] = cmp_map(function(fallback)
      print("left")
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end),
  }
})
```

Bug also reproducible with [wiki: no snippet plugin](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#no-snippet-plugin) config (the `has_words_before` function evaluates to false as expected).

### Description

Hi, it seems that there is a remapping issue with my Shift-Tab mapping, where it also calls the Tab mapping, causing an indent to the right (instead of the left from calling the fallback function).

### Steps to reproduce

Same effect in multiple filetypes:
Go to beginning of an indented line and try to unindent it with Shift-Tab.

### Expected behavior

The line becomes unindented (calling fallback mapping) only.

### Actual behavior

The tab mapping is also called, resulting the line being indented as well (further). 

### Additional context

This shows that Tab mapping is called when pressing the Shift Tab mapping:

![image](https://user-images.githubusercontent.com/62098008/149646645-8d26c0c0-8c32-4675-9c53-9256877e9f74.png)

**Comment by hrsh7th** [comment]
@axieax I think `nvim --clean` and press `<S-Tab>` will works as the same. Why do you think this is nvim-cmp's bug?

**Comment by axieax** [comment]
Oh my apologies, wasn't sure of the expected behaviour. Do you know if there is a way to unindent with normal `<S-Tab>`
