### ISSUE TITLE
Add `:CmpEnable` and `:CmpDisable` commands

### ISSUE THREAD

**Issue by VVKot** [hrsh7th/nvim-cmp#745]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

Any setup with cmp will do.

### Description

I'd want to have a `:CmpEnable` and `:CmpDisable` commands, such that `:CmpEnable` correct picks up my initial config. One use case that I have in mind is recording macros (having completions messes that up in my experience) - but maybe people have other applications for it.

### Steps to reproduce

N/A

### Expected behavior

`:CmpEnable` and `:CmpDisable` exist

### Actual behavior

No such commands as of now

### Additional context

N/A

**Comment by hrsh7th** [comment]
Please create your own command. I don't add this. Sorry.
