### ISSUE TITLE
Fallback no longer working if using vim.keymap.set

### ISSUE THREAD

**Issue by petertriho** [hrsh7th/nvim-cmp#746]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+897-g0c0469c4f

### Minimal reproducible config
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}

vim.keymap.set("i", "<CR>", function() print("hello") end, {})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

Maybe related to this issue? https://github.com/folke/which-key.nvim/pull/223

I'm using https://github.com/RishabhRD/lspactions#input and `<CR>` and `<C-c>` does not work because I'm also using `<CR>` for `cmp.mapping.confirm` and `<C-c>` for `cmp.mapping.close`

### Steps to reproduce

Type <CR> in insert mode

### Expected behavior

Should print hello

### Actual behavior

Does not print hello

### Additional context

https://github.com/hrsh7th/nvim-cmp/commit/703e915b7f0b673a37c8b92e019bd8a5d369d4e9 This commit seems to be the culprit. Fallback works with previous commit https://github.com/hrsh7th/nvim-cmp/commit/243d5f4a120580ebb171484b5a3fe15d06cf8fae

**Comment by hrsh7th** [comment]
I think this is `<silent>` related issue. I'll check it..

**Comment by nyngwang** [comment]
@hrsh7th The `<Tab>`-completion failed again after c23d810
