### ISSUE TITLE
[Feature] Optional documentation

### ISSUE THREAD

**Issue by Iamafnan** [hrsh7th/nvim-cmp#751]
Hey, is there any plan to add an optional feature in which the documentation will be toggled on a specific key like `<C-a>`?

**Comment by shri3k** [comment]
Not sure why this was closed. @Iamafnan did you ever find a solution to this? I tried looking for mapping in this [file](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/mapping.lua) but it doesn't seem to be there for us to add the toggle mapping.

**Comment by Iamafnan** [comment]
This is a duplicate issue of #674
