### ISSUE TITLE
when there are no autocomplete suggestions. Tab throws up an error

### ISSUE THREAD

**Issue by zim0369** [hrsh7th/nvim-cmp#752]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#luasnip

### Description

E5108: Error executing lua /home/zim/.config/nvim/lua/plugins/nvim-cmp.lua:27: attempt to call global 'has_words_before' (a nil
value)

### Steps to reproduce

Hitting `tab` when there are no suggestions

### Expected behavior

insert 4 spaces

### Actual behavior

Insert 4 spaces

**Comment by hrsh7th** [comment]
```
E5108: Error executing lua /home/zim/.config/nvim/lua/plugins/nvim-cmp.lua:27: attempt to call global 'has_words_before' (a nil
value)
```

You should define has_words_before because you are using it.

**Comment by zim0369** [comment]
> ```
> E5108: Error executing lua /home/zim/.config/nvim/lua/plugins/nvim-cmp.lua:27: attempt to call global 'has_words_before' (a nil
> value)
> ```
> 
> You should define has_words_before because you are using it.

I defined it but no I get this error
```
E5108: Error executing lua ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:147: Vim:E15: Invalid expression: ^[
```
