### ISSUE TITLE
✗ Failed to update hrsh7th/cmp-nvim-lsp

### ISSUE THREAD

**Issue by The-Repo-Club** [hrsh7th/nvim-cmp#755]
![image](https://user-images.githubusercontent.com/9284733/150827610-8497cccb-2696-493e-90b5-c51522f9a2ef.png)

Can not update using packer

**Comment by arpangreat** [comment]
Remove the nvim-cmp file , under packer start directory , where ever is it located , then try `:PacmanSync` it should help

**Comment by hrsh7th** [comment]
I don't use packer.nvim

packer.nvim seems to have some of the command.

**Comment by The-Repo-Club** [comment]
![image](https://user-images.githubusercontent.com/9284733/150833809-30573a0a-64df-4114-bd29-8a147ca036b0.png)

seems to be the issue

**Comment by The-Repo-Club** [comment]
fixed by `rm -rf ~/.local/share/nvim/site/pack/packer/opt/cmp-nvim-lsp` then rerunning the sync

**Comment by gegoune** [comment]
you can just do `git pull --rebase` in cop's directory rather than deleting everything and re-downloading.
