### ISSUE TITLE
No longer completes on first character

### ISSUE THREAD

**Issue by zbirenbaum** [hrsh7th/nvim-cmp#756]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+920-g7e2ce35e3-dirty and v0.7.0-dev+922-g1b6ae2dbb-dirty

### Minimal reproducible config

I copied the minimal reducible config provided and moved out my other files so that is the entirety of my neovim config and the behavior persists.

### Description

cmp completion window not properly appearing according to configuration.

### Steps to reproduce

I tested this on many different types of files. It is reproducible in pretty much anything I edit.

### Expected behavior

If keyword length is set to 1, which is the default, any character typed will trigger completions if they exist for that char.

### Actual behavior

As of the last commit addressing #754 cmp will never open a completion window after the first character typed, despite keyword length being set to 1 or left as default. It will, however, provide completions on the second character, and then update to the ones which should have been provided to the first character if I backspace.

### Additional context

I spent a couple hours trying to figure out if I was going crazy and it always worked this way, but eventually decided to fork cmp, revert the last commit, and then 'used' my forked repo with the reversion in my init.lua. The behavior reverted to expected, wherein the moment I type a character completion options are provided.

I attempted to fix the issue myself as I figure its a problem with the changes made to scheduling causing the completions not to trigger until one "completion trigger" after it is meant to, or that there is an issue with line information not being read in at the correct point, but the code is a little complex so I figured I would post this so someone more knowledgeable can take a crack.

**Comment by lewpoly** [comment]
I am also having issues. The C-Space command to trigger completion no longer works and typing a character no longer suggests completion based on letter.

**Comment by zbirenbaum** [comment]
> I am also having issues. The C-Space command to trigger completion no longer works and typing a character no longer suggests completion based on letter.

I am glad to hear it is not just me. In case you or anyone else who shares this issue and finds this post want the functionality back while we wait on a fix, rather than making a fork and reverting it yourself, you can just change:
 ```
use {
    "hrsh7th/nvim-cmp"
}
```  
to: 
```
use { 
    "zbirenbaum/nvim-cmp"
}
``` 
in your init.lua

**Comment by lewpoly** [comment]
You're an actual life saver.

**Comment by hrsh7th** [comment]
Sorry. I did a rough work...
