### ISSUE TITLE
lspkind integration

### ISSUE THREAD

**Issue by Trid-collab** [hrsh7th/nvim-cmp#76]
I have switched over to nvim-cmp today and trying to set it up cmp-nvim-lsp and cmp-luasnip and luasnip
I am using the latest neovim nightly.

I have tried to integrate lspkind with the lines found in the README

But I find doing so when I am getting the autocomplete option I am getting only the autocomplete options with symbols.
Earlier with compe I used to get the get autocomplete option-symbols- text for the symbol (like functions) - source (like LSP) without doing anything. 

How can I get that back

**Comment by hrsh7th** [comment]
README.md updated.
https://github.com/hrsh7th/nvim-cmp#how-to-show-name-of-item-kind-and-source-like-compe
