### ISSUE TITLE
Does the `buffer` source include only current one or other buffers as well?

### ISSUE THREAD

**Issue by Xunius** [hrsh7th/nvim-cmp#763]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1 Build type: Release LuaJIT 2.0.5 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Minimal reproducible config

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

### Description

Not necessarily a bug.

I'm not sure about the intended behavior regarding the `buffer` source:

It gives auto-completion suggestions for the words **in the same buffer**, but not for those in other **opened buffers**.

Is it the intended behavior for the `buffer` source, or there is a separate one for completions from other buffers?

### Steps to reproduce

1. Copy the provided Minimal reproducible config
2. Run `nvim init.vim`, wait for plugin installation
3. Check for completion in same and other buffers

### Expected behavior

Gives completion suggestions from other buffers.

### Actual behavior

Only completions from same buffer.

**Comment by gegoune** [comment]
This isn't the write repository. buffer source is separate to cmp and your question is answered in its readme: https://github.com/hrsh7th/cmp-buffer#get_bufnrs-type-fun-number

**Comment by hrsh7th** [comment]
Thank you. @gegoune is right.

**Comment by Xunius** [comment]
> This isn't the right repository. buffer source is separate to cmp and your question is answered in its readme: https://github.com/hrsh7th/cmp-buffer#get_bufnrs-type-fun-number

Thanks both! Got it solved.
