### ISSUE TITLE
Disable sorting in autocompletion for nvim-cmp

### ISSUE THREAD

**Issue by satylogin** [hrsh7th/nvim-cmp#766]
nvim-cmp does sorting by default from different sources. I was looking for a way to disable this behaviour. Our LSP does its own sorting with is much better, and the sorting that is applied on top of it by nvim-cmp destroys all the benefit the we get from our lsp.

**Comment by hrsh7th** [comment]
Do your LSP server returns sortText property?
If so, you can change the sorting comparators by yourself.

**Comment by satylogin** [comment]
Please correct me if I am wrong, bu I believe you are referring to https://github.com/hrsh7th/nvim-cmp/blob/d93104244c3834fbd8f3dd01da9729920e0b5fe7/lua/cmp/config/compare.lua#L72

Out of curiosity, where does the score param comes from in: https://github.com/hrsh7th/nvim-cmp/blob/d93104244c3834fbd8f3dd01da9729920e0b5fe7/lua/cmp/config/compare.lua#L24

I couldn't find it in lsp specification: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem

**Comment by hrsh7th** [comment]
The score is computed by nvim-cmp itself.
The nvim-cmp will sort items by https://github.com/hrsh7th/nvim-cmp/blob/d93104244c3834fbd8f3dd01da9729920e0b5fe7/lua/cmp/config/default.lua#L47

You can change the comparators order. (I think you should move up the `sort_text` sorter` than `score` soter.
