### ISSUE TITLE
Basic configuartion with html. Autocomplete is not working

### ISSUE THREAD

**Issue by IgnFed** [hrsh7th/nvim-cmp#767]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

``` lua
 -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      end,
    },
    mapping = {
      ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
      ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
      ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
      ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
      ['<C-e>'] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
      }),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' }, -- For vsnip users.
      -- { name = 'luasnip' }, -- For luasnip users.
      -- { name = 'ultisnips' }, -- For ultisnips users.
      -- { name = 'snippy' }, -- For snippy users.
    }, {
      { name = 'buffer' },
    })
  })

  -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline('/', {
    sources = {
      { name = 'buffer' }
    }
  })

  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

  -- Setup lspconfig.
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
  require'lspconfig'.html.setup {
    capabilities = capabilities
  }
```

### Description

Autocomplete doesn't work with html.
i've copy and pasted the basico configuration in the readme

``` lua
  ...
  require'lspconfig'.html.setup {
    capabilities = capabilities
  }
```

and this is it is supposed to work and provide autocomplete when a tag is opened.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/70576040/151678981-0e8cc5ea-6271-4e92-aa0d-b481bcd7d1e0.png)
![image](https://user-images.githubusercontent.com/70576040/151678986-0ba480b8-9d5e-41e8-b30b-56689bb93cd7.png)

## Image 1:
   * Basic structure for configurations, in "init.lua" i'm just requiring the plugins folder

## Image 2:
   * Every folder has a "init.lua" file

In cmp-config/init.lua you just need to copy and paste the basic configuration written in the README
And replace this part:

``` lua
  -- Setup lspconfig.
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
  require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
    capabilities = capabilities
  }
```

with this:

``` lua
  -- Setup lspconfig.
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
  require'lspconfig'.html.setup {
    capabilities = capabilities
  }
```

### Expected behavior

Autocomplete work when tag is open

![image](https://user-images.githubusercontent.com/70576040/151679191-fd2bc1b3-8f33-4e6b-a944-298a4d172475.png)

### Actual behavior

Autocomplete is not working
![image](https://user-images.githubusercontent.com/70576040/151679335-1eb0ca89-db6d-445c-a007-ac7bc71b4e4e.png)

### Additional context

this is displayed when i open an html file
![image](https://user-images.githubusercontent.com/70576040/151679249-d9c4d408-d0d7-4d7d-b313-0b7c6576400f.png)

Here is the LspInfo:

![image](https://user-images.githubusercontent.com/70576040/151679256-2a9ce796-e063-4fb8-a580-059f2c91b00a.png)

**Comment by tzachar** [comment]
Looks like you have issues with your language server which are not related to `cmp`.
You can see in your LspInfo that you have 0 servers running, and when opening the html file you got 'Client 1 quit', which means your Lsp server is dead.

**Comment by hrsh7th** [comment]
`0 client(s) attached to this buffer.`
