### ISSUE TITLE
Inserting "<Plug>(cmp.u.k.recursive: )" when using tab in insert mode

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-cmp#770]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

This is the code I'm using for tab completions, I'll try to get a minimal example here soon.

https://github.com/ChristianChiarulli/nvim/blob/a5f5fb81b652fde891a6abd228cf3e9e878ea218/lua/user/cmp.lua#L132

### Description

Since this commit: https://github.com/hrsh7th/nvim-cmp/commit/f4bb6ffdb1d5377be93283ff087a5ff97e23524f

I am unable to use the <tab> key in insert mode, `<Plug>(cmp.u.k.recursive: )` is inserted instead

### Steps to reproduce

open any filetype and press tab in insert mode

### Expected behavior

tab behaves normally in insert mode

### Actual behavior

`<Plug>(cmp.u.k.recursive: )` is inserted instead

**Comment by ChristianChiarulli** [comment]
seems to be a copilot thing: https://github.com/hrsh7th/nvim-cmp/issues/459, closing

**Comment by jimcornmell** [comment]
Hi I got this with latest master, not using copilot.  Only other difference is I get this when I press enter.  "<Plug>(cmp.u.k.recursive:)".

To fix I used the following which seemed to do the trick:

:LvimCacheReset
and
:LvimUpdate.

Weird!

**Comment by zmre** [comment]
Thanks @jimcornmell -- I also don't use copilot and had this problem. But I also don't use LunaVim so don't have that LvimCacheReset command. But this did remind me that it could be an issue with the Impatient plugin. For me, calling `:LuaCacheClear` after a fresh update solved the issue. Hope this helps the next person.

**Comment by jimcornmell** [comment]
Started doing this again for me today, I've removed all plugins and then added one at a time until the error reappeared.  It started to go wrong again with the following added to my config:

```
{
 "tpope/vim-eunuch",
 event = "BufRead",
},
```

**Comment by Leandros** [comment]
Still happening for me with the latest nvim-cmp.

**Comment by YodaEmbedding** [comment]
This happens whenever I press `<S-Tab>` in INSERT mode. The infinite recursion can be stopped by pressing `<C-c>`. I have [`copilot.lua`](https://github.com/zbirenbaum/copilot.lua) and [`copilot-cmp`](https://github.com/zbirenbaum/copilot-cmp) installed.

**Comment by hrsh7th** [comment]
Sorry. I lost this issue.

https://github.com/hrsh7th/nvim-cmp/issues/770#issuecomment-1095103398

The above comment is informative. I'll try to check this.

Other comments, I can't guess anything. Sorry.

**Comment by hrsh7th** [comment]
I tried with `tpope/vim-eunuch` but it doesn't display recursive broken mapping.

**Comment by Leandros** [comment]
The combination of a `<S-Tab>` `nvim-cmp` mapping, and the `vim-vsnip` mapping creates this behavior:

```vimscript
" nvim-cmp
lua <<EOF
local cmp = require 'cmp'
cmp.setup({
  snippet = {
    expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end,
  },
  -- Installed sources
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  }, {
    { name = 'buffer' },
    { name = 'path' },
  }),

})
EOF

" vim-vsnip
" Expand
imap <expr> <C-n>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-n>'
smap <expr> <C-n>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-n>'

" Jump forward or backward
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```

**Comment by Leandros** [comment]
And this seems to fix it for me:

```lua
cmp.setup({
  -- setup ...
  mapping = {
    -- ....
    ['<S-Tab>'] = function(fallback)
      local is_jumpable = vim.api.nvim_cmd({
        cmd = "echo",
        args = { "vsnip#jumpable(-1)" },
      }, { output = true })

      if cmp.visible() then
        cmp.select_prev_item()
      elseif is_jumpable == "0" then
        return
      else
        fallback()
      end
    end,
  },
})
```
