### ISSUE TITLE
How to change ghost text color

### ISSUE THREAD

**Issue by Leiyi548** [hrsh7th/nvim-cmp#778]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+997-g21cdecc8e

### Minimal reproducible config

..

### Description

I want change ghost text color.But I found that I couldn't do it.
![image](https://user-images.githubusercontent.com/76139422/152641812-06dcb6d2-aba4-4514-b946-51ffffdb6c92.png)
I don't want use comment color.
I would like a custom color

### Steps to reproduce

。

### Expected behavior

。

### Actual behavior

。

### Additional context

。

**Comment by hrsh7th** [comment]
See this documentation.
https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L478

**Comment by Leiyi548** [comment]
@hrsh7th  Can you write an example? I don't know how to use it. Thank you.

**Comment by Bekaboo** [comment]
> @hrsh7th Can you write an example? I don't know how to use it. Thank you.

    experimental = { ghost_text = {hl_group = 'NameOfHighlightGroup'} },

**Comment by HarshalRathore** [comment]
hi how can we change the font weight for the ghost text i want the ghost text to be _italic_ currently it looks like this. 
![image](https://github.com/user-attachments/assets/ef9f3af9-aa7a-4275-8187-b49827f62afd)
