### ISSUE TITLE
When used with nvim-autopairs, completion confirmed by typing '(' leads to two pairs of parenthesis being inserted

### ISSUE THREAD

**Issue by dmbfm** [hrsh7th/nvim-cmp#780]
This seems to happen because nvim-autopairs the `on_confirm_done` event. 

Let's stay I want to complete a function named `somefunc`.  I type `some`, go to the `somefunc` item in the completion menu, and then type the character `(`. What seems to happen is that the `on_confirm_done` event is called before the `(` character is inserted. Then nvim-autopairs does not see any parenthesis after the function name and inserts a pair `()`. Next, the parenthesis I type is inserted and paired by nvim-autopairs, and I end up with two pairs of parenthesis, i.e., `somefunc(())`.

Now, I want to be able to both complete a function by typing `(` or by using `<C-y>` or `<cr>`. 

As a tentative hack to fix this, I have added an option to suppress the `on_confirm_done` event on the `core.confirm` function:
https://github.com/dmbfm/nvim-cmp/blob/06b6471dce6783faa390a0519f53f603fce3d773/lua/cmp/core.lua#L432. The `core.key_map` function sets this to true when calling `core.confirm`.

I think this is pretty much a hack, and I haven't created a PR because probably this is not the "correct" way to fix this. 

Also, maybe this issue is too specific to my use case and most people have no need for such modifications.

**Comment by yvesnrb** [comment]
I have the exact same problem! It's pretty annoying. I have now taken to using `<C-y>` to confirm completions, but I still slip up and hit the open parenthesis by accident on occasion, causing the double parenthesis problem. An option to suppress the confirm done event would be very nice indeed.

**Comment by Shougo** [comment]
It seems nvim-autopairs problem instead of nvim-cmp.

**Comment by hrsh7th** [comment]
I think the duplicate brackets were inserted by nvim-auopairs. What should I do in that situation?

**Comment by dmbfm** [comment]
@hrsh7th Indeed it is inserted by nvim-autopairs... because they listen to the `on_confirm_done` event. Is there another way they could do this? I'm asking because I don't know that much about the internals of nvim-cmp, but I can try creating a PR for nvim-autopairs if I figure out a way better way to do this.

**Comment by hrsh7th** [comment]
It seems possible to add whether core: confirm was called because of commitCharacter.

**Comment by hrsh7th** [comment]
```
core:confirm({
  commit_character = nil or '(' or '.'
})
```

**Comment by dmbfm** [comment]
Nice! I will try a solution on nvim-autopairs then. Thanks!
