### ISSUE TITLE
Can <tab> be used to complete all common characters within the completion menu?

### ISSUE THREAD

**Issue by felix-clark** [hrsh7th/nvim-cmp#785]
_meta: I did not think the Bug Report issue template was relevant here, since this is more of a question / feature request and isn't specific to my config. I have not found this feature discussed in issues or the wiki, and the FAQ link in the README is broken. Apologies if I have missed something, I am a little surprised to have not found this because it seems like it would be common._

The use-case here is for expediting completion when there are a large number of possible results remaining but they share a long common stem. For instance, we might have `my-very-long-prefix` which is shared by a number of symbols `my-very-long-prefix.foo`, `my-very-long-prefix.bar`, etc. Typing out `my-v` brings up a window where each possible result begins with `my-very-long-prefix`, and it can save a lot of typing if one could simply hit `<tab>` to autocomplete to the shared prefix, at which point one could continue typing to narrow down the possibilities. This is not dissimilar to bash terminal completion, where pressing tab will complete the common prefix of all remaining valid completions.

Is this feature possible right now, and if so can I find instructions on how to set it up? (I thought this feature was present in `nvim-compe` but perhaps I am wrong)

**Comment by hrsh7th** [comment]
Hm...interesting.
I'll try to implement it.

**Comment by hrsh7th** [comment]
BTW, You can type `mybar` for such situation.
