### ISSUE TITLE
Completion doesn't input any text with `odin language server`

### ISSUE THREAD

**Issue by ap29600** [hrsh7th/nvim-cmp#798]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit


" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

" Setup Odin Language Server
lua << EOF
local lspconfig = require 'lspconfig'
local configs = require 'lspconfig.configs'
local util = require 'lspconfig.util'

if not configs.ols then
  configs.ols = {
    default_config = {
      cmd = { 'ols' };
      filetypes = { 'odin' };
      root_dir = util.root_pattern('ols.json');
      settings = {};
    };
  }
end

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

lspconfig.ols.setup{ capabilities = capabilities }
EOF
```

### Description

Triggering autocompletion on a non-function symbol does not insert the completion text, instead it just deletes the word that triggered the completion

### Steps to reproduce

with the provided minimal config, create an Odin project.
(unfortunately `Odin` is not widely packaged, here are the basic steps to build it and `ols`)

`git clone https://github.com/odin-lang/Odin`
`cd Odin && make; cd ..`
`git clone https://github.com/DanielGavin/ols`
with odin binary in `$PATH`: 
`cd ols; build.sh`

with `ols` binary in `$PATH`:
create a folder with the following files:

`test.odin`
```odin
package test
import "core:strings"
some_function :: proc () {}
main :: proc () {
  stri
  // some
}
```
`ols.json`
```json
{
  "collections": [
    { "name": "core", "path": "/path/to/Odin/core" },
    { "name": "vendor", "path": "/path/to/Odin/vendor" }
  ],

  "enable_hover": true,
}
```

in insert mode, try to autocomplete `strings` by pressing `<C-Space><C-n>`.
Try the same on `some`.

### Expected behavior

`stri` autocompletes to `strings`, `some` autocompletes to `some_function`

### Actual behavior

`stri` is simply deleted, `some` autocompletes correctly.

### Additional context

I have confirmed that this doesn't happen with other autocompletion engines (I personally only tested `CoC`, others report no issues on editors other than vim).

since this only happens on certaion completion elements and only with `ols`, it's likely that some edge case is being triggered by possibly missing information from the server, but I haven't been able to confirm this because I'm not sure how to get a debug print of the data sent by the server.

**Comment by hrsh7th** [comment]
Could you paste the LSP response and requested line & cursor?

You can get the response with the following steps.

1. Open [`lua/cmp/source.lua:L303`](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/source.lua#L303)
2. Add `print(vim.inspect(response))`

**Comment by FollieHiyuki** [comment]
Seems like the same behavior as https://github.com/hrsh7th/nvim-cmp/issues/615#issuecomment-1003152088 if I'm not mistaken.

**Comment by ap29600** [comment]
yes, it looks similar, but this time selecting the text a second time makes no difference.

here's the result of `vim.inspect(response)`:
```{
  isIncomplete = true,
  items = { {
      additionalTextEdits = {},
      command = {
        arguments = {},
        command = "",
        title = ""
      },
      deprecated = false,
      detail = "strings",
      documentation = "",
      insertText = "",
      insertTextFormat = 1,
      kind = 9,
      label = "strings",
      tags = {}
    }, {
      additionalTextEdits = {},
      command = {
        arguments = {},
        command = "",
        title = ""
      },
      deprecated = false,
      detail = "string",
      documentation = "",
      insertText = "",
      insertTextFormat = 1,
      kind = 14,
      label = "string",
      tags = {}
    }, {
      additionalTextEdits = {},
      command = {
        arguments = {},
        command = "",
        title = ""
      },
      deprecated = false,
      detail = "cstring",
      documentation = "",
      insertText = "",
      insertTextFormat = 1,
      kind = 14,
      label = "cstring",
      tags = {}
    } }
}
```
it seems that the lsp is sending empty `insertText` fields

**Comment by ap29600** [comment]
It looks like this is a problem with the specific server, I'll close for now.

**Comment by hrsh7th** [comment]
I'll improve the empty insertText handling. Thank you.

**Comment by ap29600** [comment]
I had a look at the specification and it seems `label` should be used if it's empty:
```
	/**
	 * A string that should be inserted into a document when selecting
	 * this completion. When `falsy` the label is used as the insert text
	 * for this item.
	 *
	 * The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example
	 * `con<cursor position>` and a completion item with an `insertText` of
	 * `console` is provided it will only insert `sole`. Therefore it is
	 * recommended to use `textEdit` instead since it avoids additional client
	 * side interpretation.
	 */
	insertText?: string;
```

Anyways thanks for the good work, it's seriously impressive!

**Comment by hrsh7th** [comment]
The spec is not support `''` as `falsy` / `empty` field. But the typical language server is implemented by TS/JS. So I think we should support it.
https://github.com/microsoft/language-server-protocol/issues/1222
