### ISSUE TITLE
Support source priorities

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-cmp#8]
This can be achieved by using the `sortText` of each completion item, but seems a bit hacky.
I think that supporting a general ranking between sources is more flexible.

**Comment by hrsh7th** [comment]
I think we should add https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/menu.lua#L92 as option.

**Comment by hrsh7th** [comment]
The nvim-cmp will sort items as globally. But it has a `priority bonus` so we can control source priority by it.

And sorting logic fully customizable.

```
require'cmp'.setup {
  sorting = {
    comparators = {
      function(e1, e2)
        ...
      end
    }
  }
}
```
The default config is https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/default.lua#L49

**Comment by tzachar** [comment]
And the `score` is between 0 and 1?

**Comment by hrsh7th** [comment]
No. The score is upper 1 value (0 means `no match` instead).

**Comment by tzachar** [comment]
So the solution is to just mention the default priority scheme in the README.

**Comment by tzachar** [comment]
Cool. See #12
