### ISSUE TITLE
what does the fallback function passed to cmp.mapping do?

### ISSUE THREAD

**Issue by bryceyang** [hrsh7th/nvim-cmp#805]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Minimal reproducible config
```lua
 ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
                luasnip.expand_or_jump()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end, {"i", "s"})
```

### Description

when the mapping function of tab reached the last else branch, which execute the fallback function,  unexpected content are inserted in insert mode when i press tab in an empty line. see:

https://user-images.githubusercontent.com/9302617/154398284-f5457074-d991-41ac-be68-7148ef5baea5.mp4

when I comment out the fallback else branch, pressing tab does nothing.

### Steps to reproduce

use the tab mapping in the above, into insert mode in an empty line, and press tab.

### Expected behavior

tab itself is inserted.

### Actual behavior

`<Plug>(cmp.u.k.recursive:   )` is inserted

**Comment by bryceyang** [comment]
turns out it is an related issue with auto mapping of copilot.  sorry for the trouble, closing this issue now.

**Comment by Bekaboo** [comment]
have the same problem
