### ISSUE TITLE
:ls list is removed when trying to delete a buffer

### ISSUE THREAD

**Issue by yusuphgammut** [hrsh7th/nvim-cmp#807]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0

### Minimal reproducible config

``` lua
-- Setup nvim-cmp.
local cmp = require'cmp'

local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

cmp.setup({
  snippet = {
      -- REQUIRED - you must specify a snippet engine.
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
      end,
    },
  mapping = {
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif vim.fn["vsnip#available"](1) == 1 then
        feedkey("<Plug>(vsnip-expand-or-jump)", "")
      elseif has_words_before() then
        cmp.complete()
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function()
      if cmp.visible() then
        cmp.select_prev_item()
      elseif vim.fn["vsnip#jumpable"](-1) == 1 then
        feedkey("<Plug>(vsnip-jump-prev)", "")
      end
    end, { "i", "s" }),

    ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
    ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
    ['<C-e>'] = cmp.mapping({
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    }),
    -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
  },

  -- Use lsp, buffer, and path sources in completion.
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  }, {
    { name = 'buffer' },
  }, {
    { name = 'path' },
  })
})

-- Use buffer source for `/` search (won't work with `native_menu` enabled).
cmp.setup.cmdline('/', {
  sources = {
    { name = 'buffer' }
  }
})

-- Use cmdline & path source for ':' commands (won't work with `native_menu` enabled).
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})
```

### Description

When I want to delete a group of buffers I usually type `:ls` to display the list of opened buffers and, with the list still visible, I type `:bd` followed by the list of buffer numbers I want to delete, separated by spaces, e.g. `:bd 1 7 12`. For this to work, it's important that the list of buffers displayed by the `:ls` command stays visible while I'm typing the `:bd` command and the number of the buffers I want to delete.

The native Vim/Neovim behavior keeps the list visible. However nvim-cmp changes this behavior and makes the list disappear when I try to type the `:bd` command. I think it's better to keep the list visible (while keeping nvim-cmp completion) given it is closest to the native Vim/Neovim behavior.

### Steps to reproduce

1. Add the above configuration to Vim's configuration.
2. Comment or remove the `cmp.setup.cmdline(':', {})` section in the configuration.
3. Restart Neovim.
4. Open at least 5 buffers.
5. Type `:ls` to show the list of opened buffers.
6. Type `:bd` followed by 3 buffer numbers.
7. Note that the list stays visible while performing step 6.
8. Uncomment or add the `cmp.setup.cmdline(':', {})` section in the configuration.
9. Follow steps 2 to 6 again.
10. Note that the list disappears when performing step 6.

### Expected behavior

The list displayed by `:ls` stays visible when typing the `:bd` command and the buffer numbers to delete.

### Actual behavior

The list displayed by `:ls` disappears when typing the `:bd` command.

### Additional context

Native Neovim behavior:
<img width="461" alt="Screen Shot 2022-02-18 at 8 36 50 AM" src="https://user-images.githubusercontent.com/12637787/154700406-bc3c5395-1ea7-406d-8039-4206dc8c0c96.png">

Nvim-cmp behavior:
<img width="474" alt="Screen Shot 2022-02-18 at 8 40 47 AM" src="https://user-images.githubusercontent.com/12637787/154700443-690fb14d-c246-4ab0-acca-a5b41be0d8a0.png">

**Comment by hrsh7th** [comment]
Dou you know other cmdline completion plugin that supported it?
I think it's impossible.

**Comment by yusuphgammut** [comment]
I don't TBH. That's bad news. But at least I can continue using the plugin in the buffer and "/" commands.
