### ISSUE TITLE
Conditionally enabling completion issue

### ISSUE THREAD

**Issue by CrossR** [hrsh7th/nvim-cmp#812]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1126-gfc7fc14bd

### Minimal reproducible config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'lervag/vimtex'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  enable = function()
    return vim.bo.filetype ~= "tex" or
    vim.fn["vimtex#syntax#in_mathzone"]() ~= 1
  end,

  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

Test file:

```tex
\section{Test Section}

This is just some test text, to populate the buffer completion with something.

\subsection{Stuff should work here...}

\begin{equation}
    Except, stuff shouldn't work on this line: 
    \label{eq:test}
\end{equation}
```

### Description

This could be a misunderstanding of mine of how this should be implemented, but I was attempting to implement [this](https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disabling-completion-in-certain-contexts-such-as-comments) from the wiki, but for math mode in LaTeX. However, I seem to always get completion, regardless of the current context.

Have I made a mistake in the configuration, or is there something more happening? I'm a bit rusty with my lua so I wouldn't be surprised if I'd just missed something in the lua, or if I've misunderstood from the wiki page how this should be implemented.

### Steps to reproduce

`nvim -u minimal.vim test.tex`.

Go into insert mode on line 3 or 4 or 6 and get completion from the buffer for items (as expected).
Go into insert mode on line 8 (inside math mode context), but still get completions.

Try `:lua print(vim.bo.filetype ~= "tex" or vim.fn["vimtex#syntax#in_mathzone"]() ~= 1)` and it prints the expected result (true on lines 3/4/6, false on line 8).

### Expected behavior

I'd expect no completion at all inside of the equation environment on line 8.

### Actual behavior

I still get completion inside the math environment, despite it being disabled there.

**Comment by hrsh7th** [comment]
Your issue was easy to debug. thank you.
By the way, the problem was simple. Use `enabled` instead of `enable`.

**Comment by CrossR** [comment]
🤦 Sorry for the clutter!
Thanks for the help.
