### ISSUE TITLE
Use Tab to scroll forward s-tab backwards and select and confirm item after timeout

### ISSUE THREAD

**Issue by sollymay** [hrsh7th/nvim-cmp#814]
Essentially been looking for a way to not have to press anything in order to confirm completion (as most modern text editors do: SublimeText/VS Code, etc), were you start typing and as soon as the completion options are shown, you get one to two seconds to go through the options and if you are still pressing either tab or s-tab it will let you navigate through the options until you stop pressing the forward/backwards keys. At that point, the option under selection will be completed.

I remember nvim-compe had a function to achieve this, but have not been able to achieve this behavior with nvim-cmp, even looking at the examples. Essentially Tab can be uses to move forward/backwards (shift Tab) and if a brief time goes through without user input, option under cursor is automatically completed.

Am I missing something?

**Comment by Zawng** [comment]
I'm trying either, do you find some way to cancel the cmp jumps?

**Comment by hrsh7th** [comment]
You can use `cmp.mapping.confirm({ select = true })`.
