### ISSUE TITLE
¿How can I cancel all cmp jumps?

### ISSUE THREAD

**Issue by Zawng** [hrsh7th/nvim-cmp#816]
Are there some ways to disable jumps?
Example:
I only want to get a snippet and nothing more, but if I press tab in another section the cmp jumps
![2022-02-25-08-19-53](https://user-images.githubusercontent.com/95452787/155722173-1941fc70-308f-4261-bc7e-db113f72544d.gif)

My CMP [config](https://github.com/Zawng/Neovim/blob/feature/vsnip/lua/cmpConfig/init.lua)

**Comment by hrsh7th** [comment]
What is the snippet engine are you using?

**Comment by Zawng** [comment]
vsnip

**Comment by Zawng** [comment]
or luasnip, I could use both

**Comment by hrsh7th** [comment]
I think it is a matter of personal preferences. I will add an option to the vim-vsnip.

**Comment by Zawng** [comment]
ty <3

**Comment by hrsh7th** [comment]
You can set `g:vsnip_deactivate_on = g:vsnip#DeactivateOn.OutsideOfCurrentTabstop`
