### ISSUE TITLE
mapping.confirm() seems to remove next word after cursor

### ISSUE THREAD

**Issue by sentriz** [hrsh7th/nvim-cmp#818]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.6.1

### Minimal reproducible config

(identical to reproduction config, but using gopls)

```diff
49c49
< require'lspconfig'.cssls.setup {
---
> require'lspconfig'.gopls.setup {
```

### Description

when using mapping.confirm() bound to a key like <cr>, it deletes the next word ahead of it if there's no space

### Steps to reproduce

given the input with cursor `|`

```
func a(one string, |three string) {}
```

type `two str<cr>` 

### Expected behavior

we get something like 

```
func one(one string, two string|three string) {}
```

### Actual behavior

we get
```
func one(one string, two string| string) {}
```
where the 3rd argument name has been removed

### Additional context

here is a video of it in action

https://user-images.githubusercontent.com/6832539/156033647-8d1d991d-a70d-4ba0-8ef7-bced535ffd82.mp4

sorry if this has been document already but I couldn't find it. try using `behavior = cmp.ConfirmBehavior.Insert` but it didn't seem to work. thanks!!

**Comment by arsham** [comment]
See [this](https://github.com/hrsh7th/nvim-cmp/issues/706#issuecomment-1044256922).

**Comment by sentriz** [comment]
@arsham aha! thank you :)
