### ISSUE TITLE
Support Vim script plugins

### ISSUE THREAD

**Issue by jbarik** [hrsh7th/nvim-cmp#82]
This is a question and not an issue?

I've been using nvim-compe. I could use vim-lsp(https://github.com/prabirshrestha/vim-lsp) by specifying "let g:compe.source.vim_lsp = v:true". 

I didn't find anything similar in the doc for nvim-cmp.

Thank you for your effort and commitment to write great plugins

**Comment by hrsh7th** [comment]
I've implemented Vim script plugin.
https://github.com/hrsh7th/nvim-cmp/commit/6173796b2b7b9fff8c951b84425ff33cfd26e42d
