### ISSUE TITLE
cmp gets stuck when completing commands starting with `!`

### ISSUE THREAD

**Issue by Bekaboo** [hrsh7th/nvim-cmp#821]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7.0--dev

### Minimal reproducible config

```
cmp.setup({
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end
    },
    sources = {
        {name = "nvim_lsp"}, {name = "path"},
        {name = "spell", max_item_count = 5},
        {name = "buffer", max_item_count = 10},
        {name = "vsnip"}, {name = "calc"}, {name = "emoji"}
    },
})

-- Use buffer source for `/`.
cmp.setup.cmdline("/", {sources = {{name = "buffer"}}})

-- Use cmdline & path source for ':'.
cmp.setup.cmdline(":", {
    sources = {
        {name = "path"},
        -- Do not show completion for words starting with '!' (huge lag, why?)
        {name = "cmdline"},
    }
})
```

### Description

https://user-images.githubusercontent.com/76579810/156193043-008b26cf-8d44-44e8-b9d7-606aab728438.mp4

I typed `!` at 00:02 and `cmp` did not reply until 00:13, during this time I could do nothing in nvim, not even quit it. 
After `cmp` returned the result, the huge lag still exists.

### Steps to reproduce

1. Type `!` in cmdline with `nvim-cmp` loaded and use `cmp-cmdline` as source

### Expected behavior

`cmp` should return completion for commands with `!` in a faster speed, or just simply disable itself temporarily when meets `!`, or add a timeout option to prevent searching that spends too long time.

### Actual behavior

When typing `!` in the cmdline with `cmp-cmdline` as source, `cmp` gets extremely slow and stucks the whole process for at least 10s.
This can happen when `!` appears at the beginning or the end of a word or appears alone.
This bug exists in both `dev` and `main` branches.
Maybe something wrong happens when searching for completions from `cmp-cmdline`?

**Comment by Shougo** [comment]
You should change `completion.keyword_length` value in command line completion.

https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L387

I think the value is 1.

**Comment by Bekaboo** [comment]
This configuration might help in most cases:
```
cmp.setup.cmdline(':', {
  sources = {
    {name = 'path'},
    -- Do not show completion for words starting with '!' (huge lag, why?)
    {name = 'cmdline', keyword_pattern = [[\!\@<!\w*]]},
  }
})
```
but if you type <Space> after the exclamation, `cmp` still gets stuck.

**Comment by steveclarke** [comment]
I'm having the same problem. I notice that you seem to be using WSL2, like me. Since WSL mixes in the Windows path with the WSL path, I think the plugin is attempting to enumerate every files in my Windows path. I had cmp-path enabled as well, and when I waited long enough for the long completion list to show after typing `:!` it would show Windows .dll files!

**Comment by Shougo** [comment]
`:!` collects executable files and dll files are executable in Windows...

**Comment by steveclarke** [comment]
> `:!` collects executable files and dll files are executable in Windows...

Yes I should have clarified - it seems to enumerate every executable in my Windows path that is shared with WSL2. I'll look through the code to see if there's a way to prevent the plugin from enumerating any path that starts with C;\, D:\, etc.
