### ISSUE TITLE
How to get rid of the results from a certain LSP in the completion menu?

### ISSUE THREAD

**Issue by nyngwang** [hrsh7th/nvim-cmp#822]
As title. I'm using both `pyright` and `pylsp` (both are documented in the `nvim-lspconfig`). The reason why I'm using two LSPs for python are:

- Current only `pyright` supports PDM. I want to use PDM.
- Currently only `pylsp` supports `vim.lsp.buf.formatting()`, and `pyright` does NOT.

OK, so here I just want to show the results of `pyright` and get rid of those from `pylsp`. So basically `pylsp` is just a formattor. Could you please help?

Here is some of my settings I thought it should work:

**pylsp**:
```lua
M = {
  -- here I already removed the `require('cmp_nvim_lsp')...`, but the results still contain those from `pylsp` :(
  autostart = true,
  on_attach = function (client, bufnr)
    require('lsp_config.common_setup')(client, bufnr)
    if (client.resolved_capabilities.document_formatting) then
      vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
    end
  end
}

return M
```

**pyright**:
```lua
M = {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  autostart = true,
  on_attach = function (client, bufnr)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
    require('lsp_config.common_setup')(client, bufnr)
  end
}

return M
```

---

**Screenshots**:

<img src="https://user-images.githubusercontent.com/24765272/156208940-d5ad7ed7-12bb-4fc0-abaa-7693f1117357.png" width="400">

**Comment by Shougo** [comment]
https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

> pylsp.plugins.jedi_completion.enabled | boolean | Enable or disable the plugin. | true
-- | -- | -- | --

I think you need to disable it.

**Comment by nyngwang** [comment]
To @Shougo: Many thanks for the link!

**Comment by nyngwang** [comment]
@Shougo: May I also ask you where should I put these config settings? Should I put them in the pylsp `setup {  }` of nvim-lspconfig?

**Comment by nyngwang** [comment]
Thank you! During the waiting I found this too: https://neovim.discourse.group/t/pylsp-config-is-not-taken-into-account/1846/2?u=nyngwang hope this will help the others who find this.

**Comment by hrsh7th** [comment]
You can add the `client.server_capabilities.completionProvider = false`

**Comment by nyngwang** [comment]
@hrsh7th: Thank you a lot!
