### ISSUE TITLE
[Question] How to get completion items from the return object? (E.g. in pyright)

### ISSUE THREAD

**Issue by nyngwang** [hrsh7th/nvim-cmp#823]
As title. Here is the screenshot to clarify what I meant:

I expect the completion menu will show items including `status_code`, which is one field from `requests.get()`.

<img src="https://user-images.githubusercontent.com/24765272/156299548-bf9127f5-b017-4158-ada7-fcf3385f9718.png" width="500">

this is my configuration for `pyright`:

```lua
M = {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  autostart = true,
  -- handlers = {
  --   ['textDocument/publishDiagnostics'] = function () end
  -- },
  on_attach = function (client, bufnr)
    require('lsp_config.common_setup')(client, bufnr)
  end,
  settings = {
    python = {
      analysis = {
        useLibraryCodeForTypes = true
      }
    }
  }
}

return M
```

And I really need to apologize in advance if this is not appropriate to be asked here. But it seems that the maintainer of nvim-lspconfig doesn't like these kind of stupid questions being asked there.

**Comment by Shougo** [comment]
I think it takes time to get LSP candidates.

**Comment by nyngwang** [comment]
@Shougo: You mean I have to wait long enough to see the item get shown?

**Comment by hrsh7th** [comment]
You should ask it to pyright devlopper.

**Comment by nyngwang** [comment]
I migrated to pylsp many days ago. After some re-check today pylsp can gracefully work without this problem:

<img src="https://user-images.githubusercontent.com/24765272/159243957-dbe3f904-42e8-40f4-a9ac-2d36dddbfabe.png" width="600">

**Comment by crates51** [comment]
> I migrated to pylsp many days ago. After some re-check today pylsp can gracefully work without this problem:
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/24765272/159243957-dbe3f904-42e8-40f4-a9ac-2d36dddbfabe.png">

Hello There @nyngwang!

Do you know how to hide those function parameters? i also use pylsp as python server

![image](https://user-images.githubusercontent.com/42578442/207540392-eaffbef4-7215-44a7-a44f-5a13b95dd215.png)

**Comment by nyngwang** [comment]
@crates51 Roger that. I have added your question to my todo list, will notify you once I get the answer. Will tag you then. While you should still try your best to find the answer since I'm busy these days.

**Comment by crates51** [comment]
I kinda find something, formatting the results by removing the parantheses manually, i dont think its the best option, but is the only one i found; like so:

    formatting = {
        format = lspkind.cmp_format({
          --maxwidth = 50,
          with_text = true,
          menu = {
            buffer = "[buf]",
            nvim_lsp = "[LSP]",
            nvim_lua = "[api]",
            path = "[path]",
            luasnip = "[snip]",
            gh_issues = "[issues]",
            tn = "[TabNine]",
          },
          before = function (entry, vim_item)
            local word = entry:get_insert_text()
            word = word:gsub('%b()', '')
            vim_item.abbr = word
            return vim_item
          end
        })
    },

(The before section)

> @crates51 Roger that. I have added your question to my todo list, will notify you once I get the answer. Will tag you then. While you should still try your best to find the answer since I'm busy these days.

**Comment by zippeurfou** [comment]
@crates51 Just wondering if you have come up with something functional. I am facing same issues sadly.

**Comment by crates51** [comment]
> @crates51 Just wondering if you have come up with something functional. I am facing same issues sadly.

Hello there,

Indeed i found something; i will respond later this day, but the idea is to use two lsp servers: pylsp(for errors diagnostic) and pyright(for everything else)

**Comment by crates51** [comment]
Actually i have some time now:

```
local pyright_handlers =  {
  ["textDocument/publishDiagnostics"] =  function() end,
  ["textDocument/hover"] =  vim.lsp.with(vim.lsp.handlers.hover, {border = "single", max_width = 100}),
  ["textDocument/signatureHelp"] =  vim.lsp.with(
    vim.lsp.handlers.signature_help, {border = "single", max_width = 50}
  ),
}


local pylsp_handlers =  {
  ["callHierarchy/incomingCalls"] = function() end,
  ["callHierarchy/outgoingCalls"] = function() end,
  ["textDocument/codeAction"] = function() end,
  ["textDocument/completion"] = function() end,
  ["textDocument/declaration"] = function() end,
  ["textDocument/definition"] = function() end,
  ["textDocument/documentHighlight"] = function() end,
  ["textDocument/documentSymbol"] = function() end,
  ["textDocument/formatting"] = function() end,
  ["textDocument/hover"] = function() end,
  ["textDocument/implementation"] = function() end,
  --["textDocument/publishDiagnostics"] = function() end,
  ["textDocument/rangeFormatting"] = function() end,
  ["textDocument/references"] = function() end,
  ["textDocument/rename"] = function() end,
  ["textDocument/signatureHelp"] = function() end,
  ["textDocument/typeDefinition"] = function() end,
  ["window/logMessage"] = function() end,
  ["window/showMessage"] = function() end,
  ["window/showDocument"] = function() end,
  ["window/showMessageRequest"] = function() end,
  ["workspace/applyEdit"] = function() end,
  ["workspace/symbol"] = function() end,
}

local capabilities = require('cmp_nvim_lsp').default_capabilities()


nvim_lsp.pyright.setup{
    handlers = pyright_handlers,
    capabilities = capabilities,
}

nvim_lsp.pylsp.setup{
  handlers = pylsp_handlers,
  settings = {
    pylsp = {
      configurationSources = {
          'flake8',
      },
      plugins = {
        jedi_definition = {
            enabled = false,
        },
        jedi_completion = {
            enabled = false,
        },
        pycodestyle = {
          enabled = false,
          --maxLineLength = 100,
        },
        pyflakes = {
            enabled = false
        },
        mccabe = {
            enabled = false,
        },
        flake8 = {
            enabled = true,
            ignore = {"E128", "E131", "E201", "E202", "E251", "E501", "W503", "W504"}, 
        },
        pylsp_mypy = {
            enabled = true, -- For this to work well, an pylsp-mypy.cfg is neccesary inside the root folder
            -- Also, inside the conda env pylsp_mypy must be installed, an example can be found below
        },
        pylint = {
            enabled = false,
            ignore = {"C0114", "C0301"},
            args = {"--rcfile=pylint_rc.rc"}
        },
      }
    }
  }
}

```

But, of course, if you dont want to use to servers, just use [my above answer](https://github.com/hrsh7th/nvim-cmp/issues/823#issuecomment-1353245660) to format the output, i switch from formatting the output to using two servers because i think pyright i a little better to go to defintions then pylsp, but i like the pylsp diagnostics

**Comment by zippeurfou** [comment]
Thanks @crates51 ,
One thing thought:
```
pylsp_mypy = {
            enabled = true, -- For this to work well, an pylsp-mypy.cfg is neccesary inside the root folder
            -- Also, inside the conda env pylsp_mypy must be installed, an example can be found below
        }
```
I use pyenv. Do you know how it works for it?
or even what is inside the cfg file?

**Comment by crates51** [comment]
> Thanks @crates51 ,
> One thing thought:
> ```
> pylsp_mypy = {
>             enabled = true, -- For this to work well, an pylsp-mypy.cfg is neccesary inside the root folder
>             -- Also, inside the conda env pylsp_mypy must be installed, an example can be found below
>         }
> ```
> I use pyenv. Do you know how it works for it?
> or even what is inside the cfg file?
> Also do you get code action with this setup?

Well just install pylsp_mypy in your pyenv then, and i dont use code action, yet :)

**Comment by crates51** [comment]
Sorry i forgot to post that day :)
@zippeurfou
i use this pylsp-mypy.cfg in the root folder of my projects
```
{
    "enabled": True,
    "live_mode": False,
    "dmypy": True,
    "strict" : False,
    "overrides": ["--ignore-missing-imports", "--follow-imports", 'skip', "--implicit-optional" , True]
}

```
