### ISSUE TITLE
*[Feature Request/Suggestion]* Option to disable nvim-cmp on user-defined buftypes

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [hrsh7th/nvim-cmp#824]
Currently I believe that there is no built-in way to disable some source or the plugin or autocomplete for example

Adding an option in the configuration would be wonderful, as other plugins also have an [option for this](https://github.com/lukas-reineke/indent-blankline.nvim/blob/2e35f7dcdc72f39b37c21e43cdb538d7a41c7e07/doc/indent_blankline.txt#L375).

**Comment by hrsh7th** [comment]
You can use `cmp.setup { enabled = function() ... end }`.
