### ISSUE TITLE
Strange behaviour when setting `backspace=0`

### ISSUE THREAD

**Issue by yardnsm** [hrsh7th/nvim-cmp#825]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Minimal reproducible config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

set backspace=0

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

Hey!

I have just started using this plugin and noticed a strange behaviour when completing an already inserted word when using `set backspace=0`. The selected suggestion simply appended right after the word, rather than replace (complete) it.

Look what happens when I'm trying to complete the word "a_nice_word" while I already inserted the part "a_nice". In the following example I am also selecting the suggestion multiple times:

https://user-images.githubusercontent.com/11786506/156899094-5a393a8f-93cc-4e52-aca4-d8087b4fe6cd.mov

When I run `set backspace=indent,eol,start`, it behaves like it should:

https://user-images.githubusercontent.com/11786506/156899098-19be4725-da6a-4b7a-bb7e-bc55aac42f9f.mov

It seems that when an item is being selected, the `backspace` option should be set to `indent,eol,start` and after that it should go back to the default.

I've found https://github.com/hrsh7th/nvim-cmp/pull/347 and https://github.com/hrsh7th/nvim-cmp/issues/343, but the issue seems to persist until now 🤷‍♂️ 

### Steps to reproduce

1. Use `set backspace=0`
2. Go to INSERT while on a given word and try to complete it.
3. Behold!

### Expected behavior

The word should be completed from its beginning.

### Actual behavior

The completion is inserted right after the word.

**Comment by hrsh7th** [comment]
I'll check it. Thank you!

**Comment by Balrrach** [comment]
Exactly the same thing happens to me and the update hasn't fixed it.
My configuration is:
```lua
local cmp = require'cmp'
local lspkind = require('lspkind')

cmp.setup({

formatting = {
	format = 
	function(entry, vim_item)
		vim_item.kind = lspkind.presets.default[vim_item.kind]
		return vim_item
	end
},

	completion = {keyword_length = 1,},

	snippet = {
		expand = function(args)
		-- For `vsnip` user.
		vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` user.

		-- For `luasnip` user.
		-- require('luasnip').lsp_expand(args.body)

		-- For `ultisnips` user.
		-- vim.fn["UltiSnips#Anon"](args.body)
	end,
	},

mapping = {
	['<C-d>'] = cmp.mapping.scroll_docs(-4),
	['<C-f>'] = cmp.mapping.scroll_docs(4),
	['<C-Space>'] = cmp.mapping.complete(),
	['<C-e>'] = cmp.mapping.close(),
	['<CR>'] = cmp.mapping.confirm({ select = true }),
	['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
	['<C-e>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
	-- ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
	-- ['<Tab>'] = cmp.mapping.confirm({ select = true }),
	['<Esc>'] =
	function(fallback)
		cmp.mapping.abort()
		fallback()
	end,
	-- ['<CR>'] = function()
	-- if not cmp.confirm({ select = false }) then
	-- vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, true, true), 'n', true)
	-- ['<CR>'] = vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<CR>', true, true, true), 'n', true),
},

sources = cmp.config.sources(
{
	{ name = 'nvim_lsp' },
	{ name = 'cmp_tabnine' },
	{ name = 'vsnip' }, -- For vsnip users.
	-- { name = 'luasnip' }, -- For luasnip users.
	-- { name = 'ultisnips' }, -- For ultisnips users.
	-- { name = 'snippy' }, -- For snippy users.
},
{ { name = 'buffer' }, }
)

})
```
