### ISSUE TITLE
Can't Get Any Kind of Autocompletion Engine to Work

### ISSUE THREAD

**Issue by Balrrach** [hrsh7th/nvim-cmp#826]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible config

```vimrc
Plug 'neovim/nvim-lspconfig'				" LSP configurations
Plug 'nvim-treesitter/nvim-treesitter'			" Treesitter
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'
Plug 'tzachar/cmp-tabnine', { 'do': './install.sh' }	" Autocompletion engine


local cmp = require'cmp'
local lspkind = require('lspkind')

cmp.setup({

formatting = {
	format = 
	function(entry, vim_item)
		vim_item.kind = lspkind.presets.default[vim_item.kind]
		return vim_item
	end
},

	completion = {keyword_length = 1,},

	snippet = {
		expand = function(args)
		vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` user.
	end,
	},

mapping = {
	['<C-d>'] = cmp.mapping.scroll_docs(-4),
	['<C-f>'] = cmp.mapping.scroll_docs(4),
	['<C-Space>'] = cmp.mapping.complete(),
	['<C-e>'] = cmp.mapping.close(),
	['<CR>'] = cmp.mapping.confirm({ select = true }),
	['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' }),
	['<C-k>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 's' }),
	['<Esc>'] =
	function(fallback)
		cmp.mapping.abort()
		fallback()
	end,
},

sources = cmp.config.sources(
{
	{ name = 'nvim_lsp' },
	{ name = 'cmp_tabnine' },
	{ name = 'vsnip' }, -- For vsnip users.
},
{ { name = 'buffer' }, }
)

})
```

### Description

After changing my computer, installing the operating system and neovim and porting my old configuration I can see that the auto-completion suggestions that I'm getting are not from any of the sources I'm using since they are very bad and not dependent on programming context and the icon that accompanies them is the `Tt` which used to be used to indicate it was context based not language server based and :
![image](https://user-images.githubusercontent.com/35852847/156901024-5b98fcc0-3df2-4062-92d8-6d9f14b0958f.png)
Also I get no info in the auto-completion menu and I can't see any snippets(the icon was some scissors).

It all seems to indicate that no auto-completion engine is being used in the background.

### Steps to reproduce

Load my config and try to autocomplete any sentence in any language.

### Expected behavior

Get a list of possible auto-completions coming from the sourced auto-completion engines.

### Actual behavior

Get a list with file-context based options.

**Comment by Shougo** [comment]
You need to install LSP server in the machine.

**Comment by Balrrach** [comment]
I have clangd installed for c++ projects.
![image](https://user-images.githubusercontent.com/35852847/156913403-104cce94-9e3a-419c-be36-46de5f1d63e0.png)

**Comment by Balrrach** [comment]
It was my fault. I was overriding the given config in a different file. Thanks for your help!
