### ISSUE TITLE
Using nvim-cmp with firenvim cause problem

### ISSUE THREAD

**Issue by tin-pham** [hrsh7th/nvim-cmp#827]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7.0dev

### Minimal reproducible config

https://github.com/tin-pham/NeoVimLua

It inside lua/options/cmp.lua

### Description

It show this error when I use firenvim on text box on the browser (markdown textbox like reddit, github work fine. Other textbox not markdown will cause this)
![image](https://user-images.githubusercontent.com/20679090/156970359-b907a38e-e948-44e4-ae8a-97063b55110f.png)

### Steps to reproduce

1. Use nvim-cmp with firenvim
2. If the textbox is not markdown (facebook, googletranslate) it will cause this

### Expected behavior

1. It just like the image above

### Actual behavior

It will just writing normal like this without that text being annoy pop up all over again
![image](https://user-images.githubusercontent.com/20679090/156971116-5948d494-6fa7-45c6-98b5-3597e8920bac.png)

### Additional context

I have open issue on the github site of the firenvim author, and have some discussion with the admin

I can turn off nvim-cmp and start using firenvim on the web but when I start coding, it can be annoy to turn it on again, so maybe my config have something that cause this problem??

https://github.com/glacambre/firenvim/issues/1330

**Comment by 130ndim** [comment]
Having the same issue in JupyterLab. 
`:set lines = 20` fixed it for me

**Comment by ariel-frischer** [comment]
@130ndim That works but like, looks wierd and doesn't fit the input box / text area. I would imagine on larger text boxes, the height of the nvim box would be too small as well. There must be another way?

**Comment by 130ndim** [comment]
I've created an autocmd to set lines = max(20, box lines). I use it mostly to edit JupyterLab cells, so I'm not comfortable with default 1 line window anywas
