### ISSUE TITLE
How to get count of available completion items?

### ISSUE THREAD

**Issue by JosefLitos** [hrsh7th/nvim-cmp#831]
I would like to replicate big IDE style of completion. They automatically expand the completion item, even if not visible, but there must be just one item to be completed.
So far I have this for `mapping`:
```lua
['<C-Space>'] = cmp.mapping(function(fallback)
	if cmp.GETCOUNT() == 1 and cmp.get_selected_entry ~= nil and luasnip.expandable() then
		luasnip.expand()
	elseif not cmp.visible() then
		cmp.complete()
	else
		cmp.select_next_item()
	end
end, {"i", "c"}),
['<Esc>'] = cmp.mapping({i = cmp.mapping.abort(), c = cmp.mapping.close()}),
['<CR>'] = cmp.mapping({
	i = cmp.mapping.confirm({behavior = cmp.ConfirmBehavior.Replace, select = false}),
}),
["<Tab>"] = cmp.mapping(function(fallback)
	if cmp.get_selected_entry() ~= nil then
		cmp.confirm()
	elseif cmp.visible() and luasnip.expandable() then
		luasnip.expand()
	elseif cmp.visible() then
		cmp.select_next_item()
	elseif luasnip.jumpable(1) then
		luasnip.jump(1)
	else
		fallback()
	end
end, {"i", "s"}),
["<S-Tab>"] = cmp.mapping(function(fallback)
	if cmp.visible() then
		cmp.select_prev_item()
	elseif luasnip.jumpable(-1) then
		luasnip.jump(-1)
	else
		fallback()
	end
end, {"i", "s"})
```

Is there, or could you implement a method that returns boolean (like `cmp.multiple()`) or item count (like `cmp.count()`)?
BTW thanks for this plugin, couldn't live without it.

**Comment by JosefLitos** [comment]
Percisely I would like to complete immediately (without displaying the menu) in case there is only one thing to be completed or the first suggestion matches the written text.

**Comment by hrsh7th** [comment]
I'll add the `cmp.get_items()`.

**Comment by smjonas** [comment]
Could you tell us more about what are you trying to achieve? When should `expand_table` be called? By the way, I think you need to use `pairs` instead of `ipairs` here.

**Comment by JosefLitos** [comment]
I don't really understand lua, I just needed to find out, what is the text of the first entry and in which variable is it stored.
I want to confirm the selection if only one entry is available, or if the text matches the first entry.
Also, I am not sure how I could get the text that was used to generate the entries.

**Comment by JosefLitos** [comment]
I have come up with this, which gives me most of the content, I just need to dig through it to understand it better:
```lua
function expandTable(table, depth, tabs)

	local tab = ""
	for i = tabs, 1, -1 do tab = tab .. "  " end
	local result = "{\n"
	for key, v in pairs(table) do
		-- prepare json key-value pairs and save them in separate table
		if v ~= nil then
			if type(v) == "table" and depth > 0 then
				v = expandTable(v, depth - 1, tabs + 1)
			elseif type(v) == "boolean" then
				v = tostring(v)
			elseif type(v) == "function" then
				v = "function"
			elseif type(v) ~= "number" and type(v) ~= "string" then
				v = type(v)
			end
			result = result .. string.format("%s  \"%s\":%s", tab, key, v) .. ",\n"
		end
	end
	-- get simple json string
	return result .. tab .. "}"
end

print(expandTable(entries[1], 3, 0))
```

**Comment by JosefLitos** [comment]
I have found the value I needed - `cmp.get_entries()[1].exact` - this tells me whether the text matches the entry. Yet, I need to have the menu displayed.
I understand this is probably a performance optimalization, but is there a way in which I could get an entry at any time?

**Comment by hrsh7th** [comment]
Good to hear. but It's un-documented API. It can be modified in the future. :)
