### ISSUE TITLE
`cmp-omni` source not displayed when `nvim_lsp` is enabled

### ISSUE THREAD

**Issue by CosmosAtlas** [hrsh7th/nvim-cmp#833]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.6.1

### Minimal reproducible config

```vimrc
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('~/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

set runtimepath=~\tmp\plugged\vim-plug\nvim-cmp,~\tmp\plugged\vim-plug\cmp-buffer,~\tmp\plugged\vim-plug\cmp-omni,~\tmp\plugged\vim-plug\cmp-nvim-lsp,~\tmp\plugged\vim-plug\vim-vsnip,~\tmp\plugged\vim-plug\nvim-lspconfig,~\tmp\plugged\vim-plug\vimtex,C:\tools\neovim\Neovim\share\nvim\runtime,C:\tools\neovim\Neovim\share\nvim\runtime\pack\dist\opt\matchit,C:\tools\neovim\Neovim\lib\nvim,~\tmp\plugged\vim-plug\cmp-buffer\after,~\tmp\plugged\vim-plug\cmp-omni\after,~\tmp\plugged\vim-plug\cmp-nvim-lsp\after,~\tmp\plugged\vim-plug\vimtex\after,~\tmp\plugged\vim-plug
execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-omni'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'lervag/vimtex'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "omni", keyword_length = 0 },
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.texlab.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When the `sources` contain `nvim_lsp`, results from `omni` will not show up. The particular behaviour is when trying to autocomplete for `\cite{` in latex.

This is when only `omni` is in source, but not `nvim_lsp`
![image](https://user-images.githubusercontent.com/5738747/157809072-ece78017-3f2d-4cdd-a463-fbb1ed651190.png)

This is when both `omni` and `nvim_lsp` are in sources
![image](https://user-images.githubusercontent.com/5738747/157809124-3322f15b-98fb-4f18-a6fd-5daa418edd0e.png)

I'm not sure if it's a configuration issue, the goal I want to achieve here is to have the source only list results from `omni` but not `nvim_lsp` when they duplicate each other.

I've tried with `group_index` and `priority` settings in sources (also both ways, so `omni` have both higher or lower `group_index`/`priority` tested), this would cause the autocomplete not populated by results from `omni`. For example:

![image](https://user-images.githubusercontent.com/5738747/157809171-313184ca-07d4-43e5-8b73-2b0167c1dbd0.png)

![image](https://user-images.githubusercontent.com/5738747/157809219-2c9b9822-8900-498e-a15b-b894051780a2.png)

### Steps to reproduce

With vimtex and texlab properly configured and setting the sources, edit a latex file and try completion with citations.

### Expected behavior

Results from `omni` would be displayed.

### Actual behavior

Results from `nvim_lsp` is displayed, and no results at all when trying to tweak with source priority.

**Comment by hrsh7th** [comment]
I think it's an offset position problem.

Could you test with adding the following config?

```
cmp.setup {
  ...
  sorting = {
    comparators = {
      cmp.config.compare.score,
    }
  }
  ...
}
```

**Comment by CosmosAtlas** [comment]
> Could you test with adding the following config?
> 
> ```
> cmp.setup {
>   ...
>   sorting = {
>     comparators = {
>       cmp.config.compare.score,
>     }
>   }
>   ...
> }
> ```

I've tried adding the config, still same behavior, no result shows up with `group_index` set, and only `nvim_lsp` results without `group_index` set.

**Comment by hrsh7th** [comment]
Hm... @CosmosAtlas Could you try this? https://github.com/hrsh7th/nvim-cmp/pull/843

**Comment by CosmosAtlas** [comment]
> Hm... @CosmosAtlas Could you try this? #843

With the version from the branch `fix-col`, I got it kind of working. So if I specifically set the ordering as the following, the behavior matches what I want.

`omni` results from `cite`
![image](https://user-images.githubusercontent.com/5738747/158513011-62ef2b00-cdf9-4e3d-89ce-dd38984ffee4.png)

`nvim_lsp` results from `usepackage`
![image](https://user-images.githubusercontent.com/5738747/158513048-c1e573c4-6dca-4020-a6bd-238370947faa.png)

However, there is one thing I'm not certain if it's expected. So I've set `group_index` for `omni`, `nvim_lsp`, and `vsnip` as 1, 2, and 3.

Each time a completion is triggered, only results from one of the sources will show up. That is I won't get results say from both `omni` and `vsnip` (which is what I get previously, see first screenshot from initial comment).

Personally, I can live with the current version, but someone else might complaint about it. 

Also, a site note here. If I set both `omni` and `nvim_lsp` to the same group, then `nvim_lsp` will overwrite the results of `omni` (the previous undesired behavior).

**Comment by hrsh7th** [comment]
You should use `priority` instead of `group_index`

**Comment by CosmosAtlas** [comment]
> You should use `priority` instead of `group_index`

If I use `priority`, I get the same problem (i.e., only `nvim_lsp` result is displayed) with either `omni` have higher `priority` or `nvim_lsp` having higher `priority`.

**Comment by CosmosAtlas** [comment]
My full neovim config: https://github.com/CosmosAtlas/dotfiles/tree/nvim_cmp_fix/neovim/.config/nvim

The tex specific part: https://github.com/CosmosAtlas/dotfiles/tree/nvim_cmp_fix/neovim/.config/nvim

**Comment by hrsh7th** [comment]
Could you remove keyword_length = 0?
It will cause undefined behaivior.

**Comment by CosmosAtlas** [comment]
> Could you remove keyword_length = 0?

I tried without `keyword_length = 0`, and get the same results.

On a sidenote, I have the setting reading from [vimtex issue](https://github.com/lervag/vimtex/issues/2215#issuecomment-981142735) which suggests I would need it to get immediate suggestion (which is what `nvim_lsp` behaves like, getting suggestions after `\cite{`). With out it, `omni` only gives suggestions after I type something after `\cite{` say `\cite{h`.

**Comment by CosmosAtlas** [comment]
I've also tried the newest MWE from the vimtex issue from the last comment (with a few lines added to properly configure the LSP). Also, no luck : (.

**Comment by CosmosAtlas** [comment]
A long waited update, but I think this is not an issue of cmp-omni, but rather an artifact of the integration with the latex environment.

In this special case, both cmp-omni, and lsp results are displayed, and in correct order. So the issue is likely elsewhere.

![image](https://user-images.githubusercontent.com/5738747/191072953-5bfa893b-b0a0-4b6b-a074-80ae41e9a4ea.png)

Some things that I've noticed:

- A `keyword_length=0` has to be set, otherwise nothing will show up.
- The omni results will only show up with the extra space after `\cite{ `
- If only enable omni but not lsp, it shows up immediately following `\cite{`
- For vimtex completion to work, setting `omnifunc` was neccessary, however, it might be overwritten by `nvim_lsp`.
- My guess here is due to the completion only triggers after `{`, which can be problematic, since it's a special character.

I'm closing this for now. Since the issue lies elsewhere.

**Comment by benbrastmckie** [comment]
> My full neovim config: https://github.com/CosmosAtlas/dotfiles/tree/nvim_cmp_fix/neovim/.config/nvim
> 
> The tex specific part: https://github.com/CosmosAtlas/dotfiles/blob/nvim_cmp_fix/neovim/.config/nvim/after/ftplugin/tex.lua

You are getting better results that I am. My config of `nvim-cmp` seems to work great on all of my sources, but can't get `omni` to work out, even turning off `nvim_lsp`. However, you seem to be able to get citations which I am eager to get working. Could you link your config as the links you provide above don't work. Thanks for the great leads!
