### ISSUE TITLE
How to achieve Lua function arguments autocompletion as in the README's demo?

### ISSUE THREAD

**Issue by AlexSWall** [hrsh7th/nvim-cmp#834]
In the README, the demo shows use of nvim-cmp to get predictions (with ghost text) in Lua which includes the arguments of functions. I'm wondering how this was achieved.

I have nvim-cmp installed and I've tried using both vsnip and LuaSnip, with sumneko's lua-language-server installed and ghost text enabled. However, instead of getting

<img width="447" alt="Screenshot 2022-03-11 at 06 04 47" src="https://user-images.githubusercontent.com/31999802/157811757-c24fb52d-0e9c-4877-a6f0-52ddd9466bfc.png">

I'm missing anything after the function name, and getting

<img width="653" alt="Screenshot 2022-03-11 at 06 03 46" src="https://user-images.githubusercontent.com/31999802/157811775-85a18d29-bdd9-4ed6-b1ee-7b40a53cc248.png">

This is contrasted to in Python, where I'll get the full suggestions.
E.g.
<img width="356" alt="Screenshot 2022-03-11 at 06 06 55" src="https://user-images.githubusercontent.com/31999802/157811980-ed4052ad-cb30-4bc8-8487-c7ddcf140b81.png">

How do I achieve that which is shown in the README video?

**Comment by gegoune** [comment]
@hrsh7th answered that before. It's not up to nvim-cmp but sumneko to return snippet, try to configure sumneko-lsp such as (if you are using lspconfig):

```lua
    settings = {
      Lua = {
        completion = {
          callSnippet = 'Replace',
        },
      },
    },
```

**Comment by AlexSWall** [comment]
Oh perfect, thank you! Apologies, I could not find the prior answer (and I did look, albeit possibly poorly), it might be worth linking it here if you know where it is.

**Comment by gegoune** [comment]
Someone else actually responded here https://github.com/hrsh7th/nvim-cmp/discussions/544. Glad you got it working. :)
