### ISSUE TITLE
`commit_characters` should honor `completeopt -= 'noselect'`

### ISSUE THREAD

**Issue by wangkaibule** [hrsh7th/nvim-cmp#835]
When `noselect` is absent from `completeopt` option, nvim-cmp will select
the first candidate entry by default but not immediately insert it into buffer. At this
scenario, it is more intuitive to accept the selected entry if I continue to input a character in `commit_characters` set.

Currently, the "selected but not yet inserted" candidate won't get accepted if I input one of "commit charaters".

## Example
Suppose I've set `commit_charaters` set to `{'.'}`, which suggests I can simply type character `.` to accept the candidate

```lua
require('cmp').setup({
     confirmation = {
           get_commit_characters = {'.'},
     },
     completion = {
           completeopt = 'menu,menuone',
     },
 })
````

And in nvim buffer:

```ascii
test
t|   <- cursor here, with candidates entry window visible, first candidate is "test"
```
type `.`,  expecting to get:

```ascii
test
test.
```

Currently, we can only get:

```ascii
test
t.
```

To "fix" this, we should fetch "selected_entry" instead of "acive_entry":

https://github.com/hrsh7th/nvim-cmp/blob/1001683bee3a52a7b7e07ba9d391472961739c7b/lua/cmp/core.lua#L118

**Comment by hrsh7th** [comment]
I don't think so... I think the commitCharacters must behave for the limited situation.

The `limited situation` intention is the following situation.

1. Type `sort` in `Golang` buffer
2. Select `sort` candidate
3. Type `.` for accept completion and then nvim-cmp will append `auto-import` statemets.

**Comment by liskin** [comment]
I agree with @wangkaibule. Without `noselect`, the preselected entry is visually indistinguishable from an entry selected via `cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select })`, yet the commit character behaviour is inconsistent. I've worked around it by having

```lua
cmp.event:on('menu_opened', function(data)
	data.window.active = true
end)
```

in my config, but it feels wrong as it relies on the internals of nvim-cmp.

**Comment by Shougo** [comment]
Hm... VSCode's commit characters seem accept the candidate.

https://dev.to/siddharthshyniben/vscode-tips-commit-characters-e2a
