### ISSUE TITLE
LSP autocomplete, kind is changed after import

### ISSUE THREAD

**Issue by zer09** [hrsh7th/nvim-cmp#838]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1241-g08d9d74fd

### Minimal reproducible config

Here is my minimal config https://github.com/zer09/nvim-config/blob/master/lua/plugins/config/cmp_conf.lua

### Description

Good day

I Hope this is the right channel to post this issue. I got a little concern about the autocomplete kind, when the function is not imported yet the lsp kind was able to detect that it was a function and will automatically import and add round brackets after the completion, but after it was successfully imported on the source and you will type the same function the lsp kind will tell it just variable and wont auto complete the round brackets.

Here is the before and after screenshot
Before
![Screenshot_20220314_095045](https://user-images.githubusercontent.com/780780/158093750-0f3337f3-864c-48d2-ba08-28db6c3cac0f.png)

After
![Screenshot_20220314_095315](https://user-images.githubusercontent.com/780780/158093766-d4db5b69-7d91-48e9-bbe2-892491146ed1.png)

### Steps to reproduce

The language is typescript
1. Call a function that will be imported
2. The function now imported on the code
3. Call again the same function

### Expected behavior

After the second time you call that function and imported, lsp kind should detect it as a function and not a variable

### Actual behavior

lsp kind detect it as a variable

**Comment by Shougo** [comment]
Hm...  It seems LSP server's problem.  I think nvim-cmp does not change the kind.

**Comment by zer09** [comment]
Is this the right repo to post this?
https://github.com/typescript-language-server/typescript-language-server

**Comment by hrsh7th** [comment]
I can't fix this. the nvim-cmp will show the kind that returned from LSP server.
