### ISSUE TITLE
Configuration merging does not work properly

### ISSUE THREAD

**Issue by dainiusm07** [hrsh7th/nvim-cmp#84]
I'm getting a lot of the same errors when tabbing through the completion list. Tried to set optional and global values of winhighlight but nothing help. Btw not sure, but I believe that this error produces a lot of load to the thread because it freezes everything for about 50-100ms.

`Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/float.lua:95: Cannot unset option 'winhighlight' because it doesn't have a global value`

**Comment by hrsh7th** [comment]
@dainiusm07 I've fixed the bug of the `misc.merge` behavior.

Now, You must set `documentation = false` if you disable documentation feature.
The empty table will be merged with default configuration.
