### ISSUE TITLE
Hide Icon and File Preview in Commandline Completion

### ISSUE THREAD

**Issue by Tummetott** [hrsh7th/nvim-cmp#842]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v.0.6.0

### Minimal reproducible config

```lua
local cmp = require'cmp'
local mapping = require('cmp.config.mapping')
local lspkind = require('lspkind')

cmp.setup({
    formatting = {
        format = lspkind.cmp_format({
            -- Don't write the type of completion, just show the icon
            with_text = false,
            maxwidth = 50,
            -- Show the completion source
            menu = {
                buffer = '[BUF]',
                nvim_lsp = '[LSP]',
                nvim_lua = '[API]',
                path = '[PATH]',
                luasnip = '[SNIP]',
            },
        })
    },
    documentation = {
        winhighlight = 'NormalFloat:Pmenu,FloatBorder:None',
    },
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end,
    },
    mapping = {
        ['<C-n>'] = mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ['<C-p>'] = mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
        ['<Up>'] = mapping.scroll_docs(-4),
        ['<Down>'] = mapping.scroll_docs(4),
        ['<C-y>'] = mapping.confirm({ select = true }),
        ['<C-e>'] = mapping.abort(),
        ['<CR>'] = mapping({
            i = mapping.confirm({ select = false }),
        }),
    },
    -- The order in which I specify sources defines the priority
    sources = cmp.config.sources({
        { name = 'nvim_lua' },
        { name = 'nvim_lsp' },
        { name = 'path' },
        { name = 'buffer', keyword_length = 5, max_item_count = 10 },
    })
})

-- Use cmdline & path source for ':'
cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
        { name = 'path' }
    }, {
        { name = 'cmdline' }
    })
})

-- This command connects the autopairs with the cmp
local cmp_autopairs = require("nvim-autopairs.completion.cmp")
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
```

### Description

Hello community, 

this is rather a question than a bug report. The completion inside a buffer works just like I want it: I use lspkind to show a fancy icon of the completion type and it shows me where the completion comes from (the completion source).

However, for the completion of the command line, I just want to see the `word` itself that is about to be completed. I don't want an icon there, and no source. If I start typing a path and I select an item of the completion menu, I also don't want a preview of the file. Is it possible to turn that off (but just for the command line completion)?

I tried adding a formatting option to the `cmp.setup.cmdline()` like this:
```lua
cmp.setup.cmdline(':', {
    formatting = {
        format = lspkind.cmp_format({
            with_text = false,
            menu = {},
        }),
    },
    sources = cmp.config.sources({
        { name = 'path' }
    }, {
        { name = 'cmdline' }
    })
})
```
Note that the cmp-config.formatting.format.menu is empty. Like this I can hide the completion source. But how can I hide the icon and how can I disable file preview when typing a path?

I noticed there is a cmp-config.formatting.fields option but I've no clue how to set it. The manpage is not really helpful for me. 

Thank you for your help.

x Tummetott

### Steps to reproduce

...

### Expected behavior

...

### Actual behavior

...

**Comment by hrsh7th** [comment]
You can set `fields = { 'abbr' }` for cmdline completion.

**Comment by Tummetott** [comment]
Thank you!! Can you also tell me how to disable file preview when typing a path to a file?

**Comment by hrsh7th** [comment]
Currently, no. The preview can't be disabled at the moment. PR is welcome.
