### ISSUE TITLE
Just opened nvim, the first completion does not work

### ISSUE THREAD

**Issue by askfiy** [hrsh7th/nvim-cmp#845]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Minimal reproducible config

this is my config:

```
    {"hrsh7th/vim-vsnip", event = {"InsertEnter", "CmdlineEnter"}},
    {"onsails/lspkind-nvim", event = {"InsertEnter", "CmdlineEnter"}},
    {"hrsh7th/nvim-cmp", load_file = true, after = {"lspkind-nvim", "vim-vsnip"}},
    {"hrsh7th/cmp-vsnip", after = "nvim-cmp"},
    {"hrsh7th/cmp-path", after = "nvim-cmp"},
    {"hrsh7th/cmp-buffer", after = "nvim-cmp"},
    {"hrsh7th/cmp-cmdline", after = "nvim-cmp"},
    {"kristijanhusak/vim-dadbod-completion", after = "nvim-cmp"},
    {"f3fora/cmp-spell", after = "nvim-cmp"},
    {"rafamadriz/friendly-snippets", after = "nvim-cmp"},
    {"tzachar/cmp-tabnine", run = "./install.sh", after = "nvim-cmp", disable = false},

------------------------------------------------------

local lspkind = require("lspkind")
local cmp = require("cmp")

---@diagnostic disable-next-line: redundant-parameter
local options = {
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end
    },
    sources = cmp.config.sources(
        {
            {name = "vsnip"},
            {name = "nvim_lsp"},
            {name = "path"},
            {name = "buffer"},
            {name = "cmdline"},
            {name = "spell"},
            {name = "cmp_tabnine"},
            {name = "vim-dadbod-completion"}
        }
    ),
    formatting = {
        format = lspkind.cmp_format(
            {
                with_text = true,
                maxwidth = 50,
                before = function(entry, vim_item)
                    vim_item.menu = "<" .. string.upper(entry.source.name) .. ">"
                    return vim_item
                end
            }
        )
    },
    mapping = {
        ["<c-p>"] = cmp.mapping.select_prev_item(),
        ["<c-n>"] = cmp.mapping.select_next_item(),
        ["<cr>"] = cmp.mapping.confirm(),
        ['<c-k>"] = cmp.mapping(
            {
                i = function()
                    if cmp.visible() then
                        cmp.abort()
                    else
                        cmp.complete()
                    end
                end,
                c = function()
                    if cmp.visible() then
                        cmp.close()
                    else
                        cmp.complete()
                    end
                end
            }
        ),
        ['<tab>"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({behavior = cmp.SelectBehavior.Select})
                    end
                    cmp.confirm()
                else
                    fallback()
                end
            end,
            {"i", "s", "c"}
        )
    }
}

---@diagnostic disable-next-line: redundant-parameter
cmp.setup(options)

cmp.setup.cmdline(
    "/",
    {
        sources = {
            {name = "buffer"}
        }
    }
)

cmp.setup.cmdline(
    "?",
    {
        sources = {
            {name = "buffer"}
        }
    }
)

cmp.setup.cmdline(
    ":",
    {
        sources = cmp.config.sources(
            {
                {name = "path"}
            },
            {
                {name = "cmdline"}
            }
        )
    }
)
```

### Description

I use tab completion, but there will be a very magical phenomenon.

When you open nvim for the first time and press tab after the completion menu appears (without entering the completion menu) it doesn't select the first one.

The tab will only be available if you manually &lt;c-n&gt; &lt;cr&gt;  select the first one.

Like the following:

![Peek 2022-03-17 23-40](https://user-images.githubusercontent.com/81478335/158837753-b78cbe1a-9cdb-4701-83df-22f03415d166.gif)

The first time I typed re, using tab, it didn't select the first suggestion.

The second time I typed re, I used &lt;c-n&gt;&lt;cr&gt; so it successfully selected the suggestion.

The third time I typed re, using tab, it successfully picked up the first suggestion.

### Steps to reproduce

1. Open nvim.
2. Type anything and press tab, it won't select the first suggestion
3. Type anything and press &lt;c-n&gt;&lt;cr&gt; to manually select the first suggestion
4. Enter any content, then press tab, the tab will take effect.

### Expected behavior

Whenever I press tab it should automatically select the first suggestion.

### Actual behavior

Tab only becomes useful when I press &lt;c-n&gt;&lt;cr&gt;.

### Additional context

I tried disabling lazyload, but still the same.

So this might be a subtle bug. From the plugin itself.

**Comment by askfiy** [comment]
This situation still exists, and I am very distressed.

Or when I press the tab for the first time, the callback function in cmp.mapping does not take effect.

**Comment by hrsh7th** [comment]
Does removing the lazy-loading specification still cause problems?

_If it's lazy-loading problem, I can't support this..._

**Comment by askfiy** [comment]
I've tried disabling lazy loading and the problem persists.

**Comment by Shougo** [comment]
Well, so you should upload the minimal vimrc.

**Comment by askfiy** [comment]
> Well, so you should upload the minimal vimrc.

Is the above information not enough? What other information do you need?

**Comment by hrsh7th** [comment]
@askfiy BTW, your mapping configuration seems to wrong.

```
        ['tab"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({behavior = cmp.SelectBehavior.Select})
                    end
                    cmp.confirm()
                else
                    fallback()
                end
            end,
            {"i", "s", "c"}
        )```

↓↓↓

```
        ['<tab>"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({behavior = cmp.SelectBehavior.Select})
                    end
                    cmp.confirm()
                else
                    fallback()
                end
            end,
            {"i", "s", "c"}
        )
```

**Comment by askfiy** [comment]
@hrsh7th  I noticed this problem, it was an oversight on my upload, it was indeed <tab>, but the problem persisted.

**Comment by askfiy** [comment]
@hrsh7th As long as I don't press the `<c-n>` and `<cr>` selection suggestions, the `<tab>` never takes effect.

**Comment by Shougo** [comment]
Your vimrc is not minimal, because it cannot be executed by one vimrc file.

**Comment by askfiy** [comment]
I use neovim and packer to manage plugins, and I tried disabling all other plugins to see if it was caused by other plugins. But the problem still exists.

I'm guessing it might be a problem due to the `function(fallback)` of `cmp.mapping` . It fails to load my config at startup.

This has nothing to do with lazyload either, since `<c-k>` `<c-n>` `<c-p>` `<cr>` all work fine.

**Comment by Shougo** [comment]
Please upload the minimal vimrc.  I cannot test your vimrc.
It must be tested by other people.

**Comment by Shougo** [comment]
@hrsh7th I have create the minimal vimrc.  But it does not work...  Can you fix my vimrc?

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer

set completeopt=menu,menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    mapping = {
      ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
      ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
      ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
      ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
      ['<C-e>'] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
      }),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    },
    sources = cmp.config.sources({
      { name = 'buffer' },
    })
  })
EOF
```

**Comment by hrsh7th** [comment]
@askfiy 

```lua
        ['<tab>"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({behavior = cmp.SelectBehavior.Select})
                    end
                    cmp.confirm()
                else
                    fallback()
                end
            end,
            {"i", "s", "c"}
```

In my eyes, this is not correct. If you hope `When I press '<Tab>', I hope to confirm the first entry.`, You should use the following mapping.


```lua
        ['<tab>"] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c' }),
```

**Comment by hrsh7th** [comment]
And please create minimal reproducible configuration based on https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

**Comment by askfiy** [comment]
@hrsh7th  The problem still exists. .

**Comment by Shougo** [comment]
@askfiy I have created minimal vimrc.

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer

set completeopt=menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    mapping = {
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
      ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c' }),
    },
    sources = {
      { name = 'buffer' },
    },
  })
EOF

runtime! after/plugin/*.lua
```

How test your problem with it?  Please explain it.

**Comment by askfiy** [comment]
@Shougo 

Is the problem description not clear enough? There are also pictures above.

[](https://user-images.githubusercontent.com/81478335/158837753-b78cbe1a-9cdb-4701-83df-22f03415d166.gif)When you open nvim for the first time and press tab after the completion menu appears (without entering the completion menu) it doesn't select the first one.

The tab will only be available if you manually <c-n> <cr> select the first one.

Like the following:

![](https://user-images.githubusercontent.com/81478335/158837753-b78cbe1a-9cdb-4701-83df-22f03415d166.gif)

The first time I typed re, using tab, it didn't select the first suggestion.

The second time I typed re, I used <c-n><cr> so it successfully selected the suggestion.

The third time I typed re, using tab, it successfully picked up the first suggestion.
Steps to reproduce

    Open nvim.
    Type anything and press tab, it won't select the first suggestion
    Type anything and press <c-n><cr> to manually select the first suggestion
    Enter any content, then press tab, the tab will take effect.

Expected behavior

Whenever I press tab it should automatically select the first suggestion.

**Comment by Shougo** [comment]
OK.  I get it.  `<Tab>` seems overwritten by snippet expand.
My tested vimrc is here.

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer
set rtp+=~/src/cmp-nvim-lsp
set rtp+=~/src/vim-vsnip
set rtp+=~/src/cmp-vsnip
set rtp+=~/src/nvim-lspconfig

set completeopt=menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
      ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c' }),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'buffer' },
    },
  })
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.sumneko_lua.setup{}
EOF

runtime! after/plugin/*.lua
```

**Comment by Shougo** [comment]
It seems the first item is inserted, but the item is snippet.  So the snippet is expanded automatically.

**Comment by Shougo** [comment]
> Type anything and press tab, it won't select the first suggestion

I cannot reproduce it.  Can you test my vimrc?

**Comment by askfiy** [comment]
> > Type anything and press tab, it won't select the first suggestion
> 
> I cannot reproduce it. Can you test my vimrc?

i can try

**Comment by askfiy** [comment]
> > Type anything and press tab, it won't select the first suggestion
> 
> I cannot reproduce it. Can you test my vimrc?

But I don't know how to do it. . . How can I test it? Do you have relevant documentation that I can learn from?

**Comment by Shougo** [comment]
I have created test.lua.

```lua
require("core.settings")
```

```
nvim -u test_cmp.vim test.lua
```

And I have typed `re`.

**Comment by askfiy** [comment]
> I have created test.lua.
> 
> ```lua
> require("core.settings")
> ```
> 
> ```
> nvim -u test_cmp.vim test.lua
> ```
> 
> And I have typed `re`.

What were the results?

**Comment by Shougo** [comment]
![スクリーンショット_2022-03-22_18-38-50](https://user-images.githubusercontent.com/41495/159451336-6a1ef6f3-0e18-445e-83e9-22c5c0f6e7b6.png)
![スクリーンショット_2022-03-22_18-39-10](https://user-images.githubusercontent.com/41495/159451340-c448d5af-f160-4d60-8985-395c67257f8c.png)

Here.

**Comment by askfiy** [comment]
I just tested it and it should be caused by a plugin, so I need to troubleshoot one by one now. . .

**Comment by Shougo** [comment]
OK.

**Comment by itsuki0927** [comment]
I have the same problem, have you found the reason? @askfiy

**Comment by askfiy** [comment]
@itsuki0927 Sorry, just saw it now. It's my own fault, I deleted the mapping of the tabs causing this problem.

**Comment by itsuki0927** [comment]
Thank you for your answer, I have a problem with lazy loading. I just changed the timing of lazy loading and successfully solved this problem❤️
