### ISSUE TITLE
[Request] Customizing aspects of custom_entries_view.lua

### ISSUE THREAD

**Issue by CKolkey** [hrsh7th/nvim-cmp#846]
I've been working on customizing some visual aspects of the custom popup menu, and ran into some issues that required making minor changes in `custom_entries_view.lua`. I don't mind this, but since I may not be the only one who is interested in this level of tweaking, I'm curious if there might be some possibility to expose these variables in the setup function. Alternatively, if there's a better way to accomplish what I'm trying to do, I'm all ears.

Specifically, I'm looking to be able to change:
- `custom_entries_view.lua:11`: `local SIDE_PADDING` to `0` so there is no window to the left of the 'kind' icon.
- `custom_entries_view.lua:35`: remove `CursorLine:PmenuSel` from `winhighlight` options so the background color of the 'kind' icon isn't changed by `PmenuSel`
- `custom_entries_view.lua:168`: offset `col` value by `-3` (`col = math.max(0, col - 3)`) so the completion entries line up with the text in the buffer.

This is how it looks without those changes:
![Screenshot 2022-03-18 at 10 46 00](https://user-images.githubusercontent.com/7228095/158980826-2ce2aa0e-4c92-408d-b83e-57fd34026e48.png)

And how it looks with the changes:
![Screenshot 2022-03-18 at 10 46 49](https://user-images.githubusercontent.com/7228095/158980870-5410592e-1480-4b3f-8d1c-c7756e8e9147.png)

Thanks in advance :)

**Comment by hrsh7th** [comment]
I can understand your expectation.

But I can't imagine we achive it in general way. we might not derrived the proper abstraction...

The nvim-cmp's design already confusing. For example, we have `window` and `view` configuration section.

We must re-thinking the design to customize appearance.

**Comment by hrsh7th** [comment]
I think the custom entries view is now customizable.

**Comment by wookayin** [comment]
@hrsh7th How? Can you please let us know relevant commits/PRs or documentation?

**Comment by hrsh7th** [comment]
See docs https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt#L624
