### ISSUE TITLE
Disabling completion candidate preselect doesn't seem to work

### ISSUE THREAD

**Issue by dajohans** [hrsh7th/nvim-cmp#850]
There's a config option to set the preselect behaviour, but it doesn't work as I expect. Or rather, it doesn't seem to work at all.

First of all, let's start with the following very minimal `nvim-cmp` setup.
``` lua
local cmp = require('cmp')
cmp.setup({
    enabled = true,
    sources = {
        {name = 'nvim_lsp'}
    }
})
```
For context, when trying this out I write `C` code(a simple hello world file) with `clangd-12` language server and the neovim builtin lsp client. Autocompletion works and I can walk through the completion candidates with `C-n`, `C-p` and documentation is shown in a popup window next to the completion menu for the currently selected completion candidate. However, if when I cycle through the completion candidates with `C-n`, `C-p` the completion candidate is immediately inserted at the cursor. What I would want is the when I cycle through the completion candidates with `C-n`, `C-p`, nothing happens at the cursor untill I confirm the selected completion candidate with `C-y`(at least this is the default keybind).

By reading the documentation, I think it seems like I should be able to get this behaviour by using the following config.
``` lua
local cmp = require('cmp')
cmp.setup({
    enabled = true,
    preselect = cmp.PreselectMode.None,
    sources = {
        {name = 'nvim_lsp'}
    }
})
```
However, this doesn't work. With this config, the completion behaviour is completely unchanged.

To try to figure out if the setting actually works, I thought that I'll temporarily modify the plugin code and play with the default values. So I modify to file `nvim-cmp/lua/cmp/config/default.lua`. I thought that I might get what I want by switching line 13:
``` lua
preselect = types.cmp.PreselectMode.Item,
```
to the following
``` lua
preselect = cmp.PreselectMode.None,
```
but nothing happened. I still get the same behaviour where the completion candidate is inserted at the cursor if it is selected but not confirmed. Next, I thought that maybe it's neovim's setting `completeopt` which is the issue. I see that this variable is also set at on point in this file, namely on line 82. I switched
``` lua
completeopt = 'menu,menuone,noselect',
```
to
```lua
completeopt = 'menu,menuone,noselect,noinsert',
```
but again nothing happened. Next tried to play with the keybinds, and this worked. Line 63 and 64 are
``` lua
['<C-n>'] = mapping(mapping.select_next_item({ behavior = types.cmp.SelectBehavior.Insert }), { 'i', 'c' }),
['<C-p>'] = mapping(mapping.select_prev_item({ behavior = types.cmp.SelectBehavior.Insert }), { 'i', 'c' }),
```
and I switched this to
``` lua
['<C-n>'] = mapping(mapping.select_next_item({ behavior = types.cmp.SelectBehavior.Select }), { 'i', 'c' }),
['<C-p>'] = mapping(mapping.select_prev_item({ behavior = types.cmp.SelectBehavior.Select }), { 'i', 'c' }),
```
and now it works just like I expect it to. When I cycle through the completion candidates with `C-n`, `C-p` the selected completion candidate is not inserted at the cursor untill I confirm the candidate with `C-y`, just as I wish.

To me it feels like this is not how it is supposed to work. It seems to me like the intent of the API(judging by both names in the code and by the documentation) is that I should be able to get my expected behaviour by only setting the variable `preselect` as in my original attempt, but this doesn't work due to how the default keybind seems to use a function which completely ignores the setting `preselect`. I feel it would be better if the default keybinds were set in a way which respects the value of the config variable `preselect`.

Any thoughts on this?

**Comment by hrsh7th** [comment]
I think you already solve the problem. Why you create the new issue?

IMO, the `pre`-select and `mapping.select_next_item's option` are enough explicit.

The `preselect` is defined in LSP spec see https://microsoft.github.io/language-server-protocol/specifications/specification-current/

**Comment by dajohans** [comment]
While I guess I kind of solved the problem, it seems to me that I solved it in a bad way. It seems to me that I should be able to just set the `preselect` variable as I originally tried. Am I wrong when I say that I should be able to obtain my desired result by modifying the variable `preselect`?

By reading the documentation it seems to me that I should modify the variable `preselect`, but the documentation also doesn't provide much detail as everything is described by just a single sentence(the usual plugin-style documentation). But I don't want to sound too harsh regarding the documentation because I really like the plugin in general, especially how I can easily deal with multiple sources like path, buffer, lsp. It's just that this particular `preselect` thing is a bit confusing to me.
