### ISSUE TITLE
How to not trigger completion in specific cases

### ISSUE THREAD

**Issue by askfiy** [hrsh7th/nvim-cmp#865]
When the code below is true I don't want it to trigger completion automatically.

```
vim.fn["vsnip#available"](1) ==  1
```

what should I do?

I want to add this to the original completion trigger base, not replace the original completion trigger base.

**Comment by askfiy** [comment]
Well, I found the enabled option. But it doesn't work very well.

For example: `try` is a fragment, when I type `try`, the enabled of cmp will be directly set to false,

What I want to achieve is that cmp will not be set to false until I select a fragment.

The following picture expresses what I mean:

![Peek 2022-03-29 20-35](https://user-images.githubusercontent.com/81478335/160612731-9d8880f0-9a1a-4bb9-bede-6fa3e447e250.gif)

Here is my setup:

```
enabled = function()
    if vim.fn["vsnip#available"](1) == 1 or vim.b.visual_multi then
        return false
    end
    return true
end,
```

**Comment by askfiy** [comment]
When I type try, completion is automatically turned off

This is because `vim.fn["vsnip#available"](1) = 1` is `true`。

I want the completion menu to not pop up when typing in the fragment...

When I insert text by pressing `c` in `$1` or `$n`, The completion menu pops up automatically, which is annoying and I have to manually close it to get my `tab` to jump to the `$n+1` position.

Is there any way to make it do better?

**Comment by askfiy** [comment]
I can finish the menu by triggering it manually, instead of it triggering automatically.

So do you have any good suggestions for this?

**Comment by hrsh7th** [comment]
I think this feature request is too specific so you should try and error for this.

I think you can use

```
require('cmp.config').set_onetime({
  completion = {
    autocomplete = false
  }
})
```

For example, you can feed keys the above snippet with vsnip expand/jump keys.

```

inoremap <Plug>(stop-completion-onetime) <Cmd>lua require('cmp.config').set_onetime({ completion = { autocomplete = false } })<CR>

imap <Plug>(my-vsnip-expand) <Plug>(vsnip-expand)<Plug>(stop-completion-onetime)
```

**Comment by askfiy** [comment]
OK, I'm willing to try this. Hope it works out...

**Comment by hrsh7th** [comment]
If this works great to you. I can consider to add `reuqire('cmp').setup.onetime` as public API.

(My above suggestion is to use a private API. Please report if you achieve your expectation or not.

**Comment by askfiy** [comment]
I'm a neovim beginner, so this is a bit of a hassle for me.

If there is a public API, I think I can handle it.

I don't know how to temporarily set `autocomplete` to `false` temporarily.

Because there is no such API right now.

**Comment by askfiy** [comment]
how is it now？

**Comment by askfiy** [comment]
I found a solution.

But it's not perfect:

```
vim.api.nvim_create_autocmd(
    {"TextChangedI"},
    {
        pattern = {"*"},
        callback = function()
            local cmp_config = require("cmp.config")
            -- vim-visual-multi and vsnip
            if vim.fn.mode() == "i" and vim.fn["vsnip#available"](1) == 1 or vim.b.visual_multi then
                cmp_config.global.completion.autocomplete = false
            else
                if not cmp_config.global.completion.autocomplete then
                    cmp_config.global.completion.autocomplete = {"TextChanged"}
                end
            end
        end
    }
)

```
