### ISSUE TITLE
`<Plug>(cmp.u.k.recursive: )` inserts on pressing `<cr>` in insert mode

### ISSUE THREAD

**Issue by UnkwUsr** [hrsh7th/nvim-cmp#871]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.6.1

### Minimal reproducible config
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
" both eunuch and autopairs needed to reproduce this issue
Plug 'tpope/vim-eunuch'
Plug 'windwp/nvim-autopairs'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
require("nvim-autopairs").setup()
-- P.S. if we setup autopairs with this:
-- require("nvim-autopairs").setup({ map_cr = false })
-- then problem disappears

local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When pressing `<cr>` in insert mode, crap inserts, instead of adding a new line.

### Steps to reproduce

Go to insert mode and press enter:
`i<cr>`

### Expected behavior

Just a new line should be inserted.

### Actual behavior

This crap inserts:
```
<Plug>(cmp.u.k.recursive:
)
```

### Additional context

Both [vim-eunuch](https://github.com/tpope/vim-eunuch) and [nvim-autopairs](https://github.com/windwp/nvim-autopairs) plugins needed to reproduce this issue (have installed in minimal config).
Also, as @ipod825 [mentioned](https://github.com/hrsh7th/nvim-cmp/issues/459#issuecomment-1082346336), if you initialize autopairs with option `map_cr = false` then problem disappears (also have a note in minimal config).

**Comment by jack-dunham** [comment]
I have the same problem when pressing `<tab>` in insert mode (but when pressing `<cr>`).

I will need to investigate further what plugins are contributing to this, I have quite a few on my current config.

**Comment by megalithic** [comment]
same thing with me; just happened with latest update :/

**Comment by megalithic** [comment]
Thank you @hrsh7th !!!

**Comment by hrsh7th** [comment]
It's tpope's job! Thank you.
