### ISSUE TITLE
How to disable cmdline auto filling?

### ISSUE THREAD

**Issue by tristone13th** [hrsh7th/nvim-cmp#878]
`select_prev_item` and `select_next_item` will auto-fill the item content in the cmdline,  how to disable this?

**Comment by hrsh7th** [comment]
Try this.

```
    mapping = {
      ['<Tab>'] = {
        c = function(fallback)
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
          else
            cmp.complete()
          end
        end
      },
      ['<S-Tab>'] = {
        c = function(fallback)
          if cmp.visible() then
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
          else
            cmp.complete()
          end
        end
      },
    },
```

**Comment by tristone13th** [comment]
> Try this.
> 
> ```
>     mapping = {
>       ['<Tab>'] = {
>         c = function(fallback)
>           if cmp.visible() then
>             cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
>           else
>             cmp.complete()
>           end
>         end
>       },
>       ['<S-Tab>'] = {
>         c = function(fallback)
>           if cmp.visible() then
>             cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
>           else
>             cmp.complete()
>           end
>         end
>       },
>     },
> ```

worked, many thanks!
