### ISSUE TITLE
Max width on menu entries

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-cmp#88]
Is it possible to get an option for doing something like this in nvim-cmp? https://github.com/hrsh7th/nvim-compe/issues/124

**Comment by hrsh7th** [comment]
I thought we should implement it, but I'd like to see it a little more.

**Comment by charbelnicolas** [comment]
Is there a way to fix the entry menu width to a certain length? I'd like the popup to always have the same width. Any help is appreciated, thanks.

**Comment by nyngwang** [comment]
@charbelnicolas Did you resolve the problem?

**Comment by krishnakumarg1984** [comment]
> Is there a way to fix the entry menu width to a certain length? I'd like the popup to always have the same width.

I'd like exactly the same. It is too jarring to have the popup menu change it's width to be bigger and smaller whilst we type. It's an annoying experience.

**Comment by wonbyte** [comment]
@hrsh7th Is there a way to completely hide the `type` info? I think that's what's causing my menu to do this:

<img width="1673" alt="Screen Shot 2022-08-25 at 11 16 33" src="https://user-images.githubusercontent.com/681965/186704520-196a085e-bea6-4b58-b069-70105383c460.png">

**Comment by DinkyTrady** [comment]
@hrsh7th 
![Screenshot_2022-10-05-21-14-41-750_com termux~2](https://user-images.githubusercontent.com/111265264/194083325-0b502db9-cd2d-42a0-b11e-890ce316e69c.jpg)

I followed this.

> You can already do it with `formatting.format`.
> 
> ```lua
> formatting = {
>   format = function(entry, vim_item)
>     vim_item.abbr = string.sub(vim_item.abbr, 1, 20)
>     return vim_item
>   end
> }
> ```
> 
> But it can be conflicts with `deprecated` indicator so I will introduce it as configuration option (maybe)

But, it's make a icon and (luasnip/text/etc) not showing

**Comment by DinkyTrady** [comment]
I have followed this 

https://github.com/hrsh7th/nvim-cmp/issues/88#issuecomment-906585635

But now it not showing icon and [LSP]. Like this picture 
![Screenshot_2022-10-05-21-14-41-750_com termux~2](https://user-images.githubusercontent.com/111265264/194084920-40aa3608-c162-475c-b6d3-6a087eccc424.jpg)

**Comment by gruvw** [comment]
Is https://github.com/hrsh7th/nvim-cmp/issues/88#issuecomment-906585635 still the recommended way to solve this ? What about sync this value with the window width ?

**Comment by gmr458** [comment]
@gruvw checkout the code snippet in this comment https://github.com/hrsh7th/nvim-cmp/issues/980#issuecomment-1138801858
