### ISSUE TITLE
How do I stop nvim-cmp from hijacking  <Tab> in command line mode?

### ISSUE THREAD

**Issue by jdhao** [hrsh7th/nvim-cmp#880]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible full config

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'

cmp.setup({
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { 'i' }),
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end,
    ['<Esc>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
  },
})
EOF

```

### Description

I only set `Tab` to work in insert mode (at least I thought it does so). But `Tab` is still mapped in command line mode, which is not what I want.

### Steps to reproduce

1. Start nvim: `nvim -u cmp-repro.vim`
2. `cmap <tab>`

### Expected behavior

`Tab` is not mapped/hijacked.

### Actual behavior

`Tab` key is hijacked by nvim-cmp.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/16662357/162583423-0694ac52-f5d8-4fda-9487-ea7e8a10e220.png">

**Comment by arsham** [comment]
It looks that this bug was introduced in 3192a0c57837c1ec5bf298e4f3ec984c7d2d60c0.

**Comment by hrsh7th** [comment]
No. The old implementation already map to tab.

**Comment by hrsh7th** [comment]
You can disable the mapping via following.

```
mapping = {
  ['<Tab>'] = {
    i = ...,
    c = cmp.config.disable
  }
}
```

**Comment by sidesteps** [comment]
> You can disable the mapping via following.
> 
> ```
> mapping = {
>   ['<Tab>'] = {
>     i = ...,
>     c = cmp.config.disable
>   }
> }
> ```

This is not a fix. This is a hack.
If I did not configure/opted-in to  use nvim-cmp for command line - you don't mess with my command line.

**Comment by Shougo** [comment]
Hi.  I have tested the following config.

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer
set rtp+=~/src/cmp-nvim-lsp
set rtp+=~/src/nvim-lspconfig

set completeopt=menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    mapping = {
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
      ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', }),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'buffer' },
    },
  })
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.gopls.setup{}
EOF

runtime! after/plugin/*.lua
```

`<Tab>` key is not mapped in command line mode.
So I think the hijack is opt-in.

**Comment by Shougo** [comment]
If you change to ` ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c'}),`, the key is mapped.

**Comment by Shougo** [comment]
> This plugin breaks command line now. Either Tab does nothing, or inserts Tab symbol on press.
> It Overrides wildmode and breaks cmd line interactions.

Really?  Please provide the minimal config.  I will test it.

**Comment by hrsh7th** [comment]
This issue was closed after 1year ago.
If you have problem, please create new issue and don't re-use old one.

**Comment by sidesteps** [comment]
> > This plugin breaks command line now. Either Tab does nothing, or inserts Tab symbol on press.
> > It Overrides wildmode and breaks cmd line interactions.
> 
> Really? Please provide the minimal config. I will test it.

Thanks @Shougo. I had in my config:
```

local go_next = cmp.mapping(
     function(fallback)
        if cmp.visible() then
            cmp.select_next_item()
        elseif has_words_before() then
            cmp.complete()
          else fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
        end
      end, 
      {'i'. 'c'})

local go_prev = cmp.mapping(function() if cmp.visible() then cmp.select_prev_item() end end, { 'i', 'c' })

local mapping = 
{
    ["<Tab>"] = go_next,
    ["<C-j>"] = go_next,
    ["<C-k>"] = go_prev,
    ['<C-c>'] = cmp.mapping.abort(),
    ['<CR>']  = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Insert, select = true }), 
}
```
so { 'i' 'c' } was specified for insert and command mode.
But, I commented out the cmd mode settup completely

```
--cmp.setup.cmdline(':', 
--{ 
--    mapping = mapping, 
--    enabled = false,
--    --enabled = function() return not vim.tbl_contains({'w', 'x', 'xa', '!'}, vim.fn.getcmdline()) end,
--    sources = cmp.config.sources( 
--    { 
--        { name = 'path' }, 
--        { name = 'cmdline' }, 
--    })
--})
```
In my understanding this is not a coherent design, If cmd line setup was not specified, the cmd mode mapping should not have an effect. 
Perhaps the setup for cmd mode means that you are opting-in to it.
I tried to disable cmd mode as it does not auto select the first option as inert mode does. So you have to explicitly select the option with navigation keys. I can have pretty much the same experience with wildmode though.

**Comment by Shougo** [comment]
If the mapping is opt-out design, the disabled command line completion should disable the mapping.

But the design is opt-in.  You have specified the mapping.
I think current mapping implementation is not problem.

**Comment by Shougo** [comment]
You don't disable cmdline mapping.
You have disabled cmdline specific config.
The cmdline mappings are enable in global config like my config.
So you need to know whats doing your config.
