### ISSUE TITLE
Add doc for comparators

### ISSUE THREAD

**Issue by tristone13th** [hrsh7th/nvim-cmp#883]
I don't understand the meaning of offset, exact. etc. Where can I find the documentation about these?

**Comment by Shougo** [comment]
I have checked.
It seems not documented.
You need to read source code...

https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/compare.lua

**Comment by hrsh7th** [comment]
It's advanced feature.
If you want to full customize, you should read the actual code.

**Comment by ZeroKnight** [comment]
A brief description of each would honestly be great, or even just less-vague comments in `cmp.config.compare` would be nice. Attempting to find out what exactly `offset` is actually comparing requires looking through at least 3 or 4 source files and understanding some of cmp's design. That's a good bit of effort involved in understanding what is by default the highest priority sort criteria.

Honestly, I'm still not sure what it does. After some experimenting I think that it may be similar to "edit distance", but I'm not confident in that assessment; there's some LSP stuff involved as well.

I understand that hrsh7th is mostly doing this alone, so if anyone who knows what `offset` here actually means (i.e. what is actually being compared and why) could comment, that'd be awesome.

**Comment by Shougo** [comment]
nvim-cmp has many features.
The documentation may be insufficient for beginners.
You can improve it.

**Comment by hrsh7th** [comment]
```
separated-word
↑              ↑
｜             └ source2 offset
└ source1 offset
```

The `offset` comparator prefers `source` cadnidates.

**Comment by hrsh7th** [comment]
The `exact` comparator prefers `exact match` candidates.

1. Exact match
    - The user input is `word` and candidates text is `word`
2. Not exact match
    - The user input is `word` and candidates text is `wording`
