### ISSUE TITLE
`vim.fn.input()` prints first line twice when using `nvim-cmp`

### ISSUE THREAD

**Issue by famiu** [hrsh7th/nvim-cmp#889]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1435-g8f95f3ea0

### Minimal reproducible full config

```viml
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

### Description

When I use `nvim-cmp` and call `input()` (VimScript) or `vim.fn.input()` (Lua) with a really long string prompt which causes the prompt to wrap around to multiple lines, the first line gets printed twice. Disabling `nvim-cmp` fixes the issue.

### Steps to reproduce

1. Open Neovim
2. `:lua vim.fn.input("Insert a really long text prompt that doesn't fit within a single line and thus causes the text to wrap around to the next line, which causes the first line of the prompt text to repeat before showing the other lines")`

### Expected behavior

The prompt shows normally

### Actual behavior

The first line of the prompt gets repeated

**Comment by hrsh7th** [comment]
It's upstream issue.

I can reproduce this with the following vimrc.

```vim
lua <<EOF
  _G.on_cmdline_enter = function()
    vim.schedule(function()
    end)
  end
  vim.cmd([[autocmd CmdlineEnter * lua _G.on_cmdline_enter()]])
EOF
```

**Comment by famiu** [comment]
Should I close this issue then? I opened one in upstream. Or do you prefer keeping it open?

**Comment by hrsh7th** [comment]
If upstream is aware of the problem, it should be closed. Close. thank you!
