### ISSUE TITLE
cmdline preset mappings not working

### ISSUE THREAD

**Issue by axieax** [hrsh7th/nvim-cmp#894]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.1

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = cmp.mapping.preset.insert({
      ['<C-b>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.abort(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}

cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'path' }
    })
  })
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

```

### Description

Pressing `<tab>` after any partially-completed command won't do anything - neither triggers the Pmenu nor completion. 

### Steps to reproduce

Start typing `:P<tab>`

### Expected behavior

Pmenu and completion for commands starting with `P` will show up.

### Actual behavior

Just nothing... literally nothing...

### Additional context

This is pretty much the minimal config plus the `cmp.setup.cmdline(":")` bit which causes it to fail. Setting up cmdline completion for `"/"` seems to work fine. This could be related to https://github.com/hrsh7th/cmp-path/issues/38.

**Comment by codebycorey** [comment]
I have the similar issue. 

I upgraded nvim-cmp, switch to `cmp.mapping.preset.insert({})` and `<C-n>` closes the pmenu and I get a log of `Scanning for tags`.

**Comment by axieax** [comment]
oo I tried using `cmp.mapping.preset.insert()` instead of `cmp.mapping.preset.cmdline()` and I get my previous issue of `^I` characters appearing every time I press `<Tab>`.

**Comment by hrsh7th** [comment]
Sorry. I can't understand.

You specified the source for cmdline is `path` only. So I think if you don't type `~/`, nvim-cmp can't show anything.

**Comment by axieax** [comment]
> So I think if you don't type ~/, nvim-cmp can't show anything.

Actually using the `path` source works. It just also breaks normal command mode behaviour (i.e. without `path`).

**Comment by hrsh7th** [comment]
> It just also breaks normal command mode behaviour

Please explain what is your expected behaivior?

**Comment by axieax** [comment]
The expected behaviour is what was defined above in the initial issue post - basically getting completion for my command. Previously, typing `:P<Tab>` would bring up the Pmenu, but now it does not anymore.

**Comment by axieax** [comment]
Hmm that's weird, everything was working fine before 801a9f98bbae14135be3a04515b9350b145ce25b

**Comment by hrsh7th** [comment]
Ah. Sorry. Maybe the above commit fixes this issue. Could you try latest nvim-cmp?

**Comment by axieax** [comment]
Unfortunately that didn't fix it :((

**Comment by hrsh7th** [comment]
really??? In my environment, the last commit fixes this perfectly...

**Comment by axieax** [comment]
Hmm I'm not sure, but it doesn't seem to work with my default config or the minimal config provided above :((

**Comment by axieax** [comment]
Works perfectly tysm @hrsh7th :))

**Comment by cexoso** [comment]
I has the some question, so how you guys resolve the problem? what does the "updated the plugin oops" mean?

**Comment by cexoso** [comment]
> I has the some question, so how you guys resolve the problem? what does the "updated the plugin oops" mean?

it work, see #809

**Comment by axieax** [comment]
Sorry by "update the plugin", I mean fetching the latest commits from the plugin (haven't use Vim-plug for a very long time haha). Good to hear it works now. I'll just leave my config [here](https://github.com/axieax/dotconfig/blob/main/nvim/lua/axie/lsp/completion.lua) as a reference for others.
