### ISSUE TITLE
The new update that harshly remove all the default mappings without any notification is a bit abrupt, and we should give a notification of the breaking change

### ISSUE THREAD

**Issue by milanglacier** [hrsh7th/nvim-cmp#896]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

--HEAD

### Minimal reproducible full config

It is not a bug.

### Description

Just find the new update brings a sudden change:
The default mappings in every mode is removed, and instead we have to pass `mappings = cmp.mapping.preset.xxx {my new mappings}` to keep the default mapping plus the customized mappings. 

Otherwise, following my old configs, all the default maps are removed, and only the customized maps are kept.

I don't think this is a bad choice, but we should send notifications to the users and marked it as a breaking change, otherwise, it is not very user-friendly. It takes me sometimes to figure out the API of cmp just changed.

### Steps to reproduce

...

### Expected behavior

...

### Actual behavior

...

**Comment by wookayin** [comment]
> I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and there are no open or closed issues with the same problem.

Please see #895 #739

**Comment by milanglacier** [comment]
> > I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and there are no open or closed issues with the same problem.
> 
> Please see #895 #739. Although I totally agree.

I agree with the default mapping change. And It don't take much steps to retrieve the expected behavior once you come to the git repo to find what happens. But it really takes me some time to figure out it is CMP's issue. Since it is a breaking change, old user should have been noticed.

**Comment by hrsh7th** [comment]
I'm considering how to notice this and how to achive `deprecation period`.

Do you have any idea?
@wookayin @milanglacier

**Comment by milanglacier** [comment]
We can set up a log file, located at somewhere like `.cached/nvim` and give a notification like 
```
the default mapping is removed, you can retrieve the default mapping via cmp.mapping.preset.xxx. 
I am sure I know what has happening. [y/n]
```

If the user press y, write a record to the log file and will not send notification again.

**Comment by hrsh7th** [comment]
I don't see the essential difference between updating the plugin and changing its behavior.
In the future, consider issuing a notice in some way.

**Comment by acomagu** [comment]
Subscribing #231 notifies me all breaking changes including the change via GitHub.

**Comment by wookayin** [comment]
Deprecation warning could be made in that announcement thread. However it should NOT after a breaking change already has been made.

In this specific case, you could have detected whether a non-user-configured default keymap is being used and print a warning message upon config setup.

**Comment by gegoune** [comment]
@hrsh7th Would you be interested in creating versioned releases? You could do any breaking changes on main branch and notify users about them in release notes. Once you have releases it's up to users to 
- use main and update configuration according to any changes
- pin version using theirs plugin manager

There are GitHub actions available to ease and automate creation of release including release notes. I might be able to help setting it all up, there should already be few other plugins doing it as well to take inspiration from.

**Comment by runiq** [comment]
A simple way to announce the existence of https://github.com/hrsh7th/nvim-cmp/issues/231, at least for packer.nvim users, would be to add a new commit with a breaking change notification (i.e. `feat!`) and a link to https://github.com/hrsh7th/nvim-cmp/issues/231. Packer notices commits with breaking changes and emphasizes plugins that have them.

**Comment by Kjir** [comment]
The format mentioned is specified here: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by gegoune** [comment]
This repository does not follow conventional commits unfortunately. @hrsh7th That's another point which greatly help with generating changelogs and notes for releases.

**Comment by Kjir** [comment]
Here is how `nvim-treesitter` handles deprecations in a visible manner: https://github.com/nvim-treesitter/nvim-treesitter/commit/acd01551a3185118f58f0708b7fffdb2465e39f1

Their utility function is a simple wrapper around `vim.notify`:
```lua
-- Wrapper around vim.notify with common options set.
function M.notify(msg, log_level, opts)
  local default_opts = { title = "nvim-treesitter" }
  vim.notify(msg, log_level, vim.tbl_extend("force", default_opts, opts or {}))
end
```

This way users get a message every time they open `neovim` that looks like this:

![image](https://user-images.githubusercontent.com/64094/164672858-68fb6ebb-7c5b-4652-9147-351965452310.png)

By using `nvim-notify` it is possible to have even better messages (includes the name of the plugin that causes it):

![image](https://user-images.githubusercontent.com/64094/164673377-4d76f8cc-3915-4c88-bc0e-84ba4f713345.png)

Which is configured like this (with Packer):
```lua
	use({
		"rcarriga/nvim-notify",
		config = function()
			vim.notify = require("notify")
			vim.notify.setup({ timeout = 15000, stages = "fade" })
		end,
	})
```

I think such a warning would be extremely helpful before breaking changes, it only requires placing a warning for some time before doing the change itself
