### ISSUE TITLE
Update the example super tab like mappings

### ISSUE THREAD

**Issue by Daniel794** [hrsh7th/nvim-cmp#898]
@hrsh7th , could you please update the example super tab like [mappings](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#super-tab-like-mapping) with respect to the recent breaking [change](https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017)
Thanks in advance

**Comment by wookayin** [comment]
I think everybody has an edit access for wiki documents.

**Comment by Daniel794** [comment]
Actually, I am a beginner at using neovim with lua and am still learning how to do various config stuff. In a recent commit the older method of mapping was deprected and in the new method I am not sure how to achieve the same behaviour as 
```lua
mapping = {
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif vim.fn["vsnip#available"](1) == 1 then
        feedkey("<Plug>(vsnip-expand-or-jump)", "")
      elseif has_words_before() then
        cmp.complete()
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { "i", "s" }),
}
```
since in the new method I do not know how to configure the command in "s" mode
Any help is greatly appreciated.

**Comment by wookayin** [comment]
@dstadelm The commit 93cf84f [changed README](https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R82) in a way `cmp.mapping.preset.insert` is used, which will include the default keymapping behavior (plus some additional customizations as it says). But I agree README could be even further improved, since what `cmp.mapping.preset.insert` means is not crystal clear.

**Comment by Liverm0r** [comment]
Also a newbie to Lua and nvim  I couldn't achieve such a basic thing as the abitlity to select_next_item. I've created a [question](https://www.reddit.com/r/neovim/comments/u2ztyb/why_tab_in_lspcmpluasnip_doesnt_select_next_iterm/) on reddit, and people say It could be due to the bracking changes.

The problem example. If I press tab (or cmp.mapping.select_next_item) here, the first snippet 'letfn' is inserted and completion menu is closed.
![image](https://user-images.githubusercontent.com/14236531/163550860-4a539f10-6cca-43c0-929e-1b7269adb205.png)
So I have no way to move to the next 'let' snippet.

I solved it only when read this thread and found out this commit https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558
Problem was due to the necessity to provide `behavior cmp.SelectBehavior.Select` to  `cmp.mapping.select_next_item`.

So as someone who spent hours to get just a basic behavior, I would like to vote for the OP suggestion with example updation and may some readme extension.

**Comment by hrsh7th** [comment]
I think it's a bug if the completion menu is closed after `cmp.mapping.select_next_item`.
(And I'm confused I don't change `SelectBehavior` implementation.)

**Comment by Liverm0r** [comment]
It's closed only if the next item is Snippet.

**Comment by hrsh7th** [comment]
@Liverm0r I guess it's caused by your mapping setting. Could you provide it?

**Comment by hrsh7th** [comment]
BTW, I don't recommend using both `<Tab>` as item navigation and snippet expansion. So I can't update the wiki... (I can't understand the expected behavior that is wanted by the users.

**Comment by Liverm0r** [comment]
I have my config in fennel, it look like this:

Packer:
```fennel
  :hrsh7th/nvim-cmp {:requires [:hrsh7th/cmp-buffer
                                :hrsh7th/cmp-nvim-lsp
                                :hrsh7th/cmp-path
                                :hrsh7th/cmp-cmdline
                                :L3MON4D3/LuaSnip
                                :saadparwaiz1/cmp_luasnip
                                :PaterJason/cmp-conjure]
                     :mod :cmp}
```

Plugin module code:
```fennel
(module plugin.cmp
  {autoload {nvim aniseed.nvim
             cmp cmp
             luasnip luasnip}})

(def- cmp-src-menu-items
  {:buffer "buff"
   :conjure "conj"
   :name :cmdline
   :nvim_lsp "lsp"})

(def- cmp-srcs
  [{:name :nvim_lsp}
   {:name :conjure}
   {:name :buffer}
   {:name :path}
   {:name :cmdline}
   {:name :luasnip}])

(defn luasnip-tab [fallback]
  (if 
    (cmp.visible)
    ;; here I have to provide SelectBehavior.Select to fix my above issue
    (cmp.select_next_item {:behavior cmp.SelectBehavior.Select}) 
    
    (luasnip.expand_or_jumpable)
    (vim.fn.feedkeys 
      (vim.api.nvim_replace_termcodes 
        "<Plug>luasnip-expand-or-jump" true true true) 
      "")
    
    (fallback)))

(cmp.setup.cmdline "/" {:mapping (cmp.mapping.preset.cmdline)}
                   :sources [{:name :buffer}])

(cmp.setup.cmdline ":" {:mapping (cmp.mapping.preset.cmdline)
                        :sources (cmp.config.sources [{:name :cmdline}] 
                                                     {:name :path})})

;; Setup cmp with desired settings
(cmp.setup {:formatting
            {:format (fn [entry item]
                       (set item.menu (or (. cmp-src-menu-items entry.source.name) ""))
                       item)}

            :mapping {:<Tab> intellij-tab
                      :<S-Tab> (cmp.mapping.select_prev_item {:behavior cmp.SelectBehavior.Select})
                      :<down> (cmp.mapping.select_next_item {:behavior cmp.SelectBehavior.Select})
                      :<up> (cmp.mapping.select_prev_item {:behavior cmp.SelectBehavior.Select})
                      :<C-b> (cmp.mapping.scroll_docs (- 4))
                      :<C-f> (cmp.mapping.scroll_docs 4)
                      :<C-Space> (cmp.mapping.complete)
                      :<C-e> (cmp.mapping.close)
                      :<CR> (cmp.mapping.confirm {:behavior cmp.ConfirmBehavior.Replace
                                                  :select true})}
            :sources cmp-srcs
            :confirm_opts {:behavior cmp.ConfirmBehavior.Replace
                           :select false}
            :snippet {:expand (fn [args] (luasnip.lsp_expand args.body))}})
```

Wihtout me providing Select-behavior like `(cmp.select_next_item {:behavior cmp.SelectBehavior.Select}) ` and have this problem without the ability choose next (and inserting it).

**Comment by Liverm0r** [comment]
Capabilities are passed to lsp just like in lsp-wiki example:
```fennel
(cmplsp.update_capabilities
  (vim.lsp.protocol.make_client_capabilities))
  ```

**Comment by mjlbach** [comment]
I'm not an autocompletion user, so I would also be interested if I should update the example cmp configuration in the lspconfig wiki wrt to <tab>

**Comment by hrsh7th** [comment]
Sorry. I can't read fenel...

**Comment by hrsh7th** [comment]
@mjlbach This page seems good to me. (https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion

The `<Tab>` and `<S-Tab>` should be specified the modes as `'i', 's'`, I think. I'll update.

**Comment by hrsh7th** [comment]
done. (lspconfig wiki updated)

**Comment by mjlbach** [comment]
Ah cool, I use the same example configuration on the autocompletion and snippets page of the lspconfig wiki, as well as [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua), I feel like a lot of people yank it from there so just want to be sure I'm not spreading bad habits :)

**Comment by mjlbach** [comment]
This change? https://github.com/nvim-lua/kickstart.nvim/pull/54/files

**Comment by hrsh7th** [comment]
Please someone update the wiki. I think @mjlbach 's suggestion is correct (But I can't maintain the wiki because I don't use and can't understand the mapping.
