### ISSUE TITLE
After the latest commit (7e07dd5), it was totally broken

### ISSUE THREAD

**Issue by rockyzhang24** [hrsh7th/nvim-cmp#899]
### FAQ

- [x] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1453-g8486c87e5

### Minimal reproducible full config

local cmp = require('cmp')
local lspkind = require('lspkind')

cmp.setup({

  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },

  -- Border
  -- window = {
  --   completion = cmp.config.window.bordered(),
  --   documentation = cmp.config.window.bordered(),
  -- },

  -- Insert mode mappings
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<C-y>'] = cmp.mapping.confirm({ select = true }),
    -- Then the default <C-n> and <C-p> for selecting the next/previous item
  }),

  sources = cmp.config.sources({
    -- The order of the sources gives them priority, or use priority = xxx to specify it.
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
    { name = 'buffer', keyword_length = 4 },
    { name = 'path' },
    { name = 'nvim_lua' }, -- nvim_lua make it only be enabled for Lua filetype
  }),

  formatting = {
    -- Icons
    format = lspkind.cmp_format({
      mode = "symbol_text",
      menu = ({
        buffer = "[buf]",
        nvim_lsp = "[LSP]",
        luasnip = "[snip]",
        nvim_lua = "[lua]",
        path = "[path]",
      })
    }),
    -- Adjust the order of completion menu fields
    -- fields = {
    --   'abbr',
    --   'kind',
    --   'menu',
    -- },
  },

  experimental = {
    ghost_text = true,
  },

})

### Description

After the newest [commit](https://github.com/hrsh7th/nvim-cmp/commit/7e07dd50ac1264b4a7936b16445488c9150d4556),  `nvim-cmp` became totally broken. While I'm typing, no complete menu pops out. Executing `cmp.mapping.complete()` still gives nothing. 

### Steps to reproduce

Update to the newest commit and then type something. 

### Expected behavior

It should work as normal. 

### Actual behavior

Broken totally, i.e., no complete menu pops out.

**Comment by lessthanseventy** [comment]
Same for me

**Comment by cleong14** [comment]
Same here

**Comment by muji-wyh** [comment]
Same here

**Comment by ichirou2910** [comment]
I think I found out the problem. It's in file `misc.lua` line 102-104 (as in the image). Changing the condition to just `merge2` solve the issue for me.
![image](https://user-images.githubusercontent.com/51302893/163316234-7d5fbd50-51a1-4005-8f65-1674efcbde9d.png)

**Comment by JryChn** [comment]
me 2 , waiting for fix

**Comment by rockyzhang24** [comment]
@ichirou2910 Yes. I noticed this as well. Let's wait dear author to fix it 🥳

**Comment by d11638104** [comment]
me too, lets wait dear author to fix it

**Comment by jorgerojas26** [comment]
Same problem here. Totally broken, menu doesn't pop up.

**Comment by jorgerojas26** [comment]
> I think I found out the problem. It's in file `misc.lua` line 102-104 (as in the image). Changing the condition to just `merge2` solve the issue for me. ![image](https://user-images.githubusercontent.com/51302893/163316234-7d5fbd50-51a1-4005-8f65-1674efcbde9d.png)

This worked for me, but i'll wait for author to fix it.

**Comment by liuyangzys** [comment]
Me too.

**Comment by Shougo** [comment]
Well, what is the minimal vimrc?
I will check it.

**Comment by hrsh7th** [comment]
Sorry. It's my bad work. I'll revert it after back my home.

**Comment by Shougo** [comment]
From the author, he notices the broken.
But he cannot fix it immediately.
Please wait until the fix.

**Comment by rockyzhang24** [comment]
@Shougo No minimal vimrc required. Update your plugin and use your own vimrc.

**Comment by Shougo** [comment]
Oh..

**Comment by hungrybirder** [comment]
After update `nvim-cmp` to latest commit(ec8e87ce5c74b3c1ff59d8dbffeb4ce5e29523a7), it still does not work for me.

**Comment by vanhtuan0409** [comment]
Lets be nice and dont push the author. I think in the mean time, we can roll back to commit dbc722

I think most package manager is able to specify the commit hash

**Comment by rockyzhang24** [comment]
@vanhtuan0409 No one pushes the author. Just a bug report and nothing else.

**Comment by vanhtuan0409** [comment]
@rockyzhang24 I don't mean to say that you are pushing and thank you for raising the issue anyway
I was trying to say that the author has already acknowledged the issue so maybe we should just wait for him to fix it :D
