### ISSUE TITLE
Feature: If completion window is positioned above cursor, display results from bottom-up

### ISSUE THREAD

**Issue by b0o** [hrsh7th/nvim-cmp#910]
When the cursor is near the bottom of the window, or when complething cmdlines/searches, the completion window appears above the cursor. It would be nice to have an option to display results starting from the bottom of the completion window in these cases.

It makes sense to me that the best match should be nearest the cursor, to minimize eye movement and scanning. This would also mean that the window should start scrolled to the bottom.

Related: #495

**Comment by hrsh7th** [comment]
This is implemented (as an unstable undocumented feature) recently.

```lua
    view = {
      entries = { name = 'custom', selection_order = 'bottom_up' }
    },

```

**Comment by b0o** [comment]
Oh, awesome, thank you! This doesn't work exactly how I wanted &ndash; I'd prefer `select_next_item` to always go "down" and  `select_prev_item` to always go "up". So I wrote these mappings which do the job:

```lua
mapping = cmp.mapping.preset.insert {
 ['<C-n>'] = function(fallback)
   if cmp.visible() then
     if cmp.core.view.custom_entries_view:is_direction_top_down() then
       cmp.select_next_item()
     else
       cmp.select_prev_item()
     end
   else
     fallback()
   end
 end,
 ['<C-p>'] = function(fallback)
   if cmp.visible() then
     if cmp.core.view.custom_entries_view:is_direction_top_down() then
       cmp.select_prev_item()
     else
       cmp.select_next_item()
     end
   else
     fallback()
   end
 end,
}
```

(sorry for using your private APIs 😉)
