### ISSUE TITLE
Scrolling Popmenu with <C-N> and <C-P> resets keyword completion

### ISSUE THREAD

**Issue by flaphoschi** [hrsh7th/nvim-cmp#916]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7.0

### Minimal reproducible full config
```
" plugins
call plug#begin()
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-calc'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'
call plug#end()


" setup nvim-cmp
set completeopt=menu,menuone,noselect

lua << EOF
local cmp = require'cmp'

cmp.setup({
	snippet = {
		-- snippet engine require for full functionality
		expand = function(args)
			vim.fn["vsnip#anonymous"](args.body)
		end,
	},
	mapping = {
		['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
		['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
		['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
		['<C-y>'] = cmp.config.disable, -- remove the default `<C-y>` mapping
		['<C-e>'] = cmp.mapping({
			i = cmp.mapping.abort(),
			c = cmp.mapping.close(),
		}),
		['<CR>'] = cmp.mapping.confirm({ select = true }), -- accept currently selected item
	},
	sources = cmp.config.sources({
		{ name = 'nvim_lsp' },
		{ name = 'vsnip' },
		{ name = 'buffer' },
		{ name = 'path' },
		{ name = 'calc' },
	})
})

-- completion for '/'
-- not available with native_menu
cmp.setup.cmdline('/', {
	sources = {
		{ name = 'buffer' }
	}
})

-- completion for ':'
-- not available with native_menu
cmp.setup.cmdline(':', {
	sources = cmp.config.sources({
		{ name = 'path' }
	}, {
		{ name = 'cmdline' }
	})
})

-- setup lspconfig
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
require('lspconfig')['clangd'].setup {
	capabilities = capabilities
}
EOF
```

### Description

Hello!
After upgrading neovim I assumed upgrading nvim-cmp would be a good idea. When I enter a variable name the popmenu shows up with the expected completions from LSP but as soon as I started scrolling with N/P the completion resets somehow:

### Steps to reproduce

1.) trigger autocompletion
2.) press `<C-N>` to reach first iteam

### Expected behavior

Select item below in this case "append(...)~".

### Actual behavior

Popupmenu resets and presents non-related items.

### Additional context

![Screenshot from 2022-04-18 12-43-07](https://user-images.githubusercontent.com/3392113/163798418-f3d0604c-3d34-4804-ab8f-fb114a22d771.png)
After pressing `.`
![Screenshot from 2022-04-18 12-43-14](https://user-images.githubusercontent.com/3392113/163798454-4a26931c-1796-4bb7-87b7-6affd34cb786.png)
After pressing `<C-N>` just once.

**Comment by hrsh7th** [comment]
The recently commit removes the default mapping see https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017

So your config doesn't have the `<C-n>` `<C-p>` mapping. Please add these.

**Comment by plastic041** [comment]
If anyone have this issue despite having proper `<C-n>` and `<C-p>` mappings, check if you have `set paste` on your `init.vim`.

see: https://www.reddit.com/r/neovim/comments/w9cu6c/comment/ihwo1jg/?utm_source=share&utm_medium=web2x&context=3

**td;dr**: if there is `set paste` in your `init.vim`, `cmp.setup({ mapping ... })` does not work(other settings like `sources`, `formatting`... seems work fine though)
