### ISSUE TITLE
Using Borders adds unwanted gaps

### ISSUE THREAD

**Issue by par4m** [hrsh7th/nvim-cmp#927]
Before, without Borders:
Normal:
![image](https://user-images.githubusercontent.com/68808783/164480166-61ec745f-f4c3-4dd5-803c-c8fae976b1f8.png)

Cmdline:
![image](https://user-images.githubusercontent.com/68808783/164480250-d486352f-0e70-4427-be85-ed31fa72060a.png)

After, with Borders:
```lua
window = {
    documentation = {
      border = {'┌', '─', '┐', '│', '┘', '─', '└', '│'},
      winhighlight = 'Normal:CmpPmenu,FloatBorder:CmpPmenuBorder,CursorLine:PmenuSel,Search:None', 
    },
completion = {
      border = {'┌', '─', '┐', '│', '┘', '─', '└', '│'},
      winhighlight = 'Normal:CmpPmenu,FloatBorder:CmpPmenuBorder,CursorLine:PmenuSel,Search:None', 
    }
  },
} 

vim.cmd("highlight! link CmpPmenu         Pmenu")
vim.cmd("highlight! link CmpPmenuBorder   Pmenu")
vim.cmd("highlight! CmpPmenu         guibg=#282828")
vim.cmd("highlight! CmpPmenuBorder   guifg=#615750")
```
Normal: gap under text and documentation window
![image](https://user-images.githubusercontent.com/68808783/164480717-5c6716f5-b0db-4556-a9ad-a01b8be88337.png)

Cmdline: 
![image](https://user-images.githubusercontent.com/68808783/164481355-24a4e495-f625-4e0e-86fd-c09e11b896b8.png)

**Comment by hrsh7th** [comment]
It's exoected and impossible to solve.
