### ISSUE TITLE
Indications in the `documentation` deprecation notice cause an error

### ISSUE THREAD

**Issue by wincent** [hrsh7th/nvim-cmp#936]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0

### Minimal reproducible full config

```
cmp.setup {
  documentation = { border = 'single' },
}
```

### Description

If you upgrade to a recent version of nvim-cmp containing old config like the above, it [prints](https://github.com/hrsh7th/nvim-cmp/blob/433af3dffce64cbd3f99bdac9734768a6cc41951/lua/cmp/config.lua#L194-L205) a deprecation notice of the form:

    [nvim-cmp] documentation is deprecated.
    [nvim-cmp] Please use window.documentation = "native" instead.

If you follow this advice literally, ie. with:

```
cmp.setup {
  window = {
    documentation = 'native',
  },
}
```

You'll get errors like these due to `documentation.max_width` being `nil`:

```
Error executing vim.schedule lua callback: ...nvim/pack/bundle/opt/nvim-cmp/lua/cmp/view/docs_view.lua:38: bad argument
     #1 to 'min' (number expected, got nil)
    stack traceback:
            [C]: in function 'min'
            ...nvim/pack/bundle/opt/nvim-cmp/lua/cmp/view/docs_view.lua:38: in function 'open'
            ...t/.config/nvim/pack/bundle/opt/nvim-cmp/lua/cmp/view.lua:229: in function 'callback'
            ...ig/nvim/pack/bundle/opt/nvim-cmp/lua/cmp/utils/async.lua:95: in function ''
            vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

As above.

### Expected behavior

Deprecation notice should include a config suggestion that will work without errors.

### Actual behavior

Described above.

### Additional context

The workaround is to provide a well-formed and complete config object; eg:

```
cmp.setup {
  window = {
    documentation = cmp.config.window.bordered(),
  },
}
```

**Comment by jc00ke** [comment]
Thanks for the workaround! :pray:

**Comment by wookayin** [comment]
Related: #920 (actually the same bug)

**Comment by hrsh7th** [comment]
PR welcome.

**Comment by wincent** [comment]
> PR welcome.

See: https://github.com/hrsh7th/nvim-cmp/pull/946

**Comment by sativ01** [comment]
A note for beginners like myself:
after doing all the above and still having seeing error/warning:
!!! remove `packer_compiled.lua` file !!!

**Comment by yanke1311** [comment]
> 

after remove `packer_compiled.lua` deprecation notice still happend

**Comment by eduardo-sdev** [comment]
replace the documentation key in cmp.setup:

```
	documentation = {
	   ...
	}
```

with

```
	window = {
	    documentation = {
	       ...
	    }
	}
```

for example, this works:

```
  window = {
    documentation = {
      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    },
  },
```
