### ISSUE TITLE
How to get completion on prompts

### ISSUE THREAD

**Issue by marko-cerovac** [hrsh7th/nvim-cmp#938]
Is there a way to get completion using nvim-cmp when answering to a prompt using ```input()``` function.  I'm using cmp-cmdline and it works like a charm in regular command mode, but when I'm answering a prompt that normally provides completion (```h command-completion```), nvim-cmp doesn't show up.

**Comment by hrsh7th** [comment]
I think it's impossible. Because we can't specify any cmdtype for `input()`.
See `:h getcmdtype()`

**Comment by Shougo** [comment]
`getcmdtype()` returns input type `@`.  But it does not return `input()` completion type.

**Comment by marko-cerovac** [comment]
I see that you enabled the default completion for ```input()```. Thank a lot, works great.

**Comment by Shougo** [comment]
Please see https://github.com/neovim/neovim/pull/18284#issuecomment-1112925925.

**Comment by shadyalfred** [comment]
Does this work now? I'm trying to get path completions for dap's input prompt, it needs the path of the compiled file. Path completions are appearing when I enter excommands tho, like cd etc.

**Comment by Shougo** [comment]
I have implemented the feature, but needs plugin support to enable it.

**Comment by eyalk11** [comment]
Doesn't seem to work  for me . 
https://vi.stackexchange.com/questions/43798/input-with-completion-in-times-of-lua-nvim-cmp

**Comment by Shougo** [comment]
nvim-cmp does not support the feature yet.
