### ISSUE TITLE
How to disable argument snippet for class

### ISSUE THREAD

**Issue by fecet** [hrsh7th/nvim-cmp#947]
The snippet argument feature is pretty good for mu, but I do not want to use it for some type, say, class, and enable it for function. How to achieve this?

**Comment by fecet** [comment]
@hrsh7th Sorry for confusing, I would like to complete "foo" to "foo(a,b)", but only "Foo()" for "Foo" 

https://user-images.githubusercontent.com/41792945/166145874-a731c207-4a08-4d97-b37c-e765d211291b.mp4

**Comment by hrsh7th** [comment]
The nvim-cmp's behaivior is depending to your kanguage server. Ithink you should report it to Language Server's repo.
