### ISSUE TITLE
Some mappings don't work as expected in cmdline

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [hrsh7th/nvim-cmp#949]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+41-g2caf5bbbc

### Minimal reproducible full config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-cmdline'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      local complete_or_next = not cmp.visible() and cmp.mapping.complete()
        or cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Insert }

      complete_or_next(fallback)
    end, { 'c' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      local complete_or_prev = not cmp.visible() and cmp.mapping.complete()
        or cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Insert }

      complete_or_prev(fallback)
    end, { 'c' }),
  },
}


cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'cmdline' },
  }),
})
EOF
```

### Description

on `<tab>`/`<S-tab>`, when `cmp.visible() ~= true`, cmp doesn't open as described in the mappings.

### Steps to reproduce

1) Enter cmdline mode (:)
2) press `<tab>` or `<S-tab>`

### Expected behavior

cmp should open on first `<tab>` or `<S-tab>`.

### Actual behavior

cmp doesn't open on first `<tab>` or `<S-tab>`.

### Additional context

The mapping described above works when:
1) Enter cmdline mode
2) press any other alphabet, cmp should open as expected, exit and enter cmdline line mode.
3) Press `<tab>` or `<S-tab>`, this time cmp opens

https://user-images.githubusercontent.com/95099980/166105553-8ab5ac0f-da13-4a31-a263-6c31531ade35.mp4

**Comment by RaafatTurki** [comment]
Same thing with `cmp.setup.cmdline('/', {...})`, the first tab prints `^Z`

**Comment by MurdeRM3L0DY** [comment]
> Same thing with `cmp.setup.cmdline('/', {...})`, the first tab prints `^Z`

With which source?

**Comment by MurdeRM3L0DY** [comment]
More additional context:
1) get cmp to show up
2) exit cmdline with `<BS>` instead of `<ESC>`
3) re-enter cmdline mode, now `<tab>` / `<S-tab>` works as expected as long as you don't exit cmdline mode with `<ESC>`

https://user-images.githubusercontent.com/95099980/166124537-13479277-83fc-438c-bf22-bdf9021a35f0.mp4

Weird :confused:

**Comment by RaafatTurki** [comment]
@MurdeRM3L0DY with the buffer source like so
```lua
  cmp.setup.cmdline('/', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'buffer' }
    }
  })
```

**Comment by hrsh7th** [comment]
@MurdeRM3L0DY I think this issue now fixed via https://github.com/hrsh7th/cmp-cmdline/commit/c36ca4bc1dedb12b4ba6546b96c43896fd6e7252

**Comment by RaafatTurki** [comment]
Unfortunately no it's still there for both `:` and `/`

**Comment by RaafatTurki** [comment]
Unfortunately no it's still there for both `:` and `/`

**Comment by MurdeRM3L0DY** [comment]
@hrsh7th That fixes it for me, thanks!
