### ISSUE TITLE
Increase size of vscode codeicons

### ISSUE THREAD

**Issue by kaykhancheckpoint** [hrsh7th/nvim-cmp#951]
I am following this section of the wiki to get vscode like icons https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-codicons-to-the-menu

However they appear much smaller on mine than the example screenshot, is there any way to increase their size?

![image](https://user-images.githubusercontent.com/65535942/166154553-2ebf162e-027c-4d04-8439-9939d424e846.png)
![image](https://user-images.githubusercontent.com/65535942/166154581-376b714f-765d-40ad-9b3f-d6fa5b377d6f.png)

**Comment by bew** [comment]
This is not an issue with this plugin.
The limited size is either that the font with that symbol indicate it should be in a single cell, or it is your terminal that do not support rendering symbols on 2 cells.
I'd suggest checking your terminal's config, and if necessary, open a feature request for that.

**Comment by hrsh7th** [comment]
It's out of scope of nvim-cmp. Please organize your terminal settings.

**Comment by kaykhancheckpoint** [comment]
> This is not an issue with this plugin. The limited size is either that the font with that symbol indicate it should be in a single cell, or it is your terminal that do not support rendering symbols on 2 cells. I'd suggest checking your terminal's config, and if necessary, open a feature request for that.

Hi thank you for the explaination, what should i be looking for in my terminal config ? Just fyi i use the gnome terminal in ubuntu with zsh and tmux if that helps.

**Comment by kaykhancheckpoint** [comment]
> It's out of scope of nvim-cmp. Please organize your terminal settings.

Okay,, could you give me an idea what i should be looking for? What are you suggesting when you say organise terminal settings? I'm really  unsure what i shiuld be looking for

**Comment by kaykhancheckpoint** [comment]
Im also using the https://github.com/be5invis/Iosevka font "Iosevka Regular Term", could it be an issue with the font i use?

**Comment by hrsh7th** [comment]
Really sorry but I don't familiar to terminal so I can't suggest any solution.

I want only to say it's out of scope of nvim-cmp.
