### ISSUE TITLE
Cannot move through autocompletion suggestions with arrow keys

### ISSUE THREAD

**Issue by hood** [hrsh7th/nvim-cmp#957]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.8-dev (latest nightly)

### Minimal reproducible full config

```lua
  require'lspkind'.init()

  local cmp = require'cmp'

  cmp.setup({
    window = {
      completion = {
        border = 'rounded',
        scrollbar = '║',
      },
      documentation = {
        border = 'double',
        scrollbar = '║',
      },
    },
    snippet = {
      expand = function(args)
        vim.fn["UltiSnips#Anon"](args.body)
      end,
    },
    mapping = {
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-c>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<Cr>'] = cmp.mapping.confirm({ select = true }),
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'ultisnips' },
      -- { name = 'buffer' },
    }),
    formatting = {
      format = require'lspkind'.cmp_format{
        with_text = true,
        menu = {
          -- buffer = "[buf]",
          nvim_lsp = "[LSP]",
          path = "[path]",
        }
      }
    },
    completion = {
      completeopt = 'menu,menuone,noinsert,preview',
    }, 
    flags = {
      debounce_text_changes = 10,
    },
  })
```

### Description

As of today, after updating my `nvim-cmp` to the latest `dev` branch's commit, I cannot move through my autosuggestion items with my arrow keys anymore. Pressing arrow keys will move my cursor as if no menu was open.

### Steps to reproduce

Spawn a nvim-cmp completion popup, then use arrow keys up/down to try and navigate its suggestions.

### Expected behavior

being able to pick and choose autosuggestion items

### Actual behavior

cursor moving as if not popup had been spawned at all

**Comment by hrsh7th** [comment]
Using `dev` branch is your own risk and read the breaking xhange announcement...

**Comment by hrsh7th** [comment]
See this. https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017

You can use other completion engine.

**Comment by MichaHoffmann** [comment]
Adding the mappings
```
    ['<Down>'] = cmp.mapping(cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
    ['<Up>'] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
```
makes it work again on my machine

**Comment by hood** [comment]
> Adding the mappings
> 
> ```
>     ['<Down>'] = cmp.mapping(cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
>     ['<Up>'] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
> ```
> 
> makes it work again on my machine

Yep, thanks for the tip. I had figured it out on my own anyway in the meantime.
