### ISSUE TITLE
nvim-cmp interferes with filetype detection

### ISSUE THREAD

**Issue by dstadelm** [hrsh7th/nvim-cmp#958]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

VIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Minimal reproducible full config

init.lua
boot strap with 
```
$ nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```
```
function nnoremap(lhs, rhs, opts)
    local options = { noremap = true}
    if opts then
        options = vim.tbl_extend("force", options, opts)
    end
    vim.api.nvim_set_keymap('n', lhs, rhs, options)
end
vim.g.mapleader = ','
nnoremap("<leader>e", ':e <C-R>=expand("%:p:h") . "/" <CR>', {silent = false})


--------------------------------------------------------------------------------
-- This section has to be before the startup function
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end
--
--------------------------------------------------------------------------------

return require('packer').startup({function(use)
  -- Packer can manage it self
  use 'wbthomason/packer.nvim'


  use {
    'hrsh7th/nvim-cmp',
    requires = {
      'hrsh7th/cmp-buffer',
      'hrsh7th/cmp-nvim-lsp',
      'hrsh7th/cmp-path',
      'hrsh7th/cmp-calc',
      'hrsh7th/cmp-cmdline',
    },

    config = function()


      vim.o.completeopt='menu,menuone,noselect'
      local cmp = require'cmp'
      local types = require('cmp.types')
      cmp.setup({
        completion = {
          completeopt = 'menu,menuone,noselect',
          --  autocomplete = true,
        },

        mapping = cmp.mapping.preset.insert({
          ['<C-b>'] = cmp.mapping.scroll_docs(-4),
          ['<C-f>'] = cmp.mapping.scroll_docs(4),
          ['<C-Space>'] = cmp.mapping.complete(),
          ['<C-e>'] = cmp.mapping.abort(),
          ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
        }),
        sources = cmp.config.sources(
        {
          { name = 'buffer' },
          { name = 'path' },
          { name = 'calc' },
        })
      })

      -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
      cmp.setup.cmdline('/', {
        mapping = cmp.mapping.preset.cmdline(),
        sources = {
          { name = 'buffer' }
        }
      })

      -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
      cmp.setup.cmdline(':', {
        mapping = cmp.mapping.preset.cmdline(),
        sources = cmp.config.sources({
          { name = 'path' }
        }, {
          { name = 'cmdline' }
        })
      })
    end

  }


  ---- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end,
config = {
  display = {
    open_fn = function()
      return require('packer.util').float({ border = 'single' })
    end
  }
}
}
)
```

### Description

After several hours of debugging it boils down to this:
When switching between files all of a sudden the syntax highlighting is gone. In that case the filetype is set to nothing. Also syntax is set to nothing.

### Steps to reproduce

There is no straight forward way to do this but use the minimal example and open 5 to 15 files with different extensions.

### Expected behavior

nvim-cmp should not interfere with filetype detection and syntax setting? 

### Actual behavior

nvim-cmp prevents neovim of setting filetype?

**Comment by Shougo** [comment]
Hmm..
You should not include packer configuration in minimal init.vim.
Because other people cannot test your configuration.

**Comment by hrsh7th** [comment]
Sorry. I can't understand.
Does this only happen if nvim-cmp is present?

**Comment by dstadelm** [comment]
Sorry about packer, what would the correct way be?

Yes, it only happens when nvim-cmp is present.

**Comment by hrsh7th** [comment]
This line seems to relate to this issue.
https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/feedkeys.lua#L21

**Comment by hrsh7th** [comment]
Could you remove,thus and then re-tests?

**Comment by hrsh7th** [comment]
@dstadelm I think this issue was fixed by latest nvim-cmp!

**Comment by dstadelm** [comment]
I'll try with the new version when the kids are in bed ;-)

**Comment by dstadelm** [comment]
Indeed, it seems the last commit resolved the issue. 

Thank you so much!

I love the neovim community the rapid response of all plugin developers is unbelievable.

This is in my opinion one of the best plugins. I absolutely love the completion mode for the search, ingenious! How could one live without this feature.
