### ISSUE TITLE
`Ctrl-n` triggers a different list than previously shown by cmp

### ISSUE THREAD

**Issue by Murderlon** [hrsh7th/nvim-cmp#959]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7.0

### Minimal reproducible full config

Happen on [my own config](https://github.com/Murderlon/dotfiles/blob/main/nvim/.config/nvim/lua/merlijn/config/cmp.lua) as well as the [debug template](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim).

### Description

I get suggestions from cmp, for instance for the LSP, but hitting `Ctrl-n` (or `p`) gives me different results.

https://user-images.githubusercontent.com/9060226/166480743-76633ef9-249d-42ff-9cd9-eafc13eefbc8.mov

I tried a lot of combinations for [`complete`](https://vimhelp.org/options.txt.html#%27complete%27) to see if anything was interfering (such as scanning tags), but it didn't help.  

### Steps to reproduce

In the [debug template](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim) it happens differently for me, it doesn't show a different list but I can't go through the list at all with `Ctrl-n`.

### Expected behavior

Keep the same list as previously shown in the video, instead of suddenly showing a different completion list.

### Actual behavior

See video.

### Additional context

To me it seems like it happen with cmp, I'm sorry if that's not the case.

**Comment by hrsh7th** [comment]
See this https://github.com/hrsh7th/nvim-cmp/issues/231#issuecomment-1098175017

You should define C-n mapping by yourself.

**Comment by Murderlon** [comment]
Thank you and sorry for not catching that myself.

**Comment by plastic041** [comment]
If anyone still having this issue despite having proper settings, check https://github.com/hrsh7th/nvim-cmp/issues/916#issuecomment-1200099385
