### ISSUE TITLE
incsearch not working

### ISSUE THREAD

**Issue by craftzdog** [hrsh7th/nvim-cmp#963]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7.0

### Minimal reproducible full config

```vim
if !exists('g:loaded_cmp') | finish | endif

set completeopt=menuone,noinsert,noselect

" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

lua <<EOF
  local cmp = require'cmp'
  local lspkind = require'lspkind'

  cmp.setup({
    snippet = {
      expand = function(args)
        require('luasnip').lsp_expand(args.body)
      end,
    },
    mapping = cmp.mapping.preset.insert({
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<CR>'] = cmp.mapping.confirm({
        behavior = cmp.ConfirmBehavior.Replace,
        select = true
      }),
    }),
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
    }, {
      { name = 'buffer' },
    }),
    formatting = {
      format = lspkind.cmp_format({with_text = false, maxwidth = 50})
    }
  })

  vim.cmd [[highlight! default link CmpItemKind CmpItemMenuDefault]]
EOF
```

### Description

Found that this commit breaks `incsearch` and `inccommand=split`:
https://github.com/hrsh7th/nvim-cmp/commit/5054c14

I rolled back to bba6fb6 for now.

### Steps to reproduce

1. Hit `/` and type words.

Or,

1. Hit `:%s/` and type words.

### Expected behavior

nvim should highlight matched text as you type without hitting the return key.

### Actual behavior

not highlighting

### Additional context

Thanks for the great plugin🙏

**Comment by hrsh7th** [comment]
Thank you! I'll check it.

**Comment by IsaacClank** [comment]
Can confirm I also have this problem.

**Comment by max397574** [comment]
Can confirm I also got the problem (and like 3 other people I talked with got it as well)

**Comment by anstadnik** [comment]
I did a binary search, and found out that the cause are some of the extension plugins, in particular:
```
hrsh7th/cmp-buffer
f3fora/cmp-spell
andersevenrud/cmp-tmux
```
What's interesting is that `hrsh7th/cmp-nvim-lsp` didn't introduce the issue.
By the way, I commented out all setup functions, so just loading a plugin seem to be sufficient.
