### ISSUE TITLE
Any way to get transparency in completion menu?

### ISSUE THREAD

**Issue by Lalit64** [hrsh7th/nvim-cmp#969]
Hey @hrsh7th is there any way of getting transparency in the completion menu. Some thing like this ↓

![image](https://user-images.githubusercontent.com/79628080/166949722-67bf7619-6c5b-4243-90e2-c397645103d1.png)

**Comment by niscolas** [comment]
You can use (in lua)
```lua
vim.cmd("highlight Pmenu guibg=NONE")
```

**Comment by Shougo** [comment]
Please set `pumblend` option.

**Comment by Mo8it** [comment]
`pumplend` did it for me :) Thanks!

**Comment by Shougo** [comment]
It should be closed.

**Comment by Koalhack** [comment]
Use transparent.nvim plugin with `Pmenu` `Float` `NormalFloat` highlight group.
