### ISSUE TITLE
LSP snippets incorrectly expanded

### ISSUE THREAD

**Issue by spywhere** [hrsh7th/nvim-cmp#97]
Not sure if this is from `nvim-cmp` or `nvim-cmp-lsp`, but when using [emmet-ls](https://github.com/aca/emmet-ls) with `nvim-cmp`, it give the output as in the screenshot.

Autocompletion suggestions
![unexpand](https://user-images.githubusercontent.com/1087399/131072247-e056daee-224b-413c-b592-f8d6efd9ad5e.png)

Once select the suggestion
![expanded](https://user-images.githubusercontent.com/1087399/131072289-ab02e705-89bc-441a-a23b-ab4a843aed7d.png)

I also notice that on the `emmet-ls` repository, there seems to be [an issue for compe support](https://github.com/aca/emmet-ls/issues/5).

And here's my LSP setup, part of it is under my setup framework
![emmet-lsp](https://user-images.githubusercontent.com/1087399/131072353-05fcebf9-6dec-4926-a54f-15c46f20071e.png)

My autocompletion setup: [spywhere/dotfiles](https://github.com/spywhere/dotfiles/tree/main/configs/nvim/lua/plugin/autocomplete)

**Comment by spywhere** [comment]
I'll do a full test again later today. But from what I have tried so far, it's seems like working now. Feel free to close the issue if you needed. I'll get back on this later. Thanks for the fix!

**Comment by pedro757** [comment]
@spywhere I'm still facing this issue but idk if it's a `emmet-ls` problem

From the example you show `table>tr*3` I get this:

![image](https://user-images.githubusercontent.com/30637426/131201923-792f0da9-1a12-4319-9329-440021fe8bc4.png)

But those `${1}` `${2}` `${3}` are just plain text, they are not jumpable snippets, If they are not jumpable it would be better to generate the emmets empty, are you getting the same?

**Comment by hrsh7th** [comment]
It's emmet-ls side problem.

**Comment by sharksforarms** [comment]
![Peek 2021-08-28 18-06](https://user-images.githubusercontent.com/10912917/131232331-1014d68e-9386-45ee-be21-af733516d6f1.gif)

Also getting some unexpected behavior using rust-analyzer

**Comment by ericpubu** [comment]
@sharksforarms are you on the latest commit? I can't replicate this. This looks like the behavior before the fix maybe?

**Comment by hrsh7th** [comment]
The emmet-ls has a problem.

The problem is that is not set `insertTextFormat = InsertTextFormat.Snippet` to the completion items.
So you will see `${0}` as literal string.

I don't know why the server is setting `insertTextFormat` when the completion item resolved.
https://github.com/aca/emmet-ls/blob/master/src/server.ts#L121

I think it should be moved to [here](https://github.com/aca/emmet-ls/blob/master/src/server.ts#L181)

**Comment by spywhere** [comment]
Sorry for a long reply, been busy this weekend so I don't have a chance at my computer til now.

Just finish testing it, here's my result...

The selection is better but still off, as it seems to expanded the snippet then truncate to only the first line.
But once selected, it get expanded correctly.

For the issue about jumping points, mine seems fine so far.

Autocomplete suggestions
![autocomplete-unselected](https://user-images.githubusercontent.com/1087399/131243728-35f618ce-b36f-43a6-a27d-dd26516967c4.png)

Once select the suggestions
![autocomplete-selected](https://user-images.githubusercontent.com/1087399/131243743-c676c6df-5e95-426b-b473-5ea200a4a2a6.png)

And once it's expanded
![autocomplete-expanded](https://user-images.githubusercontent.com/1087399/131243748-eaf0fc8b-a718-4e86-a2f8-a1a5d6126633.png)

**Comment by pedro757** [comment]
@spywhere What did you do since the first comment? How do you solve the jumping points problem?

**Comment by spywhere** [comment]
> @spywhere What did you do since the first comment? How do you solve the jumping points problem?

I did nothing to my setup, only plugin update. You can check out my setup on the original description above.

I am using LuaSnip for the snippet engine though, if that would help...

**Comment by sharksforarms** [comment]
> @sharksforarms are you on the latest commit? I can't replicate this. This looks like the behavior before the fix maybe?

Latest rust-analyzer and latest nvim-cmp, here's a smaller example

![Peek 2021-08-29 11-30](https://user-images.githubusercontent.com/10912917/131256090-f402dc02-b9aa-4e81-9f35-1c0878810903.gif)

**Comment by hrsh7th** [comment]
@sharksforarms Reproduced. And it is nvim-cmp's bug. Thank you for your report.

This issue is very insightful to me! Thank you for all!

**Comment by hrsh7th** [comment]
I've fixed it~! Thank you~!

**Comment by sharksforarms** [comment]
Confirmed fixed!

One thing I noticed, is the first character of the snippet expanded on selection? For example, I expected the '#' to come after I select it using <CR> and it's rendered in a single chunk, instead I need to undo twice, is this intended or a bug?

![Peek 2021-08-29 12-00](https://user-images.githubusercontent.com/10912917/131257099-b5be1f05-20f8-4842-978e-86dcad25dcba.gif)

**Comment by hrsh7th** [comment]
It is a intended behavior... (In this case, I don't like this behavior but so)

**Comment by hrsh7th** [comment]
But Probably we can improve the undo point management.

**Comment by sharksforarms** [comment]
Good to know! Thanks for your work!

**Comment by spywhere** [comment]
So far I think the only thing left here is when hover the selection, text on the buffer get changed.

Take a look in this video, you'll see that the code kept changing from the original text (`table>tr*3>td*4`) to expanded one (`<table>`).

https://user-images.githubusercontent.com/1087399/131257954-14515f45-2383-429b-a577-ca446203c6af.mov

All and all, the issue is minor to me. I can live with that. Let me know if want to turn this into a new issue, so we can close this one.

**Comment by hrsh7th** [comment]
The temporary inserted text (I call it as so) is the most complex thing if we implement the LSP completion plugin in vim.

**Comment by spywhere** [comment]
I think let's close this issue, since the original request was to fix the snippet expansion is now fixed. I'll open a new one just for this temporary inserted text then. Thanks for the swift fix and reply @hrsh7th! 😄

**Comment by pedro757** [comment]
@hrsh7th look at that video, I tried and it's the same for me.

If I use the `auto-select` feature it output the plain text `${1}` `${2}` ...

But if I manually select the item it works perfect, with the jumpable points

**Comment by hrsh7th** [comment]
The emmet-ls has a problem. I can't fix it in nvim-cmp.

**Comment by pedro757** [comment]
Sorry
:'(

**Comment by pedro757** [comment]
I created a better emmet language server solving all bugs. [here is the repo](https://github.com/pedro757/emmet)
