### ISSUE TITLE
Default highlight config and ColorScheme autocmd

### ISSUE THREAD

**Issue by pschyska** [hrsh7th/nvim-cmp#972]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

d9ec57e16a13f66a4b17edd872786e2c67348752

### Minimal reproducible full config

Couldn't get it reproduced outside of my config.

### Description

Hey,
I'm using https://github.com/RRethy/nvim-base16, and set up the colorscheme like this:

```lua
local base16 = require("base16-colorscheme")
base16.setup("ocean")
```

This does not trigger the  ColorScheme autocommand, so that nvim-cmp doesn't set the right default colors.

I can trigger it manually, but the highlights are still wrong:
```lua
if vim.env.TERM ~= "linux" then
  local base16 = require("base16-colorscheme")
  base16.setup("ocean")
  -- use :colorscheme instead of setup() to trigger cmp's autocommand
  -- cmd("colorscheme base16-ocean")
  vim.api.nvim_set_hl(
    0, "TermCursorNC", {fg = base16.colors.base00, bg = base16.colors.base00}
  )

  vim.api.nvim_set_hl(0, "CmpItemKind", {fg = base16.colors.base09})
end
-- re-trigger ColorScheme
local autocmd = require("cmp.utils.autocmd")
autocmd.emit("ColorScheme")
```

```
:hi CmpItemMenuDefault
CmpItemMenuDefault xxx cterm= gui= guifg=#000000
```
It should be:
```
CmpItemMenuDefault xxx guifg=#c0c5ce
```

I think that happens because `highlight.inherit('CmpItemMenuDefault', 'Pmenu', { bg = 'NONE', default = true })` is used. The default=true leading to CmpItemMenuDefault never getting updated.
Shouldn't CmpItemMenuDefault be default=false, and just `vim.api.nvim_set_hl(0, 'CmpItemMenu', { link = 'CmpItemMenuDefault', default = true })` be default=true? I.e. when the user manually updates CmpItemMenu, the highlight hook shouldn't overwrite that, but when the user changes the colorscheme, CmpItemMenu**Default** should be updated.
I resorted to monkey-patching the highlight function for now:

```lua
local highlight = require("cmp.utils.highlight")

highlight.keys = {
  "fg", "bg", "bold", "italic", "reverse", "standout", "underline", "undercurl",
  "strikethrough",
}

highlight.inherit = function(name, source, settings)
  for _, key in ipairs(highlight.keys) do
    if not settings[key] then
      local v = vim.fn.synIDattr(vim.fn.hlID(source), key)
      if key == "fg" or key == "bg" then
        local n = tonumber(v, 10)
        v = type(n) == "number" and n or v
      else
        v = v == 1
      end
      settings[key] = v == "" and "NONE" or v
    end
  end
  -- added, will never update on colorscheme otherwise
  settings.default = nil
  vim.api.nvim_set_hl(0, name, settings)
end
-- re-trigger ColorScheme
local autocmd = require("cmp.utils.autocmd")
autocmd.emit("ColorScheme")

local cmp = require("cmp")
[... my normal cmp config ...]
```

### Steps to reproduce

see above

### Expected behavior

CmpItemMenuDefault xxx guifg=#c0c5ce

### Actual behavior

CmpItemMenuDefault xxx cterm= gui= guifg=#000000

**Comment by hrsh7th** [comment]
@pschyska I think you're right. Thank you! Could you test latest nvim-cmp?

**Comment by pschyska** [comment]
@hrsh7th Thank you, seems to work without my workaround now!
