### ISSUE TITLE
Holding down ctrl+n/ctrl+p for too long will trigger completion

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-cmp#973]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.8.0

### Minimal reproducible full config

should be reproducible with the provided config. Just open up a css file (since the lsp is setup for it) and hold down `ctrl+n`

### Description

Holding down the ctrt+n/p keys in order scroll quickly through the popup will trigger an unwanted completion.

### Steps to reproduce

hold ctrl+n/p while in the popup menu

### Expected behavior

it just scrolls without unwanted completion

### Actual behavior

Holding down the ctrt+n/p keys in order scroll quickly through the popup will trigger an unwanted completion.

### Additional context

I also have `xset r rate 210 40` set to speed up my keys, I think this is what is causing the issue, but I would still like to scroll this fast without an unwanted completion.

**Comment by Shougo** [comment]
@ChristianChiarulli Please upload your mapping config.  I will test it.

**Comment by Shougo** [comment]
> should be reproducible with the provided config. Just open up a css file (since the lsp is setup for it) and hold down ctrl+n

Please upload the reproduce-able example.  I cannot test it.

**Comment by Shougo** [comment]
I have tested it with `pylsp`, but I cannot reproduce it.

**Comment by co0lster** [comment]
I have the same problem. 
I used config from this repo https://github.com/bkegley/dotfiles
