### ISSUE TITLE
I keep getting a `loop or previous error loadin module` when trying to run neovim-cmp

### ISSUE THREAD

**Issue by bab014** [hrsh7th/nvim-cmp#981]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.6.3

### Minimal reproducible full config

Error detected while processing /home/bab14/.config/nvim/init.vim:
line   44:
E5108: Error executing lua /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/utils/autocmd.lua:5: attempt to call
 field 'nvim_create_augroup' (a nil value)
stack traceback:
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/utils/autocmd.lua:5: in main chunk
        [C]: in function 'require'
        ...d/vim-plug/nvim-cmp/lua/cmp/view/custom_entries_view.lua:2: in main chunk
        [C]: in function 'require'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/view.lua:6: in main chunk
        [C]: in function 'require'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/core.lua:10: in main chunk
        [C]: in function 'require'
        /tmp/plugged/vim-plug/nvim-cmp/lua/cmp/init.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing /tmp/plugged/vim-plug/nvim-cmp/plugin/cmp.lua:
E5113: Error while calling lua chunk: /tmp/plugged/vim-plug/nvim-cmp/plugin/cmp.lua:9: loop or previou
s error loading module 'cmp.utils.autocmd'
stack traceback:
        [C]: in function 'require'
        /tmp/plugged/vim-plug/nvim-cmp/plugin/cmp.lua:9: in main chunk
Error detected while processing /home/bab14/.local/share/nvim/site/pack/packer/start/cmp-buffer/after/
plugin/cmp_buffer.lua:

### Description

So while using Packer I installed nvim-cmp and it installed without issue. But everytime I go to open any file I get a loop error saying there's no 'cmp' module. I've scoured the internet and didn;t want to have to post an issue but at this point I don't know what else to do.

It seems like it's importing from the wrong file.

### Steps to reproduce

I'm not sure how to reproduce, I also used the provided .vimrc file as my init.vim and I got basically the same issue. 

### Expected behavior

I'd expect to not receive an error

### Actual behavior

I can't use nvim-cmp

**Comment by hrsh7th** [comment]
Please update neovim to latest stable

**Comment by bab014** [comment]
Thank you, getting some other weird warnings while using it, but seems to be working,

**Comment by bab014** [comment]
This is what I get now
```lua
Error executing vim.schedule lua callback: ...te/pack/packer/start/nvim-cmp/lua/cmp/view/docs_view.lua
:38: bad argument #1 to 'min' (number expected, got nil)
stack traceback:
        [C]: in function 'min'
        ...te/pack/packer/start/nvim-cmp/lua/cmp/view/docs_view.lua:38: in function 'open'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/view.lua:229: in function 'callback'
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:95: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/17698

The function is added in neovim 0.7.  I think `nvim-cmp` should check neovim version.

**Comment by acidghost** [comment]
As @FilBot3 mentions, Fedora 35 still ships neovim 0.6.1 and this plugin is totally unusable.

@hrsh7th I understand that keeping this plugin retro-compatible with older versions of neovim has lots of drawbacks, but providing at least a tag or a commit users stuck with older neovim versions could use would be really nice. Shouldn't really take much from the dev's POV, but users will have to `git-bisect` or something.

**Comment by FilBot3** [comment]
> As @FilBot3 mentions, Fedora 35 still ships neovim 0.6.1 and this plugin is totally unusable.
> 
> @hrsh7th I understand that keeping this plugin retro-compatible with older versions of neovim has lots of drawbacks, but providing at least a tag or a commit users stuck with older neovim versions could use would be really nice. Shouldn't really take much from the dev's POV, but users will have to `git-bisect` or something.

I've also upgraded to Fedora 36 Silverblue, so this isn't a concern for me anymore, but having release Tags would allow those who need to stay on a certain version to do that.

**Comment by bab014** [comment]
Upgrading to 0.7.0 fixed this for me, as outlined.

**Comment by acidghost** [comment]
Yes, but not everyone can upgrade, as outlined..

**Comment by Shougo** [comment]
You can build neovim from source code.

**Comment by acidghost** [comment]
Sure. Do I want to? No. I would daily drive Gentoo otherwise.

I already found my solution (https://github.com/acidghost/dotfiles/commit/2b73f2488674b01ea624b699484b96d5181da60f), but is making a git tag so hard?
