### ISSUE TITLE
Add copilot icon

### ISSUE THREAD

**Issue by RakerZh** [hrsh7th/nvim-cmp#985]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/76530956/168186897-50852718-9d9a-4538-aa4d-c1aef35026b1.png">

**Comment by Shougo** [comment]
It seems feature request for copilot source.

**Comment by zbirenbaum** [comment]
@Shougo I'm the author of copilot.lua and copilot_cmp, I would like to second this request. Currently, I set the kind variable to 15 which corresponds to 'snippet'. There's no way to denote that a completion comes from the copilot source I wrote.

I think a better form of this request would be to allow for adding id's corresponding to custom completion kinds. I'd be willing to PR that if that sounds acceptable to you.

**Comment by Shougo** [comment]
Hm...  The kind is fixed in nvim-cmp?  If so, it is the feature request in nvim-cmp.

Note:  It should be described in the first though.

**Comment by Shougo** [comment]
> Since there isn't an official source for it, I think a better form of this request would be to allow for adding id numbers and strings corresponding to custom completion kinds. I'd be willing to PR that if that sounds acceptable to you.

The PR is small and it does not breaks other features and sources, it seems better solution.

**Comment by zbirenbaum** [comment]
> > Since there isn't an official source for it, I think a better form of this request would be to allow for adding id numbers and strings corresponding to custom completion kinds. I'd be willing to PR that if that sounds acceptable to you.
> 
> The PR is small and it does not breaks other features and sources, it seems better solution.

I'm very sorry Shougo, I was reading the updates on cmdheight=0 while responding to this issue post and typed your name instead of @hrsh7th on accident!
