### ISSUE TITLE
`vim_item.kind` missing in `formatting.format` function

### ISSUE THREAD

**Issue by YinAqu** [hrsh7th/nvim-cmp#987]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7

### Minimal reproducible full config
```
  formatting = {
    fields = { "kind", "abbr", "menu" },
    format = function(entry, vim_item)
      -- Note: here always print nil
      print(vim_item.kind)
      vim_item.kind = string.format("%s", kind_icons[vim_item.kind])
      return vim_item
    end
  },
```

### Description

`vim_item.kind` missing in `formatting.format` function, don't know if it is on purpose. 
This issue is introduced by commit `0318a3cbc1dc3fad7681ae33ca580da067f23f3b`

### Steps to reproduce

see Description

### Expected behavior

see Description

### Actual behavior

see Description

**Comment by madt1m** [comment]
Following this. 
![image](https://user-images.githubusercontent.com/25264901/168272644-460aeaa0-6caf-414c-b304-a3785d8f1e92.png)
Inspecting the `vim_item` table shows that no `kind` or kind-like type is present there.

**Comment by saurabhchardereal** [comment]
Reverting commit https://github.com/hrsh7th/nvim-cmp/commit/0318a3cbc1dc3fad7681ae33ca580da067f23f3b to get around this.

**Comment by ecosse3** [comment]
Same issue here:

![image](https://user-images.githubusercontent.com/17691791/168273789-7b3dd519-bf62-49c3-9f8a-a4dfee92eec5.png)

**Comment by hrsh7th** [comment]
Thank you for reporting!
