### ISSUE TITLE
nvim-cmp dies after completing methods in js if you hit `(` after method name

### ISSUE THREAD

**Issue by gozes** [hrsh7th/nvim-cmp#994]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

0.7

### Minimal reproducible full config

n/a

### Description

<img width="1792" alt="Screenshot 2022-05-17 at 10 04 48" src="https://user-images.githubusercontent.com/632922/168774869-81dcfc41-3560-4dc5-b514-a46cad0891a3.png">
if you try to complete on a js file and hit `(` after completing the method name. you will get the above error which will kill `nvim-cmp` with no way of recovering other than restarting neovim. Its worth pointing out that the error says something about snippets but I don't use or have installed anything related to snippets so I 'm not sure why is going down that code path 

### Steps to reproduce

open a js file and import lodash like `const _ = require('lodash');` the do `_.isEmpty` when the method is highlighted press `(` this will cause the error above

### Expected behavior

I expected nvim-cmp to not throw an error and continue working as normal

### Actual behavior

nvim-cmp dies with no way to recover to the point the I have restart nvim to get nvim-cmp working again

**Comment by hrsh7th** [comment]
You should set up some snippet engine.

**Comment by Shougo** [comment]
The LSP uses snippet.
