### ISSUE TITLE
The items inside popup menu are mis-indented

### ISSUE THREAD

**Issue by AstroShen** [hrsh7th/nvim-cmp#999]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

```vim

```

### Description

For example, I enter `cout`, the popup menu looks like this:
    cout     variable [lsp]
 cout   snippet [luasnip]
The first item is more indented than the second item, whick looks uncomfortable.

### Steps to reproduce

When popup menu are activated and more than one items are in the popup menu.

### Expected behavior

The items inside popup menu are correctly indented.

### Actual behavior

The popup menu looks like this:
    cout     variable [lsp]
 cout   snippet [luasnip]

**Comment by Shougo** [comment]
Hm...  It is hard to understand.  Can you upload the screenshot?

**Comment by hrsh7th** [comment]
It's caused by clandg.

**Comment by hrsh7th** [comment]
Sorry. I don't know how to acoid tjis with clang...(I don't write c family...

**Comment by AstroShen** [comment]
> Sorry. I don't know how to acoid tjis with clang...(I don't write c family...

I just solved this, clangd have an option `--header-insertion-decorators` to identify items which will be potentially requiring a header file. For example, cout is declared in <iostream> header file, so before using cout `#include <iostream>` must be added. Clangd allows users to use function&variable&class without include required headers, because clangd will automatically include missing headers, and those items are tagged which may insert header file. 
Set the option --header-insertion-decorators=false will work.

Just for those who have the same issue. Maybe adding another layer in nvim-cmp to format the items? Maybe unecessary i guess.

**Comment by YongzeYao** [comment]
But how do I set clangd option? I have no idea how to do that... Could anyone please post their steps to set this option? Thank you!
